"""Parole con cui riconoscere, nel catalogo di un quartiere, il luogo che un pin nativo indica.

Il pin dice che cosa c'è (una libreria, un bagno pubblico, un jazz club); il catalogo della guida
dice quale luogo di quel quartiere è. Il collegamento si fa cercando, fra i luoghi del quartiere,
quello il cui nome o la cui chiave contiene una di queste parole — e vale **solo se ne trova
esattamente uno**. Dove il quartiere ne ha due, o nessuno, il pin resta senza luogo collegato: ha
comunque il suo tipo e la sua etichetta.
"""

PAROLE = {
    'アイコン：自販機': ['distributore'],
    'アイコン：宝くじ': ['lotteria'],
    'アイコン：バイト情報': ['lavoro', 'bacheca'],
    'アイコン：ジューサーバー': ['succhi', 'juice'],
    'アイコン：キヨスク': ['chiosco', 'kiosk'],
    'アイコン：本屋': ['libreria'],
    'アイコン：レンタルDVD': ['videonoleggio', 'noleggio'],
    'アイコン：ファミレス': ['diner'],
    'アイコン：牛丼': ['gyudon', 'beko'],
    'アイコン：ミリタリーショップ': ['untouchable', 'softair'],
    'アイコン：ゲーセン': ['sala giochi'],
    'アイコン：コンビニ': ['minimarket', 'convenience', 'triple seven'],
    'アイコン：ジム': ['palestra'],
    'アイコン：ビックバンバーガー': ['big bang'],
    'アイコン：ドラッグストア': ['farmacia'],
    'アイコン：ドンキ': ['discount', 'rocinante'],
    'アイコン：映画館': ['cinema'],
    'アイコン：花屋': ['fiorista', 'rafflesia'],
    'アイコン：スーパー': ['super', 'supermercato'],
    'アイコン：スポーツ用品': ['sport'],
    'アイコン：和風雑貨': ['tradizional'],
    'アイコン：宝石店': ['gioieller'],
    'アイコン：アクセサリー': ['accessor'],
    'アイコン：コスメ': ['cosmetic', 'body chop'],
    'アイコン：パン屋': ['panetteria', 'panificio'],
    'アイコン：トイレ': ['servizi igienici'],
    'アイコン：教室': ['aula'],
    'アイコン：囚人高校': ['shujin', 'scuola'],
    'アイコン：バー': ['crossroads', 'bar '],
    'アイコン：雑貨屋': ['casalinghi'],
    'アイコン：レトロゲーム': ['retrogaming', 'super baron'],
    'アイコン：メイドカフェ': ['maid'],
    'アイコン：カチャガチャ': ['capsule', 'gachapon'],
    'アイコン：家電量販店': ['akindo', 'megastore'],
    'アイコン：グッズショップ': ['otaku', 'tokobushiya'],
    'アイコン：工具店': ['ferramenta', 'utensil'],
    'アイコン：銭湯': ['bagno pubblico', 'terme'],
    'アイコン：ルブラン': ['leblanc'],
    'アイコン：コインランドリー': ['lavanderia'],
    'アイコン：バッティング': ['battuta', 'batting'],
    'アイコン：リサイクルショップ': ['usati', 'yumenoshima'],
    'アイコン：診療所': ['clinica'],
    'アイコン：文房具': ['cartoleria'],
    'アイコン：古着屋': ['abiti usati', 'vestiti usati'],
    'アイコン：お寺': ['tempio'],
    'アイコン：ジャズクラブ': ['jazz'],
    'アイコン：パワーストーン': ['cristalloterapia', 'stoneon'],
    'アイコン：ダーツ': ['freccette', 'penguin sniper'],
    'アイコン：お香': ['mantra', 'incens'],
    'アイコン：揚げ物屋': ['friggitoria', 'hagoromo'],
    'スーパー（小）': ['super', 'supermercato'],
}
