[msg MSG_DUMMY]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_YAMANO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Questo posto 因 stato in costruzione[n]per un anno intero.[n][w][e]

[msg MSG_LAST_GREETING_KIOSUK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Avevi fretta di comprare[n]qualcosa? Raggiungiamo gli altri.[n][w][e]

[msg MSG_LAST_GREETING_HIKARI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non conosci nessuno che[n]andrebbe qui, vero? Andiamo[n]da qualche altra parte.[n][w][e]

[msg MSG_LAST_GREETING_JUICEB [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Non c'因 tempo per l'aojiru.[n]Andiamo a trovare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_ADJUST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Il tuo abbonamento 因 quasi[n]scaduto, ma immagino che non[n]te ne servir稲 uno nuovo...[n][w][e]

[msg MSG_LAST_GREETING_PHOTO_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1099 65535 0]Ci sono ricordi che non puoi[n]racchiudere in un'immagine. Andiamo[n]dagli altri, per l'ultima volta.[n][w][e]

[msg MSG_LAST_GREETING_NEXT_J [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_BAITO_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Dovremmo andare a salutare anche[n]le persone per cui hai lavorato.[n][w][e]

[msg MSG_LAST_GREETING_BAITO__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Ehi, domani partirai.[n]Non devi lavorare, ricordi?[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MND_0103]
[s]Non devo fare niente qui...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_YAMANOTE_PARK_BUTTON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sembra che l'area sia[n]chiusa per dei lavori.[n]Troviamo un'altra uscita.[n][w][e]

[msg MSG_YAMANOTE_PARK_BUTTON_2]
[s]La zona pi迂 avanti 因 chiusa[n]per dei lavori...[n][w][e]

[msg MSG_GOTO_Kichijoji [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]La linea Inogami 因 laggi迂. Vuoi[n]pagare 200 yen per andare[n]a Kichijoji?[n][w][e]

[sel SEL_GOTO_Kichijoji top]
[s]Buona idea.[e]
[s]Meglio di no.[e]

[msg MSG_GOTO_Kichijoji_NoMon [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]...Si direbbe che tu non[n]abbia abbastanza soldi.[n][w][e]

[msg MSG_GOTO_INOKASIRA_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Qui non hai niente da fare,[n]vero? Andiamo[n]da un'altra parte![n][w][e]

[msg MND_GOTO_INOKASIRA_NG]
[s]Non devo fare niente l淫.[n]Meglio tornare indietro...[n][w][e]

[msg MND_GATE_0103]
[s]Andiamo da un'altra parte...[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Vuoi spostarti in[n]un'altra zona?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]S淫, andiamo.[e]
[s]No, non ancora.[e]

[msg MSG_SCHOOL_1STDAY]
[s]Se non ricordo male, la[n][clr 2]linea Ginza[clr 27] dovrebbe portarmi[n]ad Aoyama-Itchome, dov'因 la scuola...[n][w][e]

[msg MSG_NG_CENTER]
[s]Da qui si arriva a Central Street,[n]ma al momento non abbiamo[n]nulla da fare, laggi迂...[n][w][e]

[msg MSG_BAITO_MAGAZINE_NOTOP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Una rivista con informazioni[n]sui lavori part-time, eh? Pi迂[n]avanti potrebbe servirti.[n][w][e]

[msg MSG_BAITO_MAGAZINE_NOTOP_2]
[s]為 una rivista informativa sui[n]lavori part-time. Di tanto[n]in tanto dovrei consultarla...[n][w][e]

[msg KIOSUKU01_NOTOPEN]
[s]Questo posto vende prodotti[n]per i pendolari.[n][w][e]
[s]Potrei comprarci qualcosa,[n]una volta presa dimestichezza[n]con il tragitto verso la scuola...[n][w][e]

[msg KIOSUKU01_SELECT [Commessa del chiosco]]
[s][f 4 23 1 4 3 5 65534 0][vp 8 2 1 0 4 0]Ehi, benvenuto. Compra[n]pure quello che ti serve.[n][w][e]

[msg KIOSUKU01_THANKS [Commessa del chiosco]]
[s][vp 8 2 1 0 4 0]Va bene, grazie.[n][w][e]

[msg KIOSUKU01_NOT_BUY [Commessa del chiosco]]
[s][vp 8 2 1 0 4 0]Va bene. Torna presto.[n][w][e]

[msg MSG_HikarieWayNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Questo sottopassaggio 因[n]lunghissimo. Torniamo indietro,[n]prima di perderci.[n][w][e]

[msg MND_HikarieWayNG]
[s]Non devo fare niente l淫.[n]Meglio tornare indietro...[n][w][e]

[msg MSG_ADJUSTMENT_MACHINE_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Avendo la tessera da viaggio[n]non devi usare la[n]biglietteria automatica, giusto?[n][w][e]

[msg MSG_ADJUSTMENT_MACHINE]
[s]Non ho bisogno di[n]adeguarmi alla tariffa...[n][w][e]

[msg MSG_PHOTO_MACHINE_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Ci sono tante opzioni per[n]far sembrare pi迂 belle le[n]persone nelle foto, ma...[n][w][e]
[s]為 una macchina per le[n]fototessere, giusto? Queste foto[n]non andrebbero manipolate...[n][w][e]

[msg MSG_PHOTO_MACHINE]
[s]為 una macchina per[n]scattare fototessere.[n][w][e]
[s]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MSG_NextJuice_KFEVT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Per caso hai sete?[n]Ehi, sicuro di avere[n]tempo per questo?[n][w][e]

[msg MND_NextJuice_KFEVT]
[s]Al momento non ho sete...[n][w][e]

[msg MND_NextJuice_NotOpen]
[s]為 un distributore automatico[n]con un display.[n][w][e]
[s]Al momento non ho sete...[n][w][e]

[msg MSG_NextJuice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Un distributore automatico,[n]eh? Le cose in vendita non[n]sono niente di speciale, per韻.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MND_NoInfoBaitoMagazine]
[s]Riviste gratuite con annunci[n]di lavoro part-time...[n][w][e]
[s]Sembrano fatte per i liceali...[n][w][e]

[msg MSG_NoInfoBaitoMagazine [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Riviste di annunci di lavoro[n]part-time. Cos淫 tante informazioni,[n]completamente gratis. Incredibile.[n][w][e]
[s][f 4 10 65535 0 0]Ma sembra non ci sia niente di[n]adatto ai liceali.[n]Controlliamo altre riviste.[n][w][e]

[msg MND_E14410100_NG_HIROBA_]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MND_E10920100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Se salgo su questo treno[n]far韻 tardi...[n][w][e]
[s][vp 8 2 65535 0 0 0]Devo prendere la[n][clr 2]linea Ginza[clr 27] a Shibuya...[n][w][e]

[msg MND_E12710100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Se salgo su questo treno[n]far韻 tardi...[n][w][e]
[s][vp 8 2 65535 0 0 0]Sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MND_E65010100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Per andare a Kichijoji devo prendere la linea Inogami...[n][w][e]

[msg MND_E14410100_NG_YAMANOT]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MND_E10920100_CHK_KIOSUK]
[s][vp 8 2 65535 0 0 0]C'因 tantissima merce di vario[n]tipo esposta...[n][w][e]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo[n]di mettermi a scegliere qualcosa...[n][w][e]

[msg MND_E12710100_CHK_KIOSUK]
[s][vp 8 2 65535 0 0 0]C'因 tantissima merce di vario[n]tipo esposta...[n][w][e]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo[n]di mettermi a scegliere qualcosa...[n][w][e]

[msg MES_E650102000_CHK_KIOSU [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]I negozi come questo sono piccoli,[n]ma hanno tante cose interessanti.[n][w][e]

[msg MES_E650102000_CHK_KIOSU_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Sul giornale di domani potrebbero[n]dire qualcosa di Madarame.[n][w][e]

[msg MND_COMMON_CHK_KIOSUKU_0]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]fare shopping...[n][w][e]

[msg MND_E10920100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Ci sono tantissime riviste[n]piene di annunci di[n]lavoro part-time.[n][w][e]
[s][vp 8 2 65535 0 0 0]Chiss稲 che tipo di lavori potrei[n]trovare da queste parti...[n][w][e]

[msg MND_E12710100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Ci sono tantissime riviste[n]piene di annunci di[n]lavoro part-time.[n][w][e]
[s][vp 8 2 65535 0 0 0]Chiss稲 che tipo di lavori potrei[n]trovare da queste parti...[n][w][e]

[msg MND_E14410100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MES_E650102000_CHK_BAITO [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]Un lavoro part-time, eh... Sono[n]un po' a corto di soldi. Forse[n]dovrei cercarne uno anch'io.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Per adesso, andiamo a Kichijoji![n][w][e]

[msg MES_E650102000_CHK_BAITO_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Queste riviste con annunci[n]per part-time sono gratuite,[n]vero? Chi le produce?[n][w][e]

[msg MND_COMMON_CHK_BAITO_MAG]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]cercare lavori part-time...[n][w][e]

[msg MND_E10920100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Appena pi迂 avanti sembra esserci[n]un centro commerciale sotterraneo.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Appena pi迂 avanti sembra esserci[n]un centro commerciale sotterraneo.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora dovrei sbrigarmi[n]e filare dritto a scuola...[n][w][e]

[msg MND_E14410100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MSG_E18010300_NG_SIBUTIK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]S淫, di l稲 ci sono dei negozi...[n]Ma quei posti si limitano[n]a vendere, giusto?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Dobbiamo trovare un posto[n]che acquisti da noi...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Oh, s淫! Quel negozio di armi[n]acquista oggetti, vero?[n]Proviamo![n][w][e]

[msg MND_E65010100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Inogami[clr 27]...[n][w][e]

[msg MND_E10920100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]La strada pi迂 avanti sembra[n]portare a Central Street.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora sar稲 meglio raggiungere[n]in fretta la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]La strada pi迂 avanti sembra[n]portare a Central Street.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora dovrei sbrigarmi[n]e filare dritto a scuola...[n][w][e]

[msg MND_E14410100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]Non pu韻 essere lontana.[n]Prover韻 a cercare qui intorno...[n][w][e]

[msg MSG_E18010300_NG_CENTER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]Qui in giro ci sono negozi[n]che acquisteranno qualcosa[n]da noi?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Oh, s淫! Quel negozio di armi[n]acquista oggetti, vero?[n]Proviamo![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]Proviamo![n][w][e]

[msg MND_E10920100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Questo negozio vende[n]succo appena spremuto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Quando avr韻 un po' di tempo[n]lo prover韻...[n][w][e]

[msg MND_E12710100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Questo negozio vende[n]succo appena spremuto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Quando avr韻 un po' di tempo[n]lo prover韻...[n][w][e]

[msg MND_E14410100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_JUICEBAR_]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]acquistare del succo...[n][w][e]

[msg MND_E10920100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Questo sembra un manjuu shop.[n][w][e]
[s][vp 8 2 65535 0 0 0]Qui vendono diverse variet稲[n]di manjuu e daifuku...[n][w][e]

[msg MND_E12710100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Questo sembra un manjuu shop.[n][w][e]
[s][vp 8 2 65535 0 0 0]Qui vendono diverse variet稲[n]di manjuu e daifuku...[n][w][e]

[msg MND_E14410100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]raggiungere Ann...[n][w][e]

[msg MND_COMMON_CHK_OMIYAGE_S]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]fare shopping...[n][w][e]

[msg MND_E10920100_NG_GATE_HI]
[s][vp 8 2 65535 0 0 0]Devo prendere la[n][clr 2]linea Ginza[clr 27] a Shibuya...[n]Meglio raggiungere la banchina.[n][w][e]

[msg MND_E12710100_NG_GATE_HI]
[s][vp 8 2 65535 0 0 0]Non ho tempo di tornare[n]indietro. Meglio prendere la[n][clr 2]linea Ginza[clr 27] e andare a scuola...[n][w][e]

[msg MND_E14410100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Non pu韻 essere lontana.[n]Prover韻 a cercare qui intorno...[n][w][e]

[msg MND_E65010100_NG_DENENTO_2]
[s][vp 8 2 65535 0 0 0]Per andare a Kichijoji[n]devo prendere la linea Inogami...[n][w][e]

[msg MND_E12710100_NG_GATE_IN]
[s][vp 8 2 65535 0 0 0]Non ho tempo di tornare[n]indietro. Meglio prendere la[n][clr 2]linea Ginza[clr 27] e andare a scuola...[n][w][e]

[msg MND_E10920100_NG_GATEOUT]
[s][vp 8 2 65535 0 0 0]Devo prendere la[n][clr 2]linea Ginza[clr 27], ma credo di[n]essere dalla parte sbagliata.[n][w][e]

[msg MND_E14410100_NG_TOKYU_0]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MND_E10920100_GOTO_INOKA]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_GOTO_INOKA]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MSG_E65010300_OPEN_KICHI [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 7080 65535 0]Queste scale portano alla[n]linea Inogami. Siamo sulla[n]strada giusta per Kichijoji.[n][w][e]

[msg MSG_E65010300_OPEN_KICHI_2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Che emozione![n][w][e]

[msg MSG_E65010300_OPEN_KICHI_3 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 7052 65535 0]Forza, andiamo![n][w][e]

[msg MSG_E65010300_OPEN_KICHI_4 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 2100 65535 0]Quei due...[n][w][e]

[msg MSG_SPOT_OPEN_KICHIJOJI]
[s]Ora puoi andare a [clr 2]Kichijoji[clr 27].[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Dunque, siamo diretti verso un'area[n]non coperta dal tuo abbonamento,[n]quindi dovrai pagare il biglietto.[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Ehi... Non dirmi che sei a corto[n]di soldi?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]D'accordo, questa volta pago io con[n]un po' della mia riserva segreta,[n]ma dalla prossima 因 affar tuo.[n][w][e]

[msg MND_NG_GOTO_INOKASIRA_06 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Ehi, non di l稲![n]Non girovagare a caso,[n]OK?[n][w][e]

[msg MND_COMMON_GOTO_INOKASIR]
[s][vp 8 2 65535 0 0 0]Non devo fare niente l淫.[n]Meglio tornare indietro...[n][w][e]

[msg MND_E10920100_CHK_ADJUST]
[s][vp 8 2 65535 0 0 0]為 una macchina per calcolare[n]il prezzo del biglietto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora non ho bisogno[n]di usarla...[n][w][e]

[msg MND_E12710100_CHK_ADJUST]
[s][vp 8 2 65535 0 0 0]為 una macchina per calcolare[n]il prezzo del biglietto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora non ho bisogno[n]di usarla...[n][w][e]

[msg MND_COMMON_CHK_ADJUSTMEN]
[s][vp 8 2 65535 0 0 0]為 una macchina per calcolare[n]il prezzo del biglietto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora non ho bisogno[n]di usarla...[n][w][e]

[msg MND_E10920100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]為 una macchina per[n]scattare fototessere.[n][w][e]
[s][vp 8 2 65535 0 0 0]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MND_E12710100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]為 una macchina per[n]scattare fototessere.[n][w][e]
[s][vp 8 2 65535 0 0 0]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MND_E14410100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_PHOTO_MAC]
[s][vp 8 2 65535 0 0 0]為 una macchina per[n]scattare fototessere.[n][w][e]
[s][vp 8 2 65535 0 0 0]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MND_E10920100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Vedo pochissime chiavi negli[n]armadietti. La maggior parte 因[n]gi稲 usata da altre persone...[n][w][e]

[msg MND_E12710100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Vedo pochissime chiavi negli[n]armadietti. La maggior parte 因[n]gi稲 usata da altre persone...[n][w][e]

[msg MND_E14410100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_COIN_LOCK]
[s][vp 8 2 65535 0 0 0]Vedo pochissime chiavi negli[n]armadietti. La maggior parte 因[n]gi稲 usata da altre persone...[n][w][e]

[msg MND_E10920100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Sullo schermo 因 mostrata[n]l'immagine di un prodotto.[n][w][e]
[s][vp 8 2 65535 0 0 0]為 touch screen, per comprare[n]gli oggetti mostrati basta[n]toccarli...[n][w][e]

[msg MND_E12710100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Sullo schermo 因 mostrata[n]l'immagine di un prodotto.[n][w][e]
[s][vp 8 2 65535 0 0 0]為 touch screen, per comprare[n]gli oggetti mostrati basta[n]toccarli...[n][w][e]

[msg MND_E14410100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_NEXT_JUIC]
[s][vp 8 2 65535 0 0 0]Ora non ho tempo di[n]fermarmi per comprare da bere...[n][w][e]

[msg MND_E10920100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Questo distributore automatico[n]vende frutta.[n][w][e]
[s][vp 8 2 65535 0 0 0]Ce n'因 di diverso tipo,[n]tutta imbustata in file...[n][w][e]

[msg MND_E12710100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Questo distributore automatico[n]vende frutta.[n][w][e]
[s][vp 8 2 65535 0 0 0]Ce n'因 di diverso tipo,[n]tutta imbustata in file...[n][w][e]

[msg MND_E14410100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_FRUIT_MAC]
[s][vp 8 2 65535 0 0 0]Penso che la frutta la comprer韻[n]un'altra volta...[n][w][e]

[msg MSG_SPOT_GO_YAMANOTE]
[s]Dovrei prendere la[n][clr 6]linea Yamanote[clr 0]...[n][w][e]

[msg MSG_SPOT_GO_INOKASIRA]
[s]Dovrei prendere la[n][clr 6]linea Inokashira[clr 0]...[n][w][e]

[msg MSG_SPOT_GO_GINZALINE]
[s]Dovrei prendere la[n][clr 6]linea Ginza[clr 0]...[n][w][e]

[msg SPOT_GO_INOKASIRA_RYUJI [Ryuji]]
[s]OK, andiamo al[n]Parco Inokashira![n][w][e]

[msg MSG_BAITO_MAGAZINE_SPOT]
[s]Qui ci sono delle riviste di[n]annunci di lavoro part-time...[n][w][e]
[s]Per韻 adesso non ho tempo[n]di leggerle...[n][w][e]

[msg MSG_SPOT_KIOSUKU_RYUJI [Ryuji]]
[s]Oh, guarda questo giornale.[n]Parla della Shujin.[n][w][e]
[s]Per韻 hanno rigirato tutto[n]in un modo assurdo. Ecco perch姻[n]non mi fido dei mass media...[n][w][e]

[msg MSG_SPOT_KIOSUKU_ANNE [Ann]]
[s]Quella rivista...[n]"Attrice famosissima sospettata[n]di chirurgia plastica"?!?[n][w][e]
[s]Cosaaa? Mi piace tanto.[n]Aspetto e capacit稲 di recitazione[n]sono due cose diverse...[n][w][e]

[msg MSG_SPOT_KIOSUKU_YUSUKE [Yusuke]]
[s]Quel giornale...[n][w][e]
[s]"Il grande pittore[n]caduto dal paradiso[n]all'inferno." Oh...[n][w][e]
[s]Umpf. Perch姻 scomodarsi a scrivere[n]un articolo di cos淫 bassa lega?[n][w][e]

[msg MSG_SPOT_KIOSUKU_MAKOTO [Makoto]]
[s]*Messaggio per Makoto[n][w][e]

[msg MSG_SPOT_JUICEBAR_RYUJI [Ryuji]]
[s]Aspetta, hai sete?[n][w][e]
[s]Qui c'因 tanta scelta,[n]ma finisco sempre per[n]scegliere la stessa cosa.[n][w][e]

[msg MSG_SPOT_JUICEBAR_ANNE [Ann]]
[s]Aspetta! Vuoi offrirmi[n]qualcosa?[n][w][e]
[s]Scherzo, scherzo.[n]Ti sto solo punzecchiando.[n][w][e]

[msg MSG_SPOT_JUICEBAR_YUSUKE [Yusuke]]
[s]Ci sono tanti frutti diversi,[n]ma tra tutti...[n][w][e]
[s]Prediligo il kiwi.[n][w][e]
[s]Gradisco anche i fichi, ma...[n]No, non resisto ai kiwi.[n][w][e]

[msg MSG_SPOT_JUICEBAR_MAKOTO [Makoto]]
[s]*Messaggio per Makoto[n][w][e]

