[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_DUMMY]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_DRUGST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Le medicine di Takemi[n]funzionano meglio di[n]qualunque altra.[n][w][e]

[msg MSG_LAST_GREETING_DRUGST_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Ormai a cosa ti servono i[n]prodotti di uso quotidiano?[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_KARAOK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Quando cercavamo Kaneshiro[n]siamo andati tutti al[n]karaoke, vero?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mi mancano quei momenti...[n]Torniamoci ancora.[n][w][e]

[msg MSG_LAST_GREETING_BEEFDO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Quando lavoravi qui hai[n]incontrato Yoshida, vero?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Era un lavoro faticoso. Altre[n]persone non avrebbero retto.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Il proprietario, per韻... ha[n]sempre mantenuto la calma.[n][w][e]

[msg MSG_LAST_GREETING_BEEFDO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Qui sei venuto a mangiare con[n]Ryuji, vero? Dopo un anno, 因[n]sempre il solito Ryuji.[n][w][e]

[msg MSG_LAST_GREETING_FAMILY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Quando Yusuke si 因 unito ai[n]Ladri Fantasma siamo venuti qui.[n][w][e]
[s][f 4 10 65535 0 0]E qui siamo venuti con Sumire,[n]ma anche in altre occasioni. 為[n]una sorta di ritrovo secondario.[n][w][e]

[msg MSG_LAST_GREETING_FAMILY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Quando Yusuke si 因 unito ai[n]Ladri Fantasma siamo venuti qui.[n][w][e]
[s][f 4 10 65535 0 0]E qui siamo venuti con Yoshizawa,[n]ma anche in altre occasioni. 為[n]una sorta di ritrovo secondario.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Andiamo a salutare tutti quanti.[n]Poi potrai prendere un succo.[n][w][e]

[msg MSG_LAST_GREETING_BOOKST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Non c'因 tempo per i libri.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_BOOKST_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Puoi consultare il catalogo delle[n]uscite, ma qui non potrai pi迂[n]comprare altri libri...[n][w][e]

[msg MSG_LAST_GREETING_DONQ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Scommetto che nella tua citt稲[n]ci sono negozi pi迂 grandi.[n][w][e]

[msg MSG_LAST_GREETING_CINEMA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Il nuovo cinema era fantastico.[n]Cerchiamo di tornarci.[n][w][e]

[msg MSG_LAST_GREETING_CINEMA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Se guarderemo un film[n]non riusciremo a salutare.[n][w][e]

[msg MSG_LAST_GREETING_GALAXY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Non credevo che saresti[n]diventato "Capitano". Hai davvero[n]qualcosa di "speciale"![n][w][e]

[msg MSG_LAST_GREETING_GALAXY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Sei diventato Primo ufficiale.[n]Sei stato bravo.[n][w][e]

[msg MSG_LAST_GREETING_GALAXY_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Sei diventato Secondo ufficiale,[n]giusto? Mangiare troppo[n]non fa bene...[n][w][e]

[msg MSG_LAST_GREETING_GALAXY_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Non c'因 tempo per gli hamburger.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_TSUTAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Ho riportato io i DVD[n]che hai noleggiato.[n]Non devi preoccuparti.[n][w][e]

[msg MSG_LAST_GREETING_TSUTAY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Se noleggiassimo qualcosa non[n]potremmo riportarla. Andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_CREPE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53138 65535 0]Le cr引pes con doppia crema[n]erano le preferite di Lady Ann![n][w][e]
[s][f 4 10 65535 0 0]...Mmh, sembra che oggi non[n]ci siano sconti.[n][w][e]

[msg MSG_LAST_GREETING_CREPE__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non c'因 tempo per le cr引pes.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_CLOTHE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Devi diventare un adulto che fa[n]bella figura con queste cose.[n][w][e]

[msg MSG_LAST_GREETING_LOCKER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]...Qui mi avete salvato.[n]為 stato imbarazzante.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ripensandoci ora, per韻,[n]因 una storia divertente...[n]Grazie.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Qui Ryuji ha fermato il taxi.[n]In quel momento 因 stato[n]davvero un grande.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non conosci nessuno che[n]andrebbe qui, vero? Andiamo[n]da qualche altra parte.[n][w][e]

[msg MSG_LAST_GREETING_TRAINI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Non c'因 tempo per la palestra.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MND_0103]
[s]Non devo fare niente qui...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Bur]
[s]為 l'insegna di Big Bang Burger.[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_LOOK_EVT_712_010_TOD]
[s]I detective gli stanno[n]ancora parlando. Meglio[n]tornare un'altra volta...[n][w][e]

[msg MSG_SHOP_LOCK]
[s](Non ho nuove informazioni[n]sul negozio di armi.)[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_MILI]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il negozio softair[clr 0] a Shibuya.[n][w][e]

[msg MSG_KARAOKE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non hai tempo per il karaoke,[n]giusto? Voglio vedere che[n]canzoni scegli, per韻.[n][w][e]

[msg MND_KARAOKE]
[s]為 tutto prenotato...[n][w][e]

[msg Msg_NotOpen_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Per caso hai fame?[n]Possiamo anche optare per[n]qualcosa di pi迂 costoso, e...[n][w][e]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0]Oh! A quel dipendente part-time[n]因 andata male. Ma lavorando qui[n]miglioreresti la tua [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MSG_BAITO_NOTOPEN]
[s]Sembra un punto vendita di una[n]grande catena di Beef Bowl Shop...[n][w][e]

[msg MSG_BeefTutorial [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ora che ci penso, hai fatto[n]domanda per un lavoro part-time[n]qui al Beef Bowl Shop, giusto?[n][w][e]

[msg MSG_Beef_NoShift [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Uhm? La [clr 2]sera[clr 27] hai il[n]turno al Beef Bowl Shop, giusto?[n][w][e]

[msg MSG_Beef_OKShift [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oggi vuoi lavorare qui?[n][w][e]

[sel SEL_Beef_Q top]
[s]Andiamo a lavorare.[e]
[s]Lavoriamo un altro giorno.[e]

[msg MSG_Gyudon_ParamInfo_int [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Lavorando al Beef Bowl potresti[n]migliorare la [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MSG_Gyudon_ParamInfo_int_2 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]C-Che succede? 為 pieno di gente...[n]Oh, ci sono gli sconti per la[n][clr 2]giornata degli yakiniku[clr 27]![n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Se riusciremo a gestire tutti questi[n]clienti, la tua [stIcon 2][clr 26][stLabel 2][clr 27] migliorerebbe[n]notevolmente...[n][w][e]

[msg MND_Beefdon_ParamUpInfo]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_Beefdon_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_GYUD]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il Beef Bowl Shop[clr 0] a Shibuya.[n][w][e]

[msg MSG_FAMIRES_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]"Bikkuri Boy, apertura imminente[n]post-rinnovo". A quanto pare sta[n]per aprire un ristorante.[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Qui dice [clr 2]maggio[clr 27]. Torniamoci.[n][w][e]

[msg MSG_FAMIRES_NOTOPEN_MORU_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]"Bikkuri Boy, apertura imminente[n]post-rinnovo". Che strano nome[n]per un diner.[n][w][e]
[s][f 4 10 65535 0 0]Apre [clr 2]il 6 di questo mese[clr 27].[n]OK, torniamoci.[n][w][e]

[msg MSG_Famires_Start_1st [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ehi, questo ristorante a gestione[n]familiare 因 stato ristrutturato[n]e aprir稲 a breve![n][w][e]

[msg MSG_Famires_Use_Common [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Scommetto che puoi studiare[n]mentre ti godi il menu.[n][w][e]

[msg MSG_Famires_Use_RainDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Visto il clima di oggi dovrebbero[n]esserci poche persone.[n][w][e]

[msg MND_Famires_ParamUpInfo]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_Famires_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MSG_Famires_Use_Ask [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vuoi studiare qui?[n][w][e]

[sel SEL_FAMIRES_START_MORU top]
[s]Entriamo.[e]
[s]Lasciamo stare.[e]

[msg MSG_Famires_MoneyNone [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Controlla il portafoglio.[n]Senza soldi non puoi[n]ordinare nulla...[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_FAMI]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il diner[clr 0] a Shibuya.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Al momento non ho sete...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg BOOKSTORE_NOTOPEN_TYPE01 [Personale]]
[s]Tra impiegati e studenti,[n]questo posto 因[n]davvero affollato.[n][w][e]
[s]Meglio tornare quando[n]sar稲 pi迂 tranquillo...[n][w][e]

[msg BOOKSTORE_NOTOPEN_TYPE02 [Cameriere]]
[s]Questo posto 因 affollatissimo.[n]C'因 una fiera del libro per i nuovi[n]assunti e gli studenti del primo anno.[n][w][e]
[s]Meglio tornare quando[n]sar稲 pi迂 tranquillo...[n][w][e]

[msg BOOKSTORE_SELECT [Commesso della libreria]]
[s]Benvenuto. I libri pi迂 venduti[n]sono da questa parte.[n][w][e]

[msg BOOKSTORE_THANKS [Commesso della libreria]]
[s]Grazie mille.[n][w][e]

[msg BOOKSTORE_NOT_BUY [Commesso della libreria]]
[s]Torna a trovarci.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_CONV]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il convenience store[clr 0] a Shibuya.[n][w][e]

[msg MSG_Conveni_ByebyeEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Qui hai finito, giusto?[n]Andiamo da un'altra parte.[n][w][e]

[msg DONQ_NOTOPEN]
[s]為 una selezione variegata che[n]spazia dal cibo[n]all'arredamento domestico...[n][w][e]
[s]Quando mi sar韻 abituato alla[n]routine quotidiana,[n]verr韻 a comprare qualcosa...[n][w][e]

[msg DONQ_START [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Che labirinto pazzesco.[n]Sembra quasi un Palazzo...[n][w][e]

[msg DONQ_THANKS [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Hai comprato qualcosa di utile?[n][w][e]

[msg DONQ_NOT_BUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]...Oh, stai solo dando un'occhiata.[n][w][e]

[msg MSG_THEATER_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Non so se andare al cinema il[n]pomeriggio sia una buona idea,[n]anche se ti serve una pausa...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vuoi vedere i film in programmazione?[n]Occupiamoci in fretta di Kamoshida![n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Shib]
[s]Ora puoi viaggiare velocemente[n]verso il [clr 6]cinema[clr 0] a Shibuya.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_BIGB]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il Big Bang Burger[clr 0] a Shibuya.[n][w][e]

[msg MSG_GAME_CENTER_DEFAULT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Sicuro di avere tempo da[n]perdere in sala giochi?[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_SHIB]
[s]Ora puoi viaggiare velocemente[n]verso la [clr 6]sala giochi[clr 0] a Shibuya.[n][w][e]

[msg DrugStore_NOTOPEN]
[s]Qui non vendono solo[n]medicine, ma anche detersivi[n]e altri prodotti di uso quotidiano.[n][w][e]
[s]Ci verr韻 quando[n]avr韻 bisogno di qualcosa...[n][w][e]

[msg DrugStore_SELECT [Farmacista]]
[s]Benvenuuuto. Cerchi qualcosa[n]in particolare?[n][w][e]

[msg DrugStore_THANKS [Farmacista]]
[s]Grazie mille.[n]Torna a trovarci![n][w][e]

[msg DrugStore_NOT_BUY [Farmacista]]
[s]Torna a trovarci![n][w][e]

[msg MSG_DRUGSTORE_KAMOSHIDA_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Preferirei una medicina[n]pi迂 efficace di questa,[n]ma per ora mi accontento.[n][w][e]

[msg MSG_DRUGSTORE_KAMOSHIDA__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Serve una medicina pi迂[n]efficace di questa. Dove possiamo[n]trovare farmaci migliori?[n][w][e]

[msg MSG_CREPE_SHOP_DEFAULT]
[s]Nell'aria si sente un[n]aroma dolce e inconfondibile...[n][w][e]

[msg MSG_CREPE_SHOP_DEFAULT_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Una creperia, eh?[n]Non sembri proprio[n]un tipo da cr引pe, vero?[n][w][e]

[msg MSG_CLOTHES_SHOP_DEFAULT]
[s]Nel negozio sono[n]esposti vestiti di[n]diversi colori...[n][w][e]

[msg MSG_CLOTHES_SHOP_DEFAULT_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Questa 因 la moda che[n]spopola in questo periodo?[n]Sembrano tutti uguali...[n][w][e]

[msg MSG_LOCKER_DEFAULT]
[s]Sono stati imbrattati[n]con adesivi e scarabocchi...[n][w][e]

[msg MSG_LOCKER_DEFAULT_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Perch姻 fare una cosa simile?[n]Hanno ridotto tutto[n]in uno stato pietoso...[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 0 11018 65535 0]Non hai tempo[n]per giocare, Prigioniero![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torna in cella![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]Queste prove... credo che[n]tu possa superarle.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso la Stanza di Velluto[clr 0].[n][w][e]

[msg MSG_DEADEND01_DEFAULT_MO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Non hai niente da fare[n]pi迂 avanti, vero?[n]Torniamo indietro![n][w][e]

[msg MSG_DEADEND01_DEFAULT]
[s]Passano troppe macchine.[n]Non devo fare niente[n]pi迂 avanti.[n][w][e]

[msg MSG_Training_NotOpen_Myr [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Una palestra, eh? 為 bello che[n]tu voglia allenarti, ma spenderesti[n]dei soldi per farlo?[n][w][e]

[msg MSG_Training_NotOpen_Myr_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Una palestra, eh? 為 bello che[n]tu voglia allenarti, ma spenderesti[n]dei soldi per farlo?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Perch姻 non lo fai in camera?[n]為 molto pi迂 economico.[n][w][e]

[msg MSG_GIM_Start1st [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Questa palestra...[n]Ci siamo gi稲 stati.[n][w][e]

[msg MSG_GIM_Think_AllDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pensi di andare in palestra?[n]Costa 2.000 yen a seduta.[n][w][e]

[msg MSG_GIM_Think_Weekday_Go [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pensi di andare in palestra?[n]Nei pomeriggi dei giorni feriali[n]costa 1.000 yen.[n][w][e]

[msg MSG_GIM_Think_Weekday_Yo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pensi di andare in palestra?[n]La sera dei giorni feriali[n]costa 1.800 yen.[n][w][e]

[msg MSG_GIM_Think_Weekend_Go [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pensi di andare in palestra?[n]Nei pomeriggi del fine settimana[n]costa 1.200 yen.[n][w][e]

[msg MSG_GIM_Think_Weekend_Yo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pensi di andare in palestra?[n]La sera del fine settimana[n]costa 2.000 yen.[n][w][e]

[sel SEL_GimShopEnter_Q top]
[s]Andiamoci.[e]
[s]Lasciamo stare.[e]

[msg MSG_GIM_MoneyOver [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]...Che delusione.[n]Non hai abbastanza soldi.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_GYM]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso la palestra[clr 0] a Shibuya.[n][w][e]

[msg MSG_BURGER_BOARD_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Big Bang Burger, eh...?[n]Che nome pomposo.[n][w][e]

[msg MSG_BURGER_BOARD]
[s]為 l'insegna di Big Bang Burger.[n][w][e]
[s]A quanto pare hanno[n]un menu stagionale...[n][w][e]

[msg MSG_Deadend02_MORU [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]In citt稲, a nessuno interessa[n]del male causato al prossimo.[n]Uff, manca l'educazione.[n][w][e]

[msg MSG_Deadend02]
[s]Una bicicletta blocca il passaggio...[n][w][e]

[msg MND_BookPanel_01]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]Meglio dare un'occhiata,[n]di tanto in tanto...[n][w][e]

[msg MND_BookPanel_02]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]"Guida per la sopravvivenza[n]nell'epoca di Internet!" uscir稲[n]a inizio maggio.[n][w][e]
[s]Devo tornare il[n]giorno dell'uscita...[n][w][e]

[msg MND_BookPanel_03]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]"Speciale sui punti[n]che aumentano la femminilit稲!"[n]uscir稲 il 16 maggio.[n][w][e]
[s]Devo tornare il[n]giorno dell'uscita...[n][w][e]

[msg MND_BookPanel_04]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]"Libro speciale per[n]adulti che giocano razionalmente!"[n]uscir稲 il primo giugno.[n][w][e]
[s]Devo tornare il[n]giorno dell'uscita...[n][w][e]

[msg MND_BookPanel_05]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]"Storie di fantasmi per[n]resistere alla calura estiva!"[n]uscir稲 il primo luglio.[n][w][e]
[s]Devo tornare il[n]giorno dell'uscita...[n][w][e]

[msg MND_BookPanel_06]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]"I segreti della citt稲:[n]Speciale sui laghetti!"[n]uscir稲 il 16 luglio.[n][w][e]
[s]Devo tornare il[n]giorno dell'uscita...[n][w][e]

[msg MND_BookPanel_07]
[s]Sul cartello della libreria[n]sono scritte le[n]informazioni sui nuovi libri...[n][w][e]
[s]"Pace e tranquillit稲: Speciale sui[n]luoghi per gli appuntamenti!"[n]uscir稲 il primo settembre.[n][w][e]
[s]Devo tornare il[n]giorno dell'uscita...[n][w][e]

[msg MND_BookPanel_08]
[s]Non ci sono[n]informazioni che[n]mi interessano...[n][w][e]

[msg MSG_M79_GYU_DON_000_00_0 [Morgana]]
[s][vp 8 2 1 1164 65535 0][bup 0 3 5 0 0][f 4 10 65535 0 0]Questo locale 因 sempre affollato...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Quel dipendente ne sapr稲 qualcosa.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Aspettiamo che esca.[n][w][e]

[msg MSG_M79_GYU_DON_001_00_0 [Morgana]]
[s][vp 8 2 1 1167 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Oh, 因 lui?[n][w][e]

[msg MSG_M79_GYU_DON_002_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Aaah! M-Mi dispiace![n][w][e]

[sel SEL_M79_GYU_DON_003_00_0 top]
[s]Ho una domanda.[e]
[s]No, lasciamo perdere.[e]

[msg MSG_M79_GYU_DON_004_01_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Oh... No, 因 tutto OK.[n][w][e]
[s][f 4 25 1 65535 0 0]Uhm, potresti spostarti?[n][w][e]

[msg MSG_M79_GYU_DON_005_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]C-Chi sei...? Ho gi稲 parlato[n]di lui alla polizia...[n][w][e]
[s][f 4 25 1 500 0 0]In genere questo negozio 因 gestito[n]da una sola persona.[n]Non si vedono altri dipendenti...[n][w][e]
[s][f 4 25 1 500 0 0]E anche se ogni tanto lo vedo,[n]parliamo di rado...[n][w][e]

[sel SEL_M79_GYU_DON_006_00_0 top]
[s]Vogliamo provare la sua innocenza.[e]
[s]Dicci quello che sai, per favore.[e]

[msg MSG_M79_GYU_DON_007_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Ehi, per caso sei...[n]l'amico di Toji-kun?[n][w][e]
[s][f 4 25 1 500 0 0]...Anch'io penso che sia[n]innocente. 為 un ragazzo[n]vivace e in gamba.[n][w][e]

[msg MSG_M79_GYU_DON_008_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Ha due lavori part-time.[n]Per lui dev'essere dura,[n]ma sorride sempre...[n][w][e]

[sel SEL_M79_GYU_DON_009_00_0 top]
[s]Nient'altro?[e]
[s]Dicci di pi迂.[e]

[msg MSG_M79_GYU_DON_010_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Oh...? Ecco, non parlavo[n]spesso con lui...[n][w][e]
[s][f 4 25 1 500 0 0]Oh, ma abbiamo parlato[n]del suo cognome, Karataki, e[n]del suo nome insolito.[n][w][e]
[s][f 4 25 1 500 0 0]Ha detto che anche il[n]cognome della famiglia di suo[n]padre 因 piuttosto singolare...[n][w][e]
[s][f 4 25 1 500 0 0]Credo che fosse... Ushiwata?[n][w][e]

[msg MSG_M79_GYU_DON_011_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Abbiamo parlato di come[n]sembrasse un nome perfetto[n]per un Beef Bowl...[n][w][e]
[s][f 4 25 1 500 0 0]Ma 因 tutto quello che so...[n][w][e]

[msg MSG_M79_GYU_DON_012_00_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Mmh, Toji Karataki...[n]Abbiamo scoperto il suo nome.[n][w][e]

[msg MSG_M79_GYU_DON_013_00_0 [Uomo timido]]
[s][f 4 25 1 500 0 0]Non so altro, mi dispiace.[n]Posso andare ora...?[n][w][e]

[msg MSG_E24330100_NG_GOTO_ST [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Dove vai? Pensavo che dovessi[n]esplorare Shibuya...[n][w][e]
[s]Questa era la tua zona, giusto?[n][w][e]

[msg MND_CHK_STATION]
[s][vp 1 0 0 0 0 0]Non dovrei tornare a casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio seguire Ryuji...[n][w][e]

[msg MND_CHK_STATION2]
[s][vp 1 0 0 0 0 0]Non dovrei tornare a casa...[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio seguire Ryuji...[n][w][e]

[msg MND_COMMON_CHK_DRUGSTORE]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_DRUGSTORE_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Possiamo comprare qualcosa anche[n]qui. Vediamo, dove sono le medicine[n]per i momenti difficili...?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Torniamoci, di tanto in tanto.[n]Hanno cose piuttosto utili.[n][w][e]

[msg MSG_DRUGSTORE_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7131 65535 0]Questa farmacia vende colliri[n]e molto altro. Utile per giocare[n]tutta la notte ai videogiochi![n][w][e]

[msg MSG_DRUGSTORE_KF_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]...Santo cielo.[n][w][e]

[msg MND_COMMON_CHK_MILITARY]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_COMMON_CHK_KARAOKE]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_KARAOKE_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Non hai tempo per il karaoke,[n]giusto? Voglio vedere che[n]canzoni scegli, per韻.[n][w][e]

[msg MSG_KARAOKE_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ehi, forza! Dobbiamo cercare[n]le armi, giusto?[n][w][e]

[msg MSG_KARAOKE_KF_0504 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Non c'因 tempo per le deviazioni![n]Troviamo un posto dove[n]ottenere dei soldi![n][w][e]

[msg MND_COMMON_CHK_GYUDON]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_BEEFDON_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]...Uh? Non 因 il posto dove[n]abbiamo mangiato con Ryuji?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gi稲 da qui si sente il profumo.[n]Miaohohoh...[n][w][e]

[msg MSG_BEEFDON_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Adoro lo zenzero rosso! ...Mi[n]viene fame anche solo a parlarne.[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]OK, la prossima volta. Per[n]oggi 因 meglio andare.[n][w][e]

[msg MSG_BEEFDON_KF_0504 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Hai fame? Andiamo a[n]scambiare la medaglia.[n][w][e]

[msg MND_COMMON_CHK_FAMILY_RE]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_FAMILY_RESTAURANT_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Accidenti... a quanto pare il[n]negozio 因 ancora chiuso.[n][w][e]

[msg MSG_FAMILY_RESTAURANT_KF_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7080 65535 0]Il diner 因 ancora in via di[n]ristrutturazione.[n][w][e]

[msg MND_COMMON_CHK_AUTO_MACH]
[s][vp 8 2 65535 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MSG_AUTO_MACHINE_KF_0504 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1046 65535 0]Non c'因 tempo per prendere[n]un succo! Su, andiamo a[n]scambiare la medaglia![n][w][e]

[msg MND_COMMON_CHK_BOOKSTORE]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_BOOKSTORE_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Per i ladri la conoscenza 因[n]importante. Pu韻 tornare utile[n]nei momenti difficili.[n][w][e]

[msg MSG_BOOKSTORE_KF_R [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 54211 65535 0]Mi viene sonno quando leggo.[n]Soprattutto durante le lezioni...[n][w][e]

[msg MSG_BOOKSTORE_KF_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Santo cielo.[n][w][e]

[msg MSG_BOOKSTORE_KF_0504 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0]Dubito che una libreria la compri![n]Andiamo da un'altra parte.[n][w][e]

[msg MND_COMMON_CHK_CONVENIEN]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_CONVENIENCE_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Uhm... A quanto pare[n]vendono snack di ogni tipo.[n]Oooh, quello sembra buono...[n][w][e]

[msg MSG_CONVENIENCE_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Uh? Qualche volta[n]mi ci fermo anch'io.[n][w][e]

[msg MSG_CONVENIENCE_KF_0504 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]I convenience store non comprano[n]nulla. Sai che dobbiamo scambiare[n]la medaglia con dei soldi, vero?[n][w][e]

[msg MND_COMMON_CHK_DONQ]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_DONQ_KF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Wow, ma 因 fantastico! Sembra un labirinto...[n][w][e]

[msg MSG_DONQ_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]為 utile, visto che 因 a buon mercato.[n]Hai visto il megapacco gigante?[n]A quel prezzo 因 un vero affare![n][w][e]

[msg MSG_DONQ_KF_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1047 65535 0]Dubito che la spiegazione[n]fosse davvero necessaria...[n][w][e]

[msg MSG_DONQ_KF_0504 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Penseremo allo shopping un'altra[n]volta. Dobbiamo cercare un posto[n]dove vendere la medaglia.[n][w][e]

[msg MND_COMMON_CHK_CINEMA]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_CINEMA_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Oh, un cinema. Oggi proiettano...[n][w][e]

[msg MSG_CINEMA_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Ehi, andiamo al negozio di armi.[n]Il film lo vedremo un'altra volta.[n][w][e]

[msg MSG_CINEMA_KF_0504 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Non hai il tempo per vedere[n]un film! Oggi dobbiamo vendere la[n]medaglia a tutti i costi![n][w][e]

[msg MND_COMMON_CHK_GALAXY]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_GALAXY_KF_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7161 65535 0]Central Street 因 sinonimo di[n]Big Bang Burger. Vendono[n]hamburger di ogni tipo. Consiglio...[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gah, no, concentriamoci.[n]Dobbiamo cercare le armi.[n]Forza, andiamo.[n][w][e]

[msg MSG_GALAXY_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Hamburger di ogni tipo, eh? Come[n]saranno? Ora s淫 che sono curioso...[n][w][e]

[msg MSG_E24330100_NG_GOTO_UN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1155 0 0]Vai avanti e occupati di[n]Central Street. Lascia il resto[n]agli altri.[n][w][e]

[msg MSG_E24330100_NG_GOTO_UN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1155 0 0]Vai avanti e occupati di[n]Central Street. Lascia il resto[n]agli altri.[n][w][e]

[msg MND_COMMON_CHK_TSUTAYA]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_TSUTAYA_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Questo 因... un videonoleggio.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Mmh... cercano nuovi membri.[n]Chiss稲 come te la caveresti[n]se accettassi di farlo.[n][w][e]

[msg MSG_TSUTAYA_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7137 65535 0]Credo che qui si possa noleggiare[n]serie famose. Non oggi, per韻.[n]Oggi andiamo al negozio d'armi.[n][w][e]

[msg MND_COMMON_CHK_GAME_CENT]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_COMMON_CHK_CREPE_SHO]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_CREPE_KF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Questo sarebbe perfetto per[n]Lady Ann... Dolce e colorato.[n][w][e]

[msg MSG_CREPE_KF_R [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]Oh, mi stupisce che tu[n]lo conosca. Ann ha detto[n]che le piacciono i dolci.[n][w][e]

[msg MND_COMMON_CHK_CLOTHES_S]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_CLOTHES_SHOP_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Ecco che si intende per[n]abiti alla moda.[n]Perch姻 non li provi, [fName]?[n][w][e]

[msg MSG_CLOTHES_SHOP_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Uhm, non fa per me.[n][w][e]

[msg MND_COMMON_CHK_LOCKER]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_LOCKER_KF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]I graffiti e gli adesivi... Dubito[n]che tu possa aprirla di nuovo...[n][w][e]

[msg MSG_LOCKER_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Uhm, non fa per me.[n][w][e]

[msg MND_COMMON_CHK_VELVET_DO]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_GAME_CENTER_KF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 0 0]Ehi, dovresti cercare un negozio di[n]armi... Cos'因 questo posto, comunque?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]...In molti indossano occhiali come[n]i tuoi. Dovremmo tornare pi迂 tardi.[n][w][e]

[msg MSG_GAME_CENTER_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, vengo spesso in questa[n]sala giochi. Ogni tanto[n]andiamoci insieme, [fName].[n][w][e]

[msg MSG_GAME_CENTER_KF_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Perch姻 siamo venuti in sala giochi?[n]Devi trovare un posto in cui[n]vendere quella medaglia d'oro.[n][w][e]

[msg MSG_GAME_CENTER_KF_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1188 0 0]Ehi, al momento non c'因 motivo di[n]stare in sala giochi. Perch姻[n]non ci veniamo un'altra volta?[n][w][e]

[msg MND_CHK_ITEM_SHOP]
[s][vp 8 2 65535 0 0 0]Questa dev'essere la clinica[n]con la ciarlatana che prescrive[n]strane medicine...[n][w][e]

[msg MND_CHK_WEAPON_SHOP]
[s][vp 8 2 65535 0 0 0]Questo sembra il negozio[n]softair menzionato da Ryuji...[n][w][e]

[msg MSG_KARAOKE_02_KF_01]
[s][vp 8 2 65535 0 0 0]C'因 scritto che il karaoke[n]因 al completo...[n][w][e]

[msg MSG_KARAOKE_02_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ma che cavolo...? Quattrocento yen[n]per cantare per sola mezz'ora?[n]Gli svaghi costano molto in citt稲.[n][w][e]

[msg MSG_GYUUDON_KF_01]
[s][vp 8 2 65535 0 0 0]為 il Beef Bowl Shop "Donburako".[n]C'因 un solo dipendente che manda[n]avanti il posto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Un dipendente dotato di[n]un'[clr 1]Agilit稲[clr 27] unica...[n][w][e]

[msg MSG_GYUUDON_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Questo Beef Bowl Shop si chiama[n]"Donburako". Ha un solo dipendente,[n]ma incredibilmente bravo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Sai, se cominciassi a[n]lavorare qui, potresti[n]migliorare la tua [clr 1]Agilit稲[clr 27].[n][w][e]

[msg MSG_IZAKAYA_KF_01]
[s][vp 8 2 65535 0 0 0]C'因 un izakaya sul retro.[n]L'interno sembra molto affollato...[n][w][e]

[msg MSG_IZAKAYA_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Oh, c'因 un izakaya sul[n]retro. Potrai andarci quando[n]avrai qualche anno in pi迂.[n][w][e]

[msg MSG_FAMIRES_KF_01]
[s][vp 8 2 65535 0 0 0]Qui 因 pieno di studenti e coppie.[n]Non 因 un gran posto per[n]passare il tempo da soli...[n][w][e]

[msg MSG_FAMIRES_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ci sono tantissimi studenti e[n]coppie qui. Venirci da solo non[n]sarebbe il massimo, no?[n][w][e]

[msg MSG_BERGER_KF_01]
[s][vp 8 2 65535 0 0 0]Big Bang Burger... Vedo molte[n]pubblicit稲 di questo posto, e[n]se ne fa un gran parlare.[n][w][e]

[msg MSG_BERGER_KF_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Questo posto viene[n]pubblicizzato molto, eh?[n][w][e]

[msg MSG_KFE_OPEN_SHOP_UNDER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1175 0 0]Il sottopasso 因 poco pi迂 avanti,[n]ma il negozio che cerchi si trova[n]a Central Street, vero?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Andiamo in quel posto nel vicolo.[n][w][e]

[msg MSG_CINEMA_KF_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Il [clr 6]Cinema 7[clr 27], eh?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Guardare un film sarebbe[n]uno svago piacevole, ma adesso[n]non hai tempo per farlo.[n][w][e]

[msg MND_COMMON_MAIN_TRAINING]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_TRAINING_GIM_KF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oh, questa 因... una palestra?[n][w][e]

[msg MSG_TRAINING_GIM_KF_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Ehi, avanti. Stiamo cercando[n]il negozio d'armi, giusto?[n][w][e]

[msg MND_COMMON_BookStore_Pan]
[s][vp 8 2 65535 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Lasciami entrare in cella.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]A quanto pare, vuoi essere[n]imprigionato. Posso esaudire[n]il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Sar韻 lieta di[n]esaudire il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Continua la tua lotta.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che c'因, Prigioniero?[n]Desideri tornare in prigione?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eheheh. Ti rimetter韻 al[n]tuo posto![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continua a lottare, Prigioniero.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ti condurr韻 dal mio padrone...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Voglio prepararmi.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora entra, per favore.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Io e il mio padrone[n]veglieremo su di te.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_CinemaBuyTicketSIBUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Ah, gi稲! Prima devi[n]comprare un biglietto.[n][w][e]

[msg MSG_CinemaCancel [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1003 65535 0]Hai cambiato idea?[n][w][e]

[msg MSG_CinemaOK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Il film sta per iniziare.[n]Andiamo a sederci.[n][w][e]

[msg MSG_CinemaWatched [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0][var 7]?[n]Ne ho avuto abbastanza di quello...[n]Torniamo un'altra volta.[n][w][e]

[msg MSG_CinemaBuyTicket [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Per vedere un film[n]devi comprare un biglietto.[n][w][e]

[msg MND_ParamEndInfo_Atama]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Miryoku]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Kiyou]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Dokyo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Yasas]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_ParamMoru_Atama [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MSG_ParamMoru_Miryoku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare il tuo[n][stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MSG_ParamMoru_Kiyou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MSG_ParamMoru_Dokyo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare il tuo[n][stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MSG_ParamMoru_Yasas [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Chiss稲 che film stanno[n]proiettando adesso...[n][w][e]

[msg MSG_Cinema_MoneyNG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Controlla il portafoglio.[n]Non hai abbastanza soldi.[n][w][e]

[msg MSG_CINEMA_MEMBER_NG [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Quante volte hai intenzione di[n]vedere lo stesso film?[n]Dacci un taglio...[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Wow, questo cinema 因 immenso![n]Chiss稲 che film stanno proiettando adesso...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questo dovrebbe essere un[n]cinema, giusto? Ma 因 vuoto...[n]Forse 因 chiuso.[n][w][e]

[msg MND_CINEMA_NOT_OPEN]
[s]Al momento il cinema[n]因 chiuso...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Non c'因 anima viva. Sembra[n]che non apra nemmeno[n]di sera. Che succede?[n][w][e]

[msg MSG_CINEMA_BOOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Visto che hai finito di leggere[n][clr 3]Anima da cineasta[clr 27], scommetto che[n]apprezzerai ancora di pi迂 il film.[n][w][e]

[msg MSG_COMMENT_LIST01_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un adolescente che[n]diventa milionario vincendo al quiz[n]"Le sedici domande"...[n][w][e]

[msg MSG_COMMENT_2ndINFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, 因 [var 7].[n]Vuoi rivederlo?[n][w][e]

[msg MSG_COMMENT_LIST02_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un eroe che[n]cerca di sgominare[n]crimine e corruzione.[n][w][e]

[msg MSG_COMMENT_LIST03_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo che fatica[n]a confessare i propri sentimenti[n]alla donna che ama.[n][w][e]

[msg MSG_COMMENT_LIST04_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo che cerca[n]di ricostruire la sua vita[n]dopo una lunga carcerazione.[n][w][e]

[msg MSG_COMMENT_LIST05_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo che deve entrare[n]nel suo appartamento ultraprotetto[n]dopo aver perso la chiave.[n][w][e]

[msg MSG_COMMENT_LIST06_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo con[n]l'incarico di pulire un enorme[n]grattacielo nel giorno di Natale.[n][w][e]

[msg MSG_COMMENT_LIST14_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un pap稲 vespa in[n]viaggio con l'amico ape per salvare[n]il figlio catturato dagli umani.[n][w][e]

[msg MSG_COMMENT_LIST07_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un gatto robot[n]che noleggia strumenti utili[n]ma a prezzo salatissimo.[n][w][e]

[msg MSG_COMMENT_LIST08_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]I soldi spariscono, il boss[n]ci rimette la pelle e le strade[n]di Tokyo si tingono di rosso...[n][w][e]

[msg MSG_COMMENT_LIST09_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia delle persone pi迂[n]inutili del mondo che formano una[n]squadra per combattere gli alieni.[n][w][e]

[msg MSG_COMMENT_LIST10_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di due uomini intrappolati in[n]una stanza con un elefante[n]imbizzarrito. Se la caveranno?[n][w][e]

[msg MSG_COMMENT_LIST15_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo insonne[n]che impazzisce dopo un certo[n]incontro in un negozio di kebab.[n][w][e]

[msg MSG_COMMENT_LIST11_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la tragica storia di[n]un boss della mafia che[n]adora i propri figli.[n][w][e]

[msg MSG_COMMENT_LIST12_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un tipo viaggia indietro nel[n]tempo e impara il ninjutsu, per[n]vendicare l'amico ucciso da un ninja.[n][w][e]

[msg MSG_COMMENT_LIST13_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di alcuni prigionieri[n]di guerra costretti a lavorare[n]duramente nonostante sia Natale.[n][w][e]

[msg MSG_COMMENT_LIST16_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di una donna pastore e di[n]uno psichiatra amante dei montoni[n]sulle tracce di un tosatore seriale.[n][w][e]

[msg MSG_COMMENT_LIST17_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un universitario che lotta[n]per la liberazione del suo[n]dormitorio oppresso.[n][w][e]

[msg MSG_COMMENT_LIST18_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo che si unisce per[n]caso a un circo, riuscendo a[n]fare carriera grazie al carisma.[n][w][e]

[msg MND_Sentou_ParamInfo_Chi]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo_]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Dok]
[s]Pare che guardando questo film[n]potrei migliorare il mio [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__2]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora il mio [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Yas]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__3]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Iro]
[s]Pare che guardando questo film[n]potrei migliorare il mio [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__4]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora il mio [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Kiy]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__5]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

