[msg GENERIC_HELP_00]
[s]Dovrei passare del tempo[n]da solo con Ohya...?[n][e]

[msg GENERIC_HELP_01]
[s]Dovrei passare del tempo[n]da solo con Takemi...?[n][e]

[msg GENERIC_HELP_02]
[s]Dovrei passare del tempo[n]da solo con Kawakami...?[n][e]

[msg GENERIC_HELP_03]
[s]Dovrei passare del tempo[n]da solo con Hifumi...?[n][e]

[msg GENERIC_HELP_04]
[s]Dovrei passare del tempo[n]da solo con Chihaya...?[n][e]

[msg GENERIC_HELP_05]
[s]Dovrei passare del tempo[n]da solo con Futaba...?[n][e]

[msg GENERIC_HELP_06]
[s]Dovrei passare del tempo[n]da solo con Ann...?[n][e]

[msg GENERIC_HELP_07]
[s]Dovrei passare del tempo[n]da solo con Makoto...?[n][e]

[msg GENERIC_HELP_08]
[s]Dovrei passare del tempo[n]da solo con Haru...?[n][e]

[msg GENERIC_HELP_09]
[s]Dovrei passare del tempo[n]da solo con Sumire...?[n][e]

[msg GENERIC_HELP_10]
[s]Magari non invito nessuno...[n][e]

[msg MSG_LAST_GREETING_CDSHOP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Questo negozio ha ottime[n]offerte per tutto l'anno...[n][w][e]

[msg MSG_LAST_GREETING_SUPERM [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non c'因 tempo per gli acquisti.[n]Andiamo a incontrare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_MIYAGE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Non servono regali.[n]Bastano le tue parole.[n][w][e]

[msg MSG_LAST_GREETING_JEWELR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Non c'因 tempo per i gioielli.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_ACCESS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Questo negozio era alla moda.[n]Chiss稲 se lo troverai nella[n]tua citt稲?[n][w][e]

[msg MSG_LAST_GREETING_SPORTS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]La tua citt稲 li ha i negozi[n]di scarpe, giusto? Andiamo[n]a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_UMBREL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Ricordi quando ti ho preparato[n]l'ombrello? 為 stato utile, vero?[n][w][e]

[msg MSG_LAST_GREETING_ORIENT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non ci sono molti[n]negozi cos淫 alla moda...[n]E comunque, non 因 il mio stile.[n][w][e]

[msg MSG_LAST_GREETING_SHOES_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Le hai indossate per un anno,[n]ma le tue scarpe sono[n]in ottimo stato.[n][w][e]

[msg MSG_LAST_GREETING_BAGSHO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]...Mi piace la tua nuova borsa.[n][w][e]

[msg MSG_LAST_GREETING_DRESSS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Sei venuto in questo negozio[n]con Sumire, giusto? Sarebbe[n]bello fare ancora shopping.[n][w][e]

[msg MSG_LAST_GREETING_DRESSS_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Questo 因 il negozio d'abbigliamento[n]preferito di Ann. Dubito che[n]abbiano qualcosa per me...[n][w][e]

[msg MSG_LAST_GREETING_BRANDS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Questo negozio andava[n]sempre alla grande.[n][w][e]

[msg MSG_LAST_GREETING_FLOWER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Al massimo, sei tu a dover[n]ricevere i fiori, giusto? Andiamo[n]a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_WATCHS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Non perdiamo altro tempo![n]Andiamo a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_LEATHE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]C'因 ancora odore di animali...[n]Muoviamoci, prima che[n]ci si attacchi addosso.[n][w][e]

[msg MSG_LAST_GREETING_COSME_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Non c'因 tempo per gli acquisti.[n]Andiamo a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_SHOESS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non devi indossare i tacchi.[n]Andiamo a incontrare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_PHOTO_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1099 65535 0]Ci sono ricordi che non puoi[n]racchiudere in un'immagine. Andiamo[n]dagli altri, per l'ultima volta.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non conosci nessuno che[n]andrebbe qui, vero? Andiamo[n]da qualche altra parte.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MND_0103]
[s]Non devo fare niente qui...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_SPORTS_NOTOPEN]
[s]Qui ci sono articoli sportivi di[n]tutti i tipi, vecchi e nuovi...[n][w][e]
[s]Verr韻 a comprare qualcosa,[n]quando avr韻 un po' di tempo...[n][w][e]

[msg MSG_SPORTS_SELECT [Commesso del negozio sportivo]]
[s]Benvenuto.[n]Abbiamo le migliori offerte.[n][w][e]

[msg MSG_SPORTS_THANKS [Commesso del negozio sportivo]]
[s]Grazie! Torna presto[n]a trovarci![n][w][e]

[msg MSG_SPORTS_NOT_BUY [Commesso del negozio sportivo]]
[s]Torna a trovarci![n][w][e]

[msg MSG_CDSHOP_P5R [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]C'因 un autografo su un poster[n]nel negozio. Vediamo...[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]...Non si legge niente...[n][w][e]

[msg MSG_SportShop_MayCueInfo [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Stecche da biliardo... Non[n]sai usarle, vero?[n][w][e]
[s][f 4 10 65535 0 0]Qui vicino vendevano un[n]libro. Magari ti insegner稲[n]come fare.[n][w][e]

[msg SUPERMARKET_NOTOPEN]
[s]Sembra che questo posto[n]abbia prodotti costosi[n]fatti di materiali diversi...[n][w][e]
[s]Dovrei tornarci se mi[n]serve qualcosa...[n][w][e]

[msg SUPERMARKET_SELECT [Commesso del supermercato]]
[s]Dai pure un'occhiata[n]in giro.[n][w][e]

[msg SUPERMARKET_THANKS [Commesso del supermercato]]
[s]Grazie mille.[n]Torna presto a trovarci.[n][w][e]

[msg SUPERMARKET_NOT_BUY [Commesso del supermercato]]
[s]Torna a trovarci.[n][w][e]

[msg MSG_MIYAGE [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Qui vendono molte[n]cose, ma che[n]razza di negozio 因...?[n][w][e]

[msg MND_MIYAGE]
[s]In questo negozio di souvenir[n]hanno prodotti di ogni tipo...[n][w][e]

[msg MSG_JEWELRY_NOTOPEN]
[s]Qui vendono oggetti di gioielleria.[n][w][e]
[s]Ci torner韻 quando[n]avr韻 bisogno di qualcosa...[n][w][e]

[msg JEWELRY_START [Commessa della gioielleria]]
[s][f 4 23 1 8 3 5 65534 0][vp 8 2 1 0 8 0]Benvenuto. Ah, per favore, non[n]toccare la merce esposta...[n][w][e]

[msg JEWELRY_THANKS [Commessa della gioielleria]]
[s][vp 8 2 1 0 8 0]Grazie mille.[n]Torna presto a trovarci.[n][w][e]

[msg JEWELRY_NOT_BUY [Commessa della gioielleria]]
[s][vp 8 2 1 0 8 0]...Speriamo di rivederti presto.[n][w][e]

[msg MSG_ACCESSORIES_NOTOPEN]
[s]Qui vendono molti accessori.[n][w][e]
[s]Ci torner韻 quando[n]avr韻 bisogno di qualcosa...[n][w][e]

[msg ACCESSORIES_SELECT [Commesso del negozio di accessori]]
[s][f 4 23 1 16 3 5 65534 0][vp 8 2 1 0 16 0]Benvenuto! Vendiamo accessori[n]per tutte le tasche.[n][w][e]

[msg ACCESSORIES_THANKS [Commesso del negozio di accessori]]
[s][vp 8 2 1 0 16 0]Grazie mille! Arrivederci.[n][w][e]

[msg ACCESSORIES_NOT_BUY [Commesso del negozio di accessori]]
[s][vp 8 2 1 0 16 0]OK... Arrivederci.[n][w][e]

[msg MSG_ShoesShop_Moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non pratichi alcuno sport. Perch姻[n]prendere le scarpe da ginnastica?[n][w][e]

[msg MSG_ShoesShop]
[s]為 pieno di scarpe da ginnastica[n]impilate l'una sull'altra...[n][w][e]

[msg MSG_UMBRELLA_SHOP_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Porta sempre un ombrello, per[n]le piogge improvvise. Non[n]ho intenzione di bagnarmi.[n][w][e]

[msg MSG_UMBRELLA_SHOP]
[s]Qui hanno ombrelli di ogni[n]tipo. Alcuni sono molto[n]costosi, altri pi迂 economici...[n][w][e]

[msg MSG_ORIENTAL_SHOP]
[s]為 un negozio che tratta[n]prodotti tipici giapponesi.[n][w][e]
[s]Comprando qui un regalo[n]per qualcuno, potrei[n]farlo davvero felice...[n][w][e]

[msg MSG_ORIENTAL_SHOP_START [Commessa del negozio di articoli vari]]
[s][f 4 23 1 5 3 5 65534 0][vp 8 2 1 0 5 0]Benvenuto. Perch姻 non fai[n]qualcosa di diverso, comprando[n]dei regali in stile giapponese?[n][w][e]

[msg MSG_ORIENTAL_SHOP_THANKS [Commessa del negozio di articoli vari]]
[s][vp 8 2 1 0 5 0]Grazie mille.[n]Torna a trovarci![n][w][e]

[msg MSG_ORIENTAL_SHOP_NOT_BU [Commessa del negozio di articoli vari]]
[s][vp 8 2 1 0 5 0]Torna a trovarci.[n][w][e]

[msg MSG_SHOES_REPAIR_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Le tue scarpe vanno benone,[n]sai? Non credo che abbiano[n]bisogno di essere aggiustate.[n][w][e]

[msg MSG_SHOES_REPAIR]
[s]Non ho bisogno di far[n]aggiustare le scarpe...[n][w][e]

[msg MSG_BAGSHOP_MORU [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Sono tutte troppo[n]piccole per me.[n][w][e]

[msg MSG_BAGSHOP]
[s]為 pieno di scarpe da donna.[n][w][e]

[msg MSG_DRESSSHOP_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Messi uno accanto all'altro,[n]questi vestiti sembrano[n]tutti uguali...[n][w][e]

[msg MSG_DRESSSHOP]
[s]Vendono vestiti da donna.[n][w][e]

[msg MSG_BRANDSHOP_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Impazziscono tutti per[n]questi prodotti. Sono di[n]una marca famosa?[n][w][e]

[msg MSG_BRANDSHOP]
[s]為 un negozio monomarca per[n]donne. 為 affollato...[n][w][e]

[msg MSG_Flower_ByebyeEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Qui hai finito, giusto?[n]Andiamo da un'altra parte.[n][w][e]

[msg MSG_FlowerLAstDay [Hanasaki]]
[s][vp 8 2 0 58508 6 0]Oh, [fName]. Come stai?[n]Vuoi...[n][w][e]
[s][vp 8 2 0 0 6 0]...Oh, stai tornando alla[n]tua citt稲.[n][w][e]
[s][vp 8 2 0 0 6 0]I fiori crescono ovunque. Quando[n]li vedrai, ricordati di questo[n]negozio... Eheh.[n][w][e]
[s][vp 8 2 0 0 6 0]Buona fortuna. Hai tutto[n]il mio supporto.[n][w][e]

[msg MSG_FLOWERSHOP_NOTOPEN]
[s]Ci sono tanti tipi di fiori[n]in esposizione. Verr韻 qui a[n]comprarli, la prossima volta.[n][w][e]

[msg MSG_FLOWER_BAITO_COMMIT_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Hai fatto domanda per lavorare[n]part-time da questo fioraio,[n]vero?[n][w][e]

[msg MSG_FlowerShop_ActQ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]I fiori hanno un buon profumo...[n]Cosa vuoi fare?[n][w][e]

[sel FLOWER_SEL top]
[s]Lavorer韻 qui.[e]
[s]Compro qualcosa.[e]
[s]Niente.[e]

[msg MSG_FLOWER_NotBaitoDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Se non ricordo male[n]hai fatto domanda per lavorare[n]part-time qui, giusto?[n][w][e]
[s][f 4 10 65535 0 0]Credo che cercassero persone solo[n][clr 2]di giorno[clr 27]. Potrai farlo[n]un'altra volta.[n][w][e]

[msg MSG_FLOWER_NotBaitoDay_c [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Credo che cerchino persone solo[n]nel [clr 2]pomeriggio[clr 27].[n][w][e]

[msg MSG_FLOWERSHOP_START_01 [Fiorista]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]I fiori rendono sempre[n]felici le persone.[n]Vuoi fare un bel regalo?[n][w][e]

[msg MSG_FLOWERSHOP_START_02 [Fiorista]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]Abbiamo anche lozioni e frammenti[n]di corteccia. Dai pure un'occhiata[n]ai nostri prodotti.[n][w][e]

[msg MSG_FLOWERSHOP_START_03 [Fiorista]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]I fiori possono migliorare[n]notevolmente l'umore. Consiglio[n]di trattarli con del concime.[n][w][e]

[msg MSG_FLOWERSHOP_START_04 [Hanasaki]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]Benvenuto. Cosa desideri oggi?[n][w][e]

[msg MSG_FLOWERSHOP_BUY_END [Fiorista]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Grazie per l'acquisto.[n][w][e]

[msg MSG_FLOWERSHOP_BUY_END_n [Hanasaki]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Grazie per l'acquisto.[n][w][e]

[msg MSG_FLOWERSHOP_NOTBUY_EN [Fiorista]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Grazie mille.[n]Torna presto a trovarci.[n][w][e]

[msg MSG_FLOWERSHOP_NOTBUY_EN_2 [Hanasaki]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Grazie mille.[n]Torna presto a trovarci.[n][w][e]

[msg MSG_FlowerBaito_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Lavorando dal fioraio potresti[n]migliorare la [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MSG_FlowerBaito_StartSPd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Ho sentito che molti andranno[n][clr 2]mercoled淫 e sabato[clr 27]...[n][w][e]

[msg MND_Flower_ParamUpInfo]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_Flower_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_FlowerBaito_Ask [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vuoi approfittarne per lavorare?[n][w][e]

[sel SEL_FlowerBaitoFix top]
[s]Voglio lavorare.[e]
[s]Ci devo pensare.[e]

[msg MSG_SYSTEM_SHORTCUT_FLOW]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il fioraio[clr 0] a Shibuya.[n][w][e]

[msg MSG_WATCHSHOP_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Non puoi leggere l'ora dal[n]telefono invece di comprare[n]un orologio costoso?[n][w][e]

[msg MSG_WATCHSHOP]
[s]Qui c'因 una vasta selezione[n]di orologi, con stili adatti[n]ai giovani e agli anziani...[n][w][e]

[msg MSG_LEATHERSHOP_MORU [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Uhm? Qui dentro c'因[n]odore di animali...[n]Possiamo andarcene?[n][w][e]

[msg MSG_LEATHERSHOP]
[s]L'aria 因 satura[n]dell'odore del cuoio...[n][w][e]

[msg MSG_COSME_NOTOPEN]
[s]Qui vendono trucchi e[n]profumi. Ci torner韻 quando[n]avr韻 bisogno di qualcosa...[n][w][e]

[msg MSG_COSME_INFO [Commessa del negozio di cosmetici]]
[s][f 4 23 1 13 3 5 65534 0][vp 8 2 1 0 13 0]Benvenuto.[n]Devi acquistare un regalo?[n]O magari qualcosa per te?[n][w][e]

[msg MSG_COSME_THANKS [Commessa del negozio di cosmetici]]
[s][vp 8 2 1 0 13 0]Grazie mille![n][w][e]

[msg MSG_COSME_NOTBUY [Commessa del negozio di cosmetici]]
[s][vp 8 2 1 0 13 0]Torna presto a farci visita.[n][w][e]

[msg MSG_SHOESSHOP_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Guarda quanto sono alti quei tacchi.[n]Potrebbero essere usati come armi.[n][w][e]

[msg MSG_SHOESSHOP]
[s]Qui vendono scarpe con[n]tacchi alti...[n][w][e]

[msg MSG_PHOTO_MACHINE_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Ci sono tante opzioni per[n]far sembrare pi迂 belle le[n]persone nelle foto, ma...[n][w][e]
[s][f 4 10 65535 0 0]為 una macchina per le[n]fototessere, giusto? Queste foto[n]non andrebbero manipolate...[n][w][e]

[msg MSG_PHOTO_MACHINE]
[s]為 una macchina per[n]scattare fototessere.[n][w][e]
[s]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MSG_DEADEND01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Sembra che pi迂 avanti non[n]ci sia nulla.[n]Torniamo indietro.[n][w][e]

[msg MSG_DEADEND01]
[s]Non ho niente da[n]vedere pi迂 avanti...[n][w][e]

[msg MND_CO_NG_COMMON_000]
[s][vp 1 0 0 0 0 0]Non credo di avere tempo[n]per fare deviazioni...[n][w][e]

[msg MND_E10920100_NG_UNDER_0]
[s][vp 1 0 0 0 0 0]Sembra che i tornelli[n]della [clr 2]linea Ginza[clr 27][n]siano su questo piano...[n][w][e]

[msg MND_E10920100_NG_Hideout]
[s][vp 1 0 0 0 0 0]C'因 un corridoio di[n]interscambio pi迂 avanti.[n][w][e]
[s][vp 1 0 0 0 0 0]Per韻, la linea che devo prendere[n]non 因 da quella parte...[n][w][e]

[msg MND_E10920100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]為 un distributore automatico.[n][w][e]
[s][vp 1 0 0 0 0 0]Non ho sete.[n][w][e]

[msg MND_E10920100_CHK_BAKERY]
[s][vp 1 0 0 0 0 0]Gli scaffali della panetteria sono[n]colmi di pane appena sfornato.[n][w][e]
[s][vp 1 0 0 0 0 0]Il profumo invitante del pane[n]si sta diffondendo[n]nei paraggi...[n][w][e]

[msg MSG_E243301_CHK_SHOP_NG_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_E243301_CHK_SHOP_NG__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Che succede? Su, andiamo[n]da qualche altra parte![n][w][e]

[msg MSG_E243301_CHK_SHOP_NG__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Al momento non hai niente da fare[n]qui, giusto? Torniamoci quando[n]ne avrai il tempo![n][w][e]

[msg MSG_E19310100_NG_GINZASE [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6023 65535 0]Dobbiamo prendere la JL a Shibuya.[n]Vogliamo sbrigarci?[n][w][e]

[msg MSG_E19310100_NG_HIDEOUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Ora dobbiamo prendere la JL.[n]Non dovremmo andare[n]verso la piazza?[n][w][e]

[msg MSG_E24420300_NG_GINZASE [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Un momento. Dobbiamo prendere la JL[n]per arrivare a Shinjuku. I tornelli[n]sono nella direzione della piazza.[n][w][e]

[msg MSG_E24420300_NG_HIDEOUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7172 65535 0]Ma dove vai? Su,[n]andiamo a Shinjuku![n][w][e]

[msg MSG_E655104_CHK_SHOP_NG_ [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1140 0 0]Ehi, prendiamo dei fiori[n]per il capo, giusto?[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__2 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1139 0 0]Al momento qui non ti serve[n]niente, giusto?[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__3 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1111 0 0]Questo non 因 un fioraio.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__4 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Uhm, non sono male, ma...[n]ora andiamo a prendere i fiori.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__5 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Lo fai apposta, eh?[n]Il posto non 因 questo.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__6 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1036 0 0]Dovremmo andare dal fioraio![n]Avanti! Il fioraio! IL FIORAIO![n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__7 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0]Hai gi稲 lavorato da un fioraio,[n]vero? Andiamo.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__8 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0]Ho sentito che al centro[n]commerciale sotterraneo c'因 un[n]fioraio. Andiamo a controllare.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__9 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0]Ehi! Stiamo andando a[n]comprare i fiori, no?[n][w][e]

[msg MSG_E65510400_FLOWER_000 [Hanasaki]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 1 18 0]Oh, [lName]-kun?[n]Che ci fai qui?[n][f 1 3 65535][w][e]

[sel SEL_E65510400_FLOWER_000 top]
[s]Sono qui per un regalo.[e]
[s]Vorrei fare un regalo.[e]

[msg MSG_E65510400_FLOWER_001 [Hanasaki]]
[s][vp 8 0 1 2 18 0]Capisco! Beh, conta su di me![n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_002 [Hanasaki]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 3 18 0]Cos淫 dovrebbe andare. Ho cercato[n]di farlo il pi迂 semplice possibile.[n][f 1 3 65535][w][e]
[s][vp 8 0 1 4 18 0]OK, mi devi...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_002_2 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Aspetta! Lascia che paghi io.[n]Ti stai occupando di me[n]tutto da solo, perci韻...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]為 il minimo per esprimerti la[n]mia gratitudine.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_003 [Hanasaki]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 7 18 0]Auguri! Faccio il tifo per te![n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_100 [Negoziante]]
[s][f 4 23 1 18 6 10 0 10][vp 8 0 1 8 18 0]Benvenuto! Cercavi qualche[n]fiore in particolare, oggi?[n][f 1 3 65535][w][e]

[sel SEL_E65510400_FLOWER_100 top]
[s]Sono qui per un regalo.[e]
[s]Vorrei fare un regalo.[e]

[msg MSG_E65510400_FLOWER_101 [Negoziante]]
[s][vp 8 0 1 9 18 0]Capito. Me ne occupo subito.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_103 [Negoziante]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 10 18 0]Ecco qui! Te l'ho fatto il[n]pi迂 semplice possibile.[n][f 1 3 65535][w][e]
[s][vp 8 0 1 11 18 0]Il totale 因...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_103_2 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Aspetta! Lascia che paghi io.[n]Ti stai occupando di me[n]tutto da solo, perci韻...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]為 il minimo per esprimerti la[n]mia gratitudine.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_104 [Negoziante]]
[s][f 4 23 1 18 6 10 0 10][vp 8 0 1 14 18 0]Grazie per l'acquisto. Auguri![n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_005 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 15 65535 0]Ci siamo! Il regalo 因 pronto![n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_000_00 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]Bene, ora sei pronto per[n]l'appuntamento. Sai gi稲 chi[n]intendi invitare... giusto?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Non preoccuparti, sono un[n]gentiluomo e conosco le buone[n]maniere. Non ti star韻 fra i piedi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]Perfetto, buona fortuna![n][f 1 3 65535][w][e]

[msg MND_E65510400_TEL_001_00]
[s][vp 1 0 0 0 0 0]Inviter韻...[n][f 1 3 65535][w][e]

[sel SEL_E65510400_TEL_001_00 top]
[s]Vediti con Ohya[ref 0 0][e]
[s]Vediti con Takemi[ref 1 1][e]
[s]Vediti con Kawakami[ref 2 2][e]
[s]Vediti con Hifumi[ref 3 3][e]
[s]Vediti con Chihaya[ref 4 4][e]
[s]Vediti con Futaba[ref 5 5][e]
[s]Vediti con Ann[ref 6 6][e]
[s]Vediti con Makoto[ref 7 7][e]
[s]Vediti con Haru[ref 8 8][e]
[s]Vediti con Sumire[ref 9 9][e]

[msg MSG_E65510400_TEL_002_00 [Ohya]]
[s][bup 0 107 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Eeeehi! Come va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_01 [Takemi]]
[s][bup 0 108 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Che c'因? Qualcosa non va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_02 [Kawakami]]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]Scusa, sono a scuola adesso...[n]Di cosa hai bisogno?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_03 [Hifumi]]
[s][bup 0 106 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]A proposito...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_04 [Chihaya]]
[s][bup 0 113 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]Oh, [lName]-san? Qualcosa non va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_05 [Futaba]]
[s][bup 0 8 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]Ehil稲. Che succede?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_06 [Ann]]
[s][bup 0 4 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Ehi. Come va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_07 [Makoto]]
[s][bup 0 6 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 16 65535 0][fName]? Qualcosa non va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_08 [Haru]]
[s][bup 0 7 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 20 65535 0][fName]-kun? Qualcosa non va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_09 [Sumire]]
[s][bup 0 10 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]S淫, parla Yoshizawa.[n][f 1 3 65535][w][e]

[sel SEL_E65510400_TEL_002_00 top]
[s]Vieni a Shinagawa.[e]
[s]Andiamo a Shinagawa.[e]

[msg MSG_E65510400_TEL_003_00 [Ohya]]
[s][bup 0 107 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]Adesso? Cos淫 all'improvviso?[n][f 1 3 65535][w][e]
[s][bup 0 107 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Beh, ogni desiderio del mio ragazzo[n]因 un ordine! Il tempo di finire[n]di lavorare e mi avvio.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_01 [Takemi]]
[s][bup 0 108 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]Shinagawa? E perch姻? Beh, immagino[n]sia una domanda stupida...[n][f 1 3 65535][w][e]
[s][bup 0 108 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Sono al lavoro, ma posso staccare[n]prima. Ci vediamo l稲.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_02 [Kawakami]]
[s][bup 0 109 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]Adesso? 為 un po'... improvviso.[n][f 1 3 65535][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]Comunque OK. Ho quasi finito qui,[n]poi mi avvio.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_03 [Hifumi]]
[s][bup 0 106 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]A... Shinagawa?[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]Perch姻 no... Fammi prendere le[n]mie cose e mi avvio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]A pi迂 tardi...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_04 [Chihaya]]
[s][bup 0 113 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]Shinagawa? Certo...[n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Staccher韻 un po' prima, allora.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_05 [Futaba]]
[s][bup 0 8 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Shinagawa...? O-OK, credo.[n][f 1 3 65535][w][e]
[s][bup 0 8 2 65535 1][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]Sei fuori per caso? Potresti[n]venirmi a... No, vabbeh,[n]lascia stare. Ci vediamo l稲.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]D'accordo, a presto![n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_06 [Ann]]
[s][bup 0 4 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]Shinagawa? OK, contaci.[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]E guarda caso 因 il White Day, eh?[n]Onestamente, speravo che[n]me lo chiedessi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]Bene, il tempo di prepararmi e ci[n]si vede l稲.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_07 [Makoto]]
[s][bup 0 6 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Oh? Uhm... OK.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Grazie al cielo mi hai chiamata.[n]Cominciavo a preoccuparmi.[n]Oggi 因... beh, lo sai.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]OK. Il tempo di cambiarmi e[n]ci vediamo l稲.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_08 [Haru]]
[s][bup 0 7 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]A Shinagawa? Ah... certo.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Ma quindi... 因 un appuntamento![n]Ne sarei felice.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]OK, vado a prepararmi. Ci[n]vediamo l稲?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_09 [Sumire]]
[s][bup 0 10 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]Adesso? Certo, va bene![n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]Oggi non mi alleno, perci韻 mi[n]avvio subito.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]Ci vediamo l淫![n][f 1 3 65535][w][e]

[msg MND_E65510400_TEL_004_00]
[s][vp 1 0 0 0 0 0]Devo prepararmi per andare a[n]Shinagawa...[n][f 1 3 65535][w][e]

[msg MND_E65510400_TEL_005_00]
[s][vp 1 0 0 0 0 0]Devo tornare al Leblanc...[n][f 1 3 65535][w][e]

[msg EX_0103_0108_LOCK_mes01 [Donna]]
[s][vp 1 0 0 0 0 0]Pare che qui le borse fortunate[n]siano incredibili. Si dice[n]valgano 10 volte il loro prezzo![n][w][e]

[msg EX_0103_0108_LOCK_mes02 [Uomo]]
[s][vp 1 0 0 0 0 0]Credo che si sia sparsa la[n]voce, vista la folla.[n][w][e]
[s][vp 1 0 0 0 0 0]Credo che qualcuno[n]stia pensando di rivendere[n]tutto ci韻 che trover稲.[n][w][e]

[msg EX_0103_0108_LOCK_mes03 [Donna]]
[s][vp 1 0 0 0 0 0]S淫, c'因 tantissima gente![n]Ma voglio prenderne una![n][w][e]

[msg EX_0103_0108_LOCK_mes04]
[s][vp 1 0 0 0 0 0]Sembra sia la fila per le[n]borse fortunate.[n][w][e]
[s][vp 1 0 0 0 0 0]Dubito di poter proseguire oltre...[n][w][e]

[msg EX_0103_0108_LOCK_mes00]
[s][vp 1 0 0 0 0 0]C'因 troppa gente per[n]poter proseguire...[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

