[msg MSG_DUMMY]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_SCHOOL_1STDAY]
[s]Se non ricordo male, la[n][clr 2]linea Ginza[clr 27] dovrebbe portarmi[n]ad Aoyama-Itchome, dov'因 la scuola...[n][w][e]

[msg MSG_TRAIN_WAIT]
[s]Aspettiamo il prossimo treno...[n][w][e]

[msg MND_E14410100_NG_HIROBA_]
[s][vp 8 2 65535 0 0 0]Sar稲 meglio che mi sbrighi[n]a trovare Ann...[n][w][e]

[msg MND_E10920100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Devo prendere la[n][clr 2]linea Ginza[clr 27] a Shibuya...[n][w][e]

[msg MND_E12710100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Se salgo su questo treno[n]far韻 tardi...[n][w][e]
[s][vp 8 2 65535 0 0 0]Sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MSG_E24310100_DENENTOSI_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, ma dove vai?[n]Non volevi cercare[n]altre informazioni?[n][w][e]

[msg MSG_E24330100_DENENTOSI_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Dove vai? Pensavo che dovessi[n]esplorare Shibuya...[n][w][e]

[msg MND_E65010100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Per andare a Kichijoji[n]devo prendere la [clr 2]linea Inoue[clr 27]...[n][w][e]

[msg MND_E14410100_NG_YAMANOT]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MND_E10920100_CHK_KIOSUK]
[s][vp 8 2 65535 0 0 0]C'因 tantissima merce di vario[n]tipo esposta...[n][w][e]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo[n]di mettermi a scegliere qualcosa...[n][w][e]

[msg MND_E12710100_CHK_KIOSUK]
[s][vp 8 2 65535 0 0 0]C'因 tantissima merce di vario[n]tipo esposta...[n][w][e]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo[n]di mettermi a scegliere qualcosa...[n][w][e]

[msg MND_COMMON_CHK_KIOSUKU_0]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]fare shopping...[n][w][e]

[msg MND_E10920100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Ci sono tantissime riviste[n]piene di annunci di[n]lavoro part-time.[n][w][e]
[s][vp 8 2 65535 0 0 0]Chiss稲 che tipo di lavori potrei[n]trovare da queste parti...[n][w][e]

[msg MND_E12710100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Ci sono tantissime riviste[n]piene di annunci di[n]lavoro part-time.[n][w][e]
[s][vp 8 2 65535 0 0 0]Chiss稲 che tipo di lavori potrei[n]trovare da queste parti...[n][w][e]

[msg MND_E14410100_CHK_BAITO_]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_BAITO_MAG]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]cercare lavori part-time...[n][w][e]

[msg MND_E10920100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Appena pi迂 avanti sembra esserci[n]un centro commerciale sotterraneo.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Appena pi迂 avanti sembra esserci[n]un centro commerciale sotterraneo.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora dovrei sbrigarmi[n]e filare dritto a scuola...[n][w][e]

[msg MND_E14410100_NG_SIBUTIK]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MND_E10920100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]La strada pi迂 avanti sembra[n]portare a Central Street.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora sar稲 meglio raggiungere[n]in fretta la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]La strada pi迂 avanti sembra[n]portare a Central Street.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora dovrei sbrigarmi[n]e filare dritto a scuola...[n][w][e]

[msg MND_E14410100_NG_CENTER_]
[s][vp 8 2 65535 0 0 0]Non pu韻 essere lontana.[n]Prover韻 a cercare qui intorno...[n][w][e]

[msg MND_E10920100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Questo negozio vende[n]succo appena spremuto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Quando avr韻 un po' di tempo[n]lo prover韻...[n][w][e]

[msg MND_E12710100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Questo negozio vende[n]succo appena spremuto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Quando avr韻 un po' di tempo[n]lo prover韻...[n][w][e]

[msg MND_E14410100_CHK_JUICEB]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_JUICEBAR_]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]acquistare del succo...[n][w][e]

[msg MND_E10920100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Questo sembra un manjuu shop.[n][w][e]
[s][vp 8 2 65535 0 0 0]Qui vendono diverse variet稲[n]di manjuu e daifuku...[n][w][e]

[msg MND_E12710100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Questo sembra un manjuu shop.[n][w][e]
[s][vp 8 2 65535 0 0 0]Qui vendono diverse variet稲[n]di manjuu e daifuku...[n][w][e]

[msg MND_E14410100_CHK_OMIYAG]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_OMIYAGE_S]
[s][vp 8 2 65535 0 0 0]Adesso non ho tempo di[n]fare shopping...[n][w][e]

[msg MND_E10920100_NG_GATE_HI]
[s][vp 8 2 65535 0 0 0]Devo prendere la[n][clr 2]linea Ginza[clr 27] a Shibuya...[n]Meglio raggiungere la banchina.[n][w][e]

[msg MND_E12710100_NG_GATE_HI]
[s][vp 8 2 65535 0 0 0]Non ho tempo di tornare[n]indietro. Meglio prendere la[n][clr 2]linea Ginza[clr 27] e andare a scuola...[n][w][e]

[msg MND_E14410100_NG_DENENTO]
[s][vp 8 2 65535 0 0 0]Non pu韻 essere lontana.[n]Prover韻 a cercare qui intorno...[n][w][e]

[msg MND_E12710100_NG_GATE_IN]
[s][vp 8 2 65535 0 0 0]Non ho tempo di tornare[n]indietro. Meglio prendere la[n][clr 2]linea Ginza[clr 27] e andare a scuola...[n][w][e]

[msg MND_E10920100_NG_GATEOUT]
[s][vp 8 2 65535 0 0 0]Sul cartello qui sopra[n]c'因 scritto "Linea Inogami".[n][w][e]
[s][vp 8 2 65535 0 0 0]Devo prendere la[n][clr 2]linea Ginza[clr 27], ma credo di[n]essere dalla parte sbagliata.[n][w][e]

[msg MND_E14410100_NG_TOKYU_0]
[s][vp 8 2 65535 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MND_E10920100_GOTO_INOKA]
[s][vp 8 2 65535 0 0 0]Pi迂 avanti sembrano esserci[n]i tornelli della linea Inogami.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_GOTO_INOKA]
[s][vp 8 2 65535 0 0 0]Pi迂 avanti sembrano esserci[n]i tornelli della linea Inogami.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora, 因 meglio andare[n]verso la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_COMMON_GOTO_INOKASIR]
[s][vp 8 2 65535 0 0 0]Non ho alcun motivo di[n]prendere la linea Inogami...[n][w][e]

[msg MND_E10920100_CHK_ADJUST]
[s][vp 8 2 65535 0 0 0]為 una macchina per calcolare[n]il prezzo del biglietto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora non ho bisogno[n]di usarla...[n][w][e]

[msg MND_E12710100_CHK_ADJUST]
[s][vp 8 2 65535 0 0 0]為 una macchina per calcolare[n]il prezzo del biglietto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora non ho bisogno[n]di usarla...[n][w][e]

[msg MND_COMMON_CHK_ADJUSTMEN]
[s][vp 8 2 65535 0 0 0]為 una macchina per calcolare[n]il prezzo del biglietto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Per ora non ho bisogno[n]di usarla...[n][w][e]

[msg MND_E10920100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]為 una macchina per[n]scattare fototessere.[n][w][e]
[s][vp 8 2 65535 0 0 0]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MND_E12710100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]為 una macchina per[n]scattare fototessere.[n][w][e]
[s][vp 8 2 65535 0 0 0]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MND_E14410100_CHK_PHOTO_]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_PHOTO_MAC]
[s][vp 8 2 65535 0 0 0]為 una macchina per[n]scattare fototessere.[n][w][e]
[s][vp 8 2 65535 0 0 0]Sembra avere diverse funzioni.[n]Pu韻 aggiungere effetti o[n]snellire il volto...[n][w][e]

[msg MND_E10920100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Vedo pochissime chiavi negli[n]armadietti. La maggior parte 因[n]gi稲 usata da altre persone...[n][w][e]

[msg MND_E12710100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Vedo pochissime chiavi negli[n]armadietti. La maggior parte 因[n]gi稲 usata da altre persone...[n][w][e]

[msg MND_E14410100_CHK_COIN_L]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_COIN_LOCK]
[s][vp 8 2 65535 0 0 0]Vedo pochissime chiavi negli[n]armadietti. La maggior parte 因[n]gi稲 usata da altre persone...[n][w][e]

[msg MND_E10920100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Sullo schermo 因 mostrata[n]l'immagine di un prodotto.[n][w][e]
[s][vp 8 2 65535 0 0 0]為 touch screen, per comprare[n]gli oggetti mostrati basta[n]toccarli...[n][w][e]

[msg MND_E12710100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Sullo schermo 因 mostrata[n]l'immagine di un prodotto.[n][w][e]
[s][vp 8 2 65535 0 0 0]為 touch screen, per comprare[n]gli oggetti mostrati basta[n]toccarli...[n][w][e]

[msg MND_E14410100_CHK_NEXT_J]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_NEXT_JUIC]
[s][vp 8 2 65535 0 0 0]Ora non ho tempo di[n]fermarmi per comprare da bere...[n][w][e]

[msg MND_E10920100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Questo distributore automatico[n]vende frutta.[n][w][e]
[s][vp 8 2 65535 0 0 0]Ce n'因 di diverso tipo,[n]tutta imbustata in file...[n][w][e]

[msg MND_E12710100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Questo distributore automatico[n]vende frutta.[n][w][e]
[s][vp 8 2 65535 0 0 0]Ce n'因 di diverso tipo,[n]tutta imbustata in file...[n][w][e]

[msg MND_E14410100_CHK_FRUIT_]
[s][vp 8 2 65535 0 0 0]Devo sbrigarmi a[n]trovare Ann...[n][w][e]

[msg MND_COMMON_CHK_FRUIT_MAC]
[s][vp 8 2 65535 0 0 0]Penso che la frutta la comprer韻[n]un'altra volta...[n][w][e]

