[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_LOTTER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Non ho vinto granch姻, ma sono[n]felice lo stesso.[n][w][e]

[msg MSG_LAST_GREETING_HACHI_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Andr韻 ovunque andrai tu.[n]Non mi piace aspettare.[n][w][e]

[msg MSG_LAST_GREETING_SMOKE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non andartene senza dire niente.[n]Andiamo a salutare tutti.[n][w][e]

[msg MSG_LAST_GREETING_GOTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non conosci nessuno che[n]andrebbe qui, vero? Andiamo[n]da qualche altra parte.[n][w][e]

[msg MSG_LAST_GREETING_TICKET [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Il tuo abbonamento 因 quasi[n]scaduto, ma immagino che non[n]te ne servir稲 uno nuovo...[n][w][e]

[msg MSG_LAST_GREETING_STAIRS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non conosci nessuno che[n]andrebbe qui, vero? Andiamo[n]da qualche altra parte.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non conosci nessuno che[n]andrebbe qui, vero? Andiamo[n]da qualche altra parte.[n][w][e]

[msg MSG_LAST_GREETING_LOTTER_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non 因 il momento di fermarsi[n]a comprare un gratta e vinci![n]Andiamo dagli altri![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MND_0103]
[s]Non devo fare niente qui...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Dog]
[s]C'因 la statua di un cane fedele...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_Yamanote_NotOpen [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Che c'因? Non ci sono posti[n]che vuoi visitare, vero?[n][w][e]

[msg MSG_Yamanote_Shinjuku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Oh, prendiamo il treno?[n]Andiamo a Shinjuku,[n]gi稲 che ci siamo.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]In un posto cos淫 colorato[n]c'因 molto da imparare.[n]La tariffa 因 [clr 2]190[clr 27] yen, per韻...[n][w][e]

[sel SEL_Yamanote_SINJUKU top]
[s]Andiamo a Shinjuku.[e]
[s]Lasciamo stare.[e]

[msg MSG_Yamanote_AllGo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Prendiamo il treno? Puoi andare[n]a Shinjuku, un posto da adulti,[n]o ad Akihabara, il paradiso dei geek.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Potresti imparare qualcosa.[n]Per andare a Shinjuku servono[n][clr 2]190[clr 27] yen, mentre per Akihabara [clr 2]240[clr 27] yen.[n][w][e]

[sel YAMANOTE_ALL_SEL top]
[s]Andiamo a Shinjuku.[e]
[s]Andiamo ad Akihabara.[e]
[s]Lasciamo stare.[e]

[msg MSG_Yamanote_MoneyNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]...Ehi, aspetta un attimo.[n]Non hai abbastanza soldi.[n][w][e]

[msg MSG_Yamanote_GreetingDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Oh, vai a trovare qualcuno?[n]Dove vai?[n][w][e]

[msg MND_GATE_0103]
[s]Andiamo da un'altra parte...[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Vuoi spostarti in[n]un'altra zona?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]S淫, andiamo.[e]
[s]No, non ancora.[e]

[msg MSG_CHK_LOTTERY_SHOP_01]
[s]Non ho tempo di acquistare[n]biglietti della lotteria...[n][w][e]

[msg MSG_LotShop_NG_Summer_Ha [Commessa della lotteria]]
[s]Partecipi alla lotteria Summer[n]Mammoth, vero? I vincitori saranno[n]annunciati dal 22 agosto in poi.[n][w][e]

[msg MSG_LOTSHOP_START_Shop1 [Commessa della lotteria]]
[s]Benvenuto al chiosco della[n]lotteria! Cosa vuoi fare?[n][w][e]

[msg MSG_LOTSHOP_START_Shop2 [Commessa della lotteria]]
[s]Vuoi comprare un biglietto della[n]lotteria? Anche gli studenti[n]possono prenderne uno![n][w][e]

[msg MSG_LotShop_End_OnlyNorm [Commessa della lotteria]]
[s]Grazie per l'acquisto.[n][w][e]
[s]I risultati saranno annunciati[n]tra una settimana, il [var 1]/[var 0].[n]Attendi con trepidazione.[n][w][e]

[msg MSG_LotShop_End_OnlySumm [Commessa della lotteria]]
[s]Grazie per l'acquisto.[n][w][e]
[s]I risultati saranno annunciati[n]il 22 agosto! Ricorda di[n]passare![n][w][e]

[msg MSG_LotShop_End_Double [Commessa della lotteria]]
[s]Grazie per l'acquisto.[n][w][e]
[s]I risultati della lotteria Summer[n]Mammoth saranno annunciati[n]il 22 agosto![n][w][e]
[s]I risultati per il biglietto che[n]hai appena acquistato saranno[n]annunciati tra una settimana, il [var 1]/[var 0].[n][w][e]

[msg MSG_LotShop_SummerLotInf [Commessa della lotteria]]
[s]I biglietti della [clr 2]lotteria Summer Mammoth[clr 27][n]sono disponibili! Venite[n]a comprarne uno![n][w][e]

[msg MSG_LotShop_End_SummerM [Commessa della lotteria]]
[s]Grazie per aver partecipato[n]alla lotteria Summer Mammoth.[n][w][e]
[s]I vincitori saranno annunciati[n]il 22 agosto. Speriamo che[n]non vediate l'ora.[n][w][e]

[msg MSG_LotShop_ReStart [Commessa della lotteria]]
[s]I risultati saranno annunciati[n]tra una settimana, il [var 1]/[var 0].[n]Attendi con trepidazione.[n][w][e]

[msg MSG_LOTSHOP_LOT_YET_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]I risultati saranno annunciati[n]il [var 1]/[var 0], giusto?[n]Torniamo un'altra volta.[n][w][e]

[msg MSG_LOTSHOP_PUBLISH_SHOP [Commessa della lotteria]]
[s]Hai un biglietto della lotteria?[n]Controllo il risultato![n][w][e]

[msg MSG_LOTSHOP_PUBLISH_SHOP_2 [Commessa della lotteria]]
[s]Hai un biglietto della lotteria[n]Summer Mammoth?[n]Controllo il risultato![n][w][e]

[msg MSG_LOTSHOP_RESULT [Commessa della lotteria]]
[s]Il risultato dell'estrazione 因...[n][w][e]

[msg MSG_LOTSHOP_RESULT_01 [Commessa della lotteria]]
[s]......[n][w][e]
[s]......Un bel niente.[n][w][e]

[msg MSG_result_00 [Commessa della lotteria]]
[s]......[n][w][e]
[s]......![n][w][e]

[msg MSG_LOTSHOP_RESULT_02 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 100 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_03 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 300 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_04 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 2.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_05 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 5.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_06 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 10.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_07 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 100.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_Summe [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 30.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_Summe_2 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 50.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_LOTSHOP_RESULT_Summe_3 [Commessa della lotteria]]
[s]Congratulazioni![n][w][e]
[s]Hai vinto 100.000 yen. Te li[n]consegno subito.[n][w][e]

[msg MSG_Lottery_ATARI_Small [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Hai vinto, ma...[n]Beh, 因 meglio di[n]niente, immagino.[n][w][e]

[msg MSG_Lottery_ATARI_Big [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Che fortuna! Usa bene[n]quei soldi, OK?[n][w][e]

[msg MSG_Lottery_ATARI_TooBig [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 53138 65535 0]Uooooo! La dea bendata ti ha baciato![n]Domani sera cener韻 come un re![n][w][e]

[msg MSG_Lottery_Normal_Hazur [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]...Che delusione.[n][w][e]

[msg MSG_Lottery_ATARI_Small_ [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]Oh, ce l'hai fatta! Potrei darti[n]qualche idea su come spenderli![n][w][e]

[msg MSG_Lottery_ATARI_Big_Su [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1180 65535 0]Sei davvero fortunato! Ora puoi[n]permetterti di offrirmi un po'[n]di sushi, giusto?[n][w][e]

[msg MSG_Lottery_ATARI_MostBi [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Wow, pazzesco! Se hai vinto cos淫[n]tanto...[n][w][e]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Significa che avr韻 pi迂 sushi[n]di quanto riesca a mangiarne![n]Non vedo l'ora, [fName]![n][w][e]

[msg MSG_LOTSHOP_NotBuy [Commessa della lotteria]]
[s]Torna presto![n][w][e]

[msg MSG_LotShopSC_Start [Commessa della lotteria]]
[s]Benvenuto. Vuoi provare i[n]gratta e vinci? Sono pi迂[n]immediati della lotteria.[n][w][e]

[msg MSG_LotShop_SC_Start [Commessa della lotteria]]
[s]Il risultato del gratta e vinci[n]因 istantaneo.[n][w][e]

[msg MSG_LotShop_SC_Start02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]OK, diamo una bella grattata![n][w][e]

[msg MSG_Scratch_Info [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Vediamo... Gratta e vinci...[n]Devi grattare in[n]tre punti e...[n][w][e]
[s][f 4 10 65535 0 0]Vinci se trovi[n]una delle somme[n]di denaro in palio.[n][w][e]

[msg MSG_Scratch_Start01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Scatenati e gratta[n]tutto. Da quale[n]vuoi iniziare?[n][w][e]

[msg MSG_Scratch_Start02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Qual 因 il prossimo[n]che vuoi grattare?[n][w][e]

[sel SEL_Scratch top]
[s]A sinistra.[e]
[s]In mezzo.[e]
[s]Proviamo a destra.[e]

[msg MSG_Scratch_Happy01 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0]Eh...?[n][w][e]
[s][f 4 10 65535 0 0]Non 因 che...[n][w][e]

[msg MSG_Scratch_Happy_5000 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Hai vinto! Sono 5.000 yen![n][w][e]

[msg MSG_Scratch_Happy_1000 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Hai vinto! Sono 1.000 yen![n][w][e]

[msg MSG_Scratch_Happy_200 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1022 65535 0]Hai vinto... ma...[n]Sono solo 200 yen.[n][w][e]

[msg MSG_Scratch_Error [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1182 65535 0]M-Meh... Hai perso.[n][w][e]

[msg MSG_Scratch_last [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Ne resta uno...[n]Ora, diamo un'occhiata![n][w][e]

[msg MSG_Scratch_End_atari01 [Commessa della lotteria]]
[s]Congratulazioni! Prendo subito[n]il tuo premio in denaro.[n][w][e]

[msg MSG_Scratch_End_atari02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Wow, hai vinto davvero![n]Torniamoci[n]ancora![n][w][e]

[msg MSG_Scratch_End_hazure01 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Che peccato...[n]Non hai vinto niente.[n][w][e]

[msg MSG_Scratch_End_hazure02 [Commessa della lotteria]]
[s]Grazie mille.[n]Torna presto a trovarci.[n][w][e]

[msg MSG_LotShop_SC_ReTry [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Per oggi hai grattato[n]abbastanza, giusto? Torniamo[n]un'altra volta.[n][w][e]

[msg MSG_HACHI_KOU_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Il cane fedele che ha aspettato[n]il padrone fino alla fine, eh?[n]La sua fedelt稲 因 commovente.[n][w][e]
[s][f 4 10 65535 0 0]Non abbandonarmi, OK?[n]Non sono il tipo che[n]rimane ad aspettare.[n][w][e]

[msg MSG_HACHI_KOU]
[s]為 la famosa statua di[n]quel cane fedelissimo...[n][w][e]

[msg MSG_SMOKE_SPACE_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Ehi... Non 因 il posto[n]adatto a uno[n]studente come te.[n][w][e]

[msg MSG_SMOKE_SPACE]
[s]Questa sembra un'area fumatori.[n]Dei minorenni non dovrebbero[n]trattenervisi...[n][w][e]

[msg MSG_MIYASITA_NG_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Qui non hai niente da fare,[n]vero? Andiamo[n]da un'altra parte![n][w][e]

[msg MSG_MIYASITA_NG]
[s]Non devo fare niente l淫.[n]Meglio tornare indietro...[n][w][e]

[msg MSG_TICKET_MACHINE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Se hai caricato la tessera,[n]non devi comprare[n]il biglietto, giusto?[n][w][e]

[msg MSG_TICKET_MACHINE]
[s]Non devo comprare[n]biglietti della linea JL...[n][w][e]

[msg MSG_STAIRS_LOT_SHOP_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Non hai niente da fare[n]pi迂 avanti, vero? Andiamo[n]da un'altra parte![n][w][e]

[msg MSG_STAIRS_LOT_SHOP]
[s]Non ho niente da[n]vedere pi迂 avanti...[n][w][e]

[msg MSG_DEADEND01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Non hai niente da fare[n]pi迂 avanti, vero? Andiamo[n]da un'altra parte![n][w][e]

[msg MSG_DEADEND01]
[s]Non ho niente da[n]vedere pi迂 avanti...[n][w][e]

[msg MND_E10920100_NG_CENTER_]
[s][vp 1 0 0 0 0 0]Dall'altra parte dell'incrocio[n]vedo Central Street.[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MND_E12710100_NG_CENTER_]
[s][vp 1 0 0 0 0 0]Dall'altra parte dell'incrocio[n]vedo Central Street.[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MND_E14410100_NG_CENTER_]
[s][vp 1 0 0 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MSG_E19310100_GOTO_MADAR [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7115 65535 0]Sicuro che sia di qua?[n]Non ricordo di aver visto case.[n][w][e]

[msg MSG_E19310100_GOTO_MADAR_2 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6127 65535 0]Dovrebbe trovarsi in un'area[n]residenziale oltre Central Street.[n][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dovremo camminare un po'.[n]OK, muoviamoci![n][w][e]

[msg MSG_E24420300_NG_CENTER_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Andiamo di qua.[n]Quella giornalista ci[n]sta aspettando, vero?[n][w][e]

[msg MND_E10920100_NG_UNDER_0]
[s][vp 1 0 0 0 0 0]Non ho tempo per tornare di sotto.[n]Per ora sar稲 meglio raggiungere[n]in fretta la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_NG_UNDER_0]
[s][vp 1 0 0 0 0 0]Non ho tempo per tornare di sotto.[n]Meglio prendere la[n][clr 2]linea Ginza[clr 27] e andare a scuola...[n][w][e]

[msg MSG_E19310100_NG_UNDER_C [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6001 65535 0]Qualcosa non va?[n]Su, andiamo a[n]Central Street.[n][w][e]

[msg MSG_E24420300_NG_UNDER_C [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Di l稲 non si va a casa tua?[n]Forza, dobbiamo prendere la JL.[n][w][e]

[msg MSG_E19310100_NG_UNDER_Y [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ehi, dove stai andando?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dai, raggiungiamo la casa di[n]Madarame. Non si trova verso[n]Central Street?[n][w][e]

[msg MSG_E24420300_NG_UNDER_Y [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Non dobbiamo scendere qui.[n]為 proprio vicino[n]ai tornelli.[n][w][e]

[msg MND_E10920100_NG_YAMANOT]
[s][vp 1 0 0 0 0 0]Ecco i tornelli della linea JL.[n][w][e]
[s][vp 1 0 0 0 0 0]Se ricordo bene, per arrivare a[n]scuola devo prendere[n]la [clr 2]linea Ginza[clr 27].[n][w][e]

[msg MND_E12710100_NG_YAMANOT]
[s][vp 1 0 0 0 0 0]Ecco i tornelli della linea JL.[n][w][e]
[s][vp 1 0 0 0 0 0]Se ricordo bene, per arrivare a[n]scuola devo prendere[n]la [clr 2]linea Ginza[clr 27].[n][w][e]

[msg MND_E14410100_NG_YAMANOT]
[s][vp 1 0 0 0 0 0]Per ora, sar稲 meglio che[n]mi sbrighi a trovare Ann...[n][w][e]

[msg MSG_E18010400_NG_YAMANOT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1183 0 0]Dove vai? Cerchiamo ancora[n]qualche negozio disposto a[n]comprare qualcosa da noi...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Oh, s淫! Quel negozio di armi[n]acquista oggetti, vero?[n]Proviamo![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]Proviamo![n][w][e]

[msg MSG_E19310100_NG_YAMANOT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Dove vai?[n]Non dovremmo dirigerci[n]verso Central Street?[n][w][e]

[msg MSG_E24310100_NG_YAMANOT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Ehi, ma dove vai?[n]Non volevi cercare[n]altre informazioni?[n][w][e]

[msg MSG_E24330100_NG_YAMANOT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1003 0 0]Dove vai? Pensavo che dovessi[n]esplorare Shibuya...[n][w][e]

[msg MSG_E24420300_YAMANOTE_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Grande! Andiamo[n]a Shinjuku![n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ora puoi andare a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Shinjuku 因 al di fuori dell'area[n]coperta dal tuo abbonamento,[n]giusto? Dovrai fare il biglietto.[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, non hai abbastanza soldi?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ti dar韻 un po' dei miei fondi[n]d'emergenza, ma la prossima volta[n]ricordati di portarli.[n][w][e]

[msg MND_E65010100_NG_YAMANOT]
[s][vp 8 2 65535 0 0 0]Per andare a Kichijoji[n]devo prendere la linea Inogami...[n][w][e]

[msg MSG_E18010300_NG_HIROBA_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1027 0 0]Qui in giro ci sono negozi[n]che acquisteranno qualcosa[n]da noi?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Oh, s淫! Quel negozio di armi[n]acquista oggetti, vero?[n]Proviamo![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]Proviamo![n][w][e]

[msg MSG_E19310100_NG_HIROBA_ [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Cos淫 non torneremo indietro?[n]So che il posto che cerchiamo[n]因 oltre Central Street.[n][w][e]

[msg MSG_E24420300_NG_HIROBA_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7197 65535 0]Perch姻 stiamo tornando indietro?[n]Dopo aver raggiunto la piazza[n]dobbiamo svoltare a destra.[n][w][e]

[msg MSG_E65010300_NG_HIROBA_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Ehi, dove stai andando? I[n]tornelli della linea Inogami sono[n]nel centro commerciale sotterraneo.[n][w][e]

[msg MND_E10920100_CHK_LOTTER]
[s][vp 1 0 0 0 0 0]Questo posto vende[n]biglietti della lotteria.[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora sar稲 meglio raggiungere[n]in fretta la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_CHK_LOTTER]
[s][vp 1 0 0 0 0 0]Questo posto vende[n]biglietti della lotteria.[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora sar稲 meglio raggiungere[n]in fretta la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E14410100_CHK_LOTTER]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_LOTTER [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7048 65535 0]Oh, vuoi comprare dei[n]biglietti della lotteria?[n][w][e]

[msg MSG_E19310100_CHK_LOTTER_2 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]E dove lo prendi il tempo?[n]Sbrighiamoci a raggiungere la[n]casa di Madarame![n][w][e]

[msg MSG_E24420300_CHK_LOTTER [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Quella roba comprala pi迂 tardi.[n]Dobbiamo andare subito a Shinjuku.[n][w][e]

[msg MND_COMMON_CHK_LOTTERY_S]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E10920100_CHK_HACHI_]
[s][vp 1 0 0 0 0 0]為 la famosa statua di[n]quel cane fedelissimo.[n][w][e]
[s][vp 1 0 0 0 0 0]Pare che la gente la usi[n]come punto di riferimento[n]per incontrarsi...[n][w][e]

[msg MND_E12710100_CHK_HACHI_]
[s][vp 1 0 0 0 0 0]為 la famosa statua di[n]quel cane fedelissimo.[n][w][e]
[s][vp 1 0 0 0 0 0]Pare che la gente la usi[n]come punto di riferimento[n]per incontrarsi...[n][w][e]

[msg MND_E14410100_CHK_HACHI_]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_HACHI_ [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 7115 65535 0]Quella statua non andr稲 da nessuna[n]parte. Ammirerai Buchiko un'altra[n]volta. Ora andiamo da Madarame.[n][w][e]

[msg MSG_E19310100_CHK_HACHI__2 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6166 65535 0]Mi sembra che da queste parti ci[n]sia pi迂 gente del solito.[n][w][e]

[msg MSG_E19310100_CHK_HACHI__3 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Forse 因 perch姻 c'因 una[n]sua mostra. Madarame 因[n]davvero famoso, eh?[n][w][e]

[msg MSG_E24420300_CHK_HACHI_ [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Mi aspettavo una folla del genere.[n]Meno male che abbiamo deciso[n]di vederci al piano di sopra.[n][w][e]

[msg MND_COMMON_CHK_HACHI_KOU]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_E10920100_CHK_SMOKE_]
[s][vp 1 0 0 0 0 0]Questa sembra un'area fumatori.[n]Dei minorenni non dovrebbero[n]trattenervisi...[n][w][e]

[msg MND_E12710100_CHK_SMOKE_]
[s][vp 1 0 0 0 0 0]Questa sembra un'area fumatori.[n]Dei minorenni non dovrebbero[n]trattenervisi...[n][w][e]

[msg MND_E14410100_CHK_SMOKE_]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_SMOKE_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, qui non hai niente[n]da fare, giusto?[n][w][e]

[msg MSG_E24420300_CHK_SMOKE_ [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7040 65535 0]Questo posto puzza di[n]sigarette. Muoviamoci a[n]salire sul treno.[n][w][e]

[msg MND_COMMON_CHK_SMOKE_SPA]
[s][vp 1 0 0 0 0 0]Non devo fare niente qui...[n][w][e]

[msg MND_E10920100_CHK_STREET]
[s][vp 1 0 0 0 0 0]Sembra che questo chiosco venda[n]giornali e riviste...[n][w][e]

[msg MND_E12710100_CHK_STREET]
[s][vp 1 0 0 0 0 0]Sembra che questo chiosco venda[n]giornali e riviste...[n][w][e]

[msg MND_E14410100_CHK_STREET]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_STREET [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Mmm? Stai guardando i manga?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Io ho gi稲 letto le nuove uscite[n]della settimana. Insomma, andiamo[n]verso casa di Madarame?[n][w][e]

[msg MSG_E24420300_CHK_STREET [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Qui non abbiamo niente da fare.[n]Su, andiamo a Shinjuku.[n][w][e]

[msg MND_COMMON_CHK_STREET_SH]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E10920100_CHK_GUIDE_]
[s][vp 1 0 0 0 0 0]C'因 una mappa dell'area.[n][w][e]
[s][vp 1 0 0 0 0 0]La banchina della linea Ginza[n]因 [clr 2]nell'Edificio Teikyu,[n]qui vicino[clr 27]...[n][w][e]

[msg MND_E12710100_CHK_GUIDE_]
[s][vp 1 0 0 0 0 0]C'因 una mappa dell'area.[n][w][e]
[s][vp 1 0 0 0 0 0]La banchina della linea Ginza[n]因 [clr 2]nell'Edificio Teikyu,[n]qui vicino[clr 27]...[n][w][e]

[msg MND_E14410100_CHK_GUIDE_]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_GUIDE_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7168 65535 0]Ti sei perso? So che 因 famoso,[n]ma non credo che abbiano messo[n]casa sua su quella mappa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Per prima cosa, andiamo verso[n]Central Street.[n][w][e]

[msg MSG_E24420300_CHK_GUIDE_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Cosa c'因 che non va?[n]All'inizio di quella zona ci[n]sono dei tornelli in bella mostra.[n][w][e]

[msg MND_COMMON_CHK_GUIDE_BOA]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_E10920100_CHK_CM_BOA]
[s][vp 1 0 0 0 0 0]為 un enorme cartellone.[n]Se sto troppo vicino, non riesco a[n]cogliere l'immagine nell'insieme...[n][w][e]

[msg MND_E12710100_CHK_CM_BOA]
[s][vp 1 0 0 0 0 0]為 un enorme cartellone.[n]Se sto troppo vicino, non riesco a[n]cogliere l'immagine nell'insieme...[n][w][e]

[msg MND_E14410100_CHK_CM_BOA]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_CM_BOA [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6168 65535 0]Non 因 pi迂 facile guardare da[n]lontano cose tanto enormi?[n][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]OK, dovremmo andare a[n]casa di Madarame.[n][w][e]

[msg MSG_E24420300_CHK_CM_BOA [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 7196 65535 0]Che hai da guardare?[n]Non 因 niente di speciale.[n][w][e]

[msg MND_COMMON_CHK_CM_BOARD_]
[s][vp 1 0 0 0 0 0]Adesso non ho tempo di[n]mettermi a guardare[n]le pubblicit稲...[n][w][e]

[msg MND_E10920100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Biglietterie automatiche della[n]linea JL. Per raggiungere la scuola[n]devo prendere la [clr 2]linea Ginza[clr 27].[n][w][e]

[msg MND_E12710100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Biglietterie automatiche della[n]linea JL. Per raggiungere la scuola[n]devo prendere la [clr 2]linea Ginza[clr 27].[n][w][e]

[msg MND_E14410100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_TICKET [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6001 65535 0]Cosa c'因 che non va?[n]Dobbiamo oltrepassare questo punto[n]per arrivare a destinazione.[n][w][e]

[msg MSG_E24420300_CHK_TICKET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Devi proprio farlo?[n][w][e]

[msg MND_COMMON_CHK_TICKET_MA]
[s][vp 1 0 0 0 0 0]Diverse biglietterie automatiche[n]della linea JL.[n]Per ora non mi servono.[n][w][e]

[msg MND_E10920100_CHK_STAIRS]
[s][vp 1 0 0 0 0 0]Queste scale scendono.[n]Non credo che da questa parte[n]trover韻 la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_CHK_STAIRS]
[s][vp 1 0 0 0 0 0]Non devo fare niente di[n]sopra. Sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MND_E14410100_CHK_STAIRS]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_STAIRS [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 6021 65535 0]Credo che dovremmo andare[n]verso la casa di Madarame[n]da Central Street.[n][w][e]

[msg MSG_E24420300_CHK_STAIRS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Da quella parte si va[n]verso la metro.[n]Andiamo, la JL 因 di qua.[n][w][e]

[msg MND_COMMON_CHK_STAIRS_LO]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg MND_E10920100_CHK_DEADEN]
[s][vp 1 0 0 0 0 0]Non credo che da questa parte[n]trover韻 la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E12710100_CHK_DEADEN]
[s][vp 1 0 0 0 0 0]Non devo fare niente di[n]sopra. Sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MND_E14410100_CHK_DEADEN]
[s][vp 1 0 0 0 0 0]Devo trovare Ann in fretta...[n][w][e]

[msg MSG_E19310100_CHK_DEADEN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Questa non 因 la strada[n]pi迂 lunga? Dobbiamo andare[n]verso Central Street.[n][w][e]

[msg MSG_E24420300_CHK_DEADEN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7197 65535 0]Ehi, non di l稲.[n]La linea JL 因 dall'altra parte.[n][w][e]

[msg MND_COMMON_CHK_DEADEND01]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg MSG_SPOT_GO_YAMANOTE]
[s]Dovrei prendere la[n][clr 6]linea Yamanote[clr 0]...[n][w][e]

[msg MSG_SPOT_GO_INOKASIRA]
[s]Dovrei prendere la[n][clr 6]linea Inokashira[clr 0]...[n][w][e]

[msg MSG_SPOT_GO_GINZALINE]
[s]Dovrei prendere la[n][clr 6]linea Ginza[clr 0]...[n][w][e]

[msg MSG_SPOT_ACCESS_LOT]
[s]Non ho tempo di acquistare[n]biglietti della lotteria...[n][w][e]

[msg MSG_SPOT_ACCESS_HATIKO]
[s]為 la famosa statua di[n]quel cane fedelissimo.[n][w][e]

[msg MSG_SPOT_ACCESS_SMOKE]
[s]Quest'area fumatori 因[n]piena di fumo...[n][w][e]

