[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_GOTO_B [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Ricordo quando il nostro ritrovo[n]era poco pi迂 avanti.[n]Non abbiamo lasciato tracce...[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non 因 il momento di[n]prendere il succo.[n]Andiamo a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_BAKERY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1047 65535 0]Peccato... Oggi c'因 il sole e[n]non vendono il panino con la[n]cotoletta dei giorni di pioggia.[n][w][e]

[msg MSG_LAST_GREETING_BAKERY_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Perch姻 stai fissando il pane?[n]Hai gi稲 fame?[n][w][e]

[msg MSG_LAST_GREETING_PAMPHL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]為 un volantino turistico. Mostra[n]diverse location famose dalle[n]quali ammirare i ciliegi in fiore.[n][w][e]
[s][f 4 10 65535 0 0]為 passato un anno...?[n]為 letteralmente volato.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Solo il personale autorizzato pu韻[n]superare questo punto. Qui non[n]conosci nessuno, vero?[n][w][e]

[msg MSG_LAST_GREETING_DISPLA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]In citt稲 ci sono[n]tantissime pubblicit稲 televisive.[n]Ormai ci siamo abituati.[n][w][e]

[msg MSG_LAST_GREETING_TICKET [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Il tuo abbonamento 因 quasi[n]scaduto, ma immagino che non[n]te ne servir稲 uno nuovo...[n][w][e]

[msg MSG_LAST_GREETING_MAN_TI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Le finestre sono chiuse.[n]Ormai 因 davvero[n]tutto automatico. [n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Che mi dici della tua citt稲[n]natale? In un anno potrebbe[n]essere cambiata.[n][w][e]

[msg MSG_LAST_GREETING_CheckD [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Il tuo abbonamento 因 ancora valido.[n]Puoi andare gratuitamente[n]a Yongen e Aoyama.[n][w][e]

[msg MSG_LAST_GREETING_Season [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]"Abbi cura di me". Uhm...[n]Assicurati di salutare tutti.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_Ajito [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Ti ricordi quando ci[n]incontravamo qui con gli altri?[n]D'accordo, andiamo altrove![n][w][e]

[msg MND_0103]
[s]Non devo fare niente qui...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_TRAIN_WAIT]
[s]Aspettiamo il prossimo treno...[n][w][e]

[msg MSG_NG_AJITO_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Non hai niente da fare[n]pi迂 avanti, vero?[n]Torniamo indietro![n][w][e]

[msg MSG_NG_AJITO]
[s]Questo passaggio arriva[n]all'edificio commerciale, ma[n]non ho motivo di andarci...[n][w][e]

[msg MSG_NG_Ajito_Night [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Se stai cercando di raggiungere[n]il Metaverso, fallo in giornate[n]in cui non hai da fare.[n][w][e]

[msg MSG_AjitoChange [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1037 65535 0]Non hai niente da fare[n]qui, vero? Mi sembra che[n]dovessimo trovarci al Leblanc.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Al momento non ho sete...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MSG_BAKERY_NOTOPEN]
[s]Sento il profumo del pane fresco.[n]Mangiandone un po'[n]mi caricherei di energia...[n][w][e]
[s]...Vendono anche prodotti[n]in edizione limitata.[n]Dovrei tornarci...[n][w][e]

[msg BAKERY_SELECT [Commessa della panetteria]]
[s][f 4 23 1 5 3 5 65534 0][vp 8 2 1 0 5 0]Benvenuto! Tutto ci韻 che vendiamo[n]因 stato appena sfornato![n]Approfittane![n][w][e]

[msg BAKERY_THANKS [Commessa della panetteria]]
[s][vp 8 2 1 0 5 0]Grazie mille.[n]Speriamo di rivederti presto![n][w][e]

[msg BAKERY_NOT_BUY [Commessa della panetteria]]
[s][vp 8 2 1 0 5 0]Torna presto![n][w][e]

[msg BAKERY_AME [Commessa della panetteria]]
[s][f 4 23 1 5 3 5 65534 0][vp 8 2 1 0 5 0]Oggi, il nostro menu speciale per giorni[n]di pioggia prevede [f 2 5 3 9999 0].[n][w][e]

[msg MSG_PMAPH_MONTH04_PC]
[s]為 una brochure turistica.[n][w][e]
[s]Mostra diversi luoghi[n]dove 因 possibile osservare[n]i ciliegi in fiore.[n][w][e]

[msg MSG_PMAPH_MONTH04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mostra diverse location[n]famose dalle quali ammirare[n]i ciliegi in fiore.[n][w][e]

[msg MSG_PMAPH_MONTH05 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mostra una location[n]idonea alle famiglie.[n][w][e]

[msg MSG_PMAPH_MONTH06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Parla di una location[n]che 因 diventata famosa[n]per vedere i ciliegi in fiore.[n][w][e]

[msg MSG_PMAPH_MONTH07 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Suggerisce un luogo dal quale[n]osservare i fuochi d'artificio.[n][w][e]

[msg MSG_PMAPH_MONTH08 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mostra dei luoghi[n]del paese dove si pu韻 assistere[n]ai festival estivi.[n][w][e]

[msg MSG_PMAPH_MONTH09 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mostra location[n]idonee per assistere[n]ai festival estivi.[n][w][e]

[msg MSG_PMAPH_MONTH10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Parla di un tour in bus[n]le cui tappe sono ristoranti[n]all-you-can-eat.[n][w][e]

[msg MSG_PMAPH_MONTH11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]為 una brochure turistica.[n][w][e]
[s][f 4 10 65535 0 0]Parla di un tour in bus[n]con le tappe migliori per[n]vedere le foglie autunnali.[n][w][e]

[msg MSG_PMAPH_MONTH12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]為 una brochure turistica.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Mostra le location migliori da[n]vedere durante le feste di Natale.[n][w][e]

[msg MSG_PMAPH_DEFAULT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]為 una brochure turistica.[n][w][e]
[s][f 4 10 65535 0 0]Mostra diverse location[n]turistiche interessanti.[n][w][e]

[msg MSG_DEADEND01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Solo il personale[n]autorizzato pu韻 superare[n]questo punto.[n][w][e]

[msg MSG_DEADEND01]
[s]L'area oltre questo punto[n]sembra off-limits...[n][w][e]

[msg MSG_DISPLAY_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Wow, pensavo fosse un[n]cartellone, ma invece si[n]tratta di uno schermo...[n][w][e]

[msg MSG_DISPLAY]
[s]Una pubblicit稲[n]scorre sul display...[n][w][e]

[msg MSG_TICKET_MACHINE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Non puoi usare l'abbonamento[n]per viaggiare in treno, invece[n]di comprare un biglietto?[n][w][e]

[msg MSG_TICKET_MACHINE]
[s]Con il mio abbonamento[n]non dovrei aver necessit稲[n]di comprare il biglietto...[n][w][e]

[msg MSG_MAN_TICKET_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Uhm, non hai gi稲 un[n]abbonamento dei trasporti[n]per andare a scuola?[n][w][e]

[msg MSG_MAN_TICKET]
[s]Non devo comprare[n]un abbonamento...[n][w][e]

[msg MND_CheckDesk]
[s]Se 因 lungo il mio tragitto,[n]probabilmente posso usare[n]l'abbonamento per andare ad Aoyama.[n][w][e]

[msg MSG_CheckDesk [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Il tuo abbonamento ti permette[n]di raggiungere qualsiasi luogo[n]si trovi tra Yongen e Aoyama.[n][w][e]
[s][f 4 10 65535 0 0]Se volessi andare in un luogo[n]diverso dovrai pagare un biglietto.[n]Cerca di risparmiare, intesi?[n][w][e]

[msg MND_Season_Poster_Spring]
[s]Qui ci sono informazioni[n]utili su dove poter osservare[n]i ciliegi in fiore...[n][w][e]

[msg MSG_Season_Poster_Spring [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Liceali e adulti sono emozionati[n]per i ciliegi in fiore, ma noi non[n]abbiamo tempo per queste cose.[n][w][e]

[msg MSG_Season_Poster_Spring_2 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Anche se ora siamo all'aperto,[n]una volta ad Aoyama saremo[n]sottoterra. Strano, eh?[n][w][e]

[msg MSG_Season_Poster_Summer [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"Spettacolo di fuochi d'artificio[n]serale di Sumidagawa, 18 luglio,[n]il Giorno del mare". Bello![n][w][e]

[msg MSG_Season_Poster_Summer_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]La spiaggia, eh...?[n]Sarebbe bello andarci[n]insieme visto che 因 estate.[n][w][e]

[msg MSG_Season_Poster_Summer_3 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Non riesco a credere di aver dovuto[n]tenere d'occhio la roba di tutti...[n]為 stato divertente, per韻...[n][w][e]

[msg MSG_Season_Poster_Autumn [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Mi lamenterei del caldo,[n]ma siamo in autunno ormai...[n][w][e]

[msg MSG_Season_Poster_Winter [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Illuminazione e luci? Sono[n]decorazioni, giusto?[n]Dovresti farlo anche tu.[n][w][e]

[msg MSG_Season_Poster_3gakki [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]"Continua ad aiutare il prossimo"...[n]Noi siamo stati aiutati molto.[n][w][e]

[msg MND_E14130700_NG_GINZASE]
[s][vp 1 0 0 0 0 0]Non devo fare niente in[n]particolare, quindi per oggi me[n]ne andr韻 a casa...[n][w][e]

[msg MSG_E19310100_NG_GINZASE [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6051 65535 0]Dovremo proseguire a piedi.[n]Credo che ci si arrivi[n]da Central Street.[n][w][e]

[msg MSG_E24310100_NG_GINZASE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, ma dove vai?[n]Non volevi cercare[n]altre informazioni?[n][w][e]

[msg MSG_E24330100_NG_GINZASE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Dove vai? Pensavo che dovessi[n]esplorare Shibuya...[n][w][e]

[msg MND_E10920100_NG_UNDER_0]
[s][vp 1 0 0 0 0 0]Non ho tempo di tornare[n]indietro. Meglio prendere[n]la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E10920100_NG_Hideout]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un collegamento[n]a un edificio commerciale, ma[n]non ho motivo di andarci.[n][w][e]
[s][vp 1 0 0 0 0 0]Devo prendere la [clr 2]linea Ginza[clr 27]...[n][w][e]

[msg MND_E14130700_NG_HIDEOUT]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un collegamento[n]a un edificio commerciale.[n][w][e]
[s][vp 1 0 0 0 0 0]Non devo fare niente in[n]particolare, quindi per oggi me[n]ne andr韻 a casa...[n][w][e]

[msg MSG_E19310100_NG_HIDEOUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Di qua non si arriva a[n]Central Street. Dobbiamo uscire[n]alla piazza della stazione.[n][w][e]

[msg MSG_E24310100_NG_HIDEOUT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, ma dove vai?[n]Non volevi cercare[n]altre informazioni?[n][w][e]

[msg MSG_E24330100_NG_HIDEOUT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Dove vai? Pensavo che dovessi[n]esplorare Shibuya...[n][w][e]

[msg MSG_E24420300_NG_HIDEOUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7036 65535 0]Stai andando dalla parte sbagliata.[n]Dobbiamo arrivare alla piazza[n]e girare a destra.[n][w][e]

[msg MND_E10920100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Al momento non ho sete...[n][w][e]

[msg MSG_E19310100_CHK_AUTO_M [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]Ehi, possiamo sbrigarci ad[n]andare a casa di Madarame?[n][w][e]

[msg MSG_E24420300_CHK_AUTO_M [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Puoi prendere[n]da bere a Shinjuku.[n]Su, sbrighiamoci.[n][w][e]

[msg MND_COMMON_CHK_AUTO_MACH]
[s][vp 1 0 0 0 0 0]Al momento non ho sete...[n][w][e]

[msg MSG_E24420300_NG_GINZASE [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7140 65535 0]Questi sono per la[n]linea Ginza. I tornelli per[n]la JL sono di sotto.[n][w][e]

[msg MND_E10920100_CHK_BAKERY]
[s][vp 1 0 0 0 0 0]Il pane appena sfornato[n]emana un aroma invitante...[n][w][e]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MSG_E19310100_CHK_BAKERY [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Muoio di fameee.[n]Prendiamo qualcosa da mangiare qui?[n][w][e]

[msg MSG_E19310100_CHK_BAKERY_2 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 54073 65535 0]Pi迂 tardi.[n]Dobbiamo parlare con Kitagawa-kun.[n][w][e]

[msg MSG_E24420300_CHK_BAKERY [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Adesso che ci penso, sto morendo[n]di fame. Chiudiamo questa faccenda[n]in fretta e andiamo a mangiare.[n][w][e]

[msg MND_COMMON_CHK_BAKERY_00]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MND_E14130700_NG_TICKET_]
[s][vp 1 0 0 0 0 0]Dovrei poter andare a casa[n]senza dover acquistare biglietti...[n][w][e]

[msg MSG_E19310100_NG_TICKET_ [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7172 65535 0]Che c'因? Muoviamoci.[n][w][e]

[msg MSG_E24420300_NG_TICKET_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]Devi proprio farlo?[n][w][e]

[msg MND_COMMON_CHK_TICKET_00]
[s][vp 1 0 0 0 0 0]Non devo comprare biglietti...[n][w][e]

[msg MND_E10920100_CHK_PAMPHL]
[s][vp 1 0 0 0 0 0]為 una brochure turistica.[n][w][e]
[s][vp 1 0 0 0 0 0]Mostra diversi luoghi[n]dove 因 possibile osservare[n]i ciliegi in fiore.[n][w][e]

[msg MSG_E19310100_CHK_PAMPHL [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7048 65535 0]Oh, 因 una guida turistica, quella?[n]Vorrei tanto andare alle Hawaii.[n][w][e]

[msg MSG_E19310100_CHK_PAMPHL_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Hai pure il tempo[n]di guardarle?[n]Diamoci una mossa![n][w][e]

[msg MSG_E24420300_CHK_PAMPHL [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Non possiamo perdere tempo[n]a guardare quella roba. Dobbiamo[n]arrivare ai tornelli della JL.[n][w][e]

[msg MND_COMMON_CHK_PAMPHLET]
[s][vp 1 0 0 0 0 0]Adesso non ho tempo di[n]mettermi a sfogliare[n]le brochure...[n][w][e]

[msg MND_E10920100_MAIN_Check]
[s][vp 1 0 0 0 0 0]Qui 因 possibile acquistare[n]abbonamenti per il treno.[n][w][e]

[msg MSG_E19310100_MAIN_Check [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7177 65535 0]Che c'因? Muoviamoci.[n][w][e]

[msg MSG_E24420300_MAIN_Check [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Vuoi comprare un abbonamento?[n]Dai, andiamo.[n][w][e]

[msg MND_COMMON_MAIN_CheckDes]
[s][vp 1 0 0 0 0 0]Qui 因 possibile acquistare[n]abbonamenti per il treno.[n][w][e]

[msg MND_E10920100_Main_Seaso]
[s][vp 1 0 0 0 0 0]Qui ci sono informazioni[n]utili su dove poter osservare[n]i ciliegi in fiore...[n][w][e]

[msg MSG_E19310100_Main_Seaso [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7177 65535 0]Che c'因? Muoviamoci.[n][w][e]

[msg MSG_E24420300_Main_Seaso [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7177 65535 0]Che c'因? Su,[n]andiamo a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MND_COMMON_Main_Season_P]
[s][vp 1 0 0 0 0 0]Qui ci sono informazioni[n]utili su dove poter osservare[n]i ciliegi in fiore...[n][w][e]

[msg MSG_SPOT_GO_YAMANOTE]
[s]Dovrei prendere la[n][clr 6]linea Yamanote[clr 0]...[n][w][e]

[msg MSG_SPOT_GO_INOKASIRA]
[s]Dovrei prendere la[n][clr 6]linea Inokashira[clr 0]...[n][w][e]

[msg MSG_SPOT_GO_GINZALINE]
[s]Dovrei prendere la[n][clr 6]linea Ginza[clr 0]...[n][w][e]

[msg SPOT_GO_TUKISIMA_MAKOTO [Makoto]]
[s]Oh, 因 il negozio di monjayaki di[n]Tsukishima. Diamo un'occhiata.[n][w][e]

