[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_SCHOOL_GATE_NG_NIGHT]
[s][vp 1 0 0 0 0 0]La scuola 因 chiusa...[n][w][e]

[msg MSG_SCHOOL_GATE_NG_HOLID]
[s][vp 1 0 0 0 0 0]La scuola 因 chiusa, ma il cancello[n]因 aperto. Potrebbero essere in[n]corso le attivit稲 di qualche club.[n][w][e]

[msg MSG_SCHOOL_GATE_HOLIDAY_]
[s][vp 1 0 0 0 0 0]Il cancello 因 aperto. Forse dovrei[n]convocare gli altri sul tetto...[n][w][e]

[msg MSG_SCHOOL_GATE_HOLIDAY__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Vuoi che ci vediamo[n]al ritrovo, oggi?[n][w][e]

[sel CHECK_HOLIDAY_KAMO_SEL top]
[s]Convoca una riunione[e]
[s]Fai altro[e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_School [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Shujin Academy... Tutto 因[n]iniziato qui...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Eheh, faremmo notte se ci[n]mettessimo a ricordare tutto[n]ci韻 che 因 successo qui.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Questo distributore era come[n]un'oasi per gli studenti prima[n]di entrare a scuola.[n][w][e]

[msg MSG_LAST_GREETING_MAP [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]La mappa di Aoyama-Itchome[n]non ci servir稲 pi迂![n][w][e]

[msg MSG_LAST_GREETING_ALLEY [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Questo 因 il punto da cui siamo[n]entrati nel Palazzo di Kamoshida[n]e dove Lady Ann ci ha seguiti...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]為 gi稲 passato un anno.[n]Che nostalgia.[n][w][e]

[msg MND_0103]
[s]Chiss稲 cosa staranno facendo[n]gli altri...[n][w][e]

[msg MND_RYUJI_0103]
[s]Qui c'因 Ryuji...[n][w][e]
[s]Forse dovrei parlargli...[n][w][e]

[msg MND_GATE_0103]
[s]Andiamo da un'altra parte...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Map]
[s]為 una mappa dell'area...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Roj]
[s]Non devo fare niente qui...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Sch]
[s]Non mi serve niente[n]a scuola...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_HEL [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][fName]-kun?[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Cosa c'因 che non va?[n]Ti serve qualcosa sul tetto?[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_01 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Ehm... Ti vedranno tutti,[n]se vieni qui.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Volevi salire sul tetto?[n][w][e]

[sel SEL_HARU_SCHOOL_GATE_02 top]
[s]Portami l稲.[e]
[s]Non importa.[e]

[sel SEL_HARU_SCHOOL_GATE_08 top]
[s]Portami l稲.[e]
[s]Devo vedere Maruki.[e]
[s]Non importa.[e]

[msg MSG_HARU_SCHOOL_GATE_03 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Sono autorizzata a usare l'entrata[n]posteriore della scuola. Vieni,[n]entriamo da l淫.[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_04 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Fammi sapere se vuoi venire a[n]vedere come stanno le piante.[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_05 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]OK, da questa parte. Dovremo[n]entrare dal retro[n]senza farci notare.[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_06 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]La zona attorno alla scuola[n]pu韻 essere pericolosa a volte,[n]fai attenzione.[n][w][e]

[msg MSG_HARU_SCHOOL_GATE_07 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Credo che il dottor Maruki[n]sia in infermeria.[n][w][e]

[msg MSG_MORUGANA_GATE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Devi fare qualcosa a scuola[n]in un giorno libero?[n][w][e]

[sel SEL_COUNSELING top]
[s]Vai a trovare Maruki[e]
[s]Non importa[e]

[msg MND_Juice_NotOpen]
[s][vp 1 0 0 0 0 0]Al momento non ho sete...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg CHK_SCHOOL_PLATE_M01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Shujin Academy...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Che bel nome per una scuola...[n][w][e]

[msg CHK_SCHOOL_PLATE_01]
[s][vp 1 0 0 0 0 0]Questa 因 la targa della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra un po' consumata...[n][w][e]

[msg MSG_MAP_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]La Shujin Academy si trova in[n]mezzo a degli edifici altissimi.[n][w][e]

[msg MSG_MAP]
[s][vp 1 0 0 0 0 0]La Shujin Academy 因 circondata[n]da alti edifici...[n][w][e]

[msg MSG_ALLEY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]為 solo un vicolo...[n][f 4 10 65535 0 0]Qualcosa non va?[n][w][e]

[msg MND_ALLEY]
[s][vp 1 0 0 0 0 0]為 un vicolo stretto...[n][w][e]
[s][vp 1 0 0 0 0 0]Dovrei riuscire a raggiungere[n]la stazione da qui, ma non[n]ricordo la strada esatta...[n][w][e]

[msg MND_E12710100_SchoolGate]
[s]Pare che sia arrivato a[n]scuola sano e salvo. Ma[n]cos'era quel castello...?[n][w][e]

[msg MND_E14130700_SchoolGate]
[s]Non devo fare niente in[n]particolare, quindi per oggi me[n]ne andr韻 a casa...[n][w][e]

[msg MSG_E19310100_NG_SCHOOL_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Hai dimenticato qualcosa?[n]Su, sbrighiamoci a raggiungere[n]la casa di Madarame![n][w][e]

[msg MND_E12710100_NG_Station]
[s]Sar稲 meglio che mi sbrighi[n]a raggiungere la scuola...[n][w][e]

[msg MND_E12710100_CHK_AUTO_M]
[s]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MSG_E19310100_CHK_AUTO_M [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Ehi, possiamo sbrigarci ad[n]andare a casa di Madarame?[n][w][e]

[msg MND_COMMON_CHK_AUTO_MACH]
[s]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MND_E12710100_CHK_SCHOOL]
[s]Il nome della scuola 因 scritto[n]in modo molto elegante...[n][w][e]

[msg MSG_E19310100_CHK_SCHOOL [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Che succede? Su, andiamo.[n][w][e]

[msg MND_COMMON_CHK_SCHOOL_PL]
[s]Il nome della scuola 因 scritto[n]in modo molto elegante...[n][w][e]

[msg MND_E12710100_CHK_MAP_00]
[s]L'ingresso della scuola[n]因 pi迂 avanti...[n][w][e]

[msg MSG_E19310100_CHK_MAP_00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Mmm? Hai scordato come[n]si arriva alla stazione?[n][w][e]

[msg MSG_E19310100_CHK_MAP_00_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Non 因 come te, Ryuji...[n][w][e]

[msg MSG_E19310100_CHK_MAP_00_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Che hai detto?!?[n][w][e]

[msg MND_COMMON_CHK_MAP_000_0]
[s]La stazione 因 dall'altra[n]parte della scuola...[n][w][e]

[msg MND_E12710100_CHK_ALLEY_]
[s]為 il vicolo che io e Ryuji[n]abbiamo attraversato ieri...[n][w][e]

[msg MSG_E19310100_CHK_ALLEY_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Oh, vuoi andare di l稲?[n][w][e]

[msg MSG_E19310100_CHK_ALLEY__2 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Cosa...? Perch姻 vuoi passare[n]di qui? Facciamo la[n]strada normale.[n][w][e]

[msg MND_COMMON_CHK_ALLEY_000]
[s]Non devo fare niente[n]pi迂 avanti.[n][w][e]

