[msg DUMMY_MSG]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_NotUse_Table [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]C'因 qualcuno che dorme sul banco...[n]Ma questi ragazzi non ce la fanno[n]a mettere la testa a posto?[n][w][e]

[msg MSG_STUDY_START_1ST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Oh, qui si pu韻 studiare.[n][w][e]

[msg MSG_Sentou_ParamInfo_int [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Studiando a un tavolo libero potresti[n]migliorare la tua [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MSG_Study_Start_Kamo [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]C'因 un po' di gente, ma...[n]questo potrebbe permetterti[n]di migliorare il tuo [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MSG_Study_Start_Normal [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Cosa vuoi fare? Studiare qui?[n][w][e]

[msg MSG_Study_Start_BadWeath [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Oggi non c'因 molta gente. Sar稲 per[n]via del tempo... Ma almeno[n]potrai studiare in santa pace![n][w][e]

[sel STUDY_THINK_SEL top]
[s]Facciamolo.[e]
[s]Lasciamo stare.[e]

[msg MND_Study_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_Study_ParamUpInfo]
[s]Credo che il mio [stIcon 0][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MSG_BOOK_SHELF_01 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]I libri che ci sono qui[n]sembrano piuttosto difficili...[n][w][e]

[msg MSG_BOOK_SHELF_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]Non credo che molta gente legga[n]questi libri. Sono coperti da uno[n]spesso strato di polvere.[n][w][e]

[msg MSG_BOOK_SHELF_03 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Il titolo di questo libro[n]因 cos淫 noioso... Non c'因 qualcosa[n]di pi迂 interessante?[n][w][e]

[msg MSG_BOOK_SHELF_04 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Chi si occupa della selezione[n]di questi libri? Dovrebbero fare[n]investimenti pi迂 interessanti...[n][w][e]

[msg MSG_BOOK_SHELF_05 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questi libri sono enormi...[n]Potremmo quasi usarli come arma![n][w][e]

[msg MSG_BOOK_SHELF_06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Lo scaffale 因 pieno di libri.[n]Ma sono quasi tutti troppo[n]seri per i miei gusti.[n][w][e]

[msg MSG_BOOK_SHELF_07 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ma c'因 qualcuno che li legge[n]almeno? Beh, immagino siano[n]qui a scopo didattico...[n][w][e]

[msg MSG_BOOK_SHELF_08 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Mmm... Nessuno di questi mi sembra[n]abbastanza interessante...[n][w][e]

[msg MSG_BOOK_SHELF_09 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Questi libri saranno antichi. Pare[n]che si possano sbriciolare[n]da un momento all'altro.[n][w][e]

[msg MSG_BOOK_SHELF_10 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questi libri hanno un odore... strano.[n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MND_KFEVT_COMMON_NG]
[s][vp 1 0 0 0 0 0]Per ora non devo fare[n]niente in particolare qui...[n][w][e]

[msg MSG_NotUse_GUIDE_DESK [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1044 0 0]Devi proprio metterti a[n]leggere adesso?[n]Puoi farlo dopo.[n][w][e]

[msg MSG_NotUse_TABLE_LEFT [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]Ora non c'因 tempo per le[n]letture ricreative.[n][w][e]

[msg MSG_NotUse_STUDYDESK_CHA [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Puoi studiare dopo.[n][w][e]

[msg MSG_NotUse_BOOK_SHELF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1189 0 0]Devi proprio metterti a[n]leggere adesso?[n]Puoi farlo dopo.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

