[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non sai che quello 因 il bagno[n]femminile?[n]Non dovresti entrarci...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_HOKEN_ROOM_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Ugh... Perch姻 l'infermeria deve[n]puzzare di medicinali?[n]Mi fa bruciare il naso...[n][w][e]

[msg MSG_HOKEN_ROOM]
[s][vp 1 0 0 0 0 0]Sento l'odore dei farmaci[n]dell'infermeria attraverso la[n]porta malconcia...[n][w][e]

[msg MSG_KATEIKA_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Che profumino...[n]Chiss稲 se qualcuno ha cucinato [n]qualcosa qui di recente...[n][w][e]

[msg MSG_KATEIKA]
[s][vp 1 0 0 0 0 0]Un piacevole aroma aleggia[n]nell'aria. Come se avessero[n]cucinato qualcosa di recente.[n][w][e]

[msg MSG_HIHUKU_ROOM_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Quante macchine da cucire.[n]Faranno un sacco di rumore[n]tutte accese allo stesso tempo.[n][w][e]

[msg MSG_HIHUKU_ROOM]
[s][vp 1 0 0 0 0 0]Ci sono molte macchine[n]da cucire sui banchi...[n][w][e]

[msg MSG_BUTURI_ROOM_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Qualcuno ha lasciato gli strumenti[n]da laboratorio sulla scrivania...[n]Non molto professionale.[n][w][e]

[msg MSG_BUTURI_ROOM]
[s][vp 1 0 0 0 0 0]Ci sono strumenti da laboratorio[n]su tutta la scrivania...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, se vuoi uscire dovremmo[n]usare l'entrata principale.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

[msg MSG_Kateika_Tool [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Una volta saranno anche stati[n]luccicanti, ma ora sono[n]opachi e spenti...[n][w][e]

[msg MND_Kateika_Tool]
[s][vp 1 0 0 0 0 0]Sono stati usati molto,[n]e non brillano praticamente pi迂...[n][w][e]

[msg MND_E14710100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_NG_BldgB1F [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E65410200_NG_BldgB1F [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MSG_E13910100_NG_BldgB1F [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MSG_E15010100_NG_BldgB1F_2 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_NG_BldgB1F_2]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E13910100_NG_BldgB1F_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MSG_E65110100_NG_BldgB1F [Lavenza]]
[s][bup 0 100 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 24008 65535 0]......[n][w][e]

[msg MND_E65110100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]Non 因 di qua...[n][w][e]

[msg MSG_E65410200_NG_BldgB1F_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_TOILET [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Non adesso. L'aula del consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_TOILET_2 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Qui non ti serve nulla, vero? Il[n]consiglio studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E12310100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]為 l'infermeria.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 un vago odore[n]di disinfettante...[n][w][e]

[msg MND_E12720100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]Questa 因 l'infermeria.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 un vago odore[n]di disinfettante...[n][w][e]

[msg MND_E13710100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]Qui stanno medicando uno studente[n]infortunatosi durante[n]la partita.[n][w][e]
[s][vp 1 0 0 0 0 0]Non vedo studenti con[n]ferite di rilievo...[n][w][e]

[msg MSG_E13910100_CHK_HOKENS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]Questa 因 l'infermeria.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 un vago odore[n]di disinfettante...[n][w][e]

[msg MND_E14710100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_HOKENS [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_HOKENS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Questa 因 l'infermeria. L'aula del[n]consiglio studentesco non[n]因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_HOKENS]
[s][vp 1 0 0 0 0 0]Inutile tornare indietro...[n][w][e]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_HOKENSITU]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Ecco l'aula di economia domestica.[n][w][e]
[s][vp 1 0 0 0 0 0]Vedo utensili da cucina[n]di tutti i tipi[n]sulla mensola...[n][w][e]

[msg MND_E12720100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Ecco l'aula di economia domestica.[n][w][e]
[s][vp 1 0 0 0 0 0]Dall'odore si direbbe che stiano[n]cucinando. A giudicare dal profumo,[n]sar稲 qualcosa di delizioso...[n][w][e]

[msg MND_E13710100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Ecco l'aula di Economia Domestica.[n][w][e]
[s][vp 1 0 0 0 0 0]Qualcuno ha lasciato in giro[n]qualcosa di bruciato...[n][w][e]

[msg MSG_E13910100_CHK_KATEIK [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Ecco l'aula di Economia Domestica.[n][w][e]
[s][vp 1 0 0 0 0 0]Dall'odore si direbbe che stiano[n]cucinando. A giudicare dal profumo,[n]sar稲 qualcosa di delizioso...[n][w][e]

[msg MND_E14710100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_KATEIK [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_KATEIK [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]L'aula di Economia Domestica. Il[n]consiglio studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_KATEIK]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_KATEIKASI]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Questa sembra l'aula[n]di cucito.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono file e file di[n]macchine da cucire...[n][w][e]

[msg MND_E12720100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Cucito.[n]Ci sono file e file di[n]macchine da cucire...[n][w][e]

[msg MND_E13710100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Cucito.[n]Ci sono file e file di[n]macchine da cucire...[n][w][e]

[msg MSG_E13910100_CHK_HIFUKU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Cucito.[n]Ci sono file e file di[n]macchine da cucire...[n][w][e]

[msg MND_E14710100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_HIFUKU [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_HIFUKU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]L'aula di Cucito. Il consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_HIFUKU]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_HIFUKUSIT]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]為 l'aula di fisica.[n][w][e]
[s][vp 1 0 0 0 0 0]Qualcuno ha lasciato tutte[n]le attrezzature in giro...[n][w][e]

[msg MND_E12720100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Fisica.[n]Ci sono tantissime attrezzature[n]tecniche incustodite...[n][w][e]

[msg MND_E13710100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Fisica.[n]Ci sono tantissime attrezzature[n]tecniche incustodite...[n][w][e]

[msg MSG_E13910100_CHK_BUTURI [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Fisica.[n]Ci sono tantissime attrezzature[n]tecniche incustodite...[n][w][e]

[msg MND_E14710100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_BUTURI [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[n]al secondo piano[clr 27]...[n][w][e]

[msg MND_E15010100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_BUTURI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Sembra l'aula di Fisica. Il consiglio studentesco non 因 al [clr 2]terzo piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_BUTURI]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_BUTURISIT]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E65110100_CHK_EMERGE]
[s][vp 1 0 0 0 0 0]Non 因 di qua...[n][w][e]

[msg MSG_KFEVT_EXIT_DOOR [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Quella 因 l'uscita d'emergenza![n]Meglio non toccarla...[n][w][e]

[msg MND_KFEVT_EXIT_DOOR]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

[msg MND_E65110100_CHK_KATEIK_2]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_KATEIKA_T]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

