[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg KOUBAIBU_NOTOPEN [Signora del negozio scolastico]]
[s][f 4 23 1 20 21 5 20 0][vp 8 2 1 0 20 0]Scusa, ma stiamo ancora allestendo.[n]Torna pi迂 avanti.[n][w][e]

[msg KOUBAIBU_SELECT [Signora del negozio scolastico]]
[s][f 4 23 1 20 21 5 20 0][vp 8 2 1 0 20 0]Ehi, ciao. Vedi qualcosa[n]che ti piace?[n][w][e]

[msg KOUBAIBU_THANKS [Signora del negozio scolastico]]
[s][vp 8 2 1 0 20 0]Grazie mille.[n][w][e]

[msg KOUBAIBU_NOT_BUY [Signora del negozio scolastico]]
[s][vp 8 2 1 0 20 0]D'accordo, torna a trovarci.[n][w][e]

[msg KOUBAIBU_YAKISOBA_INFO [Signora del negozio scolastico]]
[s][f 4 23 1 20 21 5 20 0][vp 8 2 1 0 20 0]Il [f 2 5 3 9999 0] qui va[n]molto... ma di solito il [clr 2]venerd淫[clr 27][n]ne abbiamo qualcuno in pi迂.[n][w][e]

[msg KOUBAIBU_YAKISOBA_INFO_0 [Signora del negozio scolastico]]
[s][f 4 23 1 20 21 5 20 0][vp 8 2 1 0 20 0]Sia [f 2 5 3 9999 0] che[n][f 2 5 3 9999 1] qui sono molto richiesti...[n][w][e]
[s][vp 8 2 1 0 20 0]Ma stranamente il [clr 2]venerd淫[clr 27][n]ce ne avanza qualcuno.[n][w][e]

[msg MSG_KOUBAIBU_KAMOSHIDA_T [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Questa roba potr稲 anche andar bene[n]per una pausa nel Palazzo, ma non[n]因 molto nutriente...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Forse possiamo trovare qualcosa[n]di pi迂 utile in una delle[n]farmacie della citt稲.[n][w][e]

[msg MSG_OFFICE]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]in segreteria...[n][w][e]

[msg MSG_OFFICE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ehi, qui non hai niente[n]da fare, giusto?[n][w][e]

[msg AUTO_MACHINE01_NOTOPEN]
[s][vp 1 0 0 0 0 0]Al momento non ho sete...[n][w][e]

[msg AUTO_MACHINE01_START [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MSG_SHELF_TROPHY_MORU_AF [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, almeno sono riusciti[n]a coprire il nome di Kamoshida[n]su questo trofeo...[n][w][e]

[msg MSG_SHELF_TROPHY_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Mmm... Tutti questi trofei sono stati[n]vinti dalla squadra di pallavolo...[n][w][e]

[msg MSG_SHELF_TROPHY]
[s][vp 1 0 0 0 0 0]Tutti questi trofei sono[n]della squadra di pallavolo...[n][w][e]

[msg MSG_SHELF_PHOTO_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Quest'immagine risale a quando[n]la Shujin fu fondata...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Gli insegnanti sembravano[n]nutrire davvero grandi speranze[n]per il futuro della scuola...[n][w][e]

[msg MSG_SHELF_PHOTO]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MSG_BOARD_ENTRANCE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 lo slogan della scuola?[n]為 "particolare"...[n][w][e]

[msg MSG_BOARD_ENTRANCE]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MND_BOARD_ENTRANCE_KOUTY]
[s][vp 1 0 0 0 0 0]"La corruzione morale del nostro[n]campus ha portato a voci infondate[n]apparentemente inarrestabili".[n][w][e]
[s][vp 1 0 0 0 0 0]"Nella speranza di arginare il problema,[n]ogni informazione da parte degli[n]studenti sar稲 presa in considerazione".[n][w][e]
[s][vp 1 0 0 0 0 0]"Rivolgetevi al vostro presidente di[n]consiglio se volete comunicare[n]qualsiasi cosa ufficialmente".[n][w][e]
[s][vp 1 0 0 0 0 0]"Sar稲 mantenuta la riservatezza.[n]Confido nel vostro senso[n]di responsabilit稲. - Preside Kobayakawa"[n][w][e]

[msg MND_BOARD_ENTRANCE_COUNS]
[s][vp 1 0 0 0 0 0]Ci sono dei volantini[n]sulle consulenze.[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra che ci saranno[n]sessioni fino a novembre...[n][w][e]

[msg MND_BOARD_ENTRANCE_SOUJI]
[s][vp 1 0 0 0 0 0]★Notifica sulle grandi pulizie★[n][w][e]
[s][vp 1 0 0 0 0 0]・Luogo: Parco Inokashira[n]・Data: 30 maggio[n][w][e]
[s]Puliremo il parco Inokashira.[n]Incontro al parco. Mettete[n]la tuta da atletica.[n][w][e]
[s]...sul volantino c'era scritto cos淫.[n][w][e]

[msg MSG_SIKEN_TOP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che siano usciti i[n]risultati degli esami.[n]Vediamo... Dov'因 il tuo nome?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Incredibile, sei il migliore[n]della tua classe![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Lady Ann 因 leggermente sotto[n]la media, per韻... e Ryuji 因 quasi[n]in fondo alla lista...[n][w][e]

[msg MSG_SIKEN_IN10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che siano usciti i[n]risultati degli esami.[n]Vediamo... Dov'因 il tuo nome?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Oh, sei tra i primi dieci[n]della tua classe. Grande![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Lady Ann 因 leggermente sotto[n]la media, per韻... e Ryuji 因 quasi[n]in fondo alla lista...[n][w][e]

[msg MSG_SIKEN_HIGH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che siano usciti i[n]risultati degli esami.[n]Vediamo... Dov'因 il tuo nome?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Sei appena sopra la media,[n]quindi non va poi tanto[n]male, giusto?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Lady Ann 因 leggermente sotto[n]la media, per韻... e Ryuji 因 quasi[n]in fondo alla lista...[n][w][e]

[msg MSG_SIKEN_LOW [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che siano usciti i[n]risultati degli esami.[n]Vediamo... Dov'因 il tuo nome?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Sei appena sotto la media.[n]Dovresti impegnarti di pi迂...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Lady Ann si trova proprio vicino a[n]te, ma Ryuji 因 molto pi迂 in basso.[n][w][e]

[msg MSG_SIKEN_BOTTOM [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che siano usciti i[n]risultati degli esami.[n]Vediamo... Dov'因 il tuo nome?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Uh, sei proprio[n]in fondo alla lista.[n]Tra gli ultimi, insieme a Ryuji...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Anche Lady Ann 因 al di sotto[n]della media... Dovreste prendere[n]la scuola pi迂 seriamente...[n][w][e]

[msg MSG_SIKEN_ERROR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che siano usciti i[n]risultati degli esami.[n][w][e]

[msg CHK_CANTEEN_DOOR_S_01]
[s][vp 1 0 0 0 0 0]Non ho motivo di[n]andare in mensa...[n][w][e]

[msg MSG_SYOKUDOU_NotOpen [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Non c'因 un buon odore qui dentro...[n]Andiamo da un'altra parte.[n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Questi muri sono disgustosi...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non sai che quello 因 il bagno[n]femminile?[n]Non dovresti entrarci...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg CHK_ATTENTION_BOARD_01]
[s][vp 1 0 0 0 0 0]Questa bacheca ha molti pi迂[n]annunci rispetto alle altre...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui si parla solo di Kamoshida[n]o della squadra di pallavolo...[n][w][e]

[msg MSG_GRADE3_CLASS_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]為 un'aula del terzo anno...[n][w][e]
[s][vp 1 0 0 0 0 0]Non hai motivo di entrare.[n]Su, andiamo da un'altra parte.[n][w][e]

[msg MSG_GRADE3_CLASS]
[s][vp 1 0 0 0 0 0]為 un'aula del terzo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Non ho motivo di entrare...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, se vuoi uscire dovremmo[n]usare l'entrata principale.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg MND_KFEVT_COMMON_NG]
[s][vp 1 0 0 0 0 0]Per ora non devo fare[n]niente in particolare qui...[n][w][e]

[msg MND_E12010100_NG_ENTRANC]
[s][vp 1 0 0 0 0 0]Dovrei andare in[n]sala docenti...[n][w][e]
[s][vp 1 0 0 0 0 0]La sala docenti dovrebbe essere al[n][clr 2]secondo piano di quest'edificio[clr 27].[n][w][e]

[msg MND_E12310100_NG_ENTRANC]
[s][vp 1 0 0 0 0 0]Sakamoto ha detto che avrebbe[n]aspettato sul [clr 2]tetto[clr 27].[n][w][e]
[s][vp 1 0 0 0 0 0]Prover韻 l淫...[n][w][e]

[msg MSG_E13710100_NG_ENTRANC [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Ehi, dove vai? Sbrighiamoci[n]ad andare in classe tua![n][w][e]

[msg MND_E13710100_NG_ENTRANC]
[s][vp 1 0 0 0 0 0]Devo parlare con un[n]giocatore di pallavolo con[n]una ferita vistosa...[n][w][e]

[msg MND_E13710100_NG_ENTRANC_2]
[s][vp 1 0 0 0 0 0]Devo vedermi con Ryuji[n]nel [clr 2]cortile[clr 27]...[n][w][e]

[msg MSG_E13910100_NG_ENTRANC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, dobbiamo raggiungere[n]Mishima! Se non ci diamo una mossa,[n]col cavolo che lo becchiamo.[n][w][e]

[msg MND_E14130100_NG_ENTRANC]
[s][vp 1 0 0 0 0 0]Dovrei raggiungere Ryuji.[n]Per ora, andiamo[n]in [clr 2]cortile[clr 27]...[n][w][e]

[msg MND_E14130100_NG_ENTRANC_2]
[s][vp 1 0 0 0 0 0]Oggi non devo fare niente[n]in particolare. Andr韻 direttamente[n]a casa senza fare deviazioni.[n][w][e]

[msg MND_E14710100_NG_ENTRANC]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_NG_ENTRANC]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_NG_ENTRANC [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Dove stai andando? Non ti aspettano[n]nell'aula del consiglio studentesco[n]al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MSG_E24320100_NG_ENTRANC [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1171 0 0]Dove credi di andare?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Non dovevi fare un giro per la[n]scuola e chiedere informazioni[n]su cosa sta succedendo?[n][w][e]

[msg MSG_E65410200_NG_ENTRANC [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MND_COMMON_NG_ENTRANCE_0]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E12010100_NG_BldgA1F]
[s][vp 1 0 0 0 0 0]Sembra che di qua si[n]vada verso un altro edificio.[n][w][e]
[s][vp 1 0 0 0 0 0]La sala docenti dovrebbe essere al[n][clr 2]secondo piano di quest'edificio[clr 27].[n][w][e]

[msg MSG_E13710100_NG_BldgA1F [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Di l稲 si va all'edificio[n]laboratori. Noi dobbiamo raggiungere[n]l'aula della classe D.[n][w][e]

[msg MND_E13710100_NG_BldgA1F]
[s][vp 1 0 0 0 0 0]Dovrei lasciare l'edificio laboratori[n]a Ryuji...[n][w][e]

[msg MSG_E13910100_NG_BldgA1F [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14710100_NG_BldgA1F]
[s]La strada verso l'edificio[n]laboratori 因 talmente affollata[n]che non riesco a passare...[n][w][e]
[s]Proviamone un'altra...[n][w][e]

[msg MND_E12010100_NG_Yard_00]
[s]Sembra che di qui[n]ci sia il cortile.[n][w][e]
[s]La sala docenti dovrebbe essere al[n][clr 2]secondo piano di quest'edificio[clr 27].[n][w][e]

[msg MND_E13910100_NG_Yard_00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14710100_NG_Yard_00]
[s][vp 1 0 0 0 0 0]Non riesco a superare[n]questa folla di studenti...[n][w][e]
[s][vp 1 0 0 0 0 0]Chiss稲 se posso arrivare al[n]cortile dalla parte[n][clr 2]dell'edificio laboratori[clr 27]...[n][w][e]

[msg MSG_E65110100_NG_BldgB1F [Lavenza]]
[s][bup 0 100 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 24008 65535 0]......[n][w][e]

[msg MND_E65110100_NG_BldgB1F]
[s][vp 1 0 0 0 0 0]Non 因 di qua...[n][w][e]

[msg MSG_E13910100_NG_BldgA1F_2 [Ryuji]]
[s][bup 0 2 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MSG_E65410200_NG_BldgA1F [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MND_E12010100_CHK_School]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]in segreteria...[n][w][e]

[msg MND_E12310100_CHK_School]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]in segreteria...[n][w][e]

[msg MND_E12720100_CHK_School]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]in segreteria...[n][w][e]

[msg MSG_E13710100_CHK_School [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7197 65535 0]Qui non devi fare niente,[n]vero? Se non ci sbrighiamo,[n]la partita finir稲.[n][w][e]

[msg MND_E13710100_CHK_School]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]in segreteria...[n][w][e]

[msg MSG_E13910100_NG_CHK_Sch [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, dobbiamo bloccare[n]Mishima. Se non ci diamo una[n]mossa, se ne andr稲![n][w][e]

[msg MND_E14130100_CHK_School]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]in segreteria...[n][w][e]

[msg MND_E14710100_CHK_School]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_School]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_School [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Qui non ti serve nulla, vero? Non[n]devi andare all'aula del consiglio[n]studentesco al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_School]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_SchoolOff]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12010100_CHK_School_2]
[s][vp 1 0 0 0 0 0]為 il negozio scolastico.[n]Il pane che vendono qui[n]non m'interessa...[n][w][e]

[msg MSG_E13710100_CHK_School_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7194 65535 0]Dai, la prossima volta ti[n]prendo qualcosa! Adesso dobbiamo[n]andare in classe tua.[n][w][e]

[msg MSG_E13710100_CHK_School_3 [Dipendente demotivato]]
[s][vp 1 0 0 0 0 0]Siamo ancora in allestimento...[n]Tornate un'altra volta...[n][w][e]

[msg MSG_E13910100_CHK_School [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, dobbiamo bloccare[n]Mishima. Se non ci diamo una[n]mossa, se ne andr稲![n][w][e]

[msg MND_E14710100_CHK_School_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_School_2]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MND_E65110100_CHK_School_2]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_SchoolSto]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E12010100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MSG_E13710100_CHK_AUTO_M [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Ehi, non puoi farlo dopo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]La partita finir稲, non[n]possiamo metterci troppo![n][w][e]

[msg MND_E13710100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MSG_E13910100_CHK_AUTO_M [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14710100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MND_E65110200_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_AUTO_MACH]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MND_E12010100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Qui sono esposti con orgoglio[n]i trofei vinti dalla scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]A quanto pare, tutti questi trofei[n]sono della squadra di pallavolo...[n][w][e]

[msg MND_E12310100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Tutti questi trofei sono[n]della squadra di pallavolo...[n][w][e]

[msg MND_E12720100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Tutti questi trofei sono[n]della squadra di pallavolo...[n][w][e]

[msg MSG_E13710100_CHK_TROPHY [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]La squadra di pallavolo ha[n]vinto tutti questi trofei, eh?[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7175 65535 0]Merda... mostrer韻 a tutti[n]la verit稲 sugli abusi[n]che subiscono![n][w][e]

[msg MND_E13710100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Tutti questi trofei sono[n]della squadra di pallavolo...[n][w][e]

[msg MSG_E13910100_CHK_TROPHY [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Tutti questi trofei sono[n]della squadra di pallavolo...[n][w][e]

[msg MND_E14710100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_TROPHY]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TROPHY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1192 0 0]Che hanno di strano i trofei? Non[n]stai andando all'aula del consiglio[n]studentesco [clr 2]al terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TROPHY_00]
[s][vp 1 0 0 0 0 0]Tutti questi trofei sono[n]della squadra di pallavolo...[n][w][e]

[msg MND_E12010100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MND_E12310100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MND_E12720100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MSG_E13710100_CHK_PHOTO_ [Ryuji]]
[s][bup 0 2 205 65535 0][f 4 10 65535 0 0][vp 8 2 1 7174 65535 0]Quella 因 una foto di[n]questa scuola? Guarda che[n]espressioni divertite.[n][w][e]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quindi prima era[n]cos淫, eh?[n][w][e]

[msg MND_E13710100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MSG_E13910100_CHK_PHOTO_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MND_E14710100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_PHOTO_]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_PHOTO_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Perch姻 guardi le foto? Ti hanno[n]chiamato all'aula del consiglio[n]studentesco, [clr 2]al terzo piano[clr 27].[n][w][e]

[msg MND_COMMON_CHK_PHOTO_000]
[s][vp 1 0 0 0 0 0]Quest'immagine risale alla[n]fondazione della scuola...[n][w][e]

[msg MND_E12010100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MND_E12310100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MND_E12720100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MSG_E13710100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7172 65535 0]Che stai facendo?[n]Forza, andiamo[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MSG_E13910100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MND_E14710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_BOARD_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]C'因 qualche problema? Stai andando[n]all'aula del consiglio studentesco[n][clr 2]al terzo piano[clr 27], giusto?[n][w][e]

[msg MND_E65110100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MND_COMMON_CHK_BOARD_ENT]
[s][vp 1 0 0 0 0 0]C'因 scritto lo slogan della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]"La vera libert稲 risiede[n]nelle regole della societ稲".[n][w][e]

[msg MND_E12010100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Qui c'因 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti...[n][w][e]

[msg MND_E12310100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Qui c'因 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti...[n][w][e]

[msg MND_E12720100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]為 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti,[n]ma non c'因 niente in particolare[n]che voglia mangiare...[n][w][e]

[msg MSG_E13710100_CHK_TICKET [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Per caso hai fame?[n]Comunque, al momento la[n]mensa 因 chiusa.[n][w][e]

[msg MND_E13710100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]為 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti,[n]ma non c'因 niente in particolare[n]che voglia mangiare...[n][w][e]

[msg MSG_E13910100_CHK_TICKET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]為 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti,[n]ma non c'因 niente in particolare[n]che voglia mangiare...[n][w][e]

[msg MND_E14710100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MND_E23810100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]為 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti,[n]ma non c'因 niente in particolare[n]che voglia mangiare...[n][w][e]

[msg MND_E65110100_CHK_TICKET]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_TICKET_MA]
[s][vp 1 0 0 0 0 0]為 la macchina per[n]ordinare il cibo in mensa.[n][w][e]
[s][vp 1 0 0 0 0 0]Sul menu ci sono diversi piatti,[n]ma non c'因 niente in particolare[n]che voglia mangiare...[n][w][e]

[msg MND_E12010100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Questa sembra la mensa.[n]Per ora, 因 meglio che vada[n]in [clr 2]sala docenti[clr 27].[n][w][e]

[msg MND_E12310100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Non ho motivo di[n]andare in mensa...[n][w][e]
[s][vp 1 0 0 0 0 0]Sakamoto ha detto che avrebbe[n]aspettato sul [clr 2]tetto[clr 27].[n]Prover韻 l淫.[n][w][e]

[msg MND_E12720100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Non ho motivo di[n]andare in mensa...[n][w][e]

[msg MSG_E13710100_CHK_SHOKUD [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7196 65535 0]Al momento c'因 una partita[n]in corso, sai? La mensa[n]sar稲 deserta.[n][w][e]

[msg MND_E13710100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Non ho motivo di[n]andare in mensa...[n][w][e]

[msg MSG_E13910100_CHK_SHOKUD [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Non ho motivo di[n]andare in mensa...[n][w][e]

[msg MND_E14710100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_SHOKUD [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Quella 因 la mensa. Non devi andare[n]all'aula del consiglio studentesco,[n][clr 2]al terzo piano[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_SHOKUD]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_SHOKUDO_D]
[s][vp 1 0 0 0 0 0]Non ho motivo di[n]andare in mensa...[n][w][e]

[msg MND_E12010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questi muri sono disgustosi...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questi muri sono disgustosi...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questi muri sono disgustosi...[n][w][e]

[msg MSG_E13710100_CHK_TOILET [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7200 65535 0]Oh, la stavo trattenendo[n]da un sacco di tempo. Meglio[n]andarci, finch姻 possiamo![n][w][e]

[msg MSG_E13710100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Fiuuu...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_3 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Bene, proseguiamo![n]Inizieremo dando un'occhiata[n]in classe tua.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_4 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Ti scappa di nuovo?[n]Ci siamo appena andati.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Non devo andare[n]in bagno...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Per ora, andiamo[n]in cortile...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Lo farai pi迂 tardi. Devi andare[n]all'aula del consiglio studentesco[n][clr 2]al terzo piano[clr 27], giusto?[n][w][e]

[msg MND_E65110100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Non devo andare in bagno...[n][w][e]

[msg MND_E12010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questi dovrebbero essere i[n]bagni delle studentesse[n]delle classi superiori.[n][w][e]
[s][vp 1 0 0 0 0 0]Sento le ragazze che[n]spettegolano all'interno...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ehi, coso, non puoi entrare l淫![n]Muoviamoci e andiamo[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Non serve andare l稲, vero? Non ti[n]aspettano nell'aula del consiglio[n]studentesco al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_E65110100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12010100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]La maggior parte sembra riguardare[n]la squadra di pallavolo...[n][w][e]

[msg MND_E12310100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]La maggior parte sembra riguardare[n]la squadra di pallavolo...[n][w][e]

[msg MND_E12720100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]La maggior parte sembra riguardare[n]la squadra di pallavolo...[n][w][e]

[msg MSG_E13710100_CHK_ATTENT [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Che stai guardando?[n]Dai, sbrighiamoci![n][w][e]

[msg MND_E13710100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]La maggior parte sembra riguardare[n]la squadra di pallavolo...[n][w][e]

[msg MSG_E13910100_CHK_ATTENT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]La maggior parte sembra riguardare[n]la squadra di pallavolo...[n][w][e]

[msg MND_E14710100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_ATTENT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]C'因 qualche problema? Stai andando[n]all'aula del consiglio studentesco[n][clr 2]al terzo piano[clr 27], giusto?[n][w][e]

[msg MND_E65110100_CHK_ATTENT]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_ATTENTION]
[s][vp 1 0 0 0 0 0]Su questa bacheca ci[n]sono dei volantini.[n][w][e]
[s][vp 1 0 0 0 0 0]La maggior parte sembra riguardare[n]la squadra di pallavolo...[n][w][e]

[msg MND_E12010100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Al primo piano dovrebbero[n]esserci tutte le aule[n]del terzo anno...[n][w][e]

[msg MND_E12310100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Al primo piano ci sono[n]le aule del terzo anno...[n][w][e]

[msg MND_E12720100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]為 un'aula del terzo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Uno studente di un altro anno[n]come me darebbe troppo nell'occhio.[n]Meglio andare da un'altra parte...[n][w][e]

[msg MSG_E13710100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Non vedo nessuno della[n]squadra di pallavolo.[n][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Iniziamo a chiedere ai[n]tuoi compagni di classe![n][w][e]

[msg MND_E13710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Non vedo studenti con[n]ferite vistose...[n][w][e]

[msg MSG_E13910100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]為 un'aula del terzo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Uno studente di un altro anno[n]come me darebbe troppo nell'occhio.[n]Meglio andare da un'altra parte...[n][w][e]

[msg MND_E14710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Ora devo raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Quella 因 la classe del terzo anno.[n]Andiamo all'aula del consiglio[n]studentesco al [clr 2]terzo piano[clr 27].[n][w][e]

[msg MND_E65110100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_CLASS_3_0]
[s][vp 1 0 0 0 0 0]為 un'aula del terzo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_ENTRANCE_NG_KAWAKAMI]
[s][vp 1 0 0 0 0 0]Devo fare un giro nel campus e[n]trovare informazioni che dimostrino[n]l'innocenza di Kawakami...[n][w][e]

[msg MND_E65110200_CHK_EMERGE]
[s][vp 1 0 0 0 0 0]Non 因 di qua...[n][w][e]

[msg MND_COMMON_CHK_EMERGENCY]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

