[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_DOOR_ROOF_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]A quanto pare non possiamo proseguire oltre...[n][w][e]

[msg MSG_DOOR_ROOF]
[s][vp 1 0 0 0 0 0]Questa zona 因 off-limits...[n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 persino pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non sai che quello 因 il bagno[n]femminile?[n]Non dovresti entrarci...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_MUSICROOM_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Ci sono dei ritratti allineati sulle[n]pareti della stanza... m-ma sono tutti[n]cos淫 spaventosi...[n][w][e]

[msg MSG_MUSICROOM]
[s][vp 1 0 0 0 0 0]Ritratti di compositori famosi[n]sono appesi alle pareti...[n][w][e]

[msg MSG_PCROOM_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Ci sono molti computer qui,[n]ma pochi studenti.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]I computer sembrano piuttosto[n]vecchi, e forse per questo[n]nessuno li vuole usare...[n][w][e]

[msg MSG_PCROOM]
[s][vp 1 0 0 0 0 0]Non vedo studenti qui...[n][w][e]

[msg MSG_STUDYROOM_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Wow, studiano con una tale attenzione...[n][w][e]

[msg MSG_STUDYROOM]
[s][vp 1 0 0 0 0 0]I ragazzi in questa[n]sala stanno studiando...[n][w][e]

[msg MSG_CALLIG_ROOM_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]"Lo spirito angosciato"...[n]"Il mostro interiore"...[n]Che nomi pretenziosi...[n][w][e]

[msg MSG_CALLIG_ROOM]
[s][vp 1 0 0 0 0 0]La stanza 因 decorata con[n]diverse opere calligrafiche[n]degli studenti.[n][w][e]

[msg AUTO_MACHINE01_NOTOPEN]
[s][vp 1 0 0 0 0 0]Dice che 因 in manutenzione.[n]Non credo funzioni...[n][w][e]

[msg MSG_WAREHOUSE_01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]為 un ripostiglio, questo?[n]Sembra chiuso a chiave.[n][w][e]

[msg MSG_WAREHOUSE_01]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_WAREHOUSE_02_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_WAREHOUSE_02]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, se vuoi uscire dovremmo[n]usare l'entrata principale.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

[msg MSG_MusicTool [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Non dovrebbero essere tenuti[n]con pi迂 cura...? Cos淫 finiranno[n]per rovinarsi.[n][w][e]

[msg MND_MusicTool]
[s][vp 1 0 0 0 0 0]Alcuni strumenti musicali[n]sono stati lasciati in giro...[n][w][e]

[msg MSG_PCTool [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Quindi questo 因 un "mouse", eh?[n]Non ti preoccupare,[n]non lo mangio mica.[n][w][e]

[msg MND_PCTool]
[s][vp 1 0 0 0 0 0]Qualcuno ha lasciato qui[n]un computer. Sar稲 rotto?[n][w][e]

[msg MSG_Callig01 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Chiunque l'abbia scritto[n]non 因 un granch姻...[n][w][e]

[msg MND_Callig01]
[s][vp 1 0 0 0 0 0]I tratti sono davvero incerti...[n][w][e]

[msg MSG_Callig02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Non si riesce nemmeno aleggere cosa c'因 scritto...[n][w][e]

[msg MND_Callig02]
[s][vp 1 0 0 0 0 0]I tratti sono davvero incerti...[n][w][e]

[msg MND_E14710100_GOTO_BldgB]
[s][vp 1 0 0 0 0 0]Gli studenti si stanno[n]spintonando di fronte[n]alle scale...[n][w][e]
[s][vp 1 0 0 0 0 0]Forse posso riuscire a farmi largo[n]con le maniere forti...[n][w][e]

[msg MND_E12310100_CHK_LANDIN]
[s][vp 1 0 0 0 0 0]Il tetto dell'edificio laboratori[n]dovrebbe essere oltre questo punto.[n]Non credo che riuscir韻 a passare...[n][w][e]
[s][vp 1 0 0 0 0 0]Forse Ryuji intendeva il[n][clr 2]tetto dell'edificio aule[clr 27]...[n][w][e]

[msg MND_E12720100_CHK_LANDIN]
[s][vp 1 0 0 0 0 0]Se salgo per le scale, raggiunger韻[n]il tetto dell'edificio laboratori.[n][w][e]
[s][vp 1 0 0 0 0 0]Per韻 quell'area sembra off-limits.[n]Ci sono banchi e altre cose impilate.[n][w][e]

[msg MND_E13710100_CHK_LANDIN]
[s][vp 1 0 0 0 0 0]Se salgo per le scale, raggiunger韻[n]il tetto dell'edificio laboratori.[n][w][e]
[s][vp 1 0 0 0 0 0]Per韻 quell'area sembra off-limits.[n]Ci sono banchi e altre cose impilate.[n][w][e]

[msg MSG_E13910100_CHK_LANDIN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_LANDIN]
[s][vp 1 0 0 0 0 0]Se salgo per le scale, raggiunger韻[n]il tetto dell'edificio laboratori.[n][w][e]
[s][vp 1 0 0 0 0 0]Per韻 quell'area sembra off-limits.[n]Ci sono banchi e altre cose impilate.[n][w][e]

[msg MND_E14710100_CHK_LANDIN]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_LANDIN [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Il tetto 因 chiuso. Il consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_LANDING_0]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Non adesso. L'aula del consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Qui non ti serve nulla, vero? Il[n]consiglio studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E12310100_CHK_ONGAKU]
[s][vp 1 0 0 0 0 0]Questa sembra l'aula di Musica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono molte immagini di[n]compositori. Hanno tutti la tipica[n]espressione vagamente minacciosa...[n][w][e]

[msg MND_E12720100_CHK_ONGAKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Musica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono molte immagini di[n]compositori. Hanno tutti la tipica[n]espressione vagamente minacciosa...[n][w][e]

[msg MND_E13710100_CHK_ONGAKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Musica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono molte immagini di[n]compositori. Hanno tutti la tipica[n]espressione vagamente minacciosa...[n][w][e]

[msg MSG_E13910100_CHK_ONGAKU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_ONGAKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Musica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono molte immagini di[n]compositori. Hanno tutti la tipica[n]espressione vagamente minacciosa...[n][w][e]

[msg MND_E14710100_CHK_ONGAKU]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_ONGAKU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]L'aula di Musica. Il consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_ONGAKUSIT]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_PCROOM]
[s][vp 1 0 0 0 0 0]Sembra l'aula computer.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono pochissimi studenti.[n]Probabilmente, 因 perch姻 questi[n]computer sono un po' obsoleti.[n][w][e]

[msg MND_E12720100_CHK_PCROOM]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula computer.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono pochissimi studenti.[n]Probabilmente, 因 perch姻 questi[n]computer sono un po' obsoleti.[n][w][e]

[msg MND_E13710100_CHK_PCROOM]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula computer.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono pochissimi studenti.[n]Probabilmente, 因 perch姻 questi[n]computer sono un po' obsoleti.[n][w][e]

[msg MSG_E13910100_CHK_PCROOM [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_PCROOM]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula computer.[n][w][e]
[s][vp 1 0 0 0 0 0]Ci sono pochissimi studenti.[n]Probabilmente, 因 perch姻 questi[n]computer sono un po' obsoleti.[n][w][e]

[msg MND_E14710100_CHK_PCROOM]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_PCROOM [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]L'aula computer. Il consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_PCROOM_00]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_JISHUS]
[s][vp 1 0 0 0 0 0]Sembra essere[n]l'aula studio.[n][w][e]
[s][vp 1 0 0 0 0 0]Studiano tutti in silenzio...[n][w][e]

[msg MND_E12720100_CHK_JISHUS]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula studio.[n][w][e]
[s][vp 1 0 0 0 0 0]Studiano tutti in silenzio...[n][w][e]

[msg MND_E13710100_CHK_JISHUS]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula studio.[n][w][e]
[s][vp 1 0 0 0 0 0]Studiano tutti in silenzio...[n][w][e]

[msg MSG_E13910100_CHK_JISHUS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_JISHUS]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula studio.[n][w][e]
[s][vp 1 0 0 0 0 0]Studiano tutti in silenzio...[n][w][e]

[msg MND_E14710100_CHK_JISHUS]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_JISHUS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]L'aula studio. L'aula del consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_JISHUSITU]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_SHODOS]
[s][vp 1 0 0 0 0 0]Questa sembra l'aula[n]di Calligrafia.[n][w][e]
[s][vp 1 0 0 0 0 0]Tutti i lavori esposti sono[n]bellissimi, ma il loro contenuto[n]因 piuttosto lugubre...[n][w][e]

[msg MND_E12720100_CHK_SHODOS]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Calligrafia.[n][w][e]
[s][vp 1 0 0 0 0 0]Tutti i lavori esposti sono[n]bellissimi, ma il loro contenuto[n]因 piuttosto lugubre...[n][w][e]

[msg MND_E13710100_CHK_SHODOS]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Calligrafia.[n][w][e]
[s][vp 1 0 0 0 0 0]Tutti i lavori esposti sono[n]bellissimi, ma il loro contenuto[n]因 piuttosto lugubre...[n][w][e]

[msg MSG_E13910100_CHK_SHODOS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SHODOS]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Calligrafia.[n][w][e]
[s][vp 1 0 0 0 0 0]Tutti i lavori esposti sono[n]bellissimi, ma il loro contenuto[n]因 piuttosto lugubre...[n][w][e]

[msg MND_E14710100_CHK_SHODOS]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_SHODOS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]L'aula di Calligrafia. Il consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_SHODOSITU]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Sembra un ripostiglio.[n][w][e]
[s][vp 1 0 0 0 0 0]I pacchi all'interno sono[n]in completo disordine...[n][w][e]

[msg MND_E12720100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MND_E13710100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_E13910100_CHK_SOUKO_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MND_E14710100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_SOUKO_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Sembra il ripostiglio. Il consiglio[n]studentesco non 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_SOUKO_01_]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_SOUKO__2]
[s][vp 1 0 0 0 0 0]Sembra un ripostiglio.[n][w][e]
[s][vp 1 0 0 0 0 0]La maniglia 因 coperta di[n]polvere. Forse 因 perch姻 la porta[n]viene aperta di rado...[n][w][e]

[msg MND_E12720100_CHK_SOUKO__2]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MND_E13710100_CHK_SOUKO__2]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_E13910100_CHK_SOUKO__2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SOUKO__2]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MND_E14710100_CHK_SOUKO__2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_SOUKO__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Dovrebbe essere il ripostiglio.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_SOUKO_02_]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MSG_KFEVT_EXIT_DOOR [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Quella 因 l'uscita d'emergenza![n]Meglio non toccarla...[n][w][e]

[msg MND_KFEVT_EXIT_DOOR]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

