[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_Roof [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oh, 因 chiusa... Non dovremmo[n]andare da un'altra parte?[n][w][e]

[msg MSG_ROOF_MAKOTO_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Sembra chiusa a chiave.[n][w][e]

[msg MSG_ROOF_HARU_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oh... 為 chiusa. Mi sa che senza[n]Haru non possiamo entrare.[n][w][e]

[msg MSG_STUDENT_COUNCIL_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, non hai motivo di entrare nell'aula[n]del consiglio studentesco, vero?[n][w][e]

[msg MSG_STUDENT_COUNCIL]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula del[n]consiglio studentesco.[n][w][e]
[s][vp 1 0 0 0 0 0]Le sedie al suo interno sono[n]disposte in perfetto ordine...[n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Il bagno puzza un po' di muffa...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non sai che quello 因 il bagno[n]femminile?[n]Non dovresti entrarci...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_Board_AfterKamo [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]"Non rilasciate dichiarazioni[n]fuori da scuola"?[n]Ma ne parlano gi稲 tutti...[n][w][e]

[msg MSG_BOARD_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"Codice di Condotta della Shujin[n]Academy". Ugh, 因[n]proprio specifico...[n][w][e]

[msg MSG_BOARD]
[s][vp 1 0 0 0 0 0]Questa bacheca 因 piena di[n]volantini dei club e messaggi[n]del consiglio studentesco...[n][w][e]

[msg MSG_RADIO_STUDIO_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Oooh, la sala trasmissioni... Forse[n]dovresti intrufolarti e[n]presentarti alla scuola![n][w][e]

[msg MSG_RADIO_STUDIO]
[s][vp 1 0 0 0 0 0]Gli studenti in sala trasmissioni[n]stanno mettendo in ordine i CD...[n][w][e]

[msg MSG_GRADE1_CLASS_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]...Questa 因 un'aula del primo anno.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Non conosci nessuno qui,[n]vero? Non dovremmo entrare[n]senza alcun motivo.[n][w][e]

[msg MSG_GRADE1_CLASS]
[s][vp 1 0 0 0 0 0]Questa 因 un'aula del primo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Gli studenti sembrano chiedersi[n]perch姻 mi trovi qui. Forse dovrei[n]andare altrove...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, se vuoi uscire dovremmo[n]usare l'entrata principale.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg MSG_E13710100_NG_BldgA3F [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Di l稲 si va all'edificio[n]laboratori. Noi dobbiamo raggiungere[n]l'aula della classe D.[n][w][e]

[msg MND_E13710100_NG_BldgA3F]
[s][vp 1 0 0 0 0 0]Dovrei lasciare l'edificio laboratori[n]a Ryuji...[n][w][e]

[msg MND_E12310100_GOTO_Rooft]
[s][vp 1 0 0 0 0 0]C'因 un cartello che vieta[n]l'ingresso, ma la porta[n]a quanto pare 因 aperta...[n][w][e]

[msg MND_E12720100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]Al momento non ho niente[n]da fare sul tetto...[n][w][e]

[msg MSG_E13710100_NG_Rooftop [Ryuji]]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Non credo che lass迂[n]troveremo qualcuno della[n]squadra di pallavolo.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]C'因 scritto che l'ingresso 因[n]vietato, quindi non ci va nessuno.[n][w][e]

[msg MND_E13710100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]Il tetto non 因 un posto[n]molto frequentato. Cerchiamo[n]da un'altra parte...[n][w][e]

[msg MND_E13710100_NG_Rooftop_2]
[s][vp 1 0 0 0 0 0]Al momento non ho niente[n]da fare sul tetto...[n][w][e]

[msg MSG_E13910100_NG_Rooftop [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]Al momento non ho niente[n]da fare sul tetto...[n][w][e]

[msg MND_E14710100_NG_Rooftop]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_NG_Rooftop [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Non si pu韻 andare sul tetto.[n]Andiamo all'aula del consiglio[n]studentesco al terzo piano.[n][w][e]

[msg MSG_E24320100_NG_Rooftop [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non si pu韻 andare sul tetto.[n]Proviamo da un'altra parte.[n][w][e]

[msg MND_COMMON_NG_Rooftop_00]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MND_E12310100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]In biblioteca ci sono[n]persone che studiano[n]nel silenzio generale...[n][w][e]

[msg MND_E12720100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]In biblioteca ci sono[n]persone che studiano[n]nel silenzio generale...[n][w][e]

[msg MSG_E13710100_CHK_LIBRAR [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7161 65535 0]Ehi, la sai una cosa?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]In questa biblioteca non c'因[n]neanche un manga...[n][w][e]

[msg MND_E13710100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Non vedo studenti in biblioteca...[n][w][e]

[msg MSG_E13910100_CHK_LIBRAR [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]In biblioteca ci sono[n]persone che studiano[n]nel silenzio generale...[n][w][e]

[msg MND_E14710100_CHK_LIBRAR]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_LIBRAR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Pi迂 tardi. Non devi andare[n]all'aula del consiglio studentesco[n]al terzo piano?[n][w][e]

[msg MND_COMMON_CHK_LIBRARY_0]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MND_E12310100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula del[n]consiglio studentesco.[n][w][e]
[s][vp 1 0 0 0 0 0]Le sedie al suo interno sono[n]disposte in perfetto ordine...[n][w][e]

[msg MND_E12720100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula del[n]consiglio studentesco.[n][w][e]
[s][vp 1 0 0 0 0 0]Le sedie al suo interno sono[n]disposte in perfetto ordine...[n][w][e]

[msg MSG_E13710100_CHK_STUDEN [Ryuji]]
[s][bup 0 2 202 0 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Non possiamo contare sul[n]consiglio studentesco.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quelli vogliono solo fare[n]contenti gli insegnanti.[n]Non gli importa nient'altro.[n][w][e]

[msg MND_E13710100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula del[n]consiglio studentesco.[n][w][e]
[s][vp 1 0 0 0 0 0]Le sedie al suo interno sono[n]disposte in perfetto ordine...[n][w][e]

[msg MSG_E13910100_CHK_STUDEN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula del[n]consiglio studentesco.[n][w][e]
[s][vp 1 0 0 0 0 0]Le sedie al suo interno sono[n]disposte in perfetto ordine...[n][w][e]

[msg MND_E14710100_CHK_STUDEN]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_GOTO_STUDE [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1020 0 0]Questa 因 l'aula del[n]consiglio studentesco.[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Perch姻 ci hanno convocati qui?[n]Che strano...[n][w][e]

[msg MND_COMMON_CHK_STUDENT_C]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Il bagno puzza un po' di muffa...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Il bagno puzza un po' di muffa...[n][w][e]

[msg MSG_E13710100_CHK_TOILET [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7200 65535 0]Oh, la stavo trattenendo[n]da un sacco di tempo. Meglio[n]andarci, finch姻 possiamo![n][w][e]

[msg MSG_E13710100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Fiuuu...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_3 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Bene, proseguiamo![n]Inizieremo dando un'occhiata[n]in classe tua.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_4 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Ti scappa di nuovo?[n]Ci siamo appena andati.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Il bagno puzza un po' di muffa...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Per ora, andiamo[n]in cortile...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_GOTO_TOILE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Lo farai pi迂 tardi. Devi andare[n]all'aula del consiglio studentesco[n]al terzo piano, giusto?[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Il bagno puzza un po' di muffa...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ehi, coso, non puoi entrare l淫![n]Muoviamoci e andiamo[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]L稲 non ti serve nulla, vero? Non[n]devi andare all'aula del consiglio[n]studentesco al terzo piano?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12310100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Questa bacheca 因 piena di[n]volantini dei club e messaggi[n]del consiglio studentesco...[n][w][e]

[msg MND_E12720100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Questa bacheca 因 piena di[n]volantini dei club e messaggi[n]del consiglio studentesco...[n][w][e]

[msg MSG_E13710100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Che stai facendo?[n]Forza, andiamo[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Questa bacheca 因 piena di[n]volantini dei club e messaggi[n]del consiglio studentesco...[n][w][e]

[msg MSG_E13910100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Questa bacheca 因 piena di[n]volantini dei club e messaggi[n]del consiglio studentesco...[n][w][e]

[msg MND_E14710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_BOARD_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]C'因 qualche problema? Stai andando[n]all'aula del consiglio studentesco[n]al terzo piano, giusto?[n][w][e]

[msg MND_COMMON_CHK_BOARD_000]
[s][vp 1 0 0 0 0 0]Questa bacheca 因 piena di[n]volantini dei club e messaggi[n]del consiglio studentesco...[n][w][e]

[msg MND_E12310100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Gli studenti in sala trasmissioni[n]stanno mettendo in ordine i CD...[n][w][e]

[msg MND_E12720100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Gli studenti in sala trasmissioni[n]stanno mettendo in ordine i CD...[n][w][e]

[msg MSG_E13710100_CHK_HOUSOS [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 7159 65535 0]Oh, perch姻 non proviamo[n]a riunire la squadra di pallavolo[n]con un annuncio?[n][w][e]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Anzi, no. Kamoshida lo sentirebbe[n]e verrebbe qui.[n][w][e]

[msg MND_E13710100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Gli studenti in sala trasmissioni[n]stanno mettendo in ordine i CD...[n][w][e]

[msg MSG_E13910100_CHK_HOUSOS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Gli studenti in sala trasmissioni[n]stanno mettendo in ordine i CD...[n][w][e]

[msg MND_E14710100_CHK_HOUSOS]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_HOUSOS [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Quella 因 la sala trasmissioni. Non[n]devi andare all'aula del consiglio[n]studentesco al terzo piano?[n][w][e]

[msg MND_COMMON_CHK_HOUSOSITU]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Questa 因 un'aula del primo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Gli studenti sembrano chiedersi[n]perch姻 mi trovi qui. Forse dovrei[n]andare altrove...[n][w][e]

[msg MND_E12720100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Questa 因 un'aula del primo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Gli studenti sembrano chiedersi[n]perch姻 mi trovi qui. Forse dovrei[n]andare altrove...[n][w][e]

[msg MSG_E13710100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 202 0 0][f 4 10 65535 0 0][vp 8 2 1 7047 65535 0]Non vedo nessuno della[n]squadra di pallavolo.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Iniziamo a chiedere ai[n]tuoi compagni di classe![n][w][e]

[msg MND_E13710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Non vedo studenti con[n]ferite vistose...[n][w][e]

[msg MSG_E13910100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Questa 因 un'aula del primo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Gli studenti sembrano chiedersi[n]perch姻 mi trovi qui. Forse dovrei[n]andare altrove...[n][w][e]

[msg MND_E14710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Quella 因 la classe del primo anno.[n]Andiamo all'aula del consiglio[n]studentesco al terzo piano.[n][w][e]

[msg MND_COMMON_CHK_CLASS_1_0]
[s][vp 1 0 0 0 0 0]Questa 因 un'aula del primo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

