[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_Kyokan [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_GYMNASIUM_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Vuoi allenarti qui? Non[n]sarebbe da te...[n][w][e]

[msg MSG_GYMNASIUM_MORU_Train [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Non 因 pi迂 figo allenarti[n]da solo in camera tua?[n][w][e]

[msg MSG_GYMNASIUM]
[s][vp 1 0 0 0 0 0]Non ho motivo di andare[n]in palestra...[n][w][e]

[msg AUTO_MACHINE01_NOTOPEN]
[s][vp 1 0 0 0 0 0]Dice che 因 in manutenzione.[n]Non credo funzioni...[n][w][e]

[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non sai che quello 因 il bagno[n]femminile?[n]Non dovresti entrarci...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_BIJUTU_ROOM_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]E-Ehi! C'因 qualcosa[n]che puzza da morire qui![n][w][e]

[msg MSG_BIJUTU_ROOM]
[s][vp 1 0 0 0 0 0]Nella stanza c'因[n]un orrido tanfo...[n][w][e]

[msg MSG_SITYOU_ROOM_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]C'因 un grosso proiettore[n]qui... Lo schermo sembra quasi[n]la vela di una nave.[n][w][e]

[msg MSG_SITYOU_ROOM]
[s][vp 1 0 0 0 0 0]C'因 uno strano proiettore qui...[n][w][e]

[msg MSG_KAGAKU_ROOM_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Mi piace come sono ordinate[n]queste provette... Non sembra[n]il posto adatto a uno come me?[n][w][e]

[msg MSG_KAGAKU_ROOM]
[s][vp 1 0 0 0 0 0]Gli scaffali dell'aula di Chimica[n]sono zeppi di provette...[n][w][e]

[msg MSG_SEIBUTU_ROOM_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Ci sono tantissimi campioni[n]qui. Spero che non[n]dissezionino anche gatti...[n][w][e]

[msg MSG_SEIBUTU_ROOM]
[s][vp 1 0 0 0 0 0]Ci sono molti esemplari a[n]decorazione dell'aula di Biologia.[n][w][e]

[msg MSG_TEACHERS_ROOM_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Questa stanza 因 un vero disastro...[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra quasi una camera[n]da letto piuttosto che un ufficio.[n][w][e]

[msg MSG_TEACHERS_ROOM]
[s][vp 1 0 0 0 0 0]La sala docenti di Educazione[n]Fisica 因 piena di cianfrusaglie.[n][w][e]

[msg MSG_SCIENCE_TOOL_ROOM_MO [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]C-C'因 qualcuno l淫![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un attimo... 因 una bambola? O-Oh,[n]因 un modello anatomico...[n][w][e]

[msg MSG_SCIENCE_TOOL_ROOM]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino di Scienze.[n][w][e]
[s][vp 1 0 0 0 0 0]Al buio s'intravede la sagoma[n]di un modello anatomico...[n][w][e]

[msg MSG_WAREHOUSE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]為 un ripostiglio, questo?[n]Sembra chiuso a chiave.[n][w][e]

[msg MSG_WAREHOUSE]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_Bijutu_Tool [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Che casino... Non credo che[n]questi ragazzi siano[n]davvero interessati all'arte.[n][w][e]

[msg MND_Bijutu_Tool]
[s][vp 1 0 0 0 0 0]Le tele sono un disastro...[n][w][e]

[msg MSG_Kagaku_Tool [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ma 因 possibile lasciare delle[n]medicine aperte cos淫? Oh, 因 vuoto.[n][w][e]

[msg MND_Kagaku_Tool]
[s][vp 1 0 0 0 0 0]Ci sono contenitori di[n]medicine vuoti sulla scrivania...[n][w][e]

[msg MSG_Turtle [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Una tartaruga... Cos'因,[n]la mascotte della classe?[n][w][e]

[msg MND_Turtle]
[s][vp 1 0 0 0 0 0]La tartaruga sta cercando[n]di allungare il collo...[n][w][e]

[msg MSG_POLICEMAN_02_003_01 [Agente distaccato]]
[s][f 4 23 1 6 3 10 0 0][vp 8 2 1 0 6 0]Scusa, ma stiamo indagando[n]all'interno. Potresti allontanarti[n]da quest'area per un po'?[n][w][e]
[s][vp 8 2 1 0 6 0]Mi spiace averti spaventato.[n]Apprezzerei la tua cooperazione.[n][w][e]

[msg MSG_E15010100_NG_BldgB2F [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_NG_BldgB2F]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E15010100_NG_BldgB2F_2 [Mishima]]
[s][bup 0 111 505 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]E-Ehi! La [clr 2]sala docenti[n]di Educazione Fisica[clr 27] 因[n]su questo piano![n][w][e]

[msg MND_E15010100_NG_BldgB2F_2]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E14710100_NG_BldgB2F [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7040 65535 0]Quella non 因 la direzione giusta![n]Dobbiamo scendere di sotto[n]e andare di corsa in cortile![n][w][e]

[msg MSG_E15010100_NG_BldgB2F_3 [Mishima]]
[s][bup 0 111 505 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 65535 0]E-Ehi! La [clr 2]sala docenti[n]di Educazione Fisica[clr 27] 因[n]su questo piano![n][w][e]

[msg MND_E15010100_NG_BldgB2F_3]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E65410200_NG_BldgB2F [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando? Dobbiamo[n]inseguire quella farfalla![n][w][e]

[msg MND_E12310100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Pare che da qui si possa[n]raggiungere la palestra.[n][w][e]
[s][vp 1 0 0 0 0 0]Non dovrei aprire[n]senza motivo...[n][w][e]

[msg MND_E12720100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]為 l'ingresso alla palestra[n]dal secondo piano. Non dovrei[n]aprirlo senza motivo...[n][w][e]

[msg MND_E13710100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Sento le voci allegre degli[n]studenti che stanno pulendo...[n][w][e]

[msg MSG_E13910100_CHK_TAIIKU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]為 l'ingresso alla palestra[n]dal secondo piano. Non dovrei[n]aprirlo senza motivo...[n][w][e]

[msg MND_E14710100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MND_E15010100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TAIIKU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]為 l'ingresso alla palestra del piano 2.[n]Il consiglio studentesco 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27].[n][w][e]

[msg MND_COMMON_CHK_TAIIKUKAN]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]為 molto pi迂 sporco di quelli[n]dell'edificio aule...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_TOILET [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Non adesso. L'aula del consiglio[n]studentesco non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno degli uomini...[n][w][e]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare, per ora...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_TOILET_2 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Qui non ti serve nulla, vero?[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Questo 因 il bagno delle donne...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio uscire di qui.[n]Se ci resto troppo a lungo,[n]qualcuno si far稲 strane idee.[n][w][e]

[msg MND_E12310100_CHK_BIJUTU]
[s][vp 1 0 0 0 0 0]Questa sembra l'aula di Arte.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 uno sgradevole odore[n]chimico qui.[n]Probabilmente 因 il solvente...[n][w][e]

[msg MND_E12720100_CHK_BIJUTU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Arte.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 uno sgradevole odore[n]chimico qui.[n]Probabilmente 因 il solvente...[n][w][e]

[msg MND_E13710100_CHK_BIJUTU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Arte.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 uno sgradevole odore[n]chimico qui.[n]Probabilmente 因 il solvente...[n][w][e]

[msg MSG_E13910100_CHK_BIJUTU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_BIJUTU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Arte.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 uno sgradevole odore[n]chimico qui.[n]Probabilmente 因 il solvente...[n][w][e]

[msg MND_E14710100_CHK_BIJUTU]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_BIJUTU [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_BIJUTU]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_BIJUTU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Questa 因 l'aula di Arte.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_BIJUTUSIT]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_SITYOK]
[s][vp 1 0 0 0 0 0]Questo sembra il magazzino[n]audiovisivi.[n][w][e]
[s][vp 1 0 0 0 0 0]Nella parte anteriore dell'aula[n]c'因 un grande schermo...[n][w][e]

[msg MND_E12720100_CHK_SITYOK]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino audiovisivi.[n][w][e]
[s][vp 1 0 0 0 0 0]Nella parte anteriore dell'aula[n]c'因 un grande schermo...[n][w][e]

[msg MND_E13710100_CHK_SITYOK]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino audiovisivi.[n][w][e]
[s][vp 1 0 0 0 0 0]Nella parte anteriore dell'aula[n]c'因 un grande schermo...[n][w][e]

[msg MSG_E13910100_CHK_SITYOK [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SITYOK]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino audiovisivi.[n][w][e]
[s][vp 1 0 0 0 0 0]Nella parte anteriore dell'aula[n]c'因 un grande schermo...[n][w][e]

[msg MND_E14710100_CHK_SITYOK]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_SITYOK [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_SITYOK]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_SITYOK [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Questo 因 il magazzino audiovisivi.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_SITYOKAKU]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_KAGAKU]
[s][vp 1 0 0 0 0 0]Questo posto sembra[n]l'aula di Chimica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ampolle, fornelli e altre[n]attrezzature da laboratorio[n]sono tenuti in ordine...[n][w][e]

[msg MND_E12720100_CHK_KAGAKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Chimica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ampolle, fornelli e altre[n]attrezzature da laboratorio[n]sono tenuti in ordine...[n][w][e]

[msg MND_E13710100_CHK_KAGAKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Chimica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ampolle, fornelli e altre[n]attrezzature da laboratorio[n]sono tenuti in ordine...[n][w][e]

[msg MSG_E13910100_CHK_KAGAKU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_KAGAKU]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Chimica.[n][w][e]
[s][vp 1 0 0 0 0 0]Ampolle, fornelli e altre[n]attrezzature da laboratorio[n]sono tenuti in ordine...[n][w][e]

[msg MND_E14710100_CHK_KAGAKU]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_KAGAKU [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_KAGAKU]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_KAGAKU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Questa 因 l'aula di Chimica.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_KAGAKUSIT]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_SEIBUT]
[s][vp 1 0 0 0 0 0]Questa sembra l'aula di Biologia.[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra decorata con[n]campioni di diversi organismi...[n][w][e]

[msg MND_E12720100_CHK_SEIBUT]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Biologia.[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra decorata con[n]campioni di diversi organismi...[n][w][e]

[msg MND_E13710100_CHK_SEIBUT]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Biologia.[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra decorata con[n]campioni di diversi organismi...[n][w][e]

[msg MSG_E13910100_CHK_SEIBUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SEIBUT]
[s][vp 1 0 0 0 0 0]Questa 因 l'aula di Biologia.[n][w][e]
[s][vp 1 0 0 0 0 0]Sembra decorata con[n]campioni di diversi organismi...[n][w][e]

[msg MND_E14710100_CHK_SEIBUT]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_SEIBUT [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_SEIBUT]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_SEIBUT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Questa 因 l'aula di Biologia.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_SEIBUTUSI]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_KYOKAN]
[s][vp 1 0 0 0 0 0]C'因 scritto che 因 la[n]sala docenti di Educazione Fisica.[n][w][e]
[s][vp 1 0 0 0 0 0]為 piena di oggetti di[n]vario tipo, alcuni presi[n]direttamente agli studenti...[n][w][e]

[msg MND_E12720100_CHK_KYOKAN]
[s][vp 1 0 0 0 0 0]Questa 因 la sala docenti[n]di Educazione Fisica.[n][w][e]
[s][vp 1 0 0 0 0 0]為 piena di oggetti di[n]vario tipo, alcuni presi[n]direttamente agli studenti...[n][w][e]

[msg MND_E13710100_CHK_KYOKAN]
[s][vp 1 0 0 0 0 0]Questa 因 la sala docenti[n]di Educazione Fisica.[n][w][e]
[s][vp 1 0 0 0 0 0]為 piena di oggetti di[n]vario tipo, alcuni presi[n]direttamente agli studenti...[n][w][e]

[msg MSG_E13910100_CHK_KYOKAN [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_KYOKAN]
[s][vp 1 0 0 0 0 0]Questa 因 la sala docenti[n]di Educazione Fisica.[n][w][e]
[s][vp 1 0 0 0 0 0]為 piena di oggetti di[n]vario tipo, alcuni presi[n]direttamente agli studenti...[n][w][e]

[msg MND_E14710100_CHK_KYOKAN]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_KYOKAN [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Questa 因 la palestra.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_KYOKANSIT]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_RIKAJU]
[s][vp 1 0 0 0 0 0]Questo sembra il[n]magazzino di Scienze.[n][w][e]
[s][vp 1 0 0 0 0 0]Qui dentro ci sono tantissime[n]cose dall'aspetto strano[n]e discutibile...[n][w][e]

[msg MND_E12720100_CHK_RIKAJU]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino di Scienze.[n][w][e]
[s][vp 1 0 0 0 0 0]Qui dentro ci sono tantissime[n]cose dall'aspetto strano[n]e discutibile...[n][w][e]

[msg MND_E13710100_CHK_RIKAJU]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino di Scienze.[n][w][e]
[s][vp 1 0 0 0 0 0]Qui dentro ci sono tantissime[n]cose dall'aspetto strano[n]e discutibile...[n][w][e]

[msg MSG_E13910100_CHK_RIKAJU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_RIKAJU]
[s][vp 1 0 0 0 0 0]Questo 因 il magazzino di Scienze.[n][w][e]
[s][vp 1 0 0 0 0 0]Qui dentro ci sono tantissime[n]cose dall'aspetto strano[n]e discutibile...[n][w][e]

[msg MND_E14710100_CHK_RIKAJU]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_RIKAJU [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_RIKAJU]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_RIKAJU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Questo 因 il magazzino di Scienze.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_RIKAJUNBI]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12310100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Sembra un ripostiglio.[n][w][e]
[s][vp 1 0 0 0 0 0]Non riesco a vedere bene[n]all'interno a causa di[n]tutti quei pacchi...[n][w][e]

[msg MND_E12720100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MND_E13710100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MSG_E13910100_CHK_SOUKO_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Il ripostiglio 因 chiuso a chiave.[n][w][e]

[msg MND_E14710100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E15010100_CHK_SOUKO_ [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19082 65535 0]Credo che Sakamoto sia andato nella[n][clr 2]sala docenti di Educazione Fisica[clr 27].[n][w][e]

[msg MND_E15010100_CHK_SOUKO_]
[s][vp 1 0 0 0 0 0]Per ora 因 meglio provare[n]a raggiungere Ryuji...[n][w][e]

[msg MSG_E23810100_CHK_SOUKO_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Dovrebbe essere il ripostiglio.[n]L'aula del consiglio studentesco[n]non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_SOUKO_000]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

