[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_GYMNASIUM_00]
[s]La squadra di pallavolo sta[n]usando la palestra. Sento il rumore[n]del pallone persino da qui...[n][w][e]

[msg MSG_GYMNASIUM_01]
[s]La squadra di pallavolo sta[n]usando la palestra. Sento il rumore[n]del pallone persino da qui...[n][w][e]

[msg MSG_GYMNASIUM_01_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]La squadra di pallavolo si sta[n]allenando. Stanno sempre[n]a fare pratica, eh?[n][w][e]

[msg MSG_GYMNASIUM_01_MOR_K_C [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Ora la palestra 因 tranquilla.[n]Che la squadra sia in pausa?[n][w][e]

[msg MSG_GYMNASIUM_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]C'因 una squadra che si allena,[n]ma non 因 quella di pallavolo.[n][w][e]

[msg MSG_GYMNASIUM_03 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]C'因 una squadra che si allena.[n]Forse dovresti unirti a loro![n][w][e]

[msg MSG_GYMNASIUM_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]C'因 una squadra che si allena.[n]Chiss稲 che fatica con questo caldo.[n][w][e]

[msg MSG_GYMNASIUM_05 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ci sono alcuni membri di una[n]squadra che si allenano. Si danno[n]davvero molto da fare...[n][w][e]

[msg MSG_GYMNASIUM_06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Qui si stanno preparando[n]per il festival scolastico.[n]Sembrano tutti cos淫 impegnati.[n][w][e]

[msg MSG_GYMNASIUM_07 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]C'因 una squadra in palestra[n]al momento. Sembra che si stiano[n]allenando molto duramente.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Al momento non ho sete...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg MSG_E13710100_NG_Yard_Bl [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Di l稲 si va all'edificio[n]laboratori. Noi dobbiamo raggiungere[n]l'aula della classe D.[n][w][e]

[msg MND_E13710100_NG_Yard_Bl]
[s][vp 1 0 0 0 0 0]Dovrei lasciare l'edificio laboratori[n]a Ryuji...[n][w][e]

[msg MSG_E65110100_NG_Yard_Bl [Lavenza]]
[s][bup 0 100 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 24008 65535 0]......[n][w][e]

[msg MND_E65110100_NG_Yard_Bl]
[s][vp 1 0 0 0 0 0]Non 因 di qua...[n][w][e]

[msg MND_E12310100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Questo sembra l'ingresso[n]della palestra.[n][w][e]

[msg MND_E12720100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Questo sembra l'ingresso[n]della palestra.[n][w][e]

[msg MSG_E13710100_CHK_TAIIKU [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7035 65535 0]Quello che ho visto al castello[n]non era in palestra.[n][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Iniziamo dando un'occhiata[n]in classe tua.[n][w][e]

[msg MND_E13710100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]In palestra non ho[n]trovato studenti con[n]ferite vistose...[n][w][e]

[msg MSG_E13910100_CHK_TAIIKU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_TAIIKU]
[s][vp 1 0 0 0 0 0]Questo sembra l'ingresso[n]della palestra.[n][w][e]

[msg MSG_E23810100_CHK_TAIIKU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]為 l'ingresso alla palestra. Il[n]consiglio studentesco 因 al [clr 2]terzo[n]piano dell'edificio principale[clr 27].[n][w][e]

[msg MND_COMMON_CHK_TAIIKUKAN]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MSG_E13710100_CHK_AUTO_M [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Ehi, non puoi farlo dopo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]La partita finir稲, non[n]possiamo metterci troppo![n][w][e]

[msg MND_E13710100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

[msg MSG_E13910100_CHK_AUTO_M [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E65110100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Sar稲 meglio che mi sbrighi...[n][w][e]

[msg MND_COMMON_CHK_AUTO_MACH]
[s][vp 1 0 0 0 0 0]Verr韻 qui a comprare qualcosa[n]quando ne avr韻 il tempo...[n][w][e]

