[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_KITCHEN_DUMMY]
[s]Ho consegnato lo scontrino.[n][w][e]
[s]Ho mangiato il menu per gli[n]studenti in mensa.[n][w][e]
[s]Ho ottenuto un qualche effetto.[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_KITCHEN_WOMAN_INFO [Cameriera]]
[s]Se vuoi ordinare, devi comprare[n]lo scontrino da quella[n]macchinetta.[n][w][e]

[msg MSG_KITCHEN_THINK [Morgana]]
[s][bup 0 3 0 0 0]Cosa vuoi fare?[n]Vuoi mangiare qui?[n][w][e]

[sel MSG_KITCHEN_THINK_SEL top]
[s]Manger韻 qui.[e]
[s]Non manger韻 qui.[e]

[msg MSG_KITCHEN_WOMAN_START [Cameriera]]
[s]OK, devi attendere un po'.[n][w][e]

[msg MSG_KITCHEN_INFO_KAMO_BF [Morgana]]
[s][bup 0 3 0 0 0]C'因 una cucina dentro.[n]Pare che servano degli scontrini[n]per fare l'ordine.[n][w][e]

[msg MSG_KITCHEN_KAMO_BF_MORU [Morgana]]
[s][bup 0 3 0 0 0]C'因 un buon profumino qui dentro.[n]Qualche volta dovr韻 mangiarci[n]per forza...[n][w][e]

[msg MSG_KITCHEN_KAMO_AF_MORU [Morgana]]
[s][bup 0 3 0 0 0]Il profumo che viene dalla[n]cucina 因 delizioso.[n]Non resisto pi迂...[n][w][e]
[s]La tua espulsione 因 saltata e[n]Kamoshida non c'因 pi迂![n]Vedi di trattarti come si deve![n][w][e]

[msg MSG_KITCHEN_INFO_KAMO_AF [Morgana]]
[s][bup 0 3 0 0 0]C'因 una cucina dentro.[n]Pare che servano degli scontrini[n]per fare l'ordine.[n][w][e]

[msg MSG_KITCHEN_WOMAN_NO [Cameriera]]
[s]Ripuliamo tutto dopo scuola,[n]perci韻 tornate un'altra volta.[n][w][e]

[msg MSG_TICKET_START [Morgana]]
[s][bup 0 3 0 0 0]Quindi 因 qui che puoi[n]comprare lo scontrino.[n][w][e]
[s]Pare che tutti i piatti[n]sul menu costino [clr 2]500 yen[clr 27].[n]Che facciamo?[n][w][e]

[sel MSG_TICKET_THINK_SEL top]
[s]Compriamo uno scontrino.[e]
[s]No, passo.[e]

[msg MSG_TICKET_BUY [Morgana]]
[s][bup 0 3 0 0 0]Ora che l'acquisto 因 fatto,[n]possiamo mangiare![n][w][e]
[s]...Aspetta, cosa dovremmo[n]farci con questo scontrino?[n][w][e]

[msg MSG_TICKET_HAVE_TICKET [Morgana]]
[s][bup 0 3 0 0 0]Ehi, gi稲 ce l'hai lo[n]scontrino. Vedi di usarlo,[n]o lo sprecherai.[n][w][e]

[msg MSG_TICKET_NOMONEY [Morgana]]
[s][bup 0 3 0 0 0]...Si direbbe che tu non[n]abbia abbastanza soldi.[n][w][e]

[msg MSG_TICKET_NOT_BUY [Morgana]]
[s][bup 0 3 0 0 0]Mmm? La macchinetta non[n]funziona. Mi sa che hanno[n]chiuso per oggi.[n][w][e]

[msg MSG_KITCHEN_ERROR_MORU [Morgana]]
[s][bup 0 3 0 0 0]Mmm, che odorino.[n]Ma finiremmo nei guai[n]se entrassimo l淫 dentro...[n][w][e]

[msg MSG_KITCHEN_ERROR]
[s]Dalla cucina provengono[n]svariati aromi...[n][w][e]

[msg MSG_KITCHEN_ERROR_HOUKAG [Morgana]]
[s][bup 0 3 0 0 0]Chiss稲 com'因 la cucina della[n]mensa. Sono curioso...[n]Ma non entrare l淫 dentro, OK?[n][w][e]

[msg MSG_KITCHEN_ERROR_NULL]
[s]Dalla cucina sento arrivare un[n]odore di detersivo...[n][w][e]

[msg MND_KFEVT_COMMON_NG]
[s][vp 1 0 0 0 0 0]Per ora non devo fare[n]niente in particolare qui...[n][w][e]

