[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_Teache [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Vuoi ringraziare i professori?[n]Scherzavo, dai![n]Su, andiamo da un'altra parte![n][w][e]

[msg MSG_TEACHERS_DOOR_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Pare ci siano ancora[n]insegnanti qui. Sembrano[n]piuttosto tranquilli...[n][w][e]

[msg MSG_TEACHERS_DOOR]
[s][vp 1 0 0 0 0 0]Gli insegnanti sono nel[n]mezzo di una riunione...[n][w][e]

[msg MSG_PRINCIPAL_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Wow, quella stanza 因 pazzesca.[n]Trasuda autorit稲...[n][w][e]

[msg MSG_PRINCIPAL]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]nell'ufficio del preside...[n][w][e]

[msg MSG_CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]C'因 puzza di muffa...[n][w][e]

[msg MSG_CHK_QUEST10_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sbrigati e facciamola finita, OK?[n][w][e]

[msg MSG_CHK_QUEST10_01]
[s][vp 1 0 0 0 0 0]...C'因 qualcosa inciso[n]sulla parete del gabinetto.[n][w][e]
[s][vp 1 0 0 0 0 0]"Non la perdoner韻 mai![n]Si crede una regina con quel[n]bellimbusto al suo fianco!"[n][w][e]
[s][vp 1 0 0 0 0 0]"A chiunque stia leggendo: se[n]dovesti beccarti un pugno dal nulla,[n]sar稲 tutta colpa di Kuroko Hara!"[n][w][e]

[msg MSG_CHK_QUEST10_02]
[s][vp 1 0 0 0 0 0]Meglio tenere gli occhi aperti...[n][w][e]

[msg MSG_CHK_QUEST10_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ce ne hai messo di tempo...[n][w][e]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Oh, e ho visto una ragazza strana[n]in corridoio mentre non c'eri.[n]La sua voce mi ha dato i brividi![n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non sai che quello 因 il bagno[n]femminile?[n]Non dovresti entrarci...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_STUDENT_COUNCIL_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]L'aula del consulente studentesco?[n]Che nome pomposo.[n][w][e]

[msg MSG_STUDENT_COUNCIL]
[s][vp 1 0 0 0 0 0]Non mi serve alcuna consulenza...[n][w][e]

[msg MSG_BOARD_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Pare che qui siano pubblicati[n]tutti i prossimi eventi scolastici.[n][w][e]

[msg MSG_BOARD]
[s][vp 1 0 0 0 0 0]Questa 因 la scaletta dei[n]prossimi eventi scolastici...[n][w][e]

[msg MSG_GRADE2_CLASS_MORU [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]I ragazzi all'interno continuano a[n]guardarci... Non mi piace![n][w][e]

[msg MSG_GRADE2_CLASS]
[s][vp 1 0 0 0 0 0]Gli studenti all'interno continuano[n]a guardare da questa parte...[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ehi, se vuoi uscire dovremmo[n]usare l'entrata principale.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]Non ho motivo di usare[n]l'uscita di emergenza...[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg MND_E12010100_NG_BLDGA2F]
[s][vp 1 0 0 0 0 0]Sembra che di qua si[n]vada verso un altro edificio.[n][w][e]
[s][vp 1 0 0 0 0 0]La sala docenti dovrebbe[n]essere in [clr 2]quest'edificio[clr 27].[n][w][e]

[msg MSG_E13710100_NG_BLDGA2F [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Di l稲 si va all'edificio[n]laboratori. Noi dobbiamo raggiungere[n]l'aula della classe D.[n][w][e]

[msg MND_E13710100_NG_BLDGA2F]
[s][vp 1 0 0 0 0 0]Dovrei lasciare l'edificio laboratori[n]a Ryuji...[n][w][e]

[msg MND_E14710100_NG_BLDGA2F]
[s][vp 1 0 0 0 0 0]La strada verso l'edificio[n]laboratori 因 talmente affollata[n]che non riesco a passare...[n][w][e]
[s][vp 1 0 0 0 0 0]Meglio provarne un'altra...[n][w][e]

[msg MSG_E65410201_NG_BldgA2F [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MND_E12010100_NG_BldgA2F]
[s][vp 1 0 0 0 0 0]La sala docenti dovrebbe essere[n]su [clr 2]questo piano[clr 27].[n][w][e]

[msg MSG_E14710101_NG_BldgA2F [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Ehi, dove pensi di andare?!?[n]Dobbiamo scendere di corsa[n]in cortile![n][w][e]

[msg MSG_E65410201_NG_BldgA2F_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MSG_E65410201_NG_BldgA2F_3 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]La farfalla non 因 salita. 為 scesa![n][w][e]

[msg MND_E12010100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Sembrano indaffarati.[n]Non credo che riuscir韻[n]a passare di qua...[n][w][e]

[msg MND_E12010100_GOTO_TEACH]
[s][vp 1 0 0 0 0 0]Questa sembra la sala docenti.[n]為 tempo di entrare...[n][w][e]

[msg MND_E12310100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Gli insegnanti sono nel[n]mezzo di una riunione...[n][w][e]

[msg MND_E12720100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Gli insegnanti sono nel[n]mezzo di una riunione...[n][w][e]

[msg MSG_E13710100_CHK_TEACHE [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7046 65535 0]Non serve andare in[n]sala docenti, ti pare?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tanto, gli altri insegnanti non[n]diranno mai niente di compromettente[n]su Kamoshida...[n][w][e]

[msg MND_E13710100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Gli insegnanti sono nel[n]mezzo di una riunione...[n][w][e]

[msg MSG_E13910100_CHK_TEACHE [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Gli insegnanti sono nel[n]mezzo di una riunione...[n][w][e]

[msg MND_E14710100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Gli insegnanti sembrano[n]andare davvero di corsa...[n][w][e]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_TEACHE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Quella 因 la sala docenti. Non[n]devi andare all'aula del consiglio[n]studentesco [clr 2]al terzo piano[clr 27]?[n][w][e]

[msg MSG_E65410201_CHK_TEACHE [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, quella 因 la sala docenti.[n]Inseguiamo la farfalla[n]e andiamo al primo piano.[n][w][e]

[msg MND_COMMON_CHK_TEACHERRO]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12010100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]nell'ufficio del preside...[n][w][e]

[msg MND_E12310100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]nell'ufficio del preside...[n][w][e]

[msg MND_E12720100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]nell'ufficio del preside...[n][w][e]

[msg MSG_E13710100_CHK_Koucho [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7179 65535 0]Neanche il preside pu韻[n]fare niente a Kamoshida, sai?[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7175 65535 0]Merda... Questa scuola ha proprio[n]qualcosa che non va...[n][w][e]

[msg MND_E13710100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]nell'ufficio del preside...[n][w][e]

[msg MSG_E13910100_CHK_Koucho [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]Non ho niente da fare[n]nell'ufficio del preside...[n][w][e]

[msg MND_E14710100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]Non vedo il preside.[n][w][e]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_Koucho [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Cosa devi fare nell'ufficio del[n]preside? L'aula del consiglio[n]studentesco non 因 al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MSG_E65410201_CHK_Koucho [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]Cosa devi fare nell'ufficio del[n]preside? Inseguiamo la farfalla[n]e andiamo al primo piano.[n][w][e]

[msg MND_COMMON_CHK_KouchoRoo]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12010100_CHK_Myclas]
[s][vp 1 0 0 0 0 0]Al secondo piano dovrebbero[n]esserci tutte le aule[n]del secondo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora, 因 meglio che vada[n]in [clr 2]sala docenti[clr 27]...[n][w][e]

[msg MND_E14710100_CHK_Myclas]
[s][vp 1 0 0 0 0 0]Non ho tempo di tornare in classe.[n][w][e]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E65410201_CHK_Myclas [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, dove stai andando?[n]Non dobbiamo inseguire[n]quella farfalla?[n][w][e]

[msg MND_COMMON_CHK_Myclass_0]
[s][vp 1 0 0 0 0 0]Adesso non devo fare niente[n]in classe...[n][w][e]

[msg MND_E12010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'因 puzza di muffa...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'因 puzza di muffa...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'因 puzza di muffa...[n][w][e]

[msg MSG_E13710100_CHK_TOILET [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7200 65535 0]Oh, la stavo trattenendo[n]da un sacco di tempo. Meglio[n]andarci, finch姻 possiamo![n][w][e]

[msg MSG_E13710100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Fiuuu...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_3 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Bene, proseguiamo![n]Inizieremo dando un'occhiata[n]in classe tua.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_4 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Ti scappa di nuovo?[n]Ci siamo appena andati.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Non devo andare[n]in bagno...[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Per ora, andiamo[n]in cortile...[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]Lo farai pi迂 tardi. Devi andare[n]all'aula del consiglio studentesco[n][clr 2]al terzo piano[clr 27], giusto?[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Non devo andare[n]in bagno...[n][w][e]

[msg MND_E12010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Ehi, coso, non puoi entrare l淫![n]Muoviamoci e andiamo[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]L稲 non ti serve nulla, vero? Non[n]devi andare all'aula del consiglio[n]studentesco al [clr 2]terzo piano[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Non ho alcun motivo di[n]entrare nel bagno delle donne...[n][w][e]

[msg MND_E12010100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Non mi serve alcuna consulenza...[n][w][e]

[msg MND_E12310100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Questa sembra l'aula del[n]consulente studentesco.[n][w][e]
[s][vp 1 0 0 0 0 0]C'因 uno studente che parla[n]con un insegnante.[n][w][e]

[msg MND_E12720100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Non mi serve alcuna consulenza...[n][w][e]

[msg MSG_E13710100_CHK_SIDOSI [Ryuji]]
[s][bup 0 2 205 65535 0][f 4 10 65535 0 0][vp 8 2 1 7182 65535 0]Eh? Che c'因, qualcuno[n]ti ha chiamato?[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, lascia stare. Andiamo a sentire[n]che hanno da dire i membri[n]della squadra di pallavolo![n][w][e]

[msg MND_E13710100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Non sembra esserci nessuno...[n][w][e]

[msg MSG_E13910100_CHK_SIDOSI [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Ci sono diverse ragazze obbligate[n]a scrivere qualcosa...[n][w][e]

[msg MND_E14710100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_SIDOSI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Questa 因 l'aula del consulente[n]studentesco. L'aula del consiglio[n]studentesco 因 al [clr 2]terzo piano[clr 27].[n][w][e]

[msg MND_COMMON_CHK_SIDOSITU_]
[s][vp 1 0 0 0 0 0]Qui non devo fare niente[n]in particolare...[n][w][e]

[msg MND_E12010100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Sulla bacheca c'因 scritto il[n]programma degli eventi[n]della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]Dopodomani 因 previsto un[n]torneo di pallavolo.[n][w][e]

[msg MND_E12310100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Sulla bacheca c'因 scritto il[n]programma degli eventi[n]della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]Dopodomani 因 previsto un[n]torneo di pallavolo.[n][w][e]

[msg MND_E12720100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Sulla bacheca c'因 scritto il[n]programma degli eventi[n]della scuola.[n][w][e]
[s][vp 1 0 0 0 0 0]Oh, domani ci sar稲 una partita...[n][w][e]

[msg MSG_E13710100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Che stai facendo?[n]Forza, andiamo[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Sulla bacheca c'因 scritto il[n]programma degli eventi[n]della scuola.[n][w][e]

[msg MSG_E13910100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, che stai facendo?!?[n]Dobbiamo sbrigarci a[n]raggiungere Mishima![n][w][e]

[msg MND_E14130100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Sulla bacheca c'因 scritto il[n]programma degli eventi[n]della scuola.[n][w][e]

[msg MND_E14710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_BOARD_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]C'因 qualche problema? Stai andando[n]all'aula del consiglio studentesco[n][clr 2]al terzo piano[clr 27], giusto?[n][w][e]

[msg MND_COMMON_CHK_BOARD_000]
[s][vp 1 0 0 0 0 0]Sulla bacheca c'因 scritto il[n]programma degli eventi[n]della scuola.[n][w][e]

[msg MND_E12010100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Al secondo piano dovrebbero[n]esserci tutte le aule[n]del secondo anno.[n][w][e]
[s][vp 1 0 0 0 0 0]Per ora, 因 meglio che vada[n]in [clr 2]sala docenti[clr 27]...[n][w][e]

[msg MND_E12310100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Gli studenti all'interno continuano[n]a guardare da questa parte...[n][w][e]

[msg MND_E12720100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Gli studenti all'interno continuano[n]a guardare da questa parte...[n][w][e]

[msg MSG_E13710100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Non vedo nessuno della[n]squadra di pallavolo...[n][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Era la classe D?[n]Diamo un'occhiata anche[n]in classe tua![n][w][e]

[msg MND_E13710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Non vedo studenti con[n]ferite vistose...[n][w][e]

[msg MSG_E13910100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, ho detto l'ingresso[n]principale! Se non ci sbrighiamo[n]se ne andr稲.[n][w][e]

[msg MND_E14130100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Gli studenti all'interno continuano[n]a guardare da questa parte...[n][w][e]

[msg MND_E14710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Devo andare subito in cortile...[n][w][e]

[msg MSG_E23810100_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Cosa ci devi fare nelle altre aule?[n]Andiamo all'aula del consiglio[n]studentesco al [clr 2]terzo piano[clr 27].[n][w][e]

[msg MSG_E65410201_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non serve che tu vada[n]nelle altre aule, ti pare?[n]Inseguiamo la farfalla.[n][w][e]

[msg MND_COMMON_CHK_CLASS_2_0]
[s][vp 1 0 0 0 0 0]Gli studenti all'interno continuano[n]a guardare da questa parte...[n][w][e]

