[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_COSTUME_01]
[s]Spiegazione costume 1[n][w][e]

[msg MSG_COSTUME_02]
[s]Spiegazione costume 2[n][w][e]

[msg MSG_COSTUME_03]
[s]Spiegazione costume 3[n][w][e]

[msg MSG_COSTUME_DEFAULT]
[s]Spiegazione abiti predefiniti[n][w][e]

[msg MND_NG_GOTO2F_1F_000_00]
[s]Dovrei andare a dormire,[n]cos淫 domani sar韻 pronto...[n][w][e]

[msg MSG_NG_GOTO2F_1F_0411_00]
[s]Mi sento pesante...[n]Probabilmente per oggi dovrei[n]andarmene a letto.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0412_00]
[s]Mi sento pesante...[n]Probabilmente per oggi dovrei[n]andarmene a letto.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0413_00]
[s]Oggi sono gi稲 stanco. Dovrei[n]andarmene a dormire presto.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0414_00]
[s]Mi sento sfinito.[n]Dovrei andarmene a dormire presto.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0415_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Sarai stanco, dopo la visita al[n]Metaverso. Andiamocene a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0416_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Domani non devi andare[n]a Shibuya? Fermiamoci qui[n]e andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0417_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Fare lo gnorri non serve.[n]Pulisci la scrivania.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0504_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Dove vai?[n]Domani c'因 la festa, sai?[n][w][e]

[msg MSG_NG_GOTO2F_1F_0505_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Domani non hai di nuovo lezione?[n]Sono stanco, fermiamoci qui[n]e andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0507_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sei stanco dopo il giro[n]nei Memento? Andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0513_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]為 tardi. Andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0514_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non puoi rimandare?[n]Dovresti riposare subito[n]dopo gli esami.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0515_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Domani comincia la nostra indagine[n]su Madarame, ricordi?[n]Fermiamoci qui e andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0516_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sei stanco dopo la visita[n]al Palazzo? Andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0517_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Devi riposare a sufficienza.[n]Domani metteremo in atto[n]il piano, no?[n][w][e]

[msg MSG_NG_GOTO2F_1F_0710_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Esami prima dei fuochi d'artificio,[n]eh? Ti conviene andare a dormire,[n]cos淫 domani potrai lavorare di pi迂.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0716_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Ora che gli esami sono finiti,[n]possiamo farci una bella[n]dormita... Andiamo a letto.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0723_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Domani abbiamo una festa[n]al sushi bar, ricordi?[n]Fermiamoci qui e andiamo a dormire.[n][w][e]

[msg MND_NG_GOTO2F_1F_0724_00]
[s][vp 8 2 65535 0 0 0]Morgana non 因 ancora tornato.[n]Se lo aspetto,[n]forse rientrer稲. Chiss稲...[n][w][e]

[msg MSG_NG_GOTO2F_1F_0821_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Restiamocene buoni[n]e andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0831_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Domani non hai di nuovo lezione?[n]Andiamo a letto presto, cos淫[n]non ti sveglierai tardi.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1003_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]La storia di Yoshizawa e tutto[n]il resto mi hanno distrutto.[n]Andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1011_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Dormiamo per adesso,[n]ricontrolleremo domani lo[n]stato.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1012_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sappiamo quando Haru[n]chiamer稲, quindi per oggi[n]non muoviamoci.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1020_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sicuro che ti vada di[n]uscire? Per oggi[n]restiamo qui.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1026_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Che giornata incredibile...[n]Andiamo a dormire un po'.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1121_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il capo ha ragione, devi[n]permettere al tuo corpo[n]di riposare per oggi.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1123_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Domani continueremo a cercare[n]la parola chiave.[n]Ora dovresti andare a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_1124_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Da domani ci daremo parecchio[n]da fare. Per oggi sarebbe[n]meglio che riposassi.[n][w][e]

[msg MSG_NG_GOTO2F_1F_000_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Andiamo a dormire,[n]per stasera.[n][w][e]

[msg MSG_NG_GOTO2F_1F_DNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Oggi non sei stanco?[n]Andiamo a dormire.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0202_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Maruki 因 finalmente arrivato.[n]Sei mentalmente pronto?[n][w][e]

[sel SEL_NG_GOTO2F_1F_0202_00 top]
[s]Mi serve pi迂 tempo.[e]
[s]Andiamo.[e]

[msg MSG_NG_GOTO2F_1F_0202_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gi稲, non si sa mai cosa pu韻[n]succedere. Meglio stare attenti.[n][w][e]

[msg MSG_NG_GOTO2F_1F_0202_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Qualunque risposta darai a Maruki,[n]io ti appogger韻. So che[n]prenderai la decisione giusta.[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Tu ora non vai a letto[n]fin quando non hai[n]ripulito la scrivania![n][w][e]

[msg MSG_NG_GOTO2F_1F_COMMON_ [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sei stanco? Andiamo a dormire,[n]cos淫 domani saremo pronti.[n][w][e]

[msg MND_NG_GOTO2F_1F_COMMON_]
[s]Dovrei andare a dormire,[n]cos淫 domani sar韻 pronto...[n][w][e]

[msg MSG_LAST_GREETING_MY_Bed [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Andiamo a dormire...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1036 65535 0]No, aspetta! Dobbiamo andare[n]a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_MY_Sof [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non 因 il momento di rilassarsi.[n]Andiamo a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_MY_Clo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Dovremo fare i bagagli dopo[n]aver salutato tutti, perci韻[n]non mettere in disordine.[n][w][e]

[msg MSG_LAST_GREETING_MY_Des [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Le mie ricette hanno aiutato[n]anche te, non 因 cos淫?[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Questa TV era davvero un[n]catorcio, ma ha fatto il suo[n]dovere.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ho bei ricordi di tutte le[n]volte che abbiamo guardato[n]dei DVD insieme.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]E mi sono anche divertito un[n]sacco a guardarti giocare.[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Questa TV era davvero un[n]catorcio, ma ha fatto il suo[n]dovere.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ho bei ricordi di tutte le[n]volte che abbiamo guardato[n]dei DVD insieme.[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Questa TV era davvero un[n]catorcio, ma ha fatto il suo[n]dovere.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Mi sono divertito davvero[n]un mondo a guardarti giocare[n]a quei videogiochi.[n][w][e]

[msg MSG_LAST_GREETING_MY_Tab_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Hai la testa tra le nuvole?[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_MY_She [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Hai raccolto tantissimi ricordini[n]in questa citt稲... Ricordati di[n]prenderli tutti quando parti.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Per ora andiamo dagli altri.[n][w][e]

[msg MSG_LAST_GREETING_MY_She_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Hai finito di pulire, vero?[n]Andiamo dagli altri.[n][w][e]

[msg MSG_LAST_GREETING_Chair_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]La tua salute di ferro 因[n]probabilmente dovuta a tutti[n]gli allenamenti che hai fatto.[n][w][e]

[msg MSG_LAST_GREETING_Chair [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non 因 il momento di allenarsi![n]Andiamo a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_FloorO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Le piante godono di ottima[n]salute grazie a te. Saranno[n]in buone mani con il capo.[n][w][e]

[msg MSG_LAST_GREETING_FloorO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Qualcosa non va? Non andiamo[n]a salutare gli altri?[n][w][e]

[msg MSG_LAST_GREETING_Stove [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ehi, ricordi la prima volta[n]che l'abbiamo acceso?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ne sono successe di cose[n]da allora...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ma 因 grazie a quest'affare[n]che abbiamo superato l'inverno.[n]Una compagna fantastica.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che c'因? Andiamo a[n]salutare gli altri![n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]為 tardissimo...[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_2 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]Sojiro 因 ancora sveglio?[n][w][e]
[s][f 4 10 65535 0 0]Che imbarazzo...[n][w][e]

[sel SEL_BED_MORGANA_NIGHT_10 top]
[s]Va' a casa, o si preoccuper稲.[e]
[s]Puoi dormire sul divano.[e]

[msg MSG_BED_MORGANA_NIGHT_10_3 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aspetta, non dovresti dormire tu[n]sul divano e lasciare che Futaba[n]usi il letto?[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_4 [Futaba]]
[s][bup 0 8 3 65535 0]......[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9195 65535 0][f 4 23 1 65535 4 10 0 0]...Vado a casa.[n][w][e]
[s][f 4 10 65535 0 0]'Notte.[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Finalmente Maruki 因 qui...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non preoccuparti, [fName].[n]Sar韻 al tuo fianco.[n][w][e]

[msg Sofa_CHECK_NG_0409_mes00]
[s]Il divano 因 coperto di polvere.[n][w][e]
[s]Sembra ancora utilizzabile,[n]ma prima dovr韻 pulirlo...[n][w][e]

[msg Sofa_CHECK_NG_0409_mes01]
[s]Il divano 因 coperto di polvere.[n][w][e]
[s]Sembra ancora utilizzabile,[n]ma prima dovr韻 pulirlo...[n][w][e]

[msg Sofa_CHECK_NG_0409_mes02]
[s]Il divano 因 stato pulito. Ora[n]ci si pu韻 sedere di nuovo.[n][w][e]

[msg MSG_DESK_NOTCLEAN]
[s]Su questa scrivania ci[n]sono pile di libri...[n][w][e]

[msg MSG_DESK_NOTCLEAN_MONA_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Quella scrivania potrebbe[n]essere utile...[n][w][e]
[s][f 4 10 65535 0 0]Puoi pulirla anche pi迂 tardi.[n]Per ora, fermiamoci qui[n]e dormiamo un po'.[n][w][e]

[msg MSG_DESK_NOTCLEAN_MONA_0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Quella scrivania potrebbe[n]essere utile...[n][w][e]
[s][f 4 10 65535 0 0]Puoi pulirla anche pi迂 tardi.[n]Per ora, fermiamoci qui[n]e dormiamo un po'.[n][w][e]

[msg MSG_DESK_TUTORIAL_MONA_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Sai cosa possiamo fare?[n]Una bella lezione[n]sugli strumenti d'infiltrazione.[n][w][e]

[msg MSG_ITEM_MAKE_STANDBY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Vuoi fabbricare uno[n]strumento d'infiltrazione[n]per domani? Buona idea.[n][w][e]

[msg MSG_Desk_ActNgNight [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Per oggi lasciamo stare.[n][w][e]

[msg MND_Desk_ActNgNight]
[s]Per oggi dovrei andare a dormire,[n]cos淫 domani sar韻 pronto.[n][w][e]

[msg MSG_Desk_ActNgNight_0716 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]Riesci a fabbricare strumenti per[n]le infiltrazioni? Sei stanco per[n]gli esami. Andiamo a dormire.[n][w][e]

[msg MSG_Desk_ActNgNight_0831 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Domani non hai di nuovo lezione?[n]Andiamo a letto presto, cos淫[n]non ti sveglierai tardi.[n][w][e]

[msg MSG_NG_Desk_ActNgNight_1 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ho cos淫 tante cose in testa, non[n]riesco a concentrarmi... Pensiamo[n]un'altra volta agli strumenti.[n][w][e]

[msg MSG_NG_Desk_ActNgNight_1_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1037 65535 0]Maledizione, i pensieri mi[n]assalgono... Credo proprio che[n]me ne andr韻 a dormire.[n][w][e]

[msg FLOOR_CLEAN_mes00]
[s]Ci sono tanti oggetti lasciati[n]qui. 為 tutto in disordine.[n][w][e]

[msg MSG_FLOOR_NOT_CLEAN_MONA [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Sembra proprio[n]un magazzino...[n][w][e]

[msg MSG_MY_DELI_BOX_DEFAULT_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Che scatolone enorme...[n]Oh, dentro ci sono le tue cose.[n][w][e]

[msg MSG_MY_DELI_BOX_0417_MOR [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Aspetta, chi se ne importa di[n]quello! Pulisci la scrivania, su![n][w][e]

[msg MSG_MY_DELI_BOX_DEFAULT]
[s]為 lo scatolone arrivato[n]da casa.[n][w][e]
[s]Contiene qualche vestito di[n]ricambio e oggetti di[n]uso quotidiano.[n][w][e]

[msg MSG_MY_DELI_BOX_TEST]
[s](TEST)[n]Che faccio?[n][w][e]

[sel SEL_MY_DELI_BOX_TEST top]
[s]Prender韻 un nuovo costume.[e]
[s]Mi cambio d'abito.[e]

[msg MSG_GET_COSTUME_TEST]
[s](TEST)[n]Che costume dovrei prendere?[n][w][e]

[sel SEL_GET_COSTUME_TEST top]
[s]Uniforme Yasogami[e]
[s]Uniforme Gekkoukan[e]
[s]Uniforme Seven Sisters[e]
[s]Uniforme St. Hermelin[e]
[s]Uniforme Karukozaka[e]
[s]Costume Catherine[e]
[s]Uniforme da studente[e]
[s]Costumi da bagno[e]
[s]Costumi da Maid e Butler[e]
[s]Costumi natalizi[e]

[msg MSG_ALREADY_GET_COSTUME_]
[s]Quello gi稲 ce l'ho.[n][w][e]

[sel SEL_MY_DELI_BOX top]
[s]Cambio di vestiti 1[e]

[msg MSG_MY_DELI_BOX_COSTUME_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Reazione al cambio di 1[n][w][e]

[msg MSG_MY_DELI_BOX_COSTUME__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Reazione al cambio di 2[n][w][e]

[msg MSG_MY_DELI_BOX_COSTUME__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Reazione al cambio di 3[n][w][e]

[msg MSG_MY_DELI_BOX_COSTUME__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Abbigliamento predefinito[n][w][e]

[msg SYSTEM_GET_COSTUME_P4]
[s]Ho ottenuto l'uniforme della Yasogami.[n][w][e]

[msg SYSTEM_GET_COSTUME_P3]
[s]Ho ottenuto l'uniforme della Gekkoukan.[n][w][e]

[msg SYSTEM_GET_COSTUME_P2]
[s]Ho ottenuto l'uniforme[n]della Seven Sisters.[n][w][e]

[msg SYSTEM_GET_COSTUME_IBUNR]
[s]Ho ottenuto l'uniforme[n]della St. Hermelin.[n][w][e]

[msg SYSTEM_GET_COSTUME_IF]
[s]Ho ottenuto l'uniforme[n]della Karukozaka.[n][w][e]

[msg SYSTEM_GET_COSTUME_P4D]
[s]Ho ottenuto il costume P4D.[n][w][e]

[msg SYSTEM_GET_COSTUME_P4U]
[s]Ho ottenuto il costume P4U.[n][w][e]

[msg SYSTEM_GET_COSTUME_MEGAM]
[s]Ho ottenuto il[n]costume Shin Megami Tensei.[n][w][e]

[msg SYSTEM_GET_COSTUME_RAIDO]
[s]Ho ottenuto il[n]costume Raido Kuzunoha.[n][w][e]

[msg SYSTEM_GET_COSTUME_CATHE]
[s]Ho ottenuto gli abiti[n]di un adulto smarrito.[n][w][e]

[msg SYSTEM_GET_COSTUME_P5]
[s]Ho ottenuto abiti personali,[n]uniformi scolastiche, tute e pigiama[n]per la vita da studente.[n][w][e]

[msg SYSTEM_GET_COSTUME_SWIM]
[s]Ho ottenuto dei costumi da bagno.[n][w][e]

[msg SYSTEM_GET_COSTUME_BUTLE]
[s]Hai ottenuto alcuni[n]costumi da Maid e Butler.[n][w][e]

[msg SYSTEM_GET_COSTUME_XMAS]
[s]Ho ottenuto dei costumi natalizi.[n][w][e]

[msg SYSTEM_GET_ITEM_NG]
[s]Hai raggiunto il limite massimo di[n]trasporto per quest'oggetto e[n]non potrai raccoglierne altri.[n][w][e]

[msg SYSTEM_GET_PERSONA_ORPHE]
[s]Ho ottenuto Orfeo.[n][w][e]

[msg SYSTEM_GET_PERSONA_IZANA]
[s]Ho ottenuto Izanagi.[n][w][e]

[msg SYSTEM_GET_PERSONA_THANA]
[s]Ho ottenuto Thanatos.[n][w][e]

[msg SYSTEM_GET_PERSONA_MAGAT]
[s]Ho ottenuto Magatsu-Izanagi.[n][w][e]

[msg SYSTEM_GET_PERSONA_KAGUY]
[s]Ho ottenuto Kaguya.[n][w][e]

[msg SYSTEM_GET_PERSONA_ARIAD]
[s]Ho ottenuto Arianna.[n][w][e]

[msg SYSTEM_GET_PERSONA_ASTER]
[s]Ho ottenuto Asterius.[n][w][e]

[msg SYSTEM_GET_PERSONA_TUKIY]
[s]Ho ottenuto Tsukiyomi.[n][w][e]

[msg SYSTEM_GET_PERSONA_MESSI]
[s]Ho ottenuto Messia.[n][w][e]

[msg SYSTEM_GET_ITEM_START01]
[s]Ho ottenuto una serie dioggetti curativi.[n][w][e]

[msg SYSTEM_GET_ITEM_START02]
[s]Ho ottenuto una serie dicarte abilit稲.[n][w][e]

[msg MSG_WASHBOX_NOTOPEN]
[s]Il cesto della biancheria[n]sta prendendo polvere...[n][w][e]
[s]Giusto, c'era una lavanderia[n]automatica al bagno[n]pubblico qui vicino...[n][w][e]

[msg MSG_WASHBOX_NOTOPEN_MONA [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ugh, questo cesto della biancheria[n]因 in uno stato pietoso.[n][w][e]
[s][f 4 10 65535 0 0]Ora che ci penso, non c'era una[n]lavanderia automatica al bagno[n]pubblico qui vicino?[n][w][e]

[msg MSG_SHELF_NOTCLEAN]
[s]Alcuni libri sono stati[n]riposti alla rinfusa[n]su questo scaffale...[n][w][e]

[msg MSG_SHELF_NOTCLEAN_MONA [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]為 proprio in disordine. Ci sono[n]perfino dei libri che sporgono...[n][w][e]

[msg MSG_Shelf_NotCleanThink_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Bisogna proprio pulire un po',[n]ma dovremo farlo[n]un'altra volta.[n][w][e]

[msg MSG_TABLE_CleanEnd_Notin [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questi scaffali sono[n]molto belli e spaziosi...[n][w][e]
[s][f 4 10 65535 0 0]Ma sarebbe molto meglio[n]se ci mettessi sopra qualcosa...[n][w][e]

[msg MND_TABLE_CleanEnd_Notin]
[s]Gli scaffali sono vuoti...[n][w][e]

[msg MSG_StopAct_CleanEnd_100 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Non dobbiamo pulire gli scaffali[n]adesso, vero? Meglio riposare.[n][w][e]

[msg MSG_TABLE_NOTCLEAN]
[s]Che pila enorme[n]di riviste...[n][w][e]

[msg MSG_CatBed_1ST [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0]Mmm, visto che sei stato[n]gentile a comprarmelo,[n]inizier韻 a dormire qui.[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Come? Dove ho dormito[n]finora? A volte sdraiato[n]su di te.[n][w][e]

[msg MSG_CatBed_Common [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Su, non arrabbiarti.[n][w][e]

[msg MND_CatBed]
[s]為 un letto che ho[n]comprato per Morgana.[n][w][e]

[msg MND_FloorObj_Plant_FIRST]
[s]Questa pianta ornamentale[n]sembra piuttosto malmessa.[n][w][e]

[msg MONA_FloorObj_Plant_FIRS [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Non 因 bella come pensavamo.[n]Sembra un po' smorta...[n][w][e]

[msg MONA_FloorObj_Plant_NoIt [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Non vendono concime[n]o qualcos'altro che le[n]restituisca un po' di colore?[n][w][e]

[msg MND_FloorObj_Plant_NoIte]
[s]Forse, con un po' di concime[n]questa pianta si riprenderebbe.[n][w][e]

[msg MONA_FloorObj_Plant_NoIt_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Non hai un po' di concime?[n]Aveva appena cominciato[n]a riprendersi.[n][w][e]

[msg MND_FloorObj_Plant_NoIte_2]
[s]Non ho concime...[n][w][e]

[msg MONA_FloorObj_Plant_NG [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Per ora sembra in salute.[n][w][e]

[msg MND_FloorObj_Plant_NG]
[s]Per adesso questa pianta[n]sembra in salute.[n][w][e]

[msg MONA_FloorObj_Plant_UseI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Adesso che ci penso, hai[n]comprato del concime, no?[n]Perch姻 non provi a usarlo?[n][w][e]

[msg MND_FloorObj_Plant_UseIt]
[s]Giusto, ho qualcosa[n]che potrei usare...[n][w][e]

[msg MONA_FloorObj_Plant_UseI_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Non sarebbe ora di darle[n]un po' di concime?[n][w][e]

[msg MND_FloorObj_Plant_UseIt_2]
[s]Sembra che dovrei darle[n]un po' pi迂 di concime.[n][w][e]

[msg MONA_FloorObj_Plant_UseI_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]為 roba da poco, ma sempre meglio[n]che non darle niente...[n][w][e]

[msg MONA_FloorObj_Plant_UseI_4 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]為 concime mediamente costoso.[n]Dovrebbe ridare un po'[n]di vita alla pianta![n][w][e]

[msg MONA_FloorObj_Plant_UseI_5 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Vuoi darle quello?!?[n]Devi avere molto a cuore[n]questa pianta![n][w][e]

[msg MND_FloorObj_Plant_UseIt_3]
[s]Credo che questa pianta[n]stia un po' meglio.[n][w][e]

[msg MONA_FloorObj_Plant_UseI_6 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1181 65535 0]Cos淫 dovrebbe bastare per un po'![n][w][e]

[msg MND_FloorObj_Plant_UseIt_4]
[s]Cos淫 dovrebbe bastare[n]per un po'.[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ugh, accidenti...[n]Non 因 facile rilassarsi[n]in questa stanza...[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Mi sorprende che tu riesca[n]a viverci.[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Quando avremo trovato il modo[n]di procurarci delle armi,[n]dovremmo pulire questa stanza...[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_4 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Per ora lascia stare quella parte.[n]Prima dobbiamo pulire la scrivania.[n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_5 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]No, non l淫. La scrivania![n][w][e]

[msg MSG_SUGGEST_CLEAN_MONA_0_6 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non quella scrivania.[n]Quella in fondo.[n][w][e]

[msg MSG_SUGGEST_CLEAN_TABLE_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Quella scrivania. Su, datti[n]da fare e puliscila.[n][w][e]

[sel SEL_SUGGEST_CLEAN_TABLE_ top]
[s]Puliamo.[e]
[s]Non mi va.[e]

[msg MSG_SUGGEST_CLEAN_TABLE__2 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Non dire cos淫. Dai,[n]ti insegner韻 come fabbricare[n]gli strumenti d'infiltrazione...[n][w][e]

[msg MSG_SUGGEST_CLEAN_TABLE__3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Ottimo, adesso puoi metterti a[n]costruire ogni volta che vuoi![n][w][e]

[msg TUTORIAL_TOOL]
[s]Ora puoi creare strumenti d'infiltrazione[n]su questo tavolo da lavoro.[n][w][e]

[msg MSG_Shelf_NotCleanThink [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ti va di pulire?[n][w][e]

[msg MSG_Shelf_Clean_Now [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1162 65535 0]Politica, legge, filosofia... Sembrano[n]libri abbastanza impegnativi.[n][w][e]
[s][f 4 10 65535 0 0]Oh! Forse questo potresti[n]riuscire a leggerlo![n][w][e]

[msg MSG_Shelf_Clean_End [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Chiss稲 perch姻 una cosa del genere 因[n]in mezzo a tutti quei libri complicati...[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Beh, direi che non ha importanza.[n][w][e]

[msg MSG_Shelf_Clean_GetBook0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1162 65535 0]Politica, legge, filosofia...[n]Sembrano libri[n]abbastanza impegnativi.[n][w][e]
[s][f 4 10 65535 0 0]Prendine almeno uno. Un po'[n]d'impegno fa meraviglie.[n][w][e]

[msg MSG_Shelf_Clean_GetBook0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 10 65535 0 0]Prendi anche questo. Dovrebbe[n]essere una lettura leggera, no?[n][w][e]

[msg MSG_Shelf_Clean_Continue [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Questa 因 un'ottima opportunit稲.[n][w][e]
[s][f 4 10 65535 0 0]Anche il pavimento 因 messo male.[n]Gi稲 che ci siamo,[n]puliamo a fondo![n][w][e]

[msg MND_Shelf_NotCleanThink]
[s]Questi scaffali sono talmente[n]pieni di libri che[n]alcuni sporgono.[n][w][e]

[msg MSG_Clean_DayEnd_1 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Adesso questa stanza 因[n]un po' pi迂 accogliente.[n][w][e]
[s][f 4 10 65535 0 0]Come ho previsto abbiamo trovato[n]un tesoro, ma...[n][w][e]

[msg MSG_GetTv [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]為 una TV CRT. Non potremo[n]guardare nessuna trasmissione[n]senza un decoder.[n][w][e]
[s][f 4 10 65535 0 0]Ma sarebbe uno spreco non[n]sfruttarla. Conosci un posto che[n]vende elettrodomestici a poco?[n][w][e]

[msg MSG_MyRoomClean_End [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Comunque, bel lavoro.[n]Facciamo una pausa.[n][w][e]

[msg MSG_MyRoomClean_End_YORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Comunque, bel lavoro.[n]Meglio riposarci finch姻 possiamo.[n][w][e]

[msg MSG_Clean_DayEnd_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Adesso questa stanza 因[n]un po' pi迂 accogliente.[n][w][e]
[s][f 4 10 65535 0 0]Ora puoi riorganizzarla[n]come preferisci![n][w][e]
[s][f 4 10 65535 0 0]Non sei stanco?[n]D'accordo, facciamo una pausa.[n][w][e]

[sel SEL_Clean top]
[s]Puliamo.[e]
[s]Non mi va.[e]

[msg MSG_Clean_NG [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Non facciamo pulizie[n]per ora.[n][w][e]

[msg MIND_Clean_NG]
[s]Direi di non fare[n]pulizie per ora.[n][w][e]

[msg MSG_Floor_NotClean_Think [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ti va di pulire?[n][w][e]

[msg MSG_Floor_NotClean_Think_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Bisogna proprio pulire un po',[n]ma dovremo farlo[n]un'altra volta.[n][w][e]

[msg MSG_Floor_Clean_Now [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oh, guarda! Quella pianta[n]因 ancora viva. Possiamo usarla[n]come oggetto ornamentale.[n][w][e]

[msg MSG_Floor_Clean_End [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Anche la stanza pi迂 scialba[n]pu韻 essere ravvivata da[n]un po' di verde...[n][w][e]
[s][f 4 10 65535 0 0]Prendiamoci cura di questa pianta,[n]cos淫 non appassir稲.[n][w][e]

[msg MSG_Floor_Clean_Continue [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Questa 因 un'ottima opportunit稲.[n][w][e]
[s][f 4 10 65535 0 0]Gli scaffali sono un po' in[n]disordine. Gi稲 che ci siamo,[n]puliamo a fondo![n][w][e]

[msg MND_Floor_NotClean_Think]
[s]Qui ci sono tanti oggetti di[n]uso quotidiano inutilizzati. Sono[n]messi alla rinfusa.[n][w][e]

[msg MND_Stove01]
[s]為 ancora caldo.[n][w][e]
[s]Sembra esserci ancora[n]combustibile a sufficienza.[n][w][e]

[msg MND_Stove02]
[s]為 ancora caldo.[n][w][e]
[s]Sembra esserci meno combustibile.[n][w][e]

[msg MND_Stove03]
[s]為 ancora caldo.[n][w][e]
[s]Pare che qualcuno abbia[n]gi稲 aggiunto altro combustibile.[n][w][e]

[msg MND_StopAct_Common_0724]
[s]Morgana non 因 ancora tornato...[n][w][e]

[msg MND_StopAct_Common_0915]
[s]Chi c'era insieme a Morgana?[n][w][e]

[msg MND_StopAct_Common_0916]
[s]Se andassi nei Memento[n]forse incontrerei quei due.[n][w][e]

[msg MSG_StopAct_Common_0917 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Questo posto 因 scialbo[n]come sempre... Ma lo trovo[n]abbastanza accogliente.[n][w][e]

[msg MSG_StopAct_Common_1026_ [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Futaba sembrava triste. In qualit稲[n]di leader sai cosa devi fare, vero?[n][w][e]

[msg MSG_StopAct_Common_1026 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Futaba e il capo se la caveranno.[n]Non preoccuparti per loro.[n][w][e]

[msg MSG_StopAct_Training_100 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Quel Palazzo mi ha distrutto...[n]Non alleniamoci oggi...[n][w][e]

[msg MSG_StopAct_Common_1121 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Eheh... Anche se 因 la solita[n]vecchia mansarda, 因 un[n]luogo importante per te, eh?[n][w][e]

[msg MSG_StopAct_Common_0202 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Non si pu韻 pi迂 tornare indietro.[n]Diamogli una lezione![n][w][e]

[msg MSG_StopAct_Common_0109 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Domani iniziano le lezioni, giusto?[n]Dovresti andare a letto presto.[n][w][e]

[msg MSG_StopAct_Common_0110 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Aspetta, non dormiresti abbastanza![n]Per oggi lasciamo stare.[n][w][e]

[msg MSG_StopAct_Common_0111 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]So che sei stressato, ma non[n]fare tardi. C'因 sempre domani.[n][w][e]

[msg MSG_StopAct_Common_0112 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Il Palazzo di oggi era strano...[n]Sono sfinito. Andiamo a riposare.[n][w][e]

[msg MSG_StopAct_Common_1003 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oggi non mi va di fare tardi.[n]Fermiamoci qui.[n][w][e]

[msg MSG_StopAct_Stair_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]La verit稲 su Madarame, eh...?[n]Chiediamo a Yusuke domani.[n][w][e]
[s]Sarai stanco dopo tutto quello[n]che 因 successo oggi. Meglio[n]chiuderla qui e riposare.[n][w][e]

[msg MSG_StopAct_Stair_0611 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53115 65535 0]Si sta facendo piuttosto tardi.[n]Smettiamo e andiamo a dormire.[n][w][e]

[msg MND_StopAct_Stair_0724]
[s]Io e Morgana potremmo[n]incontrarci...[n][w][e]
[s]Dovrei aspettare fino a domani.[n][w][e]

[msg MSG_StopAct_Stair_0906 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Domani parti per la gita[n]scolastica, vero? Sbrigati[n]ad andare a letto.[n][w][e]

[msg MSG_StopAct_Stair_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi... Sei appena tornato dalle[n]Hawaii, ricorda. Per oggi[n]stattene buono.[n][w][e]

[msg MND_StopAct_Stair_0914]
[s]Dovrei andare a dormire,[n]cos淫 domani sar韻 pronto...[n][w][e]

[msg MND_StopAct_Stair_0915]
[s]Chi sar稲 la Splendida Ladra?[n]Dovrei andare a letto presto[n]e indagare domani.[n][w][e]

[msg MND_StopAct_Stair_0916]
[s]Stasera dovrei andare a letto[n]per prepararmi all'imboscata[n]di domani nei Memento.[n][w][e]

[msg MSG_StopAct_Stair_0917 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Che giornata stancante...[n]Si sta facendo tardi,[n]andiamo a dormire.[n][w][e]

[msg MSG_StopAct_Stair_1026_F [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Futaba sembra depressa. Dovresti[n]andare a parlarle.[n][w][e]

[msg MSG_StopAct_Stair_1026 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hai un viso davvero stanco.[n]Su, vai a letto.[n][w][e]

[msg MSG_StopAct_Stair_1121 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Capisco che tu voglia uscire[n]dopo essere stato rinchiuso...[n][w][e]
[s][f 4 10 65535 0 0]Ma da domani avrai molto da fare.[n]Oggi dovresti prendertela comoda[n]e riposare.[n][w][e]

[msg MSG_StopAct_Stair_0109 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sono esausto, mentalmente[n]e fisicamente. Oggi[n]prendiamocela comoda.[n][w][e]

[msg MSG_StopAct_Stair_0110 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Domani dovremo affrontare una[n]discussione importante. So che[n]sei nervoso, ma cerca di riposarti.[n][w][e]

[msg MSG_StopAct_Stair_0111 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]So che vuoi farti trovare pronto, ma[n]risparmiare le energie 因 altrettanto[n]importante per la nostra strategia.[n][w][e]

[msg MSG_StopAct_Stair_0112 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aspetta, sarai esausto dopo[n]tutto quello che 因 successo.[n]Cerca di riposare per oggi...[n][w][e]

[msg MSG_StopAct_Desk_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Gi稲 ti prepari per l'infiltrazione[n]nel Palazzo? Ammiro il[n]tuo entusiasmo...[n][w][e]
[s][f 4 10 65535 0 0]Ma dovresti smettere. Non sei[n]stanco? Non vorrei ti facessi male.[n][w][e]

[msg MSG_StopAct_Desk_0611 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Per oggi lasciamo stare.[n]Cos淫 pieno non riuscirai[n]a concentrarti.[n][w][e]

[msg MND_StopAct_Desk_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Sembri assonnato...[n][w][e]
[s][f 4 10 65535 0 0]E se ti facessi male?[n]Dovresti smetterla per oggi.[n][w][e]

[msg MND_StopAct_Desk_0914]
[s]Un gatto ha lasciato le sue[n]impronte nella polvere...[n][w][e]
[s]Sono in pensiero per Morgana...[n][w][e]

[msg MND_StopAct_Desk_0915]
[s]Morgana si occupava sempre di me,[n]ma non 因 pi迂 qui...[n][w][e]

[msg MND_StopAct_Desk_0916]
[s]Saranno davvero Morgana e la[n]sua amica a risolvere le[n]richieste nei Memento...?[n][w][e]

[msg MSG_StopAct_Desk_0917 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1048 65535 0]Ti metter韻 di nuovo sotto per[n]insegnarti a fabbricare gli[n]strumenti d'infiltrazione! Occhio![n][w][e]

[msg MND_StopAct_Desk_0202 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, c'因 Maruki di sotto! Non 因[n]il momento di fabbricare strumenti![n][w][e]

[msg MSG_StopAct_Table_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53116 65535 0]Domani, dopo la scuola, a Shibuya...[n]Non dormire fino a tardi solo[n]perch姻 sei stato al Palazzo.[n][w][e]

[msg MSG_StopAct_Table_0611 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Qual 因 il problema? Stai ripensando[n]alla festa dell'hot pot?[n][w][e]

[msg MSG_StopAct_Table_0716 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hai studiato un sacco per gli esami[n]negli ultimi giorni. Non fare tardi[n]e cerca di riposarti un po', OK?[n][w][e]

[msg MSG_StopAct_Table_0906 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Adesso puoi anche fabbricare[n]strumenti per le infiltrazioni[n]da solo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1037 65535 0]...Non 因 niente. Vai a dormire.[n][w][e]

[msg MSG_StopAct_Table_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Se dovessi...[n][w][e]
[s][f 4 10 65535 0 0]...No, niente.[n][w][e]

[msg MND_StopAct_Table_0914]
[s]Sono i segni lasciati da artigli[n]sulle zampe del tavolo...[n][w][e]
[s]Sono in pensiero per Morgana...[n][w][e]

[msg MSG_StopAct_Table_0917 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 53111 65535 0]Eheheh, direi che sono tornato.[n][w][e]

[msg MSG_StopAct_Table_1011 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1047 65535 0]Povera Haru... Vedere suo padre[n]in quello stato... Com'因 potuta[n]accadere una cosa cos淫 orribile?[n][w][e]

[msg MSG_StopAct_Table_0202 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Cosa c'因? Hai qualcosa in mente?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Ehi, non ti spaventare![n]Resta saldo![n][w][e]

[msg MSG_StopAct_Gomi_0516 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Possiamo pensarci domani.[n]Riordineremo un'altra volta.[n][w][e]

[msg MSG_StopAct_GomiClean_05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Sapevo che Lady Ann avrebbe[n]pensato a tutto...[n][w][e]

[msg MSG_StopAct_Gomi_0611 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Vuoi metterti a pulire ora?[n]Guarda che Yusuke 因 gi稲 qui![n]Non devi farlo per forza oggi.[n][w][e]

[msg MSG_StopAct_GomiClean_06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1031 65535 0]Meno male che abbiamo ripulito.[n]Sarebbe stato scortese accogliere[n]Lady Ann in quello schifo, eh?[n][w][e]

[msg MSG_StopAct_GomiClean_07 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Hai appena finito gli esami.[n]Non spremerti troppo[n]le meningi, oggi.[n][w][e]

[msg MSG_StopAct_Gomi_0716 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Ripuliamo un'altra volta. Ora che[n]gli esami sono finiti, possiamo[n]andare a letto presto, per favore?[n][w][e]

[msg MSG_StopAct_GomiClean_09 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Andiamo a dormire. Per ora possiamo[n]lasciar stare i tuoi cimeli...[n][w][e]

[msg MSG_StopAct_Gomi_0906 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Non credo che tu debba[n]preoccuparti di ripulire adesso,[n]visto che domani andrai in gita.[n][w][e]

[msg MSG_StopAct_Gomi_0912 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Perch姻 ti ci vuoi mettere adesso[n]d'improvviso? Ci penserai domani.[n][w][e]

[msg MSG_StopAct_GomiClean_09_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]La stanza era silenziosissima[n]mentre non c'eri...[n][w][e]
[s][f 4 10 65535 0 0]Non che abbia molta importanza...[n][w][e]

[msg MND_StopAct_Gomi_0914]
[s]Morgana mi ha detto di pulire...[n][w][e]
[s]Sono in pensiero per Morgana...[n][w][e]

[msg MND_StopAct_GomiClean_09]
[s]Che silenzio qui...[n][w][e]
[s]Sono in pensiero per Morgana...[n][w][e]

[msg MND_StopAct_GomiClean_09_2]
[s]Come si saranno incontrati[n]Morgana e la Splendida Ladra?[n][w][e]

[msg MND_StopAct_GomiClean_09_3]
[s]Come faccio a sistemare le cose[n]con Morgana?[n][w][e]

[msg MSG_StopAct_GomiClean_10 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Dovresti pulire, ma prima[n]riposa un po'.[n][w][e]

[msg MSG_StopAct_GomiClean_10_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Davvero vuoi riordinare adesso[n]lo scaffale? Io non riesco nemmeno[n]a riordinare i miei sentimenti...[n][w][e]

[msg MSG_StopAct_Gomi_1011 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ce l'abbiamo fatta... come sempre,[n]vero? Dovremmo... essere a posto...[n][w][e]

[msg MSG_StopAct_GomiClean_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ehi, [fName], torniamocene di sotto[n]appena avrai raccolto le idee.[n][w][e]

[msg MSG_StopAct_Training_051 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ehi, sembri esausto. Oggi non devi[n]allenarti per forza.[n][w][e]

[msg MSG_StopAct_Training_061 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0]Vuoi davvero allenarti a stomaco[n]pieno?!? Ti sentirai male![n][w][e]

[msg MSG_StopAct_Training_071 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Capisco che ti vuoi sfogare[n]dopo aver finito gli esami, ma[n]non sei stanco? Vai a dormire, dai.[n][w][e]

[msg MSG_StopAct_Training_090 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Ti conviene evitare di stancarti.[n]Da domani, ci attende un[n]sacco di lavoro.[n][w][e]

[msg MSG_StopAct_Training_091 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Non hai ancora smaltito il jet lag.[n]Oggi possiamo anche non farlo.[n][w][e]

[msg MND_StopAct_Training_091]
[s]La pioggia 因 insolitamente[n]rumorosa...[n][w][e]
[s]Sono in pensiero per Morgana...[n][w][e]

[msg MND_StopAct_Training_091_2]
[s]Sono troppo preoccupato per Morgana[n]per riuscire ad allenarmi...[n][w][e]

[msg MSG_StopAct_Training_091_2]
[s]Sono in pensiero per Morgana.[n]Non penso di potermi concentrare[n]a sufficienza sull'allenamento...[n][w][e]

[msg MSG_StopAct_Training_091_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oggi sono stanco. Ci alleneremo[n]un'altra volta.[n][w][e]

[msg MSG_StopAct_Training_101 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Non ho alcuna voglia di muovermi...[n]Cos'因 successo... di preciso...?[n][w][e]

[msg MSG_StopAct_Training_020 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sar韻 sempre con te. Pensa[n]bene alla risposta, OK?[n][w][e]

[msg MND_E10530101_NG_GOTO_1F]
[s][vp 1 0 0 0 0 0]Domani dovr韻 alzarmi presto...[n]Oggi dovrei riposare per bene.[n][w][e]

[msg fev0409_10_STEP_mes01]
[s][vp 1 0 0 0 0 0]...Dovrei fare un po'[n]di pulizia.[n][w][e]

[msg fev0409_NG_DOWN]
[s][vp 1 0 0 0 0 0]Dovrei chiuderla qui[n]e andarmene a letto...[n][w][e]

[msg fev1030_NG_DOWN]
[s][vp 1 0 0 0 0 0]Dovrei chiuderla qui[n]e andarmene a letto...[n][w][e]

[msg fev1121_NG_DOWN]
[s][vp 1 0 0 0 0 0]Dovrei chiuderla qui[n]e andarmene a letto...[n][w][e]

[msg BED_CHECK_mes00]
[s][vp 1 0 0 0 0 0]Qui c'因 un materasso.[n][w][e]
[s][vp 1 0 0 0 0 0]Questo sarebbe il mio letto...?[n][w][e]

[msg BED_CHECK_mes01]
[s][vp 1 0 0 0 0 0]In quest'angolo[n]c'因 un letto.[n][w][e]

[msg BED_CHECK_0409_END_mes01]
[s][vp 1 0 0 0 0 0]Da oggi, questa 因 la mia stanza...[n][w][e]

[sel BED_CHECK_0409_EV_SEL top]
[s]Cambiati e vai a letto[e]
[s]Non dormire ancora[e]

[msg fev0410_04_mes01]
[s][vp 1 0 0 0 0 0]Non 因 il mio cellulare[n]a squillare...[n][w][e]

[msg fev0410_04_mes02]
[s][vp 1 0 0 0 0 0]Proviene dal piano di sotto.[n][w][e]

[msg MND_E10530101_NG_BED]
[s][vp 1 0 0 0 0 0]Il telefono di sotto squilla.[n]Dovrei sbrigarmi a rispondere...[n][w][e]

[msg BED_CHECK_0410_END_mes01]
[s][vp 1 0 0 0 0 0]C'因 qualcos'altro che[n]devo fare...?[n][w][e]

[sel BED_CHECK_0410_EV_SEL top]
[s]Dormi[e]
[s]Stai sveglio[e]

[msg MND_E10920100_NG_BED]
[s][vp 1 0 0 0 0 0]Non credo di avere[n]tempo per un sonnellino...[n][w][e]

[msg MND_E12710100_NG_BED]
[s][vp 1 0 0 0 0 0]Non credo di avere[n]tempo per un sonnellino...[n][w][e]

[msg MSG_E22810100_NG_BED [Morgana]]
[s][bup 0 3 10 65535 0][f 4 10 65535 0 0][vp 8 2 1 1111 65535 0]Forza, 因 presto per crollare[n]a letto! Chiediamo prima al capo.[n][w][e]

[msg MSG_E22810100_NG_BED_2 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ho cercato anche l淫, ma non[n]ho trovato nessuna pentola.[n]Che ha detto il capo?[n][w][e]

[msg MND_E24410100_NG_BED]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg BED_CHECK_1030_END_mes01 [Futaba]]
[s][f 4 23 1 850 3 10 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]為 tardissimo...[n][w][e]

[sel BED_CHECK_1030_EV_SEL_1 top]
[s]Dormi[e]
[s]Stai sveglio[e]

[msg MSG_356_101_01_FUTABA_EN [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]Sojiro 因 ancora sveglio?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Che imbarazzo...[n][w][e]

[sel BED_CHECK_1030_EV_SEL_2 top]
[s]Va' a casa, o si preoccuper稲.[e]
[s]Puoi dormire sul divano.[e]

[msg MSG_356_101_01_FUTABA_EN_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Aspetta, non dovresti dormire tu[n]sul divano e lasciare che Futaba[n]usi il letto?[n][w][e]

[msg MSG_356_101_01_FUTABA_EN_3 [Futaba]]
[s][bup 0 8 3 65535 0][vp 8 2 65535 0 0 0]......[n][w][e]

[msg MSG_356_101_01_FUTABA_EN_4 [Futaba]]
[s][f 4 23 1 850 4 10 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9195 65535 0]...Vado a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Buonanotte.[n][w][e]

[msg BED_CHECK_1121_END_mes01]
[s][vp 1 0 0 0 0 0]Dovrei andare a letto...[n][w][e]

[sel BED_CHECK_1121_EV_SEL top]
[s]Dormi[e]
[s]Stai sveglio[e]

[msg MSG_399_101_01_MORU_END [Morgana]]
[s][f 4 23 1 850 0 0 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oggi concediamoci[n]riposo a volont稲...[n][w][e]

[msg MND_COMMON_NG_BED]
[s][vp 1 0 0 0 0 0]Adesso non ho tempo di[n]mettermi a dormire...[n][w][e]

[msg MND_E10510100_CHK_Closet]
[s][vp 1 0 0 0 0 0]為 lo scatolone arrivato[n]da casa.[n][w][e]
[s][vp 1 0 0 0 0 0]Contiene qualche vestito di[n]ricambio e oggetti di[n]uso quotidiano.[n][w][e]

[msg MND_E10530100_CHK_Closet]
[s][vp 1 0 0 0 0 0]為 lo scatolone arrivato[n]da casa.[n][w][e]
[s][vp 1 0 0 0 0 0]Contiene qualche vestito di[n]ricambio e oggetti di[n]uso quotidiano.[n][w][e]

[msg MND_E10920100_CHK_Closet]
[s][vp 1 0 0 0 0 0]為 lo scatolone arrivato[n]da casa.[n][w][e]
[s][vp 1 0 0 0 0 0]Contiene qualche vestito di[n]ricambio e oggetti di[n]uso quotidiano.[n][w][e]

[msg MND_E12710100_CHK_Closet]
[s][vp 1 0 0 0 0 0]為 lo scatolone arrivato[n]da casa.[n][w][e]
[s][vp 1 0 0 0 0 0]Contiene qualche vestito di[n]ricambio e oggetti di[n]uso quotidiano.[n][w][e]

[msg MSG_E22810100_NG_Closet [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Mmm? Non dovevi parlare col capo[n]e farti prestare una pentola?[n][w][e]

[msg MSG_E22810100_NG_Closet2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Hai parlato con il capo, vero?[n]Non sei riuscito a farti[n]prestare una pentola?[n][w][e]

[msg MSG_E22810100_NG_ROOMOBJ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mmm? Non dovevi parlare col capo[n]e farti prestare una pentola?[n][w][e]

[msg MSG_E22810100_NG_ROOMOBJ_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hai parlato con il capo, vero?[n]Non sei riuscito a farti[n]prestare una pentola?[n][w][e]

[msg MND_E24410100_CHK_Closet]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_CHK_Closet]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg BENCH_CLEAN_LONELY_mes00]
[s][vp 1 0 0 0 0 0]為 una scrivania con[n]dei libri impilati sopra.[n][w][e]
[s][vp 1 0 0 0 0 0]Non si pu韻 usare[n]in questo stato...[n][w][e]

[msg BENCH_CLEAN_LONELY_mes01]
[s][vp 1 0 0 0 0 0]Non si pu韻 usare[n]in questo stato...[n][w][e]

[msg BENCH_CLEAN_LONELY_mes02]
[s][vp 1 0 0 0 0 0]Se togliessi i libri, forse[n]potrei usarla come scrivania...[n][w][e]

[msg MND_E10530100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Ci sono parecchi libri[n]impilati sulla scrivania. Non posso[n]usarla finch姻 因 in questo stato.[n][w][e]

[msg MND_E10920100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Ci sono parecchi libri[n]impilati sulla scrivania. Non posso[n]usarla finch姻 因 in questo stato.[n][w][e]

[msg MND_E12710100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Ci sono parecchi libri[n]impilati sulla scrivania. Non posso[n]usarla finch姻 因 in questo stato.[n][w][e]

[msg MSG_E22810100_CHK_Desk [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Ehi, non vorrai mica metterti[n]a forgiare una pentola?!?[n]Vai a chiederla al capo![n][w][e]

[msg MSG_E22810100_CHK_Desk2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Non vedo l'ora di mangiare[n]l'hot pot con tutti quanti! Chiss稲[n]cosa ci sar稲 dentro.[n][w][e]

[msg MND_E24410100_CHK_Desk]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_CHK_Desk]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg TABLE_CLEAN_mes00]
[s][vp 1 0 0 0 0 0]Un tavolo coperto di polvere.[n][w][e]
[s][vp 1 0 0 0 0 0]Passandoci il dito, ci lascerei[n]sopra una linea ben visibile...[n][w][e]

[msg TABLE_CLEAN_mes01]
[s][vp 1 0 0 0 0 0]Non vorrei proprio mangiare[n]su questo tavolo...[n][w][e]

[msg TABLE_CLEAN_mes02]
[s][vp 1 0 0 0 0 0]Ora che questo tavolo[n]因 pulito, chiss稲 come[n]potrei usarlo...[n][w][e]

[msg MND_E10530100_CHK_Table]
[s][vp 1 0 0 0 0 0]Ora il tavolo 因 pulito...[n][w][e]

[msg MND_E10920100_CHK_Table]
[s][vp 1 0 0 0 0 0]Ora il tavolo 因 pulito...[n][w][e]

[msg MND_E12710100_CHK_Table]
[s][vp 1 0 0 0 0 0]Ora il tavolo 因 pulito...[n][w][e]

[msg MSG_E22810100_NG_CHK_Tab [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Alla disposizione penseremo dopo.[n]Prima prendi la pentola.[n][w][e]

[msg MSG_E22810100_NG_CHK_Tab_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]Cosa? Non trovi una pentola?[n]Non c'因 nulla neanche qui...[n][w][e]

[msg MND_E24410100_CHK_Table]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_CHK_Table]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg SHELF_CLEAN_mes00]
[s][vp 1 0 0 0 0 0]Alcune parti dello scaffale[n]sono arrugginite.[n][w][e]
[s][vp 1 0 0 0 0 0]Questi libri dall'aria complicata[n]vi erano stipati alla rinfusa...[n][w][e]

[msg SHELF_CLEAN_mes01]
[s][vp 1 0 0 0 0 0]Questi libri dall'aria complicata[n]vi erano stipati alla rinfusa...[n][w][e]

[msg SHELF_CLEAN_mes02]
[s][vp 1 0 0 0 0 0]Se togliessi i libri,[n]forse potrei usare[n]questo scaffale...[n][w][e]

[msg MND_E10530100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Alcuni libri sono stati[n]riposti alla rinfusa[n]su questo scaffale...[n][w][e]

[msg MND_E10920100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Alcuni libri sono stati[n]riposti alla rinfusa[n]su questo scaffale...[n][w][e]

[msg MND_E12710100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Alcuni libri sono stati[n]riposti alla rinfusa[n]su questo scaffale...[n][w][e]

[msg MSG_E22810100_NG_Shelf [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]La stanza 因 pulita,[n]ma dobbiamo prepararci.[n]Cerchiamo una pentola.[n][w][e]

[msg MSG_E22810100_NG_Shelf2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non credo che l淫[n]troverai una pentola.[n]Forse al piano di sotto?[n][w][e]

[msg MND_E24410100_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_CHK_Shelf]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg MND_E10920100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Ci sono oggetti sparsi[n]disordinatamente per terra.[n]Vedo a malapena il pavimento...[n][w][e]

[msg MND_E10530100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Ci sono oggetti sparsi[n]disordinatamente per terra.[n]Vedo a malapena il pavimento...[n][w][e]

[msg MND_E12710100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Ci sono oggetti sparsi[n]disordinatamente per terra.[n]Vedo a malapena il pavimento...[n][w][e]

[msg MSG_E22810100_NG_Floor [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Va bene voler pulire prima che[n]arrivino gli altri... ma te la sei[n]cercata, eh.[n][w][e]

[msg MSG_E22810100_NG_Floor2 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Ti avevo detto di sistemare...[n][w][e]

[msg MND_E24410100_CHK_Floor]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_CHK_Floor]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg MND_E10510100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]為 un cesto della biancheria[n]vecchio stile.[n][w][e]
[s][vp 1 0 0 0 0 0]All'interno ci sono uno strato[n]di polvere e una molletta.[n][w][e]

[msg MND_E10510100_CHK_Washbo_2]
[s][vp 1 0 0 0 0 0]為 un cesto della biancheria[n]vecchio stile.[n][w][e]

[msg MND_E10530100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]C'因 qualcos'altro che[n]devo fare...?[n][w][e]

[msg MND_E10920100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]Qui c'因 un cesto[n]della biancheria...[n][w][e]

[msg MND_E12710100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]Qui c'因 un cesto[n]della biancheria...[n][w][e]

[msg MND_E24410100_CHK_Washbo]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_CHK_Washbox]
[s][vp 1 0 0 0 0 0]Il cesto della biancheria[n]sta prendendo polvere...[n][w][e]
[s][vp 1 0 0 0 0 0]Giusto, c'era una lavanderia[n]automatica al bagno[n]pubblico qui vicino...[n][w][e]

[msg MSG_COMMON_CHK_Washbox_M [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1170 0 0]Ugh, questo cesto della biancheria[n]因 in uno stato pietoso.[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1189 0 0]Ora che ci penso, non c'era una[n]lavanderia automatica al bagno[n]pubblico qui vicino?[n][w][e]

[msg MND_NG_HIT_356_101]
[s][vp 1 0 0 0 0 0]Dovrei chiuderla qui[n]e andarmene a letto...[n][w][e]

[msg MND_NG_HIT_399_101]
[s][vp 1 0 0 0 0 0]Dovrei chiuderla qui[n]e andarmene a letto...[n][w][e]

[msg DELI_BOX_0409_mes00]
[s][vp 1 0 0 0 0 0]為 lo scatolone arrivato[n]da casa.[n][w][e]
[s][vp 1 0 0 0 0 0]為 pieno di vestiti e oggetti di[n]uso quotidiano. 為 ora di mettere[n]degli abiti pi迂 comodi.[n][w][e]

[msg DELI_BOX_mes01]
[s][vp 1 0 0 0 0 0]Oltre a mettere in ordine,[n]dovrei anche pulire la camera...[n][w][e]

[msg fev0409_10_CHECK_mes01]
[s][vp 1 0 0 0 0 0]Prima dovrei iniziare a pulire...[n][w][e]

[sel fev0409_10_CHECK_SEL top]
[s]Inizia a pulire[e]
[s]Guarda altrove[e]

[msg MND_E10530100_CHK_Sofa]
[s][vp 1 0 0 0 0 0]Il divano 因 stato pulito. Ora[n]ci si pu韻 sedere di nuovo.[n][w][e]

[msg MND_E10920100_CHK_Sofa]
[s][vp 1 0 0 0 0 0]Non ho tempo di mettermi[n]a riposare sul divano...[n][w][e]

[msg MSG_E22810100_NG_Sofa [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Non puoi essere cos淫[n]stanco da volerti sedere.[n]Devi farti dare la pentola.[n][w][e]

[msg MSG_E22810100_NG_Sofa2 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Qui si sieder稲 Lady Ann...[n]Miaohohoh...[n][w][e]

[msg MSG_E22810100_NG_TRChair [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Non 因 il momento di allenarsi![n]Dobbiamo preparare la pentola![n][w][e]

[msg MSG_E22810100_NG_TRChair_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1186 65535 0]La pentola non 因 al piano di[n]sotto? Che ha detto il capo?[n][w][e]

[msg MND_E24410100_TRChair]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_TRChair]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg MSG_E22810100_NG_PlantOB [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1048 65535 0]Dicono che le piante crescano[n]meglio quando sentono voci[n]allegre. Scateniamoci stasera![n][w][e]

[msg MSG_E22810100_NG_PlantOB_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]No, non 因 la pentola che cerchiamo...[n][w][e]

[msg MND_E24410100_PlantOBJ]
[s][vp 1 0 0 0 0 0]Sar稲 meglio andare all'incontro[n]con quella giornalista...[n][w][e]

[msg MND_COMMON_PlantOBJ]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

