[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_Door_WhatDo_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7062 65535 0]Hai altro da fare? Allora mi sa[n]che me ne esco anch'io.[n][w][e]

[msg MSG_Door_WhatDo_Yusuke [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 4054 65535 0]Devi andare da qualche parte?[n]Tra poco uscir韻 anch'io.[n][w][e]

[msg MSG_DAY_END_MONA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oggi non sei stanco?[n]Andiamo a dormire.[n][w][e]

[msg MSG_DAY_END]
[s]Dovrei andare a dormire...[n][w][e]

[sel SEL_DAY_END top]
[s]Dormi[e]
[s]Stai sveglio[e]

[msg MSG_LAST_GREETING_Freeze [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Non 因 il momento di guardare gli[n]ingredienti. Andiamo a salutare.[n][w][e]

[msg MSG_LAST_GREETING_Kitche [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Il profumo del caff因...[n]Mi mancher稲...[n][w][e]

[msg MSG_LAST_GREETING_Phone_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Chiss稲 se Kawakami 因 a scuola.[n]Vuoi andare da lei?[n][w][e]

[msg MSG_LAST_GREETING_Phone__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Chiss稲 se Kawakami 因 a scuola.[n]Oh, ma oggi 因 domenica...[n][w][e]

[msg MSG_LAST_GREETING_Phone [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Andiamo a trovare tutti.[n]Non limitiamoci a chiamarli.[n][w][e]

[msg MSG_LAST_GREETING_Counte [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Su questo bancone si legge meglio.[n][w][e]

[msg MSG_LAST_GREETING_Counte_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Basta fare l'intellettuale, andiamo[n]a incontrare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_Table [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Mi mancano i giorni in cui[n]studiavamo tutti assieme.[n][w][e]

[msg MSG_LAST_GREETING_Tv01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Vuoi dare un'occhiata ai ciliegi[n]in fiore mentre andiamo[n]a trovare gli altri?[n][w][e]

[msg MSG_LAST_GREETING_Curry [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Credo che non mangeremo[n]il curry del capo per un po'.[n]Torniamo indietro.[n][w][e]

[msg MSG_LAST_GREETING_SHELF_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Hai vissuto un anno intero con questo[n]profumo. Ti ricorderai degli[n]insegnamenti del capo?[n][w][e]

[msg MSG_LAST_GREETING_COFFEE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Cerca di non dimenticare quello che[n]ti ha insegnato il capo sul caff因.[n][w][e]

[msg MSG_LAST_GREETING_SHELF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Smettila di fissare il caff因[n]e andiamo dagli altri.[n][w][e]

[msg MSG_LAST_GREETING_Sayuri [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Non importa quante volte la veda,[n]la "Sayuri" 因 un dipinto stupendo.[n]Ricorda di salutare Yusuke, OK?[n][w][e]

[msg MSG_LAST_GREETING_Sayuri_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Non importa quante volte la veda,[n]la "Sayuri" 因 un dipinto stupendo.[n]Non la vedrai per un po'.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_TV [Giornalista]]
[s]Visto il tempo soleggiato e i primi[n]ciliegi in fiore, domani sar稲[n]una giornata ideale per uscire.[n][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Non hai ancora salutato[n]quei due. Sei sicuro di[n]voler concludere cos淫?[n][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Non hai ancora salutato[n]Futaba. Sicuro di voler[n]concludere cos淫?[n][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Non hai ancora salutato il[n]capo. Sicuro di voler[n]concludere cos淫?[n][w][e]

[sel SEL_LAST_GREETING_DOOR_0 top]
[s]Esci[e]
[s]Ripensaci[e]

[msg MSG_TABLE_CENTER_LOCK_MO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Eh? Qualcosa non va[n]con quel tavolo?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Potremmo metterci qualcosa sopra[n]e usarlo in qualche modo...[n][w][e]

[msg MSG_TABLE_CENTER_LOCK]
[s]Potremmo metterci qualcosa sopra[n]e usarlo in qualche modo...[n][w][e]

[msg MSG_StudyTutorial_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5147 65535 0]Usalo pure quando vuoi,[n]se devi studiare.[n][w][e]

[msg MSG_StudyTutorial [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Le dimensioni sono perfette.[n]C'因 molto spazio per studiare.[n][w][e]
[s]Non sottovalutare il valore[n]dell'intelligenza. Dopotutto, nessuno[n]seguirebbe un leader idiota.[n][w][e]

[msg MND_StudyTutorial]
[s]Questo tavolo 因 delle dimensioni[n]ideali per studiare...[n][w][e]

[msg MSG_Study_NotNight [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto, giusto?[n]Qui 因 meglio studiare la sera.[n][w][e]

[msg MND_Study_NotNight]
[s]Il Leblanc 因 ancora aperto.[n]Qui 因 meglio studiare[n]la sera...[n][w][e]

[msg MSG_Study_NotNight_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Ti offre un sacco di spazio[n]per studiare. Ma il[n]Leblanc 因 ancora aperto...[n][w][e]

[msg MND_Study_NotNight_nonTu]
[s]Questo tavolo sembra l'ideale[n]per studiare. Ma il Leblanc[n]因 ancora aperto...[n][w][e]

[msg MSG_Study_StandBy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Studierai un'altra volta.[n]Domani 因 il giorno del[n]colpo, ricordi?[n][w][e]

[msg MSG_Study_StandBy_nonTut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Sembra un posto perfetto[n]per studiare, ma adesso dovresti[n]pensare ai tuoi preparativi.[n][w][e]

[msg MSG_Study_PalaceAfter [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Forse ti conviene studiare[n]un'altra volta. La stanchezza[n]因 un grosso ostacolo per il lavoro.[n][w][e]

[msg MND_Study_PalaceAfter]
[s]Sono piuttosto stanco.[n]Studier韻 un'altra volta.[n][w][e]

[msg MSG_Study_PalaceAfter_no [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sembra un posto perfetto[n]per studiare, ma non sei[n]esausto dopo oggi?[n][w][e]

[msg MND_Study_PalaceAfter_no]
[s]Questo tavolo sembra l'ideale[n]per studiare. Ma per oggi[n]sono troppo stanco...[n][w][e]

[msg MSG_Study_SleepDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Riposiamoci un po' per[n]farci trovare pronti domani.[n]Leggerai un'altra volta.[n][w][e]

[msg MND_Study_SleepDay]
[s]Domani sar稲 una giornata intensa.[n]Studier韻 un'altra volta...[n][w][e]

[msg MSG_Study_SleepDay_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sembra un posto perfetto[n]per studiare, ma adesso[n]dovresti riposarti.[n][w][e]

[msg MND_Study_SleepDay_nonTu]
[s]Questo tavolo sembra l'ideale[n]per studiare. Ma mi conviene[n]riposarmi per domani...[n][w][e]

[msg MSG_Study_NotOpen_KyakuD [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto...[n]Sarai solo d'intralcio[n]restando qui a far niente.[n][w][e]

[msg MND_Study_NotOpen_KyakuD]
[s]Il Leblanc 因 ancora aperto...[n][w][e]

[msg MSG_StudyNG_Sojiro_Kyaku [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0]Oggi ci sono dei clienti, quindi...[n]Hai capito cosa intendo, giusto?[n][w][e]

[msg MSG_StudyNG_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ci sono ancora dei clienti...[n]Meglio studiare un'altra volta.[n][w][e]

[msg MND_StudyNG_KyakuDay]
[s]Ci sono ancora dei clienti.[n]Meglio studiare un'altra volta...[n][w][e]

[msg MSG_Study_Open_AkechiDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sai, Akechi resta pur sempre un[n]cliente. Ti conviene rimandare[n]lo studio a pi迂 tardi.[n][w][e]

[msg MSG_TABLE_CENTER_SojiroG [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Io me ne torno a casa.[n]Pulisci tutto quando hai[n]finito, d'accordo?[n][w][e]

[msg MSG_TABLE_CENTER_SojiroG_2 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Va bene, io me ne torno a casa.[n][w][e]

[msg MSG_Study_Q_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5081 65535 0]Quando sei in giro, il tempo per lo[n]studio scarseggia. Approfittane[n]ora, finch姻 puoi.[n][w][e]

[msg MSG_Study_Q_R [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Che fai oggi? Studi?[n][w][e]

[msg MSG_Study_Q_Rain [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Oggi il tempo 因 pessimo, ma...[n]quando si 因 bloccati in casa 因 pi迂[n]facile concentrarsi nello studio.[n][w][e]

[msg MND_Study_Q]
[s]Forse dovrei passare la giornata[n]a studiare...[n][w][e]

[sel SEL_TABLE_USE top]
[s]Studia[e]
[s]Annulla[e]

[msg MSG_Study_ParamInfo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ehi, c'因 un posto libero.[n]Vuoi studiare e migliorare la tua[n][stIcon 0][clr 26][stLabel 0][clr 27]?[n][w][e]

[msg MND_Study_ParamInfo]
[s]Credo che studiando qui[n]migliorer韻 la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_Study_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_Study_ParamUpInfo]
[s]Credo che il mio [stIcon 0][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MSG_FreezerRuburanOpen [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto.[n]Ti conviene chiudere il frigo[n]prima di cacciarti nei guai.[n][w][e]

[msg MND_FreezerRuburanOpen]
[s]Il Leblanc 因 ancora aperto.[n]Mi conviene chiudere il frigo[n]prima di cacciarmi nei guai.[n][w][e]

[msg MSG_FreezerKyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ci sono ancora dei clienti.[n]Ti conviene chiudere il frigo[n]prima di cacciarti nei guai.[n][w][e]

[msg MND_FreezerKyakuDay]
[s]Ci sono ancora dei clienti.[n]Mi conviene chiudere il frigo[n]prima di cacciarmi nei guai.[n][w][e]

[msg MSG_Curry_NotOpen_Akechi [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sai, Akechi resta pur sempre un[n]cliente. Dovresti chiudere il[n]frigo prima che il capo s'arrabbi.[n][w][e]

[msg MSG_Curry_NotOpen_Goro [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sai, Akechi resta pur sempre un[n]cliente. Dovresti chiudere il[n]frigo prima che il capo s'arrabbi.[n][w][e]

[msg MSG_FreezerItem_NotEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Mmm? Che c'因 scritto l稲[n]nell'angolo del frigo?[n]"Arrangiati con gli avanzi".[n][w][e]

[msg MND_FreezerItem_NotEnd]
[s]C'因 un appunto nell'angolo del[n]frigorifero. "Arrangiati con[n]gli avanzi".[n][w][e]

[msg MSG_FreezerItem_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Mmm, pare proprio che non[n]sia rimasto nulla.[n][w][e]

[msg MND_FreezerItem_End]
[s]Pare proprio che non sia[n]avanzato nulla...[n][w][e]

[msg MSG_FreezerFull_CurryON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Ci sono un po' di ingredienti[n]qui. Oh, puoi usare tutta questa[n]roba per preparare il curry?[n][w][e]

[msg MND_FreezerFull_CurryON]
[s]Ci sono un po' di ingredienti[n]qui dentro. Sembrano quelli[n]per preparare il curry...[n][w][e]

[msg MSG_FreezerNone_CurryON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]A quanto pare, abbiamo finito[n]gli ingredienti per il curry...[n]Ci riproverai un altro giorno.[n][w][e]

[msg MND_FreezerNone_CurryON]
[s]A quanto pare, abbiamo finito[n]gli ingredienti per il curry...[n][w][e]

[msg MSG_FREEZER_NOTHING_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]C'因 del cibo qui dentro, ma[n]nulla che si possa mangiare[n]al volo. 為 demoralizzante...[n][w][e]

[msg MSG_FREEZER_NOTHING]
[s]Non c'因 nulla di pronto[n]da mangiare in frigo.[n][w][e]

[msg MSG_TABLE_Freezer_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0]Mmm... Vuoi mangiare[n]qualcosa dal frigorifero?[n][w][e]
[s][f 4 10 65535 0 0]Beh, io me ne torno a casa.[n]Non lasciare sporcizia, OK?[n][w][e]

[msg MSG_CurryNG_KawaCoffeeON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]La cucina 因 occupata da Kawakami[n]al momento. Dovrai aspettare[n]un'altra volta per fare il curry.[n][w][e]

[msg MSG_CurryNG_KawaCoffeeON_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Hai imparato dal capo come[n]si prepara il curry, ma adesso[n]in cucina c'因 Kawakami.[n][w][e]

[msg MSG_Curry_TodayGoPalace [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ma non sei stanco?[n]Basta cos淫 per oggi,[n]andiamo a dormire.[n][w][e]

[msg MND_Curry_TodayGoPalace [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sono a pezzi.[n]Mi conviene andare a letto.[n][w][e]

[msg MSG_Curry_OnlySleepDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Dovremmo riposare per domani.[n][w][e]

[msg MND_Curry_OnlySleepDay]
[s]Mi conviene riposare oggi, cos淫 da[n]essere belli carichi per domani.[n][w][e]

[msg MSG_Curry_NoticeDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Domani 因 il giorno del colpo.[n]Stai attento a non prendere[n]un raffreddore.[n][w][e]

[msg MND_Curry_NoticeDay]
[s]Domani 因 il giorno del colpo...[n][w][e]

[msg MSG_Curry_Tutorial [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Ah, gi稲. Il capo ti ha insegnato[n]come preparare il curry, giusto?[n][w][e]

[msg MND_Curry_Tutorial]
[s]Oh, giusto... Sojiro[n]mi ha insegnato a preparare il curry.[n][w][e]

[msg MSG_CurryInfo_Common [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ehi, ci sono un po' di[n]ingredienti per il curry![n][w][e]

[msg MND_CurryInfo_Common]
[s]Ci sono un po' di[n]ingredienti per il curry...![n][w][e]

[msg MSG_CURRY_NG_0410]
[s]Qui c'因 un grosso tegame di curry.[n]Forse 因 in preparazione[n]per essere servito domani...[n][w][e]

[msg MSG_CurryPot_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto.[n]Usciamo dalla cucina prima[n]di cacciarci nei guai.[n][w][e]

[msg MSG_CURRY_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Se sapessi preparare il curry[n]speciale del locale, potremmo[n]mangiarlo quando ci pare.[n][w][e]

[msg MSG_CURRY_NOTOPEN]
[s]Credo che sia qui che venga[n]preparato il curry del Leblanc...[n][w][e]

[msg MSG_CURRY_OPEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Se nel frigo sono rimasti[n]abbastanza ingredienti, prova[n]a preparare del curry.[n][w][e]

[msg MND_CURRY_OPEN]
[s]Se nel frigo sono rimasti[n]abbastanza ingredienti, potrei[n]preparare del curry.[n][w][e]

[msg MSG_CURRY_OPEN_Gogo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ma il Leblanc non 因 ancora[n]aperto? Se resti in cucina,[n]sarai in mezzo ai piedi.[n][w][e]

[msg MND_CURRY_OPEN_Gogo]
[s]Il Leblanc 因 ancora aperto.[n]Non dovrei restarmene qui[n]in cucina...[n][w][e]

[msg MSG_CURRY_OPEN_Dng [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ma non sei stanco?[n]Basta cos淫 per oggi,[n]andiamo a dormire.[n][w][e]

[msg MND_CURRY_OPEN_Dng]
[s]Sono a pezzi.[n]Mi conviene andare a letto.[n][w][e]

[msg MSG_CurryPot_NotMakeDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pare che il capo abbia fatto[n]il curry. Dubito che siano[n]avanzati ingredienti, per韻...[n][w][e]

[msg MND_CurryPot_NotMakeDay]
[s]A quanto pare, Sojiro ha fatto il[n]curry. Difficilmente saranno[n]rimasti ingredienti per cucinare...[n][w][e]

[msg MSG_Curry_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Non lasciare aperto il frigo.[n][w][e]

[msg MSG_Curry_SojiroGoHome [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5020 65535 0]Oh, stai preparando la cena...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Sto tornando a casa, ma...[n]Attento con quei fornelli, OK?[n][w][e]

[msg MSG_Curry_SojiroGoHome_c [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Oh, stai preparando la cena?[n]Sto tornando a casa, ma...[n]Attenzione ai fornelli, OK?[n][w][e]

[msg MND_NotOpen_Croosword]
[s]La superficie di questo tavolo[n]因 stata pulita attentamente...[n][w][e]

[msg MSG_DUMMY_01]
[s]Devo pensare a cosa[n]fare adesso...[n][w][e]
[s]......[n][w][e]

[msg MSG_DUMMY_0410_mes01]
[s]Rispondo al telefono?[n][w][e]

[msg MSG_DUMMY_0410_mes02]
[s]Mi ha detto di girare il cartello.[n]為 quello sulla porta d'ingresso?[n][w][e]

[msg MSG_DUMMY_0410_mes03]
[s]Che fame...[n][w][e]

[msg MSG_DUMMY_0410_mes04]
[s]Domani ho scuola.[n]Dovrei andare a letto.[n][w][e]

[msg MSG_DUMMY_0411_mes01]
[s]Spero di orientarmi con[n]le linee ferroviarie...[n][w][e]

[msg MSG_CW_NotSetDay_NotOpen [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Mmm, che tavolo antico...[n]Ha un che di vintage e pittoresco.[n][w][e]

[msg MND_CW_NotSetDay_NotOpen]
[s]Ci sono dei piccoli graffi[n]sul tavolo...[n][w][e]

[msg MSG_CW_NotOpen_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Il Leblanc 因 ancora aperto.[n][w][e]

[msg MND_CW_NotOpen_KyakuDay]
[s]Il Leblanc 因 ancora aperto...[n][w][e]

[msg MSG_CW_NotOpen_KyakuDay_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Il Leblanc 因 ancora aperto.[n][w][e]

[msg MND_CW_NotOpen_KyakuDay_]
[s]Il Leblanc 因 ancora aperto...[n][w][e]

[msg MSG_CW_NotSetDay_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oggi manca la rivista[n]di cruciverba...[n][w][e]

[msg MND_CW_NotSetDay_Open]
[s]Oggi non c'因 la rivista[n]di cruciverba...[n][w][e]

[msg MSG_NotOpen_Crossword_tu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Cruciverba, eh?[n]Immagino siano un buon modo[n]per allenare la mente.[n][w][e]

[msg MND_NotOpen_Crossword_tu]
[s]為 una rivista di cruciverba...[n][w][e]

[msg MSG_CROSSWORD_PLAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Vuoi metterti a fare il cruciverba?[n]Non ti ci immergere troppo,[n]hai altre cose da fare.[n][w][e]

[msg MND_CROSSWORD_PLAY]
[s]Forse potrei cercare di risolvere[n]uno di questi cruciverba...[n][w][e]

[sel SEL_MGK_CROSSWORD_PLAY top]
[s]Gioca un po'[e]
[s]Non adesso[e]

[sel SEL_MGK_CROSSWORD_PLAY2 top]
[s]Gioca un po'[e]
[s]Leggi le curiosit稲[e]
[s]Non adesso[e]

[sel SEL_MGK_CROSSWORD_PLAY3 top]
[s]Leggi le curiosit稲[e]
[s]Non adesso[e]

[msg MSG_CROSSWORD_SojiroGoHo [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5020 65535 0]Oh, e cos淫 因 questo che[n]stavi cercando? Uhm, capisco.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Io sto per tornare a casa.[n]Non giocherellare con quei[n]cruciverba fino a tardi, OK?[n][w][e]

[msg MSG_CROSSWORD_SojiroGoHo_2 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Va bene, io me ne torno a casa.[n][w][e]

[msg MND_CrossWord_Stage_Coff]
[s]Sulla pagina c'因 scritto che 因 la[n]sezione "Caff因 e caffetterie"...[n][w][e]

[msg MND_CrossWord_Stage_Scho]
[s]Sulla pagina c'因 scritto che 因 la[n]sezione "Vita universitaria"...[n][w][e]

[msg MND_CrossWord_Stage_Phan]
[s]Sulla pagina c'因 scritto che 因 la[n]sezione "Ladri Fantasma"...[n][w][e]

[msg MND_CrossWord_Stage_Myth]
[s]Sulla pagina c'因 scritto che 因 la[n]sezione "Religione e mitologia"...[n][w][e]

[msg MSG_CrossWord_ParamUp [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Oh, wow... Quella non[n]la sapevo nemmeno io.[n][w][e]

[msg MSG_CrossWord_ParamUp02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Forse sei diventato un po'[n]pi迂 sveglio dopo aver[n]risolto questi cruciverba.[n][w][e]

[msg MND_CrossWord_ParamUp]
[s]OK, OK... Oh...[n]Ah, ora ho capito...[n][w][e]

[msg MND_CrossWord_ParamUp02]
[s]Credo di aver acquisito[n]maggior [stIcon 0][clr 26][stLabel 0][clr 27][n]dopo aver[n]risolto quel cruciverba.[n][w][e]

[msg MSG_CrossWord_AllClear [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non ci sono pi迂 cruciverba.[n]Credo che tu li abbia risolti[n]tutti quanti...[n][w][e]

[msg MND_CrossWord_AllClear]
[s]Non ci sono pi迂 cruciverba.[n]Credo di averli risolti[n]tutti quanti...[n][w][e]

[msg MSG_CrossWord_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]*yawn* Abbiamo davvero passato[n]tutto questo tempo sui cruciverba?[n]為 tardi, meglio andare a letto.[n][w][e]

[msg MND_CrossWord_End]
[s]Si 因 fatto tardi...[n]Mi conviene chiuderla qui[n]e andare a dormire.[n][w][e]

[msg MSG_CrossWord_Bad [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm, non li hai ancora risolti[n]tutti? Beh, ci riproverai[n]un'altra volta.[n][w][e]

[msg MND_CrossWord_Bad]
[s]Non sono riuscito a rispondere[n]a tutte le domande...[n][w][e]

[msg MSG_MGK_CROSSWORD_ALLCLE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]A quanto pare, hai finito[n]tutte le domande della pagina...[n][w][e]

[msg MND_MGK_CROSSWORD_ALLCLE]
[s]Non sono rimaste altre domande[n]su questa pagina...[n][w][e]

[msg MSG_CrossWord_kuria [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]So che sei annoiato, ma non credi[n]di aver giocato abbastanza?[n][w][e]

[msg MND_CrossWord_kuria]
[s]L'ho gi稲 completato. Per oggi[n]non posso pi迂 giocare.[n][w][e]

[msg MSG_CrossWord_sippai [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non puoi arrenderti di fronte al[n]problema di prima, giusto?[n]Questo 因 lo spirito![n][w][e]

[msg MND_CrossWord_sippai]
[s]Riprova a risolvere il cruciverba.[n][w][e]

[sel CrossWord_SEL top]
[s]SEMESTRI[e]
[s]FIORITURA[e]
[s]GOLDEN[e]
[s]MALUMORE[e]
[s]GALLERIA[e]
[s]POLLINOSI[e]
[s]NIPPONICA[e]
[s]MAESTRO[e]
[s]CONFERENZA[e]
[s]GUARDAROBA[e]
[s]DENARO[e]
[s]FRONTE[e]
[s]NARCOTICI[e]
[s]VACANZE[e]
[s]ESAMI[e]
[s]ARTIFICIO[e]
[s]ISOLA[e]
[s]CORAGGIO[e]
[s]USTIONE[e]
[s]TORRIDO[e]
[s]HACKER[e]
[s]TIFONE[e]
[s]FESTIVAL[e]
[s]CLASSIFICA[e]
[s]NERO[e]
[s]HALLOWEEN[e]
[s]STAND[e]
[s]RICOMPENSA[e]
[s]ATTACCO[e]
[s]CARISMA[e]
[s]INFLUENZA[e]
[s]ILLUMINA[e]
[s]CONSENSO[e]
[s]NATALE[e]
[s]PROPOSITI[e]
[s]DIONISO[e]
[s]LACHESI[e]
[s]OROCHI[e]

[msg CrossWord_MENU]
[s]Cruciverba[n][e]

[msg MSG_CrossWord_Toribia_OS [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Non si sa mai quando pu韻 tornare[n]utile sapere certe cose.[n][w][e]

[msg MSG_CrossWord_NG_Kyaku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ci sono ancora clienti a[n]quest'ora?[n][w][e]

[msg MND_CrossWord_NG_Kyaku]
[s]Ci sono ancora dei clienti[n]nel locale...[n][w][e]

[msg MSG_CrossWord_NG_Akechi_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Akechi 因 ancora qui? Beh, la sua[n]popolarit稲 因 precipitata, non posso[n]biasimarlo se 因 depresso.[n][w][e]

[msg MSG_CrossWord_NG_Akechi__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Akechi deve avere un sacco[n]di tempo libero se se ne resta[n]qui fino a quest'ora.[n][w][e]

[msg MSG_CrossWord_NG_Akechi__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Akechi 因 ancora qui... Non[n]star稲 architettando qualcosa, vero?[n][w][e]

[msg MSG_CrossWord_NG_Akechi__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Akechi 因 ancora qui. Si vede che[n]trova rilassante questo posto.[n][w][e]

[msg MSG_CrossWord_NG_StandBy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non hai tempo da perdere.[n]Ricordi cosa dobbiamo[n]fare domani, giusto?[n][w][e]

[msg MSG_CW_NG_StandBy_NotSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Che succede? Dobbiamo[n]essere pronti per domani.[n][w][e]

[msg MSG_CrossWord_NG_StandBy_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]T'interessa quella rivista?[n]Ci conviene prepararci per[n]domani, per韻.[n][w][e]

[msg MSG_CW_NG_StandBy_nonTut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Che succede? Dobbiamo[n]essere pronti per domani.[n][w][e]

[msg MSG_CrossWord_NG_DNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sforzarti troppo quando[n]sei stanco. Puoi sempre[n]farlo un'altra volta.[n][w][e]

[msg MND_CrossWord_NG_DNG]
[s]Sono esausto dopo gli eventi[n]di oggi. Mi conviene provarci[n]un'altra volta...[n][w][e]

[msg MSG_CW_NG_DNG_notSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Che ti prende? Dovresti[n]andare a riposare.[n][w][e]

[msg MND_CW_NG_DNG_notSet]
[s]Mi conviene riposare[n]un po' per oggi...[n][w][e]

[msg MSG_CrossWord_NG_DNG_non [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Una rivista di cruciverba, eh?[n]Ma non sei stanco?[n]Fallo un'altra volta.[n][w][e]

[msg MND_CrossWord_NG_DNG_non]
[s]C'因 una rivista di cruciverba[n]qui... ma per oggi mi[n]conviene riposare.[n][w][e]

[msg MSG_CW_NG_DNG_nonTuto_no [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Che tavolo spazioso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Perch姻 non chiedi al capo[n]se puoi usarlo?[n][w][e]

[msg MND_CW_NG_DNG_nonTuto_no]
[s]Mi conviene riposare[n]un po' per oggi...[n][w][e]

[msg MSG_CrossWord_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto.[n][w][e]

[msg MND_CrossWord_NG]
[s]Il Leblanc 因 ancora aperto...[n][w][e]

[msg MSG_CrossWord_Trivia01 [SEMESTRI]]
[s]Molte scuole dividono l'anno in due semestri o tre[n]quadrimestri. In Giappone, l'anno scolastico[n]inizia ad aprile.[n][w][e]
[s]Il governo giapponese, per韻, divide l'anno in modo[n]diverso. Ad esempio, il periodo da luglio a giugno[n]因 "l'anno del grano".[n][w][e]

[msg MSG_CrossWord_Trivia02 [FIORITURA]]
[s]Letteralmente "ammirare i fiori", l'hanami 因 un'antica[n]tradizione giapponese che consiste nel godere della[n]fioritura dei ciliegi e dell'arrivo della primavera.[n][w][e]
[s]Il "fiore" menzionato nella poesia tradizionale[n]giapponese 因 il fiore del pruno. Durante il[n]periodo Heian 因 diventato il fiore di ciliegio.[n][w][e]

[msg MSG_CrossWord_Trivia03 [GOLDEN]]
[s]La Golden Week 因 di solito a cavallo[n]tra la fine di aprile e l'inizio di maggio,[n]e include anche il sabato e la domenica.[n][w][e]
[s]"Golden" deriva dal termine televisivo giapponese[n]"golden time" e si riferisce alla fascia oraria con il[n]pi迂 alto indice di ascolti giornalieri.[n][w][e]

[msg MSG_CrossWord_Trivia04 [MALUMORE]]
[s]In Giappone si definisce "May Blues" quel malumore[n]derivato dal cambio di stagione e dall'aumento[n]dei malanni dopo la lunga festivit稲 di inizio aprile.[n][w][e]
[s]Nel resto del mondo si usano espressioni simili. Ad[n]esempio, in America si parla di "September Blues"[n]al rientro dalle vacanze estive.[n][w][e]

[msg MSG_CrossWord_Trivia05 [GALLERIA]]
[s]La galleria 因 l'area dove vengono esposte opere[n]d'arte o dove il pubblico si riunisce per assistere[n]a eventi, come concerti o opere teatrali.[n][w][e]
[s]Pu韻 anche riferirsi a un tunnel di una miniera o[n]a un passaggio creato da un animale, come ad[n]esempio i cunicoli sotterranei delle talpe.[n][w][e]

[msg MSG_CrossWord_Trivia06 [POLLINOSI]]
[s]Reazione allergica causata dal contatto del[n]polline con le mucose del naso o degli occhi.[n]Causa starnuti, naso che cola e prurito agli occhi.[n][w][e]
[s]Questi sintomi si manifestavano spesso quando[n]i contadini inglesi mietevano i loro pascoli, da[n]cui il nome comune "febbre da fieno".[n][w][e]

[msg MSG_CrossWord_Trivia07 [NIPPONICA]]
[s]A differenza degli stili artistici occidentali importati,[n]i dipinti prodotti dopo il 1900 con tecniche[n]giapponesi sono chiamati "Nihonga".[n][w][e]
[s]Durante il periodo Meiji i turisti in Giappone[n]chiamavano queste opere "dipinti giapponesi",[n]letteralmente "Nihon" (Giappone) e "ga" (opera).[n][w][e]

[msg MSG_CrossWord_Trivia08 [MAESTRO]]
[s]L'espressione "maestro d'arte" 因 un titolo riservato[n]agli artisti di incredibile talento e tecnica, divenuti[n]molto influenti nei loro specifici campi e generi.[n][w][e]
[s]Uno dei pi迂 prolifici maestri della pittura, Pablo[n]Picasso, ha anche uno dei nomi completi pi迂[n]lunghi della storia dell'arte: ben 103 lettere![n][w][e]

[msg MSG_CrossWord_Trivia09 [CONFERENZA]]
[s]Si ha quando la stampa viene riunita per ascoltare[n]e riferire informazioni che vengono rese pubbliche.[n]Pu韻 essere sia programmata che dell'ultimo minuto.[n][w][e]
[s]In una conferenza stampa, di solito vengono[n]stabilite entrate e uscite differenti, per evitare[n]assalti dalla stampa all'uscita.[n][w][e]

[msg MSG_CrossWord_Trivia10 [GUARDAROBA]]
[s]Gli studenti giapponesi fanno il cambio di guardaroba[n]due volte all'anno per stare pi迂 comodi. Ogni uniforme[n]scolastica ha una versione estiva e una invernale.[n][w][e]
[s]Si dice che il cambio di guardaroba abbia avuto[n]origine in Cina. Nel periodo Edo, la gente doveva[n]cambiare il guardaroba quattro volte all'anno.[n][w][e]

[msg MSG_CrossWord_Trivia11 [DENARO]]
[s]Termine generico per i soldi, "denaro" deriva dal[n]latino "denarius", che indicava una moneta del[n]valore di dieci assi.[n][w][e]
[s]Nel corso della storia, una variet稲 incredibile di[n]oggetti 因 stata utilizzata come moneta di scambio:[n]rocce, conchiglie, bestiame, piume, sale.[n][w][e]

[msg MSG_CrossWord_Trivia12 [FRONTE]]
[s]Quando correnti d'aria fredda e calda si scontrano,[n]il confine 因 chiamato fronte stazionario. Ad esempio,[n]il fronte piovoso dura dalla primavera all'estate.[n][w][e]
[s]La stagione delle piogge in Giappone 因 detta "tsuyu",[n]i cui caratteri sono "pruno" e "pioggia". Forse perch姻[n]coincide con la maturazione delle prugne.[n][w][e]

[msg MSG_CrossWord_Trivia13 [NARCOTICI]]
[s]Si riferisce a qualsiasi farmaco che induce torpore,[n]ma pi迂 spesso 因 usato come termine per droghe[n]assunte sia legalmente che illegalmente.[n][w][e]
[s]La morfina, un comune narcotico usato come[n]antidolorifico in molte strutture mediche, deve[n]il suo nome a Morfeo, il dio greco del sonno.[n][w][e]

[msg MSG_CrossWord_Trivia14 [VACANZE]]
[s]Le vacanze pi迂 comuni per scuole e aziende sono[n]in estate. La loro durata dipende dalla prefettura,[n]ma 因 sempre una pausa lunga e attesa.[n][w][e]
[s]Il Giappone ha un altro periodo di vacanza in autunno.[n]Dura dai tre ai sette giorni, molto meno di[n]quello estivo, ma 因 sempre benvenuto.[n][w][e]

[msg MSG_CrossWord_Trivia15 [ESAMI]]
[s]Gli esami si tengono alla fine del semestre o del[n]quadrimestre per determinare la competenza degli[n]studenti in ciascuna materia.[n][w][e]
[s]In Giappone si usano nelle valutazioni "O" e "X",[n]il cui significato varia rispetto alle altre nazioni.[n]Non sempre "O" significa che la risposta 因 giusta![n][w][e]

[msg MSG_CrossWord_Trivia16 [ARTIFICIO]]
[s]Questo spettacolo all'aperto 因 popolare da secoli. Dei[n]contenitori vengono riempiti di esplosivi e composti[n]chimici per creare colori, fumo e suoni allo scoppio.[n][w][e]
[s]Lo sapevi che i fuochi d'artificio non fischiano una[n]volta lanciati? Il fischio di un razzo 因 il risultato di[n]una componente apposita.[n][w][e]

[msg MSG_CrossWord_Trivia17 [ISOLA]]
[s]Le isole di calore sono aree pi迂 calde delle zone[n]circostanti, generate da una scarsa ritenzione[n]idrica e da un alto assorbimento di calore.[n][w][e]
[s]I giorni in cui la massima supera i 25 gradi sono detti[n]"natsubi" (estate), oltre i 30 "manatsubi" (mezza estate)[n]e oltre i 35 sono i "moushoubi" (molto caldi).[n][w][e]

[msg MSG_CrossWord_Trivia18 [CORAGGIO]]
[s]Una prova di coraggio comune 因 entrare in posti[n]spaventosi o sinistri. In Giappone, questi luoghi[n]sono spesso cimiteri o templi bui.[n][w][e]
[s]L'antico gioco di coraggio "100 racconti fantastici"[n]ebbe inizio nel periodo Edo e divenne popolare[n]tra i samurai per mettere alla prova i loro nervi.[n][w][e]

[msg MSG_CrossWord_Trivia19 [USTIONE]]
[s]Infiammazione della pelle causata dai raggi[n]ultravioletti del sole, che comporta un cambio[n]temporaneo della pigmentazione cutanea.[n][w][e]
[s]I raggi UV sono riflessi da molte superfici, incluse[n]l'acqua, la sabbia e la neve. Ci韻 pu韻 causare[n]ustioni persino mentre si scia.[n][w][e]

[msg MSG_CrossWord_Trivia20 [TORRIDO]]
[s]In Giappone, un giorno 因 considerato torrido quando[n]la temperatura minima supera i 25 gradi. Ci韻 因 dovuto[n]all'effetto delle isole di calore.[n][w][e]
[s]Prima che l'espressione "colpo di calore" si[n]diffondesse, si credeva che le morti a esso[n]dovute fossero provocate da cause non naturali.[n][w][e]

[msg MSG_CrossWord_Trivia21 [HACKER]]
[s]Anche se viene usato per indicare un criminale, un [n]"hacker" 因 chi entra in qualsiasi sistema protetto,[n]a prescindere dall'intento malevolo o meno.[n][w][e]
[s]Si definisce "white hat" un hacker che aiuta a rivelare[n]le vulnerabilit稲 nei sistemi, a differenza del "black hat"[n]che li viola illegalmente con effetti dannosi.[n][w][e]

[msg MSG_CrossWord_Trivia22 [TIFONE]]
[s]Si riferisce a cicloni tropicali dai venti sostenuti con[n]velocit稲 di almeno 118 km/h che soffiano nella[n]regione dell'Oceano Pacifico nord-occidentale.[n][w][e]
[s]La scala di misurazione dell'intensit稲 di un ciclone[n]in Giappone prevede pi迂 di otto categorie, tra cui:[n]"Tifone", "Tifone molto forte" e "Tifone violento".[n][w][e]

[msg MSG_CrossWord_Trivia23 [FESTIVAL]]
[s]Lo Tsukimi 因 una festa tradizionale in cui si ammira la luna[n]in autunno. Esistono anche termini che indicano il[n]guardare la luna quando piove o quando 因 nuova.[n][w][e]
[s]Per preparare gli "Tsukimi dango", il numero giusto[n]di pezzi dipende dalla data. Se lo Tsukimi cade il 15,[n]i pezzi saranno 15; se cade il 13, saranno 13.[n][w][e]

[msg MSG_CrossWord_Trivia24 [CLASSIFICA]]
[s]Con una classifica 因 pi迂 facile mettere in ordine pi迂[n]voci, a prescindere dalla loro lunghezza. Scegliendo[n]un fattore specifico, ordinare diventa pi迂 semplice.[n][w][e]
[s]Votare pu韻 essere complesso. Il "metodo di Borda"[n]permette ai votanti di fare una classifica delle loro[n]scelte, che viene poi conteggiata al posto dei voti.[n][w][e]

[msg MSG_CrossWord_Trivia25 [NERO]]
[s]Questo colore appare in numerose espressioni e[n]metafore dalle accezioni negative, quali "lista nera",[n]"mercato nero" e "pecora nera".[n][w][e]
[s]Diversi Paesi hanno una bandiera che contiene il nero,[n]ma ci sono molti significati dietro questo colore, come[n]le battaglie o il passato di una nazione.[n][w][e]

[msg MSG_CrossWord_Trivia26 [HALLOWEEN]]
[s]Festa dalle origini contrastanti tenuta il 31 ottobre. Si[n]sostiene che sia una festa celtica per il raccolto o[n]che sia una festa cristiana in onore dei santi.[n][w][e]
[s]Anche al termine "jack-o'-lantern" si attribuiscono[n]diverse origini, ma tutti concordano sul fatto che[n]l'intaglio delle zucche sia nato in Irlanda.[n][w][e]

[msg MSG_CrossWord_Trivia27 [STAND]]
[s]Questi negozietti vengono spesso messi in piedi alle[n]fiere o anche agli eventi scolastici dagli studenti stessi.[n]Vi si pu韻 trovare ogni sorta di cibo e altri prodotti.[n][w][e]
[s]Lo staff degli stand deve soddisfare alcuni requisiti per[n]poter operare, come inviare rapporti all'ufficio sanitario[n]e rispettare determinati standard di sicurezza.[n][w][e]

[msg MSG_CrossWord_Trivia28 [RICOMPENSA]]
[s]Denaro conferito a chiunque fornisca informazioni[n]decisive riguardanti un caso, soddisfando le richieste[n]di chi raccoglie le informazioni.[n][w][e]
[s]In caso di pi迂 informatori, la ricompensa conferita[n]dal Sistema speciale di incentivazione investigativa[n]giapponese varia a seconda del grado di utilit稲.[n][w][e]

[msg MSG_CrossWord_Trivia29 [ATTACCO]]
[s]Oggi "attacco" non riguarda solo il contesto[n]militare, ma viene utilizzato anche per indicare[n]una critica verso una persona o un gruppo.[n][w][e]
[s]Il termine pu韻 anche indicare la parte offensiva di[n]una squadra sportiva, l'inizio di un pezzo musicale[n]o anche una crisi acuta di una malattia.[n][w][e]

[msg MSG_CrossWord_Trivia30 [CARISMA]]
[s]L'abilit稲 di attirare o affascinare gli altri.[n]Deriva dal greco "ch茨ris", che significa[n]"grazia" o "dono".[n][w][e]
[s]Il carisma non dipende dalla bont稲 o dalla cattiveria[n]di una persona. Un uomo, che sia buono o cattivo,[n]因 carismatico se ha il potere di attrarre gli altri.[n][w][e]

[msg MSG_CrossWord_Trivia31 [INFLUENZA]]
[s]Malattia infettiva che causa febbre alta e dolori[n]articolari. Tale virus pu韻 sopravvivere fuori dal[n]corpo umano per diversi giorni.[n][w][e]
[s]Mentre l'influenza 因 difficile da combattere a causa[n]della sua mutazione genetica, altre malattie simili[n]sono state debellate, come la peste bovina (2001).[n][w][e]

[msg MSG_CrossWord_Trivia32 [ILLUMINA]]
[s]Chiamate "denshoku" ("luci decorative"), luci come[n]strisce a LED o lampadine illuminano cartelli o[n]altro per attirare l'attenzione su una pubblicit稲.[n][w][e]
[s]In passato, le uniche luci a LED colorate erano rosse.[n]Sviluppate quelle verdi, blu e bianche, l'intero spettro[n]因 diventato disponibile per gli inserzionisti.[n][w][e]

[msg MSG_CrossWord_Trivia33 [CONSENSO]]
[s]Un valore numerico che indica l'opinione della societ稲[n]su qualcosa, come il leader di una nazione o un partito[n]politico. I consensi e l'abilit稲 politica non sono collegati.[n][w][e]
[s]I dati sono calcolati con un sondaggio effettuato su un[n]campione di persone, non sull'intera popolazione, per[n]cui i risultati possono non essere precisi.[n][w][e]

[msg MSG_CrossWord_Trivia34 [NATALE]]
[s]25 di dicembre secondo il calendario gregoriano,[n]il giorno della nascita di Ges迂 Cristo e il giorno[n]dopo il lavoro sbalorditivo di Babbo Natale.[n][w][e]
[s]Il governo degli Stati Uniti ha un programma che[n]rintraccia Babbo Natale ogni anno. Secondo i dati,[n]viaggia 100 volte pi迂 veloce dello Shinkansen.[n][w][e]

[msg MSG_CrossWord_Trivia35 [PROPOSITI]]
[s]Obiettivi personali per l'anno a venire. Sono formulati[n]prima o all'inizio del nuovo anno. Molte persone[n]cercano di portarli a termine lungo tutto l'anno.[n][w][e]
[s]Uno dei kanji di "proposito" significa "fardello", ma[n]il termine in s姻 non 因 usato con accezione negativa:[n]因 un semplice riconoscimento di responsabilit稲.[n][w][e]

[msg MSG_CrossWord_Trivia36 [DIONISO]]
[s]Un dio della mitologia greca, il cui nome significa[n]"giovane Zeus". Ha viaggiato in vari luoghi,[n]creando un culto di fanatici devoti.[n][w][e]
[s]Il filosofo Nietzsche indic韻 i due principi centrali della[n]cultura greca antica, "apollineo" e "dionisiaco", nella[n]sua opera "La nascita della tragedia".[n][w][e]

[msg MSG_CrossWord_Trivia37 [LACHESI]]
[s]為 una delle tre dee greche del fato, con sua sorella[n]maggiore Cloto e quella minore Atropo. 為 la dea[n]che misura il filo del destino da tagliare.[n][w][e]
[s]"Lachesis" 因, inoltre, il nome di un genere di vipere,[n]pi迂 comunemente note come "terrore dei boschi".[n]Sono i pi迂 lunghi serpenti velenosi in Occidente.[n][w][e]

[msg MSG_CrossWord_Trivia38 [OROCHI]]
[s]"Yamata-no-Orochi" 因 un drago gigante della mitologia[n]giapponese con otto teste e otto code. Ucciso da[n]Susano-o mentre era privo di sensi a causa del sake.[n][w][e]
[s]Orochi mangi韻 sette figlie di una coppia di anziani,[n]cos淫 Susano-o si offr淫 di uccidere il drago in cambio[n]della mano della loro ultima figlia.[n][w][e]

[msg MSG_TABLE_FRONT_DEFAULT_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Il divano del locale[n]因 abbastanza vecchio,[n]ma 因 stato pulito a fondo.[n][w][e]

[msg MSG_TABLE_FRONT_DEFAULT]
[s]Il divano del locale 因 stato[n]pulito a fondo...[n][w][e]

[msg MSG_RuburanTable_Akechi0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Akechi 因 ancora qui? Beh, la sua[n]popolarit稲 因 precipitata, non posso[n]biasimarlo se 因 depresso.[n][w][e]

[msg MSG_RuburanTable_Akechi0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Akechi deve avere un sacco[n]di tempo libero se se ne resta[n]qui fino a quest'ora.[n][w][e]

[msg MSG_RuburanTable_Akechi0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Akechi 因 ancora qui... Non[n]star稲 architettando qualcosa, vero?[n][w][e]

[msg MSG_RuburanTable_Akechi0_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Akechi 因 ancora qui. Si vede che[n]trova rilassante questo posto.[n][w][e]

[msg MSG_COUNTER_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Quel libro 因 stravecchio, ormai non[n]因 pi迂 leggibile. Perch姻 non[n]ne compri uno altrove?[n][w][e]

[msg MSG_COUNTER_NOTOPEN]
[s]Qui ci sono dei vecchi[n]libri tascabili...[n][w][e]

[msg MSG_BookNG_NotNight [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto,[n]giusto? Se vuoi leggere[n]un libro, fallo di notte.[n][w][e]

[msg MND_BookNG_NotNight]
[s]Il Leblanc 因 ancora aperto.[n]Per leggere un po',[n]dovr韻 aspettare la notte...[n][w][e]

[msg MSG_BookNG_NotNight_nonT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sembra il posto perfetto[n]per leggere un po', ma il Leblanc[n]因 ancora aperto.[n][w][e]

[msg MND_BookNG_NotNight_nonT]
[s]Questo sembra un posto ideale per[n]leggere un libro, ma il[n]Leblanc 因 ancora aperto...[n][w][e]

[msg MSG_BookNG_StandBy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Oggi niente libri.[n]Piuttosto, cerca di prepararti[n]per domani.[n][w][e]

[msg MSG_BookNG_StandBy_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Sembra il posto perfetto per[n]leggere un po', ma oggi dovresti[n]pensare a prepararti.[n][w][e]

[msg MSG_BookNG_PalaceAfter [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Devi essere stanco morto.[n]Dubito che assimileresti i[n]concetti dei libri.[n][w][e]

[msg MND_BookNG_PalaceAfter]
[s]Oggi sono un po' stanco.[n]Meglio leggere un'altra volta...[n][w][e]

[msg MSG_BookNG_PalaceAfter_n [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Oh, vuoi leggere qualcosa?[n]Devi essere stanco.[n]Ti conviene rimandare.[n][w][e]

[msg MND_BookNG_PalaceAfter_n]
[s]Sembra un posto carino per[n]leggere, ma per oggi mi[n]conviene riposarmi...[n][w][e]

[msg MSG_BookNG_SleepDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Riposiamoci un po' per[n]farci trovare pronti domani.[n]Leggerai un'altra volta.[n][w][e]

[msg MND_BookNG_SleepDay]
[s]Domani sar稲 una giornata intensa.[n]Legger韻 un'altra volta...[n][w][e]

[msg MSG_BookNG_SleepDay_nonT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oh, vuoi leggere qualcosa?[n]Devi essere stanco.[n]Ti conviene rimandare.[n][w][e]

[msg MND_BookNG_SleepDay_nonT]
[s]Sembra un posto carino per[n]leggere, ma per oggi mi[n]conviene riposarmi...[n][w][e]

[msg MSG_BookNG_NotHave [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Non hai libri da leggere...[n][w][e]

[msg MND_BookNG_NotHave]
[s]Non ho libri da leggere...[n][w][e]

[msg MSG_BookNG_NotHave_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sembra il luogo ideale[n]per leggere. Perch姻 non vai[n]a comprarti un libro per dopo?[n][w][e]

[msg MND_BookNG_NotHave_nonTu]
[s]Sembra che qui possa immergermi[n]completamente nella lettura. Dovrei[n]comprarmi un libro per dopo.[n][w][e]

[msg MSG_BookNG_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ci sono ancora dei clienti...[n]Leggerai pi迂 tardi.[n][w][e]

[msg MND_BookNG_KyakuDay]
[s]Ci sono ancora dei clienti.[n]Meglio leggere un'altra volta...[n][w][e]

[msg MSG_BookNG_KyakuDay_nonT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Sembra il posto perfetto[n]per leggere un po', ma non[n]puoi quando ci sono clienti.[n][w][e]

[msg MND_BookNG_KyakuDay_nonT]
[s]Sembra un posto perfetto[n]per leggere, ma ci sono[n]ancora dei clienti...[n][w][e]

[msg MSG_RubuBook_Tuto [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Sembra un buon posto[n]per leggere un libro.[n][w][e]

[msg MND_RubuBook_Tuto]
[s]Sembra il posto perfetto[n]per immergersi completamente[n]nella lettura.[n][w][e]

[msg MSG_TABLE_Book_SojiroGoH [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5020 65535 0]Mmm? Devi usare il locale[n]per qualcosa?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Beh...[n]Non lasciare in disordine.[n]Io me ne vado a casa.[n][w][e]

[msg MSG_TABLE_Book_SojiroGoH_2 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Va bene, io me ne torno a casa.[n][w][e]

[msg MSG_PHONE_DEFAULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Mmm? Perch姻 mai usare[n]quest'affare oggigiorno?[n][w][e]

[msg MSG_PHONE_DEFAULT]
[s]Chiss稲 se ci sono clienti[n]che utilizzano questo[n]telefono pubblico...[n][w][e]

[msg MSG_PHONE_0410_mes01]
[s]Chiss稲 se ci sono clienti[n]che utilizzano questo[n]telefono pubblico...[n][w][e]

[msg MSG_PHONE_STANDBY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Domani abbiamo il colpo, lo sai?[n]Puoi farlo un'altra volta.[n][w][e]

[msg MSG_PHONE_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Se userai il telefono con il[n]locale ancora aperto, il capo[n]s'arrabbier稲.[n][w][e]

[msg MSG_COFFEE_NG_mes01]
[s]Qui ci sono alcune[n]macchinette del caff因...[n][w][e]

[msg MSG_Coffee_NotOpen_Kyaku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]E cos淫 questa si usa per[n]preparare il caff因, eh? Sembra[n]sia stata usata parecchio.[n][w][e]

[msg MSG_Coffee_Open_Kyaku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Il Leblanc 因 ancora aperto.[n]Non dovresti metterti[n]ad armeggiare adesso.[n][w][e]

[msg MSG_Coffee_Open_Akechi [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sai, Akechi resta pur sempre[n]un cliente. Non metterti a[n]preparare il caff因 adesso.[n][w][e]

[msg MSG_Coffee_Open_Goro [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sai, Akechi resta pur sempre[n]un cliente. Non metterti a[n]preparare il caff因 adesso.[n][w][e]

[msg MSG_COFFEE_NG_0410_mes01]
[s]Dovrei rispondere al[n]telefono, per adesso...[n][w][e]

[msg MSG_COFFEE_NG_0410_mes02]
[s]Preferirei mangiare qualcosa[n]anzich姻 bere caff因. Cerchiamo[n]un po' nel [clr 2]frigorifero[clr 27].[n][w][e]

[msg MSG_COFFEE_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]E cos淫 questa si usa per[n]preparare il caff因, eh? Sembra[n]sia stata usata parecchio.[n][w][e]

[msg MSG_COFFEE_NOTOPEN]
[s]Ci sono tutta una serie[n]di macchine per[n]preparare il caff因.[n][w][e]

[msg MSG_Coffee_Sojiro_FIRST [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]Sai come si prepara il caff因?[n][w][e]
[s][f 4 10 65535 0 0]Serviti pure dei chicchi sulle[n]mensole. Ti spiegher韻 le[n]differenti variet稲 pi迂 avanti.[n][w][e]
[s][f 4 10 65535 0 0]D'accordo, io esco a[n]comprare le sigarette...[n][w][e]

[msg MSG_Coffee_Sojiro_01 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5122 65535 0]Sembra che la cosa stia iniziando[n]ad appassionarti. Ehi, non lo fai[n]per impressionarmi, vero?[n][w][e]
[s][f 4 10 65535 0 0]Beh, fa lo stesso...[n]Io esco a comprare[n]le sigarette...[n][w][e]

[msg MSG_Coffee_Sojiro_02 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5019 65535 0]為 bello una volta che ci si prende[n]la mano, eh? C'因 cos淫 tanto da[n]scoprire e imparare del caff因.[n][w][e]
[s][f 4 10 65535 0 0]Beh, fa lo stesso...[n]Io esco a comprare[n]le sigarette...[n][w][e]

[msg MSG_Coffee_Sojiro_03 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5092 65535 0]Beh, ti vedo sospettosamente[n]entusiasta. La fissa del caff因[n]ti ha scombussolato, eh?[n][w][e]
[s][f 4 10 65535 0 0]Beh, fa lo stesso...[n]Io esco a comprare[n]le sigarette...[n][w][e]

[msg MSG_Coffee_Sojiro_04 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5024 65535 0]Sembra che il lavoro stia iniziando[n]ad appassionarti. Non vorrai[n]mica rubarmi il posto?[n][w][e]
[s][f 4 10 65535 0 0]Beh, fa lo stesso...[n]Io esco a comprare[n]le sigarette...[n][w][e]

[msg MSG_Coffee_Sojiro_GoHome [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Per oggi vado a casa.[n]Mi fa piacere che tu abbia[n]mostrato interesse per l'attivit稲.[n][w][e]

[msg MSG_CoffeeNG_KawaCurryON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]La cucina 因 occupata da Kawakami[n]al momento. Dovrai aspettare[n]un'altra volta per fare il caff因.[n][w][e]

[msg MSG_CoffeeNG_KawaCurryON_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Hai imparato come si prepara[n]il caff因, ma adesso in cucina[n]c'因 Kawakami.[n][w][e]

[msg MSG_COFFEE_NOT_NIGHT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hai imparato dal capo a[n]preparare il caff因, ma dovresti[n]aspettare la chiusura...[n][w][e]

[msg MND_COFFEE_NOT_NIGHT]
[s]Il Leblanc 因 ancora aperto.[n]Dovr韻 prepararmi un po'[n]di caff因 stasera...[n][w][e]

[msg MSG_COFFEE_TodayGoPalace [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Perch姻 lo stai facendo adesso[n]che sei gi稲 esausto? Risparmiati[n]per un'altra volta.[n][w][e]

[msg MND_COFFEE_TodayGoPalace]
[s]Sono troppo stanco per oggi...[n]Lo far韻 domani.[n][w][e]

[msg MSG_COFFEE_OrderAfter [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non hai chiesto a qualcuno[n]di prepararti il caff因?[n][w][e]

[msg MND_COFFEE_OrderAfter]
[s]Ho gi稲 chiesto a Kawakami[n]di preparare il caff因...[n][w][e]

[msg MSG_COFFEE_NoticeDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Stai pensando di usare quella[n]macchina del caff因? Beh, sarebbe[n]meglio che ti riposassi per domani.[n][w][e]

[msg MND_COFFEE_NoticeDay]
[s]Dovrei riposare per domani...[n][w][e]

[msg MSG_COFFEE_SHELF_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s][f 4 10 65535 0 0]Sono tutte variet稲 differenti di[n]chicchi? Il caff因 因 molto pi迂[n]complesso di quanto credessi...[n][w][e]

[msg MSG_COFFEE_SHELF]
[s]Ci sono svariati chicchi di caff因[n]tutti belli allineati. Un lieve[n]aroma di caff因 profuma l'aria...[n][w][e]
[s]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s]Ce ne sono anche degli altri[n]di cui ignoro il nome...[n][w][e]

[msg MSG_COFFEE_SETUMEI_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s][f 4 10 65535 0 0]Sono tutte variet稲 differenti di[n]chicchi? Il caff因 因 molto pi迂[n]complesso di quanto credessi...[n][w][e]
[s][f 4 10 65535 0 0]Ricordi quando il capo ti ha[n]istruito sul caff因? Ti vengono[n]in mente alcune variet稲?[n][w][e]

[msg MND_COFFEE_SETUMEI_01]
[s]Ci sono svariati chicchi di caff因[n]tutti belli allineati. Un lieve[n]aroma di caff因 profuma l'aria...[n][w][e]
[s]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s]Ce ne sono anche degli altri[n]di cui ignoro il nome...[n][w][e]
[s]Mi ricordo di quando Sojiro[n]mi ha istruito sul caff因.[n][w][e]

[msg MSG_COFFEE_OSIMAI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Quante variet稲 di caff因...[n][w][e]

[msg MND_COFFEE_OSIMAI]
[s]Penso di aver scoperto alcuni[n]segreti del gusto ricco[n]del caff因...[n][w][e]

[msg COFFEE_MENU]
[s]Conoscenza chicchi di caff因[n][e]

[sel COFFEE_SEL top]
[s]Giamaica Blue Mountain[e]
[s]Guatemala SHB[e]
[s]Colombia Nari隠o[e]
[s]Cuba Crystal Mountain[e]
[s]Hawaii Kona[e]
[s]Etiopia Moka Harrar[e]
[s]Moka Matari[e]
[s]Mexico Altura[e]
[s]Brasile N° 2/18[e]
[s]Colombia Bucaramanga Supremo[e]
[s]Costa Rica SHB[e]
[s]Kenya AA[e]
[s]Brasile Bourbon[e]
[s]Colombia 100% Typica[e]
[s]Honduras SHG[e]
[s]Guatemala Antigua[e]
[s]Salvador Pacamara[e]
[s]Panama Esmeralda Geisha[e]
[s]Indonesia Kopi Luwak[e]

[msg SYS_050_1_0 [Giamaica Blue Mountain]]
[s][vp 8 2 65535 0 0 0]Le Blue Mountains della Giamaica, con il loro[n]clima unico e il suolo vulcanico, sono[n]l'ideale per la coltivazione di questo caff因.[n][w][e]
[s][vp 8 2 65535 0 0 0]Raccolto in piccole quantit稲 e sottoposto[n]a controlli rigorosissimi, il risultato 因[n]un caff因 di alta qualit稲 e dall'aroma pieno.[n][w][e]

[msg SYS_051_1_0 [Guatemala SHB]]
[s][vp 8 2 65535 0 0 0]Il suolo vulcanico del Guatemala 因 l'ideale[n]per il caff因. I chicchi vengono classificati[n]in base all'altitudine delle coltivazioni.[n][w][e]
[s][vp 8 2 65535 0 0 0]I chicchi SHB (Strictly Hard Bean), che[n]crescono a oltre 1.300 metri, hanno[n]un'acidit稲 simile a quella degli agrumi.[n][w][e]

[msg SYS_052_1_0 [Colombia Nari隠o]]
[s][vp 8 2 65535 0 0 0]L'alta quota, il clima piovoso e il suolo[n]delle montagne colombiane sono la ricetta[n]ideale per un caff因 di alta qualit稲.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il caff因 Nari隠o ha un corpo denso[n]e cremoso, che avvolge il palato[n]con aromi fruttati e sentori di nocciola.[n][w][e]

[msg SYS_053_1_0 [Cuba Crystal Mountain]]
[s][vp 8 2 65535 0 0 0]Cuba 因 l'isola pi迂 grande dei Caraibi.[n]Il caff因 cubano 因 noto per il suo[n]aroma e il gusto corposo.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il Crystal Mountain viene prodotto usando[n]solo i chicchi pi迂 grandi. Ha un sapore[n]dolce, poco acido e con sentori di nocciola.[n][w][e]

[msg SYS_054_1_0 [Hawaii Kona]]
[s][vp 8 2 65535 0 0 0]Una specialit稲 hawaiana. A causa della rarit稲[n]e del prezzo dei chicchi Kona, una miscela[n]Kona contiene tali chicchi solo per il 10%.[n][w][e]
[s][vp 8 2 65535 0 0 0]Un Kona 100% pu韻 raggiungere prezzi piuttosto[n]elevati. Un buon Kona ha un sapore ricco,[n]una spiccata acidit稲 e un aroma complesso.[n][w][e]

[msg SYS_055_1_0 [Etiopia Moka Harrar]]
[s][vp 8 2 65535 0 0 0]Mokha 因 una citt稲 portuale dello Yemen[n]dalla quale vengono esportati sia il caff因[n]yemenita che l'Etiopia Moka Harrar.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il caff因 di questa regione 因 stato[n]soprannominato "Moka". Ha un sapore speziato[n]e un forte aroma con sentori di mora.[n][w][e]

[msg SYS_056_1_0 [Moka Matari]]
[s][vp 8 2 65535 0 0 0]Mokha 因 una citt稲 portuale dello Yemen[n]dalla quale vengono esportati sia il caff因[n]yemenita che l'Etiopia Moka Harrar.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il Moka Matari ha un profilo gustativo[n]complesso. 為 speziato, presenta sentori[n]di cioccolato e toni quasi "vinosi".[n][w][e]

[msg SYS_057_1_0 [Mexico Altura]]
[s][vp 8 2 65535 0 0 0]Si dice che il caff因 giunse in Messico nel '700[n]grazie agli spagnoli. Oggi il Messico 因 uno[n]dei pi迂 grandi produttori al mondo di caff因.[n][w][e]
[s][vp 8 2 65535 0 0 0]Altura ("altezza" in spagnolo) sta a indicare[n]l'altitudine alla quale crescono i chicchi di[n]questo caff因 dai toni aciduli e di nocciola.[n][w][e]

[msg SYS_058_1_0 [Brasile N° 2/18]]
[s][vp 8 2 65535 0 0 0]Il Brasile 因 il pi迂 grande produttore di caff因[n]al mondo. I chicchi brasiliani sono di alta[n]qualit稲, amari e acidi al punto giusto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Noto anche come Santos, il N° 2/18 因 uno dei[n]caff因 brasiliani pi迂 apprezzati. Il 2 indica[n]la qualit稲, il 18 le dimensioni del chicco.[n][w][e]

[msg SYS_059_1_0 [Colombia Bucaramanga Supremo]]
[s][vp 8 2 65535 0 0 0]L'alta quota, il clima piovoso e il suolo[n]delle montagne colombiane sono la ricetta[n]ideale per un caff因 di alta qualit稲.[n][w][e]
[s][vp 8 2 65535 0 0 0]"Supremo" sta per le dimensioni del chicco,[n]mentre "Bucamaranga" indica la provenienza.[n]Ha un sapore dolce e un'acidit稲 moderata.[n][w][e]

[msg SYS_060_1_0 [Costa Rica SHB]]
[s][vp 8 2 65535 0 0 0]La Costa Rica, paese dotato di immense[n]ricchezze naturali, da secoli esporta[n]caff因 in tutto il mondo.[n][w][e]
[s][vp 8 2 65535 0 0 0]SHB 因 una classificazione attribuita ai caff因[n]che crescono a circa 1300 metri d'altezza.[n]為 un caff因 dolce e dal retrogusto raffinato.[n][w][e]

[msg SYS_061_1_0 [Kenya AA]]
[s][vp 8 2 65535 0 0 0]Le piantagioni di caff因 del Kenya sono[n]sottoposte a rigorosi controlli, e sono note[n]per i loro chicchi di altissima qualit稲.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il Kenya AA 因 coltivato ad altitudini elevate.[n]La sigla AA sta a indicarne la qualit稲.[n]Ha un aroma pieno e un'acidit稲 moderata.[n][w][e]

[msg SYS_062_1_0 [Brasile Bourbon]]
[s][vp 8 2 65535 0 0 0]Il Brasile 因 il pi迂 grande produttore di caff因[n]al mondo. I chicchi brasiliani sono di alta[n]qualit稲, amari e acidi al punto giusto.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il Brasile Bourbon 因 un caff因 raro, poich姻[n]viene prodotto solo in piccole quantit稲.[n]為 dolce e ha una nota finale molto pulita.[n][w][e]

[msg SYS_063_1_0 [Colombia 100% Typica]]
[s][vp 8 2 65535 0 0 0]L'alta quota, il clima piovoso e il suolo[n]delle montagne colombiane sono la ricetta[n]ideale per un caff因 di alta qualit稲.[n][w][e]
[s][vp 8 2 65535 0 0 0]Questo caff因 因 prodotto a partire da chicchi[n]100% Typica ed 因 molto raro, ma regala[n]una freschezza agrumata e un aroma fragrante.[n][w][e]

[msg SYS_064_1_0 [Honduras SHG]]
[s][vp 8 2 65535 0 0 0]L'Honduras 因 un paese prevalentemente montuoso.[n]La classificazione del suo caff因 因 determinata[n]dall'altitudine alla quale viene coltivato.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il caff因 SHG (Strictly High Grown), come l'SHB,[n]cresce ad altezze elevate. Ha un aroma[n]ricco, fruttato, e una delicata acidit稲.[n][w][e]

[msg SYS_065_1_0 [Guatemala Antigua]]
[s][vp 8 2 65535 0 0 0]Il suolo vulcanico del Guatemala 因 l'ideale[n]per il caff因. I chicchi vengono classificati[n]in base all'altitudine delle coltivazioni.[n][w][e]
[s][vp 8 2 65535 0 0 0]A causa dei minerali e delle sostanze presenti[n]nel suolo, il caff因 di Antigua ha una[n]delicata acidit稲 e un retrogusto fresco.[n][w][e]

[msg SYS_066_1_0 [Salvador Pacamara]]
[s][vp 8 2 65535 0 0 0]Oggi, il caff因 costituisce pi迂 del 50% delle[n]esportazioni di El Salvador. Il suo Pacamara[n]因 un caff因 ibrido specifico di questa regione.[n][w][e]
[s][vp 8 2 65535 0 0 0]Il Pacamara 因 ricavato da una pianta ibrida[n]che produce chicchi di grosse dimensioni.[n]Ha un corpo denso, con note di cioccolato.[n][w][e]

[msg SYS_067_1_0 [Panama Esmeralda Geisha]]
[s][vp 8 2 65535 0 0 0]Questa variet稲 molto ricercata detiene[n]il record per il pi迂 alto prezzo d'asta[n]all'International Coffee Auction di Panama.[n][w][e]
[s][vp 8 2 65535 0 0 0]為 un caff因 molto apprezzato ma molto raro,[n]a causa della coltivazione limitata.[n]Ha un aroma floreale e un retrogusto dolce.[n][w][e]

[msg SYS_068_1_0 [Indonesia Kopi Luwak]]
[s][vp 8 2 65535 0 0 0]Questo caff因 raro viene prodotto a partire[n]da bacche di caff因 che hanno attraversato[n]il tratto digestivo dello zibetto asiatico.[n][w][e]
[s][vp 8 2 65535 0 0 0]Nonostante sia molto costoso, si dice che il Kopi Luwak[n]abbia un aroma pieno e un gusto ricco,[n]grazie agli enzimi digestivi dello zibetto.[n][w][e]

[msg MND_SayuriPicture]
[s]為 quel famoso ritratto,[n]la "Sayuri"...[n][w][e]
[s]Quest'opera trasmette un[n]profondo amore materno...[n][w][e]

[msg MSG_SayuriPicture [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]La "Sayuri", eh?[n][w][e]
[s][f 4 10 65535 0 0]Riesco a percepirne chiaramente[n]dolcezza e gentilezza.[n]Le madri sono davvero forti.[n][w][e]

[msg STOP_OUTDOOR_DEFAULT_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Per oggi 因 meglio andare[n]a letto, OK?[n][w][e]

[msg STOP_OUTDOOR_DEFAULT]
[s]Dovrei andare a letto...[n][w][e]

[msg STOP_OUTDOOR_0410]
[s]為 gi稲 tardi...[n]Non dovrei uscire a quest'ora.[n][w][e]

[msg MSG_CHK_DOOR_playroom [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Vuoi uscire anche se i tuoi[n]amici sono qui?[n][w][e]
[s][f 4 10 65535 0 0]Se lo farai, se ne andranno,[n]ma... 為 quello che vuoi?[n][w][e]

[sel SEL_CHK_DOOR_pc_playroom top]
[s]Esco.[e]
[s]Resto a casa.[e]

[msg MSG_CHK_DOOR_ryuji_react [Ryuji]]
[s]Colpa mia. Beh, ci[n]vediamo domani.[n][w][e]

[msg MSG_CHK_DOOR_anne_reacti [Ann]]
[s]Scusa se mi sono presentata[n]cos淫 all'improvviso.[n]Ci vediamo pi迂 tardi.[n][w][e]

[msg MSG_CHK_DOOR_makoto_reac [Makoto]]
[s]Ah, che peccato.[n]Ci vediamo domani.[n][w][e]

[msg MSG_CHK_DOOR_yusuke_reac [Yusuke]]
[s]Capisco. Scusa per il disturbo.[n]Ti prego di perdonarmi.[n][w][e]

[msg MSG_CHK_DOOR_akechi_reac [Akechi]]
[s]Perdonami se ti ho disturbato.[n]Torner韻 un'altra volta.[n][w][e]

[msg MSG_CHK_DOOR_futaba_reac [Futaba]]
[s]*sigh* E va beeene. Ufffff...[n]Mi sa che me ne torno a casa.[n][w][e]

[msg MSG_CHK_DOOR_haru_reacti [Haru]]
[s]OK, ho capito.[n]Ci vediamo presto, allora.[n][w][e]

[msg MSG_STANDBY_MORU_DOOR_No [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Il colpo 因 per domani! Facciamo[n]con calma ed evitiamo di uscire.[n][w][e]

[msg MSG_GO_DUNGEON_TODAY_MOR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oggi non sei stanco?[n]Evitiamo di uscire.[n][w][e]

[msg MND_GO_DUNGEON_TODAY]
[s]Oggi sono un po' stanco.[n]Mi conviene prendermela con calma[n]e restare nella mia stanza...[n][w][e]

[msg MSG_GO_DUNGEON_TODAY_MOR_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Dobbiamo pensare a domani.[n]Potremo uscire un'altra volta.[n][w][e]

[msg MND_GO_DUNGEON_TODAY_V2]
[s]Devo pensare a domani...[n][w][e]
[s]Meglio non uscire oggi...[n][w][e]

[msg MSG_STOP_GO_OUT_0501 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_0503 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Domani dobbiamo assolutamente[n]andare a vendere quella cosa,[n]resta a casa e rilassati stasera.[n][w][e]

[msg MSG_STOP_GO_OUT_0504 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Domani c'因 la festa, vero?[n]Resta a casa a riposarti stasera.[n][w][e]

[msg MSG_STOP_GO_OUT_0505 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Miaohohoh... Delizioso.[n]Sono sazio.[n][w][e]
[s][vp 1 0 0 0 0 0]Stasera dovremmo rilassarci.[n]Da domani, inizieremo a operare[n]come [group].[n][w][e]

[msg MSG_STOP_GO_OUT_0507 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Sarai distrutto dopo tutto quello[n]che hai fatto oggi.[n]Rimandiamo l'uscita per oggi.[n][w][e]

[msg MSG_STOP_GO_OUT_0604 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_0619 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Devi essere stanco dopo la visita[n]al Metaverso. Ammiro la tua tenacia,[n]ma per oggi fermiamoci.[n][w][e]

[msg MSG_STOP_GO_OUT_0620 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]La visita al Palazzo mi ha[n]distrutto. Per oggi basta attivit稲.[n][w][e]

[msg MSG_STOP_GO_OUT_0708 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_0710 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53114 65535 0]Miaaao... Ottimo lavoro oggi.[n]Si 因 fatto tardi, meglio restare[n]a casa per stasera...[n][w][e]

[msg MSG_STOP_GO_OUT_0820 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_1007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_1011 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ehi, resta qui. Hai davvero[n]intenzione di uscire?[n][w][e]

[msg MSG_STOP_GO_OUT_1012_101 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non avevamo detto di tenere[n]un basso profilo? 為 meglio se[n]non usciamo...[n][w][e]

[msg MSG_STOP_GO_OUT_1020_102 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Se la squadra investigativa ti[n]nota, siamo spacciati. Meglio non[n]andare in giro di notte.[n][w][e]

[msg MSG_STOP_GO_OUT_1120 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_1217 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ti ricordi quello che dovrai[n]fare domani, giusto? Rilassati[n]e vai a dormire.[n][w][e]

[msg MSG_STOP_GO_OUT_01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Fai attenzione, l稲 fuori.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Anche se dubito che qualcuno[n]stia cercando una persona[n]che 因 data per morta.[n][w][e]

[msg MSG_STOP_GO_OUT_02 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Vedi di non fare troppo tardi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Anche se dubito che qualcuno[n]stia cercando una persona[n]che 因 data per morta.[n][w][e]

[msg MSG_STOP_GO_OUT_03 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Cerca di non cacciarti[n]in qualche guaio, d'accordo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Anche se dubito che qualcuno[n]stia cercando una persona[n]che 因 data per morta.[n][w][e]

[msg MSG_NIGHTWALK_NG [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Fermo l淫, chi ti ha dato il[n]permesso di uscire?[n][w][e]

[msg MSG_NIGHT_RESTRICTION [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Sono io che devo chiudere la[n]porta. Cerca di non stare fuori[n]fino a tardi, d'accordo?[n][w][e]

[msg MSG_0506_0604_0 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Ehi, vedi di non farti trascinare[n]nei guai, d'accordo?[n][w][e]

[msg MSG_0506_0604_1 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5081 65535 0]Cerca di tenerti alla larga[n]dai luoghi pericolosi, va bene?[n][w][e]

[msg MSG_0506_0604_2 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5106 65535 0]Sei ancora in libert稲 vigilata.[n]Vedi di non scordartelo.[n][w][e]

[msg MSG_DUNGEON_SENTOU_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sei stanco? Se proprio devi[n]uscire, limitati al bagno pubblico.[n][w][e]

[msg MND_DUNGEON_SENTOU]
[s]Oggi sono stanco. Dovrei rinunciare[n]a uscire.[n][w][e]
[s]Magari andr韻 al bagno pubblico[n]per chiudere la giornata...[n][w][e]

[msg MSG_EVENT_SENTOU_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ricordati di domani. Se proprio[n]devi uscire, limitati al bagno[n]pubblico.[n][w][e]

[msg MND_EVENT_SENTOU]
[s]Devo pensare a domani...[n]Meglio non allontanarmi troppo.[n][w][e]
[s]Magari andr韻 al bagno pubblico[n]per chiudere la giornata...[n][w][e]

[sel SEL_LEBLANC_SENTOU top]
[s]Vai al bagno pubblico[e]
[s]Pensaci su[e]

[msg MND_Sentou_ParamUpInfo]
[s]Penso di poter migliorare ancora[n]un po' il mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_Sentou_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MSG_LEBLANC_SENTOU_NoMon [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Aspetta, non puoi andare al[n]bagno pubblico con quella miseria[n]che hai nel portafoglio.[n][w][e]

[msg MND_LEBLANC_SENTOU_NoMon]
[s]A quanto pare non ho[n]abbastanza soldi.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_SENT]
[s]Ora puoi viaggiare velocemente[n]verso il [clr 6]bagno pubblico[clr 0][n]di Yongen-Jaya.[n][w][e]

[msg MSG_LEBLANC_SENTOU_LAST [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Credo che servano 500 yen[n]per partecipare.[n][w][e]

[msg fev0410_05_EXIT_NG_mes01]
[s][vp 1 0 0 0 0 0]La strada qua fuori[n]sembra molto animata...[n][w][e]
[s][vp 1 0 0 0 0 0]Probabilmente, per ora dovrei[n]rispondere al telefono...[n][w][e]

[msg fev0410_05_EXIT_NG_mes02]
[s][vp 1 0 0 0 0 0]La strada qua fuori[n]sembra molto animata...[n][w][e]
[s][vp 1 0 0 0 0 0]Domani dovr韻 alzarmi presto,[n]sarebbe meglio non uscire[n]per il resto della giornata...[n][w][e]

[msg MSG_GO_OUTSIDE_000 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Oh, gira il cartello di fuori su[n]"Aperto".[n][w][e]

[sel SEL_GO_OUTSIDE_001 top]
[s]D'accordo, capito.[e]
[s]Perch姻 dovrei?[e]
[s]Siamo gi稲 aperti?[e]

[msg MSG_GO_OUTSIDE_010 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Non dimenticare di farlo,[n]d'accordo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Ora datti una mossa.[n]Se ti smarrisci farai tardi,[n]ragazzo di campagna.[n][w][e]

[msg MSG_GO_OUTSIDE_011 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Proprio non capisci, eh?[n]Finch姻 vivi qui,[n]fa parte dei tuoi doveri.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 15 65535 0]Ora datti una mossa.[n]Se ti smarrisci farai tardi,[n]ragazzo di campagna.[n][w][e]

[msg MSG_GO_OUTSIDE_012 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]Di gi稲...?[n]Siamo in ritardo, semmai.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Ora datti una mossa.[n]Se ti smarrisci farai tardi,[n]ragazzo di campagna.[n][w][e]

[msg MSG_GO_OUTSIDE_127101_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gira il cartello sulla porta[n]d'ingresso del locale.[n]Fa parte del tuo lavoro.[n][w][e]

[sel SEL_GO_OUTSIDE_127101_00 top]
[s]S淫, lo so.[e]
[s]Il mio lavoro?[e]

[msg MSG_GO_OUTSIDE_127101_00_2 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Va bene.[n][w][e]

[msg MSG_GO_OUTSIDE_127101_00_3 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]S淫, proprio cos淫.[n]Ma non aspettarti[n]che ti paghi.[n][w][e]

[msg MSG_E22810100_NG_GOOUT [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]Mmm? Dove vai?[n]I tuoi amici sono andati[n]a comprare qualcosa.[n][w][e]

[msg MSG_0415_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Siamo gi稲 arrivati?[n][w][e]

[msg MSG_0415_01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]Hai sentito? Sembrava un gatto.[n][w][e]

[sel SEL_0415 top]
[s]Non ho sentito nulla.[e]
[s]Te lo sei immaginato.[e]
[s]Veniva da fuori.[e]

[msg MSG_0415_02 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Beh, non fa niente.[n]Suppongo non ci sia nulla, ma...[n][w][e]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 5099 65535 0]Sai, a volte i gatti[n]entrano nel locale e[n]non ce ne accorgiamo, quindi...[n][w][e]

[msg MSG_0415_03 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ehi, non metterti a dare da[n]mangiare ai gatti randagi, capito?[n]Darai fastidio al vicinato.[n][w][e]

[msg MSG_E40110100_TALK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, dove stai andando?[n]Vieni qui e dimmi[n]che ne pensi.[n][w][e]

[msg EX_FREEZER_0410_mes00]
[s][vp 1 0 0 0 0 0]Gli ingredienti del locale[n]sono conservati qui. Non dovrei[n]usarli senza chiedere...[n][w][e]

[msg MSG_E10920200_CHK_Freeze [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]...AHEM.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Chiudilo subito.[n]Non voglio che qualcosa[n]vada a male.[n][w][e]

[msg MSG_E12710100_CHK_Freeze [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]...AHEM.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Chiudilo subito.[n]Non voglio che qualcosa[n]vada a male.[n][w][e]

[msg MSG_E22810100_CHK_Freeze [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]...Ehi. Se dovessi prendere[n]del cibo da l淫, sar稲 meglio[n]che lo paghi.[n][w][e]

[msg MSG_E22810100_CHK_Freeze_2 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]...Ehi. Non ti servir稲[n]una pentola per quello?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E se dovessi prendere[n]del cibo da l淫, sar稲 meglio[n]che lo paghi.[n][w][e]

[msg MND_COMMON_CHK_Freezer_0]
[s][vp 1 0 0 0 0 0]Pare che qui vengano conservati[n]gli ingredienti del locale...[n][w][e]

[msg MSG_E10920200_CHK_Kitche [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MSG_E12710100_CHK_Kitche [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MND_E22810100_CHK_Kitche]
[s][vp 1 0 0 0 0 0]Qui sono rimaste solo[n]macchinette del caff因...[n][w][e]

[msg MND_COMMON_CHK_Kitchen_0]
[s][vp 1 0 0 0 0 0]Qui ci sono alcune[n]macchinette del caff因...[n][w][e]

[msg MSG_E10530200_CHK_Phone_]
[s][vp 1 0 0 0 0 0]Chiss稲 se ci sono clienti[n]che utilizzano questo[n]telefono pubblico...[n][w][e]

[msg MSG_E10920200_CHK_Phone_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MSG_E12710100_CHK_Phone_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MND_E22810100_CHK_Phone_]
[s][vp 1 0 0 0 0 0]Dovrei pensare a trovare[n]una pentola...[n][w][e]

[msg MND_COMMON_CHK_Phone_000]
[s][vp 1 0 0 0 0 0]Adesso non ho tempo[n]per questo...[n][w][e]

[msg MSG_E10530200_CHK_Counte]
[s][vp 1 0 0 0 0 0]Qui ci sono dei vecchi[n]libri tascabili...[n][w][e]

[msg MSG_E10920200_CHK_Counte [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MSG_E12710100_CHK_Counte [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MND_E22810100_CHK_Counte]
[s][vp 1 0 0 0 0 0]Sar稲 meglio preparare la pentola...[n][w][e]

[msg MND_COMMON_CHK_Counter_0]
[s][vp 1 0 0 0 0 0]Sul bancone c'因 un libro[n]dall'aspetto consunto...[n][w][e]

[msg MSG_E10530200_CHK_Table_]
[s][vp 1 0 0 0 0 0]La superficie di questo tavolo[n]因 stata pulita attentamente...[n][w][e]

[msg MSG_E10920200_CHK_Table_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MSG_E12710100_CHK_Table_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MND_E22810100_CHK_Table_]
[s][vp 1 0 0 0 0 0]Sar稲 meglio preparare la pentola...[n][w][e]

[msg MND_COMMON_CHK_Table_000]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg MSG_E10530200_Table_Fron]
[s][vp 1 0 0 0 0 0]Il divano del locale 因 stato[n]pulito a fondo...[n][w][e]

[msg MSG_E12710100_Table_Fron [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]...Che stai facendo?[n]Sbrigati ad andare a scuola.[n][w][e]

[msg MND_E22810100_Table_Fron]
[s][vp 1 0 0 0 0 0]Sar稲 meglio preparare la pentola...[n][w][e]

[msg MND_E14620000_Table_Fron]
[s][vp 1 0 0 0 0 0]C'因 un cliente nel Leblanc...[n][w][e]

[msg MND_COMMON_Table_Front_0]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi...[n][w][e]

[msg MND_E10920200_CHK_Kitche]
[s][vp 1 0 0 0 0 0]Qui c'因 un grosso tegame[n]di curry. Sembra essere la[n]specialit稲 della casa...[n][w][e]

[msg MSG_E10920200_CHK_Kitche_2 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5150 65535 0]...Che stai facendo?[n]Non toccare le cose destinate[n]ai clienti, intesi?[n][w][e]

[msg MND_E12710100_CHK_Kitche]
[s][vp 1 0 0 0 0 0]Qui c'因 un grosso tegame[n]di curry. Sembra essere la[n]specialit稲 della casa...[n][w][e]

[msg MSG_E12710100_CHK_Kitche_2 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5150 65535 0]...Che stai facendo?[n]Non toccare le cose destinate[n]ai clienti, intesi?[n][w][e]

[msg MND_E22810100_CHK_Kitche_2]
[s][vp 1 0 0 0 0 0]Qui c'因 un grosso tegame[n]di curry. Sembra essere la[n]specialit稲 della casa...[n][w][e]

[msg MND_COMMON_CHK_KitchenCu]
[s][vp 1 0 0 0 0 0]Qui c'因 un grosso tegame di curry.[n]Forse 因 in preparazione[n]per essere servito domani...[n][w][e]

[msg MND_E22810100_CrossWord_]
[s][vp 1 0 0 0 0 0]Sar稲 meglio preparare la pentola...[n][w][e]

[msg MND_COMMON_CrossWord_000]
[s][vp 1 0 0 0 0 0]La superficie di questo tavolo[n]因 stata pulita attentamente...[n][w][e]

[msg MSG_GOTO_OUT_NG_PLAY_OK [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ehi, non uscire. Sbrigati a salire[n]di sopra e vattene a letto.[n][w][e]

[msg MSG_GOTO_OUT_NG_0416 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ehi, dove pensi di andare?[n]Non ti ho gi稲 detto di[n]andare di sopra?[n][w][e]

[msg fev0410_05_STEP_mes01]
[s][vp 1 0 0 0 0 0]Probabilmente dovrei rispondere[n]al telefono...[n][w][e]

[msg fev0410_05_STEP_mes02]
[s][vp 1 0 0 0 0 0]Potrebbe essere una buona idea[n]fare quello che ha chiesto...[n][w][e]

[msg fev0410_05_STEP_mes03]
[s][vp 1 0 0 0 0 0]Dovrei girare il cartello[n]all'ingresso.[n][w][e]

[msg fev0410_06_mes01 [Voce maschile]]
[s][vp 8 0 1 1 65535 0]Ehi, sono io.[n][w][e]

[sel fev0410_06_Q01_SEL top]
[s]Chi parla?[e]
[s]為 uno scherzo telefonico?[e]

[msg fev0410_06_A_mes01 [Sojiro]]
[s][bup 0 103 602 0 1][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Uff, hai gi稲 dimenticato[n]la mia voce? Sono Sakura.[n][w][e]

[msg fev0410_06_B_mes01 [Sojiro]]
[s][bup 0 103 603 0 1][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Sul serio hai gi稲 dimenticato[n]la mia voce? Sono Sakura.[n][w][e]

[msg fev0410_06_mes02 [Sojiro]]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Comunque... Ho chiuso il[n]locale, ma andando via ho scordato[n]di girare il cartello su "Chiuso".[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Non ho assolutamente voglia di[n]tornare solo per quello.[n]Potresti farlo per me?[n][w][e]

[sel fev0410_06_Q02_SEL top]
[s]D'accordo, capito.[e]
[s]Non ne ho voglia.[e]
[s]E chiami qui?[e]

[msg fev0410_06_A_mes02 [Sojiro]]
[s][bup 0 103 601 0 1][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Dubito che arriveranno[n]dei clienti, anche con[n]il cartello che dice "Aperto".[n][w][e]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]E devo ammettere che...[n]因 un vero sollievo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]為 mia regola non salvare[n]sul telefono i numeri dei ragazzi.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Sono contento[n]che tu abbia risposto.[n][w][e]

[msg fev0410_06_B_mes02 [Sojiro]]
[s][bup 0 103 602 0 1][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Ehi, cerca di capire la situazione.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]So che hai parecchie cose per[n]la testa, ma ora che dormi qui[n]devi darmi ascolto.[n][w][e]

[msg fev0410_06_C_mes02 [Sojiro]]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]為 mia regola non salvare[n]sul telefono i numeri dei ragazzi.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Comunque, sono contento[n]che tu abbia risposto.[n][w][e]

[msg fev0410_06_mes03 [Sojiro]]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]A ogni modo, lascio a te il compito[n]di girare il [clr 2]cartello del locale[clr 27].[n][w][e]

[msg fev0410_06_mes04]
[s][vp 1 0 0 0 0 0]Vuole che giri il cartello[n]sulla porta d'ingresso.[n][w][e]

[msg MSG_NIGHT_LEAVE_MASTER [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sto per uscire.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se non torni a casa[n]abbastanza presto, troverai[n]il locale chiuso.[n][w][e]

[msg MSG_E126101_009_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Oh, ehi. Aspetta un attimo.[n][w][e]

[msg MSG_E126101_010_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sto per andare.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non scordarti di chiudere a chiave[n]la porta e spegnere le luci, OK?[n][w][e]

[msg MSG_E126101_011_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5019 65535 0]...S淫, me ne sto andando.[n][w][e]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 5037 65535 0]Te l'ho detto, 因 un aiutante...[n][w][e]

[msg MSG_E136101_001_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ehi, aspetta.[n][w][e]

[msg MSG_E136101_002_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, me ne torno a casa,[n]per stanotte.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Chiudo il locale.[n]Vedi di non andartene in giro.[n][w][e]

[msg MSG_E14110100_200_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, ehi, hai un minuto?[n][w][e]

[msg MSG_E14110100_201_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hai idea di che cosa[n]vada forte tra le ragazze?[n][w][e]

[sel SEL_E14110100_202_00 top]
[s]Non saprei.[e]
[s]Hai un appuntamento?[e]
[s]Vecchio depravato.[e]

[msg MSG_E14110100_203_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Come pensavo. Non sembri proprio[n]una calamita per le ragazze.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Alle donne piacciono i ragazzi[n]diligenti. Cerca di ricordartelo.[n][w][e]

[msg MSG_E14110100_203_01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, alle donne non[n]piacciono i ficcanaso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non che tu possa saperne qualcosa.[n]Non sembri proprio una[n]calamita per le ragazze.[n][w][e]

[msg MSG_E14110100_203_02 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ehi, non c'因 niente di male.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non che tu possa saperne qualcosa.[n]Non sembri proprio una[n]calamita per le ragazze.[n][w][e]

[msg MSG_E14110100_204_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Beh... me ne vado a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Controlla che tutte le[n]finestre siano chiuse, OK?[n][w][e]

[msg MSG_E146101_001_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ehi, io vado.[n][w][e]

[msg MSG_E146101_002_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Volevo solo ricordarti di non stare[n]in piedi fino a tardi. Capito?[n][w][e]

[msg MSG_E146201_001_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5074 65535 0]Bene, credo che[n]ora andr韻...[n][w][e]

[msg MSG_E146201_002_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Occupati tu[n]di questo posto, d'accordo?[n][w][e]

[msg MSG_E152101_017_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sto uscendo.[n][w][e]

[msg MSG_E152101_017_01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non combinare guai, intesi?[n]Se proprio devi uscire,[n]resta nei dintorni.[n][w][e]

[msg MSG_E152101_GOOUT_00 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5125 65535 0]Ehi, non uscire.[n]Non hai neanche la chiave.[n][w][e]

[msg MSG_E152101_GOOUT_01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sto andando via.[n]Se proprio devi uscire,[n]resta nei dintorni.[n][w][e]

[msg MSG_E401201_00 [Yusuke]]
[s][f 4 23 1 855 3 10 0 10][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][fName]?!?[n][w][e]

[msg MSG_E401201_01 [Ann]]
[s][f 4 23 1 853 14 10 13 10][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Uhm... Sbaglio o 因 appena[n]scappato via di corsa?[n][w][e]

[msg MSG_E401201_02 [Futaba]]
[s][f 4 23 1 850 110 10 0 10][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ugh, tu dovresti essere[n]morto! Non dovresti farti[n]vedere in giro![n][w][e]

[msg MSG_E401201_03 [Ryuji]]
[s][f 4 23 1 852 14 10 13 10][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Inseguiamolo![n][w][e]

[msg MSG_E401201_04 [Makoto]]
[s][f 4 23 1 851 14 10 13 10][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sarebbe meglio non andare tutti.[n]Qualcuno dovrebbe aspettare qui.[n][w][e]

[msg MSG_E401201_05 [Haru]]
[s][f 4 23 1 854 14 10 13 10][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vado anch'io![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non preoccuparti.[n]Prometto che non[n]far韻 sciocchezze.[n][w][e]

[msg MSG_E401201_06 [Morgana]]
[s][f 4 23 1 857 3 10 0 10][bup 0 3 0 0 0][f 4 10 0 0 0][vp 8 2 1 0 65535 0]Allora 因 deciso. Vengo con voi.  [n][w][e]
[s][f 4 10 0 0 0][vp 8 2 1 0 65535 0]Allora, siamo pronti ad andare?[n][w][e]

[msg MND_C14_INIT_01_00]
[s]為 il telefono pubblico.[n][w][e]
[s]Chiamo il servizio di[n]maid a domicilio?[n][w][e]

[msg MND_C14_INIT_01_01]
[s]......[n][w][e]
[s]Tuttavia, il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]因 attualmente insufficiente...[n][w][e]
[s]Non riuscir韻 a chiamare dal[n]Leblanc finch姻 non avr韻 abbastanza[n][stIcon 3][clr 26][stLabel 3][clr 27] da essere [clr 26][stLvLabel 3 3][clr 27].[n][w][e]

[msg MND_C14_INIT_01_02]
[s]Posso chiamare quando voglio,[n]visto che sono pieno[n]di [stIcon 3][clr 26][stLabel 3][clr 27]![n][w][e]

[msg MSG_C14_INIT_01_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Pensavi di chiamare una maid?[n]Beh, se usi questo non lascerai[n]tracce nel registro delle chiamate![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]為 per il bene dei[n]Ladri Fantasma... vero?[n][w][e]

[sel SEL_C14_INIT_01_00 top]
[s]Certo.[e]
[s]Magari un'altra volta.[e]

[msg MND_C14_INIT_00_00]
[s]為 il telefono pubblico.[n][w][e]
[s]Dovrei provare a chiamare[n]il numero di lavoro di Kawakami...[n][w][e]

[msg MSG_C14_INIT_00_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Vuoi chiamare Kawakami?[n][w][e]

[sel SEL_C14_INIT_00_02 top]
[s]Chiamiamo il servizio.[e]
[s]No, lasciamo stare.[e]

[msg MND_C14_INIT_NG_00]
[s]為 il telefono pubblico.[n][w][e]
[s]Oggi sono stanco,[n]lo user韻 un'altra volta.[n][w][e]

[msg MSG_C14_INIT_NG_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sembri stanco... Beh, dopotutto[n]siamo stati nel Metaverso...[n][w][e]
[s][f 4 10 65535 0 0]Puoi chiamare Kawakami per farle[n]fare le faccende di casa. Ma prima[n]scegli che incarico assegnarle![n][w][e]

[msg MSG_C14_INIT_NG_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, hai gi稲 chiesto a[n]Kawakami di venire oggi.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Se hai un'altra richiesta,[n]falla un'altra volta.[n][w][e]

[msg MND_C14_INIT_NG_03]
[s]Adesso ho cose pi迂[n]importanti da fare.[n]Chiamer韻 un'altra volta.[n][w][e]

[msg MSG_C14_INIT_NG_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non hai altre cose da fare?[n]Chiama un'altra volta.[n][w][e]

[msg MSG_C14_INIT_NG_04 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Sembri stanco... Beh, dopotutto[n]siamo stati nel Metaverso...[n][w][e]

[msg MSG_C14_PRECOOP_00_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky...[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Oh, aspetta, sei tu.[n][w][e]
[s][f 4 10 65535 0 0]Beh, fanno 5.000, richiesta[n]inclusa. Va bene per te?[n][w][e]

[sel SEL_C14_PRECOOP_00_01 top]
[s]Certo.[e]
[s]Magari la prossima volta.[e]

[msg MSG_C14_PRECOOP_00_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15153 65535 0]Molto bene.[n][w][e]
[s][f 4 10 65535 0 0]Allora vengo subito[n]da te...[n][w][e]

[msg MSG_C14_PRECOOP_00_03 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Uhm...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15032 65535 0]Mi dispiace, ora sto[n]lavorando, per cui...[n]Chiamami un'altra volta.[n][w][e]

[msg MSG_C14_PRECOOP_NG_00 [Voce di Kawakami]]
[s][vp 8 2 1 15091 65535 0]Mi dispiace, Padrone.[n]Al momento sono in pausa.[n][w][e]
[s]Posso essere la tua maid[n]solo di notte.[n][w][e]
[s]OOOK, aspetter韻 la tua[n]prossima chiamata.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Questa tua chiamata mi sorprende.[n][w][e]
[s][f 4 10 65535 0 0]Probabilmente non lo capisci, ma[n]aiutarti a battere la fiacca[n]in classe non 因 facile.[n][w][e]
[s][f 4 10 65535 0 0]Magari un'altra volta.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Questa tua chiamata mi sorprende.[n][w][e]
[s][f 4 10 65535 0 0]Probabilmente non lo capisci, ma[n]aiutarti a battere la fiacca[n]in classe non 因 facile.[n][w][e]
[s][f 4 10 65535 0 0]Magari un'altra volta.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_3 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Ah, sei tu. Wow,[n]davvero mi stai chiamando?[n][w][e]
[s][f 4 10 65535 0 0]Credevo che fossi talmente[n]occupato da non poter neanche[n]rispondere ai miei messaggi...[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_4 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Ah, sei tu. Wow,[n]davvero mi stai chiamando?[n][w][e]
[s][f 4 10 65535 0 0]Credevo che fossi talmente[n]occupato da non poter neanche[n]rispondere ai miei messaggi...[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, Becky 因 tutta bagnaaata[n]al momento... Aspetta, sei tu.[n][w][e]
[s][f 4 10 65535 0 0]Ugh, che pioggia terribile.[n]Il mio bucato ci metter稲[n]di pi迂 ad asciugarsi...[n][w][e]
[s][f 4 10 65535 0 0]E devo tenere l'asciugatrice accesa[n]dieci minuti in pi迂 del solito... [n][w][e]

[msg MSG_C14_BEGIN_WEATHER_00_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Salve. Oh, [lName]-kun.[n][w][e]
[s][f 4 10 65535 0 0]Ugh, che pioggia terribile.[n]Il mio bucato ci metter稲[n]di pi迂 ad asciugarsi...[n][w][e]
[s][f 4 10 65535 0 0]E devo tenere l'asciugatrice accesa[n]dieci minuti in pi迂 del solito... [n][w][e]

[msg MSG_C14_BEGIN_WEATHER_01 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky, dalla[n]pelle bianca come la ne...[n]Ah, aspetta, sei tu.[n][w][e]
[s][f 4 10 65535 0 0]Nevica raramente in[n]citt稲, vero?[n][w][e]
[s][f 4 10 65535 0 0]Oh, a proposito, spalare la[n]neve non 因 tra i miei servizi.[n]Niente lavori pesanti.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_01_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Salve. Oh, [lName]-kun.[n][w][e]
[s][f 4 10 65535 0 0]Nevica raramente in[n]citt稲, vero?[n][w][e]
[s][f 4 10 65535 0 0]Oh, a proposito, spalare la[n]neve non 因 tra i miei servizi.[n]Niente lavori pesanti.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky. Grazie per[n]aver chiamato in questa giornata[n]di piog... Ah, sei tu.[n][w][e]
[s][f 4 10 65535 0 0]Nei giorni di pioggia[n]ho pochissimi clienti...[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_02_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Salve. Oh, [lName]-kun.[n][w][e]
[s][f 4 10 65535 0 0]Spero che smetta presto di piovere.[n]Il bucato ci mette troppo ad[n]asciugarsi. E sono occupatissima.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_03 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky! Oh, quel[n]tifone 因 cos淫 spav... Ah, sei tu?!?[n][w][e]
[s][f 4 10 65535 0 0]Cio因, se dovessi chiedere di me,[n]verrei anche in un giorno simile.[n]Il lavoro 因 lavoro.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_03_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Salve. Oh, [lName]-kun.[n][w][e]
[s][f 4 10 65535 0 0]Visto che tifone?[n]Spero che passi presto...[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_04 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Bec...[n][w][e]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0]Ecc淫. Oh, cielo. Chiedo[n]scusa, ohohoho![n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Oh, aspetta, sei tu?[n]Fiuuu. Sono salva.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_04_2 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo.[n]Oh, sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0]Ecc淫. Oh, cielo. Chiedo[n]scusa, ohohoho![n][w][e]

[msg MSG_C14_BEGIN_WEATHER_05 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Parla Becky, maid d'assalto.[n]Il tipo di lavoro che facciamo[n]dipende da come... Oh, sei tu.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_05_2 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Pronto? Oh, [lName]-kun.[n]Come stai? Piove a catinelle,[n]vedi di non ammalarti, OK?[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_06 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Parla Beckyyy. Anche nelle notti[n]pi迂 calde, ti aiuter韻 a scaricare[n]lo stress... Ah, sei tu.[n][w][e]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0]Che caldooo.[n]Da te non c'因 l'aria[n]condizionata, vero?[n][w][e]
[s][f 4 10 65535 0 0]Oh, beh. Se dovessi richiedermi,[n]vedr韻 di sopportare.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_06_2 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0]Che caldooo.[n]Da te non c'因 l'aria[n]condizionata, vero?[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_07 [Kawakami]]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Bec... *coff coff*.[n][w][e]
[s][f 4 10 65535 0 0]Scusa, Padrone...[n]Oh, sei solo tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Mi si era incastrato uno[n]snack in gola. Non preoccuparti,[n]non ho l'influenza.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_07_2 [Kawakami]]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n]*coff coff*[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Mi si era incastrato uno[n]snack in gola. Non preoccuparti,[n]non ho l'influenza.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_08 [Kawakami]]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaaao! In una serata cos淫 gelida,[n]Becky pu韻 riscaldarti il cuore...[n]Oh, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]In camera tua fa freddino.[n]Non ammalarti, OK?[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_08_2 [Kawakami]]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Pronto... Oh, [lName]-kun![n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Ti sei coperto bene oggi?[n]Fa parecchio freddo, cerca di[n]non ammalarti, d'accordo?[n][w][e]

[msg MSG_C14_BEGIN_TIME_01 [Kawakami]]
[s][bup 0 109 600 65535 1]Ciaooo, parla Becky![n]Ah, aspetta, sei tu.[n][w][e]

[msg MSG_C14_BEGIN_TIME_01_01 [Kawakami]]
[s][bup 0 109 0 65535 1]Ciaooo, parla Becky![n]Ah, aspetta, sei tu.[n][w][e]

[msg MSG_C14_BEGIN_TIME_02 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky![n]Ah, aspetta, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Stai studiando? Non cominciare[n]a battere la fiacca solo perch姻[n]gli esami sono finiti, OK?[n][w][e]

[msg MSG_C14_BEGIN_TIME_02_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Stai studiando? Non cominciare[n]a battere la fiacca solo perch姻[n]gli esami sono finiti, OK?[n][w][e]

[msg MSG_C14_BEGIN_TIME_03 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Grazie per aver chiamato![n]Sono a tua... Oh, sei solo tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Sai, ho sentito dire che[n]di recente Shibuya 因[n]diventata pi迂 pericolosa.[n][w][e]
[s][f 4 10 65535 0 0]Ricordo che ci passi per andare[n]a scuola, quindi vedi di non[n]trattenertici troppo, OK?[n][w][e]

[msg MSG_C14_BEGIN_TIME_03_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Sai, ho sentito dire che[n]di recente Shibuya 因[n]diventata pi迂 pericolosa.[n][w][e]
[s][f 4 10 65535 0 0]Ricordo che ci passi per andare[n]a scuola, quindi vedi di non[n]trattenertici troppo, OK?[n][w][e]

[msg MSG_C14_BEGIN_TIME_04 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky![n]Ah, aspetta, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Non rilassarti solo perch姻[n]因 estate. Sei ancora un liceale,[n]non metterti a giocare di notte.[n][w][e]
[s][f 4 10 65535 0 0]Un momento, questo 因 giocare[n]di notte? O peggio? Beh, sei sotto[n]la mia supervisione. No problem.[n][w][e]

[msg MSG_C14_BEGIN_TIME_04_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Non rilassarti solo perch姻[n]因 estate. Sei ancora un liceale,[n]non metterti a giocare di notte.[n][w][e]
[s][f 4 10 65535 0 0]Un momento, questo 因 giocare[n]di notte? O peggio? Beh, sei sotto[n]la mia supervisione. No problem.[n][w][e]

[msg MSG_C14_BEGIN_TIME_05 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15089 65535 0]Salve, Padrone.[n]Parla Beckyyy![n]Oh, aspetta, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Senti, metterete mai[n]l'aria condizionata l淫 da voi?[n][w][e]
[s][f 4 10 65535 0 0]Con il costume da maid si soffre il[n]caldo d'estate e il freddo[n]d'inverno. 為 molto scomodo.[n][w][e]

[msg MSG_C14_BEGIN_TIME_05_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Anche se di giorno fa caldo,[n]di notte la temperatura scende.[n]Attento a non ammalarti, OK?[n][w][e]

[msg MSG_C14_BEGIN_TIME_06 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky![n]Ah, aspetta, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Ti sei abituato[n]alla vita di citt稲?[n][w][e]
[s][f 4 10 65535 0 0]Aspetta, sei qui da pi迂 di[n]sei mesi, eh? Come vola[n]il tempo...[n][w][e]

[msg MSG_C14_BEGIN_TIME_06_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Ti sei abituato[n]alla vita di citt稲?[n][w][e]
[s][f 4 10 65535 0 0]Aspetta, sei qui da pi迂 di[n]sei mesi, eh? Come vola[n]il tempo...[n][w][e]

[msg MSG_C14_BEGIN_TIME_07 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo! Sono tutta per te,[n]Padrone! Oh, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Pensano tutti che tu sia gi稲[n]tornato nella tua citt稲, quindi[n]fai attenzione, OK?[n][w][e]
[s][f 4 10 65535 0 0]Se chiedi di me,[n]verr韻 l淫.[n][w][e]

[msg MSG_C14_BEGIN_TIME_07_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Pensano tutti che tu sia gi稲[n]tornato nella tua citt稲, quindi[n]fai attenzione, OK?[n][w][e]
[s][f 4 10 65535 0 0]Se chiedi di me,[n]verr韻 l淫.[n][w][e]

[msg MSG_C14_BEGIN_TIME_08 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15089 65535 0]Parla Becky! Per il mio Padrone[n]arriver韻 in un lam...[n]Ah, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Se chiedi di me, verr韻 di corsa,[n]anche a Natale e Capodanno![n][w][e]

[msg MSG_C14_BEGIN_TIME_08_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Se chiedi di me, verr韻 di corsa,[n]anche a Natale e Capodanno![n][w][e]

[msg MSG_C14_BEGIN_TIME_09 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15089 65535 0]Ciaooo! Sono Becky, Padrone.[n]Sono tutta tua![n]...Oh, sei tu.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Ho pi迂 clienti da quando 因[n]iniziato l'anno nuovo.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Il manager 因 contento, ma[n]mi fa un po' strano...[n][w][e]

[msg MSG_C14_BEGIN_TIME_09_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Pronto? [lName]-kun?[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Non ti sembra che di colpo siano[n]diventati tutti pi迂 felici? Anche[n]a scuola. La cosa mi puzza...[n][w][e]
[s]Ma quando chiedo, mi rispondono[n]che 因 tutto come prima. Mi sto[n]forse immaginando le cose?[n][w][e]

[msg MSG_C14_BEGIN_SECOMD_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky![n]Ah, aspetta, sei tu.[n][w][e]

[msg MSG_C14_BEGIN_SECOMD_00_ [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]

[msg MSG_C14_BIGEN_NG_00_02 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Oh, sei tu?[n][w][e]
[s][f 4 10 65535 0 0]Lavoro solo di [clr 2]venerd淫 e sabato[n]sera[clr 27], dovresti richiedermi[n]in quei giorni.[n][w][e]
[s][vp 8 2 1 15053 65535 0][f 4 10 65535 0 0]Se dovessi finire per[n]lavorare in altri giorni,[n]ti contatter韻. OK, ciaooo.[n][w][e]

[msg MSG_C14_BIGEN_NG_00 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Oh, sei tu?[n][w][e]
[s][f 4 10 65535 0 0]Lavoro solo di [clr 2]venerd淫 e sabato[n]sera[clr 27], dovresti richiedermi[n]in quei giorni.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Beh, se sono solo faccende di casa,[n]magari potrei venire da te[n]e sbrigarle alla svelta...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15053 65535 0][f 4 10 65535 0 0]Oh, ma se dovessi finire per[n]lavorare in altri giorni,[n]ti contatter韻. OK, ciaooo.[n][w][e]

[msg MSG_C14_BIGEN_NG_00_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][f 4 10 65535 0 0]Stavo scrivendo un resoconto. Se[n]hai bisogno di me, potresti[n]richiedermi [clr 2]venerd淫 o sabato sera[clr 27]?[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Oh, se sono solo faccende[n]di casa, posso venire da te[n]e sbrigarle alla svelta.[n][w][e]
[s][vp 8 2 1 15053 65535 0][f 4 10 65535 0 0]Comunque, se mi capiter稲 di[n]lavorare anche durante la[n]settimana, ti contatter韻. OK, ciao.[n][w][e]

[msg MSG_C14_BIGEN_NG_02_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Mi dispiace, Padrone, ma oggi[n]ho l'agenda gi稲 pienaaa.[n][w][e]
[s]Ti prego di chiamare[n]un'altra volta, OK?[n]Ciao ciaooo.[n][w][e]

[msg MSG_C14_BIGEN_NG_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Mi dispiace, Padrone, ma oggi[n]ho l'agenda gi稲 pienaaa.[n][w][e]
[s][f 4 10 65535 0 0]Se si tratta solo di faccende[n]domestiche, posso venire a[n]sbrigarle pi迂 tardi...[n][w][e]
[s][f 4 10 65535 0 0]Per韻, se hai bisogno d'altro,[n]ti prego di chiedere di me[n]un'altra volta. Ciaooo.[n][w][e]

[msg MSG_C14_BIGEN_NG_02_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Ciaooo! Oh, aspetta...[n]Sei tu, [lName]-kun.[n][w][e]
[s][f 4 10 65535 0 0]Se si tratta solo di faccende[n]domestiche, posso venire a[n]sbrigarle pi迂 tardi...[n][w][e]
[s][f 4 10 65535 0 0]Per韻, se hai bisogno d'altro,[n]ti prego di chiedere di me[n]un'altra volta. Ciaooo.[n][w][e]

[msg MSG_C14_BIGEN_NG_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Oh, ancora tu? Scusa, ma[n]adesso sono occupata.[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]Se hai bisogno di me, mettimi in[n]programma per [clr 2]venerd淫 e[n]sabato sera[clr 27]. OK, ciao![n][w][e]

[msg MSG_C14_BIGEN_NG_01_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Oh, ancora tu? Scusa, ma[n]adesso sono occupata.[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]Se hai bisogno di me, mettimi in[n]programma per [clr 2]venerd淫 e[n]sabato sera[clr 27]. OK, ciao![n][w][e]

[msg MSG_C14_CORP_00_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Se chiedi i miei servizi,[n]mi occuper韻 delle tue faccende[n]domestiche per soli 5.000 yen![n][w][e]

[msg MSG_C14_CORP_10_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Grazie per la chiamata.[n][w][e]
[s][f 4 10 65535 0 0]Posso fare qualcosa per te?[n][w][e]

[msg MSG_C14_CORP_10_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Grazie per la chiamata.[n][w][e]
[s][f 4 10 65535 0 0]Oggi posso venire a casa tua?[n][w][e]

[msg MSG_C14_SPOT_01_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15019 65535 0][f 4 10 65535 0 0]Che ne dici di andare[n]da qualche parte[n]come attivit稲 extrascolastica?[n][w][e]
[s][f 4 10 65535 0 0]Decidi tu il posto.[n]Puoi considerarlo il[n]nostro primo incarico.[n][w][e]
[s][f 4 10 65535 0 0]Se posso aiutarti in[n]qualcosa oggi, sar韻 felice[n]di venire l淫. Allora, che ne dici?[n][w][e]

[msg MSG_C14_SPOT_02_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15090 65535 0]Mi piacerebbe uscire a[n]mangiare qualcosa per festeggiare[n]l'uscita dall'ospedale.[n][w][e]
[s][f 4 10 65535 0 0]In un posto che serva[n]alcol e cibo delizioso,[n]ma a prezzi ragionevoli![n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Ma chi voglio prendere in giro?[n]Non posso chiedere una cosa[n]del genere a un ragazzino.[n][w][e]
[s][f 4 10 65535 0 0]Come al solito, verr韻[n]da te per 5.000 yen.[n][w][e]

[msg MSG_C14_SPOT_03_00 [Kawakami]]
[s][bup 0 109 6 65535 1][f 4 10 65535 0 0]Adesso che ci frequentiamo,[n]sarebbe bello andare in un[n]posto speciale...[n][w][e]
[s][f 4 10 65535 0 0]Qualcosa con un bel panorama[n]notturno, noi due da soli...[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15085 65535 0]Ahah, sto chiedendo troppo?[n]Comunque, se hai bisogno[n]di aiuto verr韻 l淫.[n][w][e]

[msg MSG_C14_SPOT_04_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15090 65535 0]Il dottore dell'ospedale ha[n]detto che devo mangiare cibi[n]molto nutrienti...[n][w][e]
[s][f 4 10 65535 0 0]Non ho molti soldi, ma forse andr韻[n]in uno di quegli all-you-can-eat.[n][w][e]
[s][f 4 10 65535 0 0]Beh, ci penser韻 poi.[n]Se hai bisogno di aiuto,[n]posso venire da te.[n][w][e]

[msg MSG_C14_SPOT_05_00 [Kawakami]]
[s][bup 0 109 6 65535 1][f 4 10 65535 0 0][vp 8 2 1 15165 65535 0]Voglio venire da te[n]come tua fidanzata,[n]non come Becky la maid...[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Oh, non 因 niente. Posso[n]aiutarti in qualche modo?[n][w][e]

[msg MSG_C14_SPOT_06_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Volevo informarmi un po' sulle[n]sottoculture, ma mi sono[n]ritrovata in un vicolo cieco...[n][w][e]
[s][f 4 10 65535 0 0]Qualche idea su dove potrei andare[n]per informarmi su certe cose?[n][w][e]
[s][f 4 10 65535 0 0]Sono gi稲 stata ad Akihabara,[n]quindi mi andrebbe bene[n]qualsiasi altro posto.[n][w][e]

[msg MSG_C14_CORP_01_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]I miei servizi ti costeranno[n]5.000 yen, ma stavolta far韻[n]un lavoro sopraffino![n][w][e]

[msg MSG_C14_CORP_02_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Uhm... Padrone, per caso[n]hai fame?[n][w][e]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Ora offriamo servizi speciali come[n]"Maid in cucina" e "Cucina con[n]la maid"! [clr 2][f 1 9 0][clr 27]![n][w][e]
[s][f 4 10 65535 0 0]Il prezzo 因 di 5.000 yen,[n]richiesta inclusa![n]Un affare d'oro![n][w][e]

[msg MSG_C14_CORP_03_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Ti fornir韻 i miei servizi per[n]5.000 yen, richiesta inclusa![n][w][e]
[s][f 4 10 65535 0 0]Perci韻 oggi chiederai di me,[n]vero? Vero...?[n][w][e]

[msg MSG_C14_CORP_04_00 [Kawakami]]
[s][bup 0 109 602 65535 1][f 4 10 65535 0 0]Hai capito cosa ho detto[n]l'ultima volta, vero? E vuoi[n]lo stesso i miei servizi?[n][w][e]

[msg MSG_C14_CORP_05_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Oggi c'因 qualcosa di speciale[n]sul menu, solo per il[n]Padroneee [clr 2][f 1 9 0][clr 27].[n][w][e]
[s][f 4 10 65535 0 0]Lo vuoi per 5.000 yen?[n][w][e]

[msg MSG_C14_CORP_06_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Kawakami non ha risposto.[n]Prova a chiamarla.[n][w][e]

[msg MSG_C14_CORP_06_00 [Voce femminile sconosciuta]]
[s]Salve... Oh, per caso[n]parla [lName]-san?[n][w][e]

[msg MSG_C14_CORP_07_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Devo pulire la tua stanza[n]o vuoi che cucini per te?[n]Offro servizi di ogni genere![n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Ma, uhm... devo parlarti di[n]alcune cose, quindi ti[n]spiacerebbe richiedermi?[n][w][e]

[msg MSG_C14_CORP_08_00 [Voce di Kawakami]]
[s][vp 8 2 1 15002 65535 0]Ciaooo, parla Becky![n]Sono in pausa per un pooo'.[n][w][e]
[s]Spero che richiamerai[n]presto![n][w][e]

[msg MSG_C14_CORP_08_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sembra che oggi Kawakami[n]non ci sia. Ha davvero[n]intenzione di smettere?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Beh, probabilmente sbrigher稲 lo[n]stesso le tue faccende. Dopotutto,[n]avete stretto un accordo.[n][w][e]

[msg MND_C14_CORP_08_02]
[s]Oggi Kawakami non c'因, ma[n]posso chiederle lo stesso di[n]rispettare l'accordo.[n][w][e]
[s]So gi稲 i nomi dei Takase. Dovrei[n]andare nei Memento e[n]risvegliargli il cuore...[n][w][e]

[msg MSG_C14_CORP_08_03 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15019 65535 0]Ehi, ascolta! 為 successa[n]una cosa incredibile...[n][w][e]
[s][f 4 10 65535 0 0]Sono ancora sconvolta.[n]Non so da dove iniziare[n]a spiegare...[n][w][e]
[s][f 4 10 65535 0 0]Ci sono anche altre cose[n]di cui voglio parlarti. Oggi[n]chiederai di me, vero?[n][w][e]

[msg MSG_C14_CORP_09_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15006 65535 0]Tempismo perfetto. C'因 qualcosa[n]di cui voglio parlarti.[n][w][e]
[s][f 4 10 65535 0 0]Non come maid, ma in veste[n]di insegnante. Pi迂 tardi[n]potrei venire al Leblanc?[n][w][e]

[msg MSG_C14_CORP_09_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Grazie della chiamata.[n][w][e]
[s][vp 8 2 1 15193 65535 0][f 4 10 65535 0 0]Anch'io dovevo parlarti[n]di una cosa...[n][w][e]
[s][f 4 10 65535 0 0]Maid, insegnante, non importa[n]in che veste.[n]Posso venire subito da te?[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Sento di potermi avvicinare a[n]Kawakami grazie alla Persona[n][var 2] [clr 1][var 5][clr 27]...[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Sento che presto il mio legame[n]con Kawakami si rafforzer稲...[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]Non penso che il mio legame con[n]Kawakami si rafforzer稲, per ora...[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Ho un solido legame[n]con Kawakami...[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Ho un legame speciale[n]con Kawakami...[n][w][e]

[msg MSG_COOP_CHECK_NIGHT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vuoi far venire qui Kawakami?[n]Ti coster稲 5.000 yen.[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nessuno pensa che tu sia vivo.[n]Se fai attenzione, dovrebbe[n]andare tutto bene.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vuoi far venire qui Kawakami?[n]Ti coster稲 5.000 yen.[n][w][e]

[msg MSG_COOP_CHECK_RANK_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]La voce al telefono non era[n]di Kawakami. Forse dovresti[n]chiedere altri dettagli?[n][w][e]

[msg MSG_COOP_CHECK_RANK_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Hai intenzione di far venire[n]qui Kawakami?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Nessuno pensa che tu sia vivo.[n]Se fai attenzione, dovrebbe[n]andare tutto bene.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Hai intenzione di far venire[n]qui Kawakami?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Chiedile di venire[e]
[s]Verifica legame con Kawakami[e]
[s]Rifiuta[e]

[sel SEL_COOP_CHECK_06 top]
[s]Chi 因?[e]
[s]Verifica legame con Kawakami[e]
[s]Ha sbagliato persona.[e]

[msg MSG_MONEY_NG_MORGANA [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Ehi... hai solo[var 1] yen.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non 因 abbastanza per[n]pagare Kawakami.[n][w][e]

[msg MSG_MONEY_NG [Kawakami]]
[s][bup 0 109 604 65535 1][f 4 10 65535 0 0][vp 8 2 1 15039 65535 0]...Aspetta, hai[n]problemi di soldi?!?[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Beh, richiamami quando avrai[n]messo da parte qualcosa. Ciaooo.[n][w][e]

[msg MSG_C14_YES_01_00 [Kawakami]]
[s][bup 0 109 604 65535 1][f 4 10 65535 0 0][vp 8 2 1 15040 65535 0]Cosa? Vuoi veramente[n]chiedere i miei servizi?!?[n][w][e]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Vengo subito da te...[n][w][e]
[s][f 4 10 65535 0 0]Gradirei che dessi una ripulita[n]prima! Cos淫 agevolerai il mio[n]lavoro! [clr 2][f 1 9 0][clr 27][n][w][e]

[msg MSG_C14_YES_02_00 [Kawakami]]
[s][bup 0 109 604 65535 1][f 4 10 65535 0 0][vp 8 2 1 15040 65535 0]Cosa? Sul serio...?[n][w][e]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]C-Cio因, grazie per[n]aver chiesto di me.[n][w][e]
[s][f 4 10 65535 0 0]Allora ti prego di aspettarmi,[n]Padrone! Spero che tu abbia[n]una fame da lupiii![n][w][e]

[msg MSG_C14_YES_03_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15030 65535 0]Evviva! Ti adoro, Padroneee! [clr 2][f 1 9 0][clr 27][n][w][e]
[s][f 4 10 65535 0 0]OK, sar韻 subito da teee![n][w][e]

[msg MSG_C14_YES_04_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15066 65535 0]D'accordo... credo che dovremo[n]parlarne come si deve.[n][w][e]
[s][f 4 10 65535 0 0]Aspettami l淫.[n][w][e]

[msg MSG_C14_YES_05_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15030 65535 0]Grazie per aver chiesto[n]ancora di meee.[n][w][e]
[s][f 4 10 65535 0 0]Ti prego di aspettare[n]finch姻 non sar韻 l淫![n][w][e]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0]*coff* *coff*[n][w][e]

[msg MSG_C14_YES_06_00 [Infermiera]]
[s]Salve, sono una caposala[n]dell'ospedale di Aoyama.[n]Parlo per conto di Kawakami-san.[n][w][e]
[s]Kawakami-san 因 svenuta[n]ed 因 stata ricoverata[n]nel nostro ospedale.[n][w][e]
[s]Conosce l'indirizzo dell'ospedale?[n]Il numero della stanza 因...[n][w][e]

[msg MSG_C14_YES_06_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Che cosa terribile.[n]Andiamoci subito![n][w][e]

[msg MSG_C14_YES_07_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15060 65535 0]Allora arrivo subitooo.[n]Ti prego di aspettarmi, Padrone![n][w][e]

[msg MSG_C14_YES_08_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15031 65535 0]S淫, immagino che tu abbia[n]ragione...[n][w][e]
[s][f 4 10 65535 0 0]Arrivo subito, aspettami.[n][w][e]

[msg MSG_C14_YES_09_00 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15087 65535 0]Arrivo subito,[n]aspettami l淫.[n][w][e]

[msg MSG_C14_YES_09_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15164 65535 0]OK, vengo subito.[n][w][e]

[msg MSG_C14_YES_00_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15059 65535 0]OK, allora parto subito.[n]Pulisci la tua stanza[n]e aspettami. [clr 2][f 1 9 0][clr 27][n][w][e]

[msg MSG_C14_YES_10_00 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15087 65535 0]OK, vengo subito...[n][w][e]

[msg MSG_C14_YES_10_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15164 65535 0]D'accordo, allora aspettami.[n][w][e]

[msg MND_C14_SPOT_01_01]
[s]Forse dovrei invitarla[n]al museo d'arte...[n][w][e]

[sel SEL_C14_SPOT_01_02 top]
[s]Invitala[e]
[s]Non invitarla[e]

[msg MSG_C14_SPOT_01_03 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Il museo d'arte di Ueno, eh?[n]Potrebbe essere educativo.[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15051 65535 0]Spero che non sia chiuso.[n]Andiamo a vedere.[n][w][e]

[msg MND_C14_SPOT_02_01]
[s]Forse dovrei invitarla a mangiare[n]un monjayaki insieme a me...[n][w][e]

[sel SEL_C14_SPOT_02_02 top]
[s]Invitala[e]
[s]Non invitarla[e]

[msg MSG_C14_SPOT_02_03 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15045 65535 0]Oh, buona idea![n]Tsukishima ha degli ottimi monja.[n][w][e]
[s][f 4 10 65535 0 0]Vediamoci alla stazione![n][w][e]
[s][f 4 10 65535 0 0]Per韻 non puoi bere alcol.[n]OK, Padroneee?[n][w][e]

[msg MND_C14_SPOT_03_01]
[s]Forse dovrei invitarla[n]a fare un giro sulla ruota[n]panoramica di Odaiba con me...[n][w][e]

[sel SEL_C14_SPOT_03_02 top]
[s]Invitala[e]
[s]Non invitarla[e]

[msg MSG_C14_SPOT_03_03 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]D'accordo, Padr... Aspetta.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15173 65535 0]Grazie, [lName]-kun. Andare sulla[n]ruota panoramica con l'uomo[n]che amo 因 un sogno che si avvera.[n][w][e]

[msg MND_C14_SPOT_04_01]
[s]Forse dovrei invitarla a venire[n]con me al buffet del Wilton...[n][w][e]

[sel SEL_C14_SPOT_04_02 top]
[s]Invitala[e]
[s]Non invitarla[e]

[msg MSG_C14_SPOT_04_03 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15178 65535 0]Oh, allora sei un buongustaio.[n]L'unico problema 因 che[n]因 abbastanza costoso...[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]Oh, beh! Lascia fare alla tua[n]insegnante! Vediamoci a Shibuya.[n][w][e]

[msg MND_C14_SPOT_05_01]
[s]Forse dovrei invitarla in camera[n]come fosse la mia ragazza...[n][w][e]

[sel SEL_C14_SPOT_05_02 top]
[s]Invitala[e]
[s]Non invitarla[e]

[msg MSG_C14_SPOT_05_03 [Kawakami]]
[s][bup 0 109 6 65535 1][f 4 10 65535 0 0]Oh, uhm, certo...[n]C-Certo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15088 65535 0]Sto solo venendo a sistemare[n]la tua stanza come al solito,[n]ma sono molto nervosa...[n][w][e]

[msg MND_C14_SPOT_06_01]
[s]Forse dovrei invitarla a venire[n]con me a Nakano Broadway...[n][w][e]

[sel SEL_C14_SPOT_06_02 top]
[s]Invitala[e]
[s]Non invitarla[e]

[msg MSG_C14_SPOT_06_03 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15045 65535 0]Oh! Nakano! Ne ho sentito parlare[n]ma non ci sono mai stata![n][w][e]
[s][f 4 10 65535 0 0]Andiamo subito a dare un'occhiata![n]Prego, Padrone. Fai strada.[n][w][e]

[msg MSG_C14_COOP_CANCEL_00 [Kawakami]]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0][vp 8 2 1 15028 65535 0]Uff... E va bene, dovr韻 fare[n]qualche chiamata e vedere se[n]a qualcuno interessa.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]E sar稲 meglio che tu[n]continui a studiare.[n][w][e]

[msg MSG_C14_COOP_CANCEL_04 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Bravo, 因 la cosa migliore.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15127 65535 0]Spero che inizierai a prendere[n]le lezioni pi迂 sul serio[n]d'ora in poi.[n][w][e]

[msg MSG_C14_COOP_CANCEL_06 [Infermiera]]
[s]Come? Pensavo che fosse[n]un suo parente. Scusi[n]il malinteso.[n][w][e]

[msg MSG_C14_COOP_CANCEL_09 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15054 65535 0]Vedi di impegnartinello studio a casa.[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Ora puoi andare a [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ora puoi andare a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Ora puoi andare ad [clr 2]Akihabara[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere Akihabara, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Parco Inokashira[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere il Parco Inokashira, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Se conosci qualcuno[n]a cui piace il ramen,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Seaside Park di Odaiba[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui[n]piacciono i parchi acquatici,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Museo di Ueno[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui[n]potrebbe piacere l'arte,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui[n]piace mangiare il monjayaki,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Harajuku Takenoko[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui piace[n]Takenoko Street, prova[n]a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Chinatown di Motomachi[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere Chinatown, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Destinyland di Maihama[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere Destinyland, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui piace[n]lo Skytree o Nakamise Street,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Planetario di Ikebukuro[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere il planetario, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere il planetario, invitalo[n]ad andarci con te.[n][w][e]
[s]Se vuoi puoi anche[n]andarci da solo per[n]pregare al santuario.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Dome Town di Suidobashi[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere Dome Town, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Wilton Hotel di Shibuya[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere il Wilton Hotel, invitalo[n]ad andarci con te.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Sushi Bar di Ginza[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui piace[n]mangiare sushi costoso,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Book Town di Jinbocho[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui[n]potrebbero piacere le librerie,[n]invitalo ad andarci con te.[n][w][e]
[s]Se vuoi puoi anche[n]andarci da solo per fare[n]qualche acquisto.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Lago Ichigaya[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui[n]piace pescare, prova[n]a invitarlo qui.[n][w][e]
[s]Inoltre, se vuoi, puoi[n]andarci da solo e provare[n]a prendere qualche pesce.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Acquario di Shinagawa[clr 27].[n][w][e]
[s]Se conosci qualcuno[n]a cui potrebbe piacere l'acquario,[n]prova a invitarlo qui.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Hai scoperto un nuovo[n]luogo d'incontro:[n][clr 2]Zona complesso commerciale, Nakano[clr 27].[n][w][e]
[s]Se conosci qualcuno a cui potrebbe[n]piacere la zona del complesso[n]commerciale, invitacelo.[n][w][e]

[msg MND_C14_MASSAGE_00_00]
[s]為 il telefono pubblico.[n][w][e]
[s]Sono sfinito,[n]dovrei chiedere a Kawakami[n]di farmi un massaggio...[n][w][e]

[msg MSG_C14_MASSAGE_00_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Se ti senti molto stanco,[n]perch姻 non chiedi a Kawakami[n]di farti un massaggio?[n][w][e]

[sel SEL_C14_MASSAGE_00_02 top]
[s]Vorrei un massaggio.[e]
[s]No, lasciamo stare.[e]

[msg MSG_C14_MASSAGE_00_03_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15100 65535 0]Oh, va bene se vengo[n]con il costume da maid?[n][w][e]
[s][f 4 10 65535 0 0]為 vero, non lavoro pi迂 come maid,[n]ma se si venisse a sapere che una[n]docente frequenta un suo alunno...[n][w][e]
[s][f 4 10 65535 0 0]Non posso farmi scoprire, spero[n]che non ti dispiaccia se vengo[n]ad aiutarti vestita cos淫.[n][w][e]

[msg MSG_C14_MASSAGE_00_03 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15040 65535 0]Oh, mi stai davvero[n]chiedendo un massaggio...?[n][w][e]
[s][f 4 10 65535 0 0]Va beneee... Sappi che l'ho[n]imparato lavorando da[n]Victoria. Sono bravissima.[n][w][e]
[s][f 4 10 65535 0 0]OK, arrivo subito. Aspettami.[n][w][e]

[msg MND_C14_MASSAGE_00_04]
[s]Per ora passo.[n][w][e]

[msg MSG_C14_MASSAGE_00_05 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1059 65535 0]Non la vuoi chiamare?[n]Dopo un bel massaggio defaticante[n]potrai uscire, lo sai?[n][w][e]

[msg MSG_C14_NG_MASSAGE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Dobbiamo pensare a domani.[n]Chiamiamola un'altra volta.[n][w][e]

