[msg DUMMY_MSG]
[s]Ho venduto [var 0].[n][w][e]

[msg MSG_LAST_GREETING_InfoCe [Signora del banco informazioni]]
[s][vp 8 2 1 58671 1 0]Oddio, sei il ragazzino di prima,[n]vero? Quello che ha ascoltato con[n]attenzione tutte le informazioni.[n][w][e]
[s][vp 8 2 1 0 1 0]Sei riuscito a scoprire[n]altro su Kichijoji?[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, presto lascerai la citt稲, perci韻[n]dovresti salutare anche quella[n]gentile signora delle informazioni.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_3 [Signora del banco informazioni]]
[s][vp 8 2 1 58675 1 0]Eh? Ti trasferisci?!?[n][w][e]
[s][vp 8 2 1 0 1 0]Capisco... Scommetto che anche[n]la tua citt稲 因 splendida.[n][w][e]
[s][vp 8 2 1 0 1 0]Ma non credi che anche Kichijoji[n]sia stata un bel posto in cui[n]sentirsi a casa?[n][w][e]
[s][vp 8 2 1 0 1 0]為 per questo che spero che non[n]dimenticherai questa citt稲. Torna[n]presto. Mi troverai qui.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_4 [Signora del banco informazioni]]
[s][vp 8 2 1 58673 1 0]為 per questo che spero che non[n]dimenticherai questa citt稲. Torna[n]presto. Mi troverai qui.[n][w][e]

[msg MSG_LAST_GREETING_InfoCe_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Non serve imparare altro di questa[n]citt稲, vero? Andiamo altrove.[n][w][e]

[msg MSG_LAST_GREETING_MeatFr [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]In questo posto c'era sempre una[n]coda pazzesca. Ehi, un giorno[n]dobbiamo tornarci.[n][w][e]

[msg MSG_LAST_GREETING_DartsA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Abbiamo passato molto tempo qui.[n]Le partite con gli altri saranno[n]un bel ricordo per entrambi.[n][w][e]

[msg MSG_LAST_GREETING_DartsA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non c'因 tempo di giocare, adesso.[n]Andiamo a salutare tutti.[n][w][e]

[msg MSG_LAST_GREETING_JazzCl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]為 stato Akechi a dirti[n]di questo posto...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Scommetto che lui...[n]Su, andiamo da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_JazzCl_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Sembra che questo posto[n]sia chiuso di giorno.[n]Andiamo altrove.[n][w][e]

[msg MSG_LAST_GREETING_Shop_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hai tantissimi ottimi amici.[n]Non hai bisogno di[n]cristalli curativi.[n][w][e]

[msg MSG_LAST_GREETING_Shop_V [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Che buon profumooo. Ehm...[n]Qui non hai niente da fare, vero?[n]Andiamocene.[n][w][e]

[msg MSG_LAST_GREETING_Cafe_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Siamo venuti qui diverse volte con[n]Akechi. Se fosse ancora qui,[n]scommetto che... Mmh, lascia stare.[n][w][e]

[msg MSG_LAST_GREETING_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Se vuoi un caff因, dovresti berlo al[n]Leblanc. Dobbiamo incontrare[n]gli altri, prima.[n][w][e]

[msg MSG_LAST_GREETING_Shop_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Non 因 qui che avete comprato gli[n]occhiali per il padre di Sumire?[n][w][e]
[s]Anzi, perch姻 indossi ancora il tuo?[n][w][e]

[msg MSG_LAST_GREETING_Shop_M_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non 因 il momento di scegliere degli[n]occhiali. Sbrighiamoci ad andare[n]a salutare tutti.[n][w][e]

[msg MSG_LAST_GREETING_FoodSh [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Questo s淫 che 因 un negozio alla[n]moda. Ce ne sono di simili[n]nella tua citt稲 natale?[n][w][e]

[msg MSG_LAST_GREETING_Statio [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Quante cartolerie colorate ed[n]eleganti... Appropriato per Kichijoji.[n][w][e]

[msg MSG_LAST_GREETING_Temple [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Il corridoio all'aperto del tempio[n]era tranquillo e silenzioso.[n][w][e]
[s][f 4 10 65535 0 0]Dicevi che anche la tua citt稲 因[n]bella e tranquilla? Non vedo l'ora.[n][w][e]

[msg MSG_LAST_GREETING_Temple_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non conosci alcun monaco, vero?[n]Andiamo da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_OldClo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non 因 il momento di guardare[n]gli abiti usati alla moda![n][w][e]

[msg MSG_LAST_GREETING_Dagash [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]A proposito, chiss稲 perch姻[n]Sumire era in questo negozio?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Beh, non importa.[n]Andiamo a salutare.[n][w][e]

[msg MSG_LAST_GREETING_Dagash_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non 因 il momento di fermarsi[n]a prendere snack.[n][w][e]

[msg MSG_LAST_GREETING_Bank [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Non mi sembra che tu abbia un[n]conto in banca. Andiamocene.[n][w][e]

[msg MSG_LAST_GREETING_Ethnic [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Ricordi quel ristorante di sushi a[n]Ginza? Non mi dispiacciono neanche[n]i ristoranti di sushi a nastro.[n][w][e]
[s][f 4 10 65535 0 0]A proposito, la tua citt稲 non 因[n]vicina al mare? Sono impaziente[n]di vedere com'因![n][w][e]

[msg MSG_LAST_GREETING_HatSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Quanti cappelli alla moda...[n]Starebbero benissimo ad Haru![n][w][e]

[msg MSG_LAST_GREETING_Taiyak [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Voglio il miglior taiyaki che c'因.[n]Pancake a forma di orata con[n]fagioli azuki... Li hanno da te, s淫?[n][w][e]

[msg MSG_LAST_GREETING_TeaHou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Concordo, mangiamo qualche dolce e[n]rilassiamoci davanti a una[n]tazza di buon t因.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Cio因, no! Finiremo per fare notte[n]senza accorgercene! Andiamo a[n]salutare gli altri finch姻 因 chiaro.[n][w][e]

[msg MSG_LAST_GREETING_SocksS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]Sono sicuro che gi稲 lo sai, ma[n]non indosso calzini bianchi, OK?[n][w][e]

[msg MSG_LAST_GREETING_Teleph [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53124 65535 0]Il tuo cellulare ci ha aiutato molto.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ci ha tenuti tutti in contatto,[n]ci ha fatto da Navi nel Metaverso...[n]Non saremmo qui senza di lui.[n][w][e]

[msg MSG_LAST_GREETING_IceSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Sai, Ryuji va matto per le barrette[n]gelato. Ricordo che ne ha mangiata[n]una anche in spiaggia.[n][w][e]

[msg MSG_LAST_GREETING_Fudous [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Sai, se dovessimo mai tornare,[n]vorrei vivere a Yongen.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Non trovi anche tu?[n][w][e]

[msg MSG_LAST_GREETING_MajorC [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Se ti rimpinzi ora, non riuscirai[n]a salutare tutti.[n][w][e]

[msg MSG_LAST_GREETING_Ethnic_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Non vedo l'ora di vedere la[n]tua stanza nella tua citt稲.[n]Com'因 fatta?[n][w][e]

[msg MSG_LAST_GREETING_Realto [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Non hai gi稲 dei mobili in stanza,[n]nella tua citt稲?[n][w][e]

[msg MSG_LAST_GREETING_Karaok [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]La tua citt稲 因 parecchio distante,[n]vero? In treno ti intratterr韻[n]cantando qualche canzone.[n][w][e]

[msg MSG_LAST_GREETING_Record [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Nella tua citt稲 hai una macchina[n]che pu韻 riprodurre CD giganti?[n][w][e]

[msg MSG_LAST_GREETING_MusicT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Ehi, sapevi che Iwai[n]suona la chitarra?[n][w][e]

[msg MSG_LAST_GREETING_MusicT_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Dai, gli strumenti musicali[n]non ti interessano, vero?[n]Andiamo da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_Pasta_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che bel negozio di pasta.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Scommetto che Kawakami[n]andrebbe matta per questo posto.[n]Dobbiamo portarcela un giorno.[n][w][e]

[msg MSG_LAST_GREETING_Pasta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che bel negozio di pasta.[n]Hai fame, per caso?[n][w][e]

[msg MSG_LAST_GREETING_Bicycl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non ce la faremo in bici fino a[n]casa... Prenderemo il treno, vero?[n][w][e]

[msg MSG_LAST_GREETING_ToySho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Perch姻 guardi i giocattoli?[n]Andiamo dagli altri.[n][w][e]

[msg MSG_LAST_GREETING_SteakF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Scommetto che Ryuji impazzirebbe[n]a mangiare della carne cos淫.[n]Dovremmo tornarci con lui.[n][w][e]

[msg MSG_LAST_GREETING_WineBa [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Un wine bar, eh? Quando sarai[n]pi迂 grande, potremmo tornare[n]a bere qui con Ohya.[n][w][e]

[msg MSG_LAST_GREETING_WineBa_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non sei abbastanza grande per bere.[n]Su, andiamo altrove.[n][w][e]

[msg MSG_LAST_GREETING_Antiqu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]La tua stanza al Leblanc 因[n]piuttosto antiquata, ma com'因[n]quella nella tua citt稲 natale?[n][w][e]

[msg MSG_LAST_GREETING_DonutS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Ricordi quella cosa della ciambella?[n]Ammetto che mi ha impressionato[n]la tua capacit稲 di osservazione.[n][w][e]

[msg MSG_LAST_GREETING_DonutS_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Vuoi delle ciambelle? Non le[n]vendono nella tua citt稲 natale?[n][w][e]

[msg MSG_LAST_GREETING_Sports [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Scommetto che andare in[n]campeggio con gli altri[n]sarebbe divertente.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Potremmo noleggiare un camper[n]e viaggiare in tutto il paese.[n][w][e]

[msg MSG_LAST_GREETING_Realto_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Ricordi quando sei venuto a sederti[n]qui? Devi aver pensato che[n]fosse comodissima.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Sar韻 felice se il divano nella tua[n]citt稲 fosse altrettanto comodo.[n][w][e]

[msg MSG_LAST_GREETING_Realto_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Perch姻 fissi il divano?[n]Ti sei stancato?[n][w][e]

[msg MSG_LAST_GREETING_Realto_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Ce l'hai una sedia nella tua stanza,[n]vero? Ma immagino che non[n]ci siano sbarre per allenarsi, eh?[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non c'因 tempo per bere succhi![n]Dobbiamo andare a salutare[n]gli altri, no?[n][w][e]

[msg MSG_LAST_GREETING_CoinLo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Passer稲 un pezzo prima di[n]poter tornare... Non ti conviene[n]usare gli armadietti.[n][w][e]

[msg MSG_LAST_GREETING_Tobari [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1183 65535 0]L'oden di questo posto aveva[n]un aspetto delizioso, eh? Per韻[n]adesso 因 chiuso...[n][w][e]

[msg MSG_LAST_GREETING_Tobari_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Questo posto aveva bevande di ogni[n]tipo. Beh, ora 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Questo posto era cos淫 intimo...[n]Purtroppo non possiamo dargli[n]un'ultima occhiata. 為 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]La cucina di questo posto era cos淫[n]minuta, anche per gli standard[n]del capo. Ma purtroppo 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Sento odore di pesce fresco, qui![n]...Per韻 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Quell'oden al pomodoro sembra[n]squisito, eh? Ma non possiamo[n]mangiarlo adesso, 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_7 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]C'因 un esercizio al secondo piano.[n]Credo si chiami "Terme del[n]maiale". Avranno davvero le terme?[n][w][e]

[msg MSG_LAST_GREETING_Tobari_8 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Questo posto, "Tsuppari Banzuke",[n]sembra offrire specialit稲 locali.[n]Ma "tsuppari" non viene dal sumo?[n][w][e]

[msg MSG_LAST_GREETING_Tobari_9 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1034 65535 0]Questo posto 因 pieno di graffiti.[n]Forse un giorno potresti venirci[n]con Yusuke.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]Questo negozio 因 fortunato a[n]trovarsi in una posizione cos淫[n]strategica. A ogni modo, 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Il profumo del pollo fritto di[n]questo posto era cos淫 invitante...[n]Per韻 ora 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Qui puoi bere seduto sul tatami,[n]vero? Ma non possiamo dare[n]un'occhiata, visto che 因 chiuso.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Ricordo che avevano delle botti l淫[n]dentro. Curavano molto lo stile,[n]nonostante le piccole dimensioni.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Qui si possono mangiare molte[n]variet稲 di alette. 為 chiuso, per韻.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]I nikuman sembrano buoni, ma ora[n]non abbiamo tempo per mangiare.[n][w][e]

[msg MSG_LAST_GREETING_Tobari_16 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Il ramen qui sembra sempre[n]buonissimo. Prima o poi voglio[n]visitare tutti i ramen bar di Tokyo.[n][w][e]

[msg MSG_LAST_GREETING_Udon_1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh gi稲, ho visto l'intervista di[n]Hifumi. Lo sapevi che va matta[n]per gli udon?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Un giorno dovresti portarla qui.[n][w][e]

[msg MSG_LAST_GREETING_Udon_1_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sembra un posto dove si possono[n]mangiare udon in piedi, ma non[n]ne abbiamo il tempo.[n][w][e]

[msg MSG_LAST_GREETING_Deaden [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Certo, li troveremo di sicuro in[n]mezzo all'immondizia... Perch姻 mai[n]dovrebbero essere qui!?! Andiamo![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Su, non abbiamo niente da fare qui![n]Andiamo altrove![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Pi迂 avanti non c'因 nessuno che[n]conosciamo. Sbrighiamoci ad[n]andare a salutarli![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MND_0103]
[s]Dovrei vedere cosa stanno facendo[n]i miei amici.[n][w][e]

[msg MND_TEMPLE_0103]
[s]......[n][w][e]
[s]Rester稲 chiuso fino all'8.[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non 因 il momento di fare compere.[n][w][e]
[s]Meglio andare a[n]controllare gli altri.[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni.[n][w][e]
[s]Meglio andare a[n]controllare gli altri.[n][w][e]

[msg MND_CommonKeyFree]
[s]Adesso ho una cosa da fare.[n][w][e]

[msg MSG_CommonKeyFree [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Qui non hai niente da fare.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Al momento non ho sete.[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MSG_KF794101_AddInfo [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Andiamo alla sala delle[n]freccette, forza.[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Vuoi spostarti in[n]un'altra zona?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]S淫, andiamo.[e]
[s]No, non ancora.[e]

[msg MND_GATE_0103]
[s]Andiamo da un'altra parte...[n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Superata quest'area, c'因 la linea[n]Inogami. Pagando 200 yen, puoi[n]raggiungere Shibuya. Ci andiamo?[n][w][e]

[sel SEL_GOTO_Kichijoji2Shibu top]
[s]Buona idea.[e]
[s]Meglio di no.[e]

[msg MSG_GOTO_Kichijoji2Shibu_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, non hai abbastanza soldi?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ti dar韻 un po' dei miei fondi[n]d'emergenza, ma la prossima volta[n]ricordati di portarli.[n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Qui non hai niente da fare,[n]vero? Andiamo[n]da un'altra parte![n][w][e]

[msg MSG_GOTO_Kichijoji2Shibu_4]
[s]Non devo fare niente l淫.[n]Meglio tornare indietro...[n][w][e]

[msg MSG_KF794101_InfoCenter [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Un banco informazioni? Non si vedono[n]spesso nelle altre citt稲.[n][w][e]

[msg MSG_InfoCenter [Signora del banco informazioni]]
[s][vp 8 2 1 58671 1 0]Salve! Diamo volentieri informazioni[n]dettagliate su quest'area![n][w][e]

[msg MSG_InfoCenter02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Perch姻 non le chiedi di Kichijoji?[n][w][e]

[msg MND_InfoCenter02]
[s]Cosa voglio sapere di Kichijoji...?[n][w][e]

[msg MSG_InfoCenter_start [Signora del banco informazioni]]
[s][vp 8 2 1 58672 1 0]Cosa vuoi sapere?[n][w][e]

[sel SEL_InfoCenter top]
[s]Informazioni sulla citt稲.[e]
[s]Cosa mi consiglia?[e]
[s]Informazioni sui negozi.[e]
[s]Qualcosa che dovrei sapere?[e]
[s]Niente.[e]

[msg MSG_InfoCenter01_01 [Signora del banco informazioni]]
[s][vp 8 2 1 58673 1 0]Certo! Permettimi di spiegare![n][w][e]
[s][vp 8 2 1 0 1 0]Ci sono quattro zone diverse...[n][w][e]
[s][vp 8 2 1 0 1 0]Nella galleria ci sono una friggitoria,[n]una cartoleria, un negozio di[n]abbigliamento usato e un tempio.[n][w][e]
[s][vp 8 2 1 0 1 0]Il menchi-katsu della friggitoria[n]因 delizioso, ma bisogna fare[n]la fila.[n][w][e]
[s][vp 8 2 1 0 1 0]Se svolti a sinistra alla friggitoria,[n]trovi Retro Street, piena[n]di negozi chic e sofisticati.[n][w][e]
[s][vp 8 2 1 0 1 0]C'因 anche un jazz club alla fine del[n]vicolo. Spesso ci suonano artisti[n]famosi e c'因 molto fermento.[n][w][e]
[s][vp 8 2 1 58674 1 0]Fiuuu, spero di aver spiegato tutto[n]bene... Altre domande?[n][w][e]

[sel SEL_InfoCenter01_Inter top]
[s]Continui pure.[e]
[s]Credo che basti cos淫.[e]

[msg MSG_InfoCenter01_02 [Signora del banco informazioni]]
[s][vp 8 2 1 58676 1 0]Certo![n][w][e]
[s][vp 8 2 1 0 1 0]Superata Retro Street, c'因[n]Rue De Chouchou,[n]piena zeppa di negozi alla moda.[n][w][e]
[s][vp 8 2 1 0 1 0]C'因 anche un negozio di pietre[n]del potere rinomate per la[n]loro efficacia.[n][w][e]
[s][vp 8 2 1 0 1 0]Ma non solo, su Rue De Chouchou[n]c'因 una sala per giocare a biliardo[n]e freccette. Divertimento assicurato.[n][w][e]
[s][vp 8 2 1 0 1 0]L'ultima 因 Harmony Alley, una sorta[n]di distretto alcolico. 為 giusto[n]dietro questo punto informazioni.[n][w][e]
[s][vp 8 2 1 0 1 0]Ha uno stile molto nipponico, ideale[n]per godersi l'atmosfera e[n]trovare un po' d'ispirazione.[n][w][e]
[s][vp 8 2 1 0 1 0]Troppe informazioni per[n]un minorenne?[n][w][e]
[s][vp 8 2 1 0 1 0]Ed 因 pi迂 o meno tutto per la citt稲.[n]C'因 qualcos'altro che posso fare[n]per te?[n][w][e]

[msg MSG_InfoCenter02_01 [Signora del banco informazioni]]
[s][vp 8 2 1 58673 1 0]Ci penso io! Ti spiego tutto![n]Sei minorenne, giusto?[n]In tal caso...[n][w][e]
[s][vp 8 2 1 0 1 0]Se superi il distretto alcolico e[n]Rue De Chouchou, trovi una[n]sala da biliardo e freccette.[n][w][e]
[s][vp 8 2 1 0 1 0]為 un posto carinissimo, e[n]quelli della tua et稲 possono[n]accedervi senza problemi.[n][w][e]

[sel SEL_InfoCenter02_Inter top]
[s]E per gli adulti?[e]
[s]Qualche luogo speciale?[e]

[msg MSG_InfoCenter02_02 [Signora del banco informazioni]]
[s][vp 8 2 1 58675 1 0]Eh?!? Beh, sei venuto fin qui...[n][w][e]
[s][vp 8 2 1 0 1 0]Se cerchi un posto per adulti,[n]c'因 il jazz club...[n][w][e]
[s][vp 8 2 1 0 1 0]E CREDO che i minorenni siano[n]ammessi... Scusa se non posso[n]confermartelo al 100%.[n][w][e]
[s][vp 8 2 1 0 1 0]Vuoi sapere qualcos'altro?[n][w][e]

[msg MSG_InfoCenter02_03 [Signora del banco informazioni]]
[s][vp 8 2 1 58677 1 0]Oh, s淫! Uno dei tesori nascosti[n]della citt稲 因 il tempio nella[n]galleria.[n][w][e]
[s][vp 8 2 1 0 1 0]為 apprezzato anche dai giovani[n]in cerca di consiglio. [n][w][e]
[s][vp 8 2 1 0 1 0]Oh, ma forse questo non include[n]studenti come te, eh? Ahah.[n]Se sei interessato, facci un salto.[n][w][e]
[s][vp 8 2 1 0 1 0]C'因 qualcos'altro che[n]volevi chiedere?[n][w][e]

[msg MSG_InfoCenter03_01 [Signora del banco informazioni]]
[s][vp 8 2 1 58673 1 0]Certo! Permettimi di spiegare![n][w][e]
[s][vp 8 2 1 0 1 0]C'因 anche un negozio d'abbigliamento[n]di seconda mano davvero molto[n]strano... ehm, cio因, unico.[n][w][e]
[s][vp 8 2 1 0 1 0]Si trova lungo il corso.[n]Il direttore mi saluta sempre[n]al mattino, ma...[n][w][e]
[s][vp 8 2 1 0 1 0]Dice sempre "Voglio soprattutto[n]indumenti sporchi".[n]Ed 因 anche molto selettivo.[n][w][e]
[s][vp 8 2 1 0 1 0]Oh, e sei mai stato al negozio di[n]incensi su Harmony Alley?[n]Ha aperto solo di recente.[n][w][e]
[s][vp 8 2 1 0 1 0]Hanno incensi davvero molto[n]particolari e spesso sconosciuti.[n]Ma 因 assolutamente certificato.[n][w][e]
[s][vp 8 2 1 0 1 0]C'因 qualcos'altro che[n]volevi chiedere?[n][w][e]

[msg MSG_InfoCenter04_01 [Signora del banco informazioni]]
[s][vp 8 2 1 58678 1 0]Qualcosa che dovresti sapere...[n]In realt稲, s淫. C'因 una voce che[n]ho sentito di recente.[n][w][e]
[s][vp 8 2 1 0 1 0]Riguarda la friggitoria nella[n]galleria. Dicono che ci sia[n]una fila sfiancante...[n][w][e]
[s][vp 8 2 1 0 1 0]E quando arriva sera hanno gi稲[n]esaurito tutto. Mi chiedo cosa[n]si debba fare per mangiarci...[n][w][e]
[s][vp 8 2 1 0 1 0]Beh, quantomeno ho sentito che[n]di domenica preparano pi迂 cibo.[n][w][e]
[s][vp 8 2 1 0 1 0]Quindi, in pratica, ti conviene[n]andarci la domenica sera...[n]Questo 因 tutto ci韻 che ho sentito.[n][w][e]
[s][vp 8 2 1 0 1 0]Desideri sapere altro?[n][w][e]

[msg MSG_InfoCenter05_01 [Signora del banco informazioni]]
[s][vp 8 2 1 58680 1 0]Se vuoi sapere altro di Kichijoji,[n]passa quando vuoi![n][w][e]

[msg MSG_InfoCenter_00 [Signora del banco informazioni]]
[s][vp 8 2 1 58679 1 0]Volevi chiedere altro?[n][w][e]

[msg MSG_InfoCenter_ParamUp [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 1 0]Fiuuu... Quante informazioni.[n]Direi che ci siamo fatti[n]una cultura su Kichijoji![n][w][e]

[msg MND_InfoCenter_ParamUp]
[s]Sento di aver ampliato[n]i miei orizzonti![n][w][e]

[msg MSG_InfoCenter_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Sembra chiuso.[n][w][e]
[s][f 4 10 65535 0 0]Se hai qualche domanda, torna[n]di giorno.[n][w][e]

[msg MND_InfoCenter_heiten]
[s]Sembra chiuso...[n][w][e]
[s]Dovr韻 tornarci[n]in un'altra occasione.[n][w][e]

[msg MSG_KF794101_FriedShop [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Cacchio, guarda che fila! Mi pare[n]di aver visto questo posto in TV.[n][w][e]

[msg MSG_FriedShop_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ooh, che profumino! Pare che[n]il menchi-katsu che cucinano qui[n]sia molto famoso.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Per韻, cavolo, guarda che coda...[n]Ci vorr稲 una vita di questo[n]passo. Meglio rinunciare.[n][w][e]

[msg MND_FriedShop_NG]
[s]Ha un odore buonissimo, ma...[n][w][e]
[s]Che fila lunga...[n]Meglio riprovare in seguito.[n][w][e]

[msg MSG_FriedShop_NG_Night [Personale della friggitoria]]
[s][vp 8 2 1 0 2 0]Oh, sei qui per il nostro famoso[n][clr 3]Katsu a pezzettoni[clr 27]? Mi dispiace,[n]ma oggi 因 finito...[n][w][e]
[s][vp 8 2 1 0 2 0]Passa un altro giorno.[n]Magari sarai pi迂 fortunato.[n][w][e]

[msg MSG_FriedShop_OK [Personale della friggitoria]]
[s][vp 8 2 1 0 2 0]Benvenuto. Ecco il tuo [clr 3]Katsu a[n]pezzettoni[clr 27]. 為 l'ultimo, tra l'altro.[n][w][e]

[msg MSG_FriedShop_Thanks [Personale della friggitoria]]
[s][vp 8 2 1 0 2 0]Grazie! Attenzione, scotta.[n][w][e]

[msg MSG_FriedShop_NotBuy [Personale della friggitoria]]
[s][vp 8 2 1 0 2 0]Oggi non ti va?[n][w][e]

[msg MSG_FriedShop_SoldOut [Personale della friggitoria]]
[s][vp 8 2 1 0 2 0]Mi spiace, quello era l'ultimo.[n]Torna per assaggiarlo, OK?[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_DART]
[s]Ora puoi viaggiare velocemente[n]verso [clr 6]Freccette e biliardo[clr 0][n]a Kichijoji.[n][w][e]

[msg MSG_JazzClub_PreStart [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]為 il jazz club dove ti ha[n]portato Akechi.[n][w][e]

[msg MSG_Jazzclub_Start_1st02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Luoghi simili ti aiuteranno a[n]rilassarti e a parlare di cose che[n]di solito ti mettono in difficolt稲.[n][w][e]
[s][f 4 10 65535 0 0]Mmm. Come leader dei Ladri[n]Fantasma, forse potresti invitare[n]un membro del gruppo qui.[n][w][e]

[sel SEL_Jazzclub_1st top]
[s]Non 因 una brutta idea...[e]
[s]Chiss稲 che fanno gli altri.[e]

[msg MSG_JazzClub_Ck_info_1st [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Oh, a quanto pare ai minorenni[n]servono "[clr 2]cocktail analcolici[clr 27]".[n][w][e]

[msg MSG_JazzClub_Ck_info_Com [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Mmh, sembra che il cocktail di[n]stasera sia un "[clr 2][var 0][clr 27]".[n][w][e]

[msg MSG_JazzClub_Ck_info_Get [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"為 cos淫 buono che migliorer稲 la[n]tua [clr 2]energia[clr 27]! Portala a[n]un [clr 2]livello superiore[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Kay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Il gusto del drink ti conferir稲[n][clr 2]potere[clr 27] E [clr 2]fortuna[clr 27]! Potrai[n][clr 2]difenderti[clr 27] da qualunque cosa!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Sui [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Dischiudi l'[clr 2]anima[clr 27] con questo[n]cocktail e raggiungi un [clr 2]livello superiore[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Mok [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Sprigiona [clr 2]velocit稲[clr 27] e [clr 2]fortuna[clr 27] con[n]gli ingredienti di questo drink![n]Lasciati ammaliare dalla [clr 2]magia[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Kin [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"[clr 2]Tutte le tue statistiche[clr 27][n]miglioreranno! Un drink che alimenta[n]la [clr 2]resistenza[clr 27] e l'[clr 2]anima[clr 27]!"[n][w][e]

[msg MSG_JazzClub_Ck_info_Nit [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]"Il drink originale di oggi! Potresti[n]scoprire un nuovo lato di te,[n]magari uno del tutto inedito!?!"[n][w][e]

[msg MSG_JazzClub_Ck_info_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Interessante![n][w][e]

[msg MSG_Jazz_TodaySinger_Tut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Sembra che in alcuni[n]giorni [clr 2]venga un cantante[clr 27]...[n][w][e]

[msg MSG_Jazz_TodaySingerOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oh, guarda! Oggi dovrebbe[n]esibirsi un cantante![n][w][e]

[msg MSG_JazzClub_AskUse [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi andare?[n]Sembra che costi [clr 2]3.000 yen[clr 27].[n][w][e]

[sel SEL_Jazzclub_UseThink top]
[s]Invita qualcuno[e]
[s]Guarda il cartello[e]
[s]Annulla[e]

[msg MSG_Jazz_NextSingerDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Il cantante si esibir稲 il [clr 2][var 2]/[var 1][clr 27]![n]Sorseggiare cocktail ascoltando[n]musica dal vivo... Roba da adulti![n][w][e]

[msg MSG_Jazzclub_NoMoreSinge [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mmm. Non c'因 menzione di quando[n]verr稲 il cantante. Che delusione.[n][w][e]

[msg MSG_Jazzclub_Who_Invite [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Chi inviterai?[n][w][e]

[sel SEL_SELECT_FRIEND top]
[s]Blank: This is not used[e]
[s]Protag: This will also not be used.[e]
[s]Ryuji[e]
[s]Morgana[e]
[s]Ann[e]
[s]Yusuke[e]
[s]Makoto[e]
[s]Haru[e]
[s]Futaba[e]
[s]Akechi[e]
[s][sumi 10 1][e]

[msg MSG_Jazz_FRIEND [Morgana]]
[s][bup 0 3 1 0 0][vp 8 2 1 1167 65535 0][f 4 10 65535 0 0]Oh, [var 3], eh?[n][w][e]

[sel SEL_NPC_SELECT top]
[s]S淫.[e]
[s]Voglio pensarci su.[e]

[msg MSG_FRIEND_NG [Morgana]]
[s][bup 0 3 0 0 0][vp 8 2 1 1185 65535 0][f 4 10 65535 0 0]Allora, chi vuoi invitare?[n][w][e]

[msg MSG_Jazzclub_Moru_Bye [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Allora far韻 una passeggiata.[n]Fammi sapere quando[n]si torna a casa.[n][w][e]

[msg MSG_Jazzclub_Moru_NotBye [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Chiss稲 se i cocktail mi[n]piacerebbero. Dovr韻 provare![n][w][e]

[msg MSG_Jazzclub_NoMoney [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Costa 3.000 yen. Non hai[n]abbastanza soldi...[n][w][e]

[msg MSG_KF794101_JazzClub [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Un jazz club, eh? Sembra quasi[n]un ritrovo segreto per adulti.[n][w][e]

[msg MSG_JazzClub_Lock [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Un jazz club... Chiss稲 che[n]tipo di posto 因.[n][w][e]

[msg MND_JazzClub_Lock]
[s]Sembra un jazz club...[n][w][e]
[s]Non posso nemmeno immaginare[n]come sia laggi迂.[n][w][e]

[msg MND_JazzClub_PreStart]
[s]為 il jazz club che mi ha mostrato[n]Akechi... Forse dovrei entrare.[n][w][e]

[msg MSG_JazzClub_PreStartNot [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]為 il jazz club dove ti ha portato[n]Akechi, ma pare che sia aperto[n]solo di sera.[n][w][e]

[msg MND_JazzClub_PreStartNot]
[s]為 il jazz club che mi ha mostrato[n]Akechi...[n][w][e]
[s]為 aperto solo di notte. Dovr韻[n]tornare in un altro orario.[n][e]

[msg MSG_JazzClub_StartNotNig [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Oh, pare che il jazz club sia[n]aperto solo di sera.[n][w][e]

[msg MND_JazzClub_StartNotNig]
[s]Sembra sia aperto durante[n]il giorno. Forse la prossima volta[n]mi ci fermer韻.[n][w][e]

[sel SEL_Jazzclub top]
[s]Entra[e]
[s]Annulla[e]

[msg MSG_SYSTEM_SHORTCUT_JUZZ]
[s]Ora puoi viaggiare velocemente[n]verso il [clr 6]Jazz Club[clr 0][n]a Kichijoji. [n][w][e]

[msg MSG_JazzClub_Alpha [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]※本来は明智コープランク3で解禁しますが、[n] α1では強制的に解禁状態にします[n][w][e]

[msg MSG_Accessories_Start [Cristalloterapeuta]]
[s][vp 8 2 1 0 4 0]Benvenuto! Guarda pure[n]la nostra merce![n][w][e]

[msg MSG_Accessories_THANKS [Cristalloterapeuta]]
[s][vp 8 2 1 0 4 0]Grazie! Torna presto![n][w][e]

[msg MSG_Accessories_NOT_BUY [Cristalloterapeuta]]
[s][vp 8 2 1 0 4 0]Oh, davvero? Torna a trovarci![n][w][e]

[msg MSG_KF794101_Variety [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Un negozio di incensi?[n]A me sembra sospetto.[n][w][e]

[msg MSG_Variety_Start [Personale del negozio di incensi]]
[s][vp 8 2 1 0 3 0]Ah, un cliente! Prego, prova[n]pure i nostri profumi![n][w][e]

[msg MSG_Variety_THANKS [Personale del negozio di incensi]]
[s][vp 8 2 1 0 3 0]Grazie ancora![n][w][e]

[msg MSG_Variety_NOT_BUY [Personale del negozio di incensi]]
[s][vp 8 2 1 0 3 0]Torna presto![n][w][e]

[msg MSG_Variety_NotOpen [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Wow... l'odore... Non so se il[n]mio naso pu韻 sopportarlo.[n][w][e]
[s][f 4 10 65535 0 0]Non pensavo ti piacesse l'incenso.[n]Se non 因 cos淫, usciamo.[n][w][e]

[msg MSG_FoodShop_NotInfo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Vendono un sacco di cose che[n]vengono da paesi stranieri.[n]Cavolo, vorrei proprio andarci...[n][w][e]

[msg MSG_FoodShop_NotInfo_Aft [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Sembra che vendano un sacco di roba[n]da paesi differenti. Qual era[n]l'articolo pi迂 venduto alle Hawaii?[n][w][e]

[msg MND_FoodShop_NotInfo_Aft]
[s]A quanto pare vendono soprattutto[n]merce d'importazione.[n][w][e]
[s]Non mi serve nulla di queste cose.[n][w][e]

[msg MSG_FoodShop_Start [Commesso del supermercato]]
[s][vp 8 2 1 0 4 0]Benvenuto! Assaggia pure i sapori[n]provenienti da tutto il mondo![n][w][e]

[msg MSG_FoodShop_THANKS [Commesso del supermercato]]
[s][vp 8 2 1 0 4 0]Grazie mille![n]Torna a trovarci![n][w][e]

[msg MSG_FoodShop_NOT_BUY [Commesso del supermercato]]
[s][vp 8 2 1 0 4 0]Grazie ancora![n][w][e]

[msg MSG_Stationer_Start [Dipendente della cartoleria]]
[s]Salve e benvenuto. Abbiamo[n]tantissimi articoli ideali per[n]fare dei regali.[n][w][e]

[msg MSG_Stationer_THANKS [Dipendente della cartoleria]]
[s]Grazie per l'acquisto![n]Torna presto a farci visita.[n][w][e]

[msg MSG_Stationer_NOT_BUY [Dipendente della cartoleria]]
[s]Torna a trovarci.[n][w][e]

[msg MSG_OldClothe_NotOpen_No [Commesso del negozio di vestiti usati]]
[s]Oh, salve... Sei qui per vendere[n]dei vestiti?[n][w][e]
[s]Ehm... sembrano piuttosto usuali...[n]Abbiamo gi稲 vestiti[n]cos淫 in negozio.[n][w][e]

[msg MSG_OldClothe_NotOpen_No_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Come? Non comprer稲 da noi?[n]Hai qualcosa di diverso?[n][w][e]

[msg MSG_OldClothe_NotOpen_No_3 [Commesso del negozio di vestiti usati]]
[s]Cerco soprattutto [clr 2]vestiti sporchi[clr 27]...[n]Sai, che sembrano da buttare.[n]Se solo riuscissi a trovarne...[n][w][e]

[msg MSG_OldClothe_NotOpen_No_4 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Beh, si dice che la stagionatura[n]migliori la carne. Forse 因 lo stesso[n]anche per i vestiti?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Ha parlato di [clr 2]vestiti sporchi[clr 27]...[n]Torniamoci quando ne avremo.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye [Commesso del negozio di vestiti usati]]
[s]Benvenuto. Se vuoi vendere dei[n]vestiti... A-aspetta, cos'因 quello?[n][w][e]
[s]Posso guardarlo? Non temere,[n]non lo ruber韻.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Sta reagendo ai vestiti che abbiamo[n]preso alle Ombre... Sembra sapere[n]di cosa sta parlando.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_3 [Commesso del negozio di vestiti usati]]
[s]Sono qui da 40 anni, ma non ho[n]mai visto vestiti in grado di[n]raggelarmi il cuore...[n][w][e]
[s]D'accordo, li compro. Ma solo[n]per la cifra che si meritano.[n][w][e]
[s]Dunque, qui utilizziamo una tessera[n]punti. Ogni [clr 2]indumento[clr 27] che vendi[n]ti garantisce [clr 2]10 punti[clr 27].[n][w][e]
[s]Una volta ottenuti abbastanza punti,[n]puoi scambiarli con un premio.[n]Ergo, vendici pi迂 vestiti che puoi.[n][w][e]

[msg MSG_OldClothe_NotOpen_Ye_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Quindi non solo ce li comprano,[n]ma ci danno anche dei punti?[n]Dobbiamo tornare assolutamente.[n][w][e]

[msg MSG_OldClothe_Start [Commesso del negozio di vestiti usati]]
[s]Cosa posso fare per te?[n][w][e]

[msg MSG_OldClothe_Start_loop [Commesso del negozio di vestiti usati]]
[s]C'因 altro?[n][w][e]

[sel SEL_OldClothe_bunki top]
[s]Voglio vendere.[e]
[s]Mostrami i premi.[e]
[s]Niente.[e]

[msg MSG_OldClothe_SelCancel [Commesso del negozio di vestiti usati]]
[s]No? Che peccato...[n][w][e]

[msg MSG_OldClothe_Start_NotH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, al momento non hai[n]vestiti da vendere.[n][w][e]

[msg MSG_OldClothe_AnySell [Commesso del negozio di vestiti usati]]
[s]Dunque, hai venduto [var 2] vestiti...[n]Mmh, sono [clr 2][var 0][clr 27] punti.[n][w][e]
[s]E adesso hai [clr 2][var 1][clr 27] punti.[n][w][e]

[msg MSG_OldClothe_give_end [Commesso del negozio di vestiti usati]]
[s]Se vuoi altri punti, vendi[n]i tuoi abiti.[n][w][e]

[msg MSG_OldClothe_give_end_s [Commesso del negozio di vestiti usati]]
[s]Spero che la nostra merce[n]ti sia piaciuta.[n][w][e]
[s]Se vuoi altri punti, vendi[n]i tuoi abiti.[n][w][e]

[msg MSG_OldClothe_Bey [Commesso del negozio di vestiti usati]]
[s]Che vestiti fantastici...[n]Torna a trovarci, d'accordo?[n][w][e]

[msg MSG_OldClothe_Bey_Nosell [Commesso del negozio di vestiti usati]]
[s]Torna a venderci altro, OK?[n]Ti aspetto.[n][w][e]

[msg MSG_Hurugi_Start [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Ho sempre voluto sapere cosa c'因[n]dentro questa roba. Guardiamo![n][w][e]

[msg MSG_Hurugi_end [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Niente male. Torniamoci,[n]prima o poi.[n][w][e]

[msg MSG_Temple_Night [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pare che il tempio non accetti[n]visitatori di notte. Proviamo a[n]tornarci [clr 2]di giorno[clr 27].[n][w][e]

[msg MSG_Temple_Daily [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Scommetto che un tempio[n]in un distretto commerciale[n]aiuta gli affari.[n][w][e]

[msg MND_Temple_Night]
[s]Sembra che la sera sia chiuso.[n]Devo venirci di [clr 2]giorno[clr 27]...[n][w][e]

[msg MSG_Temple_1st_info [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Wow. Difficile credere che ci[n]sia un tempio dentro una citt稲.[n][w][e]
[s][f 4 10 65535 0 0]Ehi, leggi il cartello. "Per avere[n]una vita appagante, devi prima[n]imparare a conoscere te stesso".[n][w][e]
[s][f 4 10 65535 0 0]Meditare al tempio, eh? A quanto[n]pare puoi farlo solo durante il[n]giorno.[n][w][e]

[msg MSG_Temple_NotHaveCard [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oh, non ci vai?[n][w][e]

[msg MSG_Temple_AskUse_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Forse, meditando e rilassandoti[n]potresti imparare qualcosa.[n][w][e]

[msg MSG_Temple_AskUse_002 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Cosa vuoi fare?[n]Vuoi meditare al tempio?[n][w][e]

[sel SEL_TempleUse top]
[s]Diamo un'occhiata.[e]
[s]Vediamo il mio stato.[e]
[s]Non ora.[e]

[msg SYS_ShortCut_Temple]
[s]Ora puoi viaggiare velocemente[n]verso il [clr 6]Tempio[clr 0] a Kichijoji.[n][w][e]

[msg MSG_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Che caffetteria elegante. Se[n]un giorno dovessi invitare[n]Lady Ann... Perch姻 mi guardi cos淫?[n][w][e]

[msg MND_Cafe]
[s]為 una caffetteria elegante.[n][w][e]
[s]Pare che la specialit稲 sia l'espresso[n]con chicchi tostati in casa.[n][w][e]

[msg MSG_Shop_Megane [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]I tuoi occhiali sono finti, vero?[n]Bisogna guardarli da vicino[n]per capirlo...[n][w][e]

[msg MND_Shop_Megane]
[s]......[n][w][e]
[s]I miei occhiali sono falsi.[n]Non c'因 bisogno di cambiarli.[n][w][e]

[msg MSG_KF794101_Deadend_mea [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Pare che da questa parte ci siano[n]solo negozi.[n][w][e]

[msg MSG_Deadend_meat [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Si direbbe che i negozi pi迂[n]interessanti siano laggi迂.[n]Torniamo indietro.[n][w][e]

[msg MND_Deadend_meat]
[s]Non c'因 niente che mi interessi.[n]Dovrei tornare indietro.[n][w][e]

[msg MSG_KF794101_Deadend_Iza [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Cacchio, ho sbattuto il gomito.[n]Perch姻 因 cos淫 stretto qui?[n][w][e]

[msg MSG_Deadend_Izakaya [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Accidenti, sembra un vicolo cieco.[n]Questo posto 因 un labirinto.[n][w][e]

[msg MND_Deadend_Izakaya]
[s]為 un vicolo cieco...[n][w][e]

[msg MSG_KF794101_Deadend_Meg [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Il negozio che stiamo cercando[n]dev'essere qui nei paraggi.[n]Torniamo indietro.[n][w][e]

[msg MSG_Deadend_Megane [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Non vedo niente d'interessante[n]pi迂 avanti. Torniamo indietro.[n][w][e]

[msg MND_Deadend_Megane]
[s]Non devo fare niente[n]pi迂 avanti.[n][w][e]

[msg MSG_KF794101_Deadend_Caf [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Non ci sono pi迂 molti negozi.[n]Torniamo indietro.[n][w][e]

[msg MSG_Deadend_Cafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Qui intorno ci sono pi迂 case[n]che negozi...[n][w][e]

[msg MND_Deadend_Cafe]
[s]Sembra che pi迂 avanti ci sia[n]un'area residenziale.[n][w][e]

[msg MSG_KF794101_Deadend_Jaz [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7029 65535 0]Qui in giro sembrano esserci[n]pi迂 negozi dall'aria adulta.[n]Guardiamo un po'.[n][w][e]

[msg MSG_Deadend_Jazz [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Sembrano esserci negozi pi迂[n]da adulti qui... Torniamo indietro.[n][w][e]

[msg MND_Deadend_Jazz]
[s]In quest'area ci sono negozi pi迂[n]da adulti...[n][w][e]
[s]Torniamo indietro.[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 1 11018 65535 0]Non hai tempo[n]per giocare, Prigioniero![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torna in cella![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]Queste prove... credo che[n]tu possa superarle.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso la Stanza di Velluto[clr 0].[n][w][e]

[msg MSG_Dagashi_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Guarda cosa c'因[n]in queste vetrine...[n][w][e]
[s]Una specialit稲 di Kichijoji,[n]"Dorayaki con castagne e anko"?[n]Sembra pi迂 un hamburger...[n][w][e]

[msg MND_Dagashi_001]
[s]"Dorayaki con castagne e anko".[n][w][e]
[s]Sembra un hamburger.[n][w][e]

[msg MSG_Dagashi_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]為 gi迂 chiuso, ma lo senti[n]questo profumo dolce?[n][w][e]

[msg MND_Dagashi_heiten]
[s]Sento l'odore dolce delle castagne[n]da qui...[n][w][e]

[msg MSG_Bank_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]為 una banca. Sai, mi sono sempre[n]chiesto perch姻 si chiamino cos淫...[n][w][e]

[msg MND_Bank_001]
[s]Non devo fare niente[n]in banca...[n][w][e]

[msg MSG_Bank_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Sembra che la banca sia chiusa...[n]Siamo fuori orario, in effetti.[n]Beh, non che ci servisse, comunque.[n][w][e]

[msg MND_Bank_heiten]
[s]La banca 因 chiusa...[n][w][e]
[s]Ma sembra che ci siano ancora[n]degli impiegati al lavoro...[n][w][e]

[msg MSG_HatShop_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]為 un negozio di cappelli per[n]anziani.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Perch姻 non ti metti un cappello[n]per tenere fermi quei capelli[n]scombinati?[n][w][e]

[msg MND_HatShop_001]
[s]為 un negozio di cappelli per[n]anziani.[n][w][e]
[s]...Magari un giorno indosser韻[n]anch'io un cappello.[n][w][e]

[msg MSG_HatShop_heiten [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Di notte si vedono solo persiane.[n]Ha un'aria desolata.[n][w][e]

[msg MSG_Taiyaki_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Maddai, lo chiamano pesce, ma[n]因 soltanto un taiyaki, no?[n]Pensi che potrebbe piacer... Mmh?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]"Vi offriamo prodotti freschi e[n]biologici ogni giorno". Ma un taiyaki[n]pu韻 essere fresco e biologico...?[n][w][e]

[msg MND_Taiyaki_Open]
[s]"Vi offriamo prodotti freschi[n]e biologici ogni giorno!"[n][w][e]
[s]Avranno una tecnica[n]speciale per farli...[n][w][e]

[msg MSG_Taiyaki_Close [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Secondo te perch姻 hanno scelto un[n]dentice rosso? Potevano scegliere[n]un altro pesce, no?[n][w][e]

[msg MSG_TelephoneShop_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Oh, vuoi comprarmi un cellulare?[n]Assicurati di prendere il modello[n]pi迂 recente, d'accordo?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]...Scherzo. Lascio a te le[n]comunicazioni con gli altri.[n][w][e]

[msg MND_TelephoneShop_001]
[s]"Resistente all'acqua, ampio[n]display e compatibilit稲 4K!" Fanno[n]pubblicit稲 a un nuovo telefono.[n][w][e]
[s]Mi va bene quello che ho adesso...[n][w][e]

[msg MSG_TelephoneShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Hai visto quei telefoni con[n]lo schermo incrinato?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Chiss稲 se possono procurare dei[n]tagli. Ho come l'impressione che[n]andrebbe tutto in pezzi...[n][w][e]

[msg MSG_IceShop_001 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Caff因, fragola e t因 verde...[n]Hanno ogni sorta di sapori.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh! Che ne dici di un gelato al[n]sushi?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]...Lasciamo stare. Mi 因 venuta la[n]nausea solo a pensarci...[n][w][e]

[msg MND_IceShop_001]
[s]Ci sono tantissimi gusti di gelato.[n][w][e]
[s]Forse dovrei venirci[n]con qualcuno.[n][w][e]

[msg MSG_IceShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Sai la differenza tra un gelato[n]alla spina e un gelato normale?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Perch姻 non ne ho idea.[n][w][e]

[msg MSG_Realtor_Sofa_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Oh, guarda quel divano comodo...[n]Ma che ci fai seduto l淫 sopra?[n][w][e]

[msg MND_Realtor_Sofa_001]
[s]Quel divano sembra comodo...[n][w][e]

[sel SEL_sofa top]
[s]Solo un altro po'...[e]
[s]Andiamo.[e]

[msg MSG_Realtor_Sofa_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Cosa, 因 davvero cos淫 comodo?[n]Dev'essere vero, visto che lo[n]espongono qui davanti a tutti...[n][w][e]
[s]OK, andiamo.[n][w][e]

[msg MSG_Realtor_Sofa_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Sul serio? Ma quanto 因 comodo...?[n][w][e]
[s]...Ehi.[n][w][e]
[s]...Ehiiil稲.[n][w][e]
[s]Ehi, ti stanno guardando tutti...[n]Beh, non ti manca il coraggio.[n][w][e]

[msg MSG_Realtor_Sofa_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Bene, andiamo.[n][w][e]

[msg MSG_Realtor_Sofa_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]OK, abbiamo capito che ti piace[n]questo divano. Ma prima[n]aspetta di avere una casa, OK?[n][w][e]

[msg MSG_Realtor_Sofa_End_Fau [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Abbiamo molte cose da fare.[n]Non c'因 tempo per rilassarsi.[n][w][e]

[msg MSG_Realtor [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1186 65535 0]Vuoi prendere un nuovo divano[n]per la tua stanza? Forse ce la[n]facciamo con i soldi che ho...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Wow, guarda il prezzo.[n]Come non detto...[n][w][e]

[msg MND_Realtor]
[s]Forse potrei procurarmi[n]del nuovo mobilio...[n][w][e]
[s]......[n][w][e]
[s]Non credo che avr韻 mai[n]i soldi necessari...[n][w][e]

[msg MSG_Realtor_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]為 chiusa...[n][w][e]
[s][f 4 10 65535 0 0]Con una saracinesca cos淫 grande,[n]mette quasi paura.[n][w][e]

[msg MSG_Realtor_Chair [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Non trovi che questa sedia sia[n]perfetta per me?[n][w][e]

[msg MND_Realtor_Chair]
[s]Questa sedia 因 stata realizzata[n]completamente a mano...[n][w][e]
[s]C'因 odore di vernice.[n][w][e]

[msg MSG_Fudousan [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Eh, guarda il prezzo per una[n]sola camera da letto... C'era da[n]aspettarselo a Kichijoji.[n][w][e]
[s]Aspetta... penso che anche[n]Yongen-Jaya sia in alto[n]nella lista.[n][w][e]
[s]Forse vivi in un'area[n]molto ricercata.[n][w][e]

[msg MND_Fudousan]
[s]C'因 scritto "Ti aiuteremo a trovare[n]la casa dei tuoi sogni!"[n][w][e]
[s]Tuttavia, non ho in programma di[n]affittare una casa a breve.[n][w][e]

[msg MSG_Karaoke [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]"Sconti per famiglie e pensionati!"[n]為 un po' troppo presto per voi...[n][w][e]

[msg MND_Karaoke]
[s]"Comprende numerose enka[n]storiche!"[n][w][e]
[s]Chiss稲 se ci sono canzoni[n]che conosco.[n][w][e]

[msg MSG_RecordShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Questi s淫 che sono CD enormi...[n]Eh? Vinili?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Scommetto che, essendo cos淫[n]grandi, il suono 因 stupendo.[n][w][e]

[msg MND_RecordShop]
[s]為 un negozio di dischi...[n][w][e]
[s]Anche se ne comprassi uno,[n]non avrei modo di ascoltarlo.[n][w][e]

[msg MSG_MusicTool [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Quel violino sembra costosissimo.[n]Eh? 為 un contrabbasso?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]E quello? Un violoncello? Mentre[n]quella 因 una viola? Argh, non[n]ci capisco niente...[n][w][e]

[msg MND_MusicTool]
[s]Tutti gli strumenti sono[n]costosissimi. Mi chiedo quanto[n]costi mantenerli...[n][w][e]

[msg MSG_MusicTool_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]為 bello che ci siano cos淫 tanti[n]tipi di strumenti.[n][w][e]
[s][f 4 10 65535 0 0]Non 因 fantastico che la musica[n]riesca a far commuovere le[n]persone senza usare le parole?[n][w][e]

[msg MSG_Pasta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]Vi consigliamo le pappardelle[n]e le orecchiette, ma anche[n]i cappelletti e gli agnolotti...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Ce l'ho fatta... L'ho detto[n]tutto d'un fiato![n][w][e]

[msg MND_Pasta]
[s]"Lo chef consiglia le pappardelle e[n]le orecchiette. Ma assaggiate anche[n]gli agnolotti e i cappelletti!"[n][w][e]
[s]Mi chiedo che aspetto abbiano.[n][w][e]

[msg MSG_Pasta_Error [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]Vi consigliamo le pappardelle[n]e le orecchiette, ma anche[n]i cappellet...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]...mi sono impappinato.[n][w][e]

[msg MSG_EthnicCafe [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]I ristoranti di sushi a nastro sono[n]luoghi misteriosi, vero? Cio因,[n]perch姻 farlo girare...?[n][w][e]

[msg MND_EthnicCafe]
[s]Vedo il sushi che scorre[n]sui nastri.[n][w][e]

[msg MSG_Japanese_TeaHouse [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Oh, guarda quel menu l稲 sopra.[n]"Granita preparata con acqua[n]naturale".[n][w][e]
[s][f 4 10 65535 0 0]Mi chiedo cosa cambi dall'acqua[n]di rubinetto. Mmh, che acqua[n]usa il capo...?[n][w][e]

[msg MND_Japanese_TeaHouse]
[s]"Una meravigliosa granita naturale."[n][w][e]
[s]Sento voci di ragazze provenienti[n]da oltre le scale.[n][w][e]

[msg MSG_Japanese_TeaHouse_he [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Come si chiama questo negozio?[n]"Yamayuki" o "Sansetsu"?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Perch姻 c'因 una montagna innevata?[n]Chiss稲...[n][w][e]

[msg MSG_SocksShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Eh, hanno dei calzini per cani?[n]Ma non ce ne sono per gatti?[n][w][e]
[s][f 4 10 65535 0 0]Beh, non che mi servano delle[n]calze... Ma scommetto che mi[n]starebbero bene.[n][w][e]

[msg MND_SocksShop]
[s]I calzini che ho comprato sono[n]assolutamente perfetti.[n][w][e]

[msg MSG_SocksShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]A quest'ora i negozi sono chiusi.[n]Che silenzio...[n][w][e]

[msg MSG_MajorCafe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MSG_MajorCafe_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MND_MajorCafe]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]※レストラン ヒット自体をカット予定 [n][w][e]

[msg MSG_EthnicShop [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ci sono maschere da svariate[n]nazioni. 為 un po' inquietante.[n][w][e]

[msg MND_EthnicShop]
[s]Hanno vari prodotti[n]dei paesi asiatici.[n][w][e]
[s]Sembrano tutti particolari.[n][w][e]

[msg MSG_CoinLocker [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Quindi puoi sbloccare gli armadietti[n]con la giusta ricevuta, eh?[n][w][e]
[s][f 4 10 65535 0 0]Per韻 sembrano tutti occupati.[n]Immagino sia perch姻 ci sono un[n]sacco di turisti.[n][w][e]

[msg MND_CoinLocker]
[s]Tutti gli armadietti sono occupati...[n][w][e]

[msg MSG_Bicycle [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh, queste biciclette sembrano[n]molto maneggevoli.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Mmh. Non hanno un posto[n]dove possa mettermi comodo...[n][w][e]

[msg MND_Bicycle]
[s]為 una bicicletta leggera.[n][w][e]
[s]Avranno rimosso il cestino[n]per renderla pi迂 leggera.[n][w][e]

[msg MSG_Bicycle_heiten [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Magari un giorno potremo fare una[n]scampagnata in bicicletta. Sarebbe[n]divertente, anche se ci smarrissimo.[n][w][e]

[msg MSG_ToyShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Guarda quanti giocattoli di legno...[n]Li importano dall'estero, eh?[n][w][e]
[s][f 4 10 65535 0 0]Oh, quel gatto nero... Sembra[n]una mia versione... pi迂 elegante.[n][w][e]

[msg MND_ToyShop]
[s]Ci sono dei giocattoli di legno.[n][w][e]
[s]Non ho alcun motivo di[n]comprarne uno.[n][w][e]

[msg MSG_ToyShop_heiten [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]I giocattoli di legno sono cos淫[n]di classe... Sarei molto[n]contento di riceverne uno.[n][w][e]

[msg MSG_SportsShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Per mare e montagna...[n]Sembra che abbiano parecchie[n]cose da esterno.[n][w][e]
[s][f 4 10 65535 0 0]E per gattine, invece...? Un attimo,[n]che aspetto avrebbero?[n][w][e]

[msg MSG_SportsShop_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pensi che la parete sia verde per[n]ricordare le montagne?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Anzi, lascia stare. Non vedo niente[n]che rappresenti il mare o il[n]cielo...[n][w][e]

[msg MND_SportsShop]
[s]Vendono tantissimi prodotti[n]da esterno.[n][w][e]

[msg MSG_WineBar [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Guarda quel formaggio gigante![n][w][e]
[s][f 4 10 65535 0 0]Oh, 因 finto... Beh, immagino[n]fosse scontato. Ma sembra[n]comunque autentico.[n][w][e]

[msg MND_WineBar]
[s]"Abbiamo 100 tipi di vino".[n][w][e]
[s]Forse ci far韻 un salto[n]quando avr韻 l'et稲 giusta.[n][w][e]

[msg MSG_WineBar_Yoru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Birra e vino non sono entrambi[n]alcolici? 為 meglio se li lasci[n]perdere...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Certa gente non sa resistere, vero?[n][w][e]

[msg MSG_SteakFood [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]"Provate la nostra deliziosa carne[n]di qualit稲 A5 frollata 40 giorni![n]Vi si scioglier稲 in bocca!"[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh cavolo, scusa. Mi 因 sgocciolata[n]un po' di bava sulla tua spalla...[n][w][e]

[msg MND_SteakFood]
[s]"Provate la nostra deliziosa carne[n]di qualit稲 A5 frollata 40 giorni![n]Vi si scioglier稲 in bocca!"[n][w][e]
[s]Chiss稲 com'因...[n][w][e]

[msg MSG_AntiqueStore [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Cavolo, pensavo ci fosse un[n]albero in quel negozio, invece[n]era solo un orologio.[n][w][e]

[msg MND_AntiqueStore]
[s]In questo negozio sembrano esserci[n]parecchi cimeli. Ma... quello...[n][w][e]
[s]All'inizio quello sembrava un dipinto,[n]ma in realt稲 因 un tavolo...[n][w][e]

[msg MSG_AntiqueStore_Yoru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]La parola "antico" sembra dare[n]all'oggetto pi迂 valore.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Che ne dite del Leblanc?[n]為 r姻tro o antico?[n][w][e]
[s][f 4 10 65535 0 0]Wow. Il termine "d'epoca" 因 molto[n]profondo...[n][w][e]

[msg MSG_DonutShop [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Credo di aver appena[n]capito una cosa.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Non ti sembra che ci manchi[n]qualcosa senza la parte centrale[n]della ciambella?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Ma immagino che questa sia la[n]prima forma che ti viene in[n]mente pensando a una ciambella...[n][w][e]

[msg MND_DonutShop]
[s]Riesco a sentire l'odore[n]dolce delle castagne.[n][w][e]

[msg MSG_DonutShop_Quiz_001 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Domanda a sorpresa.[n][w][e]
[s][f 4 10 65535 0 0]Quante ciambelle ci sono su[n]questo cartello?[n][w][e]

[msg MSG_DonutShop_Quiz_Re [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Allora, quante ciambelle ci sono[n]su questo cartello?[n][w][e]

[sel SEL_Donut_01 top]
[s]...9.[e]
[s]...10?[e]
[s]Aspetta.[e]

[msg MSG_DonutShop_Quiz_Commo [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Miaohohoh... Ne sei sicuro?[n][w][e]

[sel SEL_Donut_02 top]
[s]Dovrebbero essere 9.[e]
[s]Aspetta.[e]

[sel SEL_Donut_03 top]
[s]Dovrebbero essere 10.[e]
[s]Aspetta.[e]

[msg MSG_DonutShop_Quiz_Commo_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Pensi di aver indovinato?[n][w][e]
[s][f 4 10 65535 0 0]La risposta 因...[n][w][e]

[msg MSG_DonutShop_Quiz_NG [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1036 65535 0]No! Peccato! La risposta 因 10![n][w][e]
[s][f 4 10 65535 0 0]Non hai visto la ciambella[n]a sinistra? Conta anche quella.[n][w][e]

[msg MSG_DonutShop_Quiz_OK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Congratulazioni! 為 esatto![n]La risposta 因 10![n][w][e]
[s][f 4 10 65535 0 0]Sembra che tu abbia notato[n]la ciambella sulla sinistra.[n]Ne hanno messa una anche l淫, eh.[n][w][e]

[msg MSG_DonutShop_Quiz_Commo_3 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Scusa se mi sono preso gioco[n]di te. Ma non 因 stato emozionante?[n][w][e]

[msg MSG_DonutShop_Quiz_Cance [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Eheh, scommetto che adesso lo[n]guarderai meglio. Ho ragione?[n][w][e]

[msg MSG_DonutShop_Quiz_End_N [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Ricordi la domanda sulle ciambelle?[n]Eh eh, ricordo ancora che hai[n]sbagliato la risposta.[n][w][e]

[msg MSG_DonutShop_Quiz_End_O [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Ricordi quella domanda sulle[n]ciambelle? 為 stata una sorpresa[n]che tu abbia indovinato.[n][w][e]

[msg MSG_Tobari01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Il profumo del ravanello nella[n]zuppa... Mi scalda il cuore.[n][w][e]

[msg MND_Tobari01]
[s]Il ravanello nell'oden 因 stato[n]bollito...[n][w][e]

[msg MSG_Tobari02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Ci sono cos淫 tanti alcolici diversi.[n]Proprio come i chicchi di caff因.[n][w][e]
[s][f 4 10 65535 0 0]Eppure, guarda i nomi... Alcuni[n]sembrano proprio violenti.[n][w][e]

[msg MND_Tobari02]
[s]Ci sono bevande alcoliche[n]esposte in un piccolo spazio.[n][w][e]

[msg MSG_Tobari03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Guarda quanta roba, e in un posto[n]cos淫 piccolo... Non pensi che i[n]posti intimi aiutino a rilassarsi?[n][w][e]

[msg MND_Tobari03]
[s]...Sfruttano lo spazio davvero[n]molto bene.[n][w][e]

[msg MSG_Tobari04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ma come fanno a cucinare in un[n]posto cos淫 piccolo?[n][w][e]
[s][f 4 10 65535 0 0]Aspetta, mi sa che la cucina del[n]Leblanc 因 ancora pi迂 piccola.[n]Complimenti al capo...[n][w][e]

[msg MND_Tobari04]
[s]Sento odore di qualcosa di salato.[n][w][e]

[msg MSG_Tobari05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Wow! Fanno anche del sushi!?![n]Non posso guardare...[n]Anzi, no, sembra cos淫 buono...[n][w][e]

[msg MND_Tobari05]
[s]為 un bar che serve anche sushi.[n][w][e]

[msg ChineseMan_Start [Dipendente del negozio di baozi]]
[s][vp 8 2 1 0 5 0]Ehi, benvenuto! Vendiamo baozi[n]caldi e freddi, qui![n][w][e]

[msg ChineseMan_NOT_BUY [Dipendente del negozio di baozi]]
[s][vp 8 2 1 0 5 0]Torna presto![n][w][e]

[msg ChineseMan_THANKS [Dipendente del negozio di baozi]]
[s][vp 8 2 1 0 5 0]Grazie! Torna di nuovo![n][w][e]

[msg MSG_Tobari07 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Puoi mettere il pomodoro nell'oden?[n]Chiss稲 se la zuppa diventa rossa,[n]cos淫.[n][w][e]

[msg MND_Tobari07]
[s]Ci sono dei pomodori nell'oden.[n][w][e]
[s]Chiss稲 che sapore ha.[n][w][e]

[msg MSG_Tobari08 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ora che guardo bene,[n]c'因 anche un secondo piano.[n]為 davvero tutto stipato...[n][w][e]

[msg MND_Tobari08]
[s]Ci sono negozi perfino[n]al secondo piano.[n][w][e]

[msg MSG_Tobari09 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Piatti locali... Insomma, in citt稲[n]puoi procurarti di tutto. Di che[n]piatti locali staranno parlando?[n][w][e]

[msg MND_Tobari09]
[s]Specialit稲 locali...[n][w][e]
[s]Chiss稲 cos'hanno qui.[n][w][e]

[msg MSG_Tobari10 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ehi, ho visto un tizio ubriaco[n]a Yongen-Jaya.[n][w][e]
[s][f 4 10 65535 0 0]Era cos淫 fuori di s姻 che[n]facevo fatica a guardarlo.[n][w][e]

[msg MND_Tobari10]
[s]為 un bar in cui si pu韻[n]bere in piedi.[n][w][e]
[s]Chiss稲 come fanno a non stancarsi.[n][w][e]

[msg MSG_Tobari11 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Non pensi che alla fine di una giornata[n]non ci sia niente di meglio del ramen?[n]Nemmeno il porridge sarebbe male.[n][w][e]

[msg MND_Tobari11]
[s]Sento odore di ramen...[n][w][e]
[s]Il profumo mi fa venire[n]ineluttabilmente fame.[n][w][e]

[msg MSG_Tobari12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Perci韻, dopo aver superato[n]l'area alcolica, c'因 una via alla[n]moda. Ogni zona 因 unica...[n][w][e]

[msg MND_Tobari12]
[s]Ci sono tanti oggetti particolari.[n][w][e]

[msg MSG_Tobari13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Ahhh, il profumo del pollo fritto.[n]Ehi, che differenza c'因 tra[n]questo e il tempura?[n][w][e]

[msg MND_Tobari13]
[s]Sento un buon profumo[n]di pollo fritto.[n][w][e]

[msg MSG_Tobari14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Oh, wow. Hanno il tatami l淫 dentro?[n]Scommetto che 因 comodissimo...[n][w][e]

[msg MND_Tobari14]
[s]Ci sono dei tatami all'interno.[n][w][e]
[s]Sembra molto comodo.[n][w][e]

[msg MSG_Tobari15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Quelle botti mi ricordano il[n]Palazzo di Kamoshida.[n][w][e]

[msg MND_Tobari15]
[s]為 una botte di sake.[n][w][e]
[s]Come le hanno portate qui?[n][e]

[msg MSG_Tobari16 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Perci韻, ci sono due tipi di alette.[n]Quelle normali e quelle a bastoncino.[n]Non pensavo ci fosse scelta.[n][w][e]

[msg MND_Tobari16]
[s]Sento il profumo della salsa sapida[n]e del pollo.[n][w][e]

[msg MSG_Tobari_heiten [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mi sa che questi posti non[n]aprono prima di sera.[n][w][e]

[msg MND_Tobari_heiten]
[s]Sembra che questi posti non[n]apriranno prima di sera.[n][w][e]

[msg MSG_DeadEnd_Seacret [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Quante cose...[n][w][e]

[msg MND_DeadEnd_Seacret]
[s]Non ho niente da fare pi迂 avanti.[n][w][e]

[msg MSG_Udon_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Un posto dove mangiare gli[n]udon in piedi, eh?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Ci sono cos淫 tanti condimenti.[n]E anche se sei di corsa, devi[n]comunque scegliere attentamente...[n][w][e]

[msg MND_Udon_Open]
[s]為 un posto dove si possono[n]mangiare udon in piedi.[n][w][e]
[s]Quanti condimenti...[n][w][e]

[msg MND_COMMON_NG_MACHINE_00]
[s][vp 1 0 0 0 0 0]Ora non ho tempo di[n]fermarmi per comprare da bere.[n][w][e]

[msg MND_E10410100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Al momento non ho sete.[n][w][e]

[msg MND_E10920100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Adesso non ho proprio il[n]tempo per dissetarmi.[n][w][e]

[msg MSG_E27930100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Possiamo farlo poi?[n]Prima dobbiamo trovare[n]informazioni su Futaba.[n][w][e]

[msg MSG_E79310100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, ora non hai il tempo di[n]fermarti per comprare da bere.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Su, sbrigati a portarci[n]alla clinica.[n][w][e]

[msg MSG_KF_Dagashi_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Wow! Guarda la vetrina, coso![n][w][e]

[msg MSG_KF_Dagashi_mes02 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Una specialit稲 di Kichijoji,[n]"Dorayaki con castagne e anko"?[n]Sembra quasi un hamburger...[n][w][e]

[msg MSG_KF_Dagashi_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]"Dorayaki con castagne e anko".[n]Una bomba nucleare di sapori,[n]eh...?[n][w][e]

[msg MSG_KF_HatShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Un negozio di cappelli, eh?[n]Ne hanno un sacco.[n][w][e]

[msg MSG_KF_HatShop_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Chiss稲 quante teste potrebbero[n]rifornire...[n][w][e]

[msg MSG_KF_HatShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Magari provo un cappello.[n][w][e]

[msg MSG_KF_Stationer_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1165 65535 0]I miei sensi morganici hanno[n]scorto dei cappelli che si sposano[n]alla perfezione con il mio stile.[n][w][e]

[msg MSG_KF_Stationer_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Che diavolo percepisce Morgana...?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7079 65535 0]Beh, diamo un'occhiata.[n][w][e]

[msg MSG_KF_Stationer_mes03 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quel dipendente ha detto che[n]i loro prodotti sono perfetti[n]per fare dei regali, eh?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Penso che sarebbe fichissimo[n]riceverne uno.[n][w][e]

[msg MSG_KF_Stationer_mes04 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non pensavo che avresti[n]comprato qualcosa.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Ti hanno detto i tuoi sensi di[n]comprarne uno?[n][w][e]

[msg MSG_KF_TelephoneShop_mes [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7085 65535 0]Ci sono un sacco di cellulari,[n]ma a me sembrano tutti uguali.[n][w][e]

[msg MSG_KF_TelephoneShop_mes_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cavoli, voglio anch'io un[n]telefono. Possibilmente l'ultimo[n]modello![n][w][e]

[msg MSG_KF_TelephoneShop_mes_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]"Resistente all'acqua, ampio[n]display e compatibilit稲 4K!" Assurdo[n]dov'因 arrivata la tecnologia, eh?[n][w][e]

[msg MSG_KF_OldClothesShop_me [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Oh, coso! Guarda il cartello[n]in quel negozio. Dice "portate qui[n]i vostri vestiti sporchi!"[n][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Vestiti sporchi?[n][w][e]

[msg MSG_KF_OldClothesShop_me_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Eh, vediamo cos'hanno![n][w][e]

[msg MSG_KF_OldClothesShop_me_3 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]B-beh, 因 un negozio davvero strano.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Per韻 因 stato divertente.[n]Torniamoci, una volta o l'altra.[n][w][e]

[msg MSG_KF_IceShop_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Caff因, fragola e t因 verde...[n]Hanno ogni sorta di sapori.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Oh! Che ne dici di un gelato al[n]sushi?[n][w][e]

[msg MSG_KF_IceShop_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Chiudi il becco, Morgana! Bleah,[n]solo a immaginarmelo, mi viene[n]il vomito![n][w][e]

[msg MSG_KF_IceShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Ne hanno da due o tre palline.[n]Chiss稲 quante ne puoi mettere[n]su un solo cono...[n][w][e]

[msg MSG_KF_Fudousan_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Eh, guarda il prezzo per una[n]sola camera da letto... C'era da[n]aspettarselo a Kichijoji.[n][w][e]

[msg MSG_KF_Fudousan_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Coso, tu sei un gatto.[n]Gli affitti non sono affar tuo.[n][w][e]

[msg MSG_KF_Fudousan_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 23046 65535 0]Non sono un gatto![n][w][e]

[msg MSG_KF_Fudousan_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7174 65535 0]Dovresti pagare questa cifra[n]ogni mese, giusto? Diamine, costa[n]un rene vivere da soli...[n][w][e]

[msg MSG_KF_Bank_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7088 65535 0]Coso, perch姻 ci sono sempre[n]delle banche vicino alla stazione?[n]Cio因, non che mi servano, per韻...[n][w][e]

[msg MSG_KF_Bank_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]為 una banca. Sai, mi sono sempre[n]chiesto perch姻 si chiamino cos淫...[n][w][e]

[msg MSG_KF_Bank_mes03 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Forse perch姻 le ha inventate un[n]tizio di nome Banca.[n][w][e]

[msg MSG_KF_Bank_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1028 65535 0]Uh, non penso proprio...[n][w][e]

[msg MSG_KF_Bank_mes05 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7046 65535 0]Dannazione! Maledetto Morgana![n][w][e]

[msg MSG_KF_Bank_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Chiss稲 perch姻 ci sono cos淫 tanti[n]tipi di banche...[n][w][e]

[msg MSG_KF_EthnicCafe_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]I ristoranti di sushi a nastro sono[n]luoghi misteriosi, vero? Cio因,[n]perch姻 farlo girare...?[n][w][e]

[msg MSG_KF_EthnicCafe_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eheh, vorrei provare del sushi[n]non rotante uno di questi giorni.[n][w][e]

[msg MSG_KF_EthnicCafe_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Il sushi a nastro non 因 male,[n]ma vorrei provare del sushi pi迂[n]costoso e non rotante, una volta.[n][w][e]

[msg MSG_KF_Taiyaki_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Maddai, lo chiamano pesce, ma[n]因 soltanto un taiyaki, vero?[n]Pensi che potrebbe piacermi?[n][w][e]

[msg MSG_KF_Taiyaki_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ma guarda cosa c'因 scritto. "Vi[n]offriamo prodotti freschi e biologici[n]ogni giorno". Invitante...[n][w][e]

[msg MSG_KF_Taiyaki_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Freschi e biologici? 為 proprio vero[n]che non si giudicano i pesci[n]dalla copertina...[n][w][e]

[msg MSG_KF_Taiyaki_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]"Vi offriamo prodotti freschi[n]e biologici ogni giorno!"[n]Che sapore avranno?[n][w][e]

[msg MSG_KF_TeaHouse_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]"Granita preparata con acqua[n]naturale"? Quindi c'因 differenza[n]rispetto all'acqua del rubinetto?[n][w][e]

[msg MSG_KF_TeaHouse_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ho sentito che, quando la granita[n]andava di moda, si formavano[n]code infinite anche in inverno.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non riesco a credere che la gente[n]mangi certa roba d'inverno...[n][w][e]

[msg MSG_KF_TeaHouse_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]"Una meravigliosa granita naturale"?[n]Non sapevo che le granite potessero[n]essere tanto speciali.[n][w][e]

[msg MSG_KF_SocksShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0]為 un posto dove vendono solo[n]calze. Fa una certa impressione...[n][w][e]

[msg MSG_KF_SocksShop_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, gi稲, le mie calze sono bucate.[n]Devo comprarne un paio nuovo.[n][w][e]

[msg MSG_KF_SocksShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Hanno anche dei calzini con dei[n]personaggi ricamati sopra.[n][w][e]

[msg MSG_KF_MeatFryShop_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Cacchio, guarda che fila! Mi pare[n]di aver visto questo negozio in TV.[n][w][e]

[msg MSG_KF_MeatFryShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, che profumo... Pare che[n]il loro piatto pi迂 famoso sia[n]il "menchi-katsu speciale".[n][w][e]

[msg MSG_KF_MeatFryShop_mes03 [Personale della friggitoria]]
[s][vp 8 2 1 0 2 0]Scusate, ma ci 因 rimasto[n]abbastanza [clr 3]menchi-katsu speciale[clr 27][n]solo per le persone gi稲 in fila.[n][w][e]
[s][vp 8 2 1 0 2 0]Prova a passare di sera.[n][w][e]

[msg MSG_KF_MeatFryShop_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Beh, se 因 cos淫 affollato[n]non possiamo farci niente...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non dimentichiamo che di [clr 2]sera[clr 27][n]potremmo riuscire a comprare il[n]"menchi-katsu speciale"![n][w][e]

[msg MSG_KF_Udon_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]Un posto dove mangiare gli[n]udon in piedi, eh? Hanno[n]un sacco di condimenti extra.[n][w][e]

[msg MSG_KF_Udon_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sono posti creati apposta per[n]mangiare al volo, ma con tutti[n]questi condimenti, 因 dura decidersi.[n][w][e]

[msg MSG_KF_Udon_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Udon da mangiare in piedi.[n]為 questo che chiamano[n]"fast food", vero?[n][w][e]

[msg MSG_KF_Temple_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]Visto da vicino ha un[n]bell'impatto, eh?[n][w][e]

[msg MSG_KF_Temple_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Scommetto che un tempio[n]in un distretto commerciale[n]aiuta gli affari.[n][w][e]

[msg MSG_KF_Temple_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Ma che ci fa un tempio in un[n]distretto commerciale come questo?[n][w][e]

[msg MSG_KF_CoinLocker_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Quindi puoi sbloccare gli armadietti[n]con la giusta ricevuta, eh?[n][w][e]

[msg MSG_KF_CoinLocker_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sai, ho come l'impressione che la[n]gente si dimentichi spesso dove[n]lascia la sua roba.[n][w][e]

[msg MSG_KF_CoinLocker_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Per韻 sembrano tutti occupati.[n]Immagino sia perch姻 ci sono un[n]sacco di turisti.[n][w][e]

[msg MSG_KF_FoodShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Hanno piatti provenienti da[n]altri paesi? Alcuni mi[n]incuriosiscono parecchio.[n][w][e]

[msg MSG_KF_FoodShop_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sembra che abbiano delle rarit稲.[n]Diamo un'occhiata![n][w][e]

[msg MSG_KF_FoodShop_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Costoso, eh?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Magari un giorno me li compro,[n]giusto per scoprire che sapore hanno.[n][w][e]

[msg MSG_KF_FoodShop_mes04 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Oh, hai preso qualcosa?[n]Fammi sapere che sapore ha.[n][w][e]

[msg MSG_KF_JuiceMachine01_me [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, prendi qualcosa da bere?[n][w][e]

[msg MSG_KF_JuiceMachine01_me_2 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7156 65535 0]Wow, non l'ho mai vista vuota.[n][w][e]

[msg MSG_KF_JuiceMachine01_me_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7044 65535 0]Pare che il distributore[n]sia vuoto.[n][w][e]

[msg MSG_KF_EthnicShop_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0]Di solito questi negozi non hanno[n]un odore strano? Non mi va[n]molto a genio...[n][w][e]

[msg MSG_KF_EthnicShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sei proprio un bambino, Ryuji.[n]為 un profumo esotico.[n][w][e]

[msg MSG_KF_EthnicShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Ci sono maschere da svariate[n]nazioni. 為 un po' inquietante.[n][w][e]

[msg MSG_KF_Karaoke_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]"Sconti per famiglie e pensionati!"[n]Mi pare di sentirli cantare.[n][w][e]

[msg MSG_KF_Karaoke_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Il karaoke 因 sempre economico[n]durante la settimana. Chiss稲 se[n]ci guadagnano qualcosa.[n][w][e]

[msg MSG_KF_Karaoke_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]"Comprende numerose enka[n]storiche!"... Scommetto che sono[n]tutte canzoni di un secolo fa.[n][w][e]

[msg MSG_KF_Realtor_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Oh, guarda quanti mobili eleganti.[n][w][e]

[msg MSG_KF_Realtor_mes02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vuoi prendere un nuovo divano[n]per la tua stanza? Forse ce la[n]facciamo con i soldi che ho...[n][w][e]

[msg MSG_KF_Realtor_mes03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Coso, Morgana. Guardate il prezzo.[n][w][e]

[msg MSG_KF_Realtor_mes04 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 0 1032 65535 0]Uff, come non detto.[n][w][e]

[msg MSG_KF_Realtor_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Chiss稲 se sarei popolare con roba[n]del genere in stanza...[n][w][e]

[msg MSG_KF_Realtor_Sofa_mes0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E-ehi, 因 stato cos淫 improvviso che[n]mi hai quasi spaventato...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Per韻 hai del fegato.[n]Che sorpresa![n][w][e]

[msg MSG_KF_Realtor_Sofa_mes0_2 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]...D'accordo. Sappiamo tutti che[n]hai fegato. Andiamo, coso.[n][w][e]

[msg MSG_KF_RecordShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Questi s淫 che sono CD enormi...[n]Eh? Vinili?[n][w][e]

[msg MSG_KF_RecordShop_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]為 vero che CD e vinili hanno[n]un suono diverso?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non credo che sar韻 mai in grado[n]di distinguerli.[n][w][e]

[msg MSG_KF_RecordShop_mes00 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]I dischi sono una figata. Se solo[n]avessi il coso per sentirli...[n][w][e]

[msg MSG_KF_Main_MusicTool_me [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Guarda quanti strumenti l稲[n]dentro... Quasi quasi entro a[n]provarli.[n][w][e]

[msg MSG_KF_Main_MusicTool_me_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Staresti benissimo con una[n]tromba.[n][w][e]

[msg MSG_KF_Main_MusicTool_me_3 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo dici solo per via del colore[n]dei miei capelli, non 因 cos淫?[n][w][e]

[msg MSG_KF_Main_MusicTool_me_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quel violino sembra costosissimo.[n]Eh? 為 un contrabbasso?[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]E quello? Un violoncello? Mentre[n]quella 因 una viola? Argh, non[n]ci capisco niente...[n][w][e]

[msg MSG_KF_JazzClub_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Un jazz club, eh? Sembra[n]un posto per adulti.[n][w][e]

[msg MSG_KF_JazzClub_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Coso, ti piace il jazz? 為 fico.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Comunque, pare sia aperto[n]solo di sera.[n][w][e]

[msg MSG_KF_JazzClub_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Pare che questo jazz club[n]sia aperto solo di sera.[n][w][e]

[msg MSG_KF_Izakaya06_mes01 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7159 65535 0]Coso, questo nikuman 因 molto[n]pi迂 succulento di quelli del[n]convenience store.[n][w][e]

[msg MSG_KF_Izakaya06_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]S淫... Ehi, gente, ne volete uno?[n]Che ne dite?[n][w][e]

[msg MSG_KF_Izakaya06_mes03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7133 65535 0]Nikuman alla napoletana e[n]Nikuman piccante...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cavolo, vorrei troppo assaggiarlo![n]Uno di questo giorni, devo[n]mangiarlo per forza![n][w][e]

[msg MSG_KF_Izakaya_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mi sa che questi posti non[n]aprono prima di sera.[n][w][e]

[msg MSG_KF_Izakaya_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Chiss稲 com'因 di notte...[n]Vorrei dargli un'occhiata.[n][w][e]

[msg MSG_KF_Izakaya_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Ho sentito che quest'area 因[n]parecchio movimentata di sera.[n]Chiss稲 com'因.[n][w][e]

[msg MSG_KF_ramen_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]Un ramen bar aperto solo alla[n]sera, eh?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Di solito sono i migliori, coso.[n][w][e]

[msg MSG_KF_ramen_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tutti vanno matti per il ramen.[n]Voglio dire, in alcuni bar bisogna[n]attendere anche due ore, giusto?[n][w][e]

[msg MSG_KF_ramen_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anche se 因 chiuso, si sente[n]comunque l'odore di ramen.[n][w][e]

[msg MSG_KF_Variety_mes01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Un negozio di incensi? Coso,[n]fidati, questo posto 因 losco.[n][w][e]

[msg MSG_KF_Variety_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aspetta un momento...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 1187 65535 0]Ehi, diamo un'occhiata![n][w][e]

[msg MSG_KF_Variety_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Ho la sensazione che questi incensi[n]abbiano qualche strano potere...[n]Magari potrebbero servirci.[n][w][e]

[msg MSG_KF_Variety_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, non capisco...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ma se Morgana avverte questa[n]sensazione, magari potremmo[n]tornare a comprarli.[n][w][e]

[msg MSG_KF_VarietyNG_mes01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Un negozio di incensi? Coso,[n]fidati, questo posto 因 losco.[n][w][e]

[msg MSG_KF_VarietyNG_mes02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non t'interessa l'incenso, vero?[n]E poi, dove lo useresti?[n][w][e]

[msg MSG_KF_Megane_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Un negozio che vende solo[n]occhiali... Ne hanno tantissimi.[n][w][e]

[msg MSG_KF_Megane_mes02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me lo scordo sempre, ma i tuoi[n]occhiali sono finti, vero? Pensi[n]che io sembrerei pi迂 sveglio?[n][w][e]

[msg MSG_KF_Megane_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Mai avuto bisogno di occhiali,[n]perci韻 non sono mai entrato[n]in negozi cos淫.[n][w][e]

[msg MSG_KF_Accessories_mes01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]Wow! Guarda che quantit稲[n]di tesori hanno l淫![n][w][e]

[msg MSG_KF_Accessories_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Le pietre del potere sono quella[n]sottospecie di amuleti, vero?[n]Hanno un qualche potere bizzarro...[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Diamo un'occhiata.[n][w][e]

[msg MSG_KF_Accessories_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7114 65535 0]Per poco non mi sanguinava il[n]naso a guardare quei prezzi...[n][w][e]

[msg MSG_KF_Accessories_mes04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ma sembravano davvero possedere[n]un qualche potere. Dovremmo[n]controllare, un giorno di questi.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Potrebbe tornare utile[n]ai Ladri Fantasma![n][w][e]

[msg MSG_KF_DonutShop_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ho appena capito una cosa.[n][w][e]

[msg MSG_KF_DonutShop_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Che c'因, Morgana?[n][w][e]

[msg MSG_KF_DonutShop_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si perde un casino senza[n]la parte centrale della ciambella![n][w][e]

[msg MSG_KF_DonutShop_mes04 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Gi稲... 為 proprio qualcosa di cui[n]dobbiamo preoccuparci adesso...[n][w][e]

[msg MSG_KF_DonutShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7184 65535 0]Oh, ma le ciambelle non erano[n]gettonatissime? Ricordo che un po' di[n]tempo fa ne andavano tutti matti.[n][w][e]

[msg MSG_KF_AntiqueStore_mes0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Wow, guarda quanti[n]oggetti artistici antichi...[n][w][e]

[msg MSG_KF_AntiqueStore_mes0_2 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Basta, ho chiuso con l'arte dopo[n]il museo dell'altro giorno.[n][w][e]

[msg MSG_KF_AntiqueStore_mes0_3 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Coso, pensavo che quella roba[n]l稲 dentro fosse un quadro,[n]invece era un maledetto tavolo.[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]L'arte proprio non la capisco.[n][w][e]

[msg MSG_KF_SteakFood_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]"Provate la nostra deliziosa carne[n]di qualit稲 A5 frollata 40 giorni![n]Vi si scioglier稲 in bocca!"[n][w][e]

[msg MSG_KF_SteakFood_mes02 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Basta! Basta! Mi farai venire[n]voglia di mangiarla![n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Questo posto 因 pericoloso.[n]Stiamone alla larga.[n][w][e]

[msg MSG_KF_SteakFood_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Diamine, il profumo della carne[n]mi manda in estasi...[n]Oh, merda, sto sbavando.[n][w][e]

[msg MSG_KF_WineBar_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0]"Abbiamo 100 tipi di vino".[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Il vino si fa con l'uva, giusto?[n]Esistono davvero[n]cos淫 TANTE variet稲?[n][w][e]

[msg MSG_KF_WineBar_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]C'因 molto da sapere sul vino.[n]Tipo che c'因 sia il vino rosso[n]che il vino bianco...[n][w][e]

[msg MSG_KF_WineBar_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]L'unica cosa che ho capito 因[n]che non sei buono a spiegare[n]le cose...[n][w][e]

[msg MSG_KF_WineBar_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Vino e formaggio. Un giorno[n]vorrei provarlo.[n][w][e]

[msg MSG_KF_SportsShop_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Per mare e montagna...[n]Sembra che abbiano parecchie[n]cose da esterno.[n][w][e]

[msg MSG_KF_SportsShop_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Le ragazze di oggi amano[n]stare all'aperto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ma perch姻 non c'因 roba per i ragazzi[n]che amano il mare o la montagna?[n][w][e]

[msg MSG_KF_SportsShop_mes03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Ottima osservazione.[n][w][e]

[msg MSG_KF_SportsShop_mes00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7184 65535 0]Sai, un giorno potrebbero servirci[n]dei costumi da bagno.[n][w][e]

[msg MSG_KF_ToyShop_mes01 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Quindi qui vendono giocattoli[n]importati. In effetti sembrano[n]molto diversi dai nostri.[n][w][e]

[msg MSG_KF_ToyShop_mes02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sono quasi tutti in legno.[n]Magari potremmo realizzarne[n]uno da soli.[n][w][e]

[msg MSG_KF_ToyShop_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Perci韻 因 tutta roba importata[n]dall'estero, eh? Anche le famiglie[n]all'interno sono alquanto eleganti.[n][w][e]

[msg MSG_KF_MajorCafe_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Che caffetteria elegante. Se[n]un giorno dovessi invitare[n]Lady Ann... Perch姻 mi guardi cos淫?[n][w][e]

[msg MSG_KF_MajorCafe_mes02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Beh, c'因 scritto che gli animali[n]sono ammessi, perci韻 perch姻[n]no?[n][w][e]

[msg MSG_KF_MajorCafe_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Chi stai chiamando animale?!?[n][w][e]

[msg MSG_KF_MajorCafe_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Che caffetteria elegante. Pare che[n]la specialit稲 sia l'espresso[n]con chicchi tostati in casa.[n][w][e]

[msg MSG_KF_Pasta_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Vi consigliamo le pappardelle[n]e le orecchiette, ma anche[n]i cappelletti e gli agnolotti...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Ce l'ho fatta! L'ho detto[n]tutto d'un fiato![n][w][e]

[msg MSG_KF_Pasta_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pappar... dette? Agno... cosa?[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non so nemmeno pronunciarli,[n]tantomeno ho idea di come[n]diavolo siano fatti...[n][w][e]

[msg MSG_KF_Pasta_mes00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pare che consiglino pappardelle,[n]orecchiette, cappelletti e[n]agnolotti![n][w][e]

[msg MSG_KF_Bicycle_mes01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Oh, queste biciclette sembrano[n]molto maneggevoli.[n][w][e]

[msg MSG_KF_Bicycle_mes02 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Coso, guarda che prezzi quelle[n]bici! Merda, ma non sono pi迂[n]costose delle moto?[n][w][e]

[msg MSG_KF_Bicycle_mes00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mi chiedo se le bici pi迂 costose[n]siano pi迂 utili di quelle normali...[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 7173 65535 0]Non posso usare questa moto.[n]Ho paura che venga rubata o[n]che ne so io...[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Lasciami entrare in cella.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]A quanto pare, vuoi essere[n]imprigionato. Posso esaudire[n]il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Sar韻 lieta di[n]esaudire il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Continua la tua lotta.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che c'因, Prigioniero?[n]Desideri tornare in prigione?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eheheh. Ti rimetter韻 al[n]tuo posto![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continua a lottare, Prigioniero.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ti condurr韻 dal mio padrone...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Voglio prepararmi.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora entra, per favore.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Io e il mio padrone[n]veglieremo su di te.[n][w][e]

[msg MSG_KICHIJOJ_OPEN_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Finirai di nuovo alla stazione se[n]vai da quella parte. Torniamo alla[n]sala delle freccette, per ora.[n][w][e]

[msg MSG_MONEY_MORGANA_CHK_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Oh, non hai abbastanza soldi?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ti dar韻 un po' dei miei fondi[n]d'emergenza, ma la prossima volta[n]ricordati di portarli.[n][w][e]

[msg MSG_KFEVT_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ehi, dove stai andando?[n][w][e]

[msg MND_COMMON_CHK_000_00]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti...[n][w][e]

[msg EX_0103_0108_LOCK_mes01 [Donna col cappello]]
[s][vp 1 0 0 0 0 0]為 questo il posto con il[n]carismatico profumiere di cui[n]parlano nelle riviste?[n][w][e]

[msg EX_0103_0108_LOCK_mes02 [Donna]]
[s][vp 1 0 0 0 0 0]Oh, s淫. I loro prodotti sono usati[n]da un sacco di attrici e modelli[n]famosi.[n][w][e]

[msg EX_0103_0108_LOCK_mes03 [Donna col cappello]]
[s][vp 1 0 0 0 0 0]Sembra che anche il direttore del[n]negozio sia un tipo misterioso![n]Ne parlano tutti![n][w][e]
[s][vp 1 0 0 0 0 0]Spero di potergli stringere la[n]mano mentre faccio i miei acquisti![n][w][e]

[msg EX_0103_0108_LOCK_mes04]
[s][vp 1 0 0 0 0 0]Sembra sia la fila per il[n]negozio di incensi.[n][w][e]
[s][vp 1 0 0 0 0 0]Dubito di poter proseguire oltre...[n][w][e]

[msg EX_0103_0108_LOCK_mes00]
[s][vp 1 0 0 0 0 0]C'因 troppa gente per[n]poter proseguire...[n][w][e]

