[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_CINEMA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al cinema ci siamo divertiti un[n]sacco. Facciamo una maratona[n]la prossima volta che ci andiamo![n][w][e]

[msg MSG_LAST_GREETING_CINEMA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Se guardiamo un film, non rester稲[n]tempo per i saluti.[n][w][e]

[msg MSG_LAST_GREETING_FURNIT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1140 65535 0]Ehi, non abbiamo tempo per andare[n]da Mran Mran, sai?[n][w][e]

[msg MSG_LAST_GREETING_FLOWER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Abbiamo comprato molti nutrienti[n]qui. 為 un vero peccato che sia[n]chiuso, non possiamo salutare...[n][w][e]

[msg MSG_LAST_GREETING_FLOWER_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Eh? Perch姻 fissi la saracinesca?[n][w][e]

[msg MSG_LAST_GREETING_NOODLE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questo locale 因 chiuso...[n]Un giorno torneremo per ordinare[n]tutto quello che c'因 sul menu.[n][w][e]

[msg MSG_LAST_GREETING_NOODLE_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Il ramen di Ogikubo era buono, vero?[n]Anch'io vorrei provarlo...[n]Portamici la prossima volta, OK?[n][w][e]

[msg MSG_LAST_GREETING_NOODLE_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Chiss稲 se nella tua citt稲[n]il ramen 因 buono?[n][w][e]

[msg MSG_LAST_GREETING_PAWNSH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1003 65535 0]Non hai niente da vendere, no?[n]Forza, andiamo a salutare gli[n]altri![n][w][e]

[msg MSG_LAST_GREETING_SUSHI_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Ricordi il ristorante di sushi[n]a Ginza?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Non che sia un problema, ma...[n]La prossima volta portamici![n][w][e]

[msg MSG_LAST_GREETING_SUSHI__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non c'因 tempo per degustare sushi.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_FREE_I [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Tu hai molto pi迂 fascino diabolico[n]dei tizi in foto.[n][w][e]

[msg MSG_LAST_GREETING_FREE_I_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Smettila di guardare i tizi[n]nella foto e andiamo a[n]salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_BOOK_S [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]La libreria 因 stata di grande aiuto.[n]為 stata la fonte del sapere[n]che ha migliorato le tue abilit稲.[n][w][e]

[msg MSG_LAST_GREETING_BOOK_S_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]I libri in questa libreria...[n]forse non sono adatti a te.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Non c'因 tempo per le bevande.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_DEST_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1182 65535 0]Maledizione. Se ti andava un succo,[n]non avresti potuto berlo.[n]Andiamo dagli altri, dai.[n][w][e]

[msg MSG_LAST_GREETING_HOME_S [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Non c'因 tempo per le bevande.[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_PACHIN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Sembra che l'inaugurazione di[n]questo posto sia durata[n]tutto l'anno...[n][w][e]

[msg MSG_LAST_GREETING_Izakay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Sembrerebbe chiuso durante il[n]giorno. Beh, se ci capiter稲,[n]ci torneremo.[n][w][e]

[msg MSG_LAST_GREETING_Curtai [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Sembra che di giorno sia chiuso.[n]Andiamo altrove.[n][w][e]

[msg MSG_LAST_GREETING_Izakay_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Eiko non c'因 pi迂, quindi non hai[n]niente da fare qui, vero?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ma Makoto era pazzesca, eh?[n]E anche tu facevi faville.[n][w][e]

[msg MSG_LAST_GREETING_Izakay_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questo negozio non ha niente che[n]possa servirti, no? Andiamo[n]a salutare.[n][w][e]

[msg MSG_LAST_GREETING_Izakay_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Sembrerebbe chiuso durante il[n]giorno. Beh, ci torneremo[n]prima o poi.[n][w][e]

[msg MSG_LAST_GREETING_Izakay_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Hai gi稲 Ohya, vero? Non ti servono[n]altre diavolette.[n][w][e]

[msg MSG_LAST_GREETING_Izakay_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non ti servono diavolette.[n]Andiamo da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_Shop_H [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Non c'因 tempo da perdere.[n]Andiamo a salutare gli altri![n][w][e]

[msg MSG_LAST_GREETING_PetSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Qui non ci serve niente.[n]Andiamo da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Da questa parte non c'因 nessuno che[n]conosci, vero? Andiamo a salutare[n]gli altri.[n][w][e]

[msg MSG_LAST_GREETING_Bar [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Non 因 ancora l'orario di[n]apertura, ma diamo[n]comunque un'occhiata...[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Vuoi spostarti in[n]un'altra zona?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]S淫, andiamo.[e]
[s]No, non ancora.[e]

[msg MSG_BAR_no_open_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Devi fare qualcosa a[n]questo Crossroads?[n]Sembra chiuso, al momento.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_BAR]
[s]Ora puoi viaggiare velocemente[n]verso il [clr 6]Crossroads[clr 0] a Shinjuku.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Shin]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il cinema[clr 0] a Shinjuku.[n][w][e]

[msg MSG_FURNITURE_START [Commesso dell'emporio]]
[s][f 4 23 1 24 3 5 65534 0][vp 8 2 1 0 24 0]Benvenuto! Abbiamo tanti prodotti[n]diversi, dalla bigiotteria[n]carina alla merce pi迂 costosa.[n][w][e]

[msg MSG_FURNITURE_THANKS [Commesso dell'emporio]]
[s][vp 8 2 1 0 24 0]Grazie per l'acquisto.[n][w][e]

[msg MSG_FURNITURE_NOTBUY [Commesso dell'emporio]]
[s][vp 8 2 1 0 24 0]Torna presto![n][w][e]

[msg MSG_FURNITURE_CLOSE_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Un emporio? Immagino ci sia[n]una forte richiesta di regali e[n]cianfrusaglie.[n][w][e]
[s][f 4 10 65535 0 0]Ora 因 chiuso, per韻. Torniamo[n]quando sar稲 tutto illuminato.[n][w][e]

[msg MSG_FLOWER_START [Fiorista]]
[s][f 4 23 1 25 3 5 65534 0][vp 8 2 1 0 25 0]Benvenuto. Eheheh.[n]Vuoi dei fiori per la[n]donna della tua vita?[n][w][e]

[msg MSG_FLOWER_THANKS [Fiorista]]
[s][vp 8 2 1 0 25 0]Grazie mille.[n]為 bello viziare la tua donna,[n]ma non spendere troppo, OK?[n][w][e]

[msg MSG_FLOWER_NOTBUY [Fiorista]]
[s][vp 8 2 1 0 25 0]Torna a trovarmi.[n][w][e]

[msg MSG_FLOWER_CLOSE_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Questo fioraio 因 chiuso...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0]Ugh, guarda gli orari d'apertura.[n]Dalla sera, fino a notte fonda?[n]Da Shinjuku non mi aspetto altro.[n][w][e]

[msg MSG_CHINESE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oooh... L'interno del negozio 因[n]tappezzato di biglietti da visita.[n]Credi che abbia molti clienti?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Aspetta. Sono quasi tutti[n]contatti di host. Umpf, una[n]cosa simile 因 normale, a Shinjuku...[n][w][e]

[msg MSG_CHINESE_Gogo [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Quella saracinesca 因 stata[n]deturpata. 為 questo che fanno[n]le persone, di notte?[n][w][e]

[msg MSG_NOODLE_Ogikubo [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Se hai voglia di[n]ramen, vai a Ogikubo.[n][w][e]
[s]Non mangiandolo spesso,[n]quando capita 因 meglio che sia[n]eccezionale, non credi?[n][w][e]

[msg MSG_NOODLE_NotInfoOgikub [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Un ramen bar, eh? Sul treno ho[n]sentito dire che a Tokyo ce[n]n'因 uno buonissimo...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Non so dove sia, ma[n]facciamo in modo di mangiare[n]l淫 il nostro primo ramen a Tokyo![n][w][e]

[msg MSG_PAWNSHOP [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Scommetto che tutte le cose che[n]la gente perde in citt稲, in un modo[n]o nell'altro finiscono qui...[n][w][e]

[msg MSG_SUSHI_SHOP [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Che nome inquietante, per un[n]posto dove si mangia il sushi...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Se hai voglia di sushi,[n]andiamo a Ginza.[n]S淫, a Ginza![n][w][e]

[msg MSG_SUSHI_SHOP_NotInfoGi [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Sanzu...? Come il fiume Stige?[n]Hanno scelto questo nome?[n]Spero che sia uno scherzo.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Sono molto esigente con il sushi,[n]sai? A Tokyo deve per forza esserci[n]un posto di qualit稲 eccezionale![n][w][e]

[msg MSG_FREE_SPACE [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]為 come se questi umani fossero[n]dei cataloghi informativi per[n]il nostro tornaconto. 為 triste...[n][w][e]

[msg MSG_DEADEND01_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Non andare troppo in giro,[n]OK? Altrimenti potresti perderti.[n][w][e]

[msg MSG_Book_Open [Commesso della libreria]]
[s]Benvenuuuto... Wow, sembri molto[n]giovane. Non posso venderti[n]libri per adulti, OK?[n][w][e]

[msg MSG_Book_NotBuy [Commesso della libreria]]
[s]Torna a trovarci quando[n]avrai cambiato idea.[n][w][e]

[msg MSG_Book_Buy [Commesso della libreria]]
[s]Grazie! Torna ancora![n][w][e]

[msg MSG_Book_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Uhm. Mi aspettavo solo libri[n]assurdi, invece ce ne sono alcuni[n]utili, come quello sul baseball.[n][w][e]
[s][f 4 10 65535 0 0]Per ora non hai bisogno[n]di questi libri. Torniamo[n]in un altro momento.[n][w][e]

[msg MSG_Book_NG_02 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Ehi, lo staff del negozio ci sta[n]guardando. Qui 因 pieno di[n]libri per adulti, 因 comprensibile...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Oh, ci sono anche libri che[n]possiamo leggere. Vuoi[n]restare a dare un'occhiata?[n][w][e]

[sel SEL_BookCheck top]
[s]Diamo un'occhiata.[e]
[s]No, va bene.[e]

[msg MSG_BookCheckEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]OK, allora...[n]Andiamocene.[n][w][e]

[msg MSG_BookCheckCommon [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Torniamo un'altra volta.[n]Potresti trovare dei libri[n]interessanti.[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MSG_DEST_MACHINE01_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Un ubriaco deve aver rotto[n]questa macchina. 為 normale,[n]in un posto del genere.[n][w][e]

[msg MGS_HOME_SECURITY [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Qui vendono davvero dei[n]rivelatori di microspie?[n]Dove andremo a finire...?[n][w][e]

[msg MSG_PACHINKO [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Ehi, i liceali non possono[n]frequentare posti simili. E se[n]ti scoprissero?[n][w][e]

[msg MSG_HostClubBoard_moru_Y [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Questi sono gli host[n]suggeriti per questo club?[n][w][e]
[s][f 4 10 65535 0 0]I volti e i capelli...[n]Sono troppo simili tra loro.[n]Sembrano tutti imparentati...[n][w][e]

[msg MSG_Bimajo_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]*coff* Qui dentro c'因[n]puzza di cosmetici. Ed 因 molto[n]pi迂 di un vago aroma...[n][w][e]

[msg MSG_Bimajo_moru_YORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Oltre la tenda c'因 un mondo[n]ignoto e bizzarro, ma affrontiamo[n]gi稲 abbastanza pericoli nel Metaverso.[n][w][e]

[msg MSG_Izakaya_Entrance_Hou [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]C'因 gi稲 chi beve a quest'ora?[n]Devono passarsela male,[n]o non gli importa del lavoro...[n][w][e]

[msg MSG_Izakaya_Entrance_YOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Chiss稲 se un giorno diventerai[n]uno di quegli adulti.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Uhm... No, non ti riesco a[n]immaginare sottomesso ai superiori![n][w][e]

[msg MSG_Izakaya_Entrance_Gog [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ora 因 chiuso.[n]Immagino che siano in[n]pausa fino a stasera.[n][w][e]

[msg MSG_Curtain_Houkago [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]In cima a queste scale c'因[n]il mondo degli adulti, eh?[n]Aspetta. Non ne vale la pena.[n][w][e]

[msg MSG_Curtain [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Ora 因 chiuso, ma sono certo[n]che di notte il posto si[n]illumina a festa...[n][w][e]

[msg MSG_Iyashinsu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Vuoi scaricare un po' di[n]stress? So che ne hai bisogno,[n]ma... questo posto...[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Beh, ci sono io, giusto?[n]Anche se preferirei che non lo facessi,[n]puoi toccarmi un po' le zampe.[n][w][e]

[msg MSG_Koakuma [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Se cerchi una diavoletta,[n]non hai gi稲 Lady Ann?[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Ah, ma non farti fregare.[n]Le diavolette in questo[n]posto sono fin troppo reali![n][w][e]

[msg MSG_PetShop_Gogo [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Un negozio di animali...[n]No. No, questo posto[n]non mi piace per niente.[n][w][e]
[s][f 4 10 65535 0 0]Dopotutto, ho l'aspetto di[n]un gatto. Sbrighiamoci a[n]uscire e andiamo da un'altra parte.[n][w][e]

[msg MSG_PetShop [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Qui vendono anche i gatti,[n]e le gabbie sono cos淫 piccole...[n][w][e]
[s][f 4 10 65535 0 0]Solo a guardarlo mi sento male.[n]Andiamo altrove.[n][w][e]

[msg MSG_Stair_China [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Che ci fanno qui queste scale?[n]A Shinjuku ci sono negozi[n]a ogni angolo...[n][w][e]

[msg MSG_Hari [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Una clinica per l'agopuntura?[n]Uhm, qui le persone usano gli[n]aghi a scopi terapeutici...[n][w][e]
[s][f 4 10 65535 0 0]Scommetto che la gente di Shinjuku[n]viene qui per riprendersi[n]dalla stanchezza.[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 0 11018 65535 0]Non hai tempo[n]per giocare, Prigioniero![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torna in cella![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]Queste prove... credo che[n]tu possa superarle.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso la Stanza di Velluto[clr 0].[n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MSG_E24430100_NG_GOOUT_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Di l稲 si va alla stazione.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Dobbiamo trovare il posto in cui[n]ci aspetta quella giornalista[n]e recuperare qualche informazione![n][w][e]

[msg MSG_E24450100_NG_GOOUT_B [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]La stazione 因 poco pi迂 avanti.[n]Per tornare possiamo andare[n]a Shibuya e poi...[n][w][e]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Aspetta, non ci stiamo[n]dimenticando di Ryuji?[n][w][e]

[msg MSG_E24450100_GOOUT_AFTE [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]La stazione 因 poco pi迂 avanti.[n]Mi dispiace per Ryuji, ma[n]andiamo a casa.[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Allora, cambiamo linea a Shibuya[n]e poi... mmm. Lascio il resto[n]a te, [fName]![n][w][e]

[msg MSG_E70209000_NG_GOOUT_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2019 65535 0]Di l稲 non si va alla stazione?[n]Parliamo con i promoter[n]qui in giro.[n][w][e]

[msg MSG_E24430100_BAR_1st_00 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]Ehi, coso... Non siamo abbastanza[n]grandi per stare qui.[n]Sicuro che il posto sia questo?[n][w][e]

[msg MSG_E24430100_BAR_1st_00_2 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]Birra, whisky, vino...[n]La vita notturna passa per i bar.[n][w][e]

[msg MSG_E24430100_BAR_1st_00_3 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]Non 因 una buona idea andare[n]in uniforme... L'altra volta[n]ci hanno beccati...[n][w][e]

[sel SEL_E24430100_BAR_1st_00 top]
[s]Aspetta fuori.[e]
[s]Sei inutile.[e]

[msg MSG_E24430100_BAR_1st_00_4 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Sono venuto fino a Shinjuku[n]e non posso neanche entrare?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Vaaa bene. Ammazzer韻 il tempo[n]qui intorno... Quando avete finito,[n]fatemi sapere.[n][w][e]

[msg MSG_E24430100_BAR_1st_00_5 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]Tsk, non posso ribattere...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Mi dispiace, ma lascer韻[n]fare a voi. Io ammazzer韻[n]il tempo qui intorno.[n][w][e]

[msg MSG_E24450100_NG_BAR_BEF [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1172 0 0]Abbiamo ottenuto le informazioni[n]sul bersaglio. Raggiungiamo Ryuji.[n][w][e]

[msg MSG_E24450100_NG_BAR_AFT [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1181 0 0]Abbiamo ottenuto le informazioni[n]sul bersaglio. Torniamo a casa.[n][w][e]

[msg MSG_E70209000_NG_BAR_000 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2113 65535 0]Questo posto non sembra un[n]host club. Qui non c'因 nessuno,[n]parliamo con le persone fuori.[n][w][e]

[msg MSG_E24430100_CHK_CINEMA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, un cinema. Chiss稲 che[n]proiettano di bello![n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Beh, oggi non abbiamo tempo[n]per andarci.[n]Prima troviamo quel bar![n][w][e]

[msg MSG_E24450100_CHK_CINEMA [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Che cinema enorme.[n]La prossima volta portamici.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Raggiungiamo Ryuji e andiamo[n]a casa. Dove ci aspetta?[n][w][e]

[msg MSG_E24450100_CHK_CINEMA_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Che cinema enorme.[n]La prossima volta portamici.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Si sta facendo tardi,[n]andiamo a casa.[n]Da che parte 因 la stazione?[n][w][e]

[msg MSG_E70209000_NG_CINEMA_ [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2117 65535 0]Che cinema enorme...[n]Per韻 non credo che ci[n]troveremo dei promoter.[n][w][e]

[msg MSG_E24430100_CHK_FURNIT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7086 65535 0]Arredo d'interni...?[n]Uh, di notte 因 chiuso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torniamoci un'altra volta.[n]Adesso dobbiamo incontrare[n]quella giornalista.[n][w][e]

[msg MSG_E24450100_CHK_FURNIT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Sembra un negozio d'arredo di[n]interni. Al momento, per韻,[n]因 chiuso.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Comunque, pensiamo a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_FURNIT_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Sembra un negozio d'arredo di[n]interni. Potresti comprarci dei[n]mobili per arredare la tua camera.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Beh, ora comunque 因 chiuso.[n]Per oggi torniamo[n]a casa.[n][w][e]

[msg MSG_E70209000_NG_FURNITU [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2019 65535 0]Possiamo fare shopping un'altra[n]volta. Voglio ottenere informazioni[n]su Tsukasa il prima possibile.[n][w][e]

[msg MSG_E24430100_CHK_FLOWER [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Non ti serve niente[n]in questo negozio di fiori. Forza,[n]dobbiamo trovare quell'insegna.[n][w][e]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Cacchio, questo posto 因 aperto[n]fino alle cinque del mattino?[n]Chi compra fiori cos淫 tardi?[n][w][e]

[msg MSG_E24450100_CHK_FLOWER [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1164 0 0]Un negozio di fiori, eh?[n]Guardare tutti quei[n]fiori mi rilassa.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Comunque, pensiamo a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_FLOWER_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]L淫 ci sono tantissimi fiori.[n]Forse Lady Ann sarebbe felice[n]se gliene regalassi qualcuno...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Ah, ci penser韻 un'altra volta.[n]Prendiamo il treno e[n]andiamo a casa.[n][w][e]

[msg MSG_E70209000_NG_FLOWER_ [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2035 65535 0]Chiuso. Per ora proviamo a[n]recuperare informazioni.[n][w][e]

[msg MSG_E24430100_CHK_NOODLE [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7039 65535 0]Un ristorante cinese, eh?[n]為 strapieno...[n]Il cibo 因 davvero cos淫 buono qui?[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un momento, penseremo[n]dopo al cibo. Adesso dobbiamo[n]trovare quel bar.[n][w][e]

[msg MSG_E24450100_CHK_NOODLE [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1183 0 0]Che profumo delizioso...[n]Ed 因 pienissimo.[n]Sar稲 un locale gettonato![n][w][e]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 65535 1028 0 0]Comunque, sar稲 meglio trovare[n]Ryuji. Se lo lasciamo troppo tempo[n]da solo, si caccer稲 nei guai.[n][w][e]

[msg MSG_E24450100_CHK_NOODLE_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Che profumo delizioso...[n]Ed 因 pienissimo.[n]Sar稲 un locale gettonato![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Comunque, per oggi torniamo[n]a casa. Non dobbiamo far[n]preoccupare Lady Ann.[n][w][e]

[msg MSG_E70209000_NG_NOODLE0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2035 65535 0]為 chiuso. Pensiamo a[n]cercare dei promoter.[n][w][e]

[msg MSG_E24430100_CHK_NOODLE_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7024 65535 0]Caaacchio, un ramen bar.[n]Dopo aver finito, andiamo a[n]mangiare da qualche parte?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Per fortuna questo posto 因 sempre[n]aperto. Se mi capita di fare le ore[n]piccole ci vengo a mangiare.[n][w][e]

[msg MSG_E24450100_CHK_NOODLE_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Un ramen bar, eh?[n]I clienti stanno mangiando[n]in tutta tranquillit稲...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Comunque, pensiamo a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_NOODLE_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Hai fame, per caso?[n]Sbrighiamoci ad andare a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Sono sicuro che Lady Ann 因 in[n]pensiero, quindi incamminiamoci[n]verso la stazione.[n][w][e]

[msg MSG_E70209000_NG_NOODLE0_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2069 65535 0]Qui il cibo sembra delizioso, ma[n]possiamo venirci poi. Adesso la[n]priorit稲 sono le informazioni.[n][w][e]

[msg MSG_E24430100_CHK_PAWNSH [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Un banco dei pegni?[n]Hai qualcosa da[n]vendere?[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Fallo dopo, coso.[n]Sbrighiamoci a trovare quel[n]posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_CHK_PAWNSH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1168 0 0]Accidenti, qui vendono oggetti[n]di ogni genere.[n]Questi negozi guadagnano molto?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Oh, beh... per adesso[n]raggiungiamo Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_PAWNSH_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un banco dei pegni, eh? Vendono[n]proprio di tutto in[n]questo posto...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Beh, possiamo tornarci poi.[n]Adesso andiamo alla stazione[n]e torniamo a casa.[n][w][e]

[msg MSG_E70209000_NG_PAWNSHO [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2128 65535 0]Non credo che la persona[n]che cerchiamo sia in questo[n]banco dei pegni. Cerchiamo altrove.[n][w][e]

[msg MSG_E24430100_CHK_SUSHI_ [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7040 65535 0]Un sushi bar, eh?[n]Non 因 caro come posto?[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un giorno di questi ci mangeremo,[n]ma per adesso dobbiamo[n]trovare una pista.[n][w][e]

[msg MSG_E24430100_CHK_SUSHI__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Sushi di qualit稲 e costoso, eh?[n]Mmm, per ora riuscir韻[n]a resistere.[n][w][e]

[msg MSG_E24450100_CHK_SUSHI_ [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Oh, volevi offrirmi[n]un po' di sushi?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Ti ringrazio, ma al momento[n]dovremmo raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_SUSHI__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un ristorante di sushi, eh?[n]Sembra molto caro.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Comunque, non siamo lontani[n]dalla stazione? Sbrighiamoci[n]e torniamo a casa.[n][w][e]

[msg MSG_E70209000_NG_SUSHI_S [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2198 65535 0]Ti sta venendo fame?[n]Prima di mangiare, vorrei[n]raccogliere qualche informazione.[n][w][e]

[msg MSG_E24430100_CHK_FREE_I [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Un banco informazioni? Questo[n]posto ha un'aria sospetta...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non dobbiamo chiedere in giro per[n]trovarlo, no? Ci basta cercare il[n]cartello "Crossroads".[n][w][e]

[msg MSG_E24450100_CHK_FREE_I [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1166 0 0]Non hai bisogno di altre[n]indicazioni, vero? Abbiamo gi稲[n]le informazioni che ci servono.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Ora andiamo da Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_FREE_I_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Non hai bisogno di altre[n]indicazioni, vero? Abbiamo gi稲[n]le informazioni che ci servono.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Per tornare a casa dobbiamo[n]prendere il treno. Non abbiamo[n]gi稲 visto dei binari qui in giro?[n][w][e]

[msg MSG_E70209000_NG_FREE_IN [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2191 65535 0]C'因 scritto che 因 gratis, ma...[n]Faremmo prima a chiedere[n]direttamente a un promoter.[n][w][e]

[msg MSG_E24430100_CHK_DEADEN [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Uh, sembra che di qua[n]non ci siano negozi.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Andiamo da quella parte,[n]dove c'因 pi迂 gente.[n][w][e]

[msg MSG_E24450100_CHK_DEADEN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, dove stai andando?[n]Il cinema 因 proprio l淫.[n][w][e]

[msg MSG_E24450100_CHK_DEADEN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Sicuro che la stazione sia di qua?[n]Beh, visto che 因 la tua prima[n]volta qui, non posso biasimarti.[n][w][e]
[s][vp 1 0 0 0 0 0]Credo di aver visto dei binari[n]qui intorno. Da che parte erano...?[n][w][e]

[msg MSG_E70209000_NG_DEADEND [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2019 65535 0]Non ci stiamo allontanando dalla[n]zona trafficata? Troviamo un[n]promoter e chiediamo informazioni.[n][w][e]

[msg MSG_E24430100_CHK_DEADEN_2 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Ehi, non 因 la direzione sbagliata?[n]Non vedo molti negozi.[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torniamo indietro e cerchiamo[n]da un'altra parte![n][w][e]

[msg MSG_E24450100_CHK_DEADEN_3 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Non mi sembra la direzione giusta.[n]Il cinema non 因 pi迂 vicino[n]alla stazione?[n][w][e]

[msg MSG_E24450100_CHK_DEADEN_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Non ci stiamo allontanando dalla[n]stazione? Cos淫 finiremo[n]per smarrirci.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Mmm, da che parte era? Credo[n]di aver visto dei binari[n]da un'area aperta qui intorno...[n][w][e]

[msg MSG_E70209000_NG_DEADEND_2 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2129 65535 0]Di l稲 non sembrano esserci[n]molte persone. Torniamo indietro e[n]cerchiamo qualche promoter.[n][w][e]

[msg MSG_E24430100_CHK_DEADEN_3 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7193 65535 0]Non pensate che si trovi[n]in un posto con pi迂[n]negozi e persone?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torniamo indietro. Sono sicuro[n]che non 因 lontano.[n][w][e]

[msg MSG_E24450100_CHK_DEADEN_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Siamo davvero arrivati[n]da qui? Il cinema non 因[n]su un'altra strada?[n][w][e]

[msg MSG_E24450100_CHK_DEADEN_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Ehi, dove stai andando?[n]Credevo che saremmo[n]tornati alla stazione.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Posso capire che non ti orienti[n]perch姻 non sei mai stato qui,[n]ma da che parte era?[n][w][e]

[msg MSG_E70209000_NG_DEADEND_3 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2082 65535 0]Credo che sia la direzione[n]sbagliata. Non sarebbe meglio[n]tornare indietro?[n][w][e]

[msg MSG_E24430100_CHK_DEADEN_4 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Non credo che di qua[n]ci siano molti negozi.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]L'avremo superato? Torniamo[n]indietro, forse non[n]l'abbiamo visto![n][w][e]

[msg MND_E24450100_CHK_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Ryuji 因 vicino al cinema,[n]vero? Dovremmo tornare indietro.[n][w][e]

[msg MND_E24450100_CHK_DEADEN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Che motivo c'因 di venire[n]fin quaggi迂? Lady Ann si preoccuper稲[n]se non torniamo presto a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Sbrighiamoci a salire sul[n]treno. La stazione non era[n]nella direzione opposta?[n][w][e]

[msg MSG_E70209000_NG_DEADEND_4 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2113 65535 0]Chiss稲 cosa c'因 pi迂 avanti?[n]Beh, l淫 non troveremo alcun[n]promoter. Meglio tornare indietro.[n][w][e]

[msg MSG_E24430100_CHK_BOOK_S [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Una libreria?[n]Wow, perch姻 mi sento strano[n]al pensiero di entrarci?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Forse hanno roba ganza[n]da leggere. Andiamo a[n]dare un'occhiata?[n][w][e]

[msg MSG_E24430100_CHK_BOOK_S_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Adesso non c'因 tempo[n]per quello.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Lo farai dopo. Prima dobbiamo[n]incontrare quella giornalista![n][w][e]

[msg MSG_E24430100_CHK_BOOK_S_3 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gi稲, OK. Ci verremo[n]un'altra volta.[n][w][e]

[msg MSG_E24430100_CHK_BOOK_S_4 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Oh, quindi vuoi dare un'occhiata[n]a questo posto?[n][w][e]

[msg MSG_E24430100_CHK_BOOK_S_5 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Pi迂 tardi. Non possiamo permetterci[n]di perdere tempo.[n][w][e]

[msg MSG_E24450100_CHK_BOOK_S [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Questo negozio ha tantissimi libri[n]particolari. Potrebbe essere una[n]buona idea comprarne uno.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Comunque, per ora[n]raggiungiamo Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_BOOK_S_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Questo negozio ha tantissimi libri[n]particolari. Potrebbe essere una[n]buona idea comprarne uno.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Beh, non adesso comunque.[n]Lady Ann si star稲 preoccupando,[n]quindi andiamo a casa.[n][w][e]

[msg MSG_E70209000_NG_BOOK_ST [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 2111 65535 0]Veniamoci un'altra volta.[n]Oggi voglio pensare a[n]raccogliere altre informazioni.[n][w][e]

[msg MSG_E24430100_CHK_HARI_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7042 65535 0]Va bene la salute, ma farsi[n]bucherellare da degli aghi?[n]Deve fare malissimo![n][w][e]

[msg MSG_E24450100_CHK_HARI_B [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 65535 1040 0 0]Lascia perdere l'agopuntura.[n]Dobbiamo muoverci e[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_CHK_HARI_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_HARI_00 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2127 65535 0]Mmm, non credo che troveremo[n]la persona che cerchiamo in[n]questa clinica di agopuntura.[n][w][e]

[msg MSG_E24430100_AUTO_MACHI [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7037 65535 0]Ehi, non abbiamo tempo per le[n]pause. Sbrighiamoci a trovare[n]quel posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_AUTO_MACHI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_AUTO_MACHI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_AUTO_MA [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2129 65535 0]Possiamo pensarci dopo? Prima[n]recuperiamo qualche informazione.[n][w][e]

[msg MSG_E24430100_DEST_MACHI [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7044 65535 0]Quest'affare 因 rotto,[n]non possiamo usarlo...[n][w][e]

[msg MSG_E24450100_DEST_MACHI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_DEST_MACHI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_DEST_MA [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2159 65535 0]為 rotta. Chiss稲 se[n]qualcuno la aggiuster稲.[n][w][e]

[msg MSG_E24430100_HOME_SECUR [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Forza, sbrighiamoci a trovare[n]quel posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_HOME_SECUR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_HOME_SECUR_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_HOME_SE [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2155 65535 0]Non troveremo ci韻 che cerchiamo[n]in un'agenzia di sicurezza. Continuiamo[n]a cercare dei promoter.[n][w][e]

[msg MSG_E24430100_PACHINKO_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Forza, sbrighiamoci a trovare[n]quel posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_PACHINKO_B [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_PACHINKO_A [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_PACHINK [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2164 65535 0]L淫 ci sono molti clienti, ma[n]dubito che qualcuno vorr稲 parlare[n]con noi. Meglio cercare altrove.[n][w][e]

[msg MSG_E24430100_Izakaya_En [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Forza, sbrighiamoci a trovare[n]quel posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_Izakaya_En [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_Izakaya_En_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_Izakaya [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2191 65535 0]Qualcosa non va?[n]Dovremmo cercare[n]dei promoter.[n][w][e]

[msg MSG_E24430100_HostClubBo [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Forza, sbrighiamoci a trovare[n]quel posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_HostClubBo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_HostClubBo_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_HostClu [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2022 65535 0]Non vedo nomi sull'insegna.[n]Forse chiedendo a qualcuno[n]faremmo prima.[n][w][e]

[msg MSG_E24430100_Curtain_Iz [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Questo non 因 il "Crossroads".[n][w][e]

[msg MSG_E24450100_Curtain_Iz [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_Curtain_Iz_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_Curtain [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2191 65535 0]Qualcosa non va?[n]Troviamo qualche promoter[n]e chiediamogli informazioni.[n][w][e]

[msg MSG_E24430100_Izakaya_Iy [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Questo non 因 il "Crossroads".[n][w][e]

[msg MSG_E24450100_Izakaya_Iy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_Izakaya_Iy_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_Izakaya_2 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2036 65535 0]Pare che questo posto non c'entri[n]nulla con gli host.[n]Chiediamo a qualche promoter.[n][w][e]

[msg MSG_E24430100_Izakaya_Bi [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Questo non 因 il "Crossroads".[n][w][e]

[msg MSG_E24450100_Izakaya_Bi [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_Izakaya_Bi_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_Izakaya_3 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]Questo posto 因 chiuso.[n]Perch姻 non parliamo con[n]la gente per strada?[n][w][e]

[msg MSG_E24430100_Izakaya_Ko [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Questo non 因 il "Crossroads".[n][w][e]

[msg MSG_E24450100_Izakaya_Ko [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_Izakaya_Ko_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_Izakaya_4 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2117 65535 0]Qui offrono lezioni private?[n]O tutoraggio individuale?[n]Mmm, non perdiamo tempo.[n][w][e]

[msg MSG_E24430100_PetShop_00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Forza, sbrighiamoci a trovare[n]quel posto chiamato Crossroads![n][w][e]

[msg MSG_E24450100_PetShop_BE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_PetShop_AF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_PetShop [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2113 65535 0]Molti negozi sono chiusi[n]anche se 因 giorno, ma le[n]strade sono affollate.[n][w][e]

[msg MSG_E24430100_Stair_Chin [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]Uh. Non vedo alcuna insegna[n]con la scritta "Crossroads"...[n][w][e]

[msg MSG_E24450100_Stair_Chin [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, sbrighiamoci a[n]raggiungere Ryuji.[n][w][e]

[msg MSG_E24450100_Stair_Chin_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Torniamo a casa.[n]Sono sicuro che Lady Ann[n]inizia a essere in pensiero.[n][w][e]

[msg MSG_E70209000_NG_Stair_C [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2191 65535 0]Qualcosa non va?[n]Troviamo qualche promoter[n]e chiediamogli informazioni.[n][w][e]

[msg MSG_E70209100_Common_000 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 2191 65535 0]Qualcosa non va?[n]Troviamo qualche promoter[n]e chiediamogli informazioni.[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Lasciami entrare in cella.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]A quanto pare, vuoi essere[n]imprigionato. Posso esaudire[n]il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Sar韻 lieta di[n]esaudire il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Continua la tua lotta.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che c'因, Prigioniero?[n]Desideri tornare in prigione?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eheheh. Ti rimetter韻 al[n]tuo posto![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continua a lottare, Prigioniero.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ti condurr韻 dal mio padrone...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Voglio prepararmi.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora entra, per favore.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Io e il mio padrone[n]veglieremo su di te.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_CinemaBuyTicketSIBUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Ah, gi稲! Prima devi[n]comprare un biglietto.[n][w][e]

[msg MSG_CinemaCancel [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1003 65535 0]Hai cambiato idea?[n][w][e]

[msg MSG_CinemaOK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Il film sta per iniziare.[n]Andiamo a sederci.[n][w][e]

[msg MSG_CinemaWatched [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0][var 7]?[n]Ne ho avuto abbastanza di quello...[n]Torniamo un'altra volta.[n][w][e]

[msg MSG_CinemaBuyTicket [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Per vedere un film[n]devi comprare un biglietto.[n][w][e]

[msg MND_ParamEndInfo_Atama]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Miryoku]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Kiyou]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Dokyo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Yasas]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_ParamMoru_Atama [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MSG_ParamMoru_Miryoku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare il tuo[n][stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MSG_ParamMoru_Kiyou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MSG_ParamMoru_Dokyo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare il tuo[n][stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MSG_ParamMoru_Yasas [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Chiss稲 che film stanno[n]proiettando adesso...[n][w][e]

[msg MSG_Cinema_MoneyNG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Controlla il portafoglio.[n]Non hai abbastanza soldi.[n][w][e]

[msg MSG_CINEMA_MEMBER_NG [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Quante volte hai intenzione di[n]vedere lo stesso film?[n]Dacci un taglio...[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Wow, questo cinema 因 immenso![n]Chiss稲 che film stanno proiettando adesso...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questo dovrebbe essere un[n]cinema, giusto? Ma 因 vuoto...[n]Forse 因 chiuso.[n][w][e]

[msg MND_CINEMA_NOT_OPEN]
[s]Al momento il cinema[n]因 chiuso...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Non c'因 anima viva. Sembra[n]che non apra nemmeno[n]di sera. Che succede?[n][w][e]

[msg MSG_CINEMA_BOOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Visto che hai finito di leggere[n][clr 3]Anima da cineasta[clr 27], scommetto che[n]apprezzerai ancora di pi迂 il film.[n][w][e]

[msg MSG_COMMENT_LIST01_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un adolescente che[n]diventa milionario vincendo al quiz[n]"Le sedici domande"...[n][w][e]

[msg MSG_COMMENT_2ndINFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, 因 [var 7].[n]Vuoi rivederlo?[n][w][e]

[msg MSG_COMMENT_LIST02_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un eroe che[n]cerca di sgominare[n]crimine e corruzione.[n][w][e]

[msg MSG_COMMENT_LIST03_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo che fatica[n]a confessare i propri sentimenti[n]alla donna che ama.[n][w][e]

[msg MSG_COMMENT_LIST04_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo che cerca[n]di ricostruire la sua vita[n]dopo una lunga carcerazione.[n][w][e]

[msg MSG_COMMENT_LIST05_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo che deve entrare[n]nel suo appartamento ultraprotetto[n]dopo aver perso la chiave.[n][w][e]

[msg MSG_COMMENT_LIST06_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo con[n]l'incarico di pulire un enorme[n]grattacielo nel giorno di Natale.[n][w][e]

[msg MSG_COMMENT_LIST14_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un pap稲 vespa in[n]viaggio con l'amico ape per salvare[n]il figlio catturato dagli umani.[n][w][e]

[msg MSG_COMMENT_LIST07_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un gatto robot[n]che noleggia strumenti utili[n]ma a prezzo salatissimo.[n][w][e]

[msg MSG_COMMENT_LIST08_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]I soldi spariscono, il boss[n]ci rimette la pelle e le strade[n]di Tokyo si tingono di rosso...[n][w][e]

[msg MSG_COMMENT_LIST09_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia delle persone pi迂[n]inutili del mondo che formano una[n]squadra per combattere gli alieni.[n][w][e]

[msg MSG_COMMENT_LIST10_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di due uomini intrappolati in[n]una stanza con un elefante[n]imbizzarrito. Se la caveranno?[n][w][e]

[msg MSG_COMMENT_LIST15_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo insonne[n]che impazzisce dopo un certo[n]incontro in un negozio di kebab.[n][w][e]

[msg MSG_COMMENT_LIST11_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la tragica storia di[n]un boss della mafia che[n]adora i propri figli.[n][w][e]

[msg MSG_COMMENT_LIST12_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un tipo viaggia indietro nel[n]tempo e impara il ninjutsu, per[n]vendicare l'amico ucciso da un ninja.[n][w][e]

[msg MSG_COMMENT_LIST13_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di alcuni prigionieri[n]di guerra costretti a lavorare[n]duramente nonostante sia Natale.[n][w][e]

[msg MSG_COMMENT_LIST16_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di una donna pastore e di[n]uno psichiatra amante dei montoni[n]sulle tracce di un tosatore seriale.[n][w][e]

[msg MSG_COMMENT_LIST17_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un universitario che lotta[n]per la liberazione del suo[n]dormitorio oppresso.[n][w][e]

[msg MSG_COMMENT_LIST18_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo che si unisce per[n]caso a un circo, riuscendo a[n]fare carriera grazie al carisma.[n][w][e]

[msg MND_Sentou_ParamInfo_Chi]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo_]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Dok]
[s]Pare che guardando questo film[n]potrei migliorare il mio [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__2]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora il mio [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Yas]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__3]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Iro]
[s]Pare che guardando questo film[n]potrei migliorare il mio [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__4]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora il mio [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Kiy]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__5]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

