[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg DUMMY_MSG]
[s][vp 1 0 0 0 0 0]......[n][w][e]

[msg MSG_LAST_GREETING_MAIDCA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Questa caffetteria era meglio del[n]Leblanc per certi versi.[n]Torniamoci appena capita.[n][w][e]

[msg MSG_LAST_GREETING_MAIDCA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Adesso non hai tempo di giocare[n]con le maid. Andiamo a salutare[n]gli altri.[n][w][e]

[msg MSG_LAST_GREETING_ELECTR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Non puoi comprare roba elettronica[n]dopo il trasferimento? Andiamo[n]da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_OTAKU_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non c'因 bisogno di caricarsi[n]ancora di pi迂. Torneremo poi[n]in questo negozio.[n][w][e]

[msg MSG_LAST_GREETING_TOOL_S [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Hai fatto bene a comprare qui[n]gli strumenti. Le tue abilit稲 di[n]fabbricarne sono maturate.[n][w][e]

[msg MSG_LAST_GREETING_TOOL_S_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Ora non c'因 tempo di comprare[n]strumenti. Andiamo a salutare[n]gli altri.[n][w][e]

[msg MSG_LAST_GREETING_GAME_S [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Questi vecchi giochi erano super[n]divertenti. Continuiamo a giocarci[n]anche dopo il trasloco![n][w][e]

[msg MSG_LAST_GREETING_GAME_S_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Adesso non hai tempo di giocare.[n]Andiamo da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_CAPSUL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Ti piacevano, eh?[n]Anche a me.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Prendine una nuova serie[n]quando torni.[n][w][e]

[msg MSG_LAST_GREETING_CAPSUL_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Non c'因 tempo da perdere, sai?[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Ehi, non hai tempo di[n]prendere da bere.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Comprare una bibita[n]per 100 yen 因 stato un affare.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Speriamo che ci sia anche[n]nella tua citt稲.[n][w][e]

[msg MSG_LAST_GREETING_ILLUST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Quest'auto 因 rimasta parcheggiata[n]qui per un anno intero... Ecco[n]perch姻 ci hanno scritto sopra.[n][w][e]

[msg MSG_LAST_GREETING_TOOL_S_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Ehi, ci siamo appena sbarazzati[n]di un sacco di roba. Non[n]appesantiamo i bagagli, OK?[n][w][e]

[msg MSG_LAST_GREETING_OTAKU__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ehi, ci siamo appena sbarazzati[n]di un sacco di roba. Non[n]appesantiamo i bagagli, OK?[n][w][e]

[msg MSG_LAST_GREETING_ELECTR_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Ehi, ci siamo appena sbarazzati[n]di un sacco di roba. Non[n]appesantiamo i bagagli, OK?[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Da questa parte non c'因 nessuno che[n]conosci, vero? Andiamo a salutare[n]gli altri.[n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MND_0103]
[s]Chiss稲 cosa staranno facendo[n]gli altri...[n][w][e]

[msg MND_MAID_0103]
[s]C'因 scritto "Posti esauriti a[n]causa delle prenotazioni"...[n][w][e]
[s]Dovr韻 tornarci in seguito.[n][w][e]

[msg MND_AKIBA_GAME_0103]
[s]Sembra affollato a causa[n]del nuovo anno...[n][w][e]

[msg MND_FUKU_0103]
[s]Sembra che vendano[n]borse fortunate...[n][w][e]
[s]Non c'因 nulla di particolarmente[n]interessante.[n][w][e]

[msg MND_ELECTRO_SHOP_0103]
[s]Chiss稲 di cosa staranno parlando[n]Futaba e Sojiro.[n][w][e]
[s]Dovr韻 tornarci[n]in un'altra occasione.[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MND_0103to0108_Error_Bad]
[s]C'因 un disegno sull'auto...[n][w][e]
[s]Meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_GATE_DEAFULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Vuoi spostarti in[n]un'altra zona?[n][w][e]

[sel SEL_GATE_YESNO_moru top]
[s]S淫, andiamo.[e]
[s]No, non ancora.[e]

[msg MND_GATE_0103]
[s]Andiamo da un'altra parte...[n][w][e]

[msg MSG_MaidCafe_Start [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Un Maid Caf姻, eh?[n][w][e]

[msg MSG_MaidCafe_Start_Param [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Potresti acquisire un po' di[n][stIcon 1][clr 26][stLabel 1][clr 27] usufruendo del servizio[n]delle maid...[n][w][e]

[msg MND_Maid_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_Maid_ParamUpInfo]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 1][n]aumenter稲 presto...[n][w][e]

[msg MSG_MaidCafe_Start_1st [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vogliamo dare un'occhiata, per[n]provare? Stando al menu,[n]ti servono almeno 1.000 yen.[n][w][e]

[msg MSG_MaidCafe_Start_commo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hai [clr 2][var 0][clr 27] timbri.[n]Potrai ordinare dal menu speciale[n]una volta che ne avrai raccolti 20.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Vuoi dare un'occhiata al[n]Maid Caf姻? Servono[n]almeno 1.000 yen.[n][w][e]

[msg MSG_MaidCafe_Start_commo_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Hai [clr 2][var 0][clr 27] timbri.[n]Ne hai abbastanza per ordinare[n]dal menu speciale.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Vuoi tornare al Maid Caf姻?[n]Puoi ordinare dal menu[n]speciale, quindi 因 gratis.[n][w][e]

[msg MSG_MaidCafe_Start_commo_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hai [clr 2][var 0][clr 27] timbri.[n]Potrai ordinare dal menu speciale[n]una volta che ne avrai raccolti 20.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Di sabato c'因 il Maid Day.[n]Ricevi 4 timbri extra per ogni[n]ordinazione, un buon affare.[n][w][e]
[s]Vuoi dare un'occhiata al[n]Maid Caf姻? Servono[n]almeno 1.000 yen.[n][w][e]

[sel SEL_MaidCafe_In top]
[s]Diamogli un'occhiata![e]
[s]Lasciamo stare.[e]

[msg MSG_MaidCafe_Start_NotMo [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Uhm, non hai abbastanza soldi.[n]Torna quando avrai[n]le tasche piene.[n][w][e]

[msg MND_MaidCafe_ParamInfo]
[s][vp 1 0 0 0 0 0]Studiando il servizio[n]del Maid Caf姻 potrei[n]aumentare il mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_MaidCafe_ParamEndInf]
[s][vp 1 0 0 0 0 0]Non credo di poter migliorare[n]ancora il [stIcon 1][clr 26][stLabel 1][clr 27]studiando[n]il servizio del Maid Caf姻...[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Maid]
[s][vp 1 0 0 0 0 0]Ora puoi viaggiare velocemente[n][clr 6]verso il Maid Caf姻[clr 0] ad Akihabara.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_AKIB]
[s][vp 1 0 0 0 0 0]Ora puoi viaggiare velocemente[n][clr 6]verso la sala giochi[clr 0] ad Akihabara.[n][w][e]

[msg MSG_ELECTRO_SHOP_START [Commesso del negozio di elettronica]]
[s][f 4 23 1 9 3 5 65534 0][vp 8 2 1 0 9 0]Benvenuto! Abbiamo le ultime novit稲[n]nell'elettronica di consumo,[n]signore. Dia un'occhiata.[n][w][e]

[msg MSG_ELECTRO_SHOP_THANKS [Commesso del negozio di elettronica]]
[s][vp 8 2 1 0 9 0]Grazie mille![n]Torni a trovarci![n][w][e]

[msg MSG_ELECTRO_SHOP_NOTBUY [Commesso del negozio di elettronica]]
[s][vp 8 2 1 0 9 0]Torni presto![n][w][e]

[msg MSG_ElectroShop_Close [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Sembra che il negozio di[n]elettronica sia chiuso. Torniamo[n]durante il giorno.[n][w][e]

[msg MND_ElectroShop_Close]
[s]Il negozio di elettronica 因 chiuso.[n]Devo tornarci di giorno...[n][w][e]

[msg MSG_OTAKU_SHOP_START [Commessa del negozio Otaku]]
[s][vp 1 0 0 0 0 0]Bentornato a cas... Voglio dire,[n]benvenuto! Cerca qualcosa, signore?[n][w][e]

[msg MSG_OTAKU_SHOP_THANKS [Commessa del negozio Otaku]]
[s][vp 1 0 0 0 0 0]Grazie milleee.[n][w][e]

[msg MSG_OTAKU_SHOP_NOTBUY [Commessa del negozio Otaku]]
[s][vp 1 0 0 0 0 0]Torna a trovaaarci.[n][w][e]

[msg MSG_OtakuShop_Close [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Sembra chiuso.[n]Torniamo un'altra volta.[n][w][e]

[msg MND_OtakuShop_Close]
[s]Ora sembra chiuso.[n]Dovr韻 tornarci in seguito.[n][w][e]

[msg MSG_TOOL_SHOP_START [Commesso del negozio di componenti]]
[s][vp 1 0 0 0 0 0]Benvenuto. Qui vendiamo merce di[n]qualit稲. Stai attento quando[n]la usi, va bene?[n][w][e]

[msg MSG_TOOL_SHOP_END [Commesso del negozio di componenti]]
[s][vp 1 0 0 0 0 0]Torni presto![n][w][e]

[msg MSG_TOOL_SHOP_END_NOTBUY [Commesso del negozio di componenti]]
[s][vp 1 0 0 0 0 0]Oh, quindi non compri[n]nulla...[n][w][e]

[msg MSG_ToolShop_Close [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1182 65535 0]Uhm, sembra che a quest'ora[n]sia chiuso...[n][w][e]

[msg MND_ToolShop_Close]
[s]Ora sembra chiuso.[n]Dovr韻 tornarci in seguito.[n][w][e]

[msg MSG_GameShop_Close [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Il negozio di videogiochi 因 chiuso.[n]Ah, volevo entrare anch'io.[n]Torniamo un'altra volta.[n][w][e]

[msg MND_GameShop_Close]
[s]Il negozio di videogiochi 因 chiuso.[n]Ci torner韻 un'altra volta...[n][w][e]

[msg MSG_GameShop_NotHave [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Oooh, un negozio di retrogaming, eh?[n]Dovrebbero vendere vecchi giochi...[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Uhm, qui non possiamo giocare,[n]per韻. Servono una TV e[n]una console.[n][w][e]

[msg MND_GameShop_NotHave]
[s]Un negozio di retrogaming.[n]Vendono vecchi videogiochi...[n][w][e]
[s]Per韻 non ho niente per giocarci.[n]Mi servono una TV e una console...[n][w][e]

[msg GAMESHOP_SELECT [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Benvenuto! Ehi, ragazzo, sembri[n]molto giovane. Ti interessano i[n]giochi storici?[n][w][e]

[msg GAMESHOP_THANKS [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Grazie mille.[n]Spero che ti divertirai, giocandoli.[n][w][e]

[msg GAMESHOP_NOT_BUY [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Torna a trovarmi.[n][w][e]

[msg GAMESHOP_GAME_POSTC_GOU [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e la password...![n]Hai finito "Power Intuition"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]Oooh, quella trama profonda e la[n]caratterizzazione dei personaggi![n][w][e]
[s][vp 1 0 0 0 0 0]Con l'audio incredibile e un[n]sistema di combattimento unico![n][w][e]
[s][vp 1 0 0 0 0 0]為 un titolo all'avanguardia,[n]tra i giochi di combattimento![n]Un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GAME_POSTC_PUN [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e la password...![n]Hai finito "Punch Ouch"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]Essendo vecchio ha una[n]grafica datata, ma il sistema[n]di gioco 因 davvero realistico...[n][w][e]
[s][vp 1 0 0 0 0 0]Giocandolo ti accorgi che il[n]sistema di combattimento simula[n]le vere tattiche del pugilato![n][w][e]
[s][vp 1 0 0 0 0 0]為 un punto fermo per i giochi di[n]pugilato. S淫, un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GAME_POSTC_GOE [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e la password...![n]Hai finito "Legend of Gambla[n]Goemon"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]La grafica...[n]Trasmette in modo perfetto[n]l'ambientazione infernale...![n][w][e]
[s][vp 1 0 0 0 0 0]Quando giochi, suoni e musica[n]creano una suspense incredibile![n][w][e]
[s][vp 1 0 0 0 0 0]為 un gioco d'azzardo fantastico.[n]Un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GAME_POSTC_AKA [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e la password...![n]Hai finito "Train of Life"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]Fantastico! Non solo hanno aggiunto[n]il movimento con i dadi,[n]ma anche la gestione delle risorse![n][w][e]
[s][vp 1 0 0 0 0 0]E quei personaggi di ostacolo[n]trasmettono l'odio e l'amore con cui[n]gli sviluppatori affrontano la vita![n][w][e]
[s][vp 1 0 0 0 0 0]Si ispira al sugoroku, ma 因[n]un gioco rivoluzionario,[n]a modo suo. 為 un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GAME_POSTC_REN [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e la password...![n]Uooooo... Hai finito[n]"Star Forneus"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]Questo 因 il primo gioco con la[n]funzionalit稲 "fuoco rapido"! Oh, e ha[n]lanciato la mania dei record![n][w][e]
[s][vp 1 0 0 0 0 0]Gi稲, i giocatori cercavano tutti i[n]segreti delle meccaniche[n]di gioco, per superarsi a vicenda![n][w][e]
[s][vp 1 0 0 0 0 0]為 il gioco che ha definito[n]il genere degli sparatutto![n]為 un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GAME_POSTC_GOL [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e la password...![n]Hai finito "Pro Golfer[n]Sarutahiko"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]Prima che uscisse, si pensava che[n]un videogioco sul golf fosse impossibile.[n]Questo ha sconvolto tutti![n][w][e]
[s][vp 1 0 0 0 0 0]La musica, gli effetti sonori...[n]Il vero golf non ha effetti sonori[n]tanto belli![n][w][e]
[s][vp 1 0 0 0 0 0]為 un apripista nel genere dei[n]simulatori di golf. Un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GAME_POSTC_MAN [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]Quella cartolina e[n]la password...! Hai finito[n]"Featherman Seeker"?!?[n][w][e]
[s][vp 1 0 0 0 0 0]Un sistema innovativo in cui non[n]controlli semplicemente l'eroe,[n]ma diventi tu stesso l'eroe![n][w][e]
[s][vp 1 0 0 0 0 0]為 diventato ben pi迂 di un semplice[n]gioco di Featherman e ha conquistato[n]una marea di fan![n][w][e]
[s][vp 1 0 0 0 0 0]Un gioco davvero anticonformista.[n]Un capolagodo... cio因, un capolavoro![n][w][e]
[s][vp 1 0 0 0 0 0]Oh, sono rimasti alcuni premi[n]dell'epoca. Posso scambiarli[n]con quella cartolina![n][w][e]

[msg GAMESHOP_GiftInfoEnd [Commesso del negozio di videogiochi]]
[s][vp 1 0 0 0 0 0]...Ah, scusa. Mi sono esaltato senza[n]rendermene conto. Vuoi vedere[n]qualche gioco?[n][w][e]

[msg MSG_CAPSULE_MACHINE_STAR [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Cos'因 questo mostro?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un distributore Gacha?[n]Oh, quindi con 500 yen puoi[n]ottenere questi personaggi...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Perch姻 non mettiamo alla[n]prova la tua fortuna?[n][w][e]

[msg MND_CAPSULE_MACHINE_STAR]
[s]Questo mostro 因...[n][w][e]
[s]Un distributore Gachapon. Ogni[n]tentativo costa 500 yen...[n][w][e]
[s]Cosa dovrei fare...?[n][w][e]

[sel MSG_CAPSULE_MACHINE_SEL top]
[s]Facciamolo.[e]
[s]Lasciamo stare.[e]

[msg MSG_CAPSULE_MACHINE_STAR_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Vuoi provare il[n]distributore Gacha?[n][w][e]

[msg MSG_CAPSULE_MACHINE_NOMO [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]...Uhm? Non hai abbastanza[n]soldi...[n][w][e]

[msg MSG_CAPSULE_MACHINE_RESU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 uscita una capsula... 為...[n][w][e]

[msg MSG_CAPSULE_ATARI_06 [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 2 1 53138 65535 0]Sulla capsula c'因 scritto che 因[n][clr 2]super rara[clr 27]! S-Sei incredibile![n][w][e]

[msg MSG_CAPSULE_ATARI_05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 53140 65535 0]Sulla capsula c'因 scritto che 因[n][clr 2]rara[clr 27]! Dev'essere opera del karma...[n]Ho fatto il bravo, dopotutto.[n][w][e]

[msg MSG_CAPSULE_ATARI_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Sulla capsula c'因 scritto che 因[n][clr 2]non comune[clr 27]. Non 因 una gran vittoria,[n]ma non 因 nemmeno cos淫 male.[n][w][e]

[msg MSG_CAPSULE_ATARI_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Sulla capsula c'因 scritto che 因[n][clr 2]non comune[clr 27]. Non 因 una gran vittoria,[n]ma non 因 nemmeno cos淫 male.[n][w][e]

[msg MSG_CAPSULE_ATARI_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53139 65535 0]Sulla capsula c'因 scritto che 因[n][clr 2]comune[clr 27]. Beh, 因 abbastanza sfigata...[n][w][e]

[msg MSG_CAPSULE_ATARI_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53141 65535 0]Sulla capsula c'因 scritto che 因[n][clr 2]comune[clr 27]. Beh, 因 abbastanza sfigata...[n][w][e]

[msg MSG_CAPSULE_End1st [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]*sigh* Non capisco. Perch姻 la[n]gente vuole questa roba?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Siamo ad Akihabara, giusto?[n]Forse qui troveremo qualcuno[n]che possa volere questi Gacha.[n][w][e]

[msg MSG_DEADEND_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Non ha senso andare cos淫 lontano.[n]Se usciamo per fare due passi,[n]restiamo in zona.[n][w][e]

[msg MSG_DEADEND]
[s]Non devo fare niente[n]pi迂 avanti.[n][w][e]

[msg MSG_ILLUST_CAR_moru [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Ehi, guarda.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Qualcuno ha deturpato questa[n]macchina. Che crudelt稲...[n][w][e]

[msg MSG_ILLUST_CAR]
[s]Che sia una di quelle...[n]macchine degli anime?[n][w][e]
[s]Il personaggio di un anime[n]decora l'intera auto...[n][w][e]

[msg MSG_TOOL_SHOP_SHELF01_mo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Qui hanno tanti[n]attrezzi industriali. Chiss稲[n]a cosa servono...[n][w][e]

[msg MSG_TOOL_SHOP_SHELF01]
[s]Ci sono file e file di strumenti.[n][w][e]
[s]Chiss稲 a cosa servono...[n][w][e]

[msg MSG_TOOL_SHOP_SHELF02_mo [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]C'因 scritto che 因 in offerta,[n]ma non ho idea di quanto[n]costi normalmente...[n][w][e]

[msg MSG_TOOL_SHOP_SHELF02]
[s]Sembrano in offerta, ma...[n][w][e]
[s]Non so quale sia il prezzo[n]di mercato...[n][w][e]

[msg MSG_TOOL_SHOP_SHELF03_mo [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]為 tutto impolverato.[n]Immagino che quest'affare[n]sia in offerta da molto tempo...[n][w][e]

[msg MSG_TOOL_SHOP_SHELF03]
[s]Quanta polvere... Sar稲 un secolo[n]che questi oggetti sono sulla[n]mensola...[n][w][e]

[msg MSG_OTAKU_SHOP_SHELF_mor [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, questo 因 abbastanza[n]econom...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Aspetta, i prodotti sono tutti[n]uguali. Sar稲 quello[n]che non sono riusciti a vendere?[n][w][e]

[msg MSG_OTAKU_SHOP_SHELF]
[s]Costano davvero poco...[n][w][e]
[s]......[n][w][e]
[s]Sono tutti uguali...[n][w][e]

[msg MSG_ELECTRO_SHOP_SHELF_m [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Qui vendono elettronica di[n]consumo straniera.[n]Perch姻 costa cos淫 poco?[n][w][e]

[msg MSG_ELECTRO_SHOP_SHELF]
[s]Pare che qui vendano anche[n]elettronica di consumo straniera...[n][w][e]
[s]Come fa a costare cos淫 poco...?[n][w][e]

[msg MSG_ELECTRO_SHOP_SHELF01]
[s]Pare che qui vendano anche[n]elettronica di consumo straniera,[n]ma 因 possibile che costi cos淫 poco?[n][w][e]
[s]Comunque, meglio andare a[n]controllare gli altri...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MND_Juice_Start]
[s]Forse dovrei prendere una bevanda...[n][w][e]

[msg MSG_Juice_Start100 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]C'因 scritto che tutti i prodotti di[n]questo distributore costano[n]100 yen. Vuoi qualcosa da bere?[n][w][e]

[msg MND_Juice_Start100]
[s]Questo distributore vende[n]tutto a 100 yen. Forse[n]dovrei comprare una bibita...[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MND_Juice_SoldOut [Morgana]]
[s]Tutto esaurito...[n][w][e]
[s]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MND_Juice_AllBuy [Morgana]]
[s]Tutto esaurito...[n][w][e]
[s]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MND_Juice_HeatIsland]
[s]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MSG_Juice_Akiba_Start [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]...Questo distributore vende[n]delle strane bevande.[n][w][e]

[msg MND_Juice_Akiba_Start]
[s]Ci sono dei succhi particolari...[n][w][e]

[msg MSG_VELVET_GIRL_LOUD01 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 1 11018 65535 0]Non hai tempo[n]per giocare, Prigioniero![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Torna in cella![n][w][e]

[msg MSG_VELVET_GIRL_Lavenza [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55422 65535 0]Queste prove... credo che[n]tu possa superarle.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_VELV]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso la Stanza di Velluto[clr 0].[n][w][e]

[msg DUMMY_000 [dummy]]
[s]テスト[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]Lasciami entrare in cella.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]A quanto pare, vuoi essere[n]imprigionato. Posso esaudire[n]il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Sar韻 lieta di[n]esaudire il tuo desiderio...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Continua la tua lotta.[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che c'因, Prigioniero?[n]Desideri tornare in prigione?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eheheh. Ti rimetter韻 al[n]tuo posto![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continua a lottare, Prigioniero.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ti condurr韻 dal mio padrone...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Voglio prepararmi.[e]
[s]Non voglio entrare.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora entra, per favore.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Io e il mio padrone[n]veglieremo su di te.[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

