[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_CHK_GATE]
[s][vp 1 0 0 0 0 0]Devo andare a Shibuya[n]con la linea Ginza...?[n][w][e]

[msg MSG_CHK_GATE_KAMO]
[s][vp 1 0 0 0 0 0]Dove devo andare, in treno...?[n][w][e]

[sel TRAIN_KAMO top]
[s]Vado a Shibuya.[e]
[s]Vado a Yongen-Jaya.[e]
[s]Lasciamo stare.[e]

[msg MND_CO_NG_COMMON_000]
[s][vp 1 0 0 0 0 0]Non credo di avere tempo[n]per fare deviazioni...[n][w][e]

[msg MND_ARRIVE_SCHOOL_2ND]
[s][vp 1 0 0 0 0 0]Oggi dovrei riuscire[n]ad arrivare a scuola puntuale...[n][w][e]
[s][vp 1 0 0 0 0 0]Al termine delle lezioni[n]devo andare sul tetto. Di certo[n]ci sar稲 anche Ryuji...[n][w][e]

[msg MND_ARRIVE_SCHOOL_3RD]
[s][vp 1 0 0 0 0 0]Beh, a quanto pare[n]sono arrivato puntuale...[n][w][e]
[s][vp 1 0 0 0 0 0]Al termine delle lezioni devo[n]trovare Ryuji, per parlare[n]delle nostre prossime mosse...[n][w][e]

