[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_CHK_GATE]
[s]電園都市線に乗って渋谷に[n]向かおうか...[n][w][e]

[msg MSG_CHK_GATE_KAMO]
[s]電車に乗ってどこに行こうか...[n][w][e]

[sel TRAIN_KAMO top]
[s]渋谷[e]
[s]蒼山一丁目[e]
[s]やめる[e]

[msg MSG_SPOT_TUTO01 [Morgana]]
[s]とうちゃーく。[n][w][e]
[s]さあて、どちらに行くかだけど...[n][w][e]

[msg MSG_SPOT_TUTO02 [Morgana]]
[s]荻窪も原宿も初めてだよね、行くの。[n]だったら誰か誘ってみれば?[n][w][e]
[s]普段と違う場所で過ごすことで[n]いつもより仲良くなれるかもね。[n][w][e]
[s]場所ごとに適した相手は[n]ワガハイが選んじゃうよ。[n][w][e]
[s]坊ちゃんじゃ、見当違いの[n]相手を選びそうだからね![n][w][e]

[msg MSG_SPOT_TUTO_PC02]
[s]Dove dovrei andare...?[n][w][e]

[sel MSG_SPOT_TUTO_SEL01 top]
[s]荻窪(ラーメン屋)[e]
[s]原宿(竹下通り)[e]

[msg MSG_SPOT_TUTO03 [Morgana]]
[s]荻窪かぁ。[n]そこなら...[n][w][e]
[s]ラーメンが好きそうな...[n][w][e]
[s]リュージがいいんじゃないかな。[n][w][e]

[sel MSG_SPOT_TUTO_SEL02 top]
[s]竜司に連絡をとる[e]
[s]考え直す[e]

[msg MSG_SPOT_TUTO_PC03]
[s]竜司に電話してみるか...[n][w][e]

[msg MSG_SPOT_TUTO_RYUJI01 [Ryuji]]
[s]ふわあ...おう、主人公か。[n]どうしたよ。[n][w][e]
[s]あん? ラーメン屋?[n]荻窪は遠いが...絶品か。[n][w][e]
[s]よーっし! 行くか、荻窪![n]ラーメン食おうぜ![n][w][e]
[s]1時間後に渋谷地下街に集合な。[n]そんじゃ、またな。[n][w][e]

[msg MSG_SPOT_TUTO04 [Morgana]]
[s]うんうんオッケーもらえてよかったね。[n]渋谷に行こう![n][w][e]

[msg MSG_SPOT_TUTO05 [Morgana]]
[s]原宿かぁ。[n]そこなら...[n][w][e]
[s]オシャレに興味がありそうな...[n][w][e]
[s]アンちゃんかな。[n][w][e]

[sel MSG_SPOT_TUTO_SEL03 top]
[s]アンに連絡をとる[e]
[s]考え直す[e]

[msg MSG_SPOT_TUTO_PC04]
[s]アンに電話してみるか...[n][w][e]

[msg MSG_SPOT_TUTO_ANN01 [Ann]]
[s]ん、なぁに?[n][w][e]
[s]竹下通り?[n]原宿ね...[n][w][e]
[s]いいよ、ヒマしてたし。[n]遊ぼうか。[n][w][e]
[s]1時間後に渋谷地下街に集合ね。[n]よろー。[n][w][e]

[msg MSG_SPOT_TUTO06 [Morgana]]
[s]うんうんオッケーもらえてよかったね。[n]渋谷に行こう![n][w][e]

[msg MSG_SPOT_TUTO07 [Morgana]]
[s]ゆーじゅーふだん。[n]だニャ。[n][w][e]

[msg DrugStore_NOTOPEN]
[s]Questa 因 la farmacia[n]"Le medicine di Jutaro".[n][w][e]
[s]Qui non vendono solo[n]medicine, ma anche detersivi[n]e altri prodotti di uso quotidiano.[n][w][e]
[s]Al momento non c'因 nulla[n]che vorrei comprare...[n][w][e]

[msg DrugStore_SELECT [Cameriere]]
[s]Benvenuto![n][w][e]

[msg DrugStore_THANKS [Cameriere]]
[s]Grazie mille![n]Speriamo di rivederti molto,[n]molto presto![n][w][e]

[msg DrugStore_NOT_BUY [Cameriere]]
[s]Torna a trovarci![n][w][e]

[msg DrugStore_SOLDOUT [Cameriere]]
[s]Mi dispiace taaanto.[n]Abbiamo esaurito le scorte[n]di... tutto.[n][w][e]

[msg MSG_BATTING_CENTER_KF_01]
[s]Al secondo piano di questo posto[n]ci sono le gabbie di battuta, ma[n]al momento le stanno [clr 2]ristrutturando[clr 27].[n][w][e]
[s]Sembra che riapriranno[n]nel mese di maggio.[n]Ci torner韻...[n][w][e]

[msg MSG_BATTING_CENTER_KF_02 [Morgana]]
[s]Oh, al secondo piano ci sono[n]delle gabbie di battuta. Ho sentito che al momento[n]le stanno [clr 2]ristrutturando[clr 27], per韻.[n][w][e]
[s]A quanto pare riapriranno[n]a maggio. Torniamo quando[n]avranno riaperto.[n][w][e]

[msg MSG_BATTING_CENTER_NG [Morgana]]
[s]Oh, al secondo piano ci sono[n]le gabbie di battuta. Ho sentito che al momento[n]le stanno [clr 2]ristrutturando[clr 27], per韻.[n][w][e]
[s]A quanto pare riapriranno[n]a maggio. Torniamo quando[n]avranno riaperto.[n][w][e]

[msg MSG_BATTING_CENTER [Morgana]]
[s]Oh, al secondo piano ci sono[n]le gabbie di battuta. Puoi migliorare[n]la tua [clr 1]Agilit稲[clr 27] pagando [clr 2]500 yen[clr 27].[n][w][e]

[msg MSG_BATTING_CENTER_POLIS [Morgana]]
[s]Inoltre, stai andando alla grande.[n]Ormai potresti aver sviluppato i[n][clr 2]Riflessi da battitore[clr 27].[n][w][e]

[msg MSG_BATTING_CENTER_NO_PO [Morgana]]
[s]Se ti allenerai abbastanza svilupperai[n]i [clr 2]Riflessi da battitore[clr 27] e potrai[n]fare un fuori campo.[n][w][e]

[msg MSG_BATTING_CENTER_CHK [Morgana]]
[s]Beh, vuoi passare[n]un po' di tempo qui alla[n]gabbia di battuta?[n][w][e]

[sel SEL_BATTING_CENTER_CHK top]
[s]Gioca.[e]
[s]No, meglio andare.[e]

[msg MSG_BATTING_CENTER_NO_MO [Morgana]]
[s]...Aspetta, non hai[n]abbastanza soldi. Cavolo, li[n]hai gi稲 spesi tutti?[n][w][e]

[msg MND_OldCinema]
[s]Sembra un vecchio cinema,[n]ma credo che abbia[n]gi稲 chiuso...[n][w][e]

[msg MSG_OldCinema [Morgana]]
[s]為 un vecchio cinema.[n]Purtroppo, sembra che[n]abbia gi稲 chiuso.[n][w][e]

[msg MSG_OldCinema_KF_01]
[s]Sembra un vecchio[n]cinema.[n][w][e]
[s]Ora non posso fermarmi.[n]Torner韻 volentieri[n]un'altra volta.[n][w][e]

[msg MSG_OldCinema_KF_02 [Morgana]]
[s]Oh, 因 un vecchio cinema.[n][w][e]
[s]Ora non abbiamo tempo per[n]fermarci, purtroppo. Lo[n]faremo un'altra volta.[n][w][e]

[msg MSG_OldCinema_H_01]
[s]為 un vecchio cinema.[n]Il tema di questa settimana sono[n]i film horror.[n][w][e]
[s]Pagando [clr 2]1.500 yen[clr 27] per guardare[n]un film horror, potrei[n]aumentare il mio [clr 1]Coraggio[clr 27].[n][w][e]

[msg MSG_OldCinema_H_02]
[s]Oggi passer韻 un po'[n]di tempo qui...[n][w][e]

[msg MSG_OldCinema_H_03 [Morgana]]
[s]為 un vecchio cinema.[n]Questa settimana proietteranno[n]una selezione di film horror.[n][w][e]
[s]Pagando [clr 2]1.500 yen[clr 27] per guardare[n]un film horror, aumenterai[n]il tuo [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MSG_OldCinema_H_04 [Morgana]]
[s]Oh, oggi pensavi di passare[n]del tempo qui?[n][w][e]

[msg MSG_OldCinema_D_01]
[s]為 un vecchio cinema.[n]Questa settimana 因 dedicata[n]ai film di fantascienza.[n][w][e]
[s]Pagando [clr 2]1.500 yen[clr 27] per guardare[n]un film di fantascienza, potrei[n]migliorare il mio [clr 1]Intuito[clr 27].[n][w][e]

[msg MSG_OldCinema_D_02]
[s]Oggi passer韻 un po'[n]di tempo qui...[n][w][e]

[msg MSG_OldCinema_D_03 [Morgana]]
[s]為 un vecchio cinema.[n]Questa settimana proietteranno[n]una selezione di film di fantascienza.[n][w][e]
[s]Pagando [clr 2]1.500 yen[clr 27] per guardare[n]un film di fantascienza, potrai[n]migliorare il tuo [clr 1]Intuito[clr 27].[n][w][e]

[msg MSG_OldCinema_D_04 [Morgana]]
[s]Oh, oggi pensavi di passare[n]del tempo qui?[n][w][e]

[sel SEL_OldCinema_01 top]
[s]Guardiamo un film.[e]
[s]Non importa, andiamo.[e]

[msg MSG_OldCinema_NG_01]
[s]...Un momento. Temo di[n]non avere abbastanza soldi.[n][w][e]

[msg MSG_OldCinema_TICKET_02 [Morgana]]
[s]Ora che ci penso, il capo non[n]ti aveva dato un biglietto[n]omaggio per il cinema?[n][w][e]
[s]Quindi puoi guardare[n]un film senza pagare. Che fortuna![n][w][e]

[msg MSG_OldCinema_TICKET_01]
[s]Oh, giusto, il capo mi ha dato[n]un biglietto omaggio per un film.[n][w][e]
[s]Posso entrare e godermi[n]un film senza pagare...[n][w][e]

[msg MSG_OldCinema_NG_02 [Morgana]]
[s]...Aspetta, non hai[n]abbastanza soldi. Cavolo, li[n]hai gi稲 spesi tutti?[n][w][e]

[msg MSG_OldCinema_night_01]
[s]Sembra che questo posto[n]sia chiuso, la sera. Devo[n]passare di giorno...[n][w][e]

[msg MSG_OldCinema_night_02 [Morgana]]
[s]Credo che questo posto sia chiuso,[n]la sera. Perch姻 la prossima volta[n]non ci torni di giorno?[n][w][e]

[msg MSG_OldCinema_test_mes]
[s] α5範囲外対応メッセージ。[n]4/18~24と4/25~31以外はメッセージ対応していません。[n][w][e]

[msg MSG_KARAOKE_KF_01]
[s]為 un negozio affiliato a un[n]famoso karaoke, ma 因 ancora[n]chiuso. Apre al tramonto.[n][w][e]

[msg MSG_KARAOKE_KF_02 [Morgana]]
[s]200 yen per mezz'ora?[n]Anche per cantare si[n]deve pagare.[n][w][e]

[msg MSG_KARAOKE_arbeit_no_ch [Morgana]]
[s]200 yen per mezz'ora?[n]Anche per cantare si[n]deve pagare.[n][w][e]

[msg MSG_KARAOKE_NG_night [Morgana]]
[s]Ricordo male, o avevi fatto[n]domanda qui per lavorare part-time?[n]Devi lavorare oggi?[n][w][e]
[s]Aspetta, 因 ancora presto.[n]Per lavorare devi venire[n]qui la sera.[n][w][e]

[msg MSG_KARAOKE_NG_shift [Morgana]]
[s]Ricordo male, o avevi fatto[n]domanda qui per lavorare part-time?[n]Devi lavorare oggi?[n][w][e]
[s]Oh, non sei di turno.[n]C'因 scritto che lavori il marted淫,[n]il gioved淫 e il sabato.[n][w][e]

[msg MSG_KARAOKE_CHK [Morgana]]
[s]Oggi puoi lavorare qui.[n][w][e]
[s]Ci sono diversi clienti con cui[n]non sar稲 facile avere a che[n]fare, ma migliorerai la tua [clr 1]Agilit稲[clr 27].[n][w][e]

[msg MSG_KARAOKE_POLISH [Morgana]]
[s]Inoltre, non hai quasi finito il[n]periodo di formazione? Potrebbe[n]succedere qualcosa di bello.[n][w][e]

[msg MSG_KARAOKE_NO_POLISH [Morgana]]
[s]Se continuerai a lavorare, finirai[n]il periodo di formazione e potrebbe[n]succedere qualcosa di bello.[n][w][e]

[msg MSG_KARAOKE_CHK_START [Morgana]]
[s]Allora, cosa vuoi fare? Oggi[n]lavorerai qui?[n][w][e]

[sel SEL_KARAOKE_CHK top]
[s]Andiamo a lavorare.[e]
[s]Lavoriamo un altro giorno.[e]

[msg MSG_KARAOKE_01]
[s]Oh, quindi questi sono poster[n]di idol e gruppi musicali[n]famosi in questo periodo...[n][w][e]

[msg MSG_KARAOKE_02 [Morgana]]
[s]Oh, quindi questi sono poster[n]di idol e gruppi musicali[n]famosi in questo periodo...[n][w][e]

[msg MSG_CHK_KEITAI_SHOP]
[s]為 un negozio di telefoni cellulari.[n]Pur essendo piccolo, ha[n]tantissimi modelli.[n][w][e]
[s]Eh? Un membro dello staff ci[n]sta osservando. Meglio andare via,[n]prima che qualcuno si insospettisca.[n][w][e]

[msg MSG_KONBINI_KF_01]
[s]為 un negozio affiliato a un[n]convenience store che[n]vedo spesso.[n][w][e]

[msg MSG_KONBINI_KF_02 [Morgana]]
[s]為 pieno di convenience store.[n]Non ce n'因 uno anche[n]dietro casa?[n][w][e]

[msg MSG_KONBINI_arbeit_no_ch [Morgana]]
[s]為 pieno di convenience store.[n]Non ce n'因 uno anche[n]dietro casa?[n][w][e]

[msg MSG_KONBINI_NG_night [Morgana]]
[s]Se non ricordo male, hai fatto[n]domanda per lavorare qui.[n]Oggi devi lavorare?[n][w][e]
[s]Aspetta, ora 因 troppo tardi.[n]Devi tornare domani[n]dopo la scuola.[n][w][e]

[msg MSG_KONBINI_NG_shift [Morgana]]
[s]Se non ricordo male, hai fatto[n]domanda per lavorare qui.[n]Oggi devi lavorare?[n][w][e]
[s]Aspetta, non sei di turno.[n]Qui dice che lavori il[n]luned淫, il mercoled淫 e il sabato.[n][w][e]

[msg MSG_KONBINI_CHK [Morgana]]
[s]Oggi puoi lavorare qui.[n][w][e]
[s]Il responsabile sembra stravolto.[n]Il tuo [clr 1]Intuito[clr 27] potrebbe affinarsi, con[n]un assaggio della vita adulta.[n][w][e]

[msg MSG_KONBINI_POLISH [Morgana]]
[s]Inoltre, non hai quasi finito il[n]periodo di formazione? Potrebbe[n]succedere qualcosa di bello.[n][w][e]

[msg MSG_KONBINI_NO_POLISH [Morgana]]
[s]Se continuerai a lavorare, finirai[n]il periodo di formazione e potrebbe[n]succedere qualcosa di bello.[n][w][e]

[msg MSG_KONBINI_CHK_START [Morgana]]
[s]Allora, cosa vuoi fare? Oggi[n]lavorerai qui?[n][w][e]

[sel SEL_KONBINI_CHK top]
[s]Andiamo a lavorare.[e]
[s]Lavoriamo un altro giorno.[e]

[msg MSG_CHK_KINKEN_SHOP]
[s]Ci sono borse e accessori in[n]esposizione. Qui vendono anche[n]i biglietti della lotteria.[n][w][e]
[s]Per comprare un biglietto di[n]questa lotteria, per韻, bisogna[n]avere almeno 18 anni.[n][w][e]

[msg MSG_CHK_STAND_SOBA]
[s]Gli avventori del locale mangiano[n]la soba. Il profumo delizioso della[n]zuppa di miso satura l'aria.[n][w][e]

[msg MSG_CRAMMER_KF_01]
[s]A quanto pare, al secondo piano[n]di questo posto c'因[n]un corso privato.[n][w][e]

[msg MSG_CRAMMER_KF_02 [Morgana]]
[s]Al secondo piano di questo[n]palazzo c'因 un corso privato, ma[n]perch姻 因 cos淫 vicino a un pachinko?[n][w][e]

[msg MSG_CRAMMER_arbeit_no_ch [Morgana]]
[s]Al secondo piano di questo[n]palazzo c'因 un corso privato, ma[n]perch姻 因 cos淫 vicino a un pachinko?[n][w][e]

[msg MSG_CRAMMER_arbeit_ng_ma [Morgana]]
[s]Ora che ci penso, hai fatto[n]domanda qui per un lavoro part-time.[n][w][e]
[s]Sulla rivista degli annunci[n]si parlava di requisiti extra[n]per i liceali.[n][w][e]
[s]Beh, dovresti andare[n]a chiedere ulteriori dettagli.[n][w][e]

[msg MSG_CRAMMER_arbeit_ng_ma_2 [Voce dal tono presidenziale]]
[s]Oh, sei [lName]-kun?[n]Ah, hai chiesto di lavorare qui?[n][w][e]
[s]Abbiamo un disperato bisogno[n]di insegnanti. Siamo felici[n]per la tua candidatura, ma...[n][w][e]
[s]Per i liceali ci sono delle[n]condizioni extra per poter[n]insegnare ai ragazzi delle medie.[n][w][e]
[s]Tieni, prendi questi[n][clr 2]esercizi di base[clr 27] e[n]torna dopo averli capiti tutti.[n][w][e]
[s]Prenditi tutto il tempo[n]necessario per finirli. Siamo a[n]corto di personale tutto l'anno.[n][w][e]

[msg MSG_CRAMMER_arbeit_ng_ma_3 [Morgana]]
[s]...Dunque, che libro di esercizi 因?[n]Io me la cavo benone.[n]Fammi vedere.[n][w][e]

[msg MSG_CRAMMER_arbeit_ng_ma_4]
[s]Apro il libro e trovo un problema[n]sul calcolo dell'area di un[n]diagramma molto complesso...[n][w][e]
[s]Non so come usare questa[n]formula. I bambini delle elementari[n]sanno davvero risolverlo?[n][w][e]

[msg MSG_CRAMMER_arbeit_ng_ma_5 [Morgana]]
[s]......[n][w][e]
[s]Uhm. Devi trovare un [clr 2]posto[n]pieno di libri dove concentrarti[n]per studiare[clr 27] gli esercizi...[n][w][e]
[s]...Comunque, [clr 2]non potrai[n]lavorare al corso privato[clr 27][n]finch姻 non risolverai gli esercizi.[n][w][e]
[s]Andiamo. 為 inutile[n]restare qui.[n][w][e]

[msg MSG_CRAMMER_arbeit_ng_ma_6 [Morgana]]
[s]Non hai ancora[n]finito gli esercizi[n]per lavorare qui, giusto?[n][w][e]
[s]Torniamo quando[n]li avrai risolti tutti.[n][w][e]

[msg MSG_CRAMMER_NG_night [Morgana]]
[s]Non avevi un turno qui,[n]subito dopo la scuola?[n][w][e]
[s]Se arrivi la sera sar稲[n]troppo tardi. Fermiamoci[n]un'altra volta.[n][w][e]

[msg MSG_CRAMMER_NG_shift [Morgana]]
[s]Sei di turno il luned淫,[n]il mercoled淫 e il gioved淫, giusto?[n][w][e]
[s]Torniamo un'altra volta.[n][w][e]

[msg MSG_CRAMMER_CHK [Morgana]]
[s]Oggi puoi lavorare qui.[n][w][e]
[s]Molti di questi bambini sono[n]impudenti, ma insegnando[n]affinerai il tuo [clr 1]Intuito[clr 27].[n][w][e]

[msg MSG_CRAMMER_POLISH [Morgana]]
[s]Inoltre, non hai quasi finito il[n]periodo di formazione? Potrebbe[n]succedere qualcosa di bello.[n][w][e]

[msg MSG_CRAMMER_NO_POLISH [Morgana]]
[s]Se continuerai a lavorare, finirai[n]il periodo di formazione e potrebbe[n]succedere qualcosa di bello.[n][w][e]

[msg MSG_CRAMMER_CHK_START [Morgana]]
[s]Allora, cosa vuoi fare? Oggi[n]lavorerai qui?[n][w][e]

[sel SEL_CRAMMER_CHK top]
[s]Andiamo a lavorare.[e]
[s]Lavoriamo un altro giorno.[e]

[msg MSG_CHK_PACHINKO_SLOT]
[s]Gli adulti giocano al pachinko[n]e alle slot, ma hanno tutti[n]lo sguardo spento. Si divertiranno?[n][w][e]

[msg SuperMarket_NOTOPEN]
[s]為 il supermercato "Meet Masa".[n][w][e]
[s]A differenza degli altri supermercati,[n]vende prodotti alimentari in[n]quantit稲 industriali...[n][w][e]
[s]Al momento non c'因 nulla[n]che vorrei comprare...[n][w][e]

[msg SuperMarket_SELECT [Cameriere]]
[s]Benvenuto![n][w][e]

[msg SuperMarket_THANKS [Cameriere]]
[s]Grazie mille![n]Speriamo di rivederti molto,[n]molto presto![n][w][e]

[msg SuperMarket_NOT_BUY [Cameriere]]
[s]Torna a trovarci![n][w][e]

[msg SuperMarket_SOLDOUT [Cameriere]]
[s]Mi dispiace taaanto.[n]Abbiamo esaurito le scorte[n]di... tutto.[n][w][e]

[msg MSG_CRAMMER]
[s]為 l'entrata del[n]corso privato.[n][w][e]
[s]C'因 scritto[n]"Punta alle scuole[n]medie migliori!"[n][w][e]

[msg MSG_BATTING_CENTER_OPEN_ [Morgana]]
[s]バッティングセンターがあるよ、坊っちゃん。[n]結構人気みたいだね。[n][w][e]
[s]あ、看板が出てるよ![n]なになに......[n][w][e]
[s]“只今混雑のため、利用人数規制中"だってさ。[n]しょうがないから、今日は諦めよう?[n][w][e]

[msg MSG_BATTING_CENTER_OPEN__2 [Morgana]]
[s]あ、[clr 2]木曜日[clr 27]が[clr 2]定休日[clr 27]みたいだから、[n]その日以外にまた来てみようか。[n][w][e]

[msg MSG_BATTING_CENTER_OPEN__3 [Morgana]]
[s]バッティングセンターみたいだよ。[n]何か貼り紙がある......[n][w][e]
[s]“[clr 2]1プレイ100円[clr 27]! 事故っても自己責任"だって。[n]......これ、法律的には限りなくアウトな気がするけど。[n][w][e]
[s]事故想定のバッティングセンターって、[n]よっぽど[clr 3]デンジャラスな球が飛んでくる[clr 27]のか...?[n][w][e]
[s]うーん、ここでなら[n][stIcon 3][clr 26][stLabel 3][clr 27]を磨けそうだけど......[n][w][e]
[s]どうする?[n][w][e]

[sel MSG_BATTING_CENTER_SEL top]
[s]入店する[e]
[s]やめておく[e]

[msg MSG_BATTING_CENTER_NOMON [Morgana]]
[s]坊っちゃん...[n]所持金が足りないよ...[n][w][e]

[msg MSG_BATTING_CENTER_OPEN__4 [Morgana]]
[s]今日はお休みだって。[n]ここはまた今度だね。[n][w][e]

[msg MSG_MOVE_NG_ITEM_OPEN_MO [Morgana]]
[s]坊ちゃん、何処へ行くの?[n]診療所はこの近くにあるハズだよ。[n][w][e]

