[msg MSG_LAST_GREETING_sentou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Il bagno pubblico era un posto[n]carino. Adoravo il murale del[n]Monte Fuji all'interno.[n][w][e]

[msg MSG_LAST_GREETING_sentou_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Non abbiamo niente da fare al bagno[n]pubblico. Andiamo dagli altri.[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Comprare una bibita[n]per 100 yen 因 stato un affare.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Speriamo che ci sia anche[n]nella tua citt稲.[n][w][e]

[msg MSG_LAST_GREETING_RECYCL [Gestore del negozio dell'usato]]
[s][f 4 23 1 150 3 10 0 0]Benvenuto.[n][w][e]

[msg MSG_LAST_GREETING_RECYCL_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Il vecchio 因 sempre stato buono[n]con noi. Dovresti ringraziarlo.[n][w][e]

[msg MSG_LAST_GREETING_RECYCL_3 [Gestore del negozio dell'usato]]
[s][f 4 23 1 150 3 10 0 0]Oh, davvero...? Beh, ci mancherai.[n]Stammi bene, d'accordo?[n][w][e]

[msg MSG_LAST_GREETING_RECYCL_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Qui non ci serve niente. Potrai[n]comprare quello che ti serve[n]quando sarai tornato a casa.[n][w][e]

[msg MSG_LAST_GREETING_BATTIN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non scorder韻 mai quel fuoricampo[n]incredibile che hai piazzato qui.[n]為 stato pazzesco...[n][w][e]

[msg MSG_LAST_GREETING_BATTIN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Avevi fatto 5 su 5 quel giorno.[n]Dovremmo chiamarti Hitman![n][w][e]

[msg MSG_LAST_GREETING_BATTIN_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Non scorder韻 mai il rumore della[n]mazza di metallo. Dovremmo[n]tornarci appena possibile.[n][w][e]

[msg MSG_LAST_GREETING_BATTIN_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Sentivamo sempre i rumori di[n]questo posto dal Leblanc,[n]ma non ci siamo mai venuti...[n][w][e]

[msg MSG_LAST_GREETING_CINEMA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Le nostre azioni hanno salvato[n]questo cinema...[n][w][e]

[msg MSG_LAST_GREETING_CINEMA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Che senso ha andare in un[n]cinema chiuso?[n]Raggiungiamo gli altri![n][w][e]

[msg MSG_LAST_GREETING_SUPERM [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Abbiamo comprato qui gli[n]ingredienti per l'hot pot della[n]festa di benvenuto di Yusuke...[n][w][e]

[msg MSG_LAST_GREETING_WASHIN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]為 qui che facevamo il bucato.[n]Come vola il tempo...[n][w][e]

[msg MSG_LAST_GREETING_WASHIN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non abbiamo bucato da fare.[n]Possiamo andare dagli altri?[n][w][e]

[msg MSG_LAST_GREETING_AUTO_M_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Che c'因, hai sete?[n][w][e]

[msg MSG_LAST_GREETING_Sojiro [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]La casa del capo. Quei due sono al[n]Leblanc, quindi 因 vuota.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ricordo la prima volta che siamo[n]venuti qui da Futaba...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]E il modo in cui Makoto si 因[n]infuriata... Lo ricordo come se[n]fosse ieri.[n][w][e]

[msg MSG_LAST_GREETING_Sojiro_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]La casa del capo...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Sono entrambi al Leblanc, non c'因[n]nessuno in casa. Andiamo[n]da un'altra parte.[n][w][e]

[msg MSG_LAST_GREETING_GRAFFI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Questi graffiti... sono qui[n]da un anno.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]A Takemi non importa niente[n]dei graffiti, eh?[n][w][e]

[msg MSG_LAST_GREETING_NOTBUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Che vuoi prendere da un vecchio[n]distributore? Non possiamo andare[n]dagli altri e basta?[n][w][e]

[msg MSG_LAST_GREETING_DRINK_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ora che ci penso, non abbiamo mai[n]mangiato qui. Non ti piace[n]il cibo piccante?[n][w][e]

[msg MSG_LAST_GREETING_DRINK__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Abitiamo qui vicino, ma non siamo[n]mai venuti a mangiare qui.[n]Torniamoci quando sarai pi迂 grande.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1155 65535 0]La mia passerella 因 lass迂.[n]Non temere, l'ho gi稲 fatto[n]sapere a tutti i gatti.[n][w][e]

[msg MSG_LAST_GREETING_DRINK__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non c'因 nessuno.[n]Dai, andiamo dagli altri.[n][w][e]

[msg MSG_LAST_GREETING_BONE_R [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Non siamo mai venuti qui...[n]Del resto, i massaggi te li faceva[n]Kawakami.[n][w][e]

[msg MSG_LAST_GREETING_BONE_R_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non 因 il momento dei massaggi.[n]Dobbiamo andare a salutare[n]gli altri![n][w][e]

[msg MSG_LAST_GREETING_OLD_AP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Non conosciamo nessuno che viva[n]qui. Andiamo a trovare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_TABACO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Credo che il capo comprasse qui[n]le sigarette...[n][w][e]

[msg MSG_LAST_GREETING_Post [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Una lettera? Dovrai spedirne un[n]po' dopo il trasloco![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MND_RETURNHOME_NORMAL]
[s]Dovrei andare a casa...[n][w][e]

[msg MSG_RETURNHOME_NORMAL_MO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Eh? Vuoi gi稲 andare a casa?[n][w][e]

[msg MND_RETURNHOME_AJITO]
[s]Cosa dovrei fare...?[n][w][e]

[msg MSG_RETURNHOME_AJITO_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Andiamo al ritrovo?[n]O vuoi riposare un po'?[n][w][e]

[sel SEL_RETURNHOME top]
[s]Vediamoci con gli altri.[e]
[s]Riposiamo fino a sera.[e]
[s]Andiamo da un'altra parte.[e]

[msg MSG_GOTO_AJITO_MORGANA [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Raduniamo tutti al ritrovo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Non possiamo farci battere[n]da Maruki. Siete pronti?[n][w][e]

[sel SEL_GOTO_AJITO top]
[s]Raduniamo tutti.[e]
[s]Mi serve pi迂 tempo.[e]

[msg MSG_RETURN_BYE_GREET_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Finito con i saluti?[n][w][e]

[msg MSG_RETURN_BYE_GREET_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]C'因 qualcuno che non hai[n]ancora salutato... Vuoi davvero[n]tornare a casa?[n][w][e]

[sel SEL_RETURN_BYE_GREET_01 top]
[s]Finisci di salutare e vai.[e]
[s]Non ancora.[e]

[msg MSG_RETURN_BYE_GREET_20 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Sei proprio sicuro?[n][w][e]

[sel SEL_RETURN_BYE_GREET_21 top]
[s]Andiamo a casa.[e]
[s]Beh, forse no.[e]

[msg MSG_RETURN_BYE_GREET_03_ [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Ehi, uhm... ecco, anch'io ho[n]un regalo per te, [fName].[n][w][e]

[msg MSG_RETURN_BYE_GREET_03__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Non so perch姻, ma quando[n]sono uscito dal Metaverso mi 因[n]rimasta solo questa sciarpa.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 6 0 0]L'ho sempre[n]considerata speciale...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 7 0 0]Voglio che l'abbia tu, come prova[n]di tutto quello che[n]abbiamo passato insieme.[n][w][e]

[msg MSG_RETURN_BYE_GREET_03__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Bene... 因 ora di andare[n]a casa e prepararsi, eh?[n][w][e]

[msg MSG_RETURN_BYE_GREET_04 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]In questo caso, andiamo[n]a salutare gli altri.[n][w][e]

[msg MSG_RETURN_BYE_GREET_00_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 9 0 0]Finito con i saluti?[n][w][e]

[msg MSG_RETURN_BYE_GREET_10_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 10 0 0]C'因 qualcuno che non hai[n]ancora salutato... Vuoi davvero[n]tornare a casa?[n][w][e]

[sel SEL_RETURN_BYE_GREET_01_ top]
[s]Finisci di salutare e vai.[e]
[s]Non ancora.[e]

[msg MSG_RETURN_BYE_GREET_20_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Sei proprio sicuro?[n][w][e]

[sel SEL_RETURN_BYE_GREET_21_ top]
[s]Andiamo a casa.[e]
[s]Beh, forse no.[e]

[msg MSG_RETURN_BYE_GREET_03__4 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 12 0 0]Ehi, uhm... ecco, anch'io ho[n]un regalo per te, [fName].[n][w][e]

[msg MSG_RETURN_BYE_GREET_03__5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 13 0 0]Anche da umano, per qualche[n]ragione, non ho voluto separarmene.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 14 0 0]為 difficile per me capire cosa[n]io sia, se gatto, umano, o una[n]qualche specie di veicolo.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 15 0 0]Ma a prescindere da questo, una[n]cosa la so... sono tuo amico.[n][w][e]

[msg MSG_RETURN_BYE_GREET_03__6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 16 0 0]Bene... 因 ora di andare[n]a casa e prepararsi, eh?[n][w][e]

[msg MSG_RETURN_BYE_GREET_04_ [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]In questo caso, andiamo[n]a salutare gli altri.[n][w][e]

[msg MND_RETURNHOME_AJITO_010]
[s]Cosa dovrei fare...?[n][w][e]

[sel SEL_RETURNHOME_0103 top]
[s]Riposo a casa.[e]
[s]Esco fuori.[e]

[msg MND_RETURNHOME_0103]
[s]為 ancora troppo presto[n]per andare a casa...[n][w][e]
[s]Dovrei andare dagli altri...[n][w][e]

[msg MSG_NG_ROJIURA_OUT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Hai promesso che saresti[n]rimasto nel vicinato.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Devi avere pazienza e conquistare[n]la fiducia del capo. Obbediscigli[n]per un po', OK?[n][w][e]

[msg MSG_ROJIURA_OUT_FIRST [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Assaporiamo la vita[n]notturna di citt稲![n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Yonc]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso il cinema[clr 0] di Yongen-Jaya.[n][w][e]

[msg MSG_Eiga_UseNG_HIRU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Sembra che il cinema sia aperto[n]solo di sera.[n][w][e]

[msg MSG_Eiga_UseNG_6Month_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Uh-oh, sono chiusi.[n]C'因 un cartello appeso dentro...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 65535 0]"Troppo stremati per[n]restare aperti"...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 65535 0]Esausti, eh? Non possiamo farci[n]molto. Spero che si riprendano.[n][w][e]

[msg MSG_Eiga_UseNG_6Month_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Un cinema... Ma 因 chiuso.[n]C'因 un cartello appeso dentro...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 65535 0]"Troppo stremati per[n]restare aperti"...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 65535 0]Esausti, eh? Non possiamo farci[n]molto. Spero che si riprendano.[n][w][e]

[msg MSG_Eiga_UseNG_6Month_03 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Il cartello dentro dice "Troppo[n]stremati per restare aperti".[n]Spero si riprendano presto.[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_YO [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Oooh, finalmente ha riaperto![n]Chiss稲 che genere di[n]film trasmetteranno![n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_YO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Questo posto 因...[n]ricco di atmosfera. Chiss稲[n]cosa trasmettono.[n][w][e]

[msg MSG_SENTOU_NG_TERM_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Un bagno pubblico, eh?[n]Perch姻 non ci vieni quando[n]sei molto stanco?[n][w][e]

[msg MSG_SENTOU_NG_TERM]
[s]Il profumo del sapone si[n]diffonde dal bagno pubblico...[n][w][e]
[s]Dovrei venirci, quando[n]mi sento stanco...[n][w][e]

[msg MSG_Sentou_UseNG_HIRU_an [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]"Fuji no yu"... 為 un bagno[n]pubblico. Mi piace lo stile[n]classico di questo posto.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ma stanno ancora sistemando.[n][w][e]

[msg MSG_Sentou_UseNG_HIRU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Ma stanno ancora sistemando.[n]Torniamoci di [clr 2]sera[clr 27].[n][w][e]

[msg MSG_SENTOU_START_1ST [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Ecco il bagno pubblico...[n]Mmm, 因 in un'area isolata.[n][w][e]

[msg MSG_Sentou_ParamInfo_int [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Rilassarti al bagno pubblico[n]potrebbe aiutarti a migliorare il[n]tuo [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MSG_Sentou_Kusuri_1st [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]*sniff sniff* Che buon odore.[n]Forse 因 un bagno medicinale.[n][w][e]

[msg MSG_Sentou_Hot_1st [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Uh... Quanto vapore...[n][w][e]

[msg MSG_SENTOU_START_DrugDay [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]*sniff sniff* Oggi 因 un bagno[n]medicinale.[n][w][e]

[msg MSG_SENTOU_START_HotDay [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Wow, quanto vapore.[n][w][e]

[msg MND_Sentou_ParamUpInfo]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 1][n]aumenter稲 presto...[n][w][e]

[msg MND_Sentou_ParamEndInfo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MSG_SENTOU_START_COMMON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi farti un bagno rigenerante?[n]Sono 500 yen per entrare.[n][w][e]

[sel SEL_SENTOU_Q top]
[s]Andiamoci.[e]
[s]Un'altra volta.[e]

[msg MSG_Sentou_NoMoney [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1182 65535 0]Non hai abbastanza soldi[n]per il biglietto d'ingresso.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Sent]
[s]Ora puoi viaggiare velocemente[n]verso il [clr 6]bagno pubblico[clr 0][n]di Yongen-Jaya.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Al momento non ho sete...[n][w][e]

[msg AUTO_MACHINE01_NOTOPEN]
[s]為 indicato un prezzo fisso[n]di 100 yen. 為 poco,[n]per un distributore automatico.[n][w][e]

[msg MSG_Juice_Start100 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]C'因 scritto che tutti i prodotti di[n]questo distributore costano[n]100 yen. Vuoi qualcosa da bere?[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg RECYCLE_SHOP_NOTOPEN]
[s]Il negoziante sembra assente.[n][w][e]

[msg RECYCLE_SHOP_CLOSE]
[s]Oggi sembra chiuso.[n][w][e]

[msg RECYCLE_SHOP_CLOSE_MONA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]C'因 scritto che oggi 因 chiuso.[n][w][e]

[msg MSG_RECYCLE_CLOSE_NotIte [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Vendono parecchie cose qui,[n]ma niente di interessante.[n]Diamogli un'occhiata, ogni tanto.[n][w][e]

[msg RECYCLE_SHOP_SELECT [Gestore del negozio dell'usato]]
[s][f 4 23 1 150 3 10 0 0]Benvenuto.[n][w][e]

[msg RECYCLE_SHOP_THANKS [Gestore del negozio dell'usato]]
[s][f 4 23 1 150 6 5 0 0]...Grazie.[n][w][e]

[msg RECYCLE_SHOP_NOT_BUY [Gestore del negozio dell'usato]]
[s]為 uno di quei giorni...[n][w][e]

[msg MSG_RECYCLE_DvdPlayerBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Beh, hai un lettore DVD ma...[n]non hai una TV.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Dovresti provare a pulire[n]la stanza. Chiss稲 cosa[n]potresti trovarci![n][w][e]

[msg MSG_GO_HOME [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vuoi tornare al caf姻?[n][w][e]

[sel SEL_GO_HOME top]
[s]Torniamo.[e]
[s]No, non ora.[e]

[msg HELP_GO_HOME]
[s]Se torno a casa, al caf姻,[n]diventer稲 [clr 2]"notte"[clr 27].[n][w][e]

[msg MND_Batting_NotOpen]
[s]Le gabbie di battuta sono aperte...[n][w][e]

[msg MSG_Batting_0417 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Gabbie di battuta? Qui?[n][w][e]

[msg MSG_BAT_START_1ST_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1130 65535 0]Gabbie di battuta?[n]In un posto cos淫 piccolo?[n][w][e]
[s][f 4 10 65535 0 0]...Com'因 all'interno?[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_BATT]
[s]Ora puoi viaggiare velocemente[n]verso le [clr 6]gabbie di battuta[clr 0][n]di Yongen-Jaya.[n][w][e]

[sel SEL_BAT_START_1ST_MORU top]
[s]Diamo un'occhiata.[e]
[s]No, non mi interessa.[e]

[msg SuperMarket_NOTOPEN]
[s]Ci sono molti prodotti alimentari[n]a uso commerciale.[n][w][e]
[s]Se mi servisse qualcosa,[n]dovrei venire qui...[n][w][e]

[msg SuperMarket_YORU_CLOSE_M [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Stanno riordinando gli[n]scaffali. Sembra che[n]presto chiuderanno.[n][w][e]

[msg SuperMarket_YORU_CLOSE]
[s]Cominciano a pulire.[n]Vista l'ora, direi che[n]sono in chiusura.[n][w][e]

[msg SuperMarket_SELECT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]C'因 qualcosa che devi[n]fare al supermercato?[n][w][e]

[msg SuperMarket_THANKS [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1180 65535 0]Questo posto 因 gigante perch姻[n]hanno un vastissimo assortimento.[n]Torniamoci, quando capita.[n][w][e]

[msg SuperMarket_NOT_BUY [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]Sei venuto qui solo per guardare?[n][w][e]

[msg MSG_SUPER_SALE [Commesso del supermercato]]
[s]Benvenuto![n]Abbiamo offerte ogni[n]sabato e domenica![n][w][e]

[msg MSG_SUPER_THANKS [Commesso del supermercato]]
[s]Grazie mille![n][w][e]

[msg MSG_CHK_SUPER_ITEM01_MOR [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Una montagna di prodotti[n]ammucchiati. Qui per韻 non[n]rubiamo niente, intesi?[n][w][e]

[msg MSG_CHK_SUPER_ITEM01]
[s]Questa 因 verza?[n][w][e]

[msg MSG_CHK_SUPER_ITEM02_MOR [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oooh, le verdure sono[n]ancora sporche di terra.[n]Vuol dire che sono davvero fresche.[n][w][e]

[msg MSG_CHK_SUPER_ITEM02]
[s]Nella vetrina del negozio[n]c'因 una quantit稲 enorme[n]di verdure in mostra...[n][w][e]

[msg MSG_DEADEND_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Ci siamo persi? Siamo finiti[n]in un vicolo cieco.[n][w][e]

[msg MSG_DEADEND_0409]
[s]Qui non c'因 niente.[n]Sembra un vicolo cieco...[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_Coin]
[s]Ora puoi viaggiare velocemente[n][clr 6]verso la lavanderia automatica[clr 0].[n][w][e]

[msg MSG_WASH_MACHINE_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]La lavatrice 因 in funzione.[n]Sobbalza senza far rumore...[n][w][e]

[msg MSG_WASH_MACHINE]
[s]Sembra che qualcuno stia usando[n]questa macchina. 為 silenziosa.[n][w][e]

[msg MSG_SPIN_DRIER_MORU [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]I vestiti all'interno[n]girano in cerchio...[n][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Inizia a girarmi la testa.[n]Questa cosa 因 pericolosa![n][w][e]

[msg MSG_SPIN_DRIER]
[s]Vedo girare dei vestiti[n]all'interno.[n][w][e]

[msg MSG_CLINIC_YET_OPEN]
[s]Questo posto sembra[n]una clinica.[n][w][e]

[msg MSG_CLINIC_LOCK_0417 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]La clinica ha gi稲[n]chiuso oggi.[n][w][e]

[msg MSG_CLINIC_NIGHT_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]La clinica 因 chiusa[n]di notte. Torniamo[n]di giorno.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_SHIN]
[s]Ora puoi viaggiare velocemente[n]verso la [clr 6]clinica[clr 0].[n][w][e]

[msg MSG_SojiroHouse_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Il capo abita qui? 為 una casa[n]sorprendentemente nella media.[n][w][e]

[msg MSG_SojiroHouse_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Chi l'avrebbe detto che Futaba[n]abitasse cos淫 vicino a noi...[n][w][e]

[msg MSG_SojiroHouse_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1034 65535 0]Sei in pensiero per Futaba?[n]Dobbiamo essere pazienti e[n]avere fiducia in lei.[n][w][e]

[msg MSG_SojiroHouse_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Non sapevo che anche Futaba vivesse[n]qui. Forse l'abbiamo incontrata e[n]non ce ne siamo accorti.[n][w][e]

[msg MSG_SOJIRO_HOUSE]
[s]Questa 因 la casa di Sojiro.[n][w][e]
[s]Sembra esserci una stanza[n]al secondo piano, ma le tende[n]sono tirate...[n][w][e]

[msg MSG_DEADEND01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Di l稲 non vedo molti negozi[n]che possano esserci utili.[n]Meglio tornare indietro.[n][w][e]

[msg MSG_DEADEND01]
[s]Non ci sono molti negozi[n]interessanti da questa parte.[n]Torniamo indietro.[n][w][e]

[msg MSG_DEADEND02_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Di qua c'因 un'area residenziale,[n]ma non abbiamo motivo[n]di andarci.[n][w][e]

[msg MSG_DEADEND02]
[s]Pi迂 avanti dovrebbe esserci[n]un'area residenziale, ma[n]non ho motivo di andarci.[n][w][e]

[msg MSG_GRAFFITI_CLINIC_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Su questo cartello ci sono dei[n]graffiti. Non 因 un grande incentivo[n]a entrare...[n][w][e]

[msg MSG_GRAFFITI_CLINIC]
[s]Qui ci sono dei graffiti.[n]Chiss稲 se li toglieranno mai...[n][w][e]

[msg MSG_MACHINE_NOTBUY01_MOR [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Hanno un bel coraggio[n]a lasciarlo qui[n]in questo stato...[n][w][e]

[msg MSG_MACHINE_NOTBUY01]
[s]Pare che questa macchina[n]sia rotta da un bel po'...[n][w][e]

[msg MSG_DEADEND03_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Quest'area puzza d'alcol...[n][w][e]

[msg MSG_DEADEND03]
[s]L'odore dell'alcol[n]permea tutta l'area...[n][w][e]

[msg MSG_GRAFFITI_SHOP_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Quanti graffiti.[n]Toglierli tutti sembra[n]un gran lavoraccio...[n][w][e]

[msg MSG_GRAFFITI_SHOP]
[s]Il muro 因 pieno[n]di graffiti.[n][w][e]

[msg MSG_WALL_VOTE_MORU [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0]為 come se quel manifesto[n]fosse l淫 per coprire i graffiti.[n][w][e]

[msg MSG_WALL_VOTE]
[s]Sembra che abbiano affisso[n]questo manifesto solo per[n]coprire i graffiti...[n][w][e]

[msg MSG_DRINK_SHOP01_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pepe? O 因 peperoncino?[n]Sento aromi molto complessi...[n][w][e]

[msg MSG_DRINK_SHOP01]
[s]為 un ristorante fusion.[n]Sento l'aroma di[n]diverse spezie...[n][w][e]

[msg MSG_DRINK_SHOP02_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]為 aperto fino alle due[n]del mattino? Suppongo che sia[n]un locale con una clientela adulta.[n][w][e]

[msg MSG_DRINK_SHOP02]
[s]Questo bar sembra aperto[n]fino a tarda notte.[n][w][e]

[msg MSG_DEADEND04_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Non abbiamo motivo di[n]andare di qua, no?[n][w][e]

[msg MSG_DEADEND04]
[s]Non devo fare niente[n]pi迂 avanti.[n][w][e]

[msg MSG_DEADEND05_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Di qua si arriva a un'area[n]residenziale. Abbiamo qualche[n]motivo per andarci?[n][w][e]

[msg MSG_DEADEND05]
[s]Pi迂 avanti c'因 un'area[n]residenziale, ma non ho motivo[n]di andarci.[n][w][e]

[msg MSG_DRINK_SHOP03_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Questo posto non m'invoglia[n]per niente a entrare. Sicuramente[n]因 pieno di clienti abituali.[n][w][e]

[msg MSG_DRINK_SHOP03]
[s]Chiss稲 che tipo di clientela[n]ha un izakaya come questo...[n][w][e]

[msg MSG_BONE_REPAIR_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Kurubushi, eh?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Nome interessante per[n]una clinica. Non 因 il[n]nome del dottore, vero?[n][w][e]

[msg MSG_BONE_REPAIR]
[s]Clinica ortopedica Kurubushi...[n][w][e]
[s]Per quanto lo ripeta,[n]mi suona sempre strano. Mmm.[n]Forse 因 voluto.[n][w][e]

[msg MSG_OLD_APARTMENT_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0]Sembra un posto molto[n]poco soleggiato...[n][w][e]

[msg MSG_OLD_APARTMENT]
[s]Se resto qui, qualcuno[n]potrebbe scambiarmi per un[n]tipo sospetto...[n][w][e]

[msg MSG_TABACO_SHOP_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Un adolescente non ha[n]motivo di andare[n]in tabaccheria, no?[n][w][e]

[msg MSG_TABACO_SHOP]
[s]Non mi serve niente[n]in questa tabaccheria...[n][w][e]

[msg MSG_Post_ItemNotHave [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Non hai nulla da spedire[n]a qualcuno, vero?[n][w][e]

[msg MND_Post_ItemNotHave]
[s]Non ho posta[n]da spedire...[n][w][e]

[msg MSG_Post_ItemHave [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Adesso che ci penso, hai[n]comprato una cartolina. Perch姻[n]non la spedisci a qualcuno?[n][w][e]

[msg MSG_Post_NotUseTime [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Ora che ci penso, avevi preso una cartolina.[n]Vuoi spedi... Un attimo.[n][w][e]
[s][f 4 10 65535 0 0]Vuoi scriverla e inviarla ADESSO?[n]Non 因 una buona idea. Si bagner稲.[n][w][e]

[sel SEL_WhoPray top]
[s]Invia a Ryuji[e]
[s][clr 30]Invia a Ryuji[clr 27][e]
[s]Invia a Ann[e]
[s][clr 30]Invia a Ann[clr 27][e]
[s]Invia a Yusuke[e]
[s][clr 30]Invia a Yusuke[clr 27][e]
[s]Invia a Makoto[e]
[s][clr 30]Invia a Makoto[clr 27][e]
[s]Invia a Futaba[e]
[s][clr 30]Invia a Futaba[clr 27][e]
[s]Invia a Haru[e]
[s][clr 30]Invia a Haru[clr 27][e]
[s]Invia a Sojiro[e]
[s][clr 30]Invia a Sojiro[clr 27][e]
[s]Invia a Mishima[e]
[s][clr 30]Invia a Mishima[clr 27][e]
[s]Invia a Takemi[e]
[s][clr 30]Invia a Takemi[clr 27][e]
[s]Invia a Iwai[e]
[s][clr 30]Invia a Iwai[clr 27][e]
[s]Invia a Kawakami[e]
[s][clr 30]Invia a Kawakami[clr 27][e]
[s]Invia a Yoshida[e]
[s][clr 30]Invia a Yoshida[clr 27][e]
[s]Invia a Ohya[e]
[s][clr 30]Invia a Ohya[clr 27][e]
[s]Invia a Chihaya[e]
[s][clr 30]Invia a Chihaya[clr 27][e]
[s]Invia a Hifumi[e]
[s][clr 30]Invia a Hifumi[clr 27][e]
[s]Invia a Shinya[e]
[s][clr 30]Invia a Shinya[clr 27][e]
[s]Invia a Akechi[e]
[s][clr 30]Invia a Akechi[clr 27][e]
[s]Invia a [sumi 10 1][e]
[s][clr 30]Invia a [sumi 10 1][clr 27][e]
[s]Invia a Maruki[e]
[s][clr 30]Invia a Maruki[clr 27][e]

[msg MSG_Post_Cancel [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Oh, hai cambiato idea?[n][w][e]

[msg MND_Think_Chara]
[s][vp 1 0 0 0 0 0]Proviamo a spedirla[n]a [var 0]...[n][w][e]

[msg MND_Think_NGChara_Start]
[s][vp 1 0 0 0 0 0]......[n][w][e]
[s]Non credo che[n]il destinatario gradirebbe.[n][w][e]

[msg MND_Think_NGChara_Moru]
[s][vp 1 0 0 0 0 0]......[n][w][e]
[s]Mmm, forse 因[n]stato inutile.[n][w][e]

[msg MND_Chara_Result]
[s][vp 1 0 0 0 0 0]......[n][w][e]
[s]Sento di aver migliorato[n]un po' la mia relazione[n]con [var 0]...[n][w][e]

[msg MND_TEST]
[s][vp 1 0 0 0 0 0]Sei di livello [var 0].[n]La tua Persona 因 [var 1].[n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MND_0103]
[s]Chiss稲 cosa staranno facendo[n]gli altri...[n][w][e]
[s]Andiamo da un'altra parte...[n][w][e]

[msg MND_SHOP_0103]
[s]......[n][w][e]
[s]Sembra che sia chiuso[n]per Capodanno...[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]Non c'因 tempo per gli acquisti...[n][w][e]
[s]Chiss稲 cosa staranno facendo gli[n]altri... Cambiamo zona, dai...[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]Non c'因 tempo per le deviazioni...[n][w][e]
[s]Chiss稲 cosa staranno facendo gli[n]altri... Cambiamo zona, dai...[n][w][e]

[msg MND_0103to0108_Error_Soj]
[s]Non sembra diversa dal solito...[n][w][e]
[s]Chiss稲 cosa staranno facendo gli[n]altri... Cambiamo zona, dai...[n][w][e]

[msg MSG_RETURNHOME_0427_MORG [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Vai a casa? Ti ricordi[n]della scadenza, vero?[n][w][e]

[sel MSG_RETURNHOME_0427_MORG_2 top]
[s]Riposiamo fino a sera.[e]
[s]Andiamo da un'altra parte.[e]

[msg MSG_RETURNHOME_0428_MORG [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Vai davvero a casa?[n]Ma hai da fare![n][w][e]

[msg MSG_RETURNHOME_0429_MORG [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Vai davvero a casa?[n]E il risveglio del cuore?!?[n][w][e]

[msg MSG_RETURNHOME_0430_MORG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Vai gi稲 a casa? Beh...[n]Immagino sia la cosa migliore.[n][w][e]

[msg MSG_RETURNHOME_0501_MORG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Vai a casa? S淫, forse 因 meglio...[n][w][e]

[msg MSG_RETURNHOME_0501_MORG_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Eh? Vuoi gi稲 andare a casa?[n][w][e]

[msg MSG_RETURNHOME_0428_MORG_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Davvero vai a casa? Sono sicuro[n]che hai le tue buone ragioni, ma...[n][w][e]

[msg MSG_RETURNHOME_0429_MORG_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Vai a casa...? Uhm, sai che[n]non abbiamo pi迂 tempo, vero?[n][w][e]

[msg MSG_RETURNHOME_0430_MORG_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Aspetta, stai andando a casa?[n]E la lettera di sfida?!?[n][w][e]

[msg MND_E10410100_NG_STATION]
[s][vp 1 0 0 0 0 0]La stazione 因 appena[n]pi迂 avanti. Devo andare a[n][clr 2]casa di Sojiro[clr 27]...[n][w][e]

[msg MND_E10410300_NG_STATION]
[s][vp 1 0 0 0 0 0]Di qua si va alla stazione.[n]Dovrei tornare indietro e trovare[n]un locale chiamato [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E10410400_NG_N_STATI]
[s][vp 1 0 0 0 0 0]Di qua si va alla stazione.[n]Dovrei tornare indietro e trovare[n]un caff因 chiamato [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E65210100_GOTO_KASUM]
[s][vp 1 0 0 0 0 0]Kasumi sta aspettando a Odaiba.[n][w][e]

[sel SEL_E65210100_GOTO_KASUM top]
[s]Andr韻 da Kasumi.[e]
[s]Non ci andr韻 ancora.[e]

[msg MND_E10410400_NG_S_STATI]
[s][vp 1 0 0 0 0 0]L'agente ha detto che il[n]caff因 [clr 2]Leblanc[clr 27] 因[n]in questo vicolo...[n][w][e]

[msg MSG_E27930100_NG_STATION [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Dove vai? Se non restiamo qui,[n]non riusciremo a raccogliere[n]alcuna informazione...[n][w][e]

[msg MND_E40110200_NG_00]
[s][vp 1 0 0 0 0 0]Mi sto allontanando dalla[n]voce di Shido. Questa sembra[n]la direzione sbagliata...[n][w][e]

[msg MND_E10410100_GOTO_CAFE_]
[s][vp 1 0 0 0 0 0]Dalla finestra si vede[n]all'interno. Non ci sono[n]molti clienti...[n][w][e]

[msg MND_E10410300_GOTO_CAFE_]
[s][vp 1 0 0 0 0 0]Sembra che questo posto[n]sia il [clr 2]Leblanc[clr 27].[n][w][e]

[sel MND_E10410300_GOTO_CAFE__2 top]
[s]Entro.[e]
[s]Resto fuori.[e]

[msg MND_E10410300_GOTO_CAFE__3]
[s][vp 1 0 0 0 0 0]Prima far韻 un giro[n]nei dintorni...[n][w][e]

[msg MND_E10920100_NG_CAFE_00]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi.[n]為 meglio che mi sbrighi[n]ad andare a scuola...[n][w][e]

[msg MND_E12710100_NG_CAFE_00]
[s][vp 1 0 0 0 0 0]Non posso fare tardi[n]due giorni di seguito. Dovrei[n]sbrigarmi ad andare a scuola.[n][w][e]

[msg MND_E180101_MEDALINFO_00]
[s][vp 1 0 0 0 0 0]Se torno indietro, Sojiro[n]potrebbe appiopparmi qualche[n]mansione da sbrigare.[n][w][e]
[s][vp 1 0 0 0 0 0]E non ho ancora venduto[n]la medaglia...[n][w][e]
[s][vp 1 0 0 0 0 0]Finch姻 non lo far韻, sarebbe[n]meglio evitare il Leblanc...[n][w][e]

[msg MSG_E180101_MEDALINFO_00]
[s][vp 1 0 0 0 0 0]Le leggi della fisica, violate?[n]Andr韻 di nuovo al negozio, come se[n]avessi venduto quella medaglia...[n][w][e]

[msg MND_E180101_MEDALINFO_00_2]
[s][vp 1 0 0 0 0 0]Sono riuscito a vendere la medaglia[n]e ci ho ricavato qualche soldo.[n][w][e]
[s][vp 1 0 0 0 0 0]Chiss稲 che tipo di posto[n]sceglier稲 Ann...[n][w][e]

[msg MSG_E27930100_RECYCLE_SE [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Possiamo preoccuparci dopo del[n]Leblanc. Prima dobbiamo trovare[n]informazioni su Futaba.[n][w][e]

[msg MND_E40110200_NG_CAFE_00]
[s][vp 1 0 0 0 0 0]Ora dovrei andare[n]dove si trova Shido...[n][w][e]

[msg MND_E10410100_NG_SENTOU_]
[s][vp 1 0 0 0 0 0]為 un caratteristico bagno pubblico.[n]Il gradevole profumo del sapone[n]si diffonde nell'aria...[n][w][e]

[msg MND_E10410300_NG_SENTOU_]
[s][vp 1 0 0 0 0 0]為 il bagno pubblico.[n]Il gradevole profumo del sapone[n]si diffonde nell'aria...[n][w][e]
[s][vp 1 0 0 0 0 0]Ora dovrei cercare un[n]locale chiamato [clr 2]Leblanc[clr 27].[n][w][e]

[msg MND_E10410400_NG_SENTOU_]
[s][vp 1 0 0 0 0 0]為 il bagno pubblico.[n]Il gradevole profumo del sapone[n]si diffonde nell'aria...[n][w][e]
[s][vp 1 0 0 0 0 0]Ora dovrei cercare un[n]caff因 chiamato [clr 2]Leblanc[clr 27]. Mi hanno[n]detto che 因 nel vicolo...[n][w][e]

[msg MND_E10920100_NG_SENTOU_]
[s][vp 1 0 0 0 0 0]Il gradevole profumo del sapone[n]si diffonde nell'aria...[n][w][e]
[s][vp 1 0 0 0 0 0]Dovrei sbrigarmi[n]ad andare a scuola...[n][w][e]

[msg MSG_E27930100_NG_SENTOU_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Ora non possiamo fermarci al[n]bagno pubblico. Prima dobbiamo[n]trovare informazioni su Futaba.[n][w][e]

[msg MND_COMMON_NG_SENTOU_000]
[s][vp 1 0 0 0 0 0]Non ho tempo per fermarmi[n]al bagno pubblico...[n][w][e]

[msg MND_COMMON_NG_MACHINE_00]
[s][vp 1 0 0 0 0 0]Ora non ho tempo di[n]fermarmi per comprare da bere...[n][w][e]

[msg MND_E10410100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Al momento non ho sete...[n][w][e]

[msg MND_E10920100_NG_MACHINE]
[s][vp 1 0 0 0 0 0]Adesso non ho proprio il[n]tempo per dissetarmi...[n][w][e]

[msg MSG_E27930100_NG_MACHINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]Possiamo farlo poi?[n]Prima dobbiamo trovare[n]informazioni su Futaba.[n][w][e]

[msg MND_E10410100_NG_RECYCLE]
[s][vp 1 0 0 0 0 0]Il proprietario non[n]因 qui al momento. Sul[n]cartello c'因 scritto "In pausa".[n][w][e]
[s][vp 1 0 0 0 0 0]Questo posto tratta anche[n]elettronica. Forse potrei comprarci[n]qualcosa a buon mercato.[n][w][e]

[msg MND_E10920100_NG_RECYCLE]
[s][vp 1 0 0 0 0 0]Questo sembra il[n]negozio dell'usato.[n][w][e]
[s][vp 1 0 0 0 0 0]Non ho il tempo di dare[n]un'occhiata, per韻. Sar稲 meglio che[n]mi sbrighi ad andare a scuola...[n][w][e]

[msg MSG_E18010100_NG_RECYCLE [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]Eh? Vuoi vendermi una[n]medaglia d'oro?[n][w][e]
[s][vp 1 0 0 0 0 0]為 vero che vendiamo cianfrusaglie[n]di ogni tipo, ma le medaglie[n]non le trattiamo...[n][w][e]
[s][vp 1 0 0 0 0 0]Mi dispiace, ma non posso[n]comprarla. Perch姻 non provi[n]da un'altra parte?[n][w][e]

[msg MSG_E18010100_NG_RECYCLE_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Sai, avevo la sensazione che[n]qui l'avrebbero comprata...[n][w][e]

[msg MSG_E18010100_NG_RECYCLE_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Oh, giusto! Magari la comprer稲[n]il negozio softair?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Proviamo l淫![n][w][e]

[msg MSG_E18010100_NG_RECYCLE_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]No, anche se[n]insisti, non credo[n]che la compreranno.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Proviamo al negozio[n]softair a Shibuya.[n][w][e]

[msg MND_COMMON_NG_RECYCLE_00]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E10410100_NG_BATTING]
[s][vp 1 0 0 0 0 0]Gabbie di battuta[n]in un posto del genere...?[n][w][e]

[msg MND_E10410300_NG_BATTING]
[s][vp 1 0 0 0 0 0]Gabbie di battuta[n]in un posto del genere...?[n][w][e]

[msg MND_E10920300_NG_BATTING]
[s][vp 1 0 0 0 0 0]Non ho tempo per[n]le deviazioni. Devo sbrigarmi[n]ad andare a scuola...[n][w][e]

[msg MSG_E27930100_NG_BATTING [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Non hai tempo per le deviazioni,[n]giusto? Prima dobbiamo[n]trovare informazioni su Futaba.[n][w][e]

[msg MND_COMMON_NG_BATTING_00]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E10410100_NG_CINEMA_]
[s][vp 1 0 0 0 0 0]Dentro 因 buio pesto.[n]Forse questo posto[n]因 stato chiuso...[n][w][e]

[msg MND_E10920100_NG_CINEMA_]
[s][vp 1 0 0 0 0 0]Dentro 因 buio pesto.[n]Forse questo posto[n]因 stato chiuso...[n][w][e]

[msg MSG_E27930100_NG_CINEMA_ [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Non hai tempo per le deviazioni,[n]giusto? Prima dobbiamo[n]trovare informazioni su Futaba.[n][w][e]

[msg MND_COMMON_NG_CINEMA_000]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E10410100_NG_SUPER_0]
[s][vp 1 0 0 0 0 0]Sento provenire un[n]flusso di aria fredda[n]dal locale...[n][w][e]

[msg MND_E10920100_NG_SUPER_0]
[s][vp 1 0 0 0 0 0]Adesso non ho tempo di[n]fare compere.[n]Meglio filare a scuola...[n][w][e]

[msg MSG_E27930100_SuperMarke [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Questo posto 因 vicino al[n]Leblanc, magari qui scopriremo[n]qualcosa![n][w][e]

[msg MSG_E27930100_SuperMarke_2 [Commesso]]
[s][vp 8 0 1 5 65535 0]Benvenuto![n][w][e]
[s][vp 8 0 1 6 65535 0]......[n][w][e]
[s][vp 8 0 1 7 65535 0]Futaba? Da Sakura-san?[n][w][e]
[s][vp 8 0 1 8 65535 0]Mi spiace, non so niente.[n][w][e]
[s][vp 8 0 1 9 65535 0]Torni presto![n][w][e]

[msg MSG_E27930100_SuperMarke_3 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Mmm, non abbiamo scoperto[n]niente su Futaba...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Mi sa che possiamo solo[n]andare a casa e chiedere[n]direttamente al capo...[n][w][e]

[msg MSG_E27930100_NG_SUPER_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_NG_SUPER_000_]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MND_E10410100_DEADEND_00]
[s][vp 1 0 0 0 0 0]為 un vicolo cieco...[n][w][e]

[msg MND_E10920100_DEADEND_00]
[s][vp 1 0 0 0 0 0]為 un vicolo cieco...[n][w][e]

[msg MSG_E27930100_DEADEND_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Questo 因 un vicolo cieco...[n]Non perdiamo tempo qui. Dobbiamo[n]trovare informazioni su Futaba.[n][w][e]

[msg MND_COMMON_DEADEND_000_0]
[s][vp 1 0 0 0 0 0]為 un vicolo cieco...[n][w][e]

[msg MND_E10410100_WASH_NG_00]
[s][vp 1 0 0 0 0 0]Questa lavatrice 因 piuttosto[n]sporca. Forse 因 perch姻 viene[n]usata da parecchio tempo.[n][w][e]

[msg MSG_E79310100_WASH_NG_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ti stai facendo distrarre da[n]una lavatrice? Sbrigati a[n]portarci alla clinica.[n][w][e]

[msg MND_E10920100_WASH_NG_00]
[s][vp 1 0 0 0 0 0]Questa lavatrice 因 piuttosto[n]sporca. Forse 因 perch姻 viene[n]usata da parecchio tempo.[n][w][e]

[msg MSG_E27930100_WASH_NG_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1187 0 0]Ti stai facendo distrarre da[n]una lavatrice? Dobbiamo[n]trovare informazioni su Futaba.[n][w][e]

[msg MND_COMMON_WASH_NG_000]
[s][vp 1 0 0 0 0 0]Questa lavatrice 因 piuttosto[n]sporca. Forse 因 perch姻 viene[n]usata da parecchio tempo.[n][w][e]

[msg MND_E10410100_SPINDRIER_]
[s][vp 1 0 0 0 0 0]Vedo girare dei vestiti[n]all'interno.[n][w][e]

[msg MSG_E79310100_SPINDRIER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Cosa fai?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Su, sbrigati a portarci[n]alla clinica.[n][w][e]

[msg MND_E10920100_SPINDRIER_]
[s][vp 1 0 0 0 0 0]Vedo girare dei vestiti[n]nell'asciugatrice...[n][w][e]
[s][vp 1 0 0 0 0 0]Se continuo a fissarla,[n]far韻 tardi...[n][w][e]

[msg MSG_E27930100_SPINDRIER_ [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_SPINDRIER_NG_]
[s][vp 1 0 0 0 0 0]Vedo girare dei vestiti[n]nell'asciugatrice...[n][w][e]

[msg MND_CHK_ITEM_SHOP_104101]
[s][vp 1 0 0 0 0 0]Questo posto sembra una[n]clinica, ma non credo che[n][clr 2]Sojiro Sakura[clr 27] sia un medico...[n][w][e]

[msg MND_CHK_ITEM_SHOP_104103]
[s][vp 1 0 0 0 0 0]Questo posto sembra una[n]clinica, ma io devo trovare[n]un locale chiamato [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_CHK_ITEM_SHOP_104104]
[s][vp 1 0 0 0 0 0]Questo posto sembra una[n]clinica, ma io devo trovare[n]un locale chiamato [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_CHK_ITEM_SHOP_109203]
[s][vp 1 0 0 0 0 0]Questa sembra essere la[n]clinica. C'因 un vago odore[n]di disinfettante...[n][w][e]
[s][vp 1 0 0 0 0 0]Beh, al momento non ho niente[n]da fare qui. Dovrei andare alla[n][clr 2]stazione di Yongen-Jaya[clr 27]...[n][w][e]

[msg MSG_E27930100_ITEM_SHOP_ [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_CHK_ITEM_SHOP_COMMON]
[s][vp 1 0 0 0 0 0]Non c'因 tempo per le deviazioni...[n][w][e]

[msg MSG_LOOK_EVT_713_010_MON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Questa 因 la clinica[n]menzionata dal capo. Come possiamo[n]farci dare dei farmaci...?[n][w][e]

[sel SEL_LOOK_EVT_713_010_MON top]
[s]Inventeremo qualcosa.[e]
[s]Dobbiamo essere sinceri.[e]
[s]Forse dovremmo andarcene.[e]

[msg MSG_LOOK_EVT_713_010_MON_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Beh, suppongo sia[n]l'unica possibilit稲 che abbiamo.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Dovremo improvvisare.[n]D'accordo, entriamo.[n][w][e]

[msg MSG_LOOK_EVT_713_010_MON_3 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Ti aspetti che una persona normale[n]capisca cosa sia un Palazzo?!?[n][w][e]

[msg MSG_LOOK_EVT_713_010_MON_4 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Ehi, non possiamo rinunciare[n]dopo essere arrivati fin qui![n][w][e]

[msg MND_E104101_CHK_SOJIRO_H]
[s][vp 1 0 0 0 0 0]Sulla targa c'因 scritto[n]"Sakura". Pare che sia[n]la [clr 2]casa di Sojiro Sakura[clr 27]...[n][w][e]

[msg MSG_E104101_CHK_SOJIRO_H]
[s][vp 1 0 0 0 0 0](SE)ピンポーン、というチャイムのSE[n][w][e]

[msg MND_E104101_CHK_SOJIRO_H_2]
[s][vp 1 0 0 0 0 0]Ho suonato il campanello,[n]ma nessuno viene ad aprire[n]la porta.[n][w][e]
[s][vp 1 0 0 0 0 0]Forse 因 uscito...[n][w][e]

[msg MSG_E10410100_000_00 [Uomo delle consegne]]
[s][vp 8 0 1 1 65535 0]A quanto pare non c'因 nessuno...[n][w][e]

[msg MSG_E10410100_001_00 [Uomo delle consegne]]
[s][vp 8 0 1 2 65535 0]Ah, gi稲... Di solito a quest'ora[n]Sakura-san 因 al caff因.[n][w][e]
[s][vp 8 0 1 3 65535 0]Beh, il [clr 2]Leblanc 因 nel[n]vicolo[clr 27], quindi dovrei fare[n]prima le altre consegne...[n][w][e]
[s][vp 8 0 1 4 65535 0]Mmm, il prossimo pacco 因 per...[n][w][e]

[msg MND_E10410200_000_00]
[s][vp 1 0 0 0 0 0]Sembra che nessuno[n]verr稲 ad aprire.[n]Forse 因 uscito...[n][w][e]

[msg MND_E10410300_000_00]
[s][vp 1 0 0 0 0 0]Pare che di solito a quest'ora[n]Sojiro Sakura si trovi a un caff因[n]chiamato Leblanc.[n][w][e]
[s][vp 1 0 0 0 0 0]Dovrei cercare un[n]caff因 di nome [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E10410400_000_00]
[s][vp 1 0 0 0 0 0]Pare che di solito a quest'ora[n]Sojiro Sakura si trovi a un caff因[n]chiamato Leblanc.[n][w][e]
[s][vp 1 0 0 0 0 0]Dovrei cercare un[n]caff因 di nome [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E109201_CHK_SOJIRO_H]
[s][vp 1 0 0 0 0 0]Al momento non devo andare[n]a casa di Sojiro Sakura.[n][w][e]
[s][vp 1 0 0 0 0 0]Dovrei correre a scuola...[n][w][e]

[msg MSG_E79310100_CHK_SOJIRO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Wow, e cos淫 il capo abita qui...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Comunque, non 因 il posto[n]che stiamo cercando.[n][w][e]

[msg MSG_E27930100_CHK_SOJIRO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Wow, e cos淫 il capo abita qui...[n][w][e]

[msg MND_COMMON_CHK_SOJIRO_HO]
[s][vp 1 0 0 0 0 0]Al momento non devo andare[n]a casa di Sojiro Sakura.[n][w][e]

[msg MND_E104101_CHK_DEADEND0]
[s][vp 1 0 0 0 0 0]Non credo che l'indirizzo che[n]cerco sia pi迂 avanti...[n][w][e]

[msg MND_E104103_CHK_DEADEND0]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Dovrei tornare[n]di l稲 e cercare il caff因 [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E104104_CHK_DEADEND0]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Dovrei tornare[n]di l稲 e cercare il caff因 [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E109201_CHK_DEADEND0]
[s][vp 1 0 0 0 0 0]La [clr 2]stazione di Yongen-Jaya[clr 27] dovrebbe[n]trovarsi nella direzione opposta...[n][w][e]

[msg MSG_E27930100_CHK_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Non hai niente da fare pi迂 avanti,[n]vero? Su, dobbiamo recuperare[n]informazioni su Futaba.[n][w][e]

[msg MND_E40110200_CHK_DEADEN]
[s][vp 1 0 0 0 0 0]Mi sto allontanando dalla[n]voce di Shido. Questa sembra[n]la direzione sbagliata...[n][w][e]

[msg MSG_E79310100_CHK_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Prima non abbiamo incrociato[n]l'insegna di quella clinica?[n][w][e]

[msg MND_COMMON_CHK_DEADEND01]
[s][vp 1 0 0 0 0 0]Non ci sono molti negozi[n]interessanti da questa parte.[n]Torniamo indietro.[n][w][e]

[msg MND_E104101_CHK_DEADEND0_2]
[s][vp 1 0 0 0 0 0]Non credo che l'indirizzo che[n]cerco sia pi迂 avanti...[n][w][e]

[msg MND_E104103_CHK_DEADEND0_2]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Dovrei tornare[n]di l稲 e cercare il caff因 [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E104104_CHK_DEADEND0_2]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Dovrei tornare[n]di l稲 e cercare il caff因 [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E109201_CHK_DEADEND0_2]
[s][vp 1 0 0 0 0 0]La [clr 2]stazione di Yongen-Jaya[clr 27] dovrebbe[n]trovarsi nella direzione opposta...[n][w][e]

[msg MSG_E27930100_CHK_DEADEN_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Non hai niente da fare pi迂 avanti,[n]vero? Su, dobbiamo recuperare[n]informazioni su Futaba.[n][w][e]

[msg MND_E40110200_CHK_DEADEN_2]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Andando di qua non[n]trover韻 il luogo del discorso.[n][w][e]

[msg MSG_E79310100_CHK_DEADEN_2 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Non credo che di qua[n]si vada alla clinica...[n][w][e]

[msg MND_COMMON_CHK_DEADEND02]
[s][vp 1 0 0 0 0 0]Pi迂 avanti dovrebbe esserci[n]un'area residenziale, ma[n]non ho motivo di andarci.[n][w][e]

[msg MND_E104101_CHK_DRINK_SH]
[s][vp 1 0 0 0 0 0]Sembra un izakaya con[n]cucina fusion. Pare che sia[n]ancora in allestimento...[n][w][e]

[msg MND_E104301_CHK_DRINK_SH]
[s][vp 1 0 0 0 0 0]Sembra un izakaya con[n]cucina fusion. Pare che sia[n]ancora in allestimento...[n][w][e]
[s][vp 1 0 0 0 0 0]Non credo che sia questo[n]il [clr 2]Leblanc[clr 27].[n][w][e]

[msg MND_E793101_CHK_DRINK_SH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Cucina fusion, eh... Non abbiamo[n]niente da fare qui. Tra l'altro,[n]因 chiuso.[n][w][e]

[msg MND_E109201_CHK_DRINK_SH]
[s][vp 1 0 0 0 0 0]為 un izakaya con[n]cucina fusion.[n][w][e]
[s][vp 1 0 0 0 0 0]Per韻 non c'因 nessuno.[n]Forse non 因 ancora aperto.[n][w][e]

[msg MSG_E27930100_CHK_DRINK_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1001 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_CHK_DRINK_SHO]
[s][vp 1 0 0 0 0 0]為 un izakaya con[n]cucina fusion. Sembra[n]ancora in allestimento...[n][w][e]

[msg MND_E104101_CHK_DRINK_SH_2]
[s][vp 1 0 0 0 0 0]Non vedo nessuno qui dentro...[n][w][e]

[msg MND_E104301_CHK_DRINK_SH_2]
[s][vp 1 0 0 0 0 0]Dall'aspetto, questo posto[n]non sembra il [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E109201_CHK_DRINK_SH_2]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi.[n]Devo andare a scuola...[n][w][e]

[msg MSG_E27930100_CHK_DRINK__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MSG_E79310100_CHK_DRINK_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Ehi... Qui c'因 scritto che 因[n]un diner. Stiamo cercando[n]di trovare la clinica, ricordi?[n][w][e]

[msg MND_COMMON_CHK_DRINK_SHO_2]
[s][vp 1 0 0 0 0 0]Il bar 因 chiuso. All'interno[n]vedo molti bicchieri di vetro...[n][w][e]

[msg MND_E104101_CHK_DEADEND0_3]
[s][vp 1 0 0 0 0 0]Se proseguo per di qua,[n]credo che finir韻 in un posto[n]completamente diverso...[n][w][e]

[msg MND_E104301_CHK_DEADEND0]
[s][vp 1 0 0 0 0 0]Se proseguo per di qua,[n]credo che finir韻 in un posto[n]completamente diverso...[n][w][e]

[msg MND_E109201_CHK_DEADEND0_3]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti.[n][w][e]

[msg MSG_E27930100_CHK_DEADEN_3 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Non hai niente da fare pi迂 avanti,[n]vero? Su, dobbiamo recuperare[n]informazioni su Futaba.[n][w][e]

[msg MND_E40110200_CHK_DEADEN_3]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Andando di qua non[n]trover韻 il luogo del discorso.[n][w][e]

[msg MSG_E79310100_CHK_DEADEN_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Non credo che di qua[n]si vada alla clinica...[n][w][e]

[msg MND_COMMON_CHK_DEADEND04]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]pi迂 avanti.[n][w][e]

[msg MND_E104101_CHK_DEADEND0_4]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale, ma l'indirizzo che[n]cerco non 因 l淫.[n][w][e]
[s][vp 1 0 0 0 0 0]L'abitazione di Sojiro Sakura[n]dovrebbe essere qui intorno...[n][w][e]

[msg MND_E104103_CHK_DEADEND0_3]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Dovrei tornare[n]di l稲 e cercare il caff因 [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E104104_CHK_DEADEND0_3]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Dovrei tornare[n]di l稲 e cercare il caff因 [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E109201_CHK_DEADEND0_4]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale, ma non ho[n]niente da fare l淫.[n][w][e]

[msg MSG_E27930100_CHK_DEADEN_4 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Non hai niente da fare pi迂 avanti,[n]vero? Su, dobbiamo recuperare[n]informazioni su Futaba.[n][w][e]

[msg MND_E40110200_CHK_DEADEN_4]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale. Andando di qua non[n]trover韻 il luogo del discorso.[n][w][e]

[msg MSG_E79310100_CHK_DEADEN_4 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Andando di qua non arriver韻[n]a destinazione...[n][w][e]

[msg MND_COMMON_CHK_DEADEND05]
[s][vp 1 0 0 0 0 0]Pi迂 avanti c'因 un'area[n]residenziale, ma non ho[n]niente da fare l淫.[n][w][e]

[msg MND_E104101_CHK_DRINK_SH_3]
[s][vp 1 0 0 0 0 0]Chiss稲 che tipo di clientela[n]ha un izakaya come questo...[n][w][e]

[msg MND_E104103_CHK_DRINK_SH]
[s][vp 1 0 0 0 0 0]Sto cercando il [clr 2]Leblanc[clr 27].[n]Questo non sembra il[n]posto giusto...[n][w][e]

[msg MND_E104104_CHK_DRINK_SH]
[s][vp 1 0 0 0 0 0]Questo 因 un izakaya. Il[n][clr 2]Leblanc[clr 27] dovrebbe essere un caff因...[n][w][e]

[msg MND_E109201_CHK_DRINK_SH_3]
[s][vp 1 0 0 0 0 0]Non ho tempo di rilassarmi.[n]Devo andare a scuola...[n][w][e]

[msg MSG_E79310100_CHK_DRINK__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Questo 因 un izakaya...[n]Non mi aspetto di trovare[n]un dottore qui.[n][w][e]

[msg MSG_E27930100_CHK_DRINK__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_CHK_DRINK_SHO_3]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]in quest'izakaya.[n][w][e]

[msg MND_E104101_CHK_BONE_REP]
[s][vp 1 0 0 0 0 0]Questa clinica ortopedica[n]ha un nome bizzarro...[n][w][e]

[msg MND_E104103_CHK_BONE_REP]
[s][vp 1 0 0 0 0 0]Si chiama Kurubushi,[n]ma il posto che cerco io[n]si chiama [clr 2]Leblanc[clr 27].[n][w][e]

[msg MND_E104104_CHK_BONE_REP]
[s][vp 1 0 0 0 0 0]Questa 因 una[n]clinica ortopedica. Il[n][clr 2]Leblanc[clr 27] dovrebbe essere un caff因...[n][w][e]

[msg MND_E109201_CHK_BONE_REP]
[s][vp 1 0 0 0 0 0]Chiss稲 che gente viene[n]curata qui...[n][w][e]
[s][vp 1 0 0 0 0 0]Adesso per韻 non ho tempo[n]per pensarci.[n][w][e]

[msg MSG_E79310100_CHK_BONE_R [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]No, non 因 il posto che cerchiamo.[n]Le cliniche ortopediche non hanno[n]i farmaci che ci servono, giusto?[n][w][e]

[msg MSG_E27930100_CHK_BONE_R [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_CHK_BONE_REPA]
[s][vp 1 0 0 0 0 0]Clinica ortopedica Kurubushi...[n]Il nome significa "caviglia", ma[n]non sembra la loro specialit稲.[n][w][e]

[msg MND_E104101_CHK_OLD_APAR]
[s][vp 1 0 0 0 0 0]Non vedo il nome "Sakura"[n]sulla cassetta delle lettere.[n]Non mi sembra il posto giusto.[n][w][e]

[msg MND_E104104_CHK_OLD_APAR]
[s][vp 1 0 0 0 0 0]C'因 un triciclo all'ingresso.[n]Forse qui vive una famiglia[n]con bambini...[n][w][e]

[msg MND_E109201_CHK_OLD_APAR]
[s][vp 1 0 0 0 0 0]Se resto qui, qualcuno[n]potrebbe scambiarmi per un[n]tipo sospetto...[n][w][e]

[msg MSG_E27930100_CHK_OLD_AP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_CHK_OLD_APART]
[s][vp 1 0 0 0 0 0]Se resto qui, qualcuno[n]potrebbe scambiarmi per un[n]tipo sospetto...[n][w][e]

[msg MND_E104101_CHK_TABACO_S]
[s][vp 1 0 0 0 0 0]Non vedo il proprietario.[n]Mi chiedo se questo posto[n]因 aperto...[n][w][e]

[msg MND_E104103_CHK_TABACO_S]
[s][vp 1 0 0 0 0 0]Questo posto non sembra[n]essere il [clr 2]Leblanc[clr 27].[n][w][e]

[msg MND_E104104_CHK_TABACO_S]
[s][vp 1 0 0 0 0 0]Non devo fare niente[n]in questa tabaccheria. Il[n][clr 2]Leblanc[clr 27] dovrebbe essere un caff因...[n][w][e]

[msg MND_E109201_CHK_TABACO_S]
[s][vp 1 0 0 0 0 0]Non mi serve niente[n]in questa tabaccheria...[n][w][e]

[msg MSG_E79310100_CHK_TABACO [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Il proprietario non c'因?[n]Allora non possiamo neanche[n]chiedere della clinica...[n][w][e]

[msg MSG_E27930100_CHK_TABACO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_CHK_TABACO_SH]
[s][vp 1 0 0 0 0 0]Non mi serve niente[n]in questa tabaccheria...[n][w][e]

[msg MND_E104101_CHK_POST]
[s][vp 1 0 0 0 0 0]Non ho niente da spedire.[n]Dovrei cercare l'abitazione[n]di [clr 2]Sojiro Sakura[clr 27]...[n][w][e]

[msg MND_E104103_CHK_POST]
[s][vp 1 0 0 0 0 0]Non ho niente da spedire.[n]Ora dovrei cercare il [clr 2]Leblanc[clr 27]...[n][w][e]

[msg MND_E109201_CHK_POST]
[s][vp 1 0 0 0 0 0]Non ho posta da spedire.[n]Dovrei andare a scuola...[n][w][e]

[msg MSG_E27930100_CHK_POST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Cosa fai? Prima dobbiamo[n]trovare informazioni[n]su Futaba.[n][w][e]

[msg MND_COMMON_CHK_POST]
[s][vp 1 0 0 0 0 0]Non ho posta[n]da spedire...[n][w][e]

[msg MSG_E79310100_NG_BATTING [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Qui ci sono delle gabbie[n]di battuta...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Prima, per韻, dobbiamo[n]trovare quella clinica.[n][w][e]

[msg MSG_E79310100_NG_DEADEND [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Sicuro che sia di qua?[n]Secondo me no...[n][w][e]

[msg MSG_E79310100_NG_SUPER_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Qui non vedo nessuno che[n]abbia l'aria di un dottore.[n][w][e]

[msg MSG_E79310100_NG_CINEMA_ [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Prendiamola pi迂 seriamente.[n]Da qualunque parte lo si guardi,[n]questo posto non 因 una clinica.[n][w][e]

[msg MSG_E79310100_NG_MACHINE [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, ora non hai il tempo di[n]fermarti per comprare da bere.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Su, sbrigati a portarci[n]alla clinica.[n][w][e]

[msg MSG_E79310100_NG_STATION [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 1176 0 0]Dove stai andando?[n]Te l'ho detto, 因 da qualche[n]parte nel quartiere.[n][w][e]

[msg MSG_E79310100_NG_SENTOU_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]Oooh, non sapevo che ci[n]fosse un bagno pubblico qui...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Prima di tutto, per韻, dovremmo[n]trovare quella clinica.[n][w][e]

[msg MSG_E79310100_NG_RUBURAN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Mmm, sembra che non sia[n]ancora al locale...[n][w][e]

[msg MSG_E79310100_RECYCLE_SE [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]Mmm...[n][w][e]
[s][vp 1 0 0 0 0 0]Devo sbarazzarmi di questa TV...[n][w][e]
[s][vp 1 0 0 0 0 0]Sarebbe meglio se[n]la vendessi, invece[n]di gettarla via...[n][w][e]
[s][vp 1 0 0 0 0 0]Ma chi comprerebbe una[n][clr 2]TV[clr 27] cos淫 vecchia al giorno d'oggi?[n][w][e]

[msg MSG_E79310100_RECYCLE_SE_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sembra che abbiano un sacco[n]di cose... Prima, per韻, dobbiamo[n]trovare quella clinica.[n][w][e]

[msg MSG_E27930100_RECYCLE_SE_2 [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]Mmm...[n][w][e]
[s][vp 1 0 0 0 0 0]Una vecchia console da gioco.[n][w][e]
[s][vp 1 0 0 0 0 0]Forse riuscirei a venderla se[n]aggiungessi qualche gioco?[n][w][e]
[s][vp 1 0 0 0 0 0]Non so proprio chi vorrebbe[n]una [clr 2]console per videogiochi[clr 27][n]cos淫 vecchia, per韻...[n][w][e]

[msg MSG_E27930100_RECYCLE_SE_3 [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]...Mmm? Posso aiutarti?[n][w][e]

[sel MSG_E27930100_RECYCLE_SE_4 top]
[s]Conosce Futaba Sakura?[e]
[s]Mi parli di Futaba Sakura.[e]

[msg MSG_E27930100_RECYCLE_SE_5 [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]Futaba...?[n][w][e]
[s][vp 1 0 0 0 0 0]Ogni tanto vengono dei giovani a[n]curiosare... ma temo di non[n]conoscerli per nome.[n][w][e]

[msg MSG_E27930100_RECYCLE_SE_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Niente da fare neanche qui, eh?[n]Chiediamo ad altre persone.[n][w][e]

[msg MSG_E27930100_RECYCLE_GA [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]...Mmm? Posso aiutarti?[n][w][e]

[sel MSG_E27930100_RECYCLE_GA_2 top]
[s]Conosce Futaba Sakura?[e]
[s]Mi parli di Futaba Sakura.[e]

[msg MSG_E27930100_RECYCLE_GA_3 [Gestore del negozio dell'usato]]
[s][vp 1 0 0 0 0 0]Futaba? Mmm...[n][w][e]
[s][vp 1 0 0 0 0 0]Ogni tanto vengono dei giovani a[n]curiosare... ma temo di non[n]conoscerli per nome.[n][w][e]

[msg MSG_E27930100_RECYCLE_GA_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Niente da fare neanche qui, eh?[n]Chiediamo ad altre persone.[n][w][e]

[msg MND_CHK_ITEM_SHOP_SEARCH]
[s][vp 1 0 0 0 0 0]Sull'insegna c'因 scritto[n]"Clinica di medicina interna[n]Takemi"...[n][w][e]

[msg MSG_CHK_ITEM_SHOP_SEARCH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1167 0 0]L'insegna 因 accesa.[n]D'accordo, entriamo![n][w][e]

[msg MND_KFEVT_0103_0108_CHK_]
[s][vp 1 0 0 0 0 0]Forse dovrei andare a Shibuya...[n][w][e]

[sel MND_KFEVT_0103_0108_CHK__2 top]
[s]Vai a Shibuya.[e]
[s]Vai alla stazione.[e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_CinemaBuyTicketSIBUY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1179 65535 0]Ah, gi稲! Prima devi[n]comprare un biglietto.[n][w][e]

[msg MSG_CinemaCancel [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1003 65535 0]Hai cambiato idea?[n][w][e]

[msg MSG_CinemaOK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Il film sta per iniziare.[n]Andiamo a sederci.[n][w][e]

[msg MSG_CinemaWatched [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1177 65535 0][var 7]?[n]Ne ho avuto abbastanza di quello...[n]Torniamo un'altra volta.[n][w][e]

[msg MSG_CinemaBuyTicket [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1157 65535 0]Per vedere un film[n]devi comprare un biglietto.[n][w][e]

[msg MND_ParamEndInfo_Atama]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Miryoku]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Kiyou]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Dokyo]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_ParamEndInfo_Yasas]
[s]Dovrei avere gi稲 abbastanza[n][stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

[msg MSG_ParamMoru_Atama [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MSG_ParamMoru_Miryoku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare il tuo[n][stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MSG_ParamMoru_Kiyou [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MSG_ParamMoru_Dokyo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare il tuo[n][stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MSG_ParamMoru_Yasas [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Pare che questo film possa[n]insegnarti a migliorare la tua[n][stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Chiss稲 che film stanno[n]proiettando adesso...[n][w][e]

[msg MSG_Cinema_MoneyNG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Controlla il portafoglio.[n]Non hai abbastanza soldi.[n][w][e]

[msg MSG_CINEMA_MEMBER_NG [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1112 65535 0]Quante volte hai intenzione di[n]vedere lo stesso film?[n]Dacci un taglio...[n][w][e]

[msg MSG_CINEMA_1ST_ACCESS_SI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Wow, questo cinema 因 immenso![n]Chiss稲 che film stanno proiettando adesso...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questo dovrebbe essere un[n]cinema, giusto? Ma 因 vuoto...[n]Forse 因 chiuso.[n][w][e]

[msg MND_CINEMA_NOT_OPEN]
[s]Al momento il cinema[n]因 chiuso...[n][w][e]

[msg MSG_CINEMA_NOT_OPEN02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Non c'因 anima viva. Sembra[n]che non apra nemmeno[n]di sera. Che succede?[n][w][e]

[msg MSG_CINEMA_BOOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Visto che hai finito di leggere[n][clr 3]Anima da cineasta[clr 27], scommetto che[n]apprezzerai ancora di pi迂 il film.[n][w][e]

[msg MSG_COMMENT_LIST01_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un adolescente che[n]diventa milionario vincendo al quiz[n]"Le sedici domande"...[n][w][e]

[msg MSG_COMMENT_2ndINFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, 因 [var 7].[n]Vuoi rivederlo?[n][w][e]

[msg MSG_COMMENT_LIST02_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un eroe che[n]cerca di sgominare[n]crimine e corruzione.[n][w][e]

[msg MSG_COMMENT_LIST03_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo che fatica[n]a confessare i propri sentimenti[n]alla donna che ama.[n][w][e]

[msg MSG_COMMENT_LIST04_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo che cerca[n]di ricostruire la sua vita[n]dopo una lunga carcerazione.[n][w][e]

[msg MSG_COMMENT_LIST05_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo che deve entrare[n]nel suo appartamento ultraprotetto[n]dopo aver perso la chiave.[n][w][e]

[msg MSG_COMMENT_LIST06_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un uomo con[n]l'incarico di pulire un enorme[n]grattacielo nel giorno di Natale.[n][w][e]

[msg MSG_COMMENT_LIST14_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un pap稲 vespa in[n]viaggio con l'amico ape per salvare[n]il figlio catturato dagli umani.[n][w][e]

[msg MSG_COMMENT_LIST07_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di un gatto robot[n]che noleggia strumenti utili[n]ma a prezzo salatissimo.[n][w][e]

[msg MSG_COMMENT_LIST08_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]I soldi spariscono, il boss[n]ci rimette la pelle e le strade[n]di Tokyo si tingono di rosso...[n][w][e]

[msg MSG_COMMENT_LIST09_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia delle persone pi迂[n]inutili del mondo che formano una[n]squadra per combattere gli alieni.[n][w][e]

[msg MSG_COMMENT_LIST10_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di due uomini intrappolati in[n]una stanza con un elefante[n]imbizzarrito. Se la caveranno?[n][w][e]

[msg MSG_COMMENT_LIST15_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo insonne[n]che impazzisce dopo un certo[n]incontro in un negozio di kebab.[n][w][e]

[msg MSG_COMMENT_LIST11_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la tragica storia di[n]un boss della mafia che[n]adora i propri figli.[n][w][e]

[msg MSG_COMMENT_LIST12_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Un tipo viaggia indietro nel[n]tempo e impara il ninjutsu, per[n]vendicare l'amico ucciso da un ninja.[n][w][e]

[msg MSG_COMMENT_LIST13_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]為 la storia di alcuni prigionieri[n]di guerra costretti a lavorare[n]duramente nonostante sia Natale.[n][w][e]

[msg MSG_COMMENT_LIST16_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di una donna pastore e di[n]uno psichiatra amante dei montoni[n]sulle tracce di un tosatore seriale.[n][w][e]

[msg MSG_COMMENT_LIST17_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un universitario che lotta[n]per la liberazione del suo[n]dormitorio oppresso.[n][w][e]

[msg MSG_COMMENT_LIST18_INFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Siamo arrivati in tempo per vedere[n][var 7].[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Parla di un uomo che si unisce per[n]caso a un circo, riuscendo a[n]fare carriera grazie al carisma.[n][w][e]

[msg MND_Sentou_ParamInfo_Chi]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo_]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 0][clr 26][stLabel 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Dok]
[s]Pare che guardando questo film[n]potrei migliorare il mio [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__2]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora il mio [stIcon 3][clr 26][stLabel 3][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Yas]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__3]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 4][clr 26][stLabel 4][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Iro]
[s]Pare che guardando questo film[n]potrei migliorare il mio [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__4]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora il mio [stIcon 1][clr 26][stLabel 1][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo_Kiy]
[s]Pare che guardando questo film[n]potrei migliorare la mia [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

[msg MND_Sentou_ParamEndInfo__5]
[s]Anche se guardo questo film,[n]non credo che potr韻 migliorare[n]ancora la mia [stIcon 2][clr 26][stLabel 2][clr 27].[n][w][e]

