[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_CONFES [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]Ricordi quando ti 因 stato chiesto[n]di confessarti? La situazione[n]era diventata impossibile...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]為 stato meglio cos淫.[n]Ecco perch姻 sei speciale.[n][w][e]

[msg MSG_LAST_GREETING_CONFES_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Vuoi confessarti un'ultima volta?[n]A me sta bene, ma non[n]preferisci incontrare gli altri?[n][w][e]

[msg MSG_LAST_GREETING_ORGAN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]S淫, non c'因 chiesa senza organo.[n]Sarebbe stato bello sentirlo[n]suonare per il nostro addio.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Non possiamo attendere oltre...[n]Dobbiamo prepararci alla svelta![n][w][e]

[msg MSG_GATE_DEAFULT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Vuoi andare altrove?[n][w][e]

[sel GATE_YESNO_SEL top]
[s]Gi稲.[e]
[s]Non importa.[e]

[msg MSG_GATE_CANCEL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Uhm, devi ancora fare[n]qualcosa qui?[n][w][e]

[msg MSG_ORGAN_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Se lo suoni senza permesso[n]ti urleranno dietro...[n][w][e]

[msg MSG_ORGAN]
[s]Qui c'因 un organo...[n][w][e]

[msg MSG_ZANGE_BEFOR_001_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Cos'因 questa stanza? Una specie[n]di magazzino?[n][w][e]

[msg MSG_Zange_Start_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oh, vuoi usare il confessionale?[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Guarda per韻 che il prete non[n]因 qui per sentire le[n]tue confessioni.[n][w][e]

[msg MSG_Zange_WhoInvite [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ci vorr稲 un po' per[n]far arrivare qualcuno.[n][w][e]
[s][f 4 10 65535 0 0]Allora, chi vuoi che ricordi[n]un'abilit稲 dimenticata?[n][w][e]

[msg MSG_ZANGE_MAIN_005_00_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oooh, scegli me?[n][w][e]

