[msg MSG_LAST_GREETING_PAPER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]I volantini devono essere opera di[n]Iwai. La sua calligrafia... 因 pi迂[n]carina di quanto mi aspettassi.[n][w][e]

[msg MSG_LAST_GREETING_CUPSUL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Dubito che nella tua citt稲 ci siano[n]molti distributori gachapon militari...[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_GOTO_OUT_NG]
[s][vp 8 2 1 0 65535 0]...Non ho ancora un'arma.[n]Dovrei parlare col proprietario.[n][w][e]

[msg CHK_PAPER_RACK_PC_0404_0]
[s][vp 8 2 1 0 65535 0]Sembra la pubblicit稲[n]per la replica di un'arma.[n][w][e]
[s][vp 8 2 1 0 65535 0]為 piena di parole[n]che non conosco...[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ti interessa quel revolver?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]為 dotato di un copricanna[n]completo e l'effetto[n]stabilizzante 因 pazzesco.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]La molla 因 di acciaio inossidabile.[n]Se ti serve solo per collezione, posso[n]caricarla con pallottole finte.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_2 [Manager scontroso]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ti interessa quel revolver?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]為 dotato di un copricanna[n]completo e l'effetto[n]stabilizzante 因 pazzesco.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]La molla 因 di acciaio inossidabile.[n]Se ti serve solo per collezione, posso[n]caricarla con pallottole finte.[n][w][e]

[sel CHK_PAPER_RACK_0404_SEL top]
[s]D'accordo, certo.[e]
[s]Preferirei evitare.[e]

[msg CHK_PAPER_RACK_IWAI_0404_3 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Ah, s淫? Sembra che tu[n]sia un tipo cauto.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_4 [Manager scontroso]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]...Ah, s淫? Sembra che tu[n]sia un tipo cauto.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_5 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh... Beh, non ti giudico.[n]Se volevi metterti in mostra,[n]hai scelto il modo giusto.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_6 [Manager scontroso]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh... Beh, non ti giudico.[n]Se volevi metterti in mostra,[n]hai scelto il modo giusto.[n][w][e]

[msg CHK_PAPER_RACK_PC_0418]
[s][vp 8 2 1 0 65535 0]為 un volantino di partecipazione[n]a un gioco di sopravvivenza.[n][w][e]
[s][vp 8 2 1 0 65535 0]A quanto pare c'因 un club[n]di giochi di sopravvivenza[n]anche alla Shujin Academy...[n][w][e]

[msg CHK_PAPER_RACK_0425]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s]"Repliche di armi sempre nuove[n]e svariati prodotti militari,[n]ogni mese!"[n][w][e]

[msg CHK_PAPER_RACK_0503]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Il prodotto consigliato di questo[n]mese 因 un vero gioiello: [clr 4]Bianchi SBAS[clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0519]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"La stella della selezione di giugno[n]因... l'atteso [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"La rinascita esplosiva: la [clr 4]Falco delle sabbie[clr 27]![n]Estremamente popolare: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0607]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"La specialit稲 del mese[n]因 finalmente arrivata! La [clr 4]Comet 3[clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0620]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Con il mese di luglio,[n]ritorna una leggenda: [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"Festeggia 50 anni: [clr 4]Fuoco infernale[clr 27]![n]E un arrivo straordinario: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0710]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Il prodotto consigliato di questo[n]mese 因 il capolavoro del[n]secolo: [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0725]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Settembre parte col botto![n] Ecco a voi [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"Una potenza schiacciante: [clr 4]Annihilator[clr 27]![n]Con dettagli perfetti: [clr 4][var 3][clr 27]!"   [n][w][e]

[msg CHK_PAPER_RACK_0815]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Il consiglio del mese prossimo![n]Adorato dal campione del mondo![n]Parliamo di: [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0831]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Ecco la stella della selezione di[n]ottobre! 為 supersonico: [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"Pura distruzione: la [clr 4]SMG occidentale[clr 27]![n]Grande stabilit稲: [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0914]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Il prodotto in primo piano di ottobre[n]因 cos淫 realistico che potrebbe[n]quasi essere vero: [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0921]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"La nuova stella della selezione[n]di novembre 因: [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"La [clr 4]Calamit稲[clr 27] fa il suo ritorno![n]Per i novellini, 因 [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1012]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Il prodotto in primo piano di[n]questo mese 因 una rarit稲![n]L'[clr 4]Eliminatore[clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1026]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"La selezione di dicembre porta[n]con s姻 l'atteso [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"Per i fan! La [clr 4]Pistola R. I.[clr 27]![n]Per proteggere la pace! [clr 4][var 3][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1109]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Il prodotto consigliato di fine[n]anno 因 il leggendario [clr 4][var 1][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_1123]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]

[msg CHK_PAPER_RACK_1207]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]

[msg CHK_PAPER_RACK_1219]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Gennaio ci propone la nuova[n]opera di un maestro! [clr 4][var 1][clr 27]!"[n][w][e]
[s][vp 8 2 1 0 65535 0]"L'ultimo esemplare: [clr 4]SIG 227[clr 27]![n]Uno in ogni famiglia: [clr 4][var 2][clr 27]!"[n][w][e]

[msg CHK_PAPER_RACK_0101]
[s][vp 8 2 1 0 65535 0]Sembra una pubblicit稲[n]di questo negozio...[n][w][e]
[s][vp 8 2 1 0 65535 0]"Ecco la stella della selezione[n]di gennaio! Senti la nuova[n]brezza: [clr 4][var 1][clr 27]!"[n][w][e]

[msg MSG_CUPSULE_MACHINE_NOSA]
[s][vp 8 2 1 0 65535 0]為 un distributore di razioni.[n][w][e]
[s][vp 8 2 1 0 65535 0]C'因 scritto "Rifornimento[n]in arrivo a giorni!"[n][w][e]

[msg MSG_CUPSULE_MACHINE_0401 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 37".[n][w][e]

[msg MSG_CUPSULE_MACHINE_0607 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 38".[n][w][e]

[msg MSG_CUPSULE_MACHINE_0815 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 39".[n][w][e]

[msg MSG_CUPSULE_MACHINE_1012 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 40".[n][w][e]

[msg MSG_CUPSULE_MACHINE_1207 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 41".[n][w][e]

[msg MSG_CUPSULE_MACHINE_0101 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 42".[n][w][e]

[msg MSG_CUPSULE_MACHINE_0109]
[s][vp 8 2 1 0 65535 0]C'因 scritto "Prova del Gusto![n]Razioni del mondo, volume 42".[n][w][e]

[msg MSG_CUPSULE_MACHINE_0404 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Costa 800 yen per tentativo, ma...[n]Vuoi provare?[n][w][e]

[msg MSG_CUPSULE_MACHINE_0404_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Costa 800 yen per[n]tentativo. Vuoi provare?[n][w][e]

[msg MSG_CUPSULE_MACHINE_0109_2]
[s][vp 8 2 1 0 65535 0]Una prova costa 800 yen.[n]Vuoi fare un tentativo?[n][w][e]

[sel MIRIMESI_SEL top]
[s]Diamogli una possibilit稲.[e]
[s]Lasciamo stare.[e]

[msg SEL_MIRIMESI_A_02]
[s][vp 8 2 1 0 65535 0]La capsula 因 appiccicosa...[n][w][e]

[msg SEL_MIRIMESI_A_03]
[s][vp 8 2 1 0 65535 0]Forse me lo sto immaginando,[n]ma per un secondo ho sentito[n]un odore terribile...[n][w][e]

[msg SEL_MIRIMESI_A_04]
[s][vp 8 2 1 0 65535 0]A prima vista sembra[n]normale, per韻...[n][w][e]

[msg SEL_MIRIMESI_BIG_HAZURE [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13074 65535 0]...Beh, che peccato.[n][w][e]

[msg SEL_MIRIMESI_HAZURE [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13043 65535 0]...Non male.[n][w][e]

[msg SEL_MIRIMESI_ATARI [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 1 13045 65535 0]Oh... che fortuna.[n][w][e]

[msg SEL_MIRIMESI_BIG_HAZURE_ [Manager scontroso]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13074 65535 0]...Beh, che peccato.[n][w][e]

[msg SEL_MIRIMESI_HAZURE_name [Manager scontroso]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13043 65535 0]...Non male.[n][w][e]

[msg SEL_MIRIMESI_ATARI_namel [Manager scontroso]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 1 13045 65535 0]Oh... che fortuna.[n][w][e]

[msg MSG_CUPSULE_NO_MONEY [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]Wow. Non hai abbastanza soldi.[n][w][e]

[msg MSG_CUPSULE_NO_MONEY_HER]
[s][vp 8 2 1 0 65535 0]Non ho abbastanza soldi...[n][w][e]

[msg MND_NOOPEN_SHOP]
[s]Non ho ancora[n]comprato nulla...[n][w][e]

[msg MSG_180105_GOTO_NG_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Non hai ancora venduto la[n]medaglia d'oro, vero? Non andartene[n]senza chiedere di poterla vendere![n][w][e]

[msg MSG_OPEN_SHOP [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]Vuoi gi稲 tornare a casa?[n][w][e]
[s][vp 8 2 1 0 65535 0]Comunque, dovrai scegliere tu[n]da adesso in poi. Trova[n]quello che sembra pi迂 forte![n][w][e]

[msg MSG_C12_BEGIN_TIME_08 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13001 212 0]Hai una faccia fin troppo seria.[n]Non voglio finire nei guai,[n]quindi non far韻 domande.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Se vuoi qualcosa,[n]puoi dare un'occhiata.[n][w][e]

[msg MSG_C12_BEGIN_TIME_08_01 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]...Cerca di non esagerare.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109_ [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13082 212 0]Scusa per averti trattenuto.[n]Felice anno nuovo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Stanno passando troppi[n]piantagrane per l'anno nuovo.[n]Il posto non aiuta.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 13090 212 0]Sembra che l'intera[n]citt稲 sia impazzita.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109__2 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Se vuoi qualcosa,[n]puoi dare un'occhiata.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109__3 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Ci vediamo.[n][w][e]

