[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Una volta sei stato qui con Makoto,[n]giusto? 為 cambiata da allora...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]A ogni modo... Questo tizio,[n]Takekuma, vero? Deve amare[n]davvero molto questo gioco.[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Una volta sei stato qui con Makoto,[n]giusto? 為 cambiata da allora...[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Questo tizio, Takekuma, vero?[n]Deve amare davvero molto[n]questo gioco.[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Non c'因 tempo per giocare.[n]Andiamo a incontrare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_JUICE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Sembra che ci sia un succo[n]molto raro... Ma la nostra[n]priorit稲 因 salutare tutti quanti.[n][w][e]

[msg MSG_LAST_GREETING_BATTLE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Kunoichi e Machimusume stanno[n]combattendo. Sono entrambi[n]ricoperti di sangue...[n][w][e]

[msg MSG_LAST_GREETING_MONEY_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1111 65535 0]Ehi, perch姻 stai cambiando[n]dei soldi?!? Non avrai intenzione[n]di metterti a giocare, vero?[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_GUN_DEAFULT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Una pistola per giochi, eh?[n]為 ben costruita, ma resta[n]un giocattolo.[n][w][e]

[msg quest27_hint_talk_00 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Che c'因? Vuoi giocare?[n][w][e]
[s]Adesso a Gun About ci sto[n]giocando io, quindi[n]non seccarmi.[n][w][e]

[msg quest27_hint_talk_01 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Ehi! Hai preso le monete?[n][w][e]

[msg quest27_hint_talk_02 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]Non accetta la mia banconota[n]da 1.000 yen![n][w][e]

[msg quest27_hint_talk_03 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Oh, ecco l'occasione che[n]aspettavo! Quel cheater ha[n]effettuato l'accesso![n][w][e]
[s]Presto, sbrigati a portarmi[n]delle monete![n][w][e]

[sel SELquest27_hint_talk_04 top]
[s]Fammi giocare.[e]
[s]Il cheater?[e]

[msg quest27_hint_talk_05 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Mi dispiace, ma da qui[n]non mi staccher韻 per un bel po'.[n][w][e]
[s]Un momento. Ti piace Gun About[n]ma non sai del baro?[n][w][e]

[msg quest27_hint_talk_06 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]C-C'因 un famoso cheater di cui[n]in rete si lamentano tutti.[n][w][e]
[s]Per quanto tu possa attaccarlo,[n]non subisce mai danni e nessuno[n]l'ha mai battuto.[n][w][e]
[s]Gli sviluppatori gli hanno[n]chiuso l'account, ma lui ne[n]crea sempre di nuovi.[n][w][e]

[msg quest27_hint_talk_07 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Alcuni sono riusciti a risalire[n]al suo nome da un social[n]network. La gente 因 infuriata.[n][w][e]
[s]Credo che il suo vero nome[n]sia [clr 2]Yoshikuni Nejima[clr 27].[n]Un quarantenne disoccupato.[n][w][e]
[s]Ma io batter韻 questo Nejima[n]e diventer韻 un eroe.[n][w][e]

[msg quest27_hint_talk_08 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]Per韻 mi pare che tu sia ben lontano dal vincere...[n][w][e]

[msg quest27_hint_talk_09 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Zitto! Piuttosto, vammi a[n]prendere altre monete![n][w][e]

[msg MSG_quest27_morgana_10 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Cos淫 quello 因 il giocatore[n]disonesto di cui parlava Makoto.[n]Il famigerato baro.[n][w][e]
[s][f 4 10 65535 0 0]Una cosa 因 usare i trucchi[n]quando giochi da solo, un'altra[n]quando sono coinvolti anche altri.[n][w][e]
[s][f 4 10 65535 0 0]E conosciamo il suo nome.[n]Sembra proprio che [clr 2]Yoshikuni Nejima[clr 27][n]sar稲 il nostro prossimo bersaglio.[n][w][e]

[msg MSG_quest27_Target_Find]
[s]Adesso che hai un bersaglio, devi assicurarti[n]che tutti i tuoi compagni siano d'accordo.[n]Convocali al ritrovo per una votazione.[n][w][e]

[msg quest27_hint_talk_11 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Sbrigati a portarmi altre[n]monete! Prima che quel[n]bastardo di Nejima se ne vada![n][w][e]

[msg quest27_hint_talk_12 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]M-Ma...[n]N-Non mi accetta i soldi...[n][w][e]

[msg quest27_hint_talk_20 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Ehi, noi ci siamo gi稲 visti,[n]vero?[n][w][e]
[s]Allora siamo amici, giusto?[n]Beh, potresti prestarmi dei soldi?[n][w][e]

[msg quest27_hint_talk_21 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]Ehi, non puoi chiedere soldi[n]alla gente cos淫![n][w][e]
[s]Arrenditi.[n]Per cercare di battere Nejima[n]hai speso tutti i tuoi soldi.[n][w][e]

[msg quest27_hint_talk_22 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Tsk. E va bene.[n]Allora, che vuoi?[n][w][e]

[sel SELquest27_hint_talk_23 top]
[s]Conosci il Re?[e]
[s]Sei tu il Re?[e]

[msg quest27_hint_talk_24 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Il Re? Certo che lo conosco.[n][w][e]

[msg quest27_hint_talk_25 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Io il Re? Figuriamoci.[n][w][e]

[msg quest27_hint_talk_26 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]Stai parlando del Re di[n]Akihabara, giusto?[n][w][e]
[s]Va ancora alle[n]elementari, ma a Gun About[n]因 un vero professionista.[n][w][e]

[msg quest27_hint_talk_27 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]Quel maledetto moccioso...[n]Dev'essere un baro anche lui.[n][w][e]

[msg quest27_hint_talk_28 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]Pare che di solito giochi alla[n]sala giochi Gigolo di Akiba.[n][w][e]
[s]A vederlo non si direbbe,[n]ma la sua abilit稲 因 eccezionale.[n][w][e]
[s]Dovresti trovarlo l淫 di giorno.[n]為 troppo piccolo per andare[n]alla sala giochi la sera.[n][w][e]

[msg quest27_hint_talk_29 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Quindi forse il Re 因 al[n]Gigolo di Akihabara...[n]Andiamo a controllare.[n][w][e]

[msg quest27_hint_talk_30 [Gamer agitato]]
[s][f 4 23 1 613 3 10 0 10]Credo il Re sia[n]al Gigolo di Akihabara.[n][w][e]

[msg quest27_hint_talk_31 [Gamer arrabbiato]]
[s][f 4 23 1 614 3 10 0 10]為 un bambino delle elementari[n]e si fa chiamare Re...[n]Sicuro che bara.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Al momento non ho sete...[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Pensavi di comprare[n]qualcosa da bere?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Tutto esaurito...[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ops, tutto esaurito.[n]Aspettiamo che venga rifornito,[n]la settimana prossima.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]...Tutto esaurito.[n]Non 因 una sorpresa,[n]con il caldo che fa...[n][w][e]

[msg MSG_BATTLE_CABINET_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Un samurai e un ninja stanno[n]combattendo. Il sangue 因[n]pazzesco...[n][w][e]

[msg MSG_BATTLE_CABINET]
[s]Uno scontro tra un samurai[n]e un ninja... Dev'essere[n]un cabinato di lotta.[n][w][e]

[msg MSG_MONEY_CHANGER_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Wow, questo ti fa scegliere che[n]monetine ricevere? Ottimo per[n]giochi con costo diverso.[n][w][e]

[msg MSG_MONEY_CHANGER]
[s]Qui c'因 un cambiamonete...[n][w][e]

[msg MSG_GUNSHOOT_CABINET_NG_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]Adesso non hai tempo[n]per giocarci, no?[n][w][e]

[msg MSG_GAME_NOTE_NG_000_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Mmm, non vedo niente di[n]particolarmente interessante...[n][w][e]

