[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_UFO_Ca [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Tu hai raccolto dei pupazzi, vero?[n]Potrai goderteli quando[n]tornerai a casa.[n][w][e]

[msg MSG_LAST_GREETING_UFO_Ca_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]Non ti interessano queste bambole,[n]vero? Andiamo altrove.[n][w][e]

[msg MSG_LAST_GREETING_GunSho [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Guardare questo cabinato mi[n]ricorda Shinya.[n][w][e]

[msg MSG_LAST_GREETING_GunSho_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Ehi, non abbiamo tempo per giocare![n][w][e]

[msg MSG_LAST_GREETING_Side_U [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Non c'因 tempo da perdere, sai?[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_Center [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Non c'因 tempo da perdere, sai?[n]Andiamo a salutare gli altri.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_GunShoot [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Un controller a forma di pistola?[n]Ce n'因 qualcuno che sembra[n]una fionda?[n][w][e]

[msg MSG_SideUFO [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Questa sala giochi 因 piena[n]di giochi con l'artiglio.[n][w][e]

[msg MSG_CenterUFO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Mi sembra... di averlo gi稲 visto...[n][w][e]

