[msg MSG_LAST_GREETING_LEAFLE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Pensi che questi volantini[n]siano di Takemi'[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Immagino sia pi迂 all'antica di[n]quanto sembri. Che tenerezza.[n][w][e]

[msg MSG_LAST_GREETING_LEAFLE_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Basta con i volantini! Forza![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_CLINIC_LOCK_713_010_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Chiediamo alla receptionist il[n]farmaco di cui abbiamo sentito[n]parlare. Quello delle "energie illimitate".[n][w][e]

[msg MSG_GOTO_OUT_NG_0416 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ehi, siamo venuti fin qui. Non[n]possiamo rinunciare ora![n][w][e]

[msg CHK_LEAFLETS_0404]
[s]"~Bollettino sanitario: edizione[n]di aprile~... Qui dice di fare[n]attenzione all'insonnia latente.[n][w][e]
[s]Chiss稲 se tra i sintomi ci sono[n]dei sogni assurdi...[n][w][e]

[msg CHK_LEAFLETS_0401]
[s]"~Bollettino sanitario: edizione di aprile~[n]Attento all'insonnia latente/leggera"[n]...Ecco cosa dice.[n][w][e]
[s]Chiss稲 se tra i sintomi ci sono[n]dei sogni assurdi...[n][w][e]

[msg CHK_LEAFLETS_0425]
[s]"Siamo nel periodo peggiore per le[n]allergie provocate dal cipresso hinoki.[n]Non uscire nelle giornate ventose!"[n][w][e]

[msg CHK_LEAFLETS_0503]
[s]"Informazioni sulla Gara[n]di passeggiate salutari[n]di inizio estate"[n][w][e]
[s]"La carenza di esercizio pu韻[n]favorire problemi cardiaci, quindi[n]sfrutta l'estate per essere attivo."[n][w][e]

[msg CHK_LEAFLETS_0519]
[s]"~Bollettino sanitario: edizione di maggio~[n]Hai la febbre primaverile?"[n][w][e]
[s]"Quando inizi ad adattarti a[n]un nuovo ambiente, la tua mente[n]因 appesantita da mille pensieri?"[n][w][e]
[s]"Non cercare di fare tutto[n]insieme, ma prendi frequenti[n]pause quando possibile!"[n][w][e]

[msg CHK_LEAFLETS_0607]
[s]"~Curiosit稲 mediche~"[n][w][e]
[s]"I farmaci non amano[n]l'umidit稲. Non conservarli in[n]cucina o in zone analoghe".[n][w][e]

[msg CHK_LEAFLETS_0620]
[s]"~Bollettino sanitario: edizione di[n]giugno~ Attento alla depressione[n]lieve nella stagione delle piogge"[n][w][e]
[s]"In questa stagione calda e[n]piovosa, mantieni attivo il[n]corpo, anche al chiuso!"[n][w][e]

[msg CHK_LEAFLETS_0710]
[s]"~Bollettino sanitario: edizione di[n]luglio~ Medicine per i cuori affranti"[n][w][e]

[msg CHK_LEAFLETS_0725]
[s]"~Curiosit稲 mediche~"[n][w][e]
[s]"Assicurati di assumere i farmaci[n]con l'acqua. Le medicine sono[n]progettate per sciogliersi in acqua".[n][w][e]

[msg CHK_LEAFLETS_0815]
[s]"Attento alla spossatezza estiva!"[n][w][e]
[s]"Il maiale contiene vitamina B1 e[n]acido citrico, quindi 因 perfetto contro[n]la fatica! Provalo freddo in salsa ponzu".[n][w][e]

[msg CHK_LEAFLETS_0831]
[s]"~Curiosit稲 mediche~"[n][w][e]
[s]"Non sbriciolare i farmaci[n]prima di assumerli".[n][w][e]
[s]"Sono studiati per far dissolvere i[n]componenti in un ordine specifico,[n]a partire dall'esterno".[n][w][e]

[msg CHK_LEAFLETS_0914]
[s]"為 pi迂 facile prendere il raffreddore[n]con il clima instabile, durante[n]il cambio di stagione".[n][w][e]
[s]"Puoi raffreddarti agendo in[n]modo sconsiderato. Non dormendo[n]abbastanza, per esempio".[n][w][e]
[s]"Prenditi sempre cura del[n]tuo corpo".[n][w][e]

[msg CHK_LEAFLETS_0921]
[s]"~Bollettino sanitario: edizione di[n]settembre~ L'autunno favorisce la[n]depressione stagionale"[n][w][e]
[s]"Assicurati di stare all'aperto[n]e alla luce del sole,[n]quando il cielo 因 sereno".[n][w][e]

[msg CHK_LEAFLETS_1012]
[s]"~Bollettino sanitario: edizione di[n]ottobre~ Arriva la stagione con il tasso[n]maggiore di intossicazioni alimentari"[n][w][e]
[s]"Lavati con cura le mani e[n]non dimenticare i gargarismi!"[n][w][e]

[msg CHK_LEAFLETS_1026]
[s]"Informazioni sul vaccino[n]antinfluenzale"[n][w][e]
[s]Ora che ci penso,[n]le persone con le mascherine[n]sanitarie sono in aumento...[n][w][e]

[msg CHK_LEAFLETS_1109]
[s]"~Curiosit稲 mediche~"[n][w][e]
[s]"I farmaci vengono prescritti in[n]base alle necessit稲 del singolo[n]paziente e non vanno ceduti".[n][w][e]

[msg CHK_LEAFLETS_1123]
[s]"~Bollettino sanitario: edizione di[n]novembre~ Attento alle[n]intossicazioni alimentari"[n][w][e]
[s]"In questo periodo dell'anno,[n]i norovirus sono aggressivi!"[n][w][e]

[msg CHK_LEAFLETS_1207]
[s]"~Bollettino sanitario: edizione di[n]dicembre~"[n][w][e]
[s]"I governi cambiano, ma i consigli[n]per la salute sono gli stessi.[n]Non trascurare la tua salute".[n][w][e]

[msg CHK_LEAFLETS_M01]
[s]"~Bollettino sanitario di gennaio~[n]Mangiare meglio nel nuovo anno"[n][w][e]
[s]"為 facile strafare nel nuovo anno.[n]Cerca di non mangiare n姻 bere[n]troppo".[n][w][e]

[msg CHK_LEAFLETS_M02]
[s]"~Bollettino sanitario: edizione di[n]febbraio~ Per un Setsubun[n]piacevole"[n][w][e]
[s]"Tieni d'occhio i tuoi figli se[n]stanno giocando con i fagioli.[n]C'因 il rischio che si soffochino."[n][w][e]

[msg CHK_LEAFLETS_M03]
[s]"~Bollettino sanitario: edizione di[n]marzo~ Convivere con gli sbalzi[n]di temperatura"[n][w][e]
[s]"La primavera 因 dietro l'angolo,[n]ma controlla sempre le temperature[n]quando scegli come vestirti."[n][w][e]

[msg CHK_LEAFLETS_1219]
[s]Nessuno[n][w][e]

[msg MSG_SOFA_DEFAULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]...Che stai facendo?[n][w][e]

[msg MSG_C13_BEGIN_TIME_08 [Takemi]]
[s][f 4 23 1 213 14 10 13 10][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 14118 213 0]...Uhm? Sei nervoso?[n]Non so, sembra che tu stia per saltare[n]nel vuoto, o qualcosa del genere.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 213 0]Di che genere di[n]farmaco hai bisogno?[n][w][e]

[msg MSG_C13_BEGIN_TIME_08_01 [Takemi]]
[s][f 4 23 1 213 14 10 13 10][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 213 0]Posso darti le[n]medicine, nient'altro.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 213 0]Qualunque cosa tu stia facendo,[n]cerca solo di non esagerare.[n][w][e]

[msg MSG_C13_BEGIN_TIME_0109_ [Takemi]]
[s][f 4 23 1 213 14 10 13 10][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 14030 213 0]Un po' in ritardo, ma[n]felice anno nuovo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 213 0]Sembra che, da quando 因 iniziato[n]l'anno nuovo, tutti abbiano[n]ricevuto buone notizie...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 14064 213 0]Beh, non importa.[n][w][e]

[msg MSG_C13_BEGIN_TIME_0109__2 [Takemi]]
[s][f 4 23 1 213 14 10 13 10][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 213 0]Allora, che tipo di[n]farmaco ti serve?[n][w][e]

[msg MSG_C13_BEGIN_TIME_0109__3 [Takemi]]
[s][f 4 23 1 213 14 10 13 10][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 213 0]Torna a trovarmi.[n][w][e]

