[msg DUMMY_MSG]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_LAST_GREETING_BOARD_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Siamo andati a scuola da qui per[n]un anno intero. Non 因 facile[n]dirsi addio...[n][w][e]

[msg MSG_LAST_GREETING_AD_POS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Se devi vivere a Yongen-Jaya,[n]il Leblanc 因 molto meglio di[n]qualsiasi appartamento chic.[n][w][e]

[msg MSG_LAST_GREETING_AD_POS_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Non 因 il momento di guardare[n]foto di costumi da bagno.[n]Andiamo a salutare.[n][w][e]

[msg MSG_LAST_GREETING_PAMPHL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]Non avrai pi迂 bisogno dell'opuscolo[n]sulle linee ferroviarie.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_BOARD_YONCHA_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Stazione di Yongen-Jaya, eh?[n]Dal nome sembra essere[n]una specie di ristorante.[n][w][e]

[msg MSG_BOARD_YONCHA]
[s]La stazione di Yongen-Jaya...[n][w][e]

[msg MSG_AD_POSTER_01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Un appartamento ai piani alti,[n]eh? Pensi che ci sia un eliporto[n]sul tetto?[n][w][e]

[msg MSG_AD_POSTER_01]
[s]Qui 因 visibile il prezzo[n]dell'appartamento. Vivere in centro[n]costa davvero molto...[n][w][e]

[msg MSG_AD_POSTER_02_MORU [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Modelle in costume da bagno, eh?[n]Per come la vedo io,[n]因 roba poco elegante.[n][w][e]

[msg MSG_AD_POSTER_02]
[s]為 il poster di una rivista[n]settimanale. Accompagnata[n]da pubblicit稲 esagerata...[n][w][e]

[msg MSG_PAMPHLET_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Informazioni sulle linee dei treni.[n]Quante stazioni...[n][w][e]

[msg MSG_PAMPHLET]
[s]Le informazioni sulla linea[n]sono sul volantino...[n][w][e]

[msg MND_E10410100_NG_TRAIN_0]
[s][vp 1 0 0 0 0 0]Ora non ho motivo di[n]prendere il treno. Dovrei[n]uscire dalla stazione.[n][w][e]

[msg MND_E10920200_NG_OUT_000]
[s][vp 1 0 0 0 0 0]為 il momento di prendere il treno[n]e andare a [clr 2]Shibuya[clr 27]...[n][w][e]

[msg MND_E12710200_NG_OUT_000]
[s][vp 1 0 0 0 0 0]Non posso fare tardi[n]due giorni di seguito. Dovrei[n]sbrigarmi ad andare a scuola.[n][w][e]

