[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_LAST_GREETING_Home_D [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]La scuola non 因 di l稲! Andiamo[n]a salutare tutti![n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Al momento non hai niente da fare[n]qui, giusto? Su, andiamo[n]da un'altra parte![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Che ti prende? Forza,[n]dobbiamo salutare gli altri![n][w][e]

[msg MSG_Deadend [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Ma la scuola non 因 l淫,[n]giusto dopo i tornelli?[n][w][e]

[msg MND_Deadend]
[s]La scuola 因 appena[n]oltre i tornelli...[n][w][e]

[msg MND_E10920100_NG_GINZASE]
[s][vp 1 0 0 0 0 0]Se salgo di nuovo[n]sul treno far韻 tardi...[n][w][e]
[s][vp 1 0 0 0 0 0]Dovrei sbrigarmi ad andare[n]a scuola...[n][w][e]

[msg MSG_E19310100_NG_OUT_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Dove vai?[n]Non prendiamo il treno?[n][w][e]

[msg MND_E10920100_Home_Deade]
[s][vp 1 0 0 0 0 0]La scuola 因 appena[n]oltre i tornelli...[n][w][e]

[msg MSG_COMMON_Home_Deadend_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]Ehi, dove stai andando?[n][w][e]

[msg MND_COMMON_Home_Deadend_]
[s][vp 1 0 0 0 0 0]Oggi dovrei tornare a casa[n]senza fare deviazioni...[n][w][e]

