[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MND_GoOut]
[s][vp 1 0 0 0 0 0]Dove dovrei andare...?[n][w][e]

[sel SEL_DEBUG_PLACE_000_00 top]
[s]Alla clinica.[e]
[s]Al negozio softair.[e]
[s]Lasciamo stare.[e]

[msg MND_RankUp_OK_Chishiki]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 0][clr 26][stLabel 0][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Credo che il mio [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]Non credo che la mia [stIcon 1][clr 26][stLabel 0][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 1][clr 26][stLabel 1][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Credo che il mio [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]Non credo che la mia [stIcon 2][clr 26][stLabel 2][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Se tutto va bene, credo che il mio[n][stIcon 1][clr 26][stLabel 1][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 2][clr 26][stLabel 2][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]Non credo che il mio [stIcon 3][clr 26][stLabel 3][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Credo di essere a un passo[n]da una svolta col mio [stIcon 3][clr 26][stLabel 3][clr 27]...[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Credo che il mio [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]Non credo che la mia [stIcon 4][clr 26][stLabel 4][clr 27][n]aumenter稲 presto...[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Se tutto va bene, credo che la mia[n][stIcon 4][clr 26][stLabel 4][clr 27] potrebbe migliorare...[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Credo di avere ancora molto[n]margine di miglioramento...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Sento che sta[n]arrivando qualcosa...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Credo di essere a un passo[n]da una svolta con la mia [stIcon 4][clr 26][stLabel 4][clr 27]...[n][w][e]

