[msg DUMMY_MSG]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[msg MSG_DAIFUGOU_TEST]
[s]Punto d'accesso Magnate[n][w][e]

[msg MSG_VIDEO_TEST]
[s]Punto d'accesso TV[n][w][e]

[msg MSG_SOUND_TEST]
[s]Punto d'accesso lettore musicale[n][w][e]

[msg MSG_IMAGE_TEST]
[s]Punto d'accesso Galleria[n][w][e]

[msg MSG_AWARD_TEST]
[s]Punto d'accesso Premi[n][w][e]

[msg MSG_PALACE_MAKER_TEST]
[s]Punto d'accesso Personalizza Covo[n][w][e]

[msg MSG_001]
[s]Vuoi uscire dal Covo dei Ladri?[n][w][e]

[sel SEL_002 top]
[s]S淫[e]
[s]No[e]

[msg Futaba_MSG [Wakaba Isshiki cognitiva]]
[s]Mostro della cognizione di Futaba[n]Sakura. Le sfingi sorvegliano re e[n]dei. Lei ha sempre protetto Futaba.[n][w][e]

[msg Yaruda_MSG [Yaldabaoth]]
[s]Dio del controllo nato dal subconscio umano.[n]Nella tradizione gnostica 因 un falso dio[n]malvagio, creatore del mondo fisico.[n][w][e]

[msg Maruki_MSG [Adam Kadmon]]
[s]La Persona evoluta di Maruki. Per[n]la Cabala 因 un umano primordiale in[n]forma divina. Un ideale a cui aspirare.[n][w][e]

[msg Arsene_MSG [Ars因ne]]
[s]La ribellione di Joker ha dato forma[n]al suo cuore. Maestro dei travestimenti,[n]osserva e replica i comportamenti.[n][w][e]

[msg Kid_MSG [Capitan Kidd]]
[s]La ribellione di Ryuji ha dato forma[n]al suo cuore. Ispirato a William Kidd.[n]Non ci sono notizie del suo passato.[n][w][e]

[msg Goemon_MSG [Goemon]]
[s]La ribellione di Yusuke ha dato forma[n]al suo cuore. 為 in molte storie dell'epoca[n]Edo, ma 因 vissuto in un'era diversa.[n][w][e]

[msg Necro_MSG [Necronomicon]]
[s]La ribellione di Futaba ha dato forma[n]al suo cuore. Il "libro dei morti" 因 citato[n]nelle opere di H.P. Lovecraft.[n][w][e]

[msg Robin_MSG [Robin Hood]]
[s]La ribellione di Akechi ha dato forma[n]al suo cuore. Nelle storie 因 un giustiziere,[n]ma potrebbe essere l'unione di pi迂 figure.[n][w][e]

[msg Roki_MSG [Loki]]
[s]La ribellione di Akechi ha dato forma[n]al suo cuore. Nella mitologia nordica 因 un dio[n]astuto che a volte ha un aspetto femminile.[n][w][e]

[msg Cend_MSG [Cenerentola]]
[s]La ribellione di Sumire ha dato forma[n]al suo cuore. Il nome Cenerentola[n]deriva dalla parola "cenere".[n][w][e]

[msg Rakugaki_MSG]
[s]Sembra il disegno di un bambino.[n][w][e]
[s]Qui ci sono sei stelle disegnate...[n][w][e]

