[msg ENTRANCE_DOOR_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Ma che cavolo...? Non... si[n]apre neanche dall'interno?[n][w][e]

[msg ENTRANCE_DOOR_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Stanno cercando di[n]sigillare tutti gli ingressi...[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come se potessero fermarci![n][w][e]

[msg FENCE_WEST_D_mes01]
[s]Le sbarre di metallo[n]ci bloccano la strada.[n][w][e]

[msg FENCE_WEST_U_mes01]
[s]Le sbarre di metallo[n]ci bloccano la strada.[n][w][e]

[msg FENCE_EAST_D_mes01]
[s]Le sbarre di metallo[n]ci bloccano la strada.[n][w][e]

[msg FENCE_EAST_U_mes01]
[s]Le sbarre di metallo[n]ci bloccano la strada.[n][w][e]

[msg FENCE_WEST_SWITCH_mes01]
[s]Abbassa le sbarre[n][w][e]

[msg FENCE_EAST_SWITCH_mes01]
[s]Abbassa le sbarre[n][w][e]

[msg D151_002_EV_LOCK_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh! Qualcosa si muove...[n]Sono ingranaggi?[n][w][e]

[msg D151_002_EV_LOCK_mes02 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1138 65535 0]Capisco. Scommetto che adesso[n]possiamo accedere a una nuova[n]area. Ben fatto, Joker![n][w][e]

[msg D01_03_e161_025_pre_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, guardate quel dipinto[n]al centro. Ma quello[n]non 因 Kamoshida?!?[n][w][e]

[msg D01_03_e161_025_pre_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ha appeso un suo ritratto[n]nel suo stesso castello...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'essere proprio ossessionato[n]da se stesso.[n][w][e]

[msg D01_03_e161_025_pre_mes0_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi viene la nausea solo a[n]guardarlo. Andiamo altrove.[n][w][e]

[msg L1_Tutorial_mes01 [【サードアイ】]]
[s]dummy fhit_151_002_00[n]dummy fhit_151_002_00[n][w][e]

[msg D01_02_escape_ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda, c'因 un soldato[n]proprio l淫...[n][w][e]

[msg D01_02_escape_ng_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻 non ci sono altri modi.[n]Dobbiamo fuggire da quella[n]porta prima che ci scoprano.[n][w][e]

