[msg D151_03_FLASHBACK [Ryuji]]
[s]Ma non siamo al piano[n]superiore rispetto a prima?[n][w][e]

[msg D01_04_e160_041_ng_03_me [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Ehi! Dobbiamo occuparci[n]subito di quelli l淫![n][w][e]

[msg D01_04_e160_041_ng_01_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Ehi, prima di andarcene prendiamo[n]quella cosa oltre le sbarre![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'esserci un modo per superarle.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non hai un'abilit稲 speciale da[n]Ladro Fantasma? Puoi[n]usare il Terzo occhio![n][w][e]

[msg D01_04_e160_041_ng_02_me [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1173 65535 0]Dopo tutti gli ostacoli che[n]hai superato, vorresti[n]andartene cos淫?[n][w][e]

[msg Dummy_01]
[s]※サードアイ活用ギミック調整中[n] 強制的に解除します。[n][w][e]

