[msg Dummy]
[s]......[n][w][e]

[msg D01_02_moru_navi_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]Usiamo la strada da cui[n]siamo fuggiti l'ultima volta![n][w][e]

[msg D01_02_moru_navi_mes02 [Morgana]]
[s][bup 0 3 0 65535 0]Ricordate? Siamo usciti dalla[n]stanza in cima alle scale![n][w][e]

[msg D01_02_moru_navi_mes03 [Morgana]]
[s][bup 0 3 0 65535 0]Va bene, ci siamo![n][w][e]
[s]...Wow![n][w][e]

[msg D01_02_moru_navi_mes04 [Morgana]]
[s][bup 0 3 0 65535 0]為 gi稲 l'ora della pattuglia?!?[n]Presto, prima che ci notino![n][w][e]

[msg D01_02_moru_navi_mes05 [Morgana]]
[s][bup 0 3 0 65535 0]Il passaggio sotterraneo 因[n]proprio qui sotto![n][w][e]

[msg D01_02_moru_navi_mes06 [Morgana]]
[s][bup 0 3 0 65535 0]Ci siamo quasi![n][w][e]

[msg Dummy_09 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 un vaso. Qui non sembra[n]esserci niente.[n][w][e]

[msg Dummy_10 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda, brucia! Mi sono beccato[n]della cera bollente in faccia![n][w][e]

[msg Dummy_11 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qua sopra non[n]ci sono altro che posate.[n][w][e]

[msg Dummy_12 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm... Niente, qui.[n][w][e]

[msg Dummy_13 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wow... Questo castello 因 il[n]regno del cattivo gusto...[n][w][e]

[msg D01_02__ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo, non abbiamo tempo per[n]cazzeggiare. Seguiamolo.[n][w][e]

[msg D01_02__ng_mes02 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cos淫 ci scopriranno, idiota![n]Entra, presto![n][w][e]

[msg D01_02_escape_ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda, c'因 un soldato[n]proprio l淫...[n][w][e]

[msg D01_02_escape_ng_mes02 [Morgana]]
[s][bup 0 3 0 65535 0]Per韻 non ci sono altri modi.[n]Dobbiamo fuggire da quella[n]porta prima che ci scoprano.[n][w][e]

