[msg D01_04_e165_041_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6041 65535 0]Oooh, c'因 mancato poco...![n]Un momento... Che roba 因...?[n][w][e]

[msg D01_04_e165_041_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un classico sistema di sicurezza.[n]Se cercassimo di superarlo[n]cos淫, rischierei la coda...[n][w][e]

[msg D01_04_e165_041_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, s淫, vale anche per Panther.[n]Dunque... che facciamo? Ora[n]come ora non si pu韻 passare.[n][w][e]

