[msg Dummy]
[s]......[n][w][e]

[msg D151_13_miniEV03_mes01 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6200 65535 0]Ma che cavolo...?[n]Disgustoso.[n][w][e]

[msg D151_13_miniEV03_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻... 因 un po' strano[n]che questo sia un vicolo cieco.[n][w][e]

[msg D151_013_EV_LOCK_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]Eh... Nessuna reazione.[n]L'altra si 因 mossa, ma questa no.[n][w][e]

[msg D151_013_EV_LOCK_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nessun rumore dagli ingranaggi...[n]Probabilmente perch姻 sono[n]immobili.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse c'因 un interruttore nascosto[n]da qualche parte che pu韻[n]attivare questo affare.[n][w][e]

[msg D151_13_miniEV05_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Non sento muoversi gli ingranaggi.[n]A quanto pare non sono azionati.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricordiamoci di questo posto.[n]Potrebbe condurci da qualche[n]parte.[n][w][e]

