[msg Dummy]
[s]......[n][w][e]

[msg D151_15_BAN_01_mes01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Secondo te c'因 un modo per aprirla?[n][w][e]

[msg D151_15_BAN_02_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'esserci un modo per aprire[n]queste sbarre.[n][w][e]

[msg D151_15_BAN_03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non possiamo proseguire finch姻[n]ci sono queste sbarre.[n][w][e]

