[msg Dummy]
[s]......[n][w][e]

[msg PRISON_NPC_TALK_01_mes01 [Pallavolista malconcio]]
[s]Non so perch姻 siate qui, ma...[n]lasciateci in pace...[n][w][e]

[msg PRISON_NPC_TALK_01_mes02 [Ryuji]]
[s][bup 0 2 2 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7185 65535 0]Di cosa stai parlando?!?[n]Ti va bene sul serio?[n][w][e]
[s][bup 0 2 3 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tsk... Sembra che provare a[n]parlarci sia inutile...[n][w][e]

[msg PRISON_NPC_TALK_02_mes01 [Pallavolista avvilito]]
[s]Non mi piace essere guardato[n]in quel modo... Non trascinarmi[n]nelle tue faccende...[n][w][e]

[msg PRISON_NPC_TALK_02_mes02 [Ryuji]]
[s][bup 0 2 2 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]Non ha importanza! Davvero[n]vi sta bene questo trattamento[n]di merda?!?[n][w][e]
[s][bup 0 2 3 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eeeh... A quanto pare, non ne[n]vuole sapere...[n][w][e]

