[msg D01_02_EXIT_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]Dovrebbero esserci altri soldati[n]di fuori. Diamo un'occhiata alla[n]situazione e usciamo.[n][w][e]

[msg D01_02_EXIT_AF_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Presto, andiamo dove[n]hanno portato gli schiavi.[n][w][e]

[msg D_BRIEFING_START_PC03_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D'accordo, iniziamo la riunione.[n][w][e]

[msg D_BRIEFING_NEXT_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi parlare di[n]qualcos'altro?[n][w][e]

[msg D_BRIEFING_END_PC03_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, ci aggiorniamo.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC [Ryuji]]
[s][vp 1 0 0 2138 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D'accordo! Pare che[n]questo luogo sia sicuro.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_2 [Morgana]]
[s][vp 1 0 0 3138 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uuuh, una nuova Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_3 [Ann]]
[s][vp 1 0 0 4138 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ottimo posto[n]per una Safe Room![n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_4 [Yusuke]]
[s][vp 1 0 0 5138 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmm... Ecco un luogo utile.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_5 [Makoto]]
[s][vp 1 0 0 6138 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa sembra una zona sicura.[n]Usiamola come Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_6 [Futaba]]
[s][vp 1 0 0 8138 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah! Una Safe Room![n]Si sta bene qui.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_7 [Haru]]
[s][vp 1 0 0 7138 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sapevo ci[n]fosse una Safe Room qui...[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_8 [Akechi]]
[s][vp 1 0 0 9138 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, una Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_01_PC_9 [[sumi 10 0]]]
[s][vp 1 0 0 10138 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vedo che c'因 una Safe Room, qui.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC [Ryuji]]
[s][vp 1 0 0 2139 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, questo posto fa al caso nostro![n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_2 [Morgana]]
[s][vp 1 0 0 3139 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh, forse qui possiamo[n]riposare un po'.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_3 [Ann]]
[s][vp 1 0 0 4139 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 una Safe Room![n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_4 [Yusuke]]
[s][vp 1 0 0 5139 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo trovato una[n]nuova Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_5 [Makoto]]
[s][vp 1 0 0 6139 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫! Qui possiamo riposare.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_6 [Futaba]]
[s][vp 1 0 0 8139 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 sicuro, qui.[n]Vuoi fare una pausa?[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_7 [Haru]]
[s][vp 1 0 0 7139 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo posto sembra sicuro.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_8 [Akechi]]
[s][vp 1 0 0 9139 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, questa 因 una Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_02_PC_9 [[sumi 10 0]]]
[s][vp 1 0 0 10139 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 una Safe Room. Ci fermiamo?[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC [Ryuji]]
[s][vp 1 0 0 2140 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bello! Possiamo usarla[n]come Safe Room![n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_2 [Morgana]]
[s][vp 1 0 0 3140 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo posto sembra l'ideale.[n]Facciamo una pausa, Joker.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_3 [Ann]]
[s][vp 1 0 0 4140 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Una Safe Room! Grazie al cielo...[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_4 [Yusuke]]
[s][vp 1 0 0 5140 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo spazio 因 piuttosto[n]interessante... Possiamo[n]usarlo come Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_5 [Makoto]]
[s][vp 1 0 0 6140 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Possiamo usarla come Safe Room.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_6 [Futaba]]
[s][vp 1 0 0 8140 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, che luogo rilassante.[n]Sediamoci un po'.[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_7 [Haru]]
[s][vp 1 0 0 7140 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo trovato una Safe Room![n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_8 [Akechi]]
[s][vp 1 0 0 9140 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 una Safe Room...[n]Riposiamo un po'?[n][w][e]

[msg SAFE_DISCOVERY_MES_03_PC_9 [[sumi 10 0]]]
[s][vp 1 0 0 10140 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'因 una Safe Room... diamo[n]un'occhiata?[n][w][e]

[msg SAFE_RETURN_TALK_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Figo, potremo tornare[n]direttamente qui, se vogliamo.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa sar稲 una buona base.[n]Potremo riprendere da qui[n]l'infiltrazione.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricordiamoci di questo posto, [n]cos淫 potremo tornare qui, se servir稲.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo sar稲 un ottimo luogo[n]da dove riprendere l'infiltrazione.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Saremo in grado di[n]riprendere l'infiltrazione[n]da qui in futuro.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Figo, possiamo usare[n]questo luogo come base per[n]riprendere l'esplorazione![n][w][e]

[msg SAFE_RETURN_TALK_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Credo che potremo riprendere[n]le operazioni da qui la prossima volta.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che saremo in grado di[n]riprendere le cose da qui.[n][w][e]

[msg SAFE_RETURN_TALK_01_PC10 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Possiamo trasformare questo[n]posto nella nostra base.[n][w][e]

[msg SAFE_IN_MES_01_PC02_mes [Ryuji]]
[s][vp 1 0 0 2141 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fiuuu, possiamo riposarci qui.[n][w][e]

[msg SAFE_IN_MES_01_PC03_mes [Morgana]]
[s][vp 1 0 0 3141 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, prendiamoci cinque minuti.[n][w][e]

[msg SAFE_IN_MES_01_PC04_mes [Ann]]
[s][vp 1 0 0 4141 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uff... Possiamo riposare...[n][w][e]

[msg SAFE_IN_MES_01_PC05_mes [Yusuke]]
[s][vp 1 0 0 5141 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm, riposiamoci qui.[n][w][e]

[msg SAFE_IN_MES_01_PC06_mes [Makoto]]
[s][vp 1 0 0 6141 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausa, OK?[n][w][e]

[msg SAFE_IN_MES_01_PC07_mes [Futaba]]
[s][vp 1 0 0 8141 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Posso riposare un attimo, vero?[n]Non vi preoccupate,[n]non mi addormento.[n][w][e]

[msg SAFE_IN_MES_01_PC08_mes [Haru]]
[s][vp 1 0 0 7141 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, facciamo una pausa.[n][w][e]

[msg SAFE_IN_MES_01_PC09_mes [Akechi]]
[s][vp 1 0 0 9141 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uff... qui possiamo riposare.[n][w][e]

[msg SAFE_IN_MES_01_PC10_mes [[sumi 10 0]]]
[s][vp 1 0 0 10141 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Possiamo riprendere fiato qui.[n][w][e]

[msg SAFE_IN_MES_02_PC02_mes [Ryuji]]
[s][vp 1 0 0 2142 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, facciamo una pausa.[n][w][e]

[msg SAFE_IN_MES_02_PC03_mes [Morgana]]
[s][vp 1 0 0 3142 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK! Facciamo una pausa![n][w][e]

[msg SAFE_IN_MES_02_PC04_mes [Ann]]
[s][vp 1 0 0 4142 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, facciamo una pausa.[n][w][e]

[msg SAFE_IN_MES_02_PC05_mes [Yusuke]]
[s][vp 1 0 0 5142 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fiuuu, possiamo prendere fiato.[n][w][e]

[msg SAFE_IN_MES_02_PC06_mes [Makoto]]
[s][vp 1 0 0 6142 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Possiamo fare una pausa[n]in questa zona sicura.[n][w][e]

[msg SAFE_IN_MES_02_PC07_mes [Futaba]]
[s][vp 1 0 0 8142 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un rifugio sicuro. Qui possiamo[n]metterci comodi e rilassarci.[n][w][e]

[msg SAFE_IN_MES_02_PC08_mes [Haru]]
[s][vp 1 0 0 7142 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non riposiamo un po' qui?[n][w][e]

[msg SAFE_IN_MES_02_PC09_mes [Akechi]]
[s][vp 1 0 0 9142 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausa?[n][w][e]

[msg SAFE_IN_MES_02_PC10_mes [[sumi 10 0]]]
[s][vp 1 0 0 10142 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausetta.[n][w][e]

[msg SAFE_IN_MES_03_PC02_mes [Ryuji]]
[s][vp 1 0 0 2143 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, abbiamo raggiunto[n]una Safe Room![n][w][e]

[msg SAFE_IN_MES_03_PC03_mes [Morgana]]
[s][vp 1 0 0 3143 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, riposiamo un po'.[n][w][e]

[msg SAFE_IN_MES_03_PC04_mes [Ann]]
[s][vp 1 0 0 4143 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Finalmente possiamo[n]riposare un po'...[n][w][e]

[msg SAFE_IN_MES_03_PC05_mes [Yusuke]]
[s][vp 1 0 0 5143 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che ne dici di fare una pausa?[n][w][e]

[msg SAFE_IN_MES_03_PC06_mes [Makoto]]
[s][vp 1 0 0 6143 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fiuuu, possiamo riposarci qui.[n][w][e]

[msg SAFE_IN_MES_03_PC07_mes [Futaba]]
[s][vp 1 0 0 8143 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo raggiunto una Safe Room![n]為 perfetta per[n]fare una pausa, no?[n][w][e]

[msg SAFE_IN_MES_03_PC08_mes [Haru]]
[s][vp 1 0 0 7143 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausa.[n][w][e]

[msg SAFE_IN_MES_03_PC09_mes [Akechi]]
[s][vp 1 0 0 9143 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, perch姻 non riposiamo un po'?[n][w][e]

[msg SAFE_IN_MES_03_PC10_mes [[sumi 10 0]]]
[s][vp 1 0 0 10143 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovremmo essere al sicuro, qui.[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0 [Ryuji]]
[s][vp 1 0 0 2042 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ottimo. Ne abbiamo fatta di strada![n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_2 [Morgana]]
[s][vp 1 0 0 3042 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E allora che facciamo...?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_3 [Ann]]
[s][vp 1 0 0 4042 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci qui. E ora che facciamo?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_4 [Yusuke]]
[s][vp 1 0 0 5042 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci siamo. Ora che si fa?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_5 [Makoto]]
[s][vp 1 0 0 6042 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci qui. Andiamo.[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_6 [Futaba]]
[s][vp 1 0 0 8042 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci qui. E ora... che si fa?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_7 [Haru]]
[s][vp 1 0 0 7042 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci qui. Ora cosa facciamo?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC0_8 [Akechi]]
[s][vp 1 0 0 9042 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati. Che[n]si fa adesso?[n][w][e]

[msg FASTTRAVEL_IN_MES_01_PC1 [[sumi 10 0]]]
[s][vp 1 0 0 10042 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, eccoci qua... E ora?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0 [Ryuji]]
[s][vp 1 0 0 2043 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eeed... eccoci qui![n]Ora cosa vuoi fare?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_2 [Morgana]]
[s][vp 1 0 0 3043 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci.[n]Andiamo avanti![n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_3 [Ann]]
[s][vp 1 0 0 4043 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene. Ora da che parte[n]vuoi andare?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_4 [Yusuke]]
[s][vp 1 0 0 5043 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati.[n]Bene, che facciamo ora?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_5 [Makoto]]
[s][vp 1 0 0 6043 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati qui interi.[n]Ora proseguiamo.[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_6 [Futaba]]
[s][vp 1 0 0 8043 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati? Ora che facciamo?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_7 [Haru]]
[s][vp 1 0 0 7043 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati.[n]Continuiamo la nostra esplorazione.[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC0_8 [Akechi]]
[s][vp 1 0 0 9043 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci qui.[n]E ora che si fa?[n][w][e]

[msg FASTTRAVEL_IN_MES_02_PC1 [[sumi 10 0]]]
[s][vp 1 0 0 10043 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccoci qui. Esploriamo![n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0 [Ryuji]]
[s][vp 1 0 0 2044 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, ora da che parte andiamo?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_2 [Morgana]]
[s][vp 1 0 0 3044 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati.[n]Proseguiamo, Joker.[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_3 [Ann]]
[s][vp 1 0 0 4044 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati.[n]Ora che si fa?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_4 [Yusuke]]
[s][vp 1 0 0 5044 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Giunti alla meta.[n]Proseguiamo con l'esplorazione.[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_5 [Makoto]]
[s][vp 1 0 0 6044 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati.[n]Ora che si fa, Joker?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_6 [Futaba]]
[s][vp 1 0 0 8044 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora facciamo sul serio, eh?[n]Dove siamo diretti?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_7 [Haru]]
[s][vp 1 0 0 7044 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, andiamo avanti.[n]Qual 因 il piano, Joker?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC0_8 [Akechi]]
[s][vp 1 0 0 9044 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo arrivati.[n]Dunque, procediamo?[n][w][e]

[msg FASTTRAVEL_IN_MES_03_PC1 [[sumi 10 0]]]
[s][vp 1 0 0 10044 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Via all'esplorazione. Quali sono[n]gli ordini?[n][w][e]

[msg SAFE_EXIT_LOW_01_PC02_me [Ryuji]]
[s][vp 1 0 0 2144 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, andiamo.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC03_me [Morgana]]
[s][vp 1 0 0 3144 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC04_me [Ann]]
[s][vp 1 0 0 4144 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Va bene, andiamo.[n]Abbiamo ancora da fare![n][w][e]

[msg SAFE_EXIT_LOW_01_PC05_me [Yusuke]]
[s][vp 1 0 0 5144 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, andiamo.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC06_me [Makoto]]
[s][vp 1 0 0 6144 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, riprendiamo l'esplorazione.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC07_me [Futaba]]
[s][vp 1 0 0 8144 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, 因 ora di andare![n][w][e]

[msg SAFE_EXIT_LOW_01_PC08_me [Haru]]
[s][vp 1 0 0 7144 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, andiamo.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC09_me [Akechi]]
[s][vp 8 2 1 8099 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forza, andiamo.[n][w][e]

[msg SAFE_EXIT_LOW_01_PC10_me [[sumi 10 0]]]
[s][vp 1 0 0 10144 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo![n][w][e]

[msg SAFE_EXIT_LOW_02_PC02_me [Ryuji]]
[s][vp 1 0 0 2145 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Va bene, diamoci dentro![n][w][e]

[msg SAFE_EXIT_LOW_02_PC03_me [Morgana]]
[s][vp 1 0 0 3145 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forza! Il Tesoro ci aspetta![n][w][e]

[msg SAFE_EXIT_LOW_02_PC04_me [Ann]]
[s][vp 1 0 0 4145 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, riprendiamo l'esplorazione.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC05_me [Yusuke]]
[s][vp 1 0 0 5145 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, rimettiamoci al lavoro.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC06_me [Makoto]]
[s][vp 1 0 0 6145 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricevuto. Torniamo al lavoro.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC07_me [Futaba]]
[s][vp 1 0 0 8145 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non ci hanno ancora scoperto.[n]Bene, spacchiamo tutto![n][w][e]

[msg SAFE_EXIT_LOW_02_PC08_me [Haru]]
[s][vp 1 0 0 7145 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D'accordo, allora. Andiamo?[n][w][e]

[msg SAFE_EXIT_LOW_02_PC09_me [Akechi]]
[s][vp 8 2 1 8096 65535 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non abbiamo idea di cosa ci[n]attenda. Muoviamoci con cautela.[n][w][e]

[msg SAFE_EXIT_LOW_02_PC10_me [[sumi 10 0]]]
[s][vp 1 0 0 10145 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Rimettiamoci in marcia![n][w][e]

[msg SAFE_EXIT_LOW_03_PC02_me [Ryuji]]
[s][vp 1 0 0 2146 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, 因 ora di andare.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC03_me [Morgana]]
[s][vp 1 0 0 3146 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pronti? Andiamo, Joker![n][w][e]

[msg SAFE_EXIT_LOW_03_PC04_me [Ann]]
[s][vp 1 0 0 4146 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, andiamo avanti![n][w][e]

[msg SAFE_EXIT_LOW_03_PC05_me [Yusuke]]
[s][vp 1 0 0 5146 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Riprendiamo l'esplorazione.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC06_me [Makoto]]
[s][vp 1 0 0 6146 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricevuto, andiamo.[n]Contiamo su di te, Joker![n][w][e]

[msg SAFE_EXIT_LOW_03_PC07_me [Futaba]]
[s][vp 1 0 0 8146 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un attimo! Sono quasi pronta![n][w][e]

[msg SAFE_EXIT_LOW_03_PC08_me [Haru]]
[s][vp 1 0 0 7146 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora torniamo al lavoro.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC09_me [Akechi]]
[s][vp 1 0 0 9146 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, rimettiamoci al lavoro.[n][w][e]

[msg SAFE_EXIT_LOW_03_PC10_me [[sumi 10 0]]]
[s][vp 1 0 0 10146 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ancora un po'...[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC02_m [Ryuji]]
[s][vp 1 0 0 2147 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene... La sorveglianza[n]因 stretta: facciamo attenzione.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC03_m [Morgana]]
[s][vp 1 0 0 3147 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricorda. Possiamo sempre fare[n]marcia indietro, se necessario.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC04_m [Ann]]
[s][vp 1 0 0 4147 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Avanti, continuiamo[n]ancora un po'.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC05_m [Yusuke]]
[s][vp 1 0 0 5147 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Attenzione ai movimenti delle[n]Ombre. Si mette male.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC06_m [Makoto]]
[s][vp 1 0 0 6147 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La situazione 因 pericolosa.[n]Concentriamoci.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC07_m [Futaba]]
[s][vp 1 0 0 8147 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm... Non mi piace.[n]Dovremo proprio darci da fare.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC08_m [Haru]]
[s][vp 1 0 0 7147 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sono all'erta.[n]Stiamo pronti.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC09_m [Akechi]]
[s][vp 1 0 0 9147 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo tornare[n]concentrati. Stiamo attenti.[n][w][e]

[msg SAFE_EXIT_HIGH_01_PC10_m [[sumi 10 0]]]
[s][vp 1 0 0 10147 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Occhio... il nemico 因 ancora in[n]allerta.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC02_m [Ryuji]]
[s][vp 1 0 0 2148 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vai cos淫! Il livello d'allerta 因[n]alto, prepariamoci a fare sul serio.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC03_m [Morgana]]
[s][vp 1 0 0 3148 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continuiamo a esplorare...[n]ma prestiamo la massima attenzione![n][w][e]

[msg SAFE_EXIT_HIGH_02_PC04_m [Ann]]
[s][vp 1 0 0 4148 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo attenzione. Dobbiamo[n]osservare i movimenti dei nemici.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC05_m [Yusuke]]
[s][vp 1 0 0 5148 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lavorare sotto pressione[n]因 divertente, ma stai pronto a[n]battere in ritirata, se necessario.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC06_m [Makoto]]
[s][vp 1 0 0 6148 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, ma 因 rischioso.[n]Facciamo attenzione.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC07_m [Futaba]]
[s][vp 1 0 0 8148 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La situazione 因 rischiosa.[n]Non abbassiamo la guardia.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC08_m [Haru]]
[s][vp 1 0 0 7148 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 piuttosto pericoloso.[n]Teniamo d'occhio il nemico.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC09_m [Akechi]]
[s][vp 1 0 0 9148 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I nemici sono all'erta.[n]Procediamo con cautela.[n][w][e]

[msg SAFE_EXIT_HIGH_02_PC10_m [[sumi 10 0]]]
[s][vp 1 0 0 10148 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Meglio essere pronti a tutto.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC02_m [Ryuji]]
[s][vp 1 0 0 2149 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, facciamo attenzione, Joker.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC03_m [Morgana]]
[s][vp 1 0 0 3149 0 0][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hmm... facciamo pi迂[n]attenzione del solito, Joker.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC04_m [Ann]]
[s][vp 1 0 0 4149 0 0][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo essere cauti,[n]il livello di allerta 因 alto.[n]Cerchiamo di non tirare la corda.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC05_m [Yusuke]]
[s][vp 1 0 0 5149 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sanno che siamo qui, Joker.[n]Non esageriamo.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC06_m [Makoto]]
[s][vp 1 0 0 6149 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il livello di allerta 因 alto.[n]Procediamo con cautela.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC07_m [Futaba]]
[s][vp 1 0 0 8149 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La sicurezza 因 stretta.[n]Fagli vedere chi sei, Joker![n][w][e]

[msg SAFE_EXIT_HIGH_03_PC08_m [Haru]]
[s][vp 1 0 0 7149 0 0][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo attenzione, OK?[n]Joker, non sfidare la sorte.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC09_m [Akechi]]
[s][vp 1 0 0 9149 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sanno della nostra presenza, Joker.[n]Non essere frettoloso.[n][w][e]

[msg SAFE_EXIT_HIGH_03_PC10_m [[sumi 10 0]]]
[s][vp 1 0 0 10149 0 0][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sar稲 pericoloso, ma speriamo[n]comunque di fare qualche progresso.[n][w][e]

[msg D_RECOVERY_EV_mes01]
[s]Hai [clr 6]ripristinato alcuni HP[clr 27] riposando.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uff... Riposiamo un po', amico.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3154 65535 0]Ora s淫 che mi sento di nuovo in forma![n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovremmo fare una pausa.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Credo che ci meritiamo[n]un po' di riposo.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Riposiamo un minuto.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, tempo di rilassarci un po'.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Riposiamo un po'.[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Possiamo riposare un po'?[n][w][e]

[msg SAFE_RECOVERY_MES_01_PC1 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausetta.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, sono a pezzi.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3160 65535 0]Ah, mi sento rinato![n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uff... Una pausa aiuterebbe.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausa[n]per riprendere le forze.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fiuuu... Devo calmarmi un attimo.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah... che sollievo![n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Credo che dovremmo riposare,[n]anche solo per qualche minuto.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo una pausa.[n][w][e]

[msg SAFE_RECOVERY_MES_02_PC1 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Riposiamo un minuto.[n][w][e]

[msg SAFE_ACTIVE_IN_FIRST_PC0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il Tesoro 因 proprio qui vicino.[n]Forza, Joker. Andiamo.[n][w][e]

[msg SAFE_ACTIVE_IN_SECOND_PC [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il Tesoro 因 un po' lontano da[n]qui... Sicuro che questo sia il[n]miglior punto di partenza, Joker?[n][w][e]

[msg SAFE_ACTIVE_IN_DISTANT_P [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh? Siamo lontani dal[n]Tesoro... Ricordi perch姻[n]siamo qui oggi, vero?[n][w][e]

[msg SAFE_ACTIVE_MES_PC03_mes [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Pare che questa stanza sia sicura.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma non possiamo fermarci troppo.[n]Andiamo al Tesoro una volta[n]riposati![n][w][e]

[msg SAFE_ACTIVE_IN_DISCOVERY [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1022 65535 0]Uh, non mi aspettavo di[n]trovare una nuova Safe Room oggi...[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma non possiamo fermarci troppo.[n]Andiamo al Tesoro una volta[n]riposati![n][w][e]

[msg SAFE_ACTIVE_EXIT_PC03_me [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Il nostro unico obiettivo[n]oggi 因 rubare il Tesoro! Avanti![n][w][e]

[msg SAFE_EXIT_D01_02_EX_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo. Ma ricorda di[n]fare attenzione.[n][w][e]

[sel PROPOSAL_TALK_SEL top]
[s]Accetta la proposta.[bitflag 0 0 106 1][e]
[s]Non accettare la proposta.[bitflag 0 0 106 1][e]

[sel PROPOSAL_REST_SEL top]
[s]Accetta la proposta.[bitflag 0 0 106 1][e]
[s]Non accettare la proposta.[bitflag 0 0 106 1][e]

[msg VELVET_SPECIAL_TIME_REMI]
[s]Mi sento un po' inquieto...[n]Dev'esserci un allarme attivo[n]nella Stanza di Velluto...[n][w][e]

