[msg Dummy]
[s]......[n][w][e]

[msg e210_152_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]Ma questo cammello... Siamo[n]tornati al primo![n][w][e]

[msg e210_152_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi non sono collegati come[n]sembra. Dobbiamo provare fino a [n]trovare la strada giusta.[n][w][e]

[msg e210_151_mes06 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Merda, da qui non[n]possiamo rientrare...[n][w][e]

[msg D153_007_miniEV_01_mes01 [Voce di Madarame]]
[s][vp 8 1 65535 30 0 0]Ahim因, questo mondo 因 un deserto[n]pullulante di profani che non[n]comprendono la vera bellezza...![n][w][e]
[s]Il lento declino delle mie capacit稲[n]因 inevitabile, circondato come sono[n]da tanta mediocrit稲...[n][w][e]

[msg D153_007_miniEV_01_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, la colpa del suo declino[n]sarebbe del mondo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, quel bastardo non ha mai[n]avuto alcun vero talento![n][w][e]

[msg D153_007_miniEV_02_mes01 [Voce di Madarame]]
[s][vp 8 1 65535 31 0 0]Gli dei, seppure dormienti,[n]vengono venerati costantemente.[n][w][e]
[s]La gente si raduna alle porte[n]dei loro santuari, offre loro doni[n]e torna a casa soddisfatta.[n][w][e]
[s]Anche l'arte 因 cos淫.[n]Alla fine, 因 pura questione[n]di immaginazione![n][w][e]

[msg D153_007_miniEV_02_mes02 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh?!? Anche se fosse vero,[n]non hai il diritto di[n]mentire alla gente![n][w][e]

[msg D153_007_miniEV_03_mes01 [Voce di Madarame]]
[s][vp 8 1 65535 44 0 0]Non 因 il duro lavoro a[n]ricoprire di verdi foglie[n]un arbusto.[n][w][e]
[s]Di questi tempi, troppi giovani[n]non comprendono il vero valore[n]della giovent迂. Sciocchi...[n][w][e]
[s]為 davvero sbagliato che un esperto[n]come me metta a frutto quella[n]giovent迂 prima che svanisca?[n][w][e]

[msg D153_007_miniEV_03_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cosa? Praticamente sta[n]dicendo che 因 geloso[n]dei giovani di talento...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardate me! Sono stato trasformato[n]in gatto, ma combatto ancora. L'et稲[n]non 因 una buona scusa.[n][w][e]

[msg D153_007_miniEV_04_mes01 [Voce di Madarame]]
[s][vp 8 1 65535 33 0 0]Le navi potrebbero solcare l'oceano[n]se l'equipaggio si preoccupasse[n]continuamente della fauna marina?[n][w][e]
[s]Arte, vita, acqua... Sono tutte[n]identiche. 為 colui che raggiunge[n]la cima a trionfare![n][w][e]

[msg D153_007_miniEV_04_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Usa un sacco di belle parole, ma[n]in pratica sta dicendo che le[n]persone sono degli scalini.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 proprio come quello che ha fatto[n]a quei ragazzi: li ha schiacciati[n]per la sua "arte"! Schifoso![n][w][e]

[msg D153_007_miniEV_05_mes01 [Voce di Madarame]]
[s][vp 8 1 65535 30 0 0]La bellezza 因 un miraggio...[n]Trasformarla in denaro 因 ci韻[n]che porta alla vera felicit稲.[n][w][e]
[s]La mia villa, il mio stile di vita[n]degno di pochi eletti...[n]Sono queste cose la vera "arte"![n][w][e]

[msg D153_007_miniEV_05_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi quella squallida baracca[n]fatiscente che usava come atelier[n]era una messinscena...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quanto sono stato sciocco a[n]farmi ingannare cos淫 a lungo...[n][w][e]

[msg D153_007_miniEV_05_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fox...[n][w][e]

[msg D153_007_miniEV_06_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Grande, questa dev'essere la fine![n][w][e]

[msg D153_007_miniEV_06_mes02 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deplorevole...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In tutti questi dipinti, non ha[n]menzionato una sola volta[n]l'amore per l'arte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questi non sono "dipinti".[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 solo insensata[n]autoaffermazione incorniciata![n][w][e]

[msg D153_007_miniEV_06_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sono curioso di vedere come lo[n]cambier稲 il risveglio del cuore.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Su, sbrighiamoci![n][w][e]

[msg D02_07_EX_SHUTTER_mes01 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]Cos淫 non possiamo proseguire...[n][w][e]

[msg D02_07_EX_SHUTTER_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per entrare dobbiamo fare qualcosa[n]per queste saracinesche.[n][w][e]

