[msg Dummy]
[s]......[n][w][e]

[msg mini_EV_e205_111_mes01 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Cacchio, di gi稲?[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, che si fa?[n][w][e]

[sel mini_EV_e205_111_selA top]
[s]Attacchiamolo.[bitflag 0 0 106 1][e]
[s]Torniamo pi迂 tardi.[bitflag 0 0 106 1][e]
[s]Aspettiamo che se ne vada.[bitflag 0 0 106 1][e]

[msg mini_EV_e205_111_selA_0_ [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Gi稲...[n][w][e]

[msg mini_EV_e205_111_selA_1_ [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7173 65535 0]Magari potessimo, ma il tempo[n]stringe e non lascer韻 che i[n]loro sforzi vadano sprecati.[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo buttarci...[n][w][e]

[msg mini_EV_e205_111_selA_2_ [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Come facciamo a sapere che se[n]ne andr稲? Abbiamo poco tempo, ricordi?[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Secondo me dobbiamo[n]buttarci e basta...[n][w][e]

[msg mini_EV_e205_111_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il vero problema 因 il fatto[n]che dobbiamo occuparcene[n]noi due da soli...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lascio decidere a te[n]il momento, coso.[n][w][e]

[msg mini_EV_e205_112_mes01 [Voce di addetto alla security]]
[s]Ehi! Chi va l稲?!?[n][w][e]

[msg mini_EV_e205_112_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Merda! Diamocela a gambe![n][w][e]

[msg mini_EV_e205_110_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7159 65535 0]Grande! 為 la stanza giusta![n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora... quale sar稲 quello[n]della sicurezza?[n][w][e]

[msg mini_EV_TEX_GET02_LOOK_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1057 65535 0]Un momento. Prima di andarcene[n]dovremmo prendere quel depliant![n][w][e]

[msg mini_EV_e210_143_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Questa sembra la sala di[n]controllo della sicurezza...[n][w][e]

[msg mini_EV_e210_143_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E vai! Spegniamo subito[n]quella roba![n][w][e]

[msg mini_EV_e210_144_mes01 [Guardia Ombra all'inseguimento]]
[s]Pare che gli intrusi abbiano[n]superato il giardino centrale...[n][w][e]

[msg mini_EV_e210_144_mes02 [Guardia Ombra al comando]]
[s]Lo so. Prima ho ricevuto ordine di[n]cambiare la password anche qui...[n][w][e]

[msg mini_EV_e210_144_mes03 [Guardia Ombra all'inseguimento]]
[s]Come? Dev'essere difficile, penso.[n][w][e]

[msg mini_EV_e210_144_mes04 [Guardia Ombra al comando]]
[s]Beh, non riuscivo a trovarne[n]una buona...[n][w][e]
[s]Per ora, ho scelto il numero[n]dei piedi di Lord Madarame.[n][w][e]

[msg mini_EV_e210_144_mes05 [Guardia Ombra all'inseguimento]]
[s]I piedi di Lord Madarame?[n]Ma di che stai parlando?[n][w][e]

[msg mini_EV_e210_144_mes06 [Guardia Ombra al comando]]
[s]Torniamo al lavoro. Gli intrusi[n]potrebbero essere nei paraggi.[n][w][e]

[msg mini_EV_e210_144_mes07 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]I piedi di Madarame? Che cavolo[n]dovrebbe significare?!?[n][w][e]

[msg mini_EV_e210_144_mes08 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La sua taglia di scarpe, forse?[n][w][e]

[msg mini_EV_e210_144_mes09 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo, Fox. Sai quanto porta[n]di scarpa quel bastardo?[n][w][e]

[msg mini_EV_e210_144_mes10 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4171 65535 0]Purtroppo non gliene ho mai[n]sentito parlare. Siamo sicuri che[n]sia quella la password?[n][w][e]

[msg mini_EV_e210_144_mes11 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I piedi di Madarame... Cosa[n]vorr稲 dire?[n][w][e]

[msg D153_006_miniEV_01_mes01 [Voce di Madarame]]
[s][vp 8 1 65535 35 0 0]Come osate violare il mio placido[n]giardino di bamb迂 con quei piedi[n]sudici! Non ve ne andrete vivi![n][w][e]

[msg D153_006_miniEV_01_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che cavolo era...?!?[n][w][e]

[msg D153_006_miniEV_01_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Probabile che siano i pensieri[n]di Madarame. Non 因 il caso di[n]farsi prendere dal panico.[n][w][e]

[msg D153_006_miniEV_01_mes04 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4074 65535 0]Madarame...[n][w][e]

[msg mini_EV_e210_142_mes01 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Oh... Siamo in un altro dipinto...[n][w][e]

[msg mini_EV_e210_142_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, quindi questo spazio non 因 un[n]solo dipinto, ma una moltitudine.[n][w][e]

[msg mini_EV_e210_142_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]Vuoi dire che sono tutti collegati?[n]E in che modo?[n][w][e]

[msg mini_EV_e210_142_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per scoprirlo dovremo continuare[n]a camminare...[n][w][e]

[msg mini_EV_e210_142_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Joker, con le tue capacit稲 non[n]riesci a vedere i collegamenti?[n][w][e]

[msg D153_006_miniEV_02_mes01 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4044 65535 0]Osa chiamarci ladri che[n]insudiciano il suo cuore...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Chi ha infangato la natura[n]stessa dell'arte non ha il diritto[n]di accusarci cos淫![n][w][e]

[msg D153_006_miniEV_02_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fatevi prendere dall'emozione pi迂[n]tardi. Dobbiamo muoverci![n][w][e]

