[msg D02_02_e200_148_NG_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Ehi, dobbiamo tornare da Mona![n][w][e]

[msg D02_02_e200_148_NG_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Yo! Diamoci una mossa e[n]controlliamo quel vaso![n][w][e]

[msg D02_02_e200_148_NG_mes03 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Quello lo lasciamo[n]stare, Joker? Sei sicuro?[n][w][e]

[msg mini_EV_e200_150_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Ma che cavolo...?!? Come facciamo a[n]superare questo enorme buco nel...[n][w][e]

[msg mini_EV_e200_150_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Calma. Guarda dove sta[n]camminando la guardia...[n][w][e]

[msg e200_140_mes08 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]Come luccica! Che vaso splendido.[n][w][e]

[msg e200_140_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Anche se non possiamo spegnere[n]i laser, sarebbe fantastico se non[n]ci fosse questo vetro...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci sar稲 da qualche parte[n]un interruttore per aprirlo?[n][w][e]

[msg e200_140_mes07 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Ehi, forse c'因 un interruttore,[n]anche da questa parte del vetro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Probabile che non sia nello[n]stesso punto dell'altro...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non vedete niente del genere?[n][w][e]

[msg mini_EV_e200_146_mes01 [Guardia Ombra all'inseguimento]]
[s]Ehi, hai saputo di[n]quegli intrusi?[n][w][e]

[msg mini_EV_e200_146_mes02 [Guardia Ombra al comando]]
[s]Intendi i ladri che[n]si sono intrufolati qui?[n][w][e]
[s]Mi 因 stato detto di cambiare la[n]password, tanto per stare sicuri.[n][w][e]

[msg mini_EV_e200_146_mes03 [Guardia Ombra all'inseguimento]]
[s]E...? Come l'hai cambiata?[n][w][e]

[msg mini_EV_e200_146_mes04 [Guardia Ombra al comando]]
[s]Hello.[n][w][e]

[msg mini_EV_e200_146_mes05 [Guardia Ombra all'inseguimento]]
[s]...Eh?[n][w][e]

[msg mini_EV_e200_146_mes06 [Guardia Ombra al comando]]
[s]Ho detto "hello"! 07734. Se leggi[n]i numeri al contrario, viene fuori[n]la parola "hello".[n][w][e]

[msg mini_EV_e200_146_mes07 [Guardia Ombra all'inseguimento]]
[s]...Non 因 un po' infantile?[n][w][e]

[msg mini_EV_e200_146_mes08 [Guardia Ombra al comando]]
[s]Dovrebbe andare bene, basta che[n]non la scopra nessuno. Tanto[n]non ci ascolta nessuno.[n][w][e]
[s]Ricorda: quando devi inserire[n]il codice, basta che ricordi[n]la parola "hello".[n][w][e]

[msg mini_EV_e200_146_mes09 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Sentito?[n][w][e]

[msg mini_EV_e200_146_mes10 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forte e chiaro. Forza, Joker,[n]andiamo a salutare quel terminale![n][w][e]

[msg D153_003_LOCK_EV02_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1161 65535 0]Questo laser non 因 infrarosso...[n]Sarebbe meglio non toccarlo.[n][w][e]

[msg D153_003_LOCK_EV02_mes02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Anche l'uscita 因 bloccata![n]Cosa facciamo?!?[n][w][e]

[msg D153_003_LOCK_EV02_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'esserci un modo per uscire.[n]Se solo riuscissimo[n]ad [clr 2]arrivare l淫[clr 27]...[n][w][e]

[msg D153_003_LOCK_EV02_mes04 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]Pare che da qui non si prosegua...[n][w][e]

[msg mini_EV_e200_140_LOCK_me]
[s]Prima devo raggiungere[n]Panther...[n][w][e]

[msg mini_EV_e200_140_LOCK_me_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6058 65535 0]Perch姻 non ci riuniamo con[n]Skull prima di farlo?[n][w][e]

[msg D02_mi_e207_130_ng_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Joker! Per ora pensa ad andartene[n]dal Palazzo![n][w][e]

[msg D02_mi_e207_130_ng_02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6158 65535 0]Aspetta! Di qui non si esce![n][w][e]

