[msg Dummy]
[s]......[n][w][e]

[msg D03_07_BUTA_01_KICKBACK_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]So che ne abbiamo gi稲 visti nel[n]Palazzo, ma diamine, 因 orribile.[n][w][e]

[msg D03_07_BUTA_01_KICKBACK__2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6025 65535 0]Cio因, 因 un salvadanaio d'oro a[n]porcellino. Mi sembra ovvio che[n]non pensi ad altro che ai soldi.  [n][w][e]

[msg D03_07_SHUTTER_STOPPER_0 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Mmm, non sembra volersi aprire.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se cerchiamo a fondo, dovremmo[n]trovare i comandi.[n][w][e]

[msg D03_07_SHUTTER_OPEN01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Forse abbiamo trovato i comandi che[n]cercavamo. Possiamo fare[n]qualcosa qui?[n][w][e]

[msg D03_07_SHUTTER_OPEN02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]Guardate! La saracinesca 因 sparita.[n]Possiamo proseguire![n][w][e]

[msg D03_07_SHUTTER_OPEN03 [Altoparlante]]
[s]A tutte le guardie![n]A tutte le guardie![n][w][e]

[msg D03_07_SHUTTER_OPEN04 [Altoparlante]]
[s]I ratti sono riusciti a spingersi[n]fino all'ultimo piano! Rafforzate la[n]sicurezza a tutti i livelli![n][w][e]
[s]Non devono procedere oltre![n]Proteggete il porcellino dorato[n]a qualunque costo![n][w][e]

[msg D03_07_SHUTTER_OPEN05 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Diamine, dev'essere proprio[n]agitato...[n][w][e]

[msg D03_07_SHUTTER_OPEN06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Teme pi迂 di ogni altra cosa che[n]mettiamo le mani su questo[n]"porcellino dorato".[n][w][e]

[msg D03_07_SHUTTER_OPEN07 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7161 65535 0]Beh, credo proprio si riferisca a[n]quello laggi迂. 為 alquanto[n]sospetto, secondo me...[n][w][e]

[msg mini_EV_e259_502_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Mmm? Qui c'因 una nota.[n]C'因 scritto "[clr 2]P=I[clr 27]".[n][w][e]

[msg mini_EV_e259_502_mes02 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E che cavolo vuol dire?[n][w][e]

[msg mini_EV_e259_502_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un momento, il bordo 因 strappato.[n]Che sia del diario di Kaneshiro?[n][w][e]

[msg mini_EV_e259_502_mes04 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Allora 因 la parte successiva[n]del codice di prima![n]Dovrebbe esserci utile![n][w][e]

[msg mini_EV_e259_502_mes07 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Mmm? Qui c'因 una nota.[n]Chiss稲 se 因 un indizio[n]per scoprire il codice PIN.[n][w][e]

[msg mini_EV_e259_502_mes08 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻 sono abbastanza sicuro[n]che l'abbiamo gi稲 scoperto.[n][w][e]

[msg mini_EV_e259_502_mes09 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1048 65535 0]Quindi l'abbiamo risolto senza[n]tutti gli indizi. Troppo bravi![n][w][e]

[msg mini_EV_e259_502_01_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Mmm? Qui c'因 una nota.[n]C'因 scritto "[clr 2]E=9 A=3[clr 27]".[n][w][e]

[msg mini_EV_e259_502_01_mes0_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra come quello che abbiamo[n]trovato prima. Anche questo ha[n]il bordo logoro.[n][w][e]

[msg mini_EV_e259_502_01_mes0_3 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Perfetto! Pi迂 indizi troviamo,[n]pi迂 ci avviciniamo a scoprire[n]il codice.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forza, andiamo di corsa alla[n]macchina per inserirlo![n][w][e]

[msg mini_EV_e259_502_01_mes0_4 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Questa 因 una specie di nota, vero?[n]Secondo voi 因 un indizio?[n][w][e]

[msg mini_EV_e259_502_01_mes0_5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Abbiamo gi稲 scoperto il PIN.[n]Questa l'abbiamo trovata[n]un po' tardi.[n][w][e]

