[msg Dummy]
[s]......[n][w][e]

[msg mini_EV_e259_504_01_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Mmm, qui c'因 una nota.[n]C'因 scritto [clr 2]O+H=10[clr 27].[n][w][e]

[msg mini_EV_e259_504_01_mes0_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anche i calcoli, adesso.[n]Santo cielo.[n][w][e]

[msg mini_EV_e259_504_01_mes0_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7132 65535 0]Eh? Un altro indizio?[n]C'因 scritto [clr 2]O+H=10[clr 27].[n][w][e]

[msg mini_EV_e259_504_01_mes0_4 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo gi稲 risolto il codice[n]a cui si riferisce.[n][w][e]

[msg mini_EV_e259_504_02_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]為 un'altra nota.[n]C'因 scritto "[clr 2]L=U+G, D=G[clr 27]".[n][w][e]

[msg mini_EV_e259_504_02_mes0_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ugh, sembra algebra![n]Inizio a sentirmi confusa...[n][w][e]

[msg mini_EV_e259_504_02_mes0_3 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Panther... 為 solo una[n]semplice addizione...[n][w][e]

[msg mini_EV_e259_504_02_mes0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Un'altra nota, eh?[n]C'因 scritto [clr 2]D=G L=U+G[clr 27].[n][w][e]

[msg mini_EV_e259_504_02_mes0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo gi稲 risolto il codice[n]a cui si riferisce.[n]L'abbiamo trovata troppo tardi.[n][w][e]

[msg D03_MONEY_DOOR_FIRST_01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6159 65535 0]Questa porta sembra diversa dalle[n]altre. 為 tutta luccicante e dorata.[n][w][e]

[msg D03_MONEY_DOOR_FIRST_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm. C'因 anche questo strano maiale.[n]Forse dovremmo prima andare in[n]ricognizione.[n][w][e]

[msg D03_MONEY_DOOR_NAVI_01 [Voce meccanica]]
[s]Buongiorno. Quest'ingresso[n]因 riservato ai dipendenti della[n]banca di Kaneshiro.[n][w][e]
[s]Per entrare, mostrare[n]la scheda d'accesso e[n]pagare [clr 2][var 0] yen[clr 27].[n][w][e]

[msg D03_MONEY_DOOR_FIRST_03 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Capisco che i dipendenti[n]debbano mostrare le loro[n]schede d'accesso, per韻...[n][w][e]

[msg D03_MONEY_DOOR_FIRST_04 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Devono pagare anche loro!?![n]E non sono spiccioli![n][w][e]

[msg D03_MONEY_DOOR_FIRST_05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4159 65535 0]Quindi per Kaneshiro persino[n]i suoi dipendenti sono[n]risorse da sfruttare.[n][w][e]

[msg D03_MONEY_DOOR_FIRST_06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Gli far稲 sicuramente guadagnare[n]qualcosa, ma dubito si tratti[n]di somme considerevoli.[n][w][e]

[msg D03_MONEY_DOOR_FRONT_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Che dovremmo fare? Non penso che[n]dovremmo pagare Kaneshiro...[n][w][e]

[sel D03_MONEY_DOOR_SEL top]
[s]Paga[e]
[s]Non pagare[e]

[msg D03_MONEY_DOOR_PAY_01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Ma dai, sul serio!?! Che spreco![n][w][e]

[msg D03_MONEY_DOOR_PAY_02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Davvero? Ma dove[n]hai trovato i soldi?[n][w][e]

[msg D03_MONEY_DOOR_DONT_PAY [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6188 65535 0]Gi稲, credo che ci convenga[n]cercare un'altra soluzione.[n][w][e]

[msg D03_MONEY_DOOR_CANT_PAY [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1169 65535 0]Considerato quanto costa, oserei[n]dire che non 因 nemmeno[n]da prendere in considerazione...[n][w][e]

[msg D03_MONEY_DOOR_BACK_FIRS [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6159 65535 0]Questa porta sembra diversa dalle[n]altre. 為 tutta luccicante e dorata.[n][w][e]

[msg D03_MONEY_DOOR_BACK_FIRS_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm. C'因 anche questo strano maiale.[n]Forse dovremmo prima andare in[n]ricognizione.[n][w][e]

[msg D03_MONEY_DOOR_NAVI_02 [Voce meccanica]]
[s]Buongiorno. Quest'ingresso[n]因 riservato ai dipendenti della[n]banca di Kaneshiro.[n][w][e]
[s]Con questo terminale, 因[n]possibile impostare il prezzo[n]d'ingresso.[n][w][e]

[msg D03_MONEY_DOOR_BACK_FIRS_3 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4047 65535 0]Perci韻 sottrae soldi perfino ai[n]suoi dipendenti...[n]e in modo molto consistente, vedo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Mmh. Pare che solo Kaneshiro[n]abbia l'autorizzazione per[n]cambiare i prezzi.[n][w][e]

[msg D03_MONEY_DOOR_BACK_01_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Forse non dovremo pagare se[n]lo ridurremo in mille pezzi, no?[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Spaccare roba ha sempre funzionato.[n]OK, facciamo un tentativo![n][w][e]

[msg D03_MONEY_DOOR_BACK_01_0_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]OK! Distruggiamo questo coso![n][w][e]

[msg D03_MONEY_DOOR_BACK_02_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1040 65535 0]Ha funzionato sul serio...[n][w][e]

[msg D03_MONEY_DOOR_BACK_02_0_2 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]...Non dovrei dirtelo io, ma[n]certe volte sei proprio[n]aggressivo, Joker.[n][w][e]

[msg D03_09_EV_1ST_HALF_CHECK [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4195 65535 0]La sicurezza sembra pi迂[n]rigida, qui...[n][w][e]

[msg D03_09_EV_1ST_HALF_CHECK_2 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nessun problema... ci basta[n]togliere l'energia alle sbarre[n]come fatto in precedenza.[n][w][e]

[msg D03_09_EV_1ST_HALF_CHECK_3 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1178 65535 0]Stando al loro aspetto,[n]direi che abbiamo bisogno di[n]trovare delle centraline...[n][w][e]

[msg D03_09_FIRST_HALF_CHECK_ [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6159 65535 0]Quella nel mezzo era[n]quella con l'appunto.[n][w][e]

[msg D03_09_FIRST_HALF_CHECK__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1155 65535 0]Qui la sicurezza potrebbe essere[n]pi迂 stretta, meglio essere cauti.[n]Occupiamoci di quelle centraline![n][w][e]

[msg D03_09_FIRST_HALF_CRUSH_ [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Ce ne sono altre? Sta[n]diventando una vera seccatura...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Potrebbero essercene alcune[n]sopra le nostre teste, qui[n]dentro?[n][w][e]

[msg D03_09_FIRST_HALF_CRUSH__2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4159 65535 0]Mmh. A quanto pare la nostra[n]caccia all'elettricit稲 non 因[n]ancora finita.[n][w][e]

[msg D03_09_FIRST_HALF_CRUSH__3 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]Sembra che abbiamo finalmente[n]disattivato le sbarre.[n][w][e]

[msg D03_09_FIRST_HALF_STOPPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Non abbiamo ancora trovato[n]alcun indizio su questo piano...[n]Proseguiamo?[n][w][e]

[sel D03_09_FIRST_HALF_STOPPE_2 top]
[s]Torniamo dopo.[e]
[s]Diamo un'altra occhiata.[e]

[msg D03_09_FIRST_HALF_STOPPE_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D'accordo. Possiamo ritornare[n]pi迂 tardi, all'occorrenza.[n][w][e]

[msg D03_09_FIRST_HALF_STOPPE_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qui la sicurezza potrebbe rivelarsi[n]stretta, ma dev'esserci qualcosa[n]che alimenta quelle sbarre.  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non dev'essere lontano da qui...[n]diamo un'occhiata in giro![n][w][e]

[msg D03_09_EV_2ND_HALF_CHECK [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7162 65535 0]Meeerda! 為 una follia![n][w][e]

[msg D03_09_EV_2ND_HALF_CHECK_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4159 65535 0]Casseforti ovunque... Kaneshiro[n]deve aver accumulato[n]una fortuna inestimabile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tuttavia, dando un'occhiata al[n]Palazzo, non sembra[n]averla reinvestita in niente...[n][w][e]

[msg D03_09_EV_2ND_HALF_CHECK_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Forse la sua unica ossessione[n]因 quella di accumulare...[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Comunque non 因 questo il momento[n]per pensarci. Proseguiamo.[n][w][e]

[msg D03_09_SECOND_HALF_CHECK [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Ehi, guardate![n][w][e]

[msg D03_09_SECOND_HALF_CHECK_2 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]Laggi迂! 為 uno di quegli indizi![n][w][e]

[msg D03_09_SECOND_HALF_CHECK_3 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]E quella non 因 l'elettricit稲 diretta[n]alle sbarre?[n][w][e]

[msg D03_09_SECOND_HALF_CHECK_4 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh. Hai ragione...[n]Da qui non si passa.[n][w][e]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*sigh* Immagino che dovremo[n]cercare un altro percorso.[n][w][e]

[msg D03_09_SECOND_HALF_CHECK_5 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]E finalmente siamo dentro![n][w][e]

[msg D03_09_SECOND_HALF_CHECK_6 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Scombiniamo tutto per assicurarci[n]un percorso pi迂 facile![n][w][e]

