[msg Dummy]
[s]......[n][w][e]

[msg GOTO_D03_EXIT_NG_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Aspetta! Prima proviamo a dare[n]un'altra occhiata a questo posto.[n][w][e]

[msg Check_ATM_mes01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Tsk, che schifo pazzesco.[n][w][e]

[msg Check_ATM_mes02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Qualcuno nel mondo reale[n]sta soffrendo cos淫.[n]Kaneshiro 因 davvero malvagio...[n][w][e]

[msg Check_ATM_mes03 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6183 65535 0]為 terribile. Ma cosa[n]gli 因 successo?[n][w][e]

[msg Check_ATM_mes04 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4028 65535 0]Dubito che in quello stato[n]riuscir稲 a dire qualcosa.[n][w][e]

[msg D154_15_CHECK_05_mes01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Tsk... Queste sono tutte[n]vittime di Kaneshiro?!?[n][w][e]

[msg D154_15_CHECK_05_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra proprio di s淫,[n]ma non c'因 nessuno con cui[n]parlare, n姻 tantomeno banche.[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4158 65535 0]Facciamo un altro giro per la[n]stazione. Forse abbiamo tralasciato[n]qualcosa di importante.[n][w][e]

[msg D154_15_CHECK_05_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4158 65535 0]Facciamo un altro giro per la[n]stazione. Forse abbiamo tralasciato[n]qualcosa di importante.[n][w][e]

