[msg Dummy]
[s]......[n][w][e]

[msg mini_EV_e259_503_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]為 una nota come quelle di[n]prima. C'因 scritto [clr 2]U=A[clr 27].[n][w][e]

[msg mini_EV_e259_503_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 come gli altri codici che abbiamo[n]trovato. Credo che sia un indizio![n][w][e]

[msg mini_EV_e259_503_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Su questa nota c'因 scritto [clr 2]U=A[clr 27].[n]Dovrebbe essere un[n]indizio per il PIN.[n][w][e]

[msg mini_EV_e259_503_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo gi稲 inserito[n]il numero a cui si riferisce.[n][w][e]

[msg mini_EV_e259_503_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Potrebbe tornarci utile in futuro,[n]non si sa mai.[n]Mettiamola da parte.[n][w][e]

[msg mini_EV_e259_503_01_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]E vai, un'altra nota. Se non[n]sbaglio, c'因 scritto [clr 2]G=P[clr 27].[n][w][e]

[msg mini_EV_e259_503_01_mes0_2 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, abbiamo un indizio in pi迂.[n]Continuiamo cos淫![n][w][e]

[msg mini_EV_e259_503_01_mes0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Su questa nota c'因 scritto [clr 2]G=P[clr 27].[n]Dovrebbe essere un indizio[n]per il PIN, giusto?[n][w][e]

[msg mini_EV_e259_503_01_mes0_4 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻 abbiamo gi稲 scoperto il[n]PIN a cui si riferisce.[n][w][e]

[msg mini_EV_e259_503_01_mes0_5 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Prendiamola lo stesso, dai.[n][w][e]

[msg D03_08_KINKO_KAITEN_DONE]
[s]Non risponde pi迂.[n][w][e]

[msg D03_MONEY_DOOR_FIRST_01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6159 65535 0]Questa porta sembra diversa dalle[n]altre. 為 tutta luccicante e dorata.[n][w][e]

[msg D03_MONEY_DOOR_FIRST_02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm. C'因 anche questo strano maiale.[n]Forse dovremmo prima andare in[n]ricognizione.[n][w][e]

[msg D03_MONEY_DOOR_NAVI_01 [Voce meccanica]]
[s]Buongiorno. Quest'ingresso[n]因 riservato ai dipendenti della[n]banca di Kaneshiro.[n][w][e]
[s]Per entrare, mostrare[n]la scheda d'accesso e[n]pagare [clr 2][var 0] yen[clr 27].[n][w][e]

[msg D03_MONEY_DOOR_FIRST_03 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Capisco che i dipendenti[n]debbano mostrare le loro[n]schede d'accesso, per韻...[n][w][e]

[msg D03_MONEY_DOOR_FIRST_04 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Devono pagare anche loro!?![n]E non sono spiccioli![n][w][e]

[msg D03_MONEY_DOOR_FIRST_05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4159 65535 0]Quindi per Kaneshiro persino[n]i suoi dipendenti sono[n]risorse da sfruttare.[n][w][e]

[msg D03_MONEY_DOOR_FIRST_06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Gli far稲 sicuramente guadagnare[n]qualcosa, ma dubito si tratti[n]di somme considerevoli.[n][w][e]

[msg D03_MONEY_DOOR_FRONT_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Che dovremmo fare? Non penso che[n]dovremmo pagare Kaneshiro...[n][w][e]

[sel D03_MONEY_DOOR_SEL top]
[s]Paga[e]
[s]Non pagare[e]

[msg D03_MONEY_DOOR_PAY_01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Ma dai, sul serio!?! Che spreco![n][w][e]

[msg D03_MONEY_DOOR_PAY_02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Davvero? Ma dove[n]hai trovato i soldi?[n][w][e]

[msg D03_MONEY_DOOR_DONT_PAY [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6188 65535 0]Gi稲, credo che ci convenga[n]cercare un'altra soluzione.[n][w][e]

[msg D03_MONEY_DOOR_CANT_PAY [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1169 65535 0]Considerato quanto costa, oserei[n]dire che non 因 nemmeno[n]da prendere in considerazione...[n][w][e]

[msg D03_MONEY_DOOR_BACK_FIRS [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6159 65535 0]Questa porta sembra diversa dalle[n]altre. 為 tutta luccicante e dorata.[n][w][e]

[msg D03_MONEY_DOOR_BACK_FIRS_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm. C'因 anche questo strano maiale.[n]Forse dovremmo prima andare in[n]ricognizione.[n][w][e]

[msg D03_MONEY_DOOR_NAVI_02 [Voce meccanica]]
[s]Buongiorno. Quest'ingresso[n]因 riservato ai dipendenti della[n]banca di Kaneshiro.[n][w][e]
[s]Con questo terminale, 因[n]possibile impostare il prezzo[n]d'ingresso.[n][w][e]

[msg D03_MONEY_DOOR_BACK_FIRS_3 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4047 65535 0]Perci韻 sottrae soldi perfino ai[n]suoi dipendenti...[n]e in modo molto consistente, vedo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Mmh. Pare che solo Kaneshiro[n]abbia l'autorizzazione per[n]cambiare i prezzi.[n][w][e]

[msg D03_MONEY_DOOR_BACK_01_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Forse non dovremo pagare se[n]lo ridurremo in mille pezzi, no?[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Spaccare roba ha sempre funzionato.[n]OK, facciamo un tentativo![n][w][e]

[msg D03_MONEY_DOOR_BACK_01_0_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]OK! Distruggiamo questo coso![n][w][e]

[msg D03_MONEY_DOOR_BACK_02_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1040 65535 0]Ha funzionato sul serio...[n][w][e]

[msg D03_MONEY_DOOR_BACK_02_0_2 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]...Non dovrei dirtelo io, ma[n]certe volte sei proprio[n]aggressivo, Joker.[n][w][e]

