[msg Dummy]
[s]......[n][w][e]

[msg D154_005_mini_EV_01_mes0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Oooh, si 因 aperta![n][w][e]

[msg D154_005_mini_EV_01_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa 因 la seconda. Chiss稲[n]quante altre ce ne sono...[n][w][e]

[msg D154_005_mini_EV_01_mes0_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo scopriremo di sicuro strada[n]facendo. Andiamo alla prossima![n][w][e]

[msg D154_005_mini_EV_02_mes0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Guardate! Adesso 因 aperta[n]anche questa![n][w][e]

[msg D154_005_mini_EV_02_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo movimento...[n]Non c'因 alcun dubbio.[n][w][e]

[msg D154_005_mini_EV_02_mes0_3 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm? Notato qualcosa?[n][w][e]

[msg D154_005_mini_EV_02_mes0_4 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Tutto il piano 因 il[n]cilindro di una serratura.[n][w][e]

[msg D154_005_mini_EV_02_mes0_5 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I-in che senso?[n]Puoi spiegarti un po' meglio?[n][w][e]

[msg D154_005_mini_EV_02_mes0_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il cilindro 因 il meccanismo[n]che verifica la forma corretta[n]di una chiave.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se usi la chiave giusta,[n]i dischi si allineano[n]e la serratura si apre.[n][w][e]

[msg D154_005_mini_EV_02_mes0_7 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Ora che l'hai detto, ho notato che[n]i muri ruotano, ma il percorso no...[n][w][e]

[msg D154_005_mini_EV_02_mes0_8 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi, tutto il piano sarebbe[n]una gigantesca serratura?[n][w][e]

[msg D154_005_mini_EV_02_mes0_9 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esatto. I caveau pi迂 piccoli[n]non hanno importanza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pi迂 avanti dev'esserci un'area[n]chiusa dalla stanza stessa.[n][w][e]

[msg D154_005_mini_EV_02_mes1 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]E il Tesoro dev'essere l淫![n]Dai, proseguiamo![n][w][e]

[msg D154_005_mini_EV_03_mes0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Q-questo 因 un ascensore, vero?[n]Ecco il modo per scendere...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sei una specie di[n]profeta, Queen.[n][w][e]

[msg D154_005_mini_EV_03_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 merito pi迂 che altro di quegli[n]appunti. Senza di quelli,[n]non saremmo qui.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma soprattutto, avete sentito[n]cos'ha detto l'Ombra di Kaneshiro?[n][w][e]

[msg D154_005_mini_EV_03_mes0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6035 65535 0]S淫, ci stavo riflettendo![n]Non sembrava un po'[n]insicuro o qualcosa del genere?[n][w][e]

[msg D154_005_mini_EV_03_mes0_4 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esatto. Continuava a parlare di[n]quanto vuole essere ricco e potente.[n][w][e]

[msg D154_005_mini_EV_03_mes0_5 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E se 因 insicuro di certe cose,[n]crede di essere solo[n]un debole, eh?[n][w][e]

[msg D154_005_mini_EV_03_mes0_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse, pensando che sarebbe[n]diventato ricco e potente, si 因[n]convinto di esserlo.[n][w][e]

[msg D154_005_mini_EV_03_mes0_7 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4037 65535 0]Per韻, mi chiedo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, scopriremo la verit稲[n]dopo che avremo risvegliato il suo[n]cuore. Sbrighiamoci, Joker.[n][w][e]

[msg D154_005_mini_EV_04_mes0 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Tsk, un altro di questi[n]coglioni! Che ci fa qui?!?[n][w][e]

[msg D154_005_mini_EV_04_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardate! Alle sue spalle![n][w][e]

[msg D154_005_mini_EV_04_mes0_3 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un altro dispositivo. L'Ombra[n]lo star稲 proteggendo.[n][w][e]

[msg D154_005_mini_EV_04_mes0_4 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Allora per proseguire[n]dobbiamo eliminarla.[n]Sei pronto, Joker?[n][w][e]

[sel D154_005_mini_EV_04_selA top]
[s]Puoi scommetterci.[e]
[s]Aspetta.[e]

[msg D154_005_mini_EV_04_selA_2 [Ombra Agente della security]]
[s]Umpf, voi dovete essere i topi[n]di cui si parla.[n][w][e]
[s]Beh, Kaneshiro-sama mi ha ordinato[n]di non far passare nessuno[n]oltre questo punto.[n][w][e]
[s]Rassegnatevi a morire![n][w][e]

[msg D154_005_mini_EV_04_selA_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, preparati come si deve.[n][w][e]

[msg D154_005_mini_EV_04_mes0_5 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Sei pronto, Joker?[n][w][e]

[msg e259_601_mes13 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Se vogliamo proseguire, dobbiamo[n]inviare una lettera di sfida.[n][w][e]

[msg D154_005_mini_EV_06_mes0 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Ci sono dei nomi su[n]ciascuno di questi piccoli caveau.[n][w][e]

[msg D154_005_mini_EV_06_mes0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Scommetto che queste sono[n]le persone diventate[n]"clienti" di Kaneshiro.[n][w][e]

[msg D154_005_mini_EV_06_mes0_3 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non glielo perdoner韻 mai[n]a quel bastardo...[n][w][e]

[msg D154_005_mini_EV_06_mes0_4 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4156 65535 0]Non mi aspettavo che esistesse[n]un posto del genere sotto quella[n]banca volante...[n][w][e]

[msg D154_005_mini_EV_06_mes0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che tutto sia possibile[n]nei mondi cognitivi.[n][w][e]

[msg D154_005_mini_EV_06_mes0_6 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Qui ci sono tantissimi caveau[n]pi迂 piccoli. Vuol dire che...[n][w][e]

[msg D154_005_mini_EV_06_mes0_7 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 il numero delle persone[n]cadute vittima dei crimini di[n]Kaneshiro nel mondo reale.[n][w][e]

[msg D154_005_mini_EV_06_mes0_8 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi sono un simbolo dell'infamia[n]di Kaneshiro. Le sue azioni sono[n]imperdonabili.[n][w][e]

[msg D154_005_mini_EV_06_mes0_9 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4169 65535 0]Mmm, un gigantesco caveau[n]sotterraneo colmo di denaro e[n]tanti caveau pi迂 piccoli...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sembra diverso da[n]Madarame. Nella sua psiche si[n]annida qualcosa di terribile...[n][w][e]

[msg D154_005_mini_EV_06_mes1 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quel bastardo 因 solo un insetto.[n]E noi lo schiacceremo![n][w][e]

[msg D154_005_mini_EV_06_mes1_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sono d'accordo.[n][w][e]

[msg D154_005_mini_EV_06_mes1_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Finora non ho trovato un[n]caveau con il mio nome[n]qui dentro.[n][w][e]

[msg D154_005_mini_EV_06_mes1_4 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se lo trovi, sentiti libera[n]di distruggerlo.[n][w][e]

[msg D154_005_mini_EV_06_mes1_5 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, credo proprio che lo far韻.[n][w][e]

[msg D154_005_mini_EV_06_mes1_6 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]Il numero di questi caveau[n]因 incredibile...[n][w][e]

[msg D154_005_mini_EV_06_mes1_7 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 probabile che per Kaneshiro[n]sia motivo di grande orgoglio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma presto sar稲 tutto finito.[n][w][e]

[msg D154_005_mini_EV_06_mes1_8 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]La vista di tutto questo denaro[n]mi far稲 diventare indifferente[n]alla ricchezza...[n][w][e]

[msg D154_005_mini_EV_06_mes1_9 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 proprio quello che 因 successo[n]a Kaneshiro. Basta guardare[n]questo posto per capirlo.[n][w][e]

[msg D154_005_mini_EV_06_mes1_10 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Solo perch姻 因 incredibilmente[n]avido. Sono impaziente di trovare[n]il suo Tesoro.[n][w][e]

[msg D154_005_mini_EV_06_mes2 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Ma quanti caveau ci sono?[n]Non voglio neanche provare[n]a contarli.[n][w][e]

[msg D154_005_mini_EV_06_mes2_2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6025 65535 0]Di tutti i posti in cui[n]siamo stati finora, questo[n]因 in assoluto il pi迂 assurdo.[n][w][e]

[msg D154_005_mini_EV_06_mes2_3 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1044 65535 0]Ciascuno di questi rappresenta[n]una vittima che ha tormentato.[n]Terrificante...[n][w][e]

[msg D154_005_mini_EV_06_mes2_4 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4169 65535 0]Non sar韻 una persona ricca...[n]ma spero di non diventare mai[n]come quest'uomo.[n][w][e]

[msg D154_005_mini_EV_06_mes2_5 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]為 un cuore appropriato[n]per un mondo cognitivo basato[n]cos淫 tanto sul denaro.[n][w][e]

[msg D154_005_mini_EV_06_mes2_6 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7191 65535 0]Con tutti questi soldi ci[n]si potrebbe comprare un paese.[n]Un po' lo invidio.[n][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No, un momento, non dovrei[n]pensare a cose del genere...[n][w][e]

[msg D154_005_mini_EV_06_mes2_7 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]L'ho pensato anche con[n]Madarame, ma... non c'因[n]proprio limite all'avidit稲 umana.[n][w][e]

[msg D154_005_mini_EV_06_mes2_8 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]Le proporzioni sono assurde. Forse[n]questa distorsione 因 pi迂 grande di[n]quelle di Kamoshida e Madarame...[n][w][e]

[msg D154_005_mini_EV_06_mes2_9 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4170 65535 0]Dobbiamo cancellare velocemente[n]un Palazzo cos淫 orrendo...[n][w][e]

[msg D154_005_mini_EV_06_mes2_10 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]Scommetto che qui ci sono[n]anche studenti della Shujin.[n][w][e]

[msg D154_005_mini_EV_06_mes3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Sar稲 inutile chiederlo[n]in questo Palazzo, ma...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che vorr稲 farci Kaneshiro[n]con tutti questi soldi?[n][w][e]

[msg D154_005_mini_EV_06_mes3_2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Perch姻 si spinge a truffare e[n]tormentare la gente?[n]...solo per i soldi?[n][w][e]

[msg D154_005_mini_EV_06_mes3_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1164 65535 0]Questo 因 chiaramente il Palazzo[n]di un accumulatore di denaro, per韻[n]non so come sia diventato cos淫.[n][w][e]

[msg D154_005_mini_EV_06_mes3_4 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]為 naturale che la ricchezza attiri[n]le persone, ma questo 因...[n]oltraggioso.[n][w][e]

[msg D154_005_mini_EV_06_mes3_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Quando avremo distrutto il[n]Palazzo, tutta questa gente sar稲 [n]di nuovo al sicuro, vero?[n][w][e]

[msg D154_005_mini_EV_06_mes3_6 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]I Ladri Fantasma non si farebbero[n]problemi a rubare... ma nessuno[n]vorrebbe questo denaro sporco.[n][w][e]

[msg D154_005_mini_EV_06_mes3_7 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4028 65535 0]Un ladro gentiluomo d'epoca[n]avrebbe rubato questo denaro[n]per spargerlo sulla citt稲...[n][w][e]

