[msg Dummy]
[s]......[n][w][e]

[msg D03_02_mini_EV_01_DOOR_m [Makoto]]
[s][bup 0 6 4 1 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2027 65535 0]Ehi, dove vai?!?[n]Dobbiamo andare da Kaneshiro![n][w][e]

[msg e255_301_mes13 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Forza, raggiungiamo la reception[n]prima di metterci a esplorare.[n][w][e]

[msg D02_e259_111_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Cos淫 non riusciremo a passare.[n]Dobbiamo trovare un altro[n]modo di entrare.[n][w][e]

[msg D02_e259_111_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Non funzioner稲 mai...[n][w][e]

[msg mini_EV_DOOR_LOCK02_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Sar稲 il caso di usare la scheda[n]d'accesso di prima?[n][w][e]

[msg mini_EV_DOOR_LOCK02_mes0_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Benissimo![n][w][e]

[msg D154_002_mini_EV_01_02_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Un momento! Non possiamo usare[n]la scheda d'accesso[n]per aprire la porta?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Su, proviamo![n][w][e]

[msg e259_141_mes05 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm, se viene controllato[n]da remoto, non potremo[n]usarlo...[n][w][e]

[msg D154_002_mini_EV_02_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2192 65535 0]Quello 因... un ascensore?[n][w][e]

[msg D154_002_mini_EV_02_mes0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, dev'essere quello che[n]controllano da remoto.[n]Allora ci siamo proprio sopra...[n][w][e]

[msg D154_002_mini_EV_02_mes0_3 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa cos'因, la sala di controllo?[n]Perch姻 siamo venuti qui?[n][w][e]

[sel D154_002_mini_EV_02_selA top]
[s]Saliremo sull'ascensore.[e]
[s]Scenderemo al sotterraneo.[e]

[msg D154_002_mini_EV_02_mes0_4 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]Perspicace come sempre, Joker.[n]Dovremmo poter salire[n]sopra l'ascensore.[n][w][e]

[msg D154_002_mini_EV_02_mes0_5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Capisco. Saliremo sopra l'ascensore[n]e aspetteremo che si muova.[n][w][e]

[msg D154_002_mini_EV_02_mes0_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che il piano[n]ci permetter稲 di scendere.[n][w][e]

[msg D154_002_mini_EV_02_mes0_7 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Va bene, andiamo![n][w][e]

[msg D03_02_mini_EV_01_mes01 [Guardia della security]]
[s]La reception 因 oltre questa porta.[n][w][e]

[msg D03_02_mini_EV_01_mes02 [Guardia della security]]
[s]Ehi, non di l稲! 為 oltre[n]questa porta. Forza.[n][w][e]

[msg D03_02_mini_EV_01_mes03 [Guardia della security]]
[s]La reception 因 a destra.[n]Non andate da altre parti.[n][w][e]

[msg D03_02_mini_EV_01_mes04 [Guardia della security]]
[s]Non di l稲! Forza,[n]a destra![n][w][e]

[msg D03_02_mini_EV_01_mes05 [Guardia della security]]
[s]Questa 因 la reception.[n]Sbrigatevi a entrare.[n][w][e]

[msg D03_02_mini_EV_01_mes06 [Guardia della security]]
[s]Non da quella parte.[n]Tornate indietro![n][w][e]

[msg D03_02_mini_EV_01_mes07 [Guardia della security]]
[s]Ehi, non di l稲! 為 oltre[n]questa porta, sbrigatevi[n]a entrare![n][w][e]

[msg D03_02_mini_EV_01_mes08 [Guardia della security]]
[s]La reception 因 a destra,[n]sul retro.[n][w][e]

[msg D03_02_mini_EV_01_mes09 [Guardia della security]]
[s]La reception 因 a destra.[n]Sbrigatevi.[n][w][e]

[msg D03_02_mini_EV_01_mes10 [Guardia della security]]
[s]Ecco la reception. Forza, entrate.[n][w][e]

[msg D03_02_mini_EV_03_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Ehi, adesso non c'因 tempo[n]per tornare indietro![n][w][e]

[msg D03_02_mini_EV_03_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1154 65535 0]All'uscita, presto![n][w][e]

[msg D03_02_mini_EV_02_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Corri, Joker! L'uscita 因 vicina![n][w][e]

