[msg Dummy]
[s]......[n][w][e]

[msg D154_003_mini_EV_03_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Quindi siamo nel sotterraneo?[n][w][e]

[msg D154_003_mini_EV_03_mes0_2 [Altoparlante]]
[s]A tutta la sorveglianza![n][w][e]

[msg D154_003_mini_EV_03_mes0_3 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 Kaneshiro?!?[n][w][e]

[msg D154_003_mini_EV_03_mes0_4 [Ombra di Kaneshiro]]
[s][bup 0 207 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che ci sia[n]un'infestazione di topi![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non dovete permettergli di scendere[n]per nessun motivo! Rinforzate al[n]massimo la sorveglianza, capito?[n][w][e]

[msg D154_003_mini_EV_03_mes0_5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]Adesso la posizione del[n]Tesoro 因 ovvia.[n][w][e]

[msg D154_003_mini_EV_03_mes0_6 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻, la mappa di prima[n]non mostra tutto. Forse da qualche[n]parte ce n'因 un'altra.[n][w][e]

[msg D154_003_mini_EV_03_mes0_7 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Comunque, scendere potrebbe essere[n]la cosa migliore. Cerchiamo una[n]mappa mentre esploriamo![n][w][e]

[msg e259_152_mes01]
[s]Cos'因?[n][w][e]

[msg e259_152_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2192 65535 0]Che c'因, Joker?[n][w][e]

[msg e259_152_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quello cos'因, un dispositivo?[n]Andiamo a vedere.[n][w][e]

[msg e259_152_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Diamo un'occhiata a quel dispositivo, OK?[n][w][e]

[msg e259_152_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Sembra un alimentatore,[n]ma di cosa?[n][w][e]

[msg e259_152_mes06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sopra c'因 scritto "telecamera".[n][w][e]

[msg e259_152_mes07 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'essere per le telecamere[n]di sorveglianza![n]Distruggiamolo, Joker![n][w][e]

[msg e259_152_mes08 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1072 65535 0]Bel calcio![n][w][e]

[msg e259_152_mes09 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ho capito! Se spacchiamo questi[n]affari, disattiviamo le telecamere![n][w][e]

[msg e259_210_mes01 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]E-ehi, potrebbero scoprirci![n]Andiamocene, presto![n][w][e]

[msg D154_003_CAMERA_TRAP_02_ [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]OK, dovremmo aver[n]spento qualche telecamera![n][w][e]

[msg D154_003_CAMERA_TRAP_02__2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2035 65535 0]Cos淫 dovremmo aver[n]disattivato alcune telecamere.[n][w][e]

[msg D154_003_CAMERA_TRAP_02__3 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]Abbiamo spento un bel po' di[n]telecamere. Pensate che ora[n]potremo raggiungere quella stanza?[n][w][e]

[msg D154_003_CAMERA_TRAP_02__4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]Abbiamo disattivato alcune[n]telecamere di fronte alla[n]guardiola... Ma non tutte, parrebbe.[n][w][e]

[msg D154_003_CAMERA_TRAP_02__5 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Le restanti saranno collegate[n]a un'altra fonte di energia...[n]Dobbiamo cercare altrove.[n][w][e]

[msg D154_003_CAMERA_TRAP_02__6 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]A quanto pare, abbiamo disattivato[n]tutte le telecamere di fronte[n]alla guardiola![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo, Joker![n][w][e]

[msg D154_003_ENTRY_HOLE_MES_ [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Ehi, e questo cos'因?[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Una stanza eccessivamente[n]grande...[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1021 65535 0]Secondo la mappa, da qui[n]dovremmo riuscire a scendere.[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__4 [Ombra prudente]]
[s]Ehi, hai sentito? Sembra che[n]gli intrusi stiano seminando[n]il caos da queste parti.[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__5 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Eh? Fate silenzio! Sento[n]qualcuno che parla![n][w][e]

[msg D154_003_ENTRY_HOLE_MES__6 [Ombra prudente]]
[s]Perci韻, questo piano 因... e[n]Kaneshiro-sama ci ha ordinato di...[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__7 [Ombra aggressiva]]
[s]S淫, ma... Cio因, con queste due[n]chiavi... accadere?[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__8 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Mmh? Chiavi? Di che diavolo[n]parlano quelle Ombre?[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__9 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sono riuscita a capire tutto.[n]Se solo potessimo avvicinarci.[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__10 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4046 65535 0]Uff, altre telecamere[n]di sorveglianza[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__11 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci sono delle Ombre l淫 dentro.[n]為 troppo pericoloso avvicinarsi[n]in questo momento...[n][w][e]

[msg D154_003_ENTRY_HOLE_MES__12 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Vorrei sentire cosa stanno dicendo,[n]ma per il momento non[n]possiamo fare niente.[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per ora pensiamo a trovare[n]un modo per scendere.[n][w][e]

