[msg Dummy]
[s]......[n][w][e]

[msg D154_011_mini_EV_02_mes0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]Mmm?!? Aspetta, Joker! Nasconditi![n][w][e]

[msg D154_011_mini_EV_02_mes0_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Altre telecamere?[n][w][e]

[msg D154_011_mini_EV_02_mes0_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1037 65535 0]No, queste sembrano diverse[n]da quelle di prima.[n]Si accendono a intermittenza.[n][w][e]

[msg D154_011_mini_EV_02_mes0_4 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sar稲 un sistema di sorveglianza[n]che passa tra pi迂 telecamere[n]per una maggiore efficienza.[n][w][e]

[msg D154_011_mini_EV_02_mes0_5 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7150 65535 0]Quindi dobbiamo passare quando[n]non sta registrando, no?[n][w][e]

[msg D154_011_mini_EV_02_mes0_6 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Potrebbe funzionare, ma dobbiamo[n]anche stare attenti alle guardie.[n]Avanziamo con prudenza![n][w][e]

