[msg Dummy]
[s]......[n][w][e]

[sel YESNO_SEL top]
[s]S淫[e]
[s]No[e]

[sel GIMMIC_SEL top]
[s]Premilo[e]
[s]Non premerlo[e]

[msg D04_155_003_EV01_mes01 [Makoto]]
[s]Fiuuu... A parte quella grande[n]scala, le aree sono[n]molto complicate.[n][w][e]
[s]......![n][w][e]

[msg D04_155_003_GIM01_mes01 [Makoto]]
[s]Ogni volta che proviamo a[n]salire qui, un masso[n]rotola gi迂.[n][w][e]
[s]Cos淫 non riusciremo a procedere.[n]Per il momento, esploriamo[n]le aree nelle vicinanze.[n][w][e]

[msg D04_155_003_GIM01_CLEAR_ [Makoto]]
[s]Mmm, questo sembra un interruttore.[n]Che si fa, proviamo[n]a premerlo?[n][w][e]

[msg D04_155_003_GIM01_CLEAR__2 [Makoto]]
[s]Cos'因 stato? Sono rotolati gi迂[n]dei massi...[n][w][e]
[s]Dovremmo andare a vedere[n]se 因 cambiato qualcosa.[n][w][e]

[msg D04_155_003_GIM01_CLEAR__3 [Makoto]]
[s]Gi稲, potrebbe essere una[n]trappola. Per ora guardiamo[n]da un'altra parte.[n][w][e]

[msg D04_155_003_GIM01_CLEAR__4 [Morgana]]
[s]L'abbiamo gi稲 attivato.[n][w][e]

