[msg GOTO_D04_EXIT_NG_mes01]
[s]Non posso andarmene se non[n]completo il mio obiettivo.[n][w][e]

[msg GOTO_D04_EXIT_mes01 [Morgana]]
[s]Vuoi tornare[n]alla piramide?[n][w][e]

[sel YESNO_SEL top]
[s]Certo.[e]
[s]Non ancora.[e]

[msg D04_155_013_EV01_mes01]
[s]Dummy[n][w][e]

[msg D04_155_013_EV01_mes02]
[s]Dummy[n][w][e]

[msg D04_155_013_EV02_mes01]
[s]Dummy[n][w][e]
[s]Dummy[n][w][e]

[msg D04_155_013_EV02_mes02]
[s]Dummy[n][w][e]

[msg D04_155_013_CHS_ST_mes01]
[s]Dummy[n][w][e]

[msg D04_155_013_CHS_ST_mes02]
[s]Dummy[n][w][e]

[msg D04_155_013_EV_BTL_mes01]
[s]Dummy[n][w][e]
[s]Dummy[n][w][e]
[s]Dummy[n][w][e]

[msg D04_02_e296_501_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, che diavolo succede[n]nel suo cuore?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il bandito, quelle strane[n]voci che dicono "l'hai uccisa"[n]e chiss稲 che altro...[n][w][e]

[msg D04_02_e296_501_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Futaba 因 la regina di[n]questo Palazzo, ma non[n]riesce a controllarlo?[n][w][e]

[msg D04_02_e296_501_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se dovessi dare una spiegazione,[n]sta perdendo il controllo a causa[n]dei ricordi soppressi.[n][w][e]

[msg D04_02_e296_501_mes04 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Comunque, dovremmo tornare indietro[n]e aprire la porta di fuoco.[n][w][e]

[msg MSG_e296_521_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7043 65535 0]Ehi, ho detto di aspettare! Noi...[n][w][e]

[msg MSG_e296_521_001 [???]]
[s]Sei troppo lento, idiota. Cos淫[n]non mi prenderai mai.[n][w][e]

[msg MSG_e296_521_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 scappato di nuovo![n]Prendetelo, presto![n][w][e]

[msg MSG_e296_522_000 [???]]
[s]Ahahah, siete gi稲 stanchi? Che[n]branco di falliti. Per razziare le[n]tombe ci vuole fiato, sapete?[n][w][e]

[msg MSG_e296_522_001 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6115 65535 0]Urgh, ci 因 sfuggito di nuovo![n]Quanto mi fa incazzare![n][w][e]

[msg MSG_e296_522_002 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se lo seguiamo e basta,[n]non lo prenderemo mai. Dobbiamo[n]intrappolarlo da qualche parte.[n][w][e]

[msg MSG_e296_522_003 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Intrappolarlo? E come?[n][w][e]

[msg MSG_e296_522_004 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2127 65535 0]Usiamo quella piazza di prima.[n]Possiamo sgusciare l淫 intorno[n]e intrappolarlo l淫![n][w][e]

[msg MSG_e296_523_000 [???]]
[s]Ve l'ho detto, 因 inutile![n]為 meglio se ci rinunciate![n][w][e]

[msg MSG_e296_523_001 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Grrr! Quel maledetto bastardo[n]mi fa proprio incazzare![n][w][e]

[msg MSG_e296_523_002 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardiamo bene dove si[n]dirige! Con un po' di abilit稲,[n]dovremmo poterlo intrappolare![n][w][e]

[msg MSG_e296_523_003 [???]]
[s]Siete testardi. Ancora[n]non vi basta? Non mi[n]prenderete mai.[n][w][e]

[msg MSG_e296_523_004 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 umiliante, ma dobbiamo[n]sopportare. L'unica possibilit稲[n]因 intrappolarlo, giusto?[n][w][e]

[msg MSG_e296_523_005 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]S淫. Dobbiamo aggirarlo dalla parte[n]opposta e intrappolarlo nella[n]piazza dove l'abbiamo incontrato.[n][w][e]

[msg MSG_e296_523_006 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6117 65535 0]Ecco fatto! Finalmente l'abbiamo[n]spinto nella piazza![n][w][e]

[msg MSG_e296_523_007 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfetto. Adesso non ha vie[n]di fuga. Andiamo, Joker![n][w][e]

