[msg Dummy]
[s]......[n][w][e]

[msg Dummy_Shortcut_mes]
[s]Dummy[n][w][e]

[sel GIMMIC_SEL top]
[s]Premilo[e]
[s]Lascia stare[e]

[msg D04_155_02_CHECK_PUZZLE_]
[s]Dummy[n][w][e]

[msg D04_155_02_CHECK_PUZZLE__2]
[s]Dummy[n][w][e]

[msg GIMMICK_DOOR_01_OPEN_mes]
[s]Dummy[n][w][e]

[msg GIMMICK_DOOR_01_OPEN_mes_2]
[s]Dummy[n][w][e]

[msg D04_155_002_CHECK_mes01]
[s]La porta 因 gi稲 aperta.[n][w][e]

