[msg DUMMY_mes01 [仮]]
[s]......[n][w][e]

[msg D05_12_Door_Unlock_01 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, pare che la porta sia aperta.[n]Controlliamo, Joker.[n][w][e]

[msg D05_12_Ex3Battle_Confirm [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Combattiamo?[n][w][e]

[sel D05_12_Ex3Battle_Confirm_2 top]
[s]Facciamolo.[e]
[s]Dobbiamo prepararci.[e]

[msg D05_12_Ex3Battle_Before_ [Guardiano]]
[s]E voi chi siete!?![n]Non avanzerete oltre![n][w][e]

[msg D05_12_Check_lock_door_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa porta sembra chiusa.[n]Dobbiamo trovare il modo di aprirla.[n][w][e]

