[msg Dummy]
[s]......[n][w][e]

[msg D05_02_e341_030_ng_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Dove vai? Proviamo a[n]recuperare qualche informazione[n]da quei robot.[n][w][e]

[msg D156_13_alert_mes01 [Servobot]]
[s]CHI SIETE? PERCH畏[n]NON STATE LAVORANDO?[n][w][e]

[msg D156_13_alert_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Merda, siamo stati scoperti![n][w][e]

[msg D156_13_alert_mes03 [Servobot]]
[s]QUESTI CERCANO DI BATTERE[n]LA FIACCA! SEGNALATELI![n][w][e]

[msg D156_13_alert_mes04 [Makoto]]
[s][bup 0 6 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]Ci siamo avvicinati troppo.[n]Ritiriamoci e riorganizziamoci![n][w][e]

[msg D156_13_miniEV04_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]In pratica, stiamo origliando.[n][w][e]

[msg D156_13_miniEV04_mes02 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 una mia abilit稲 divina.[n][w][e]

[msg D156_13_miniEV04_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6025 65535 0]Notevole. Adesso capisco come hai[n]fatto a spiare il Leblanc[n]cos淫 a lungo...[n][w][e]

[msg D156_13_miniEV04_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quello? 為 stata una sciocchezza![n]Un giorno vi far韻 vedere[n]qualcosa di serio. Muahahah...[n][w][e]

[msg D156_13_miniEV04_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C-comunque, 因 sicuramente una[n]mossa intelligente.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo ottenere dal gruppo[n]informazioni sul [clr 2]loro capo[clr 27].[n][w][e]

[msg D156_13_miniEV04_mes06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4192 65535 0]Pi迂 avanti sembrano essercene[n]altri. Recuperiamo informazioni[n]anche da loro![n][w][e]

[msg D156_13_intelli_point_le [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2157 65535 0]Abbiamo ascoltato parecchio.[n]Che ne pensi, Joker?[n][w][e]

[sel D156_13_intelli_point_le_2 top]
[s]Vorrei ascoltare altro.[e]
[s]Non mi serve sapere altro.[e]

[msg D156_13_intelli_point_le_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2021 65535 0]Scopriamo quello che ci serve[n]e andiamo via.[n][w][e]

[msg D156_13_intelli_point_le_4 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2118 65535 0]Allora andiamocene da qui,[n]prima che ci scoprano.[n][w][e]

[msg INTELLI_POINT_01_01]
[s]QUESTO LAVORO 為 INFINITO...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_02]
[s]LAVORO CONTINUAMENTE, MA C'為[n]SEMPRE ALTRO DA FARE...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_03]
[s]CHISS委 COME HA FATTO IL[n][clr 2]DIRETTORE CAPO[clr 27] A OTTENERE[n]LA SUA POSIZIONE...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_04]
[s]IL [clr 2]DIRETTORE CAPO[clr 27] FA LA BELLA VITA.[n]STA TUTTO IL GIORNO A[n]INGOZZARSI DI [clr 2]DOLCI[clr 27].[n][f 1 2 45][e]

[msg INTELLI_POINT_01_05]
[s]SVEGLIATI, LAVORA, TORNA A CASA,[n]DORMI... E RIPETI ALL'INFINITO[n]PER IL RESTO DELLA TUA VITA...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_06]
[s]IL MIO CAPO INCOMPETENTE[n]MI MANIPOLA CONTINUAMENTE.[n]CI RIMETTO SEMPRE...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_07]
[s]SE MI LAMENTASSI DAVANTI AL[n][clr 2]DIRETTORE CAPO[clr 27], DIREBBE:[n]"[clr 2]QUAND'ERO GIOVANE...[clr 27]"[n][f 1 2 45][e]

[msg INTELLI_POINT_01_08]
[s]IL DIRETTORE CAPO HA[n]L'[clr 2]ABITUDINE[clr 27] DI PARLARE DEI [clr 2]BEI[n]TEMPI ANDATI[clr 27]...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_09]
[s]SE CEDESSI ORA,[n]CAUSEREI SOLO GUAI[n]A TUTTI GLI ALTRI...[n][f 1 2 45][e]

[msg INTELLI_POINT_01_10]
[s]SONO FELICE DI POTER LAVORARE[n]PER QUEST'AZIENDA![n][f 1 2 45][e]

[msg INTELLI_POINT_01_11]
[s]SONO FELICE DI POTER LAVORARE[n]PER QUEST'AZIENDA![n][f 1 2 45][e]

[msg INTELLI_POINT_01_12]
[s]IL [clr 2]DIRETTORE CAPO[clr 27] AMA [clr 2]PARLARE DEL[n]SUO PASSATO[clr 27]. 為 COS維 PIENO DI[n]S畏 CHE MI SFINISCE.[n][f 1 2 45][e]

[msg INTELLI_POINT_01_13]
[s]IL DIRETTORE CAPO DICE[n]SEMPRE CHE QUEST'AZIENDA 為[n][clr 2]IL MEGLIO DEL MEGLIO[clr 2]![n][f 1 2 45][e]

[msg INTELLI_POINT_01_14]
[s]SONO GRATO DI POTER LAVORARE[n]PER QUEST'ORGANIZZAZIONE[n]D'畏LITE![n][f 1 2 45][e]

[msg D05_02_kakari_battle01 [???]]
[s]EHI! VOI LAGGI育! CHI VI HA[n]DETTO DI SMETTERE DI LAVORARE!?![n][w][e]
[s]SE NON FATE IL VOSTRO LAVORO,[n]SAR違 IO A ESSERE RIMPROVERATO[n]DAL DIRETTORE DI SEZIONE![n][w][e]
[s]SONO STANCO DI ESSERE[n]DEFINITO [clr 2]INUTILE[clr 27]![n][w][e]

[msg D05_02_kakari_battle02 [Dipendente umile]]
[s]ARGH! S維, SIGNOR CAPUFFICIO![n][w][e]

[msg D05_02_kakari_battle03 [Dipendente svogliato]]
[s]HA RAGIONE... IL DIRETTORE DI[n]SEZIONE MI HA CHIAMATO [clr 2]BUONO A[n]NULLA[clr 27] SVARIATE VOLTE...[n][w][e]

[msg D05_02_kakari_battle04 [Dipendente assonnato]]
[s]CAVOLI, VORREI CHE NON GRIDASSE[n]A NOI IN PARTICOLARE...[n][w][e]

[msg D05_02_kakari_battle05 [Dipendente svogliato]]
[s]COSA SI ASPETTA DOPO CHE MI HA[n]CHIAMATO [clr 2]BUONO A NULLA[clr 27]...[n][w][e]
[s]SE LAVORASSI ANCORA PI育 DURAMENTE,[n]MI GUASTEREI.[n][w][e]

[msg D05_02_kakari_battle06 [Robot capufficio]]
[s]UH? CHI SIETE?!?[n][w][e]
[s]TORNATE ALLE VOSTRE POSTAZIONI![n]SE NON FATE IL VOSTRO LAVORO[n]SAR違 IO A FINIRE NEI GUAI![n][w][e]

[msg D05_02_kakari_battle07 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Coso, noi non lavoriamo qui.[n][w][e]

[msg D05_02_kakari_battle08 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Skull, ti spiace concentrarti?[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Scusi, dovremmo parlare con il[n]direttore capo...[n][w][e]

[msg D05_02_kakari_battle09 [Robot capufficio]]
[s]COSA? CON IL DIRETTORE CAPO?[n][w][e]
[s]MA DELLE MEZZE TACCHE COME VOI NON[n]POTREBBERO AVERE DEGLI[n]IMPEGNI COS維 IMPORTANTI![n][w][e]
[s]ORA TORNERETE ALLE VOSTRE[n]POSTAZIONI. SE PROPRIO DEVO,[n]RICORRER違 ALLA FORZA![n][w][e]

[msg D05_02_kakari_battle10 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Beh, valeva la pena tentare.[n][w][e]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Preparatevi, gente![n][w][e]

[msg D156_13_miniEV05_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Uh. Potremmo capire se[n]sono i nostri bersagli[n][clr 2]ottenendo informazioni da loro[clr 27].[n][w][e]

[msg D156_13_miniEV05_mes01_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7079 65535 0]OK, siamo stati costretti a[n]combattere, ma credo che sia[n]un buon modo di procedere.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse possiamo capire se sono i[n]nostri bersagli [clr 2]ottenendo da loro[n]informazioni[clr 27] prima dello scontro.[n][w][e]

[msg D156_13_miniEV05_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esatto! [clr 2]Confrontando le[n]informazioni[clr 27], potremmo[n]evitare le battaglie inutili![n][w][e]

[msg D05_02_e341_031_clear_me [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3045 65535 0]S淫, si 因 aperta![n][w][e]

[msg D05_02_e341_031_clear_me_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Trovando ranghi sempre pi迂 alti,[n]prima o poi otterremo il[n]tesserino del direttore capo![n][w][e]

[msg D05_02_e341_031_clear_me_3 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2035 65535 0]Concordo. Procediamo un[n]passo alla volta.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E se ti senti stanco,[n]Joker, fermiamoci un po'[n]in una Safe Room.[n][w][e]

[msg D05_02_e341_034_end_mes0 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]為... Uh?[n][w][e]

[msg D05_02_e341_034_end_mes0_2 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 un tesserino identificativo![n]Ci permetter稲 di attraversare[n]le porte.[n][w][e]

[msg D05_02_e341_034_end_mes0_3 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]Quindi quello era... il direttore di[n]sezione? Ugh, perch姻 non 因 il[n]grande capo a venire da noi...?[n][w][e]

[msg D05_02_e341_034_end_mes0_4 [Altoparlanti]]
[s]AGLI OPERAI NON SERVE MANGIARE![n]AGLI OPERAI NON SERVE MANGIARE![n][w][e]
[s]CARISSIMI, 為 IL MOMENTO DEL CAMBIO[n]TURNO! CONTINUATE A LAVORARE,[n]ANCHE A COSTO DI DISTRUGGERVI![n][w][e]

[msg D05_02_e341_034_end_mes0_5 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Ma 因...[n][w][e]

[sel D05_02_e341_034_end_selA top]
[s]Un altro cambio turno.[e]
[s]Non ricordo.[e]

[msg D05_02_e341_034_end_selA_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg D05_02_e341_034_end_selA_3 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Avanti, datti una mossa![n][w][e]

[msg D05_02_e341_034_end_mes0_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Probabilmente stanno scambiando[n]i dipendenti come prima.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non controlliamo i[n]posti accessibili con il[n]tesserino da direttore di sezione?[n][w][e]

[msg D05_02_e341_033_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]Ci fermiamo anche qui? 為[n]un altro di quei cosi di rango?[n][w][e]

[msg D05_02_e341_033_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫! Per questo ci serve almeno un[n]tesserino da direttore di sezione.[n][w][e]

[msg D05_02_e341_033_mes03 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi dispiace per tutti i problemi[n]che vi sto causando...[n][w][e]

[msg D05_02_e341_033_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6024 65535 0]Smettila. L'unico che dovr稲[n]scusarsi 因 tuo[n]padre, OK?[n][w][e]

[msg D05_02_e341_033_mes05 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Panther ha ragione. Andiamo[n]in cerca del prossimo tesserino.[n][w][e]

[msg D05_02_e341_033_mes06 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo va dai direttori di[n]sezione in su. Ci serve[n]un altro tesserino identificativo.[n][w][e]

[msg D05_02_e341_033_clear_me [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3045 65535 0]Ottimo! Si 因 aperta anche questa![n][w][e]

[msg D05_02_e341_033_clear_me_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo quasi alla fine, giusto? In[n]genere il direttore capo 因 subito[n]sopra il direttore di sezione![n][w][e]

[msg D05_02_e341_033_clear_me_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, ricordate sempre di[n]valutare le vostre condizioni.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se siete stanchi, riposate[n]in una Safe Room.[n][w][e]

[msg D05_02_e341_034_ng_mes01 [???]]
[s][clr 2]EHI[clr 27]! COS'為 QUESTO TRAMBUSTO?[n]DOVE CREDETE[n]DI ESSERE?!?[n][w][e]

[sel D05_02_e341_034_ng_selA top]
[s]Chiedo scusa.[e]
[s]Inutile arrabbiarsi tanto.[e]
[s]Chiudi il becco.[e]

[msg D05_02_e341_034_ng_selA_ [???]]
[s]MI STATE DAVVERO CHIEDENDO[n]SCUSA? UGH, E AVETE DEGLI ABITI[n]COS維 STRANI...[n][w][e]
[s]DUNQUE, COSA CERCATE DA QUESTE[n]PARTI? QUESTO NON 為[n]UN PARCO GIOCHI PER BAMBINI![n][w][e]

[msg D05_02_e341_034_ng_selA__2 [???]]
[s]NON SIATE RIDICOLI! SE NON MI[n]ARRABBIASSI, CHI LO FAREBBE?!?[n][w][e]
[s]CORRERE IN GIRO DA QUESTE PARTI[n]為 INACCETTABILE! VI PUNIR違[n]QUI E SUBITO![n][w][e]

[msg D05_02_e341_034_ng_selA__3 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Sembra che dovremo combattere.[n]Forza, prendiamolo a calci![n][w][e]

[msg D05_02_e341_034_ng_selA__4 [???]]
[s]CHE AVETE DETTO?!?[n]SIETE DAVVERO MALEDUCATI![n][w][e]
[s]NESSUN DIPENDENTE DIREBBE MAI UNA[n]COSA SIMILE! VI CONSEGNER違[n]ALLA SECURITY![n][w][e]

[msg D05_02_e341_034_ng_selA__5 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Merda, se continua cos淫,[n]dovremo batterci! Diamoci dentro![n][w][e]

[sel D05_02_e341_034_ng_selB top]
[s]Il direttore capo.[e]
[s]Stiamo cercando Okumura.[e]
[s]Cerchiamo tesori.[e]

[msg D05_02_e341_034_ng_selB_ [???]]
[s]IL DIRETTORE CAPO, AVETE DETTO?[n]PERCH畏 DELLE PERSONE COME VOI[n]DOVREBBERO CERCARLO?[n][w][e]
[s]為 PI育 AVANTI. SPERO CHE ABBIATE[n]PRESO APPUNTAMENTO![n][w][e]

[msg D05_02_e341_034_ng_selB__2 [???]]
[s]COME OSATE PARLARE DEL NOSTRO[n]GLORIOSO PRESIDENTE CON[n]TANTA CONFIDENZA![n][w][e]
[s]PAGHERETE CON LA VITA, PER[n]QUESTO TRAGICO ERRORE![n][w][e]

[msg D05_02_e341_034_ng_selB__3 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Sembra che dovremo combattere.[n]Forza, prendiamolo a calci![n][w][e]

[msg D05_02_e341_034_ng_selB__4 [???]]
[s]UN MOMENTO, SIETE QUEI TIPI[n]NOTI COME LADRI FANTASMA?!?[n][w][e]
[s]NON AVETE ALCUNA VERGOGNA, SE[n]AMMETTETE APERTAMENTE QUEI CRIMINI![n][w][e]
[s]NON SIETE DEGNI DEL TEMPO[n]SPRECATO PER QUESTA CONVERSAZIONE![n]VI UCCIDER違![n][w][e]

[msg D05_02_e341_034_ng_selB__5 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Merda, se continua cos淫,[n]dovremo batterci! Diamoci dentro![n][w][e]

[msg D05_02_e341_034_ng_mes03 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]為 il momento di prendere una[n]decisione, Joker. Cosa vuoi fare?[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo affrontiamo per rubargli[n]il tesserino?[n][w][e]

[sel D05_02_e341_034_ng_selC top]
[s]Diamoci dentro.[bitflag 0 0 106 1][e]
[s]Meglio andar via.[bitflag 0 0 106 1][e]

[msg D05_02_e341_034_ng_selC_ [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Giusto, meglio evitare altre[n]discussioni. Facciamolo a pezzi![n][w][e]

[msg D05_02_e341_034_ng_selC__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Quindi preferisci non[n]combattere? OK, ritiriamoci![n][w][e]

[msg D05_02_e341_034_ng_selC__3 [???]]
[s]EHI, TORNATE QUI! LA FUGA[n]NON 為 ACCETTABILE![n][w][e]

[msg D05_02_true_kachou_battl [???]]
[s]CHE CI FATE QUI? TORNATE[n]ALLE VOSTRE POSTAZIONI.[n][w][e]
[s]I DIPENDENTI [clr 2]INUTILI[clr 27] SARANNO[n]SMALTITI COME ROTTAMI.[n][w][e]

[msg D05_02_true_kachou_battl_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Un momento. Noi siamo...[n][w][e]

[sel D05_02_true_kachou_battl_3 top]
[s]Reparto vendite.[e]
[s]Risorse umane.[e]
[s]Siamo i Ladri Fantasma.[e]

[msg D05_02_true_kachou_battl_4 [???]]
[s]DUNQUE? DICHIARATE LE VOSTRE[n]INTENZIONI IMMEDIATAMENTE.[n][w][e]
[s]SONO MOLTO OCCUPATO. NON HO[n]TEMPO DI PARLARE CON[n][clr 2]IMPIEGATI INUTILI[clr 27].[n][w][e]

[msg D05_02_true_kachou_battl_5 [???]]
[s]I LADRI FANTASMA![n][w][e]
[s]IN TAL CASO, POSSO CONSEGNARVI[n]TUTTI E INGRAZIARMI I PEZZI[n]GROSSI![n][w][e]

[msg D05_02_true_kachou_battl_6 [Haru]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3108 65535 0]A quanto pare, ormai possiamo[n]solo combattere. Forza![n][w][e]

[sel D05_02_true_kachou_battl_7 top]
[s]Devo vedere il direttore capo.[e]
[s]Tu sei il direttore di sezione?[e]

[msg D05_02_true_kachou_battl_8 [???]]
[s]IL DIRETTORE CAPO? SULL'AGENDA[n]NON C'ERA SCRITTO NIENTE.[n][w][e]
[s]MI STATE DICENDO CHE SIETE[n]VENUTI SENZA APPUNTAMENTO?[n]SIETE PROPRIO DEI MOCCIOSI [clr 2]INUTILI[clr 27].[n][w][e]

[msg D05_02_true_kachou_battl_9 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]Tsk, sei veloce a giudicare.[n]Che ne sai di quanto sono[n][clr 2]inutili[clr 27] gli altri?[n][w][e]

[msg D05_02_true_kachou_battl_10 [???]]
[s]MA SOPRATTUTTO, NON[n]RICONOSCO LE VOSTRE FACCE.[n][w][e]
[s]LAVORATE DAVVERO QUI?[n]DATEMI I VOSTRI NOMI E[n]I VOSTRI NUMERI IDENTIFICATIVI.[n][w][e]

[msg D05_02_true_kachou_battl_11 [???]]
[s]AVETE UN BEL CORAGGIO A[n]FARE RICHIESTE A UN SUPERIORE.[n][w][e]
[s]NON SAPETE NEANCHE PORTARE[n]RISPETTO. ECCO COSA INTENDO[n]PER [clr 2]INUTILI[clr 27]![n][w][e]

[msg D05_02_true_kachou_battl_12 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]Ma ascoltati: chiami tutti[n][clr 2]inutili[clr 27] e [clr 27]senza valore[clr 2]. Mai pensato[n]ai risvolti dei tuoi abusi verbali?[n][w][e]

[msg D05_02_true_kachou_battl_13 [???]]
[s]SE VOLETE LAMENTARVI, FATELO[n]DOPO AVER DIMOSTRATO[n]LA VOSTRA UTILIT委.[n][w][e]
[s]...MA SOPRATTUTTO, NON RICONOSCO[n]LE VOSTRE FACCE. SICURI DI LAVORARE[n]QUI? HO I MIEI DUBBI.[n][w][e]

[msg D05_02_true_kachou_battl_14 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]為 ora di decidere, Joker.[n]Che facciamo?[n][w][e]

[sel D05_02_true_kachou_battl_15 top]
[s]Affrontiamolo.[e]
[s]Meglio andare via.[e]

[msg D05_02_true_kachou_battl_16 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1175 65535 0]Giusto, meglio evitare altre[n]discussioni. Facciamolo a pezzi![n][w][e]

[msg D05_02_true_kachou_battl_17 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]Quindi preferisci non[n]combattere? OK, ritiriamoci![n][w][e]

[msg D05_02_e341_034_ng_end_m [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Fiuuu, con quello 因 fatta.[n][w][e]

[msg D05_02_e341_034_ng_end_m_2 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Purtroppo sembra che non[n]avesse nulla. Non era[n]cos淫 importante, in fin dei conti.[n][w][e]

[msg D05_02_e341_034_ng_end_m_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, beh... cerchiamo da[n]un'altra parte.[n][w][e]

[msg D05_02_e341_036_ng2_mes0 [???]]
[s]UHMMM, E VOI CHI SIETE?[n][w][e]

[sel D05_02_e341_036_ng2_selA top]
[s]I Ladri Fantasma.[e]
[s]Siamo di passaggio.[e]
[s]Volevamo parlare.[e]

[msg D05_02_e341_036_ng2_selA_2 [???]]
[s]I LADRI FANTASMA, UH?[n]NON MI INTERESSA. STATE[n]INTRALCIANDO IL MIO LAVORO.[n][w][e]

[msg D05_02_e341_036_ng2_selA_3 [???]]
[s]DAVVERO? IN TAL CASO,[n]SBRIGATEVI A TOGLIERVI DI TORNO.[n]STATE INTRALCIANDO IL MIO LAVORO.[n][w][e]

[msg D05_02_e341_036_ng2_selA_4 [???]]
[s]NON NE HO ALCUN BISOGNO.[n]ORA, SPARITE. STATE[n]INTRALCIANDO IL MIO LAVORO.[n][w][e]

[sel D05_02_e341_036_ng2_selB top]
[s]Ascoltaci, per favore.[e]
[s]Sei il direttore capo?[e]
[s]Sembri apatico.[e]

[msg D05_02_e341_036_ng2_selB_2 [???]]
[s]NON 為 NECESSARIO. NON[n]HO NULLA A CHE FARE CON VOI.[n][w][e]
[s]OLTRETUTTO, PERCH畏 NON[n]STATE LAVORANDO? STATE FORSE[n]BATTENDO LA FIACCA?[n][w][e]

[msg D05_02_e341_036_ng2_selB_3 [???]]
[s]UH? NO, NON SONO IL DIRETTORE[n]CAPO... FORSE.[n][w][e]
[s]MA SE LO FOSSI? VOI CHI[n]DIAVOLO SIETE? STATE[n]BATTENDO LA FIACCA?[n][w][e]

[msg D05_02_e341_036_ng2_selB_4 [???]]
[s]GOHOHOH! 為 IL MIO ENTUSIASMO[n]A SPINGERMI A[n]TORNARE AL LAVORO.[n][w][e]
[s]MA SOPRATTUTTO, CHI SIETE?[n]DOVREI SEGNALARVI TUTTI[n]PERCH畏 BATTETE LA FIACCA![n][w][e]

[msg D05_02_e341_036_ng2_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]為 il momento di prendere una[n]decisione, Joker. Cosa vuoi fare?[n][w][e]

[sel D05_02_e341_036_ng2_selC top]
[s]Affrontiamolo.[bitflag 0 0 106 1][e]
[s]Meglio andare via.[bitflag 0 0 106 1][e]

[msg D05_02_e341_036_ng2_selC_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Giusto, meglio evitare altre[n]discussioni. Facciamolo a pezzi![n][w][e]

[msg D05_02_e341_036_ng2_selC_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1163 65535 0]Quindi preferisci non[n]combattere? OK, ritiriamoci![n][w][e]

[msg D05_02_e341_036_ng2_selC_4 [???]]
[s]FUGGITE CON LA CODA[n]TRA LE GAMBE. SI ADDICE[n]AI TOPI DI FOGNA COME VOI.[n][w][e]

[msg D05_02_e341_036_ng_end_m [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Cos淫 impari, bastardo![n]E anche questa 因 fatta![n][w][e]

[msg D05_02_e341_036_ng_end_m_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non aveva nulla di utile,[n]per韻. Tempo sprecato.[n][w][e]

[msg D05_02_e341_036_ng_end_m_3 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]P-Pare che le dimensioni[n]non siano legate al[n]rango...[n][w][e]

[msg D05_02_e341_036_ng_end_m_4 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il direttore capo dev'essere[n]altrove... Proviamo a[n]cercare in un'altra stanza.[n][w][e]

[msg D05_02_e341_036_mes01 [???]]
[s][clr 2]HWA-HEM[clr 27]! CHI SIETE, FARABUTTI?[n]COME SIETE ENTRATI?[n][w][e]
[s]COSA VI PORTA QUI,[n]ALL'AZIENDA [clr 2]MIGLIORE IN ASSOLUTO,[clr 27][n]LA OKUMURA FOODS?[n][w][e]

[sel D05_02_e341_036_selA top]
[s]Sei il direttore capo?[e]
[s]Niente di speciale.[e]
[s]Facciamo due chiacchiere.[e]

[msg D05_02_e341_036_selA_0_m [???]]
[s]UHM? OOOH, CREDO DI AVER[n]CAPITO. SIETE I FAMOSI[n]LADRI FANTASMA![n][w][e]
[s][clr 2]GRAHAHAHAH[clr 27]! MOLTO BENE,[n]VI DIR違 LA VERIT委.[n][w][e]
[s]SONO PROPRIO IL DIRETTORE CAPO![n]STA A VOI SCEGLIERE SE[n]CREDERCI O MENO.[n][w][e]
[s]ORA... NON AVETE ALTRO[n]DA CHIEDERMI?[n][w][e]

[msg D05_02_e341_036_selA_1_m [???]]
[s]ALLORA PERCH畏 SIETE QUI?[n]ANDATEVENE SUBITO! LA VOSTRA[n]PRESENZA MI INDISPONE![n][w][e]
[s]...O COS維 AVREI DETTO,[n]MA AVETE DEGLI AFFARI DA[n]SBRIGARE, VERO? IO SO TUTTO![n][w][e]

[msg D05_02_e341_036_selA_2_m [???]]
[s]NON MI PIACE IL VOSTRO TONO, MA[n]VA BENE. NON MI CAPITA SPESSO[n]DI PARLARE CON I GIOVANI.[n][w][e]
[s]INTERAGISCO DI RADO[n]CON INDIVIDUI COS維 INSIGNIFICANTI.[n][clr 2]GRAHAHAHAH[clr 27]![n][w][e]
[s]CHE SUCCEDE? FORZA, CONTINUIAMO[n]LA CONVERSAZIONE![n][w][e]

[sel D05_02_e341_036_selB top]
[s]Parliamo del passato.[e]
[s]Parliamo del futuro.[e]
[s]Parliamo del pi迂 e del meno.[e]

[msg D05_02_e341_036_selB_0_m [???]]
[s]LODEVOLE. VOLETE ASCOLTARE LE[n]STORIE DEI MIEI SUCCESSI, VERO?[n][w][e]
[s][clr 2]QUANDO ERO GIOVANE[clr 27],[n]TUTTI ERANO UMILI COME VOI.[n]MA AL GIORNO D'OGGI...[n][w][e]

[msg D05_02_e341_036_selB_1_m [???]]
[s]PERSONE PRIVE DI STABILIT委[n]VOGLIONO PARLARE DEL FUTURO?[n][clr 2]GRAHAHAHAH[clr 27]! COME SIETE INGENUI.[n][w][e]
[s]PER DEI RAGAZZI COME VOI,[n]IL FUTURO 為 FRIVOLO.[n][w][e]
[s]MA AMMETTO CHE 為[n]UN ARGOMENTO INTERESSANTE...[n][w][e]

[msg D05_02_e341_036_selB_2_m [???]]
[s]VOLETE PARLARE CON ME DI ARGOMENTI[n]BANALI? NON LO POSSO[n]SOPPORTARE.[n][w][e]
[s]SEDETEVI E ASCOLTATE![n][clr 2]QUANDO ERO GIOVANE[clr 27]...![n][w][e]

[msg D05_02_e341_036_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]為 il momento di prendere una[n]decisione, Joker. Cosa vuoi fare?[n][w][e]

[sel D05_02_e341_036_selC top]
[s]Affrontiamolo.[bitflag 0 0 106 1][e]
[s]Meglio andare via.[bitflag 0 0 106 1][e]

[msg D05_02_e341_036_selC_0_m [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]OK, Joker.[n]Facciamolo a pezzi![n][w][e]

[msg D05_02_e341_036_selC_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Quindi preferisci non[n]combattere? OK, ritiriamoci![n][w][e]

[msg D05_02_e341_036_selC_1_m_2 [???]]
[s]EHI, DOVE STATE ANDANDO?[n]NON ABBIAMO ANCORA FINITO![n][w][e]

[msg D05_02_e341_036_end_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]OK, lo abbiamo battuto.[n]Uh? Cosa c'因 per terra...?[n][w][e]

[msg D05_02_e341_036_end_mes0_2 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfetto! Finalmente abbiamo[n]il tesserino del direttore capo![n][w][e]

[msg D05_02_e341_036_end_mes0_3 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Finalmente possiamo attraversare[n]la porta al piano di sotto![n][w][e]

[msg D05_02_e341_036_end_mes0_4 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9048 65535 0]S淫, andiamo a dare un'occhiata![n]為 ora di squagliarsela,[n]come il gelato![n][w][e]

[msg D05_02_e341_035_mes01 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Uhm, un altro ostacolo. Anche[n]qui c'因 l'autenticazione di rango?[n][w][e]

[msg D05_02_e341_035_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hm. Possiamo passare solo con un[n]tesserino da direttore capo o[n]superiore.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A giudicare dalla conformazione[n]del piano, per韻, sembra che da qui[n]non si raggiungano nuove zone.[n][w][e]

[msg D05_02_e341_035_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Quindi il nostro obiettivo[n]resta la porta al piano di sotto.[n][w][e]

[msg D05_02_e341_035_mes04 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non saltiamo questa roba[n]rubando il tesserino del[n]presidente? Voglio farla finita![n][w][e]

[msg D05_02_e341_035_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uhm, un altro ostacolo. Anche[n]qui c'因 l'autenticazione di rango?[n][w][e]

[msg D05_02_e341_035_mes06 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gi稲gi稲. Possiamo passare solo[n]con un tesserino da direttore[n]capo o superiore.[n][w][e]

[msg D05_02_e341_035_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Possiamo passare solo con un[n]tesserino da direttore capo o[n]superiore.[n][w][e]

[msg D05_02_e341_035_clear_me [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3048 65535 0]S淫, si 因 aperta![n][w][e]

[msg D05_02_e341_035_clear_me_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora possiamo muoverci[n]liberamente su questo piano![n][w][e]

[msg D05_02_e341_035_clear_me_3 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfetto. Abbiamo il tesserino[n]che stavamo cercando. Finiamo[n]qui e scendiamo di sotto![n][w][e]

[msg D05_02_e341_036_ng4_mes0 [???]]
[s]UMPF, CHI SIETE? COSA CI FANNO[n]QUI DEI MOCCIOSI COME VOI?[n][w][e]

[sel D05_02_e341_036_ng4_selA top]
[s]Non essere sgarbato.[e]
[s]Siamo i Ladri Fantasma.[e]
[s]Stiamo dando fastidio?[e]

[msg D05_02_e341_036_ng4_selA_2 [???]]
[s][clr 2]AHAHAHAH[clr 27]! SGARBATO? COME OSATE[n]PARLARMI COS維![n][w][e]
[s]ASCOLTATE! SONO UNA[n]FIGURA CHIAVE NELL'AZIENDA[n][clr 2]MIGLIORE IN ASSOLUTO[clr 27]![n][w][e]
[s]L'UNICO SGARBO 為 LA VOSTRA[n]INTRUSIONE! COME SIETE ENTRATI!?[n][w][e]

[msg D05_02_e341_036_ng4_selA_3 [???]]
[s]I LADRI FANTASMA?!? QUINDI[n]AMMETTETE DI ESSERE DEGLI INTRUSI![n][w][e]
[s]IMPUDENTI! 為 ORA DI[n]DARVI UNA BELLA LEZIONE![n][w][e]

[msg D05_02_e341_036_ng4_selA_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Uhm, ero giusto in vena[n]di un po' d'azione.[n]Avanti, Joker![n][w][e]

[msg D05_02_e341_036_ng4_selA_5 [???]]
[s]MA CERTO! DOVE CREDETE[n]DI ESSERE?!?[n][w][e]
[s]QUEST'AZIENDA 為 [clr 2]LA MIGLIORE[n]IN ASSOLUTO[clr 27]: OKUMURA FOODS![n]NON DOVRESTE ESSERE QUI![n][w][e]
[s]MA SOPRATTUTTO, CHI[n]SIETE?!? COME SIETE ENTRATI?!?[n][w][e]

[sel D05_02_e341_036_ng4_selB top]
[s]Ci siamo intrufolati.[e]
[s]Dalla porta principale.[e]
[s]為 un segreto.[e]

[msg D05_02_e341_036_ng4_selB_2 [???]]
[s]VOI COSA?!? QUINDI NON SIETE[n]ALTRO CHE RAPINATORI![n][w][e]
[s]AH, CAPISCO! SIETE SPIE DI[n]UN'AZIENDA RIVALE! IN TAL CASO,[n]VI CATTURER違 PERSONALMENTE![n][w][e]

[msg D05_02_e341_036_ng4_selB_3 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4025 65535 0]Uhm, ero giusto in vena[n]di un po' d'azione.[n]Avanti, Joker![n][w][e]

[msg D05_02_e341_036_ng4_selB_4 [???]]
[s]DALLA PORTA PRINCIPALE? STATE[n]QUINDI DICENDO DI NON[n]ESSERE PERSONE SOSPETTE?[n][w][e]
[s]AVETE UN ASPETTO PREOCCUPANTE... MA[n]SAREBBE UN PROBLEMA SE VI[n]SEGNALASSI PER ERRORE...[n][w][e]

[msg D05_02_e341_036_ng4_selB_5 [???]]
[s]UN SEGRETO?!? CREDETE CHE[n]SIA UN IDIOTA?!?[n][w][e]
[s]ANCHE SE... HO SENTITO DI[n]UN'IMMINENTE ISPEZIONE SEGRETA.[n]E SE FOSTE DEGLI ISPETTORI?[n][w][e]
[s]UHMMM, SIETE TROPPO SOSPETTI,[n]PER ESSERLO...[n][w][e]

[msg D05_02_e341_036_ng4_mes0_2 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]為 il momento di prendere una[n]decisione, Joker. Cosa vuoi fare?[n][w][e]

[sel D05_02_e341_036_ng4_selC top]
[s]Affrontiamolo.[bitflag 0 0 106 1][e]
[s]Meglio andare via.[bitflag 0 0 106 1][e]

[msg D05_02_e341_036_ng4_selC_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Giusto, meglio evitare altre[n]discussioni. Facciamolo a pezzi![n][w][e]

[msg D05_02_e341_036_ng4_selC_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Quindi preferisci non[n]combattere? OK, ritiriamoci![n][w][e]

[msg D05_02_e341_036_ng4_selC_4 [???]]
[s]UN MOMENTO! COSA[n]STA SUCCEDENDO?!? EHI![n][w][e]

[msg D05_13_avoid_fake_battle [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Abbiamo gi稲 il tesserino[n]identificativo, non abbiamo pi迂[n]bisogno di combattere inutilmente.[n][w][e]

[msg D05_13_Bucho_door_back_s [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non possiamo aprirla da qui.[n]Provate a cercare un[n]lettore di schede...[n][w][e]

