[msg D05_02_e341_071_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che resti un[n]solo cancello. Dovremmo[n]dirigerci l淫.[n][w][e]

[msg D05_02_e341_071_mes02 [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm? Un momento...[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che l'unico modo per[n]raggiungerlo sia passare su[n]quella... pressa idraulica?[n][w][e]

[msg D05_02_e341_071_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gi稲. Dobbiamo solo capire[n]come fermarla. Per adesso[n]concentriamoci su quello.[n][w][e]

