[msg D05_e342_013_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Questi sono... interruttori?[n][w][e]

[msg D05_e342_013_mes02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'因 scritto qualcosa sopra.[n]Questi simboli...[n][w][e]

[msg D05_05_EX3BOSS_1st_01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Quell'Ombra sembra davvero forte.[n]Prepariamoci per bene.[n][w][e]
[s]Siamo pronti al meglio, Joker?[n][w][e]

[msg D05_05_EX3BOSS_2nd_01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3018 65535 0]Siamo pronti, Joker?[n][w][e]

[sel D05_05_EX3BOSS_selA top]
[s]Andiamo.[e]
[s]Aspettiamo.[e]

[msg D05_05_EX3BOSS_selA_2_01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3035 65535 0]OK. Dovremmo tornare quando[n]saremo sicuri di essere pronti.[n][w][e]

[msg D05_05_EX3BOSS_before_ba [Guardia robot]]
[s]CI VUOLE CORAGGIO PER IGNORARE[n]I PROPRI DOVERI E POLTRIRE...[n][w][e]
[s]A QUANTO PARE ABBIAMO DEI[n]LAVORATORI IMPUDENTI CHE NECESSITANO[n]DI FORMAZIONE EXTRA![n][w][e]

[msg D05_05_EX3BOSS_before_ba_2 [Haru]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma smettila! Il tuo cosiddetto[n]allenamento 因 solo una tortura![n][w][e]
[s]Andiamo![n][w][e]

[msg D05_05_EX3BOSS_After_win [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3048 65535 0]Ce l'abbiamo fatta![n][w][e]

[msg DUMMY_mes01 [ERROR]]
[s]Dummy[n][w][e]

