[msg D157_013_miniEV_01_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]A quanto pare abbiamo[n]aggirato il muro di carte.[n][w][e]

[msg D157_013_miniEV_01_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che palle fare tutta quella[n]strada! Dov'因 quel bastardo[n]di prima, eh?!?[n][w][e]

[msg e382_235_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]Ehi, quell'Ombra non stava[n]armeggiando con questo?[n][w][e]

[msg e382_235_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora abbiamo una via d'uscita![n]Possiamo proseguire senza[n]preoccuparcene pi迂.[n][w][e]

[msg D06_mini_ev03_mes01 [Commerciante]]
[s]Buonasera.[n][w][e]
[s]Ora le spiegher韻 le regole[n]di questa battaglia. Non tema,[n]sono molto semplici.[n][w][e]

[msg D06_mini_ev03_mes02 [Commerciante]]
[s][clr 2]Se la carta mostrata 因[n]superiore a quella dell'avversario,[n]lei vince[clr 27].[n][w][e]
[s][clr 2]Con tre vittorie[clr 27] si vince [clr 2]un set[clr 27].[n][w][e]
[s]Chi vince prima [clr 2]due set[clr 27] vince l'incontro.[n][w][e]
[s]Se sar稲 lei a vincere,[n][clr 2]raddoppier韻[clr 27] le monete[n]in suo possesso.[n][w][e]
[s]Fine della spiegazione.[n]Ha compreso le regole?[n][w][e]

[sel D06_mini_ev03_selA top]
[s]S淫.[e]
[s]Un'altra volta, prego.[e]

[msg D06_mini_ev03_selA_0_mes [Commerciante]]
[s]Diamo inizio alla battaglia.[n][w][e]

[msg D06_mini_ev03_selA_1_mes [Commerciante]]
[s]Molto bene.[n]Lo rispiego.[n][w][e]

[msg D06_mini_ev03_mes03 [Commerciante]]
[s]Ha vinto questo set.[n][w][e]
[s]為 il suo primo set.[n]Se ne vince un altro,[n]raddoppieremo le sue monete.[n][w][e]

[msg D06_mini_ev03_mes4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma che...? 為 facilissimo.[n]Come bere un bicchier d'acqua![n][w][e]

[msg D06_mini_ev03_mes5 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Speriamo che continui a[n]essere cos淫 facile.[n][w][e]

[msg D06_mini_ev03_mes6 [Commerciante]]
[s]Lei 因 un osso duro,[n]signore. Sono in[n]guai seri.[n][w][e]
[s]Dovr韻 impegnarmi di pi迂.[n][w][e]

[msg D06_mini_ev03_mes7 [Commerciante]]
[s]Mmm, quello 因 un... uno?[n][w][e]
[s]Allora gioco questa.[n][w][e]

[msg D06_mini_ev03_mes8 [Commerciante]]
[s]Mmm... Che carta ha usato?[n]Proprio non saprei...[n][w][e]
[s]Sceglier韻 questa.[n][w][e]

[msg D06_mini_ev03_mes9 [Commerciante]]
[s]為 un tre, quello?[n]Allora user韻 un quattro.[n][w][e]

[msg D06_mini_ev03_mes10 [Commerciante]]
[s]Credo che lei abbia un[n]numero alto. Forse dovrei[n]scegliere questa.[n][w][e]

[msg D06_mini_ev03_mes11 [Commerciante]]
[s]Non so se posso vincere.[n]Dovr韻 tenere duro.[n][w][e]

[msg D06_mini_ev03_mes12 [Commerciante]]
[s]Oh, avevo ragione. Che fortuna.[n][w][e]

[msg D06_mini_ev03_mes13 [Commerciante]]
[s]Ho vinto di poco.[n]La fortuna mi ha sorriso.[n][w][e]

[msg D06_mini_ev03_mes14 [Commerciante]]
[s]Oh, ho scelto bene.[n]Si direbbe che abbia vinto io.[n][w][e]

[msg D06_mini_ev03_mes15 [Commerciante]]
[s]Mi sento molto lucido.[n]Che fortuna.[n][w][e]

[msg D06_mini_ev03_mes16 [Commerciante]]
[s]Ah, sembra che non abbia[n]vinto, signore.[n][w][e]

[msg D06_mini_ev03_mes17 [Commerciante]]
[s]Ho vinto questo set.[n][w][e]
[s]Siamo in parit稲. Il prossimo[n]set sar稲 decisivo.[n][w][e]

[msg D06_mini_ev03_mes18 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bastardo! 為 tutto truccato![n][w][e]

[msg D06_mini_ev03_mes19 [Commerciante]]
[s]Truccato? Che intende?[n][w][e]

[msg D06_mini_ev03_mes20 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sai esattamente i numeri[n]che usiamo![n][w][e]

[msg D06_mini_ev03_mes21 [Commerciante]]
[s]Non so di cosa stia parlando.[n]Ho indovinato[n]per puro caso.[n][w][e]

[msg D06_mini_ev03_mes22 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puro caso, eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto bene. Ma i tuoi trucchi[n]non funzioneranno di nuovo.[n][w][e]

[msg D06_mini_ev03_mes23 [Commerciante]]
[s]M-Ma che diavolo...?!?[n][w][e]

[msg D06_mini_ev03_mes24 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che succede? Abbiamo vinto, no?[n][w][e]

[msg D06_mini_ev03_mes25 [Commerciante]]
[s]Non pu韻 essere...[n][w][e]

[msg D06_mini_ev03_mes26 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Su, continuiamo.[n][w][e]

[msg D06_mini_ev03_mes27 [Commerciante]]
[s]C-c'因 qualcosa di strano... Non[n]pu韻 essere![n][w][e]
[s]State barando![n][w][e]

[msg D06_mini_ev03_mes28 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Senti chi parla...[n][w][e]

[msg D06_mini_ev03_mes29 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No che non stiamo barando.[n]Le false accuse sono[n]molto sgradevoli, sai.[n][w][e]

[msg D06_mini_ev03_mes30 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Proprio cos淫! Comunque, vediamo[n]di continuare![n][w][e]

[msg D06_mini_ev03_mes31 [Commerciante]]
[s]Ngh...[n][w][e]

[msg D06_13_TRUMP_END_mes01 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi abbiamo vinto noi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qual era il premio? Hai detto[n]che avresti raddoppiato le nostre[n]monete, vero?[n][w][e]

[msg D06_13_TRUMP_END_mes02 [Commerciante]]
[s]...S淫.[n][w][e]
[s]Se ne occuper稲[n]l'addetto della reception.[n][w][e]

[msg D06_13_TRUMP_END_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm? Che stai tramando?[n][w][e]

[msg D06_13_TRUMP_END_mes04 [Commerciante]]
[s]Non gliel'ho detto?[n][w][e]
[s]Per vincere dovr稲 sopravvivere[n]a una battaglia contro un[n]nostro abile impiegato.[n][w][e]

[msg D06_13_TRUMP_END_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma 因 ridicolo.[n][w][e]

[msg D06_13_TRUMP_END_mes06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra facile.[n][w][e]

[msg D06_13_TRUMP_END_mes7 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sbrighiamoci allora![n][w][e]

[msg Battle_Number01 [Commerciante]]
[s]Buonasera.[n][w][e]
[s]Ora le spiegher韻 le regole[n]di questa battaglia. Non tema,[n]sono molto semplici[n][w][e]
[s][clr 2]Se la carta mostrata 因[n]superiore a quella dell'avversario,[n]lei vince[clr 27].[n][w][e]
[s]Se lei [clr 2]vince per primo tre set[clr 27],[n][clr 2]raddoppieremo[clr 27] il numero di monete[n]attualmente in suo possesso.[n][w][e]
[s]Molto bene, iniziamo.[n][w][e]

[msg Battle_Number02 [Commerciante]]
[s]Bene, passiamo alla[n]battaglia successiva.[n][w][e]

[msg Card_Battle_WIN [Commerciante]]
[s]Molto bene, signore. Sono colpito.[n][w][e]

[msg Card_Battle_LOSE [Commerciante]]
[s]Oh? Ho vinto io.[n][w][e]

[msg Card_Battle_DRAW [Commerciante]]
[s]Pareggio.[n][w][e]

[msg Card_Battle_WIN_SET [Commerciante]]
[s]Magnifico. Ha vinto questo set.[n][w][e]

[msg Card_Battle_LOSE_SET [Commerciante]]
[s]Oh, ho vinto. Che fortuna.[n][w][e]

[msg Card_Battle_WIN_END [Commerciante]]
[s]C-congratulazioni, signore.[n]Ha vinto lei.[n][w][e]
[s]Ora le dar韻 le monete.[n]Favorisca la tessera[n]di socio, prego.[n][w][e]

[msg Card_Battle_LOSE_END [Commerciante]]
[s]Oh? Purtroppo, sembra che[n]abbia vinto io.[n][w][e]
[s]為 il momento della sua[n]penalit稲, signore.[n][w][e]

[msg Card_Battle_Trick [Commerciante]]
[s]Mmm, tiro a indovinare. Credo che[n]abbia giocato un [clr 2][var 0][clr 27]...[n][w][e]
[s]In tal caso,[n]dovrei usare questa carta.[n][w][e]

[msg Card_Battle_LAST_01 [Commerciante]]
[s]Mmm, sono un po' confuso.[n][w][e]
[s]Sceglier韻... questa?[n][w][e]

[msg Card_Battle_LAST_02 [Ryuji]]
[s]Merda, smettila.[n]Dev'essere per forza truccato...[n][w][e]

[msg Card_Battle_LAST02_01 [Commerciante]]
[s]Ah, riesco di nuovo a pensare[n]chiaramente! Sceglier韻 questa.[n][w][e]

[msg Card_Battle_LAST03_01 [Akechi]]
[s]Un momento. Sei sicuro[n]che non stai barando?[n][w][e]

[msg Card_Battle_LAST03_02 [Commerciante]]
[s]Certo che no! Come potrei[n]barare in un gioco simile?[n][w][e]

[msg Card_Battle_LAST03_03 [Akechi]]
[s]Mmm, direi che potresti farlo[n]in un modo difficile[n]da dimostrare.[n][w][e]

[msg Card_Battle_LAST03_04 [Commerciante]]
[s]Pu韻 pensarla come ritiene[n]pi迂 opportuno, signore.[n][w][e]

[msg Card_Battle_LAST03_05 [Akechi]]
[s]Molto bene. Continuiamo[n]a giocare.[n][w][e]

[msg Card_Battle_LAST03_06 [Commerciante]]
[s]Lieto che capisca.[n]Bene, giriamo le nostre carte.[n][w][e]

[msg WIN_COUNT_MES [Commerciante]]
[s]Siamo a[n][clr 2][var 0][clr 27] vittorie per lei e [clr 2][var 1][clr 27] per me.[n][w][e]

[msg __test_message_01]
[s]dummy fhit_157_013_00[n][w][e]

