[msg D06_15_e382_310_mes01 [Presentatore]]
[s]Diamo inizio alla triplice[n]battaglia infernale![n][w][e]
[s]Per vincere bisogna sopravvivere[n]ai tre assassini![n][w][e]
[s]Decuplicheremo le monete[n]di chiunque ci riuscir稲![n][w][e]
[s]Passiamo alla prima battaglia![n][w][e]

[msg D06_15_e382_310_mes02 [Presentatore]]
[s]Via![n][w][e]

[msg e382_305_STOP_mes02 [Ombra]]
[s]Qui si rischia la vita.[n]Non potr韻 farla uscire da questa[n]stanza finch姻 non vincer稲.[n][w][e]

[msg e382_305_03_mes01 [Cassiere Ombra]]
[s]Dopo l'ingresso in questa stanza,[n]non c'因 possibilit稲 di ritirarsi.[n]Acconsente?[n][w][e]

[sel e382_305_03_selA top]
[s]Entro.[bitflag 0 0 106 1][e]
[s]Prima dovrei prepararmi.[bitflag 0 0 106 1][e]

[msg e382_305_03_selA_0_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg e382_305_03_selA_1_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg EV_MOVE_57_15_CBOSS01 [Commerciante]]
[s]Una triplice battaglia.[n]Se vincer稲, le sue monete[n]saranno decuplicate.[n][w][e]

[msg EV_MOVE_57_15_CBOSS02]
[s]La prima battaglia.[n][w][e]

[msg EV_MOVE_57_15_CBOSS03]
[s]La seconda battaglia.[n][w][e]

[msg EV_MOVE_57_15_CBOSS04]
[s]La terza battaglia.[n][w][e]

[msg EV_MOVE_57_15_CBOSS05]
[s]Sfida completata. Le sue monete[n]saranno decuplicate.[n][w][e]

[msg D6_ARENA_STOP_MES01 [Receptionist]]
[s]Dove vai?[n][w][e]
[s]Dopo aver accettato[n]la sfida, si pu韻 uscire[n]di qui solo avanzando.[n][w][e]

[msg D06_15_e382_360_mes8 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, devi ancora riscuotere[n]il premio.[n][w][e]

