[msg Dummy]
[s]......[n][w][e]

[msg mini_ev_mes_02_02_03_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Fermo, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Le slot machine sono facili[n]da controllare. Per loro sarebbe[n]molto semplice truccarle.[n][w][e]

[msg mini_ev_mes_02_02_03_mes_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi, se continuiamo cos淫[n]non vinceremo mai.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...A meno che non facciamo qualcosa[n]per risolvere situazione.[n][w][e]

[msg mini_ev_mes_02_01_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Capisco come ti senti, ma[n]per ora dobbiamo neutralizzare[n]il sistema che pilota le giocate.[n][w][e]

[msg mini_ev_mes_02_01_mes09 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Credo che l稲 dietro ci sia[n]un terminale per le informazioni.[n]Prova a cercare, Joker.[n][w][e]

[msg D157_010_miniEV_01_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il nemico sembra non volersi[n]allontanare da quell'area...[n]Forse vuole proteggere qualcosa?[n][w][e]

[msg D157_010_miniEV_01_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non saprei. Pensi che[n]dovremmo eliminarlo?[n][w][e]

[msg D157_010_miniEV_01_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, sarebbe meglio farlo[n]il prima possibile.[n][w][e]

[msg D157_010_miniEV_01_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene! Possiamo guardare con calma[n]cosa c'因 l淫 dopo aver[n]gonfiato di botte quell'affare![n][w][e]

[msg SLOT_SAKUSEN_01]
[s]作戦イベント部屋。[n][w][e]
[s]1:敵を全て倒す。2:散開探索[n]3:アケチによる作戦提案。作戦発生。[n][w][e]
[s]作戦イベント後、追加4万枚入手。[n]所持コイン5万枚になり、EVの新フロア解放。[n][w][e]

[msg SLOT_SAIKU_01]
[s][clr 4]細工でスロットが絶対当たる様になるイベント[n](フタバが回線に繋ぐ? )[clr 27][n][w][e]

[msg SLOT_SAIKU_02 [Futaba]]
[s]Questo grosso affare controllava[n]tutte le slot nei dintorni.[n][w][e]
[s]Ora l'ho riprogrammato e[n]dovrebbe essere pi迂 facile[n]vincere anche alle slot minori.[n][w][e]
[s]Scegli tu cosa fare[n]adesso, Joker.[n][w][e]

[msg e380_220_mes9 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Proviamo un altro pannello di[n]controllo. Da qui non si pu韻[n]disattivare il meccanismo.[n][w][e]

[msg mini_ev_mes_02_02_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Prima mettiamo fine alla storia[n]degli imbrogli. Cerchiamo qualcosa[n]di sospetto in giro.[n][w][e]

[msg mini_ev_mes_02_02_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Giochiamo prima alla slot grande.[n]Dobbiamo farlo prima che ci[n]provi qualche altro ospite.[n][w][e]

[msg mini_ev_mes_02_02_mes03 [Voce meccanica]]
[s]Vincite: 20 monete per le[n]ciliegie, 120 monete per i BAR[n]e 200 monete per un 777.[n][w][e]
[s]Quota d'ingresso: 20 monete.[n]Desidera giocare?[n][w][e]

[sel mini_ev_mes_02_02_selA top]
[s]Gioca una volta[e]
[s]Ignorala per ora[e]

[msg mini_ev_mes_02_02_selA_0 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_02_02_selA_1 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg D07_10_BIG_SLOT_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Prima mettiamo fine alla storia[n]degli imbrogli. Cerchiamo qualcosa[n]di sospetto in giro.[n][w][e]

[msg D07_10_BIG_SLOT_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E vaiii! Facciamo[n]un po' di soldi, su![n][w][e]

[msg D07_10_BIG_SLOT_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Datti da fare, Joker![n][w][e]

[msg D07_10_BIG_SLOT_mes04 [Voce meccanica]]
[s]Vincite: 20.000 monete per le[n]ciliegie, 30.000 per i BAR[n]e 50.000 per un 777.[n][w][e]
[s]Quota d'ingresso: 5000 monete.[n]Desidera giocare?[n][w][e]

[sel D07_10_BIG_SLOT_selA top]
[s]Gioca alla slot grande[e]
[s]Ignorala per ora[e]

[msg D07_10_BIG_SLOT_selA_0_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wow, ma 因 fantastico![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_2 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A-a-abbiamo vinto! Guardate![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_3 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Suppongo che nel mondo del gioco[n]d'azzardo, 因 a questo punto che[n]dicono "Abbiamo un vincitore"...[n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Eh?[n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_5 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lascia stare.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo raggiunto la quota[n]che volevamo. Scambiamo le monete[n]con una tessera delle puntate alte.[n][w][e]

[msg D07_10_BIG_SLOT_selA_1_m [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E perch姻?[n][w][e]

[msg D07_10_BIG_SLOT_selA_1_m_2 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non abbiamo abbastanza monete...?[n][w][e]

[msg D07_10_BIG_SLOT_selA_2_m [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_02_mes05 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se continuiamo a giocare qui,[n]attireremo l'attenzione. Per ora[n]smettiamo di usare questa slot.[n][w][e]

[msg D06_SLOT_CONSOLE_NOT_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Joker, suggerisco di esaminare[n]subito la slot machine gigante.[n][w][e]

[msg seigyoban_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Da qui non possiamo bloccare[n]i loro trucchi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci dovrebbero essere dei[n]pannelli di controllo associati a[n]vari colori, qui in zona.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tra questi, mi servono il [clr 2]rosso[clr 27][n]e il [clr 2]verde[clr 27]. Da l淫,[n]dovrei poter controllare le cose.[n][w][e]

[msg seigyoban_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]Ma dove saranno?[n][w][e]

[msg seigyoban_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uno dovrebbe essere [clr 2]nei pressi[n]dell'ingresso[clr 27] dell'area. Il segnale[n]arriva fin l淫.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]L'altro dovrebbe essere da qualche[n]parte [clr 2]nell'area riservata allo staff[clr 27]...[n]O almeno credo.[n][w][e]

[msg seigyoban_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8021 65535 0]Uhm, l'ingresso della sala slot...[n]e da qualche parte[n]nell'area riservata allo staff...[n][w][e]

[msg seigyoban_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Da qui non possiamo bloccare[n]i loro trucchi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo trovare i pannelli di[n]controllo [clr 2]rosso[clr 27] e [clr 2]verde[clr 27].[n]Da l淫 dovrei poter fare qualcosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, ma quello rosso 因 gi稲[n]a posto. Non resta che trovare[n]quello [clr 2]verde[clr 27].[n][w][e]

[msg seigyoban_mes06 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Il pannello verde...[n]Dov'因 che si trova?[n][w][e]

[msg seigyoban_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, quello rosso era vicino[n]all'ingresso, quindi il verde sar稲[n][clr 2]nell'area riservata allo staff[clr 27].[n][w][e]

[msg seigyoban_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, normale che sia[n]in un'area dove non[n]ci sono clienti.[n][w][e]

[msg seigyoban_mes09 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]OK, adesso non ci resta[n]che iniziare a cercare![n][w][e]

[msg seigyoban_mes10 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Da qui non possiamo bloccare[n]i loro trucchi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo trovare i pannelli di[n]controllo [clr 2]rosso[clr 27] e [clr 2]verde[clr 27].[n]Da l淫 dovrei poter fare qualcosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, ma quello verde 因 gi稲[n]a posto. Non resta che trovare[n]quello [clr 2]rosso[clr 27].[n][w][e]

[msg seigyoban_mes11 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Sai dov'因?[n][w][e]

[msg seigyoban_mes12 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, quello verde era nel[n]corridoio dello staff, quindi il[n]rosso sar稲 [clr 2]all'ingresso[clr 27]![n][w][e]

[msg seigyoban_mes13 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]L'ingresso della sala slot...[n]為 dove ci aspettava[n]quell'Ombra...[n][w][e]

