[msg Dummy]
[s]…[n][w][e]

[msg EV_MOVE_57_14_MENU]
[s]>何処に移動しますか?[n][w][e]

[sel EV_MOVE_57_14_SEL top]
[s]5F:ボス戦に行く[e]
[s]3F:ハイローラー用カジノに行く[e]
[s]2F:VIP用カジノに行く[e]
[s]1F:一般用カジノに行く[e]
[s]行かない[e]

[msg EV_MOVE_57_14_IPPAN]
[s]>一般用カジノへ移動[n][w][e]

[msg EV_MOVE_57_14_VIP]
[s]>VIP用カジノへ移動[n][w][e]

[msg EV_MOVE_57_14_HIGH]
[s]>ハイローラー用カジノへ移動[n][w][e]

[msg EV_MOVE_57_14_BOSS_BATTL]
[s]>ボス戦に移動[n][w][e]

[msg EV_MOVE_57_14_CAN]
[s]>乗るのを止めた[n][w][e]

[msg F157_014_SETUMEI]
[s]下の扉でコインを増やしてから上の扉に向かう。[n][w][e]

