[msg Dummy]
[s]......[n][w][e]

[msg D157_008_miniEV_01_mes01 [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]為 la stanza privata?[n][w][e]

[msg D157_008_miniEV_01_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Molto comoda, no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Comunque, secondo quanto diceva[n]Crow, tutti i giochi di questo[n]posto sono truccati.[n][w][e]

[msg D157_008_miniEV_01_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, allora li prenderemo[n]con le mani nel sacco! Facile.[n]Su, diamoci da fare![n][w][e]

[msg EV_03_TALK_01 [Messaggio vocale]]
[s]Salite su quel pilastro e[n]andate nel corridoio del personale![n][w][e]

[msg EV_03_ANIME_01 [アニメ(仮)]]
[s]包囲を抜け、路地裏を走る主人公。[n][w][e]
[s]しかし、何者かの気配に立ち止まる。[n][w][e]
[s]こんな所にもシャドウかと構えるが[n]不意に通信の声が。[n][w][e]

[msg EV_03_ANIME_02 [Messaggio vocale]]
[s]No...[n][w][e]
[s]Questo segnale... non[n]proviene da un'Ombra.[n][w][e]
[s]Che sia davvero umano?!?[n][w][e]

[msg EV_03_ANIME_03 [アニメ(仮)]]
[s]ナビの声は不自然に途切れ[n]向こうでもトラブルがあった気配。[n][w][e]
[s]直後、主人公の周囲に現れたのは[n]黒服の一団。[n][w][e]
[s]多勢に無勢、拳銃を向けて包囲する彼らに[n]主人公は動けない。[n][w][e]

[msg EV_03_ANIME_04 [Agente]]
[s]Mmm, successo.[n][w][e]

[msg EV_03_ANIME_05 [アニメ(仮)]]
[s]黒服は事情を知っているような事を[n]述べた後[n][w][e]

[msg EV_03_ANIME_06 [Agente]]
[s]Siete stati venduti.[n][w][e]

[msg EV_03_ANIME_07 [アニメ(仮)]]
[s]思わず抵抗しようとするも、[n]後頭部を殴られ、主人公は気を失う。[n][w][e]
[s]『連れて行け』[n][w][e]
[s]と、黒服達は主人公を乱暴に引きずっていく。[n][w][e]

