[msg Dummy]
[s]......[n][w][e]

[msg e382_210_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Oooh, da qui arriva uno spiffero.[n]Che ne dite?[n]Vogliamo entrare?[n][w][e]

[msg e382_210_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Spero che nessuno ci scopra[n]e squalifichi per violazione[n]delle regole...[n][w][e]

[msg e382_210_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Buona idea. Forse alla fine dovremo[n]farne uso, ma per ora basta[n]ricordarsi che 因 qui.[n][w][e]

[msg e382_210_mes04 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Eh, alla fine l'abbiamo usato.[n][w][e]

[msg e382_210_mes05 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahah, forse avremmo dovuto[n]farlo dal principio.[n]Oh, beh... cos淫 因 la vita.[n][w][e]

[msg e382_210_mes06 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7159 65535 0]Yo, sentite! C'因 uno spiffero[n]qui. Pensate che conduca[n]da qualche parte?!?[n][w][e]

[msg e382_210_mes07 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, scoperta utile. Se non ci[n]permettono di avanzare,[n]possiamo passare di qua.[n][w][e]

[msg e382_210_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahah, un'idea degna della[n]sorella di Sae-san. Mi sta bene[n]qualsiasi piano sceglierete.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La decisione 因 tua, Joker.[n][w][e]

[msg BattleNumber_SETUMEI_01 [Reception]]
[s]Buonasera.[n][w][e]
[s]In questo gioco[n][clr 2]va scelta una delle due porte[clr 27][n]che si hanno di fronte.[n][w][e]

[msg BattleNumber_SETUMEI_02 [Reception]]
[s]Sul percorso scelto ci sar稲[n]un [clr 2]forziere[clr 27]. Prendi la [n] [clr 2]carta da gioco[clr 27] al suo interno.[n][w][e]
[s]Dopo aver superato la stanza,[n]dovrai affrontare una [clr 2]battaglia[clr 27][n]usando quella carta.[n][w][e]
[s]Le regole sono semplici: ognuno[n]mostra le proprie carte. Chi ha[n]quella con il [clr 2]numero pi迂 alto[clr 27] vince.[n][w][e]
[s]Non c'因 altro. Inoltre, non ci[n]assumiamo alcuna responsabilit稲 per[n]ci韻 che potrebbe accaderti.[n][w][e]
[s]Buon divertimento.[n][w][e]

[msg TEST_ROULETTE_01]
[s]壁に穴を開けてアタリ部屋に落下。[n]200000枚入手[n][w][e]

