[msg Dummy]
[s]......[n][w][e]

[msg D157_007_miniEV_04_mes01]
[s]※本番仕様ではNPCが配置され、室内に入れず、[n]「ここはダメだ、他の部屋に行こう」と誘導されます。[n][w][e]

[msg D157_007_miniEV_02_mes11 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo mettere fine a[n]quest'inganno. Dovremmo cercare[n]indizi nell'area.[n][w][e]

[msg D157_007_miniEV_03_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1160 65535 0]Sembra condurre da qualche parte.[n]Diamo un'occhiata, Joker?[n][w][e]

[msg D157_007_miniEV_06_mes01 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]所持コインが減りすぎだ。[n][clr 2]ロック台詞[clr 27][n][w][e]

[msg mini_ev_mes_01_GAME_01_m [Coniglietta Ombra]]
[s]Questa sala per il gioco dei dadi[n]ha esaurito le monete.[n][w][e]
[s]Ci scusiamo per il disagio, ma[n]dobbiamo chiedervi[n]di spostarvi in un'altra sala...[n][w][e]

[msg SAIKORO_GIM_01]
[s]dummy fhit_157_007_00[n][w][e]

[msg SAIKORO_GIM_02]
[s]dummy fhit_157_007_00[n][w][e]
[s]dummy fhit_157_007_00[n][w][e]

[msg SAIKORO_SAIKU_01]
[s]dummy fhit_157_007_00[n][w][e]

[msg D6_SAIKORO_FIRST [Commerciante]]
[s]Buonasera.[n][w][e]
[s]In questo gioco, si scommette[n]sulla somma del punteggio[n]di tre dadi.[n][w][e]
[s]為 un gioco molto semplice.[n][w][e]

[msg D6_SAIKORO_01 [Commerciante]]
[s]Scelga la quantit稲 di monete[n]che desidera puntare, prego.[n][w][e]

[sel D6_SAIKORO_BET_SEL top]
[s]100 monete.[e]
[s]500 monete.[e]
[s]1.000 monete.[e]
[s]Ci ho ripensato.[e]

[msg D6_SAIKORO_02 [Commerciante]]
[s]Ora scelga il numero che[n]secondo lei risulter稲 dai dadi.[n][e]

[sel D6_SAIKORO_HIGHT_LOW_BET top]
[s]Meno di nove.[e]
[s]Pi迂 di dieci.[e]

[msg D6_SAIKORO_03 [Commerciante]]
[s]Ora lanciamo i dadi.[n][w][e]

[msg D6_SAIKORO_ATARI [Commerciante]]
[s]Complimenti, signore. Ha vinto.[n]Ora possiede [var 0] monete.[n][w][e]

[msg D6_SAIKORO_HAZURE [Commerciante]]
[s]Peccato, signore. Ha perso.[n]Ora possiede [var 0] monete.[n][w][e]

[msg D6_SAIKORO_KEIZOKU [Commerciante]]
[s]Vuole continuare a[n]giocare, signore?[n][e]

[sel D6_SAIKORO_KEIZOKU_SEL top]
[s]Ci riprovo.[e]
[s]Per ora dovrei smettere.[e]

[msg D6_SAIKORO_TRICK01 [Akechi]]
[s]Possiamo parlare un attimo, Joker?[n][w][e]
[s]Visto quanto ha detto Sae-san,[n]dubito che questi croupier[n]giochino lealmente.[n][w][e]
[s]Probabilmente barano.[n]Perch姻 non diamo un'occhiata[n]qui intorno invece di giocare?[n][w][e]

[sel D6_SAIKORO_TRICK_SEL top]
[s]調べてみよう[e]
[s]もう少し遊ばせろ[e]

[msg D6_SAIKORO_TRICK_SEL01 [Akechi]]
[s]それが最善だろうね。[n]早速、周辺を調べてみよう。[n][w][e]

[msg D6_SAIKORO_TRICK_SEL02 [Akechi]]
[s]...火遊びはほどほどにしてくれよ。[n]一応、この発言は気に留めておいてくれ。[n][w][e]

[msg D6_Trick_Room [Guardia della security]]
[s]Bene, prendiamo un altro[n]po' di soldi...[n][w][e]

[msg D6_SAIKORO_ImpotentPlay_ [Commerciante]]
[s]Mi dispiace molto, signore.[n]Le suggerisco l'area delle slot.[n][w][e]

[msg D157_007_miniEV_05_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 un passaggio segreto? Ammetto che[n]sono curioso, ma prima dovremmo[n]pensare a procurarci le monete.[n][w][e]

[msg mini_ev_mes_01_GAME_03_m [Commerciante]]
[s]Benvenuti alla sala dadi![n][w][e]
[s]為 un gioco molto semplice, in cui[n]si scommette sulla somma[n]risultante dai dadi lanciati.[n][w][e]
[s]Si vince il doppio della puntata,[n]il triplo con facce corrispondenti.[n]Se escono solo sei, il quintuplo.[n][w][e]
[s]Per giocare occorrono venticinque[n]monete. Vuole partecipare[n]al gioco dei dadi?[n][w][e]

[sel mini_ev_mes_01_GAME_03_s top]
[s]Gioca una partita[e]
[s]Non giocare[e]

[msg mini_ev_mes_01_GAME_03_s_2 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_3 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_m_2 [Commerciante]]
[s]Ora indovini il[n]numero, prego.[n][w][e]

[sel mini_ev_mes_01_GAME_03_s_4 top]
[s]Tra tre e dieci.[e]
[s]Tra undici e sedici.[e]

[msg mini_ev_mes_01_GAME_03_s_5 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_6 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_7 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_m_3 [Commerciante]]
[s]Ha vinto, signore! La sua puntata[n]verr稲 [clr 2]raddoppiata[clr 27]![n][w][e]

[msg mini_ev_mes_01_GAME_03_m_4 [Commerciante]]
[s]Complimenti! Con gli stessi[n]numeri, la puntata viene [clr 2]triplicata[clr 27]![n][w][e]

[msg mini_ev_mes_01_GAME_03_m_5 [Commerciante]]
[s]Cielo, signore! Tutti sei![n]La sua puntata verr稲 [clr 2]quintuplicata[clr 27]![n][w][e]

[msg mini_ev_mes_01_GAME_03_m_6 [Commerciante]]
[s]...Abbiamo esaurito le monete[n]per questo gioco, signore.[n][w][e]
[s]Mi dispiace molto, ma devo[n]indirizzarla ad altri tavoli.[n][w][e]

[msg mini_ev_mes_01_GAME_03_m_7 [Commerciante]]
[s]Che sfortuna, signore.[n]Il banco vince.[n][w][e]

[msg mini_ev_mes_01_GAME_03_m_8 [Commerciante]]
[s]Vuole continuare[n]a giocare?[n][w][e]

[sel mini_ev_mes_01_GAME_03_s_8 top]
[s]Continuiamo.[e]
[s]Smetto.[e]

[msg mini_ev_mes_01_GAME_03_s_9 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg mini_ev_mes_01_GAME_03_s_10 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg D06_MIDDLE_DICE_LOCK_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Abbiamo gi稲 il dispositivo,[n]no? Andiamo da un'altra parte.[n][w][e]

[msg e380_125_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, dove stai andando? Abbiamo[n]preparato il dispositivo per[n]barare. Perch姻 andarsene adesso?[n][w][e]

[msg e380_125_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sarebbe un problema se fossero[n]altri a vincere. Prima di andarcene[n]sfruttiamo il dispositivo, Joker.[n][w][e]

