[msg D157_004_miniEV_01_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che questa porta non[n]possa essere aperta...[n][w][e]

[msg D157_004_miniEV_01_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovremo trovare un'altra strada.[n][w][e]

[msg D157_004_miniEV_02_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non voglio essere un peso per[n]la squadra. E lo dimostrer韻[n]con piacere qui.[n][w][e]

[sel D157_004_miniEV_02_selA top]
[s]Non vedo l'ora.[e]
[s]Prima prepariamoci.[e]

[msg D157_004_miniEV_02_selA_ [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora superer韻 anche[n]le tue aspettative![n][w][e]

[msg D157_004_miniEV_02_selA__2 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK, cominciamo quando[n]ti senti pronto.[n][w][e]

[msg e380_255_mes01 [Voce meccanica]]
[s]Operazione in fase di rinvio.[n]Restate in attesa.[n][w][e]

[msg EV_MOVE_57_04_MENU]
[s]>何処に移動しますか?[n][w][e]

[sel EV_MOVE_57_04_SEL top]
[s]5F:ボス部屋へ行く[e]
[s]4F:ボス前カジノに行く[e]
[s]3F:ハイローラー用カジノに行く[e]
[s]2F:VIP用カジノに行く[e]
[s]行かない[e]

[msg EV_MOVE_57_04_VIP]
[s]>VIP用カジノへ移動[n][w][e]

[msg EV_MOVE_57_04_HIGH]
[s]>ハイローラー用カジノへ移動[n][w][e]

[msg EV_MOVE_57_04_BOSS]
[s]>ボス前カジノへ移動[n][w][e]

[msg EV_MOVE_57_04_BOSS_BATTL]
[s]>ボス戦へ移動[n][w][e]

[msg EV_MOVE_57_04_CAN]
[s]>乗るのを止めた[n][w][e]

[msg EV_MOVE_57_04_NOT]
[s]>スイッチが反応しない...[n] カードキーが必要なようだ。[n][w][e]

[msg TEST_KENJI_EVENT]
[s]>女検事がエレベーターで上がっていく[n] 所が見える。[n][w][e]

[msg D157_004_miniEV_04_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Sembra proprio che questa[n]porta non si aprir稲...[n][w][e]

[msg D157_004_LOCK_KENJI_mes0 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Per ora dovremmo pensare a[n]inseguire Sae-san![n][w][e]

[msg D157_004_LOCK_KENJI_mes0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1164 65535 0]為 inutile agitarsi.[n]Scendiamo fin l淫 e sentiamo[n]cos'ha da dire.[n][w][e]

