[msg Dummy]
[s]......[n][w][e]

[msg test_COUNTER_mes01 [Coniglietta Ombra]]
[s]Vuole scambiare 50.000 monete per[n]una tessera delle puntate alte?[n][w][e]

[sel test_COUNTER_selA top]
[s]S淫, grazie.[e]
[s]No, grazie.[e]

[msg test_COUNTER_selA_0_mes0 [Coniglietta Ombra]]
[s]Allora procediamo[n]con lo scambio.[n][w][e]

[msg test_COUNTER_selA_0_mes0_2 [Coniglietta Ombra]]
[s]Non ha abbastanza monete.[n][w][e]

[msg test_COUNTER_selA_1_mes0 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg e380_250_mes01 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Finalmente abbiamo la scheda![n]Facciamo del nostro meglio[n]anche al prossimo piano.[n][w][e]

[msg e380_250_mes02 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Spero di essere stato utile.[n]Venite, raggiungiamo l'ascensore.[n][w][e]

[msg e380_260_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1133 65535 0]Ci aspettano di fronte[n]all'ascensore? Non mi sento[n]per niente il benvenuto...[n][w][e]

[msg e380_260_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'essere a causa dell'istigazione[n]di Sae-san. Sar稲 meglio[n]essere pronti a combattere.[n][w][e]

[sel e380_260_selA top]
[s]Diamoci dentro.[e]
[s]Aspettate un attimo.[e]

[msg e380_260_selA_0_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg e380_260_selA_1_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg EV_MOVE_57_06_MENU]
[s]>何処に移動しますか?[n][w][e]

[sel EV_MOVE_57_06_SEL top]
[s]214F:ハイローラー用カジノに行く[e]
[s]1F:一般用カジノに行く[e]
[s]行かない[e]

[msg EV_MOVE_57_06_IPPAN]
[s]>一般用カジノへ移動[n][w][e]

[msg EV_MOVE_57_06_HIGH]
[s]>ハイローラー用カジノへ移動[n][w][e]

[msg EV_MOVE_57_06_BOSS]
[s]>ボス前カジノへ移動[n][w][e]

[msg EV_MOVE_57_06_BOSS_BATTL]
[s]>ボス前カジノへ移動[n][w][e]

[msg EV_MOVE_57_06_CAN]
[s]>乗るのを止めた[n][w][e]

[msg VIP_ROOM_SETUMEI]
[s][clr 4]セーフルーム内で作戦会議。[n]この後のやる事として、以下を説明。[clr 27][n][w][e]
[s]コインを[clr 2]5万枚稼ぐ為に[n]サイコロゲーム[clr 27]から攻略する。[n][w][e]

[msg e383_005_mes01 [Ombra di Sae]]
[s]Che trucco ingegnoso.[n][w][e]

[msg e383_005_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo seguito le tue regole.[n][w][e]

[msg e383_005_mes03 [Ombra di Sae]]
[s]Umpf! Sono la direttrice di[n]questo casin韻, e le regole dicono[n]che vinco io![n][w][e]

[msg e383_005_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che sia la Sae-san di questo[n]mondo che quella del mondo reale[n]siano alla frutta...[n][w][e]

[msg e383_005_mes05 [Ombra di Sae]]
[s]...Credo che i nostri ospiti[n]prenderanno congedo, ora.[n][w][e]

[msg e383_005_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sarai tu ad andartene,[n]vestito nero![n][w][e]

[msg e383_005_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Le cose sarebbero state molto pi迂[n]semplici se l'avessimo fatto[n]sin dall'inizio![n][w][e]

[msg D157_006_miniEV_01_mes01 [Voce maschile]]
[s]...Vogliate scusarmi, signori.[n][w][e]

[msg D157_006_miniEV_01_mes02 [Cassiere Ombra]]
[s]Non avete ancora effettuato[n]la registrazione. Di qua, prego.[n][w][e]

[msg D157_006_miniEV_01_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Sembra che non abbiamo altra scelta[n]che fare come dice. Andiamo.[n][w][e]

