[msg Dummy]
[s]......[n][w][e]

[msg D157_005_DOOR_01_mes01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Merda, non si apre.[n][w][e]

[msg D157_005_DOOR_01_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sembra che sia necessaria[n]una scheda d'accesso?[n][w][e]

[msg D157_005_DOOR_01_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6019 65535 0]Magari possiamo usare quella scheda[n]di sicurezza che abbiamo trovato?[n][w][e]

[msg D157_005_DOOR_02_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Uhm, non si apre.[n][w][e]

[msg D157_005_DOOR_02_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'因 un dispositivo di[n]autenticazione. Forse ci serve[n]una scheda di accesso.[n][w][e]

[msg D157_005_DOOR_02_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non la otterremo facilmente,[n]visto che ha a che fare[n]con la sicurezza di questo posto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sarebbe logico pensare che[n]sia in possesso di un individuo[n]relativamente importante.[n][w][e]

[msg D157_005_DOOR_02_mes04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Non possiamo passare di qui.[n][w][e]

[msg D157_005_DOOR_02_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'因 un dispositivo di[n]autenticazione proprio di fianco.[n]Usiamo quella scheda di prima.[n][w][e]

[msg D157_005_DOOR_02_mes06 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6045 65535 0]Perfetto! 為 aperta![n][w][e]

[msg D157_005_DOOR_02_mes07 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ottimo. Ora dovremmo poter passare[n]di qui, Joker.[n][w][e]

[msg D157_005_DOOR_02_mes08 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra chiusa a chiave, ma non vedo[n]nulla che permetta di sbloccarla.[n][w][e]

[msg D157_005_DOOR_02_mes09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa porta non pu韻 essere aperta,[n]oppure il dispositivo per farlo[n]si trova dall'altra parte.[n][w][e]

[msg D157_005_DOOR_03_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1173 65535 0]Non si apre... Che sia[n]bloccata dalla parte opposta?[n][w][e]

[msg D157_005_DOOR_03_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1176 65535 0]Non si apre. Pare che dovremo[n]trovare una scheda d'accesso.[n][w][e]

