[msg D157_009_miniEV_02_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Cacchio, che numero[n]assurdo di slot, eh?[n][w][e]

[msg D157_009_miniEV_02_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Penso che siano tutte truccate.[n]Non vinceremo mai niente.[n][w][e]

[msg D157_009_miniEV_02_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora dobbiamo sistemare[n]la cosa.[n][w][e]

[msg D157_009_miniEV_02_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]No, credo che sia meglio[n]esaminare pi迂 a fondo l'area slot.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I casin韻 tengono le slot con[n]i limiti pi迂 alti nel retro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Visto che vogliamo neutralizzare[n]i loro trucchi, non sarebbe meglio[n]farlo su quelle?[n][w][e]

[msg D157_009_miniEV_02_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sempre se riusciremo a[n]risolvere il problema.[n][w][e]

[msg D157_009_miniEV_02_mes06 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Confido nella vostra abilit稲.[n][w][e]

[msg D157_009_miniEV_02_mes07 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]V-va bene, andiamo a cercare quella[n]bella slot machine![n][w][e]

