[msg Dummy]
[s]......[n][w][e]

[msg EV_02_TALK_01 [Messaggio vocale]]
[s][vp 1 0 0 382 0 0]Un secondo![n][f 1 6 65535][w][e]

[msg EV_02_TALK_01_02 [Messaggio vocale]]
[s][vp 1 0 0 383 0 0]Nemici rilevati! E molto veloci.[n]Sono gi稲 all'ingresso.[n][f 1 6 65535][w][e]

[msg EV_02_TALK_01_03 [Messaggio vocale]]
[s]Mmm, questo segnale 因[n]decisamente non umano.[n][w][e]

[msg EV_02_TALK_01_04 [Altra voce 1]]
[s][vp 1 0 0 355 0 0]Sono loro, non c'因 dubbio. Abbiamo[n]anche conferma visiva.[n]Beh... 因 il momento.[n][f 1 6 65535][w][e]

[msg EV_02_TALK_01_05 [Altra voce 2]]
[s][vp 1 0 0 148 0 0]Anch'io li vedo.[n][f 1 6 65535][w][e]
[s][vp 1 0 0 149 0 0]Per il momento non serve riunirsi.[n]Occupiamoci di loro uno per uno.[n][f 1 6 65535][w][e]

[msg EV_02_TALK_01_06 [Messaggio vocale]]
[s][vp 1 0 0 384 0 0]Arrivano le Ombre![n][f 1 6 65535][w][e]

