[msg D159_011_ev_switch_ng_me [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6004 65535 0]Nessuna risposta. Sar稲 rotto?[n]Ehiii?[n][w][e]

[msg D159_011_ev_switch_ng_me_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmh... Non voglio toccare nulla e[n]rischiare di causare qualche guaio.[n]Lasciamo tutto cos淫 com'因.[n][w][e]

[msg D159_011_ev_switch_ng_me_3 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6069 65535 0]Per me va bene. Dimentichiamocene![n][w][e]

