[msg D08_01_NPC_TALK_08_mes01 [Uomo d'affari esile]]
[s]Non dovrebbe andare cos淫.[n]為 solo colpa della societ稲,[n]che non mi ha accettato...[n][w][e]
[s]Il duro lavoro porta solo[n]allo sfinimento... Questa vita[n]因 un tale spreco...[n][w][e]
[s]S淫... vorrei che tutto[n]finisse e basta...[n][w][e]

[msg D08_01_NPC_TALK_08_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Ma che cavolo dice,[n]"finire" che? Stronzate![n][w][e]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda... Chi 因 che rinchiude[n]tutta questa gente?[n][w][e]

[msg D08_01_NPC_TALK_09_mes01 [Giovane indolente]]
[s]Da solo non posso fare niente...[n]Lascer韻 le riforme sociali[n]a chi ha il potere...[n][w][e]
[s]Non sono adatto a certe cose...[n]Ma tanto il mondo finir稲 presto,[n]per cui... che importa?[n][w][e]

[msg D08_01_NPC_TALK_09_mes02 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]Il mondo finir稲?[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che intende?[n]Non 因 un semplice commento[n]buttato l淫 cos淫, vero?[n][w][e]

[msg D08_01_NPC_TALK_10_mes01 [Ragazzo arcigno]]
[s]Riforma sociale? Non m'interessa.[n]Sono tutte stupidaggini. Non 因[n]pi迂 bella la distruzione?[n][w][e]

[msg D08_01_NPC_TALK_10_mes02 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4141 65535 0]La distruzione... bella?[n]Dev'essere fuori di senno.[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 come se desiderasse[n]la fine del mondo...[n][w][e]

[msg D08_01_NPC_TALK_11_mes01 [Donna dal sorriso beffardo]]
[s]Siete degli evasi?[n]Meglio se la smettete di cercare[n]di fuggire...[n][w][e]
[s]Dicono che alcuni, dopo[n]essere fuggiti, siano tornati[n]qui di recente...[n][w][e]
[s]Non sarebbe meglio se la gente[n]accettasse ci韻 che le accade?[n]Da morire dal ridere...[n][w][e]

[msg D08_01_NPC_TALK_11_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Sta parlando di Kamoshida[n]e degli altri?[n][w][e]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non so come spiegarlo, ma 因 come se[n]i nostri bersagli fossero pi迂[n]umani di questa gente...[n][w][e]

[msg D08_01_NPC_TALK_12_mes01 [Ragazzo dallo sguardo spento]]
[s]Il mondo esterno? Posso vederlo[n]tutto online. Spostarsi 因 una[n]tale seccatura...[n][w][e]
[s]E poi... ormai[n]manca poco...[n][w][e]

[msg D08_01_NPC_TALK_12_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9028 65535 0]Vuole vedere il mondo[n]online, eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]So come ci si sente, ma[n]dopo un po' diventa stancante.[n]Lo so per esperienza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E poi, a cosa[n]"manca poco"?[n][w][e]

[msg D09_05_SCN_BTL02_mes01]
[s]>このマップに『[clr 2]開かずの独房[clr 27]』を配置予定。[n][w][e]
[s]>モルガナが独房の扉を調べる。[n][w][e]

[msg D09_05_SCN_BTL02_mes02 [Morgana]]
[s]Questo 因... il posto[n]dove sono nato...[n][w][e]

[msg D09_05_SCN_BTL02_mes03 [Ryuji]]
[s]Qu-qui? Che diavolo 因?!?[n][w][e]

[msg D09_05_SCN_BTL02_mes04 [Morgana]]
[s]Non lo so. Non ricordo[n]nient'altro...[n][w][e]

[msg D09_05_SCN_BTL02_mes05]
[s]>一行は独房の扉を開けてみようと試みるが[n] 固く閉ざされた扉は、びくともしない。[n][w][e]

[msg D09_05_SCN_BTL02_mes06 [Urlo]]
[s]Ehi! State lontani da l淫![n][w][e]

[msg D09_05_SCN_BTL02_mes07 [Yusuke]]
[s]Umpf, pessimo tempismo.[n]Sconfiggiamolo prima che[n]chiami i rinforzi![n][w][e]

