[msg D08_01_e440_010_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E questo cos'因...? Prova[n]ad attivarlo, Joker.[n][w][e]

[msg D08_01_NPC_TALK_01_mes01 [Uomo d'affari spossato]]
[s]Duro lavoro... sforzi, barlumi di[n]vuota felicit稲... 為[n]davvero necessario...?[n][w][e]
[s]Il mondo 因 gi稲 completo...[n]Non resta niente da fare...[n][w][e]

[msg D08_01_NPC_TALK_01_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Cosa diavolo...? Anche questa[n]因 una specie di cella?[n][w][e]

[msg D08_01_NPC_TALK_01_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E ci sono dei vasi sanguigni[n]che ne fuoriescono.[n][w][e]

[msg D08_01_NPC_TALK_02_mes01 [Studente assonnato]]
[s]Siamo impotenti...[n]Genitori, insegnanti... Gli adulti[n]non fanno che manipolarci...[n][w][e]
[s]Se proviamo a opporci,[n]nessuno ci ascolta... e i nostri[n]spiriti vengono schiacciati...[n][w][e]
[s]為 meglio accettare la vita[n]per quello che 因 e cedere[n]al loro volere...[n][w][e]

[msg D08_01_NPC_TALK_02_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3184 65535 0]Io ero esattamente cos淫...[n][w][e]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se non fossi cambiata,[n]forse ora direi le stesse cose![n][w][e]

[msg D08_01_NPC_TALK_03_mes01 [Uomo inespressivo]]
[s]Non importa se qualcosa sia[n]giusto o sbagliato... Dobbiamo[n]solo seguire le regole...[n][w][e]
[s]Chi rispetta le regole[n]因 retto, mentre chi[n]le infrange 因 un criminale...[n][w][e]

[msg D08_01_NPC_TALK_03_mes02 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]Ehi, tu parli di rettitudine,[n]ma ti sei accorto che qualcosa[n]ti sta succhiando il cervello, s淫?[n][w][e]

[msg D08_01_NPC_TALK_04_mes01 [Uomo confuso]]
[s]Branco di sciocchi... Le vostre[n]azioni non cambieranno nulla...[n][w][e]
[s]Tutto questo finir稲 presto...[n]Vi conviene aspettare pazientemente[n]la vostra rovina...[n][w][e]

[msg D08_01_NPC_TALK_04_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]Tutto... finir稲?[n]Che sta dicendo?[n][w][e]

