[msg D08_01_e440_120_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]為 la stessa cosa[n]di prima?[n][w][e]

[msg D08_01_e440_120_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pi迂 o meno dovrebbe esserlo.[n]Fai un tentativo, Joker.[n][w][e]

[msg D08_01_NPC_TALK_05_mes01 [Ragazzo sprezzante]]
[s]Ehi, perch姻 siete da quella[n]parte? Pensate davvero di[n]guadagnarci qualcosa?[n][w][e]
[s]Siete proprio idioti, eh? Forse[n]dovreste vivere la vostra vita[n]con un po' pi迂 di cervello.[n][w][e]

[msg D08_01_NPC_TALK_05_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2182 65535 0]La felicit稲 因 molto di pi迂[n]che "guadagnare" qualcosa.[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A essere sincera, non credo proprio[n]che qui sia soddisfatto...[n][w][e]

[msg D08_01_NPC_TALK_06_mes01 [Uomo d'affari severo]]
[s]Ci sono degli standard. Leggi.[n]Regole. Comportamenti. Buon senso.[n][w][e]
[s]Seguire queste cose 因 l'unico[n]modo giusto di vivere. Come si fa[n]a non capirlo?[n][w][e]
[s]Chi non ci riesce 因 un emarginato.[n]Tutto quello che bisogna[n]fare 因 seguire le regole...[n][w][e]

[msg D08_01_NPC_TALK_06_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]Patetico. Dovrebbe rendersi[n]conto del suo stato...[n][w][e]

[msg D08_01_NPC_TALK_07_mes01 [Ragazzo esausto]]
[s]A lungo andare, le difficolt稲[n]diventano un nutrimento.[n]Bisogna solo sopportare.[n][w][e]
[s]Non importa quanto si[n]subisca, alla fine 因 solo per[n]il nostro bene.[n][w][e]
[s]Anzi, dovrei essere grato...[n]Questo 因 esattamente[n]ci韻 che merito...[n][w][e]

[msg D08_01_NPC_TALK_07_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6197 65535 0]Sono parole che mi fanno male.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un tempo la pensavo anch'io[n]in quel modo...[n][w][e]

