[msg D08_01_e446_035_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]Perfetto, sorveglianza disattivata![n][w][e]

[msg D08_01_e446_035_mes02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Era ora. Adesso[n]possiamo continuare![n][w][e]

[msg D08_01_e446_035_mes03 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]Ben fatto, Joker![n][w][e]

[msg D08_01_NPC_TALK_22_mes01 [Donna di mezza et稲 stanca]]
[s]Shido? Pu韻 fare quello che[n]vuole. Non m'importa di che[n]tipo di persona sia.[n][w][e]
[s]Presto non avr稲 pi迂[n]alcuna importanza...[n][w][e]

[msg D08_01_NPC_TALK_22_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1038 65535 0]Capisco...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non si rende conto di[n]cosa voglia dire veramente[n]essere governati da qualcuno.[n][w][e]

[msg D08_01_NPC_TALK_23_mes01 [Ragazzo tranquillo]]
[s]Per favore, lasciatemi stare.[n]In cambio, non vi[n]chieder韻 nulla.[n][w][e]
[s]Lasciatemi solo vedere la fine[n]del mondo in pace...[n][w][e]

[msg D08_01_NPC_TALK_23_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2113 65535 0]Sono curiosa di scoprire perch姻[n]tutti credono che il mondo[n]stia per finire.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che vorranno dire?[n][w][e]

[msg D08_01_NPC_TALK_24_mes01 [Uomo d'affari stanco]]
[s]Di chi 因 la colpa dei problemi[n]che assillano il mondo?[n][w][e]
[s]Mi sento male solo a pensarci.[n]Tutto quello che posso fare[n]ora 因 ignorarli.[n][w][e]

[msg D08_01_NPC_TALK_24_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Che mucchio di stronzate. Ehi![n]Il mondo non migliorer稲[n]da solo, te ne rendi conto?[n][w][e]

[msg D08_01_NPC_TALK_25_mes01 [Ragazzo timido]]
[s]為 meglio non puntare a niente[n]nella vita...[n][w][e]
[s]Se provassi a ottenere qualcosa,[n]potrei perdere quello che ho.[n][w][e]
[s]Ho paura che succeda. Penso[n]che rester韻 per sempre cos淫...[n][w][e]

[msg D08_01_NPC_TALK_25_mes02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6187 65535 0]Dovrebbe essere la tua situazione[n]attuale a spaventarti![n][w][e]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come fa ad andargli bene...?!?[n][w][e]

