[msg D08_01_NPC_TALK_16_mes01 [Uomo di mezza et稲 cinico]]
[s]Perch姻 avete quelle[n]espressioni cos淫 compiaciute?[n]Non mi piacciono...[n][w][e]
[s]Fate gli arroganti solo perch姻[n]vivete in una zona sicura, lontani[n]da qualsiasi possibile fallimento.[n][w][e]
[s]Che sapore ha la verit稲?[n]Siete sollevati di aver capito[n]che mentite a voi stessi?[n][w][e]
[s]Non capisco proprio quella[n]che chiamate "felicit稲".[n][w][e]
[s]Ma non importa. Ognuno[n]ha il suo modo di raggiungerla.[n][w][e]
[s]A ogni modo, non diteci cosa[n]dobbiamo fare. Questo 因 il nostro[n]modo di raggiungere la felicit稲.[n][w][e]
[s]Non m'importa cosa ne[n]pensiate voi. Non ho motivo di[n]ascoltare le vostre lamentele![n][w][e]

[msg D08_01_NPC_TALK_16_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4028 65535 0]Mmm... se credi a quelle cose,[n]allora sei davvero libero[n]di fare come vuoi.[n][w][e]

[msg D08_01_NPC_TALK_17_mes01 [Donna poco amichevole]]
[s]I Ladri Fantasma? Non me[n]ne importa niente.[n][w][e]
[s]為 stato un bello scherzo finch姻 因[n]durato, ma 因 roba vecchia. Ditemi[n]qualcosa di pi迂 emozionante.[n][w][e]

[msg D08_01_NPC_TALK_17_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Uno scherzo?!? Stronzate![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sai che 因 morta della gente[n]a causa di quegli arresti[n]mentali, vero?!?[n][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci hai mai pensato?!?[n][w][e]

[msg D08_01_NPC_TALK_18_mes01 [Ragazzo assente]]
[s]Politica? Che senso avrebbe[n]interessarsene adesso?[n]Non cambierebbe nulla...[n][w][e]
[s]Preferisco pensare a me stesso[n]finch姻 sono in tempo...[n][w][e]

[msg D08_01_NPC_TALK_18_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]Non si pu韻 "pensare a se stessi"[n]quando si 因 in cella.[n]Perch姻 fanno cos淫?[n][w][e]

[msg D08_01_NPC_TALK_19_mes01 [Donna cinica]]
[s]Non fate niente di superfluo.[n]Sar稲 un finale bellissimo[n]per il nostro mondo...[n][w][e]

[msg D08_01_NPC_TALK_19_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4025 65535 0]Come pu韻 giudicare la bellezza[n]chi 因 incapace di aprire gli occhi?[n][w][e]

[msg D08_01_NPC_TALK_20_mes01 [Ragazzo rassegnato]]
[s]La realt稲 sta per finire, vero?[n]Non ha senso darsi da fare.[n][w][e]
[s]E i miei sogni? Devo solo[n]accettare il fatto che non si[n]realizzeranno. La vita 因 crudele.[n][w][e]

[msg D08_01_NPC_TALK_20_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4169 65535 0]"La realt稲 sta per finire"?[n][w][e]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anche gli altri rinchiusi in[n]prigione dicono cose simili.[n]Cosa significher稲 mai?[n][w][e]

