[msg D08_01_e446_053_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7176 65535 0]為 il fondo?[n][w][e]

[msg D08_01_e446_053_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'esserlo. Andiamo.[n][w][e]

[msg D08_01_NPC_TALK_26_mes01 [Uomo dall'aria assonnata]]
[s]Sta per arrivare la fine di tutto.[n]I miei desideri saranno esauditi.[n][w][e]

[msg D08_01_NPC_TALK_27_mes01 [Donna allegra]]
[s]Tra poco... Tra poco i miei sogni[n]diventeranno realt稲...[n][w][e]

[msg D08_01_NPC_TALK_28_mes01 [Ragazzo ostile]]
[s]Voi siete... i Ladri Fantasma?[n][w][e]
[s]Che ci fate qui?!?[n]Gi迂 le mani![n][w][e]

[msg D08_01_NPC_TALK_29_mes01 [Uomo soddisfatto]]
[s]Aaah... finch姻 ho questo,[n]non ho bisogno d'altro...[n][w][e]

[msg D08_01_NPC_TALK_30_mes01 [Ragazzo allegro]]
[s]Ti prego, salvaci tutti...[n]Trasforma i nostri sogni in realt稲.[n][w][e]

[msg D08_01_NPC_TALK_31_mes01 [Giovane indolente]]
[s]Esaudir稲 i nostri desideri.[n]Saremo liberi da tutto...[n][w][e]

[msg D08_01_NPC_TALK_32_mes01 [Uomo estasiato]]
[s]Ti prego, dammi quello che voglio.[n]Metti fine a tutto...[n][w][e]

[msg D08_01_NPC_TALK_33_mes01 [Ragazzo esausto]]
[s]Ah, il mio desiderio[n]sta per avverarsi. Finalmente[n]sar韻 felice...[n][w][e]

[msg TEST]
[s]Dummy[n][w][e]

