[msg D08_01_NPC_TALK_13_mes01 [Donna sorridente]]
[s]Non possiamo cambiare il mondo.[n]Tutti la pensano cos淫...[n][w][e]
[s]Perch姻 non vi unite a noi?[n]Il mondo finir稲 presto,[n]quindi potete anche farlo...[n][w][e]

[msg D08_01_NPC_TALK_13_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3111 65535 0]Come mai queste persone[n]hanno cominciato a pensare[n]che in prigione si vive bene?[n][w][e]

[msg D08_01_NPC_TALK_14_mes01 [Studente negato]]
[s]Solo gli idioti si impegnano[n]per realizzare i[n]loro sogni...[n][w][e]
[s]Qui, qualsiasi desiderio pu韻[n]diventare realt稲. Non 因 questo[n]che tutti desiderano?[n][w][e]

[msg D08_01_NPC_TALK_14_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Questa gente pensa davvero che i [n]suoi desideri si avvereranno?[n][w][e]

[msg D08_01_NPC_TALK_15_mes01 [Uomo di mezza et稲 rassegnato]]
[s]Ehi, 因 meglio se state attenti.[n]Qui non ci siamo solo noi.[n][w][e]
[s]Dicono che ci sia un posto[n]riservato alle persone pi迂[n]malvagie in assoluto...[n][w][e]

[msg D08_01_NPC_TALK_15_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]Intende la Cella di Quarantena[n]di cui abbiamo sentito parlare?[n][w][e]

[msg D161_06_DUMMY_mes01]
[s](調整中)戦闘は飛ばします。[n][w][e]

