[msg dammy]
[s]Dummy?[n][w][e]

[msg D10_07_look_at_door_star [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]OK! Quindi dobbiamo passare[n]da dietro? Qualcuno ha idea[n]di che strada fare?[n][w][e]

[msg D10_07_look_at_door_mes0 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Nulla, oltre alle scale che[n]abbiamo appena preso...[n][w][e]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un momento! Ce ne sono altre[n]che portano al piano superiore![n][w][e]

[msg D10_07_look_at_door_end [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, c'因 anche una porta![n]Bel colpo, Noir.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]Diamoci una mossa![n][w][e]

