[msg D10_13_e_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Una volta superato questo[n]punto, non avremo altra[n]scelta che combattere Maruki.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Sei pronto, Joker?[n][w][e]

[sel D10_13_e_selA top]
[s]Prontissimo.[e]
[s]Non ancora.[e]

[msg D10_13_e_selA_0_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]D'accordo. Andiamo![n][w][e]

[msg D10_13_e_selA_1_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Giusto. Meglio fare attenzione.[n][w][e]

[msg D10_05_DestinationSugges [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un'altra sala video...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma sembra diversa, in[n]qualche modo.[n][w][e]

[msg D10_05_DestinationSugges_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che questa sia l'ultima[n]sala video.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pi迂 sopra c'因 il punto di[n]osservazione.[n][w][e]

[msg D10_05_DestinationSugges_3 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci siamo quasi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oracle, come si raggiunge[n]il punto di osservazione?[n][w][e]

[msg D10_05_DestinationSugges_4 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovrebbe esserci un ascensore[n]sul retro della sala video.[n][w][e]
[s]Sembra proprio che vi[n]serviranno altri biglietti.[n][w][e]

[msg D10_05_DestinationSugges_5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se c'因 un'altra sala video,[n]probabilmente ci toccher稲[n]sondare di nuovo il suo passato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non so se stia cercando[n]compassione o meno, ma[n]direi che 因 troppo tardi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Troviamo i biglietti alla svelta[n]e facciamola finita.[n][w][e]

[msg D162_005_mini_EV_01_mes_ [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmh? L'ascensore 因 andato gi迂.[n][w][e]

[msg D162_005_mini_EV_01_mes__2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma l'abbiamo appena fatto[n]salire quass迂.[n][w][e]

[msg D162_005_mini_EV_01_mes0 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Strano. Lo richiamiamo?[n][w][e]

[msg D162_005_mini_EV_01_mes__3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D'accordo, facciamo cos淫.[n][w][e]

[msg D162_005_BOSS_EV_Start [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, ora si spiega tutto.[n][w][e]

[msg D162_005_BOSS_EV_01 [Ricercatore Ombra]]
[s]Come siete arrivati fin qui?!?[n]Beh, non importa! Non ne[n]uscirete vivi![n][w][e]

[msg D162_005_BOSS_EV_02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, MADDAI![n][w][e]

[msg D162_005_BOSS_EV_End [Ricercatore Ombra]]
[s]Ti render韻 un membro dell'Eden![n][w][e]

