[msg dummy_mes]
[s]......[n][w][e]

[msg D10_02_HINT_mes01 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non vedo altri ingressi...[n][w][e]
[s]Dovremmo prendere in considerazione[n][clr 2]altri percorsi oltre alle porte[clr 27],[n]come il tetto o i comignoli...[n][w][e]

[msg D10_02_e484_080_mes01 [Voce di Kasumi]]
[s][vp 1 0 0 1 0 0]Chi 因 l稲?[n][w][e]

[msg D10_02_e484_080_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Era Yoshizawa!?![n][w][e]

[sel D10_02_e484_080_SEL top]
[s]Andiamo.[e]
[s]Sembra che si metta male.[e]

[msg D10_02_e484_080_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]S淫, ma stai in guardia![n][w][e]

[msg D10_02_IN_mes01 [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo 因 lo stesso posto[n]dell'anno scorso, vero?[n][w][e]

[msg D10_02_promnadedoor_mes_ [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 qui che 因 successo.[n][w][e]

[msg D10_02_promnadedoor_mes__2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il percorso di prova 因 chiuso,[n]ma l'auditorium 因 aperto...[n][w][e]

[msg D10_02_promnadedoor_mes__3 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]Secondo la piantina, l'auditorium[n]因 dietro quella porta...[n][w][e]

[msg D10_02_promnadedoor_mes__4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Poi entriamo nella porta a sinistra[n]e andiamo sempre dritti.[n][w][e]

[msg D10_02_promnadedoor_mes__5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ce la stanno mettendo tutta[n]per dirci che 因 aperto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]Maruki dovrebbe aspettarci l淫.[n]Andiamo a vedere.[n][w][e]

[msg D10_02_to_promnadedoor_l [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'essere quella la porta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8135 65535 0]A quanto pare la sala d'ingresso[n]因 al centro di diverse strade[n]che portano all'esterno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo.[n][w][e]

[msg D10_PaleceChangedReactio [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]C'因 un sacco di folla...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 decisamente tutto diverso dall'ultima[n]volta.[n][w][e]

[msg D10_PaleceChangedReactio_2 [Annuncio educato]]
[s]Grazie per essere venuti,[n]pazienti.[n][w][e]
[s]Sarete condotti a una delle nostre[n]strutture di cura specializzate in[n]base ai vostri desideri personali.[n][w][e]

[msg D10_PaleceChangedReactio_3 [Annuncio educato]]
[s]Assisteremo ciascuno di voi.[n][w][e]
[s]Tranquilli. Tutti possono essere[n]felici.[n][w][e]

[msg D10_PaleceChangedReactio_4 [Annuncio educato]]
[s]Qualora aveste delle domande sulle strutture[n]rivolgetevi a un vicino membro dello staff.[n][w][e]

[msg D10_PaleceChangedReactio_5 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57113 65535 0]Che strano annuncio.[n]"Diventare felici"?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che tipo di posto 因?[n][w][e]

[msg D10_02_AuditoriumGuide_m [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Credo che fosse da queste parti.[n][w][e]

[msg D10_02_AuditoriumGuide_m_2 [Annuncio educato]]
[s]Pazienti VIP identificati.[n]Ora inizieremo la visita.[n][w][e]

[msg D10_02_AuditoriumGuide_m_3 [Annuncio educato]]
[s]L'Auditorium 因 ora aperto.[n][w][e]
[s]Il padrone vi attende l稲... con[n]il paziente che cercate.[n][w][e]

[msg D10_02_AuditoriumGuide_m_4 [Annuncio educato]]
[s]Siete pregati di entrare dalla porta[n]sul lato sinistro della sala[n]d'ingresso.[n][w][e]

[msg D10_02_AuditoriumGuide_m_5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Come pensavo. Ci informa[n]educatamente della loro posizione.[n][w][e]

[msg D10_02_AuditoriumGuide_m_6 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'essere quella la porta.[n]Andiamo.[n][w][e]

[msg D10_02_sumireReaction_me [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Rispetto all'ultima volta[n]c'因 qualcosa di diverso...[n][w][e]

[msg D10_02_sumireReaction_me_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]為 successo qualche mese fa, no? Dovrebbe[n]esserci stato un risveglio del cuore da allora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricordi quanto tempo 因 passato[n]dall'ultima volta che ti trovavi qui?[n][w][e]

[msg D10_02_sumireReaction_me_3 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Credo fosse dietro quella porta.[n]為 dove mi ha aiutato.[n][w][e]

[msg D10_02_sumireReaction_me_4 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Capisco, quindi conosci solo la zona[n]vicino all'entrata.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]Proseguiamo.[n][w][e]

[msg D10_02_posterSession_1st [[sumi 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57135 65535 0]Che vuol dire? Non ne capisco[n]neanche una parola...[n][w][e]

[msg D10_02_posterSession_1st_2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra il resoconto di una ricerca.[n][w][e]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Scommetto che tu puoi riuscire[n]a decifrarlo, Joker![n][w][e]

[msg D10_02_posterSession_1st_3 [[sumi 10 0]]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Strano. Questo poster 因 fuori[n]posto... E perch姻 il Palazzo 因[n]pieno di gente?[n][w][e]

[msg D10_02_posterSession_1st_4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa gente esiste solo nella[n]cognizione del signore del Palazzo.[n]Sono come bambole, diciamo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻 non sappiamo ancora come[n]il signore percepisca le cose che[n]ne provocherebbero la comparsa.[n][w][e]

[msg D10_02_posterSession_1st_5 [[sumi 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57119 65535 0]Bambole, eh? Non l'avrei[n]mai detto. Sembrano vere.[n][w][e]

[msg D10_02_posterSession_1st_6 [Akechi]]
[s][bup 0 9 802 0 0][vp 8 2 1 54502 65535 0]......[n][w][e]

[msg D10_02_posterSession_1st_7 [[sumi 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Akechi-san?[n][w][e]

[msg D10_02_posterSession_1st_8 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]...Niente. E visto che 因 inutile[n]stare qui, dovremmo andare.[n][w][e]

[msg D10_02_posterSession_2nd [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Ha tutta l'aria di una ricerca sulla[n]scienza psi-cognitiva.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maruki sembra molto[n]interessato all'argomento...[n][w][e]

[msg D10_02_posterSession_3rd [Ryuji]]
[s][bup 0 2 3 65535 0][vp 8 2 1 7085 65535 0]......[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi Panther, ti dice qualcosa?[n][w][e]

[msg D10_02_posterSession_3rd_2 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No. Neanche un po'.[n][w][e]

[msg D10_02_posterSession_3rd_3 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]Lo stesso vale per me.[n][w][e]

[msg D10_02_posterSession_3rd_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4156 65535 0]Il pubblico che viene a conoscenza[n]delle sue ricerche... Su cosa si[n]basa questa cognizione?[n][w][e]

[msg D10_02_posterSession_3rd_5 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Le sue scoperte non sono ancora[n]del tutto pronte per il mondo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra quasi convinto che la massa[n]debba avere accesso alle sue[n]ricerche.[n][w][e]

[msg D10_02_posterSession_3rd_6 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]Sembrano informazioni generiche,[n]per le persone comuni. Sarebbe poco[n]anche per una gara di scienze.[n][w][e]

[msg D10_02_posterSession_3rd_7 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, io non capisco una parola.[n]Avrebbe dovuto scrivere[n]in hiragana...[n][w][e]

[msg D10_02_posterSession_3rd_8 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3192 65535 0]Non penso che l'abbia reso[n]pi迂 comprensibile.[n][w][e]

