[msg dammy]
[s]Dummy?[n][w][e]

[msg D10_03_look_at_researche [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi! Guarda quell'Ombra.[n][w][e]

[msg D10_10_CardCheck_denied [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non otterrai niente di utile[n]analizzando quella cosa.[n][w][e]

[msg D10_10_CardCheck_First_S [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Sembra una specie di[n]dispositivo di identificazione.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci serve l'ID corretto per[n]procedere.[n][w][e]

[msg D10_10_CardCheck_First_E [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non dobbiamo andare da quella parte.[n]Lasciamo stare, per ora.[n][w][e]

[msg D10_03_look_at_researche_2 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]C'因 quell'Ombra. Interveniamo?[n][w][e]

[sel D10_03_look_at_researche_3 top]
[s]Facciamolo.[e]
[s]Non ancora.[e]

[msg D10_03_look_at_researche_4 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57186 65535 0]OK. Fammi sapere quando sei libero.[n][w][e]

[msg D10_03_look_at_researche_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un momento! Sta parlando[n]con un'altra Ombra.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9089 65535 0]Dovrei essere in grado di ottenere qualche[n]informazione utile.[n][w][e]

[msg D10_03_look_at_researche_6 [Agente]]
[s]Torna al tuo posto. Dovresti essere[n]nella stanza di osservazione.[n][w][e]
[s]Segui il piano. Non[n]agire di testa tua.[n][w][e]

[msg D10_03_look_at_researche_7 [Guardia]]
[s]Sto solo cercando di eliminare[n]potenziali minacce per il padrone.[n][w][e]
[s]Ma immagino sia meglio evitare di[n]portare il tesserino con me, da[n]queste parti. OK. Torno in posizione.[n][w][e]

[msg D10_03_look_at_researche_8 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9040 65535 0]Cos..!? Scusa, Joker...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quell'Ombra sta per andare via![n]Prendetelo! Veloci! Via, via, via![n][w][e]

[msg D10_03_look_at_researche_9 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]Che dici, Joker-senpai?[n][w][e]

[msg D10_03_researcher_battle [Guardia]]
[s]Cosa? I Ladri Fantasma![n]Devono avermi seguito![n][w][e]

[msg D10_03_researcher_battle_2 [Agente]]
[s]Maledizione! Te l'avevo detto![n]Ora dobbiamo eliminarli![n]Per il padroneee![n][w][e]

[msg D10_03_researcher_battle_3 [Guardia]]
[s]Volete il mio tesserino, eh? Beh,[n]dovrete guadagnarvelo![n][w][e]

[msg D10_03_researcher_battle_4]
[s]Non ti permetter韻 di sfruttare di nuovo[n]la ricerca del Dottor Maruki! Hai finito![n][w][e]

[msg D10_03_researcher_battle_5 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Arrivano![n][w][e]

[msg D10_03_ID_Door_Open01 [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57051 65535 0]S淫, adesso si 因 aperta![n][w][e]

[msg D10_03_ID_Door_Open02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non abbiamo visto cosa[n]c'因 dietro questa porta...[n][w][e]
[s]Quello scanner dev'essere qui per[n]un motivo. Da qui la sorveglianza[n]potrebbe essere pi迂 rigida.[n][w][e]
[s]Fai attenzione, l稲 fuori.[n]OK, Violet?[n][w][e]

[msg D10_03_ID_Door_Open03 [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]Oh! Ah, s淫, Mona-senpai![n][w][e]

[msg D10_10_CardCheck_Second_ [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che succede, senpai?[n][w][e]

[msg D10_10_CardCheck_Second__2 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra proprio che non si aprir稲...[n]Continuiamo a cercare.[n][w][e]

[msg D10_10_CardCheck_Party01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9127 65535 0]...Ho dato un'occhiata, ma sembra[n]fatto in modo da garantire[n]l'accesso solo da qui.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Serve un ID per la porta.[n][w][e]

[msg D10_10_CardCheck_Party01_2 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]Con una serratura simile, deve[n]nascondere qualcosa di importante![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo a cercare un ID![n][w][e]

[msg D10_10_CardCheck_Party01_3 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Ma prima ci serve un indizio...[n][w][e]

[msg D10_10_CardCheck_Party01_4 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]Oh! Guarda![n][w][e]

[msg D10_10_CardCheck_Party02 [Guardia]]
[s]S淫, l'imboscata 因 fallita. Ora[n]stanno esaminando il[n]dispositivo di autenticazione.[n][w][e]
[s]Senza tesserino non andranno[n]da nessuna parte, per韻.[n][w][e]
[s]Questa per loro 因 la fine.[n][w][e]

[msg D10_10_CardCheck_Party03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, Oracle![n][w][e]

[msg D10_10_CardCheck_Party03_2 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9089 65535 0]Ho intercettato la conversazione[n]di alcune Ombre...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]La caccia al tesserino si 因[n]finalmente conclusa.[n]Quell'Ombra ne ha uno.[n][w][e]

[msg D10_10_CardCheck_Party03_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7022 65535 0]Stai ficcando il nas... ehm,[n]voglio dire, la tua tecnica ci[n]因 tornata utile ancora una volta.[n][w][e]

[msg D10_10_CardCheck_Party03_4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Non ho nemmeno visto quell'Ombra.[n][w][e]

[msg D10_10_CardCheck_Party03_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9081 65535 0]Dubito che sappia che ho sentito.[n]Gli tendiamo un'imboscata[n]per prendere il tesserino?[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Da qui non potete raggiungerlo,[n]per韻. Dovete fare il giro da[n]dietro e attraversare l'auditorium.[n][w][e]

[msg D10_10_CardCheck_Party03_6 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57186 65535 0]Capito. Dobbiamo occuparcene noi.[n]Andiamo![n][w][e]

[msg D10_10_CardChecked_Party [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Passiamo dall'auditorium.[n][w][e]

[msg D10_10_CardChecked_Party_2 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra proprio che non si aprir稲...[n]Continuiamo a cercare.[n][w][e]

