[msg D10_09_gimmick_start [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4192 65535 0]Che cambio di ambiente.[n]Dove ci troviamo adesso?[n][w][e]

[msg D10_09_gimmick_01 [Receptionist Ombra]]
[s]Questa 因 la sala esami psicologici.[n][w][e]
[s]Conduciamo test psicologici[n]per offrire ai pazienti la[n]loro realt稲 ideale.[n][w][e]
[s]Se siete interessati, seguite il[n]corridoio e attraversate la porta per[n]accedere al pannello informativo.[n][w][e]

[msg D10_09_gimmick_02 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Una sala esami?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Come una sala per esami clinici?[n][w][e]

[msg D10_09_gimmick_03 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse. Che posto bizzarro.[n][w][e]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3192 65535 0]Qui le Ombre non ci attaccano.[n]Non vogliono fermarci?[n][w][e]

[msg D10_09_gimmick_end [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sembrano ostili, stranamente.[n]Inoltre, sono curioso di vedere[n]cosa prevede questo "esame".[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, forse possiamo parlare[n]alle Ombre per ottenere qualche[n]informazione utile.[n][w][e]

[msg D10_09_1st_announcement_ [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Quel receptionist ci ha detto di[n]cominciare dal pannello informativo...[n][w][e]

[msg D10_09_1st_announcement__2 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, 因 quello?[n][w][e]

[msg D10_09_1st_announcement__3 [Interfaccia elettronica di aiuto]]
[s]Rilevati nuovi pazienti nella[n]stanza. La descrizione dell'esame[n]sta per iniziare.  [n][w][e]
[s]Per iniziare, accedi al pannello informativo[n]di fronte a te.[n][w][e]
[s]A questo punto, vi troverete di[n]fronte a una situazione in cui[n]dovrete prendere una decisione.[n][w][e]
[s]Per fornire la risposta,[n]usate l'ascensore associato[n]alla lettera corrispondente.[n][w][e]

[msg D10_09_1st_announcement__4 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi, per rispondere a[n]un questionario dobbiamo[n]usare l'ascensore?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi sembra un po' troppo per un[n]esame. Cosa c'因 sotto?[n][w][e]

[msg D10_09_1st_announcement__5 [Interfaccia elettronica di aiuto]]
[s]Arrivati al piano superiore,[n]verrete condotti al trattamento[n]stabilito in base alla risposta.[n][w][e]
[s]L'intero processo 因 progettato[n]per il bene del paziente. Non c'因[n]nulla di cui preoccuparsi.[n][w][e]

[msg D10_09_1st_announcement__6 [Akechi]]
[s][bup 0 9 802 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi qui 因 dove identificano le[n]anomalie cognitive che vanno[n]modificate...  [n][w][e]

[msg D10_09_1st_announcement__7 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Sul serio?!? Non voglio[n]che facciano altri casini[n]nella mia testa![n][w][e]

[msg D10_09_1st_announcement__8 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Immagino che non abbiamo alternative.[n][w][e]

[msg D10_09_1st_question_chec [Voce amichevole]]
[s]Ciao pazienti! Ecco la prima domanda:[n][w][e]
[s]Un giorno, a scuola, un vostro[n]amico viene portato via da[n]persone poco raccomandabili![n][w][e]
[s]Volete aiutare il vostro amico...[n][w][e]
[s]Ma affrontandole da soli e perdendo,[n]probabilmente vi fareste male.[n][w][e]
[s]Andando a chiamare un[n]insegnante, non correreste[n]alcun rischio...[n][w][e]
[s]Ma se faceste troppo tardi,[n]potrebbe succedere qualcosa[n]di brutto al vostro amico.[n][w][e]
[s]Cosa fareste in questa situazione?[n][w][e]
[s]A: Andate dal vostro amico.[n]B: Andate a cercare aiuto.[n][w][e]
[s]Una volta presa la decisione,[n]prendete l'ascensore corrispondente![n]Grazie![n][w][e]

[msg D10_09_1st_question_chec_2 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]Eh? Non ci sono risposte[n]sbagliate, per韻...[n][w][e]

[msg D10_09_1st_question_chec_3 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, ma questo 因 un esame medico,[n]non scolastico. Cercano di capire[n]se sono necessarie delle terapie.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi, dovremmo puntare[n]sulle risposte che sceglierebbe[n]il dottor Maruki?[n][w][e]

[msg D10_09_1st_question_chec_4 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6166 65535 0]Quindi dobbiamo cercare di immaginare[n]cosa avrebbe fatto il dottor Maruki?[n]Oooh, sar稲 difficile...[n][w][e]

[msg D10_09_1st_question_chec_5 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In questo momento 因 difficile essere[n]sicuri di qualunque cosa...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non chiediamo a qualcuno[n]di questi pazienti?  [n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sono solo creature cognitive, ma[n]devono affrontare l'esame[n]esattamente come noi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse possono aiutarci[n]a capire qual 因 la[n]risposta giusta.[n][w][e]

[msg D10_09_1st_question_chec_6 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9035 65535 0]Sono d'accordo con Mona. Inoltre,[n]se fallissimo, almeno potremmo[n]dire di averci provato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sono contraria[n]all'idea di farci strada[n]con la forza, ma...  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Rifiutando il loro regime[n]terapeutico, qualunque esso sia,[n]dubito che resteranno a guardare.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In breve: state pronti se[n]le cose dovessero mettersi male!  [n][w][e]

[msg D10_09_second_display_lo [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ce l'abbiamo fatta. Sembra per韻[n]che la seconda domanda abbia[n]tre possibili risposte. [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53501 65535 0]Scopriamo con che cosa abbiamo a[n]che fare questa volta.[n][w][e]

[msg D10_09_2nd_question_chec [Voce amichevole]]
[s]為 bello rivedervi! Ecco[n]la seconda domanda:[n][w][e]
[s]Desiderate ardentemente che un[n]vostro sogno si avveri.[n][w][e]
[s]Avete lavorato duro per questo...[n][w][e]
[s]Ma i risultati non arrivano.[n][w][e]
[s]Ci韻 vi causa profonda sofferenza,[n]ma se vi arrendeste, il vostro[n]duro lavoro andrebbe sprecato![n][w][e]
[s]Cosa fareste in questa situazione?[n][w][e]
[s]A: Continuate cos淫.[n][w][e]
[s]B: Ce la mettete tutta.[n][w][e]
[s]C: Lasciate stare e trovate un nuovo sogno.[n][w][e]
[s]Pensando alla risposta, siate[n]onesti con i vostri sentimenti.[n]Grazie![n][w][e]

[msg D10_09_2nd_question_chec_2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]Mmm... non ne sappiamo[n]abbastanza per decidere.[n]Dobbiamo raccogliere informazioni.[n][w][e]

[msg D10_09_2nd_question_chec_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ok. Facciamo un giro e parliamo con[n]questi tizi come l'ultima volta.[n][w][e]

[msg D10_09_Third_display_loo [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Uno, due, tre, quattro... Caspita,[n]abbiamo CINQUE opzioni stavolta?[n][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merda, ho il cervello fuso...[n]Perch姻 non prendiamo un ascensore[n]a caso e la facciamo finita?[n][w][e]

[msg D10_09_Third_display_loo_2 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Capisco come ti senti, ma non possiamo[n]arrenderci senza aver provato.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dai, vediamo qual 因 la domanda.[n][w][e]

[msg D10_09_3rd_question_chec [Voce amichevole]]
[s]Rieccovi nuovamente! Passiamo[n]alla terza domanda.[n][w][e]
[s]Avete ottenuto il potere di[n]rubare i cuori![n][w][e]
[s]Pensieri, emozioni, informazioni...[n]Potete rubare tutto questo a[n]chiunque, in ogni parte del mondo![n][w][e]
[s]Non solo, potete usare questo[n]potere senza mai rischiare di[n]essere scoperti![n][w][e]
[s]In questo scenario, quale[n]opzione 因 pi迂 vicina[n]al vostro pensiero?[n][w][e]
[s]A: Rubare qualcosa di valore.[n]B: Non rubare nulla.[n][w][e]
[s]C: Rubare il mio cuore per guarire.[n]D: Rubare il cuore ai cattivi[n]per una societ稲 migliore.[n][w][e]
[s]E: Rubare il cuore di chi amo.[n][w][e]
[s]Seguite la solita procedura per[n]rispondere alla domanda. Grazie![n][w][e]

[msg D10_09_3rd_question_chec_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]Ma che...? Questa domanda ci riguarda?[n][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, 因 ovvio che 因 la D![n]Muoviamoci.[n][w][e]

[msg D10_09_3rd_question_chec_3 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cerca di USARE il cervello![n]Non stai nemmeno provando![n][w][e]

[msg D10_09_3rd_question_chec_4 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Dunque, le condizioni sono che[n]non verremo scoperti e che possiamo[n]usare quest'abilit稲 in un solo modo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ricordiamole, mentre[n]valutiamo la risposta.[n][w][e]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54503 65535 0]Sempre che tu abbia una testa...[n][w][e]

[msg D10_09_3rd_question_chec_5 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi! Non prendertela con Mona![n][w][e]

[msg D10_09_3rd_question_chec_6 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1139 65535 0]S淫, grazie, ma uh, non credo[n]di essere l'oggetto degli insulti...[n][w][e]

[msg D10_FindGate_start [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6039 65535 0]Ma che... Stanno passando[n]attraverso quello strano muro...[n]Che roba 因?!?[n][w][e]

[msg D10_FindGate_01 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wooow, com'因 futuristico![n][w][e]

[msg D10_FindGate_01_insert01 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, se avessimo fallito l'esame[n]psicologico, saremmo stati[n]sottoposti alla "terapia"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Immagino che ci abbiano mandati[n]qui perch姻 le nostre risposte[n]erano soddisfacenti.  [n][w][e]

[sel D10_09_FindGate_SEL top]
[s]Entriamo.[e]
[s]Proviamoci.[e]

[msg D10_FindGate_01_insert02 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]Uh, OK, ma... fa' attenzione.[n][w][e]

[msg D10_FindGate_02 [Interfaccia elettronica]]
[s]Rilevato tracciato anomalo[n]di onde cerebrali.[n][w][e]
[s]Accesso negato. Per ulteriori[n]istruzioni, rivolgersi alla[n]sala di supporto.[n][w][e]

[msg D10_FindGate_03 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cosa?!? Chi hai chiamato[n]"anomalo"?!? Abbiamo superato[n]il tuo esame del cavolo!  [n][w][e]

[msg D10_FindGate_04 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tuttavia... non avete risposto[n]con onest稲.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dato che siamo qui per fermare[n]Maruki, ci considereranno[n]di certo anomali.[n][w][e]

[msg D10_FindGate_end [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7113 65535 0]Ma questo significa che[n]di qui non si passa proprio![n][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Argh, maledizione! Trover韻[n]un modo per passare,[n]anche a costo della vita![n][w][e]

[msg D10_09_gimmick_end_start [Interfaccia elettronica]]
[s]Grazie per la pazienza.[n]Adesso il vostro esame 因 completo.[n][w][e]
[s]Raggiungete la sala di supporto[n]per ottenere la vostra[n]realt稲 ideale.[n][w][e]

[msg D10_09_gimmick_end_01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7190 65535 0]Huh. Abbiamo sbagliato, comunque sia[n]continuiamo...[n][w][e]

[msg D10_09_gimmick_end_end [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Secondo l'annuncio, la[n]sala terapia 因 pi迂 avanti...[n][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ho una brutta sensazione...[n][w][e]

[msg D10_09_question_ans_A [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi prendere l'ascensore [clr 2]A[clr 27]?[n][w][e]

[msg D10_09_question_ans_B [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi prendere l'ascensore [clr 2]B[clr 27]?[n][w][e]

[msg D10_09_question_ans_C [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi prendere l'ascensore [clr 2]C[clr 27]?[n][w][e]

[msg D10_09_question_ans_wron [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Sai che 因 la risposta[n]sbagliata, no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi davvero prendere l'ascensore [clr 2]C[clr 27]?[n][w][e]

[msg D10_09_question_ans_D [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi prendere l'ascensore [clr 2]D[clr 27]?[n][w][e]

[msg D10_09_question_ans_E [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Vuoi prendere l'ascensore [clr 2]E[clr 27]?[n][w][e]

[msg D10_09_question_ans_wron_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Sai che 因 la risposta[n]sbagliata, no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi davvero prendere l'ascensore [clr 2]E[clr 27]?[n][w][e]

[sel D10_09_question_ans_SEL top]
[s]S淫, questo.[e]
[s]Fammici pensare.[e]

[msg D10_09_question_ans_afte [Voce amichevole]]
[s]Conferma della risposta del[n]paziente: sei sicuro?[n][w][e]
[s]Capito. Da questa parte...[n][w][e]

[msg D10_09_question_ans_afte_2 [Voce amichevole]]
[s]Conferma della risposta del[n]paziente: 因 davvero ci韻 che vuoi?[n][w][e]
[s]Capito. Da questa parte...[n][w][e]

[msg D10_09_question_ans_afte_3 [Voce amichevole]]
[s]Conferma della risposta del[n]paziente! Uhmmm, capisco...[n][w][e]
[s]Capito. Da questa parte...[n][w][e]

[msg D10_09_research_not_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1192 65535 0]Non abbiamo imparato abbastanza da[n]prendere una decisione consapevole.[n]Perch姻 non chiediamo alla gente qui attorno?[n][w][e]

[msg D10_09_after_answer01_st [Interfaccia elettronica]]
[s]Non sono state riscontrate[n]anomalie nella risposta.[n]Continuate alla prossima stanza.[n][w][e]

[msg D10_09_after_answer01_01 [Uomo riservato]]
[s]Oh, anche tu, eh...?[n][w][e]
[s]Lo chiamano esame, ma[n]non stiamo facendo altro che[n]camminare lungo un percorso.  [n][w][e]

[msg D10_09_after_answer01_02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Per il momento va tutto bene...[n]Forse era davvero la[n]risposta giusta.[n][w][e]

[msg D10_09_after_answer01_03 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi 因 meglio non farsi[n]coinvolgere invece di dare una[n]mano? Non mi convince...[n][w][e]

[msg D10_09_after_answer01_03_2 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Forse significa che Maruki crede che[n]sia meglio trovare un modo[n]per non farsi male.[n][w][e]

[msg D10_09_after_answer01_04 [Uomo riservato]]
[s]Bello incontrarti qui...[n]Ecco, tieni.[n][w][e]
[s]Li hanno dati a tutti,[n]ma io ne ho ricevuti troppi.[n][w][e]

[msg D10_09_after_answer01_05 [Uomo riservato]]
[s]Sembra che dobbiamo ancora finire[n]l'esame. Con permesso...[n][w][e]

[msg D10_09_after_answer01_en [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Gente, continuiamo cos淫![n][w][e]

[msg D10_09_after_mistake01_s [Ombra con camice]]
[s]Rischiare per aiutare gli altri[n]因 lodevole, ma si possono[n]subire delle ferite.[n][w][e]
[s]Nella realt稲 ideale le ferite[n]non sono consentite, ma non[n]abbiate paura. Sarete felici.[n][w][e]
[s]Seguitemi nella sala di supporto.[n]Cambieremo il vostro modo di pensare[n]per farvi vivere in paradiso.[n][w][e]

[msg D10_09_after_mistake01_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1046 65535 0]Un'Ombra!? Significa che...[n][w][e]

[msg D10_09_after_mistake01_0_2 [Ombra con camice]]
[s]Oh, eccoti![n][w][e]
[s]Capisco... "Riscontrate anomalie".[n]Idee tanto pericolose[n]meritano una terapia adeguata.[n][w][e]

[msg D10_09_after_mistake01_0_3 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hai sentito? Ti interessa un[n]"adeguato trattamento"?[n][w][e]

[msg D10_09_after_mistake01_e [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]No! Non c'因 tempo da perdere...[n][w][e]

[msg D10_09_after_answer02_st [Interfaccia elettronica]]
[s]Non sono state riscontrate[n]anomalie nella risposta.[n]Continuate alla prossima stanza.[n][w][e]

[msg D10_09_after_answer02_01 [[sumi 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]Forse avevamo ragione, ma...[n]Non so cosa pensare.[n][w][e]

[msg D10_09_after_answer02_02 [Studente razionale]]
[s]Oh, anche voi, eh? Non ha[n]senso prendere queste cose[n]troppo sul serio, giusto?[n][w][e]

[msg D10_09_after_answer02_03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non 因 come credi. Volevamo solo[n]evitare la risposta sbagliata.[n][w][e]

[msg D10_09_after_answer02_04 [Studente razionale]]
[s]Che significa "risposta sbagliata"?[n]Non ci sono risposte sbagliate qui.[n][w][e]
[s]Non ci pensate troppo. Sembra[n]che questi qui sappiano[n]il fatto loro.[n][w][e]
[s]Ooh! Aspetta, lascia che ti dia questo prima[n]di andare.[n][w][e]

[msg D10_09_after_answer02_05 [Studente razionale]]
[s]Me l'hanno offerto un secondo fa,[n]ma non mi serve.[n][w][e]

[msg D10_09_after_answer02_06 [Studente razionale]]
[s]Ci si vede in giro, cosplay.[n][w][e]

[msg D10_09_after_answer02_07 [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il dottor Maruki pensa che le[n]persone debbano rinunciare[n]ai propri sogni?[n][w][e]

[msg D10_09_after_answer02_en [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Per essere precisi, pensa che le[n]persone non debbano soffrire[n]per concretizzare i propri sogni.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qualcosa del genere.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]L'esame 因 studiato per filtrare[n]le persone portate ad agire[n]in questo modo.[n][w][e]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Comunque, contemplare le domande[n]a cui abbiamo gi稲 dato risposta[n]因 solo una perdita di tempo.[n][w][e]

[msg D10_09_after_mistake02_0 [Ombra con camice]]
[s]Una simile dedizione[n]sarebbe stata lodevole...[n]in altre circostanze.[n][w][e]
[s]Se ci韻 che desiderate vi[n]spezza il cuore... 因 un sogno che[n]non merita di essere coltivato.[n][w][e]
[s]Ma non c'因 niente di cui preoccuparsi.[n]Anche voi potete essere felici.[n][w][e]

[msg D10_09_after_mistake02_0_2 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Wow, 因 un'Ombra![n][w][e]

[msg D10_09_after_mistake02_0_3 [Ombra con camice]]
[s]Bene, sono arrivati i Ladri Fantasma.[n]Aspettiamoci qualche anomalia.[n][w][e]
[s]Permettetemi di scortarvi alle[n]vostre terapie. A meno che[n]non preferiate le maniere forti...[n][w][e]

[msg D10_09_after_mistake02_0_4 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7104 65535 0]Aiutami a dire "NO"![n]Toglilo di torno, Joker![n][w][e]

[msg D10_09_after_mistake02_0_5 [Ombra con camice]]
[s]Sareste felici, ma le vostre idee[n]diffonderebbero la sofferenza[n]tra coloro che vi circondano.[n][w][e]
[s]Nella realt稲 ideale 因 proibito.[n]Ma non abbiate paura.[n]Sarete felici.[n][w][e]

[msg D10_09_after_mistake02_0_6 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Merda, un'Ombra![n][w][e]

[msg D10_09_after_mistake02_0_7 [Ombra con camice]]
[s]Il padrone non permetter稲[n]ai vostri pensieri di turbare[n]i suoi poveri pazienti.  [n][w][e]
[s]Non se ne parla! Chi ha[n]pensieri tanto pericolosi[n]deve sottoporsi alla terapia![n][w][e]

[msg D10_09_after_mistake02_0_8 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Non sarebbe la soluzione migliore,[n]anche se vi permettesse di[n]realizzare il vostro sogno...  [n][w][e]

[msg D10_09_after_answer03_st [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Un'Ombra!? Significa che ci[n]siamo sbagliati?[n][w][e]

[msg D10_09_after_answer03_01 [Interfaccia elettronica]]
[s]Non sono state riscontrate[n]anomalie nella risposta.[n]Esame completato.[n][w][e]
[s]Abbiamo appurato che il vostro[n]cuore 因 integro. Continuate al[n]piano superiore.   [n][w][e]
[s]Godetevi la nuova realt稲 libera[n]da conflitti e preoccupazioni.[n][w][e]

[msg D10_09_after_answer03_02 [Usciere]]
[s]Congratulazioni, avete completato[n]l'esame! Siamo stati[n]avvisati dalla reception.[n][w][e]
[s]Nessuna anomalia nei[n]risultati... I vostri cuori sono[n]felici e appagati.[n][w][e]
[s]Benvenuti nella vostra nuova vita.[n][w][e]

[msg D10_09_after_answer03_03 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]A quanto pare siamo passati[n]senza che trovassero anomalie...[n]Che sollievo.[n][w][e]

[msg D10_09_after_answer03_04 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma, cosa intende, "completato"?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non si sono nemmeno accorti[n]che abbiamo scelto le risposte[n]che volevano![n][w][e]

[msg D10_09_after_answer03_03_2 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Chiudi il becco, Skull...![n][w][e]

[msg D10_09_after_answer03_03_3 [Usciere]]
[s]Come dono di benvenuto, permettetemi[n]di curare i vostri dolori.[n][w][e]
[s]Prego, accettate un piccolo[n]dono di gratitudine per aver[n]partecipato.[n][w][e]

[msg D10_09_after_answer03_05 [Usciere]]
[s]Ora, continuate verso il paradiso.[n]Oltre quel cancello.[n][w][e]

[msg D10_09_after_answer03_en [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Ottimo! 為 andata piuttosto bene.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continuiamo cos淫![n][w][e]

[msg D10_09_after_answer03_no [Interfaccia elettronica]]
[s]Non sono state riscontrate[n]anomalie nella risposta.[n]Esame completato.[n][w][e]
[s]Abbiamo appurato che il vostro[n]cuore 因 integro. Continuate al[n]piano superiore.   [n][w][e]
[s]Godetevi la vostra nuova[n]vita priva di conflitti[n]e preoccupazioni.[n][w][e]

[msg D10_09_after_answer03_no_2 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]A quanto pare siamo passati[n]senza che trovassero anomalie...[n]Che sollievo.[n][w][e]

[msg D10_09_after_answer03_no_3 [Uomo dall'aria sincera]]
[s]Quindi anche voi avete[n]sostenuto l'esame?[n][w][e]
[s]Mi fa piacere che[n]ci siamo riusciti.[n][w][e]

[msg D10_09_after_answer03_no_4 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]S-s淫, anch'io...[n][w][e]

[msg D10_09_after_answer03_no_5 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...Sebbene abbiamo fatto un po' un casino.[n][w][e]

[msg D10_09_after_answer03_no_6 [Uomo dall'aria sincera]]
[s]Ah, gi稲, ora che ci penso...[n][w][e]

[msg D10_09_after_answer03_no_7 [Uomo dall'aria sincera]]
[s]Non mi servir稲 pi迂,[n]prendilo tu.[n][w][e]

[msg D10_09_after_answer03_no_8 [Uomo dall'aria sincera]]
[s]Ciao. A presto, spero![n][w][e]

[msg D10_09_after_answer03_no_9 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1169 65535 0]Beh, abbiamo fatto qualche errore,[n]ma siamo riusciti a superarlo.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo.[n][w][e]

[msg D10_09_after_mistake03_0 [Ombra con camice]]
[s]Con le risorse adeguate i sogni[n]possono sbocciare. Senza denaro,[n]tuttavia, sono destinati a fallire.[n][w][e]
[s]Anche se il furto non vi mette in[n]pericolo, potrebbe infrangere[n]i sogni delle vittime.[n][w][e]
[s]Ma non c'因 niente di cui preoccuparsi.[n]Anche voi potete essere felici.[n][w][e]

[msg D10_09_after_mistake03_0_2 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4074 65535 0]Grrr... Un'Ombra![n][w][e]

[msg D10_09_after_mistake03_0_3 [Ombra con camice]]
[s]I Ladri Fantasma! Criminali che[n]rubano in nome della giustizia![n][w][e]
[s]Le vostre anomalie devono[n]essere rimosse attraverso le[n]terapie del padrone![n][w][e]

[msg D10_09_after_mistake03_0_4 [Ombra con camice]]
[s]Dite di essere felici... ma sar稲[n]vero? Non state forse sacrificando[n]ci韻 che siete davvero?[n][w][e]
[s]Non rinunciate cos淫 presto al[n]diritto di essere felici.[n]Permetteteci di rendervi liberi.[n][w][e]

[msg D10_09_after_mistake03_0_5 [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3041 65535 0]Un'Ombra...!? Oh, no...[n][w][e]

[msg D10_09_after_mistake03_0_6 [Ombra con camice]]
[s]Ladri Fantasma... Avete[n]forse intenzione di fare[n]del male al padrone?[n][w][e]
[s]Se il vostro cuore cela ancora[n]frammenti di disonest稲, li trover韻[n]e li eliminer韻![n][w][e]

[msg D10_09_after_mistake03_0_7 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6183 65535 0]Un'Ombra![n][w][e]

[msg D10_09_after_mistake03_0_8 [Ombra con camice]]
[s]Paziente successivo.[n][w][e]

[msg D10_09_after_mistake03_0_9 [Ombra con camice]]
[s]Bene, bene, bene... I Ladri Fantasma.[n][w][e]
[s]S淫, in voi c'因 qualcosa[n]di sbagliato. Dovete[n]sottoporvi alla terapia.[n][w][e]

[msg D10_09_after_mistake03_0_10 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6047 65535 0]Tsk, un'Ombra! Figuriamoci se[n]non ne incontravamo una![n][w][e]

[msg D10_09_after_mistake03_0_11 [Ombra con camice]]
[s]Paziente successivo.[n][w][e]

[msg D10_09_after_mistake03_0_12 [Ombra con camice]]
[s]Bene, bene, bene... I Ladri Fantasma.[n][w][e]
[s]S淫, in voi c'因 qualcosa[n]di sbagliato. Dovete[n]sottoporvi alla terapia.[n][w][e]

[msg D10_09_after_mistake03_0_13 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un'Ombra... pronti![n][w][e]

[msg D10_09_after_mistake03_0_14 [Ombra con camice]]
[s]Ah, il prossimo paziente...[n][w][e]

[msg D10_09_after_mistake03_0_15 [Ombra con camice]]
[s]Bene, sono arrivati i Ladri Fantasma.[n][w][e]
[s]Siete piuttosto famosi.[n]Risvegliate il cuore delle persone,[n]causate raptus...[n][w][e]
[s]Il cuore umano non 因 un giocattolo![n]Il vostro egoismo finisce qui![n][w][e]

[msg D10_09_after_mistake03_0_16 [Akechi]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54473 65535 0]Joker... Va tutto bene!?![n][w][e]

[msg D10_09_after_mistake03_0_17 [Ombra con camice]]
[s]Ah, il prossimo paziente...[n][w][e]

[msg D10_09_after_mistake03_0_18 [Ombra con camice]]
[s]Bene, sono arrivati i Ladri Fantasma.[n][w][e]
[s]Siete piuttosto famosi.[n]Risvegliate il cuore delle persone,[n]causate raptus...[n][w][e]
[s]Il cuore umano non 因 un giocattolo![n]Il vostro egoismo finisce qui![n][w][e]

[msg D10_09_hidden_room_first [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]Questo posto...[n][w][e]

[msg D10_09_hidden_room_first_2 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3040 65535 0]Guardate! Fuori dalla finestra![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qui 因 dove conduce l'ascensore, giusto?[n][w][e]

[msg D10_09_hidden_room_first_3 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La chiamano sala esami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54489 65535 0]Potrebbero monitorare molto bene[n]lo stato psicologico di ogni[n]"paziente" nella stanza.[n][w][e]

[msg D10_09_hidden_room_first_4 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi potrebbero averci osservato[n]per tutto questo tempo?!?[n]為 inquietante...[n][w][e]

[msg D10_09_hidden_room_first_5 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]"Inquietante" 因 la parola giusta...[n]Vorrei che ci fosse il modo di approfittarne...[n][w][e]

[msg D10_09_hidden_room_first_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2100 65535 0]In effetti, sembra che tengano[n]d'occhio tutti quelli che[n]affrontano l'esame.[n][w][e]

[msg D10_09_hidden_room_first_7 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eccone un altro...[n][w][e]

[msg D10_09_hidden_room_first_8 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Forse possiamo guardare il risultato.[n]Diamo un'occhiata.[n][w][e]

[msg D10_09_hidden_room_first_9 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ed eccone un altro ancora...[n][w][e]

[msg D10_09_hidden_room_first_10 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Dovremmo essere in grado di[n]restringere le opzioni. Vediamo[n]cosa possiamo scoprire.[n][w][e]

[msg D10_09_HiddenRoom01_Hint [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora 因 cos淫 che spiano[n]tutti in sala visite.[n][w][e]
[s]......[n][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Duuunque, ecco...[n]Vi state annoiando quanto me?[n][w][e]

[msg D10_09_HiddenRoom01_Hint_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In base a dove cerchiamo,[n]potremmo riuscire a scoprire[n]qualcosa di utile...[n][w][e]

[msg D10_09_HiddenRoom02_Hint [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1130 65535 0]Possiamo origliare qualche[n]conversazione.[n][w][e]

[msg D10_09_HiddenRoom02_Hint_2 [Donna depressa]]
[s]Non sono mai andata d'accordo con[n]mio marito. In realt稲 lo odiavo...[n][w][e]
[s]Ma di recente ho pensato...[n]forse 因 stata tutta colpa mia...[n][w][e]
[s]Ora invece detesto me stessa e[n]l'odio cresce di giorno in giorno...[n][w][e]

[msg D10_09_HiddenRoom02_Hint_3 [Ombra con camice]]
[s]Allora 因 per questo che volevi[n]rubarti il tuo stesso cuore.[n][w][e]
[s]Bene, non preoccuparti...[n]Questo trattamento ti render稲[n]immediatamente felice.[n][w][e]

[msg D10_09_HiddenRoom02_Hint_4 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]Maledizione, l'hanno sottoposta[n]subito alla terapia...[n][w][e]

[msg D10_09_HiddenRoom02_Hint_5 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aveva risposto "C: Rubare[n]il mio cuore per guarire".[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In questo posto, ammettere di[n]avere un problema equivale a[n]chiedere di sottoporsi alla terapia.[n][w][e]

[msg D10_09_HiddenRoom02_Hint_6 [Persona in vestaglia d'ospedale]]
[s]Finalmente, sono felice...[n][w][e]
[s]Ahahah... Ahahahahah![n][w][e]

[msg D10_09_HiddenRoom02_Hint_7 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Non sento granch姻...[n][w][e]

[msg D10_09_HiddenRoom03_Hint [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7167 65535 0]Ehi, guardate, un'Ombra. Significa che...[n][w][e]

[msg D10_09_HiddenRoom03_Hint_2 [Donna col cuore spezzato]]
[s]Ho sempre avuto successo[n]con gli uomini. Non ho mai[n]faticato a trovare un fidanzato...[n][w][e]
[s]Ma la persona che ho sempre[n]amato non mi ha mai[n]degnata di uno sguardo.[n][w][e]
[s]Poi, un giorno, l'ho visto[n]con una ragazza...[n][w][e]
[s]Quindi ho pensato... Se solo potessi[n]rubargli il cuore...[n][w][e]

[msg D10_09_HiddenRoom03_Hint_3 [Ombra con camice]]
[s]Capisco. Dev'essere stato molto[n]difficile per te. Comunque...[n][w][e]
[s]Nella realt稲 ideale, ogni singola[n]persona 因 felice. L'egocentrismo[n]non 因 contemplato.[n][w][e]
[s]La felicit稲 ottenuta privando il[n]prossimo della propria non 因 vera[n]felicit稲. Ma anche tu sarai felice.[n][w][e]

[msg D10_09_HiddenRoom03_Hint_4 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Dubito che sia la risposta giusta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aveva risposto "E: Rubare[n]il cuore di chi amo".[n][w][e]

[msg D10_09_HiddenRoom03_Hint_5 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"La felicit稲 ottenuta privando il[n]prossimo della propria non 因 vera[n]felicit稲." Non ho idea di cosa intenda.[n][w][e]

[msg D10_09_HiddenRoom03_Hint_6 [Persona in vestaglia d'ospedale]]
[s]Eheheheh...[n][w][e]
[s]Ahahahaha![n][w][e]

[msg D10_09_HiddenRoom03_Hint_7 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Uhmmm... non c'因 niente di utile.[n][w][e]

[msg D10_09_ExtraHuddle01_Fir [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Usiamo questo posto per decidere[n]la nostra prossima mossa, Joker.[n][w][e]

[msg D10_09_ExtraHuddle01_Ans [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Qualcosa non ti convince, Joker?[n]Possiamo analizzare nuovamente le informazioni.[n][w][e]

[msg D10_09_ExtraHuddle01_Gen [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]OK, ecco un altro posto che fa al caso nostro.[n][w][e]

[msg D10_09_ExtraHuddle02_Fir [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]OK, ecco un altro posto che fa al caso nostro.[n][w][e]

[msg D10_09_ExtraHuddle02_Ans [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Qualcosa non ti convince, Joker?[n]Possiamo analizzare nuovamente le informazioni.[n][w][e]

[msg D10_09_ExtraHuddle02_Gen [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]OK, ecco un altro posto che fa al caso nostro.[n][w][e]

[msg D10_09_ExtraHuddle03_Fir [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]OK, ecco un altro posto che fa al caso nostro.[n][w][e]

[msg D10_09_ExtraHuddle03_Ans [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1003 65535 0]Qualcosa non ti convince, Joker?[n]Possiamo analizzare nuovamente le informazioni.[n][w][e]

[msg D10_09_ExtraHuddle03_Gen [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1122 65535 0]OK, ecco un altro posto che fa al caso nostro.[n][w][e]

[msg ALL_RESEARCH_END_mes_3rd [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Non 因 molto, ma almeno abbiamo[n]ottenuto delle informazioni.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non ragioniamo su[n]quale sarebbe la risposta che il[n]dottor Maruki riterrebbe[n]corretta?[n][w][e]

[msg D10_09_question_not_answ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1038 65535 0]Se abbiamo tutte le informazioni,[n]torniamo nella stanza e[n][clr 2]parliamo delle risposte[clr 27].[n][w][e]

[msg D10_09_question_not_chec [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Vediamo qual 因 la prossima domanda, Joker.[n][w][e]

[msg D10_09_Listen_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Abbiamo scoperto tutto il possibile[n]sulla persona che ha scelto[n]questa risposta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quello che scegliamo dipende da te,[n]Joker.[n][w][e]

[msg D10_09_Listen_not_end [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Non abbiamo scoperto abbastanza[n]sulla persona che ha scelto[n]questa risposta...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quello che scegliamo dipende da te,[n]Joker.[n][w][e]

[msg D10_09_acceptance_check_ [Receptionist Ombra]]
[s]...Suppongo siate i[n]Ladri Fantasma.[n][w][e]
[s]Normalmente catturo tutti gli[n]intrusi, ma quest'area 因 aperta[n]a chiunque desideri entrare.[n][w][e]
[s]Far韻 in modo che entriate nella sala[n]esami, se lo desiderate.[n][w][e]

[msg D10_09_acceptance_check__2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]...Permettono a degli[n]intrusi di continuare?[n]Che strano.[n][w][e]

[msg D10_09_acceptance_check__3 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Devono avere molta fiducia[n]nell'"esame". Comunque, dovrebbe[n]andare tutto a nostro vantaggio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Faremo in modo che sia cos淫.[n][w][e]

[msg D10_09_acceptance_check__4 [Receptionist Ombra]]
[s]Quindi, cosa scegliete? In base alla[n]vostra risposta, dovremo[n]agire di conseguenza...[n][w][e]

[sel D10_09_acceptance_check__5 top]
[s]Che tipo di posto 因?[e]
[s]Dove va quella gente?[e]

[msg D10_09_acceptance_check__6 [Receptionist Ombra]]
[s]Vedo che la nostra struttura vi[n]incuriosisce. Molto bene.[n][w][e]
[s]Questa 因 la lobby della stanza per[n]l'esame psicologico, dove stabiliamo[n]se i pazienti sono mentalmente sani.[n][w][e]
[s]Individuiamo nel cuore dei pazienti[n]potenziali problemi che loro stessi[n]potrebbero non conoscere.[n][w][e]

[msg D10_09_acceptance_check__7 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54411 65535 0]Ed esattamente cosa[n]includono questi esami?[n][w][e]

[msg D10_09_acceptance_check__8 [Receptionist Ombra]]
[s]Dopo quel corridoio c'因 la[n]sala visite speciale.[n][w][e]
[s]L淫, ogni paziente risponde[n]a tre semplici domande.[n][w][e]

[msg D10_09_acceptance_check__9 [Receptionist Ombra]]
[s]Toccate il pannello informativo[n]per iniziare la procedura.[n][w][e]
[s]Ascoltate le domande e[n]scegliete l'ascensore che[n]corrisponde alla risposta.[n][w][e]
[s]Non tornate al piano inferiore[n]fino al termine dell'esame,[n]per favore.[n][w][e]

[msg D10_09_acceptance_check__10 [Receptionist Ombra]]
[s]Il trattamento sar稲 consigliato[n]in base alle singole diagnosi...[n][w][e]
[s]Come ogni altra fase del processo,[n]la terapia 因 stata studiata pensando[n]al paziente. Non vi preoccupate.[n][w][e]
[s]Se al termine dell'esame non[n]troveremo alcuna anomalia...[n][w][e]
[s]Riceverete un piccolo regalo.[n][w][e]
[s]Per la vostra felicit稲[n]vi chiediamo di rispondere[n]in maniera sincera.[n][w][e]

[msg D10_09_acceptance_check__11 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Quindi tutto quello che dobbiamo fare 因[n]scegliere la risposta che riteniamo corretta.[n][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sebbene non abbia tanta voglia di[n]scoprire cosa intendano con[n]"trattamento"...[n][w][e]

[msg D10_09_acceptance_check__12 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esaminare il cuore di una persona,[n]scoprirne i dolori e i rimpianti[n]e distorcerne la cognizione...[n][w][e]
[s]為 quello che fa il dottor Maruki[n]nella vita reale, sotto[n]forma di Palazzo.[n][w][e]

[msg D10_09_acceptance_check__13 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Quindiii... se commetteremo[n]un errore, modificheranno[n]la nostra cognizione?[n][w][e]

[msg D10_09_acceptance_check__14 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quello succede solo nel mondo[n]reale. Qui incasinano la testa[n]alle persone in altri modi, credo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tipo, ti collegano a uno strano[n]aggeggio e... BZZZZZT![n][w][e]

[msg D10_09_acceptance_check__15 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7176 65535 0]Ehi! Non spaventarmi cos淫...[n][w][e]

[msg D10_09_acceptance_check__16 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, qualunque sia la terapia,[n]so per certo che non[n]vogliamo sottoporci a essa.  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Stare qui a cercare di immaginarlo 因[n]inutile. Facciamo questo esame[n]e vediamo come va a finire.[n][w][e]

[msg D10_09_acceptance_reChec [Receptionist Ombra]]
[s]Una volta pronti, seguite il corridoio[n]a sinistra della reception.[n][w][e]

[msg D10_09_back_block [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1111 65535 0]Come ha detto la receptionist,[n]a questo punto 因 meglio[n]non tornare indietro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non vogliamo fare una mossa falsa[n]aumentando il livello di allerta.[n][w][e]

