[msg D10_11_Light_Tutorial01_ [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dove ci troviamo...?[n][w][e]

[msg D10_11_Light_Tutorial01__2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Che cambio di panorama.[n]Eravamo in un laboratorio[n]di ricerca e adesso...[n][w][e]

[msg D10_11_Light_Tutorial01__3 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbastanza. Quasi come se fossimo...[n][w][e]

[msg D10_11_Light_Tutorial01__4 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Wow, guardate l稲![n][w][e]

[msg D10_11_Light_Tutorial01__5 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uuuh, quelle persone[n]stanno fluttuando...[n][w][e]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57065 65535 0]Ma che diamine 因?[n][w][e]

[msg D10_11_Light_Tutorial01__6 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qualunque cosa sia,[n]ha probabilmente a che fare[n]con la cognizione di Maruki.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse 因 convinto che chi[n]viene sottoposto alla "terapia"[n]finisca per sentirsi in estasi.[n][w][e]

[msg D10_11_Light_Tutorial01__7 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi crede davvero[n]di mandarli in paradiso?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Umpf. Maruki deve proprio pensare[n]di star facendo la cosa giusta.[n][w][e]

[msg D10_11_Light_Tutorial01__8 [[sumi 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]Dottor Maruki...[n][w][e]

[msg D10_11_Light_Tutorial01__9 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mona-senpai, il Tesoro 因 al di[n]sopra di questa stanza, giusto?[n][w][e]

[msg D10_11_Light_Tutorial01__10 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, ci siamo vicini.[n][w][e]

[msg D10_11_Light_Tutorial01__11 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Il problema 因 come salire lass迂.[n][w][e]

[msg D10_11_Light_Tutorial01__12 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Ci sono delle scale ma con un[n]grande buco al centro...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Da entrambi i lati spuntano[n]piante rampicanti belle grosse...[n]Possiamo usarle in qualche modo?[n][w][e]

[msg D10_11_Light_Tutorial01__13 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non sappiamo se reggerebbero[n]il nostro peso. Preferirei[n]evitare rischi inutili.[n][w][e]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gli scalini si sviluppano in parte[n]verso l'alto, quindi dev'esserci un[n]modo per utilizzarli in sicurezza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O almeno questo 因 quello che[n]mi fa supporre la precedente[n]esperienza con un Palazzo.[n][w][e]

[msg D10_11_Light_Tutorial01__14 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sono d'accordo. E sembra che ci[n]sia un dispositivo per farlo,[n]proprio laggi迂. Ci torner稲 utile?[n][w][e]

[msg D10_11_Light_Tutorial01__15 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3192 65535 0]Beh, che ne dite di[n]non sprecare tempo?[n][w][e]

[msg D10_11_Light_Tutorial02_ [[sumi 10 0]]]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57064 65535 0]Le scale sono a posto![n][w][e]

[msg D10_11_Light_Tutorial02__2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che i rampicanti[n]crescano quando il colore[n]delle luci 因 lo stesso dei fiori.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Inoltre, pare che l'interruttore[n]cambi le luci nelle vicinanze.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Chiss稲 se ce ne sono altri qui...[n][w][e]

[msg D10_11_Light_Tutorial02__3 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]In pratica, possiamo usare gli[n]interruttori delle luci per far[n]crescere i rampicanti, giusto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mettiamoci al lavoro, Joker![n][w][e]

[msg D10_11_Light_Tutorial03_ [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Prima le scale, ora[n]un muro di rampicanti...[n][w][e]

[msg D10_11_Light_Tutorial03__2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo creato delle[n]scale di rampicanti,[n]sfruttando gli interruttori...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54404 65535 0]Non dovremmo essere in grado di[n]fare lo stesso con questo muro?[n][w][e]

[msg D10_11_Light_Tutorial04_ [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cosa sarebbe?[n][w][e]

[msg D10_11_Light_Tutorial04__2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]為 un quadro di comando per le[n]luci. Serve a regolare luminosit稲[n]e colore delle luci.[n][w][e]

[msg D10_11_Light_Tutorial04__3 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vedi la luce sulla porta[n]di fronte alle scale?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Al momento, il colore[n]del regolatore dell'intensit稲[n]因 lo stesso delle luci.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardando meglio, i rampicanti[n]formano una specie di scala[n]nei punti colpiti dalla luce.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ho ragione di credere che ci sia[n]possibile modificare i percorsi[n]disponibili alterando le luci.[n][w][e]

[msg D10_11_Light_Tutorial04__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Bene, Joker. Prova a usare[n]il regolatore per cambiare lo[n]schema di colore delle luci![n][w][e]

[msg D10_11_Light_Wall_Vanish [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Il muro 因 andato.[n]Ora possiamo andare avanti![n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Caspita... Le luci accese fanno[n]uscire le scale, le luci[n]spente fanno sparire i muri...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quanto vorrei poter attivare[n]tutto e andare avanti.[n][w][e]

[msg D10_11_Light_Wall_Vanish_2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Per giunta, abbiamo avuto a[n]disposizione solo le luci rosse.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se anche dovessimo trovare[n]altri interruttori, dubito che l淫[n]avremo accesso a tutti i colori.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci conviene tenerlo bene a[n]mente per il prossimo futuro.[n][w][e]

[msg D10_11_Light_Camera_Expl [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1019 65535 0]Ehi Joker...hai un secondo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quando cambiamo le luci[n]dobbiamo stare attenti, o[n]sar稲 ancor pi迂 difficile avanzare.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardati bene intorno prima[n]di decidere quale luci[n]accendere o spegnere.[n][w][e]

[msg D10_11_Light_Camera_Expl_2 [Gestire visuale con interruttori]]
[s]Mentre regoli la luminosit稲,[n]premi [f 1 10 31] per [clr 2]cambiare la visuale[clr 27].[n][w][e]
[s]Mentre [clr 2]ti guardi attorno[clr 27] puoi osservare[n]gli interruttori che ti circondano premendo [f 1 10 47] o [f 1 10 48].[n][w][e]

[msg D10_11_Mixed_Light_First [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ok, manteniamo il ritmo![n][w][e]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Oh?[n][w][e]

[msg D10_11_Mixed_Light_First_2 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo abbinare[n]il colore delle luci a quello[n]dei fiori, giusto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Duuunque... qualcuno di voi[n]ha visto un interruttore viola?[n][w][e]

[msg D10_11_Mixed_Light_First_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2131 65535 0]Sembra pi迂 magenta. Potrei[n]sbagliarmi, ma forse possiamo[n]creare quel colore con il pannello.[n][w][e]

[msg D10_11_Mixed_Light_First_4 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Attivando insieme pi迂 colori,[n]la luce dovrebbe mescolarsi[n]e crearne di nuovi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora sono accese le luci rosse e verdi,[n]ma regolando le manopole dovremmo[n]riuscire a ottenere il magenta richiesto.[n][w][e]

[msg D10_11_Mixed_Light_First_5 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4133 65535 0]Ah, quindi si usano[n]anche i colori secondari.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mescolare i colori per[n]aprirci la strada...[n]Che enigma intrigante.[n][w][e]

[msg D10_11_Mixed_Light_First_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sugli interruttori ci sono degli[n]appunti con utili consigli[n]per mescolare i colori.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi provarci, Joker?[n][w][e]

[msg D10_11_light_stairs_end0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]S淫淫淫! Il traguardo![n][w][e]

[msg D10_11_light_stairs_end0_2 [[sumi 10 0]]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo cos淫 vicino al Tesoro...[n]Inizio a innervosirmi.[n][w][e]

[msg D10_11_4th_EX_before_sta [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'因 una TV laggi迂... e sembra che[n]ci sia un nastro nel registratore.[n][w][e]

[msg D10_11_4th_EX_before_01 [Akechi]]
[s][bup 0 9 813 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8028 65535 0]DI NUOVO? Spero sia l'ultimo.[n][w][e]

[msg D10_11_4th_EX_before_end [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I nastri sembrano per韻 diventare[n]sempre pi迂 recenti.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cosa ci riserva stavolta...?[n][w][e]

[msg D10_11_4th_passcode_lock [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]Cos'因 accaduto a Maruki il giorno[n]in cui il cielo 因 diventato rosso?[n][w][e]

[msg D10_11_4th_passcode_lock_2 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Quando il cielo si tinse di rosso"?[n]Si riferisce a quando i Memento[n]si sono fusi con il mondo reale?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lasciamo la risposta a te, Joker.[n][w][e]

[sel D10_11_4th_passcode_lock_3 top]
[s]Ha mostrato il suo lavoro a Shibusawa.[e]
[s]Le sue ricerche sono state interrotte.[e]
[s]Ha sfidato il Dio del Controllo.[e]
[s]La sua Persona si 因 risvegliata del tutto.[e]

[msg D10_11_4th_passcode_lock_4 [Voce meccanica]]
[s]Risposta errata.[n]Dispositivo di blocco attivo.[n][w][e]

[msg D10_11_4th_passcode_lock_5 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3021 65535 0]Sembra che non fosse quella[n]giusta. Riproviamo.[n][w][e]

[msg D10_11_4th_passcode_lock_6 [Voce meccanica]]
[s]Autenticazione completata.[n]Blocco disattivato.[n][w][e]

[msg D10_11_4th_passcode_lock_7 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 aperto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Continuiamo? Il Tesoro 因 vicino.[n][w][e]

[msg D10_11_4th_passcode_lock_8 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]Cos'因 accaduto a Maruki il giorno[n]in cui il cielo 因 diventato rosso?[n][w][e]

[msg D10_11_4th_passcode_lock_9 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]Un altro di quelli!?[n][w][e]

[msg D10_11_4th_passcode_lock_10 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Quando il cielo si tinse di rosso"?[n]Parla del tramonto? Questa 因[n]dura da indovinare senza indizi...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]Dovremmo ritornarci dopo[n]che avremo pi迂 informazioni[n]in mano, Joker-senpai.[n][w][e]

[msg D10_11_4th_passcode_lock_11 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57144 65535 0]Dovremmo prima ottenere[n]qualche informazione, Joker-senpai.[n][w][e]

[msg D10_11_EX3BOSS_1st_01 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quell'Ombra sembra davvero[n]forte, Joker-senpai...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]Assicuriamoci di essere pronti prima[n]di entrare, che ne pensi?[n][w][e]

[msg D10_11_EX3BOSS_2nd_01 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57047 65535 0]Entriamo?[n][w][e]

[sel D10_11_EX3BOSS_selA top]
[s]Facciamolo.[e]
[s]Un secondo...[e]

[msg D10_11_EX3BOSS_selA_2_01 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57123 65535 0]OK, ripieghiamo per ora.[n][w][e]

[msg D10_11_EX3BOSS_before_ba [Guardia Ombra]]
[s]Umpf! Ecco i pazzi che[n]hanno rifiutato la generosa[n]realt稲 del padrone...[n][w][e]
[s]Non farete un altro passo. Tornate[n]indietro se ci tenete alla vita.[n][w][e]

[msg D10_11_EX3BOSS_before_ba_2 [[sumi 10 0]]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non oggi! Prenderemo il[n]Tesoro, che lo voglia o no![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo![n][w][e]

[msg D10_11_To05_Confirmation [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra l'ultima linea di difesa.[n]Prima di combattere, assicuriamoci[n]di essere in perfetta forma.[n][w][e]

[msg D10_11_To05_Confirmation_2 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo, Joker?[n][w][e]

[sel D10_11_To05_Confirmation_3 top]
[s]Andiamo.[e]
[s]Non ancora.[e]

[msg D10_11_To05_Confirmation_4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Capito. Decidi tu quando.[n][w][e]

[msg D10_11_To05_Confirmation_5 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, facciamolo.[n][w][e]

[msg D10_11_Tell_the_Goal_sta [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6001 65535 0]Ehi, guardate! Una grande scala![n][w][e]

[msg D10_11_Tell_the_Goal_01 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra arrivare[n]fino ai tetti degli edifici![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ecco dove probabilmente si trova il Tesoro...[n][w][e]

[msg D10_11_Tell_the_Goal_end [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci siamo quasi![n]Andiamo avanti, Joker![n][w][e]

[msg D10_11_Boss03_Confirmati [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dopo di lui non rilevo[n]altri segnali... E la mappa[n]non mostra altre zone.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questo 因 probabilmente l'ultimo[n]ostacolo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra una lotta impegnativa,[n]tutti devono essere al massimo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Pronto, Joker?[n][w][e]

[msg D10_11_Boss03_Confirmati_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Pronto, Joker?[n][w][e]

[sel D10_11_Boss03_Confirmati_3 top]
[s]Certo.[e]
[s]Non ancora.[e]

[msg D10_11_Boss03_Confirmati_4 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9023 65535 0]OK! Che ognuno prenda il[n]proprio posto prima di entrare![n][w][e]

[msg D10_11_Boss03_mes_start [Guardia Ombra]]
[s]Voi!? Non ci credo che[n]siete arrivati fino a qui![n][w][e]

[msg D10_11_Boss03_mes_01 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4088 65535 0]Ma certo. Non bisogna sottovalutare[n]i Ladri Fantasma.[n][w][e]

[msg D10_11_Boss03_mes_02 [[sumi 10 0]]]
[s][bup 0 10 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non torneremo indietro.[n]Facci entrare![n][w][e]

[msg D10_11_Boss03_mes_end [Guardia Ombra]]
[s]Il tempo della salvezza 因 quasi arrivato.[n]Non vi permetter韻 di interferire![n][w][e]

[msg D10_11_This_is_Ishi_Rout [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3019 65535 0]Aspetta, Joker...[n][w][e]

[msg D10_11_This_is_Ishi_Rout_2 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siamo tutti d'accordo che[n]il Tesoro si trovi in cima a[n]quella grande scala, giusto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non dovremmo andare invece[n]in quella direzione?[n][w][e]

[msg D10_11_This_is_Ishi_Rout_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Ma laggi迂 percepisco un Seme della[n]bramosia. Che razza di Ladri Fantasma[n]saremmo, se lo ignorassimo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Potrebbe essere una buona idea[n]perlustrare l'area se ne[n]avremo l'occasione.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per韻 dipende tutto da te, Joker.[n][w][e]

[msg MND_CHECK_STAIR_MSG01]
[s]Questa scala 因 [clr 2]rossa[clr 27]...[n][w][e]

[msg MND_CHECK_STAIR_MSG02]
[s]Questa scala 因 [clr 2]verde[clr 27]...[n][w][e]

[msg MND_CHECK_STAIR_MSG03]
[s]Questa scala 因 [clr 2]blu[clr 27]...[n][w][e]

[msg MND_CHECK_STAIR_MSG04]
[s]Questa scala 因 [clr 2]ciano[clr 27]...[n][w][e]

[msg MND_CHECK_STAIR_MSG05]
[s]Questa scala 因 [clr 2]magenta[clr 27]...[n][w][e]

[msg MND_CHECK_STAIR_MSG06]
[s]Questa scala 因 [clr 2]gialla[clr 27]...[n][w][e]

[msg MND_CHECK_STAIR_MSG07]
[s]Questa scala 因 [clr 2]bianca[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG01]
[s]Questo cancello 因 [clr 2]rosso[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG02]
[s]Questo cancello 因 [clr 2]verde[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG03]
[s]Questo cancello 因 [clr 2]blu[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG04]
[s]Questo cancello 因 [clr 2]ciano[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG05]
[s]Questo cancello 因 [clr 2]magenta[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG06]
[s]Questo cancello 因 [clr 2]giallo[clr 27]...[n][w][e]

[msg MND_CHECK_GATE_MSG07]
[s]Questo cancello 因 [clr 2]bianco[clr 27]...[n][w][e]

[msg note_find_reaction_start [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Cosa sar稲? Un diario?[n][w][e]

[msg note_find_reaction_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Cos淫 pare. A giudicare da quanto[n]c'因 scritto, 因 probabile[n]che appartenga a Maruki...[n][w][e]

[msg note_find_reaction_watch [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Anche quel video di prima...[n]Adora parlare di se stesso.[n][w][e]

[msg note_find_reaction_notwa [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Pare si sia appuntato varie cose[n]riguardo al passato, ma questi[n]sembrano solo frammenti...[n][w][e]

[msg note_find_reaction_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Neanche sembra avere[n]un qualche significato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Non so se pu韻 tornarci utile per[n]l'indagine, ma conserviamolo e[n]vediamo se ne troviamo altri.[n][w][e]

