[msg e511_630_mes_Start [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci aspetta una battaglia.[n]Siamo tutti pronti?[n][w][e]

[sel e511_630_mes_SEL top]
[s]S淫, andiamo.[e]
[s]No, non ancora.[e]

[msg e511_630_mes_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]Hm... D'accordo, becchiamoci dopo.[n][w][e]

[msg e511_630_mes_02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4035 65535 0]OK, facciamolo![n][w][e]

[msg e511_630_mes_03 [Guardia Ombra]]
[s]Eccovi! I nemici di Lord Maruki![n][w][e]

[sel e511_630_before_battle_S top]
[s]Passaci attraverso.[e]
[s]Togliti di torno![e]

[msg e511_630_mes_04 [Guardia Ombra]]
[s]Non vi permetteremo di[n]disturbare il nostro padrone![n][w][e]

[msg e511_630_mes_05 [Guardia Ombra]]
[s]Mi rifiuto di muovermi per gente[n]come voi![n][w][e]

[msg D10_12_researcher_enemy0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci sono dei nemici,[n]Joker! Oh? Cosa[n]indossano...?[n][w][e]

[msg D10_12_researcher_enemy0_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Camici da laboratorio? Perch姻 le[n]dovrebbero indossare delle[n]Ombre in uno stadio?[n][w][e]
[s]Cosa vede in questo[n]posto il dottor Maruki?[n][w][e]

[msg D10_12_get_map_start [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4090 65535 0]Sembra che questa sia[n]la piantina del Palazzo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]IL posto 因 enorme.[n]Abbiamo ancora molta strada da fare.[n][w][e]

[msg D10_12_get_map02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]"Laboratorio di scienza[n]psi-cognitiva di Maruki"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ovvio... Questo Palazzo 因 un laboratorio.[n][w][e]

[msg D10_12_get_map03 [[sumi 10 0]]]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57119 65535 0]Ho capito! Questo[n]spiega i camici da laboratorio[n]delle Ombre.[n][w][e]

[msg D10_12_get_map_end [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]In un certo senso 因 tipico del[n]dottor Maruki, ma... perch姻 rendere[n]lo stadio di Odaiba un laboratorio?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2051 65535 0]...Non credo sia utile pensarci adesso.[n]Dovremmo continuare.[n][w][e]

[msg D10_12_1st_passcode_lock [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Uhm... Un momento, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Questa porta non 因 protetta[n]da un dispositivo di autenticazione,[n]ma 因 ben sorvegliata.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guarda![n][w][e]

[msg D10_12_1st_passcode_lock_2 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla domanda segreta.[n][w][e]
[s]Cosa ha sacrificato Takuto Maruki[n]in cambio del potere di[n]riscrivere la cognizione?[n][w][e]

[msg D10_12_1st_passcode_lock_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Wow, parla! Beh, non che abbia[n]importanza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cos'ha perso il dottor Maruki?[n]E cos'因? Una specie di indovinello?[n][w][e]

[msg D10_12_1st_passcode_lock_4 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9128 65535 0]Sembra una domanda di sicurezza[n]per accertare l'identit稲[n]di chi vuole accedere.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]I suoi dati personali vengono[n]usati come chiave.[n][w][e]

[msg D10_12_1st_passcode_lock_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi non 因 un indovinello.[n]Dobbiamo solo trovare[n]la risposta.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, siamo nel Palazzo di Maruki,[n]quindi sar稲 pi迂 facile trovare la[n]risposta qui che nella realt稲.[n][w][e]

[msg D10_12_1st_passcode_lock_6 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]Bene, allora andiamo! Cominciamo[n]a cercare![n][w][e]

[msg D10_12_1st_passcode_lock_7 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Joker! Non dovremmo cercare[n]delle tracce?[n][w][e]

[msg D10_12_1st_passcode_lock_8 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla domanda segreta.[n][w][e]
[s]Cosa ha sacrificato Takuto Maruki[n]in cambio del potere di[n]riscrivere la cognizione?[n][w][e]

[msg D10_12_1st_passcode_lock_9 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Dopo aver visto il filmato,[n]credo di conoscere la risposta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Davvero? Ok, inseriscila tu.[n][w][e]

[sel D10_12_1st_passcode_lock_10 top]
[s]Amici[e]
[s]Famiglia[e]
[s]Insegnante[e]
[s]Fidanzata[e]

[msg D10_12_1st_passcode_lock_11 [Voce meccanica]]
[s]Risposta errata.[n]Dispositivo di blocco attivo.[n][w][e]

[msg D10_12_1st_passcode_lock_12 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8141 65535 0]Si direbbe che non fosse[n]la risposta corretta, Joker.[n]Riprova.[n][w][e]

[msg D10_12_1st_passcode_lock_13 [Voce meccanica]]
[s]Autenticazione completata.[n]Blocco disattivato.[n][w][e]

[msg D10_12_1st_passcode_lock_14 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54241 65535 0]Bene! Ce l'abbiamo fatta![n][w][e]

[msg D10_12_1st_passcode_lock_15 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, potresti guardare pi迂 da vicino[n]quella porta con il blocco[n]super-sicuro?[n][w][e]

[msg D10_12_get_map_start_bef [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aspetta. Guarda un po' qui.[n][w][e]

[msg D10_12_wall_vanish_start [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, manca il cavo posteriore![n][w][e]

[msg D10_12_wall_vanish_01 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse cazzeggiare con la console[n]nei Memento ha funzionato. Sembra[n]che possiamo proseguire.[n][w][e]

[sel D10_12_wall_vanish_sel top]
[s]Andiamo.[e]
[s]Procediamo con cautela.[e]

[msg D10_12_wall_vanish_end [[sumi 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]S淫, andiamo, senpai![n][w][e]

[msg D10_12_find_boss_start [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aspetta un secondo! Guardate![n][w][e]

[msg D10_12_find_boss_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La sicurezza 因 pesante e[n]sembra imbattibile.[n][w][e]

[msg D10_12_find_boss_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi siamo in un posto[n]importante. Una volta pronti,[n]facciamoli fuori.[n][w][e]

