[msg e511_630_mes_Start [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Stiamo per affrontare[n]un combattimento.[n]Hai ultimato i preparativi?[n][w][e]

[sel e511_630_mes_SEL top]
[s]為 tutto pronto.[e]
[s]Un secondo.[e]

[msg e511_630_mes_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]Mmm... Una volta pronti,[n]torniamo.[n][w][e]

[msg e511_630_mes_02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4035 65535 0]Molto bene. Andiamo![n][w][e]

[msg e511_630_mes_03 [Guardia Ombra]]
[s]E cos淫, osate sfidare Sua Eccellenza![n][w][e]

[sel e511_630_before_battle_S top]
[s]Passiamo.[e]
[s]Fuori dai piedi.[e]

[msg e511_630_mes_04 [Guardia Ombra]]
[s]Non interferirete con[n]il lavoro del padrone![n][w][e]

[msg e511_630_mes_05 [Guardia Ombra]]
[s]Chi siete VOI per darmi ordini?[n][w][e]

[msg D10_12_researcher_enemy0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nemici, Joker! ...Oh? I loro abiti...[n][w][e]

[msg D10_12_researcher_enemy0_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sono... camici da laboratorio?[n]Perch姻 le Ombre indossano dei[n]camici in uno stadio?[n][w][e]
[s]Cosa vede in questo[n]posto il dottor Maruki?[n][w][e]

[msg D10_12_get_map_start [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4090 65535 0]Sembra che questa sia[n]la mappa del Palazzo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 dettagliata... Pare che abbiamo[n]ancora molta strada da fare.[n][w][e]

[msg D10_12_get_map02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]"Laboratorio di scienza[n]psi-cognitiva di Maruki"...[n][w][e]

[msg D10_12_get_map03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Il Palazzo 因 un laboratorio!?![n][w][e]

[msg D10_12_get_map04 [Akechi]]
[s][bup 0 9 801 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Davvero non l'avevi ancora capito?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Considerando il passato di[n]Maruki e l'aspetto del Palazzo,[n]non era difficile dedurlo.[n][w][e]

[msg D10_12_get_map05 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7195 65535 0]Chiudi il becco! 為 un posto[n]cos淫 assurdo che[n]non aveva senso pensarci![n][w][e]

[msg D10_12_get_map05_insert0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi capisci, vero, [fName]!?![n][w][e]

[sel D10_12_get_map_SEL top]
[s]Parla per te.[e]
[s]Ti capisco.[e]

[msg D10_12_get_map06 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54215 65535 0]...Davvero?[n][w][e]

[msg D10_12_get_map07 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]L'aspetto di un Palazzo dipende da[n]ci韻 che il suo signore pensa[n]di qualcuno o di qualcosa.[n][w][e]

[msg D10_12_get_map08 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7048 65535 0]S淫! Prendi questo![n][w][e]

[msg D10_12_get_map09 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]...L'aspetto di un Palazzo dipende[n]da ci韻 che il suo signore pensa[n]di qualcuno o di qualcosa.[n][w][e]

[msg D10_12_get_map10 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nel caso di Takuto Maruki, deve[n]considerare lo stadio come[n]un laboratorio.[n][w][e]

[msg D10_12_get_map11 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, quella parte mi 因 chiara.[n]Ma di tutti i posti possibili,[n]perch姻 lo stadio?[n][w][e]

[msg D10_12_get_map12 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Oh... Mi ricorda una cosa[n]che ho sentito tempo fa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Prima dello stadio,[n]era prevista la costruzione[n]di un laboratorio di ricerca.  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Avr稲 qualcosa a che fare[n]con quella storia...?[n][w][e]

[msg D10_12_get_map_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]為 possibile, ma per ora dovremmo[n]concentrarci sui progressi nel[n]Palazzo, non sulle domande.[n][w][e]

[msg D10_12_1st_passcode_lock [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uh-oh. Quella porta ha un blocco[n]di sicurezza assurdo e non[n]c'因 nemmeno lo scanner...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Diamo un'occhiata da vicino![n][w][e]

[msg D10_12_1st_passcode_lock_2 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]Cosa ha sacrificato Takuto Maruki[n]in cambio del potere di[n]riscrivere le cognizioni?[n][w][e]

[msg D10_12_1st_passcode_lock_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7039 65535 0]Aaah, ha parlato! Ehm...[n]ma non 因 questo il problema.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che diavolo intende? Il Doc[n]ha perso qualcosa? 為 un enigma?[n][w][e]

[msg D10_12_1st_passcode_lock_4 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9128 65535 0]為 una domanda di sicurezza, come[n]quando ripristini una password. La[n]risposta la sa solo una persona.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 cos淫 che si finiscono[n]per usare le informazioni[n]personali come delle chiavi.[n][w][e]

[msg D10_12_1st_passcode_lock_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Capisco. Quindi ci servono[n]informazioni sulla vita di Maruki...  [n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Beh, 因 il suo Palazzo. Scommetto[n]che cercando con cura troveremo[n]gli indizi per rispondere.[n][w][e]

[msg D10_12_1st_passcode_lock_6 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]OK, se il piano 因 questo,[n]andiamo a caccia di indizi![n][w][e]

[msg D10_12_1st_passcode_lock_7 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Joker, non dobbiamo prima[n]trovare gli indizi?[n][w][e]

[msg D10_12_1st_passcode_lock_8 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]Cosa ha sacrificato Takuto Maruki[n]in cambio del potere di[n]riscrivere le cognizioni?[n][w][e]

[msg D10_12_1st_passcode_lock_9 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Grazie a quel video,[n]so la risposta...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovresti saperla anche tu,[n]giusto? A te l'onore.[n][w][e]

[sel D10_12_1st_passcode_lock_10 top]
[s]Un suo amico.[e]
[s]La sua famiglia.[e]
[s]Il suo maestro.[e]
[s]La sua ragazza.[e]

[msg D10_12_1st_passcode_lock_11 [Voce meccanica]]
[s]Risposta errata.[n]Dispositivo di blocco attivo.[n][w][e]

[msg D10_12_1st_passcode_lock_12 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8141 65535 0]Pare che tu abbia sbagliato,[n]Joker. Fa' un altro tentativo.[n][w][e]

[msg D10_12_1st_passcode_lock_13 [Voce meccanica]]
[s]Autenticazione completata.[n]Blocco disattivato.[n][w][e]

[msg D10_12_1st_passcode_lock_14 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54241 65535 0]Evvai! Ce l'abbiamo fatta![n][w][e]

[msg D10_12_1st_passcode_lock_15 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, guardiamo meglio la[n]porta con il blocco super-sicuro.[n][w][e]

[msg D10_12_get_map_start_bef [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cosa... Cos'因 questo?[n][w][e]

[msg D10_12_wall_vanish_start [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardate! I cavi sono spariti![n][w][e]

[msg D10_12_wall_vanish_01 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]為 una fortuna che abbiamo provato[n]la console trovata nei Memento...[n]ora possiamo continuare.[n][w][e]

[sel D10_12_wall_vanish_sel top]
[s]Muoviamoci.[e]
[s]Procediamo con cautela.[e]

[msg D10_12_wall_vanish_end [[sumi 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]OK! Andiamo, senpai![n][w][e]

[msg D10_12_find_boss_start [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Un momento. Guardate l稲![n][w][e]

[msg D10_12_find_boss_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qui la sicurezza 因 ancora pi迂[n]rigida. Sembrano molto forti.[n][w][e]

[msg D10_12_find_boss_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi siamo in un posto[n]importante. Una volta pronti,[n]facciamoli fuori.[n][w][e]

[msg D10_12_1st_passcode_lock_16 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Mmm? Aspetta, Joker...[n][w][e]

[msg note_find_reaction_start [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Cosa sar稲? Un diario?[n][w][e]

[msg note_find_reaction_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Cos淫 pare. A giudicare da quanto[n]c'因 scritto, 因 probabile[n]che appartenga a Maruki...[n][w][e]

[msg note_find_reaction_watch [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Anche quel video di prima...[n]Adora parlare di se stesso.[n][w][e]

[msg note_find_reaction_notwa [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Pare si sia appuntato varie cose[n]riguardo al passato, ma questi[n]sembrano solo frammenti...[n][w][e]

[msg note_find_reaction_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Neanche sembra avere[n]un qualche significato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Non so se pu韻 tornarci utile per[n]l'indagine, ma conserviamolo e[n]vediamo se ne troviamo altri.[n][w][e]

