[msg dummy]
[s]......[n][w][e]

[msg D10_16_Dummy [Futaba]]
[s][bup 0 8 100 0 0]......[n][w][e]

[msg D10_16_DeckDoor_look_sta [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Aspetta un secondo, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quella stanza emette un segnale[n]unico rispetto alle altre. Potrebbe[n]essere come la stanza dei video.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Che ne dite di dare un'occhiata?[n]Potrebbe contenere degli indizi.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che non si possa aprire[n]da questo lato, quindi dobbiamo[n]seguire la strada lunga.[n][w][e]

[msg D10_16_DeckDoor_look_end [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8136 65535 0]Sono d'accordo con Oracle. Magari[n]non 因 la via pi迂 diretta per il[n]Tesoro, ma 因 gi稲 qualcosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per andare avanti, il nostro[n]obiettivo 因 quella stanza.[n][w][e]

[msg D10_16_PasswardDoor_look [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Oh, guarda... Un'altra di quelle[n]porte. Ho un dannato d姻j稲-vu...[n][w][e]

[msg D10_16_PasswardDoor_look_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cosa vuoi fare? Per[n]ora potremmo dare[n]un'occhiata, giusto?[n][w][e]

[msg D10_16_2nd_passcode_lock [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]Qual era l'elemento mancante[n]che ha causato l'interruzione delle[n]ricerche sulla scienza psi-cognitiva?[n][w][e]

[sel D10_16_2nd_passcode_lock_2 top]
[s]Probabilit稲 di successo.[e]
[s]Attendibilit稲.[e]
[s]Sostenibilit稲.[e]
[s]Dimostrazione.[e]

[msg D10_16_2nd_passcode_lock_3 [Voce meccanica]]
[s]Risposta errata.[n]Dispositivo di blocco attivo.[n][w][e]

[msg D10_16_2nd_passcode_lock_4 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1021 65535 0]Sembra che non fosse quella[n]giusta, Joker. Riproviamo.[n][w][e]

[msg D10_16_2nd_passcode_lock_5 [Voce meccanica]]
[s]Autenticazione completata.[n]Blocco disattivato.[n][w][e]

[msg D10_16_2nd_passcode_lock_6 [[sumi 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57051 65535 0]S淫! Si 因 aperta![n][w][e]

[msg D10_16_2nd_passcode_lock_7 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muoviamoci, Joker![n][w][e]

[msg D10_16_2nd_passcode_lock_8 [Akechi]]
[s][bup 0 9 803 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, andiamo. La prossima domanda[n]sar稲 "qual 因 lo spuntino preferito[n]di Maruki", o qualcosa del genere?[n][w][e]

[msg D10_16_2nd_passcode_lock_9 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]Qual era l'elemento mancante[n]che ha causato l'interruzione delle[n]ricerche sulla scienza psi-cognitiva?[n][w][e]

[msg D10_16_2nd_passcode_lock_10 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7022 65535 0]S淫, uh... non ne ho idea. Di nuovo.[n][w][e]

[msg D10_16_2nd_passcode_lock_11 [[sumi 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Rispondere a una domanda cos淫[n]specifica 因 complicato... Non so[n]nemmeno cosa pensare.[n][w][e]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E se andassimo a controllare la[n]stanza indicata da Oracle-senpai?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Potremmo trovarci la risposta,[n]o magari un indizio.[n][w][e]

[msg D10_16_2nd_passcode_lock_12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1034 65535 0]A me sta bene. Cerchiamo[n]di raggiungere quella stanza![n][w][e]

[msg D10_16_2nd_passcode_lock_13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Andiamo nella stanza[n]che ci ha indicato Oracle![n][w][e]

[msg D10_16_2nd_EX_before_sta [[sumi 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]Un altro video, come quello[n]che abbiamo visto prima...[n][w][e]

[msg D10_16_2nd_EX_before_end [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]L'idea di scavare nel passato[n]di qualcuno non mi fa impazzire,[n]ma non abbiamo scelta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se l'unico modo per andare[n]avanti 因 guardare, non[n]possiamo fare altrimenti.[n][w][e]

[msg D10_16_check_machine_sta [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57033 65535 0]Non ho mai visto una cosa[n]simile. Cosa fa?[n][w][e]

[msg D10_16_check_machine_01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra una specie di esperimento.[n]A quanto vedo, le manopole[n]influenzano le luci colorate...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma sembra che non dovremo[n]metterci mano per continuare.[n][w][e]

[msg D10_16_check_machine_end [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3116 65535 0]Quelle belle piante sugli[n]scaffali crescono benone.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Chiss稲 come funziona il sistema...[n][w][e]

[msg D10_16_check_machine02_s [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57033 65535 0]Non ho mai visto una cosa[n]simile. Cosa fa?[n][w][e]

[msg D10_16_check_machine02_0 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra una specie di esperimento.[n]A quanto vedo, le manopole[n]influenzano le luci colorate...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma sembra che non dovremo[n]metterci mano per continuare.[n][w][e]

[msg D10_16_check_machine02_e [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3116 65535 0]Quelle belle piante sugli[n]scaffali crescono benone.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Chiss稲 come funziona il sistema...[n][w][e]

[msg note_find_reaction_start [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Cosa sar稲? Un diario?[n][w][e]

[msg note_find_reaction_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Cos淫 pare. A giudicare da quanto[n]c'因 scritto, 因 probabile[n]che appartenga a Maruki...[n][w][e]

[msg note_find_reaction_watch [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Anche quel video di prima...[n]Adora parlare di se stesso.[n][w][e]

[msg note_find_reaction_notwa [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Pare si sia appuntato varie cose[n]riguardo al passato, ma questi[n]sembrano solo frammenti...[n][w][e]

[msg note_find_reaction_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Neanche sembra avere[n]un qualche significato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Non so se pu韻 tornarci utile per[n]l'indagine, ma conserviamolo e[n]vediamo se ne troviamo altri.[n][w][e]

