[msg dummy_mes]
[s]......[n][w][e]

[msg D10_15_Mission_Impossibl [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Aspettate. Laggi迂 因 pieno di[n]nemici forti. Se ci attaccassero[n]tutti insieme sarebbe un problema.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse conviene tornare pi迂 tardi?[n]Potrebbero spostarsi mentre[n]perlustriamo altre aree.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ciooo因, vuoi davvero rischiare[n]di scendere l稲 sotto?[n][w][e]

[sel D10_15_Mission_Impossibl_2 top]
[s]Scendiamo.[e]
[s]Ritiriamoci, per ora.[e]

[msg D10_15_Mission_Impossibl_3 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Mah, se lo dici tu... Fai[n]attenzione, Joker.[n][w][e]

[msg D10_15_Mission_Impossibl_4 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]S淫, prima controlliamo[n]le altre stanze.[n][w][e]

[msg D10_15_NPC_look_start [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Wow wow wow!!! Che succede con[n]questi ragazzi!?[n][w][e]

[msg D10_15_NPC_look_01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uooooo, guardate che marchingegni[n]assurdi hanno addosso![n][w][e]

[msg D10_15_NPC_look_02 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8128 65535 0]Hanno chiamato questo posto[n]"sala terapia", quindi...[n][w][e]

[msg D10_15_NPC_look_03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E QUESTO sarebbe il "trattamento"?[n]Non si direbbe proprio![n][w][e]

[msg D10_15_NPC_look_end [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Laggi迂 c'因 anche un affare[n]strano simile a un cancello.[n]Dopo diamogli un'occhiata.[n][w][e]

[msg D10_15_NPC_look_another_ [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]Wow wow wow!!! Che succede con[n]questi ragazzi!?[n][w][e]

[msg D10_15_NPC_look_another__2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uooooo, guardate che marchingegni[n]assurdi hanno addosso![n][w][e]

[msg D10_15_NPC_look_another__3 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8134 65535 0]Beh, siamo arrivati qui[n]dalla sala visite, quindi...[n][w][e]
[s]Seguendo la logica, questa[n]dev'essere la sala di supporto[n]e quelle persone sono...[n][w][e]

[msg D10_15_NPC_look_another__4 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E QUESTO sarebbe il "trattamento"?[n]Non si direbbe proprio![n][w][e]

[msg D10_15_NPC_look_another__5 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9197 65535 0]Eh, non pensarci troppo. Sono[n]tutte creature cognitive.[n]Andiamo avanti.[n][w][e]

[msg D10_15_discover_passward [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C'因 un'altra porta di sicurezza.[n]Quindi dobbiamo trovare[n]un altro indizio...[n][w][e]

[msg D10_15_discover_passward_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Giusto. Senza un indizio[n]non giungeremo mai alla risposta,[n]probabilmente.[n][w][e]

[msg D10_15_discover_passward_3 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovremmo comunque dare[n]un'occhiata per precauzione.[n][w][e]

[msg D10_15_3rd_video_notExis [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Ah, un'altra TV... mi sa che ci[n]tocca guardare un altro filmato.[n][w][e]

[msg D10_15_3rd_video_notExis_2 [[sumi 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, non adesso, almeno.[n]Nel lettore non ci sono nastri.[n][w][e]

[msg D10_15_3rd_video_notExis_3 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 indubbio che ci serva trovarne[n]uno per poter proseguire.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cominciamo a cercare.[n][w][e]

[msg D10_15_3rd_passcode_lock [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]"Come reagiscono gli adolescenti,[n]quando sono vicini a qualcuno[n]con molto pi迂 talento?"[n][w][e]

[msg D10_15_3rd_passcode_lock_2 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Argh, un'altra ancora?!?[n][w][e]

[msg D10_15_3rd_passcode_lock_3 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tutto il tempo passato qui[n]因 letteralmente sprecato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Torniamo quando avremo[n]capito come rispondere, Joker.[n][w][e]

[msg D10_15_3rd_passcode_lock_4 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Dobbiamo prima trovare un[n]suggerimento per la risposta, Joker![n][w][e]

[msg D10_15_3rd_passcode_lock_5 [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]"Come reagiscono gli adolescenti,[n]quando sono vicini a qualcuno[n]con molto pi迂 talento?"[n][w][e]

[sel D10_15_3rd_passcode_lock_6 top]
[s]Scappando.[e]
[s]Cercando di apparire normali.[e]
[s]Sperando che fallisca.[e]
[s]Desiderando di essere quella persona.[e]

[msg D10_15_3rd_passcode_lock_7 [Voce meccanica]]
[s]Risposta errata.[n]Dispositivo di blocco attivo.[n][w][e]

[msg D10_15_3rd_passcode_lock_8 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57033 65535 0]Mi sa che non 因 quella[n]giusta... Provaci di nuovo,[n]Joker-senpai.[n][w][e]

[msg D10_15_3rd_passcode_lock_9 [Voce meccanica]]
[s]Autenticazione completata.[n]Blocco disattivato.[n][w][e]

[msg D10_15_3rd_passcode_lock_10 [[sumi 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ce l'abbiamo fatta![n][w][e]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57173 65535 0]Non avrei mai immaginato di[n]diventare la password di sicurezza[n]di qualcuno...[n][w][e]

[msg D10_15_formidable_enemy_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Ehi, quelle Ombre fanno paura.[n]Cerchiamo di non farci beccare.[n][w][e]

[msg D10_15_formidable_enemy__2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che le Ombre stiano[n]pattugliando la zona...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cerchiamo di non farci sorprendere[n]da nessuno, mentre cerchiamo la[n]videocassetta.[n][w][e]

[msg D10_15_something_check01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Vediamo cosa c'因 in questa scatola.[n][w][e]

[msg D10_15_something_check_n [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1028 65535 0]Qui non c'因 niente...[n]Cerchiamo altrove.[n][w][e]

[msg D10_15_enemies_left_room [Ricercatore]]
[s]Uniamoci alla pattuglia. Sembra che[n]degli intrusi abbiano rifiutato[n]la terapia. Sono nella struttura.[n][w][e]

[msg D10_15_enemies_left_room_2 [Esaminatore]]
[s]Se hanno rifiutato la salvezza[n]del padrone, sono senza speranza.[n]Dobbiamo prenderli in fretta.  [n][w][e]
[s]Non dimenticarti di bloccare[n]questa porta.[n][w][e]

[msg D10_15_after_enemies_lef [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]Sembra che ci siano ancora pi迂[n]Ombre adesso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La stanza da dove sono usciti 因[n]sospetta, per韻. Vogliamo[n]dare un'occhiata?[n][w][e]

[msg D10_15_something_check06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Vediamo cosa c'因 in questa scatola.[n][w][e]

[msg D10_15_get_video_start [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54241 65535 0]Ah! Eccola! Ora dritti a guardarla.[n][w][e]

[msg D10_15_get_video_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ecco la chiave del nostro successo![n]Torniamo alla stanza con la TV.[n][w][e]

[msg D162_015_mini_EV_01_mes_ [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9040 65535 0]Uooo! Ombra palestrata a ore 12![n][w][e]

[msg D162_015_mini_EV_01_mes__2 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A quanto pare blocca l'unica[n]strada disponibile. Meglio[n]prepararsi a combattere.[n][w][e]

[msg D162_015_mini_EV_01_mes__3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Sembra proprio un duro...[n]Sei pronto, Joker?[n][w][e]

[sel DO_10_162_BOSS_selB top]
[s]Pronto.[e]
[s]Solo un secondo.[e]

[msg D162_015_mini_EV_01_mes0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Va bene, diamoci dentro![n][w][e]

[msg D162_015_mini_EV_01_mes0_2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Ricevuto. Prepariamoci al meglio.[n][w][e]

[msg D162_015_BOSS_EV_Start [Sentinella]]
[s]Voi siete... i Ladri Fantasma?[n][w][e]

[msg D162_015_BOSS_EV_01 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Siamo qui per distruggere[n]l'utopia ipocrita del tuo capo. Ti[n]dispiacerebbe toglierti di mezzo?[n][w][e]

[msg D162_015_BOSS_EV_End [Sentinella]]
[s]Sciocchi ribelli! Da qui[n]non si passa![n][w][e]

[msg D10_15_look_videoroom_st [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, guarda![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra il posto giusto dove[n]poter trovare una videocassetta.[n]Andiamo a controllare![n][w][e]

[msg D10_15_videoroom_remind_ [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker, controlliamo[n]la stanza con la TV[n]dov'eravamo passati?[n][w][e]

[msg D10_15_enemy_look_force_ [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Ehi, quelle Ombre fanno paura.[n]Cerchiamo di non farci beccare.[n][w][e]

[msg D10_15_enemy_look_force__2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che le Ombre stiano[n]pattugliando la zona...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non torniamo pi迂 tardi?[n]Meglio non sprecare energie[n]contro di loro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54703 65535 0]Poco fa abbiamo superato una stanza.[n]Ricordate?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 non gli diamo un'occhiata?[n][w][e]

[msg D10_15_urge_check_3rd_vi [Voce meccanica]]
[s]Blocco di sicurezza attivo.[n]Rispondere alla seguente[n]domanda di autenticazione:[n][w][e]
[s]"Come reagiscono gli adolescenti,[n]quando sono vicini a qualcuno[n]con molto pi迂 talento?"[n][w][e]

[msg D10_15_urge_check_3rd_vi_2 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]...Forse siamo arrivati qui[n]un po' prima del previsto.[n][w][e]

[msg D10_15_urge_check_3rd_vi_3 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nella videocassetta dovremmo[n]trovare qualche indizio.[n]Torniamo dopo averla vista.[n][w][e]

[msg D10_15_urge_check_3rd_vi_4 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Prima guardiamo il video, Joker.[n][w][e]

[msg D10_FindGate_start_inser [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Ma che...[n][w][e]

[msg D10_FindGate_start [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Stanno passando[n]attraverso quello strano muro...[n]Che roba 因?!?[n][w][e]

[msg D10_FindGate_01 [Avviso]]
[s]Ai pazienti che hanno effettuato[n]il trattamento: siete pregati di[n]superare i cancelli splendenti.[n][w][e]
[s]Il vostro paradiso vi attende[n]dall'altro lato.[n][w][e]

[msg D10_FindGate_02 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]Quindi, identificano le "anomalie"[n]nella sala visite e qui[n]effettuano la "terapia"...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Le persone giudicate "felici"[n]vengono mandate oltre[n]quei cancelli.[n][w][e]

[sel D10_FindGate_SEL top]
[s]Entriamo.[e]
[s]Proviamoci.[e]

[msg D10_FindGate_03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Attenzione! Potresti[n]finire incenerito al[n]minimo contatto.[n][w][e]

[msg D10_FindGate_04 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]NON dirlo neanche per scherzo![n][w][e]

[msg D10_FindGate_05 [Avviso]]
[s]I pazienti non possono passare[n]senza terapia. Per riceverla, seguite[n]le istruzioni fornite altrove.[n][w][e]

[msg D10_FindGate_end [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi sa tanto che non riusciremo[n]a superare questi cancelli.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Credo ci convenga cercare[n]un percorso alternativo.[n][w][e]

[msg D10_15_CheckTvWithVideo_ [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bene, abbiamo la cassetta...[n]Chiss稲 cosa scopriremo questa[n]volta.[n][w][e]

[msg D10_15_CheckTvWithVideo__2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]Scommetto una cosa: non sar稲 piacevole.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ogni modo, dovremmo guardarla[n]il prima possibile.[n][w][e]

[msg note_find_reaction_start [[sumi 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57037 65535 0]Cosa sar稲? Un diario?[n][w][e]

[msg note_find_reaction_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Cos淫 pare. A giudicare da quanto[n]c'因 scritto, 因 probabile[n]che appartenga a Maruki...[n][w][e]

[msg note_find_reaction_watch [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Anche quel video di prima...[n]Adora parlare di se stesso.[n][w][e]

[msg note_find_reaction_notwa [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4191 65535 0]Pare si sia appuntato varie cose[n]riguardo al passato, ma questi[n]sembrano solo frammenti...[n][w][e]

[msg note_find_reaction_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Neanche sembra avere[n]un qualche significato.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Non so se pu韻 tornarci utile per[n]l'indagine, ma conserviamolo e[n]vediamo se ne troviamo altri.[n][w][e]

