[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_02_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_02_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non pensavo che questo muro[n]fosse ancora qui.[n][w][e]

[msg SCN_LOCK_02_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ma che cavolo...? Pensavo che[n]l'avessimo aperto influenzando[n]il pubblico o roba simile.[n][w][e]

[msg SCN_LOCK_02_mes04 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S淫, il primo. Per韻 sembra[n]che non sar稲 sufficiente[n]ad aprire questo.[n][w][e]
[s]...Almeno credo.[n][w][e]

[msg SCN_LOCK_02_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mona, hai detto che l'influenza[n]deriva da chi crede in noi, giusto?[n][w][e]
[s]Forse si aprirebbe se[n]potessimo farci accettare[n]da altra gente.[n][w][e]

[msg SCN_LOCK_02_mes06 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse...[n][w][e]

[msg SCN_LOCK_02_mes07 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perch姻 sei cos淫 vago[n]su tutta questa faccenda?[n][w][e]

[msg SCN_LOCK_02_mes08 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Va tutto bene. Il nostro[n]obiettivo non cambia.[n][w][e]
[s]Dovremo solo darci da fare finch姻[n]questo muro non si aprir稲![n][w][e]

[msg SCN_LOCK_02_mes09 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Allora quello che ci aspetta[n]qui dietro dovr稲 aspettare.[n][w][e]

[msg SCN_LOCK_02_mes10 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg SCN_LOCK_CLEAR_02_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Wow, ci siamo riusciti![n][w][e]

[msg SCN_LOCK_CLEAR_02_mes02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 perch姻 ora c'因 pi迂 gente[n]che crede in noi, giusto?[n][w][e]

[msg SCN_LOCK_CLEAR_02_mes03 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dev'essere cos淫.[n]Forza, entriamo![n][w][e]

