[msg AREA_EXIT_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Per ora seguiamo Mona.[n][w][e]

[msg mona_chase_ng_mes01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tsk, non 因 qui. Cerchiamo da un'altra parte![n][w][e]

[msg mona_chase_ng_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non 因 qui...[n]Andiamo da un'altra parte![n][w][e]

[msg mona_chase_ng_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non 因 qui. Proviamo a cercare[n]su un altro percorso![n][w][e]

[msg D05_02_e334_105_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, ma dove vai?[n]Mona non 因 di l稲![n][w][e]

