[sel RETURN_SEL top]
[s]Andiamo.[e]
[s]Lasciamo stare.[e]

[sel GO_SEL top]
[s]Andiamo.[e]
[s]Lasciamo stare.[e]

[msg MSG_DNG_RETURN_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi tornare indietro?[n][w][e]

[msg MSG_DNG_RETURN_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi salire, Joker?[n][w][e]

[msg MSG_DNG_RETURN_03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Saliamo?[n][w][e]

[msg MSG_DNG_GO [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuoi proseguire?[n][w][e]

[msg MSG_DNG_GO_NG [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra bloccata. Dubito che[n]riusciremo ad andare oltre.[n][w][e]

[msg D08_01_e437_011_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]為 davvero una porta?[n]Come facciamo a passare?[n][w][e]

[msg D08_01_e437_011_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Si 因 aperta subito...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Scommetto che le profondit稲 di cui[n]parlava il Meta-Nav sono[n]poco pi迂 avanti.[n][w][e]

[msg D08_01_e437_011_mes03 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aspettate.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La porta si apre[n]solo da questo lato...[n][w][e]

[msg D08_01_e437_011_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]C-Che intendi dire...?[n][w][e]

[msg D08_01_e437_011_mes05 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ho dato una rapida occhiata[n]al meccanismo interno...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sembra che si possa aprire[n]solo da qui. Possiamo entrare, ma[n]non si pu韻 uscire.[n][w][e]

[msg D08_01_e437_011_mes06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 come se avessero rinchiuso[n]qualcosa qui dentro.[n][w][e]

[msg D08_01_e437_011_mes07 [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3196 65535 0]Stai dicendo che chi entra[n]sta scegliendo una vita[n]di prigionia?[n][w][e]

[msg D08_01_e437_011_mes08 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non ho mai avvertito niente di cos淫[n]agghiacciante. Cos'因 questo posto?[n][w][e]

[msg D08_01_e437_011_mes09 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo scopriremo quando raggiungeremo[n]le profondit稲. Forza, andiamo.[n][w][e]

[msg D08_01_e437_011_DUMMY]
[s](調整中)大扉が開く[n][w][e]

