[msg dummy_mes]
[s]......[n][w][e]

[msg D08_01_e437_005_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]E-Ehi, quindi... quest'affare 因[n]la porta per le profondit稲, vero?[n][w][e]

[msg D08_01_e437_005_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Dovrebbe esserlo. Perch姻, che c'因?[n][w][e]

[msg D08_01_e437_005_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Non so, sembra come tutti[n]gli altri. Ci sono rimasto[n]un po' male.[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Forse 因 perch姻 ne abbiamo passate[n]davvero tante per arrivare qui.[n][w][e]

[msg D08_01_e437_005_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]La mancanza di circostanze[n]impreviste non 因 cosa di cui[n]lamentarsi. Proseguiamo.[n][w][e]

[msg SCN_LOCK_07_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_07_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]Pare che la gente non ci accetti[n]abbastanza da far aprire la porta.[n][w][e]

[msg SCN_LOCK_07_mes03 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]P-per ora non possiamo fare[n]niente. Non c'因 modo di[n]andare oltre.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Torniamo indietro, Joker?[n][w][e]

