[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_03_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_03_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm? Non si apre?[n][w][e]

[msg SCN_LOCK_03_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che dovremo farci accettare[n]da pi迂 persone...[n][w][e]

[msg SCN_LOCK_03_mes04 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuol dire che non siamo[n]molto popolari, eh?[n][w][e]

[msg SCN_LOCK_03_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ti sorprende?[n][w][e]

[msg SCN_LOCK_03_mes06 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un po' s淫...[n][w][e]

[msg SCN_LOCK_03_mes07 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]L'ha chiesto a me![n][w][e]

[msg SCN_LOCK_CLEAR_03_mes01 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si 因 aperta...[n][w][e]

[msg SCN_LOCK_CLEAR_03_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non vi sentite apprezzati[n]da tutto il mondo quando[n]questi affari si aprono?[n][w][e]

[msg SCN_LOCK_CLEAR_03_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All'inizio s淫, ma poi ricordo[n]che ci sono altri muri[n]come questo pi迂 avanti...[n][w][e]

[msg SCN_LOCK_CLEAR_03_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D'accordo, entriamo![n][w][e]

