[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_04_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_04_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non si apre?[n][w][e]

[msg SCN_LOCK_04_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gi稲. Significa che il popolo[n]non ci accetta ancora abbastanza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]為 successo cos淫[n]anche con gli altri.[n][w][e]

[msg SCN_LOCK_04_mes04 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un muro che non si apre[n]se non ci accettano. Un po' come[n]nel mondo dello spettacolo.[n][w][e]

[msg SCN_LOCK_04_mes05 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora che la metti cos淫,[n]lo trovo un po' deprimente...[n][w][e]

[msg SCN_LOCK_04_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quindi 因 questo che[n]stava succedendo? Cacchio...[n][w][e]

[msg SCN_LOCK_CLEAR_04_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si 因 aperta...[n][w][e]

[msg SCN_LOCK_CLEAR_04_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Grande, adesso possiamo proseguire.[n][w][e]

[msg SCN_LOCK_CLEAR_04_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Facciamo attenzione, OK? Pi迂 andiamo in profondit稲,[n]pi迂 i nemici diventano forti.[n][w][e]

