[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_06_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_06_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ci risiamo...[n][w][e]

[msg SCN_LOCK_06_mes03 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vuol dire che c'因 ancora[n]gente che non ci accetta?[n][w][e]

[msg SCN_LOCK_06_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non preoccuparti. Basta darsi[n]da fare e alla fine si aprir稲.[n][w][e]

[msg SCN_LOCK_06_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dobbiamo solo pazientare[n]finch姻 non accadr稲.[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oh, si 因 aperta...[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guardando l'area nel complesso,[n]questa 因 la cinquantaduesima area,[n]vero? Chiss稲 quante ne mancano.[n][w][e]

[msg SCN_LOCK_CLEAR_06_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovremo scoprirlo di persona![n]Andiamo![n][w][e]

