[msg dummy_mes]
[s]......[n][w][e]

[msg SCN_LOCK_05_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_05_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qui non si passa finch姻[n]non ci accettano altre persone...[n][w][e]

[msg SCN_LOCK_05_mes03 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ehi, non puoi fare qualcosa[n]con il tuo potere di Oracle,[n]o quel che 因?[n][w][e]

[msg SCN_LOCK_05_mes04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Credo di no. Non sono una[n]divinit稲, sai?[n][w][e]

[msg SCN_LOCK_05_mes05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A proposito di divinit稲, sapete di[n]quel dio che ha aperto una porta[n]eseguendo una danza lasciva?[n][w][e]

[msg SCN_LOCK_05_mes06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, credo di capire cos'hai[n]in mente. Forza, Skull![n][w][e]

[msg SCN_LOCK_05_mes07 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me ne vado.[n][w][e]

[msg SCN_LOCK_CLEAR_05_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oooh, si 因 aperta.[n][w][e]

[msg SCN_LOCK_CLEAR_05_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora possiamo esplorare[n]pi迂 a fondo.[n][w][e]

[msg SCN_LOCK_CLEAR_05_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Andiamo, allora![n][w][e]

