[msg dummy_mes]
[s]......[n][w][e]

[msg D08_01_e437_005_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]E-Ehi, quindi quest'affare 因[n]la porta per le profondit稲, vero?[n][w][e]

[msg D08_01_e437_005_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dovrebbe esserlo. Perch姻, che c'因?[n][w][e]

[msg D08_01_e437_005_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Non so, sembra come tutti[n]gli altri. Ci sono rimasto[n]un po' male.[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Forse 因 perch姻 ne abbiamo passate[n]davvero tante per arrivare qui.[n][w][e]

[msg D08_01_e437_005_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La mancanza di circostanze[n]impreviste non 因 cosa di cui[n]lamentarsi. Proseguiamo.[n][w][e]

[msg SCN_LOCK_07_mes01]
[s]Sembra proprio che[n]non si aprir稲...[n][w][e]

[msg SCN_LOCK_07_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pare che la gente non ci accetti[n]abbastanza da far aprire la porta.[n][w][e]

[msg SCN_LOCK_07_mes03 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]P-per ora non possiamo fare[n]niente. Non c'因 modo di[n]andare oltre.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Torniamo indietro, Joker?[n][w][e]

[msg CHECK_CONSOLE_MES_01_01 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9159 65535 0]Dopo l'interruzione[n]del trasferimento dati,[n]i cavi sono spariti.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ora dovremmo riuscire a superare[n]quell'area del Palazzo.[n][w][e]

[msg CHECK_CONSOLE_MES_01_02 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Immagino che dovremo[n]scoprirlo con i nostri occhi...[n]Riprendiamo l'infiltrazione![n][w][e]

[msg CHECK_CONSOLE_MES_02_01 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3155 65535 0]Questo posto era davvero[n]collegato al Palazzo alla fine.[n][w][e]

[msg CHECK_CONSOLE_MES_02_02 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Potr稲 sembrare assurdo,[n]ma 因 vero.[n][w][e]

[msg CHECK_CONSOLE_MES_02_03 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Abbiamo interrotto la connessione.[n]Qui non possiamo fare nulla, adesso.[n][w][e]

[msg CHECK_CONSOLE_MES_02_04 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Joker? Non c'因 altro che[n]possiamo fare...[n][w][e]

[msg Joze_imcomplete_stamp [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0]Ehi, salve.[n][w][e]
[s]Ho scoperto solo poco fa[n]questo percorso, ma sembra[n]terminare qui.[n][w][e]
[s]Con tutti questi schermi, la[n]stanza 因 inquietante... Sembra[n]un luogo per spiare gli umani.[n][w][e]
[s]Dopo tutta questa strada... Dopo[n]tutti quei fiori... Non so ancora[n]nulla degli umani.[n][w][e]

[msg Joze_Battle_reinvite [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0]Oh, signore.[n][w][e]
[s]Hai voglia di combattere con me[n]adesso?[n][w][e]

[sel SEL_fight_or_flight top]
[s]戦おう[e]
[s]今はやめておく[e]

[msg Joze_Battle_flight [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0]Oh, OK.[n][w][e]
[s]Poi torna quando sei pronto.[n]Ti aspetter韻...[n][w][e]

[msg Joze_Battle_fight [Jose]]
[s][bup 0 221 0 0 0][f 4 10 65535 0 0]Davvero? Grazie.[n][w][e]
[s]OK, ecco...[n][w][e]

