// ============================================================
// schemaUtente — le tabelle delle partite, nel loro file (partite.db, schema «utente»)
// ============================================================
//
// Decisione dell'utente (2026-09-12): i dati di gioco stanno in gioco.db e si manutengono con
// import/export; i dati delle partite stanno in un file a parte, così sostituire il DB di gioco
// non tocca l'avanzamento. Questa è la DDL completa e attuale delle tabelle delle partite, con i
// vincoli di chiave esterna verso le tabelle di gioco tolti (stanno in un altro file: SQLite non
// li può applicare); i vincoli fra tabelle delle partite restano, con le loro cascate.
//
// Serve in due punti: la migrazione 066 di gioco.db (che copia le righe dal vecchio file unico) e
// la migrazione 001 delle partite (un partite.db nuovo, per esempio dopo la sostituzione del DB di
// gioco). Le migrazioni successive delle partite stanno in migrazioniUtente/.
// ============================================================

import type { AppDatabase } from './dbService.js';

/** Le tabelle che vivono nel file delle partite, in ordine alfabetico. */
export const TABELLE_UTENTE = ["acquisto_partita","attivita_svolta_partita","azione_partita","azione_utente","azione_utente_partita","ciclo_salvato","compendio_partita","confidente_partita","cruciverba_partita","domanda_partita","dote_sociale_partita","effetto_lettura_partita","evento_partita","evento_storia_partita","evento_utente","lettura_partita","membro_squadra_partita","obiettivo_partita","partita","persona_posseduta","persona_posseduta_skill","piano_salvato","progresso_film_partita","progresso_libro_partita","progresso_videogioco_partita","punti_negozio_partita","punto_partita","regalo_partita","requisito_partita","richiesta_partita","spillo_partita","trofeo_partita"] as const;

/** DDL idempotente (IF NOT EXISTS) delle tabelle e degli indici delle partite, schema «utente». */
export const DDL_UTENTE: readonly string[] = [
  "CREATE TABLE IF NOT EXISTS utente.acquisto_partita (\n  partita_id       INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  articolo_chiave  TEXT NOT NULL,\n  updated_at       TEXT NOT NULL,\n  PRIMARY KEY (partita_id, articolo_chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.attivita_svolta_partita (\n        partita_id INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n        attivita_chiave TEXT NOT NULL,\n        volte INTEGER NOT NULL CHECK (volte >= 0),\n        updated_at TEXT NOT NULL,\n        PRIMARY KEY (partita_id, attivita_chiave)\n      );",
  "CREATE TABLE IF NOT EXISTS utente.azione_partita (\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  data        TEXT NOT NULL,\n  indice      INTEGER NOT NULL,\n  updated_at  TEXT NOT NULL, effetti_json TEXT,\n  PRIMARY KEY (partita_id, data, indice)\n);",
  "CREATE TABLE IF NOT EXISTS utente.azione_utente (\n  id                 INTEGER PRIMARY KEY,\n  partita_id         INTEGER REFERENCES partita(id) ON DELETE CASCADE,\n  data               TEXT NOT NULL,\n  fascia             TEXT NOT NULL DEFAULT 'giorno' CHECK (fascia IN ('giorno','sera')),\n  tipo               TEXT NOT NULL DEFAULT 'altro',\n  azione             TEXT NOT NULL,\n  riferimento_tipo   TEXT,\n  riferimento_chiave TEXT,\n  rango_atteso       INTEGER,\n  note               TEXT,\n  ordine             INTEGER NOT NULL DEFAULT 0,\n  created_at         TEXT NOT NULL,\n  updated_at         TEXT NOT NULL\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_azione_utente_data ON azione_utente(data, fascia, ordine);",
  "CREATE INDEX IF NOT EXISTS utente.idx_azione_utente_partita ON azione_utente(partita_id);",
  "CREATE TABLE IF NOT EXISTS utente.azione_utente_partita (\n  partita_id       INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  azione_utente_id INTEGER NOT NULL REFERENCES azione_utente(id) ON DELETE CASCADE,\n  fatta_at         TEXT NOT NULL,\n  effetti_json     TEXT,\n  PRIMARY KEY (partita_id, azione_utente_id)\n);",
  "CREATE TABLE IF NOT EXISTS utente.ciclo_salvato (\n  id              INTEGER PRIMARY KEY,\n  partita_id      INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  persona_id      INTEGER NOT NULL,\n  nome            TEXT NOT NULL DEFAULT '',\n  note            TEXT NOT NULL DEFAULT '',\n  anelli_json     TEXT NOT NULL,\n  costo           INTEGER NOT NULL DEFAULT 0,\n  iterazioni      INTEGER NOT NULL DEFAULT 0 CHECK (iterazioni >= 0),\n  anello_corrente INTEGER NOT NULL DEFAULT 0 CHECK (anello_corrente >= 0),\n  created_at      TEXT NOT NULL,\n  updated_at      TEXT NOT NULL\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_ciclo_salvato_partita ON ciclo_salvato(partita_id, id DESC);",
  "CREATE TABLE IF NOT EXISTS utente.compendio_partita (\n  partita_id          INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  persona_id          INTEGER NOT NULL,\n  registrata          INTEGER NOT NULL DEFAULT 1 CHECK (registrata IN (0,1)),\n  livello_registrato  INTEGER,\n  updated_at          TEXT NOT NULL, bonus_forza INTEGER NOT NULL DEFAULT 0, bonus_magia INTEGER NOT NULL DEFAULT 0, bonus_resistenza INTEGER NOT NULL DEFAULT 0, bonus_agilita INTEGER NOT NULL DEFAULT 0, bonus_fortuna INTEGER NOT NULL DEFAULT 0, skill_ids_json TEXT, tratto_skill_id INTEGER, carica INTEGER NOT NULL DEFAULT 0 CHECK (carica IN (0,1)), osservate_livello INTEGER, osservate_forza INTEGER, osservate_magia INTEGER, osservate_resistenza INTEGER, osservate_agilita INTEGER, osservate_fortuna INTEGER,\n  PRIMARY KEY (partita_id, persona_id)\n);",
  "CREATE TABLE IF NOT EXISTS utente.confidente_partita (\n  partita_id        INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  confidente_chiave TEXT NOT NULL,\n  sbloccato         INTEGER NOT NULL DEFAULT 0 CHECK (sbloccato IN (0,1)),\n  rango             INTEGER NOT NULL DEFAULT 0 CHECK (rango BETWEEN 0 AND 10),\n  note              TEXT NOT NULL DEFAULT '',\n  updated_at        TEXT NOT NULL, punti REAL NOT NULL DEFAULT 0 CHECK (punti >= 0),\n  PRIMARY KEY (partita_id, confidente_chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.cruciverba_partita (\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  data        TEXT NOT NULL,\n  updated_at  TEXT NOT NULL,\n  PRIMARY KEY (partita_id, data)\n);",
  "CREATE TABLE IF NOT EXISTS utente.domanda_partita (\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  domanda_id  INTEGER NOT NULL,\n  fatta_at    TEXT NOT NULL,\n  PRIMARY KEY (partita_id, domanda_id)\n);",
  "CREATE TABLE IF NOT EXISTS utente.dote_sociale_partita (\n  partita_id   INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  dote_chiave  TEXT NOT NULL,\n  punti        INTEGER NOT NULL DEFAULT 0 CHECK (punti >= 0),\n  updated_at   TEXT NOT NULL,\n  PRIMARY KEY (partita_id, dote_chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.effetto_lettura_partita (\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  tipo        TEXT NOT NULL,               -- 'libro' | 'film' | 'videogioco'\n  chiave      TEXT NOT NULL,\n  ordine      INTEGER NOT NULL,            -- 1 = primo conseguimento, 2 = secondo…\n  dote_chiave TEXT NOT NULL,\n  punti       INTEGER NOT NULL,\n  note        INTEGER NOT NULL,\n  updated_at  TEXT NOT NULL,\n  PRIMARY KEY (partita_id, tipo, chiave, ordine, dote_chiave)\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_effetto_lettura_partita ON effetto_lettura_partita(partita_id, tipo, chiave);",
  "CREATE TABLE IF NOT EXISTS utente.evento_partita (\n  id          INTEGER PRIMARY KEY,\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  tipo        TEXT NOT NULL,\n  titolo      TEXT NOT NULL,\n  dettaglio   TEXT NOT NULL DEFAULT '',\n  dati_json   TEXT NOT NULL DEFAULT '{}',\n  persona_id  INTEGER,\n  created_at  TEXT NOT NULL\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_evento_partita ON evento_partita(partita_id, id DESC);",
  "CREATE INDEX IF NOT EXISTS utente.idx_evento_partita_tipo ON evento_partita(partita_id, tipo, id DESC);",
  "CREATE INDEX IF NOT EXISTS utente.idx_evento_partita_persona ON evento_partita(partita_id, persona_id, id DESC);",
  "CREATE TABLE IF NOT EXISTS utente.evento_storia_partita (\n        partita_id INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n        evento_chiave TEXT NOT NULL,\n        avvenuto INTEGER NOT NULL DEFAULT 1 CHECK (avvenuto IN (0, 1)),\n        updated_at TEXT NOT NULL,\n        PRIMARY KEY (partita_id, evento_chiave)\n      );",
  "CREATE TABLE IF NOT EXISTS utente.evento_utente (\n  id                 INTEGER PRIMARY KEY,\n  partita_id         INTEGER REFERENCES partita(id) ON DELETE CASCADE,\n  data               TEXT NOT NULL,\n  tipo               TEXT NOT NULL DEFAULT 'evento' CHECK (tipo IN ('evento','scadenza','promemoria')),\n  titolo             TEXT NOT NULL,\n  dettaglio          TEXT NOT NULL DEFAULT '',\n  riferimento_tipo   TEXT,\n  riferimento_chiave TEXT,\n  ordine             INTEGER NOT NULL DEFAULT 0,\n  created_at         TEXT NOT NULL,\n  updated_at         TEXT NOT NULL\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_evento_utente_data ON evento_utente(data, ordine);",
  "CREATE INDEX IF NOT EXISTS utente.idx_evento_utente_partita ON evento_utente(partita_id);",
  "CREATE TABLE IF NOT EXISTS utente.lettura_partita (\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  tipo        TEXT NOT NULL CHECK (tipo IN ('libro','film')),\n  chiave      TEXT NOT NULL,\n  updated_at  TEXT NOT NULL,\n  PRIMARY KEY (partita_id, tipo, chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.membro_squadra_partita (\n  partita_id          INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  personaggio_chiave  TEXT NOT NULL,\n  livello             INTEGER NOT NULL DEFAULT 1,\n  esperienza          INTEGER NOT NULL DEFAULT 0,\n  updated_at          TEXT NOT NULL, in_squadra INTEGER NOT NULL DEFAULT 1 CHECK (in_squadra IN (0,1)),\n  PRIMARY KEY (partita_id, personaggio_chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.obiettivo_partita (\n  id            INTEGER PRIMARY KEY,\n  partita_id    INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  persona_id    INTEGER NOT NULL,\n  skill_json    TEXT NOT NULL DEFAULT '[]',\n  livello_min   INTEGER CHECK (livello_min BETWEEN 1 AND 99),\n  priorita      INTEGER NOT NULL DEFAULT 1 CHECK (priorita BETWEEN 0 AND 2),\n  stato         TEXT NOT NULL DEFAULT 'aperto' CHECK (stato IN ('aperto','raggiunto','annullato')),\n  note          TEXT NOT NULL DEFAULT '',\n  raggiunto_at  TEXT,\n  created_at    TEXT NOT NULL,\n  updated_at    TEXT NOT NULL\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_obiettivo_partita ON obiettivo_partita(partita_id, stato, priorita DESC, id);",
  "CREATE UNIQUE INDEX IF NOT EXISTS utente.idx_obiettivo_aperto_unico ON obiettivo_partita(partita_id, persona_id) WHERE stato = 'aperto';",
  "CREATE TABLE IF NOT EXISTS utente.partita (\n  id                    INTEGER PRIMARY KEY,\n  nome                  TEXT NOT NULL,\n  note                  TEXT NOT NULL DEFAULT '',\n  attiva                INTEGER NOT NULL DEFAULT 0 CHECK (attiva IN (0,1)),\n  livello_protagonista  INTEGER NOT NULL DEFAULT 1 CHECK (livello_protagonista BETWEEN 1 AND 99),\n  data_gioco            TEXT,                                   -- 'MM-GG' del calendario di gioco, opzionale\n  difficolta            TEXT NOT NULL DEFAULT 'normale'\n                        CHECK (difficolta IN ('sicura','facile','normale','difficile','spietata')),\n  nuova_partita_plus    INTEGER NOT NULL DEFAULT 0 CHECK (nuova_partita_plus IN (0,1)),\n  dlc_posseduti_json    TEXT NOT NULL DEFAULT '[]',             -- indici dei dlc_set posseduti\n  allarme_attivo        INTEGER NOT NULL DEFAULT 0 CHECK (allarme_attivo IN (0,1)),\n  created_at            TEXT NOT NULL,\n  updated_at            TEXT NOT NULL\n, fascia_gioco TEXT NOT NULL DEFAULT 'giorno', yen INTEGER NOT NULL DEFAULT 0);",
  "CREATE UNIQUE INDEX IF NOT EXISTS utente.idx_partita_attiva ON partita(attiva) WHERE attiva = 1;",
  "CREATE TABLE IF NOT EXISTS utente.persona_posseduta (\n  id                INTEGER PRIMARY KEY,\n  partita_id        INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  persona_id        INTEGER NOT NULL,\n  livello           INTEGER NOT NULL CHECK (livello BETWEEN 1 AND 99),\n  forza             INTEGER,                                    -- statistiche attuali (NULL = base della Persona)\n  magia             INTEGER,\n  resistenza        INTEGER,\n  agilita           INTEGER,\n  fortuna           INTEGER,\n  tratto_skill_id   INTEGER,   -- NULL = tratto proprio\n  in_squadra        INTEGER NOT NULL DEFAULT 1 CHECK (in_squadra IN (0,1)),\n  note              TEXT NOT NULL DEFAULT '',\n  created_at        TEXT NOT NULL,\n  updated_at        TEXT NOT NULL, carica INTEGER NOT NULL DEFAULT 0 CHECK (carica IN (0,1)), bonus_forza INTEGER NOT NULL DEFAULT 0, bonus_magia INTEGER NOT NULL DEFAULT 0, bonus_resistenza INTEGER NOT NULL DEFAULT 0, bonus_agilita INTEGER NOT NULL DEFAULT 0, bonus_fortuna INTEGER NOT NULL DEFAULT 0, osservate_livello INTEGER, osservate_forza INTEGER, osservate_magia INTEGER, osservate_resistenza INTEGER, osservate_agilita INTEGER, osservate_fortuna INTEGER,\n  UNIQUE (partita_id, persona_id)\n);",
  "CREATE TABLE IF NOT EXISTS utente.persona_posseduta_skill (\n  posseduta_id  INTEGER NOT NULL REFERENCES persona_posseduta(id) ON DELETE CASCADE,\n  slot          INTEGER NOT NULL CHECK (slot BETWEEN 1 AND 8),\n  skill_id      INTEGER NOT NULL,\n  PRIMARY KEY (posseduta_id, slot),\n  UNIQUE (posseduta_id, skill_id)\n);",
  "CREATE TABLE IF NOT EXISTS utente.piano_salvato (\n  id            INTEGER PRIMARY KEY,\n  partita_id    INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  persona_id    INTEGER NOT NULL,\n  obiettivo_id  INTEGER REFERENCES obiettivo_partita(id) ON DELETE SET NULL,\n  nome          TEXT NOT NULL DEFAULT '',\n  note          TEXT NOT NULL DEFAULT '',\n  opzioni_json  TEXT NOT NULL DEFAULT '{}',\n  skill_json    TEXT NOT NULL DEFAULT '[]',\n  piano_json    TEXT NOT NULL,\n  costo         INTEGER NOT NULL DEFAULT 0,\n  created_at    TEXT NOT NULL,\n  updated_at    TEXT NOT NULL\n);",
  "CREATE INDEX IF NOT EXISTS utente.idx_piano_salvato_partita ON piano_salvato(partita_id, id DESC);",
  "CREATE INDEX IF NOT EXISTS utente.idx_piano_salvato_obiettivo ON piano_salvato(obiettivo_id);",
  "CREATE TABLE IF NOT EXISTS utente.progresso_film_partita (\n        partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n        film_chiave TEXT NOT NULL,\n        avanzamento INTEGER NOT NULL CHECK (avanzamento >= 1),\n        updated_at  TEXT NOT NULL,\n        PRIMARY KEY (partita_id, film_chiave)\n      );",
  "CREATE TABLE IF NOT EXISTS utente.progresso_libro_partita (\n        partita_id   INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n        libro_chiave TEXT NOT NULL,\n        avanzamento  INTEGER NOT NULL CHECK (avanzamento >= 1),\n        updated_at   TEXT NOT NULL,\n        PRIMARY KEY (partita_id, libro_chiave)\n      );",
  "CREATE TABLE IF NOT EXISTS utente.progresso_videogioco_partita (\n        partita_id INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n        videogioco_chiave TEXT NOT NULL,\n        avanzamento INTEGER NOT NULL CHECK (avanzamento >= 1),\n        updated_at TEXT NOT NULL,\n        PRIMARY KEY (partita_id, videogioco_chiave)\n      );",
  "CREATE TABLE IF NOT EXISTS utente.punti_negozio_partita (\n        partita_id INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n        negozio_chiave TEXT NOT NULL,\n        punti INTEGER NOT NULL CHECK (punti >= 0),\n        updated_at TEXT NOT NULL,\n        PRIMARY KEY (partita_id, negozio_chiave)\n      );",
  "CREATE TABLE IF NOT EXISTS utente.punto_partita (\n  partita_id    INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  punto_chiave  TEXT NOT NULL,\n  stato         TEXT NOT NULL CHECK (stato IN ('ottenuto','esaurito')),\n  updated_at    TEXT NOT NULL,\n  PRIMARY KEY (partita_id, punto_chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.regalo_partita (\n  partita_id        INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  confidente_chiave TEXT NOT NULL,\n  regalo            TEXT NOT NULL,\n  fatto_at          TEXT NOT NULL,\n  PRIMARY KEY (partita_id, confidente_chiave, regalo)\n);",
  "CREATE TABLE IF NOT EXISTS utente.requisito_partita (\n  partita_id         INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  confidente_chiave  TEXT NOT NULL,\n  rango              REAL NOT NULL,\n  indice             INTEGER NOT NULL,\n  confermato         INTEGER NOT NULL DEFAULT 0 CHECK (confermato IN (0,1)),\n  updated_at         TEXT NOT NULL,\n  PRIMARY KEY (partita_id, confidente_chiave, rango, indice)\n);",
  "CREATE TABLE IF NOT EXISTS utente.richiesta_partita (\n  partita_id        INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  richiesta_chiave  TEXT NOT NULL,\n  stato             TEXT NOT NULL CHECK (stato IN ('accettata','completata')),\n  updated_at        TEXT NOT NULL,\n  PRIMARY KEY (partita_id, richiesta_chiave)\n);",
  "CREATE TABLE IF NOT EXISTS utente.spillo_partita (\n  partita_id  INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  spillo_id   INTEGER NOT NULL,\n  raccolto    INTEGER NOT NULL DEFAULT 0 CHECK (raccolto IN (0,1)),\n  updated_at  TEXT NOT NULL,\n  PRIMARY KEY (partita_id, spillo_id)\n);",
  "CREATE TABLE IF NOT EXISTS utente.trofeo_partita (\n  partita_id     INTEGER NOT NULL REFERENCES partita(id) ON DELETE CASCADE,\n  trofeo_chiave  TEXT NOT NULL,\n  updated_at     TEXT NOT NULL,\n  PRIMARY KEY (partita_id, trofeo_chiave)\n);",
];

/** Crea le tabelle delle partite che mancano nello schema «utente». */
export function creaSchemaUtente(db: AppDatabase): void {
  for (const sql of DDL_UTENTE) db.exec(sql);
}
