import json,sqlite3,collections,hashlib
from pathlib import Path
out=Path('outputs/mappe-p5r/app-integration')
audit=json.loads((out/'audit-pulizia-globale.json').read_text(encoding='utf-8'))
db=sqlite3.connect(Path('work/runtime-atlante/project-p5r.db').resolve().as_uri()+'?mode=ro',uri=True);db.row_factory=sqlite3.Row
tables={r[0]:r[1] for r in db.execute("SELECT name,sql FROM sqlite_master WHERE type='table'")}
snapshot={name:[dict(r) for r in db.execute('SELECT * FROM "'+name+'"')] for name,sql in tables.items() if sql and ('mappa' in sql.lower() or 'spillo' in sql.lower())}
# Membership comes from the actual title records in texelem, not from the name of an archive folder.
canonical={'Palazzo di Kamoshida':'kamoshida','Palazzo di Madarame':'madarame','Palazzo di Kaneshiro':'kaneshiro','Palazzo di Futaba':'futaba','Palazzo di Okumura':'okumura','Palazzo di Niijima':'niijima','Palazzo di Shido':'shido','Palazzo di Maruki':'maruki'}
roots=[]
for key in sorted({int(m['code'].split('_')[1]) for m in audit['native']}):
 records=[e for m in audit['native'] if int(m['code'].split('_')[1])==key for e in m['evidence'] if e['group'] not in ('???','NULL','')]
 groups=set(e['group'] for e in records)
 if len(groups)!=1 or next(iter(groups)) not in canonical:continue
 group=next(iter(groups));source='nativo-archivio-'+str(key).zfill(3);target='dungeon-'+canonical[group]
 if not any(m['chiave']==source for m in snapshot['mappa']):continue
 children=[m['chiave'] for m in snapshot['mappa'] if m['genitore_chiave']==source]
 roots.append(dict(source=source,target=target,title=group,evidence=records,children=children))
renames=[dict(key='nativo-'+m['code'].lower().replace('_','-'),title=m['nativeTitles'][0],evidence=m['evidence']) for m in audit['native'] if len(m['nativeTitles'])==1]
conflicts=collections.defaultdict(list)
for n in renames:conflicts[n['title']].append(n['key'])
report=dict(roots=roots,renames=renames,snapshot=snapshot,schema=tables,repeatedNames={k:v for k,v in conflicts.items() if len(v)>1},policy={'sameName':'Not duplicate evidence. Preserve every image and resource variant. Stable internal IDs disambiguate URLs only; readable display names can repeat.','seed':'Archive roots are user package nodes, not generated by sincronizzaMappe. Exporter must stop recreating merged roots. Legacy semantic areas remain until evidence-based per-area replacement can preserve their POIs; deleting them by name is forbidden.','merge':'Transaction: reparent children; transfer every FK reference, spillo map refs, aliases and destination records to canonical target; preserve user notes and root images or reject ambiguous merge; no canvas pin copying without transform.','verification':'Copy DB, execute transformation, compare references/images/pin IDs and partita states; rerun seed; no merged roots restored. Then apply live with backup.'})
(out/'piano-pulizia-globale.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(dict(roots=[{k:v for k,v in r.items() if k!='evidence'} for r in roots],renames=len(renames),sameNameGroups=len(report['repeatedNames']),tables={k:len(v) for k,v in snapshot.items()}),ensure_ascii=False))
